### ISSUE TITLE
Newline inserted after initializer list in function call

### ISSUE THREAD

**Issue by jlee975** [uncrustify/uncrustify#1000]
Expect to be one line:

```
v.push_back({ 2, 3.0 });
```

See braceinparen.cpp, braceinparen.cpp.uncrustify, braceinparen.debug in https://github.com/jlee975/uncrustify-tests

Using uncrustify v0.64_d 1f538888ad9b3adc8a46828ebe2ad6578629df29

**Comment by CDanU** [comment]
This is caused by "nl_brace_fparen = force".

It does what it should:
> nl_brace_fparen: Add or remove newline between '}' and ')' in a function invocation

I:
```cpp
int main()
{
	// Newline inserted between '}' and ')'
	v.push_back({ 2, 3.0 });
}
```
O:
```cpp
int main()
{
	// Newline inserted between '}' and ')'
	v.push_back({ 2, 3.0 }
	            );
}
```

**Comment by jlee975** [comment]
Thanks, I didn't catch that option.

It would be nice, however, if there were a symmetric option. i.e., to handle the newline between '(' and '{'. I don't see such a thing.
