### ISSUE TITLE
Space lost before colon in class specialization

### ISSUE THREAD

**Issue by jlee975** [uncrustify/uncrustify#1001]
But not for unspecialized class definition

```
template< >
struct Bar< false > : Foo
{
};
```

See colon.cpp, colon.cpp.uncrustify, colon.debug in https://github.com/jlee975/uncrustify-tests

Using uncrustify v0.64_d 1f538888ad9b3adc8a46828ebe2ad6578629df29

**Comment by CDanU** [comment]
C:
```sql
# Uncrustify 0.64.414-g06cfd174
sp_after_angle                  = remove
sp_before_class_colon           = force
# option(s) with 'not default' value: 2
#
```
I:
```cpp
// Has space before colon
template< bool B >
struct Bar : Foo
{
};

// Space before colon is removed
template< >
struct Bar< false > : Foo
{
};
```
O:
```cpp
// Has space before colon
template< bool B >
struct Bar : Foo
{
};

// Space before colon is removed
template< >
struct Bar< false >: Foo
{
};
```

**Comment by jlee975** [comment]
Can the sp_before_class_colon take precedence? My reasoning would be that it is a more specific match. I'm thinking of something like CSS where conflicts are resolved this way.

**Comment by guy-maurel** [comment]
Do we have any cases which are *not* template?

**Comment by guy-maurel** [comment]
Can you please push a new complete example?

**Comment by jlee975** [comment]
To answer your question from Feb 24, no I don't have a non-template example.

I don't think I have anything to add to what @CDanU said either: the options are contradictory. The code produces

```
template< >
struct Bar< false >: Foo
{
};
```

but I expected to have a space before the colon:
```
template< >
struct Bar< false > : Foo
{
};
```

Don't know that there's a "correct" version or to break the ambiguity.

**Comment by guy-maurel** [comment]
The work is done in space.cpp, line 127, the function do_space.
The options are programmed at:
sp_after_angle at line 836
sp_before_class_colon at line 1434.
The first one as a precedence on the second one.
There are some more situations as this one.
There is no way for your example.

**Comment by gmaurel** [comment]
I will introduce a new option.

**Comment by guy-maurel** [comment]
#1382 is a bugfix proposal.
Please test and report.
