### ISSUE TITLE
Lose space before && in template

### ISSUE THREAD

**Issue by jlee975** [uncrustify/uncrustify#1002]
But not in the definition of value

```
template< class B1 = void, class B2 = void >
struct conjunction : foo< B1::value && B2::value >
{
	static const bool value = B1::value && B2::value;
};
```

See conditional.cpp, conditional.cpp.uncrustify, conditional.debug in https://github.com/jlee975/uncrustify-tests

Using uncrustify v0.64_d 1f538888ad9b3adc8a46828ebe2ad6578629df29

**Comment by CDanU** [comment]
This is caused by `sp_before_byref = remove`. 

I am not entirely sure what the `&&` in
```cpp
struct conjunction : foo< B1::value && B2::value >
```
are supposed to mean.

**Comment by jlee975** [comment]
It's boolean AND, just as if it were in (true && false).

**Comment by guy-maurel** [comment]
Could please push a complete example. I would like to compile and run it.

**Comment by jlee975** [comment]
I"ve updated conditional.cpp, etc in https://github.com/jlee975/uncrustify-tests

It is a simple implementation of std::conjunction from C++17

**Comment by guy-maurel** [comment]
We don't support C++17 now.
But, if you want to join us, we will be very happy.

**Comment by jlee975** [comment]
Sorry, that's not what I meant. The code will compile under C++03.

I maintain a project (cppbackport) that implements C++11/14/17 stuff in C++03, so that's ultimately where it came from. I was just mentioning what the code does, if you were going to run it.

**Comment by guy-maurel** [comment]
http://en.cppreference.com/w/cpp/types/conjunction shows:
 _template<class... B>
struct conjunction;
	(1) 	(since C++17)_
We take it in the TODO list

**Comment by jlee975** [comment]
Sorry, I think the use of conjunction has confused things. The issue doesn't really have anything to do with std::conjunction except that I chose to use it for the example.

The issue is that for

```
struct conjunction : foo< B1::value && B2::value >
```

the && is formatted with sp_before_byref/sp_after_byref when it should be sp_arith

**Comment by guy-maurel** [comment]
A proposal is PR#1141

**Comment by gmaurel** [comment]
is fixed

**Comment by jlee975** [comment]
Thanks for your help with this
