### ISSUE TITLE
Delegating constructor treated differently than member initialization

### ISSUE THREAD

**Issue by jlee975** [uncrustify/uncrustify#1003]
Foo is not split across several lines, but Bar is:

```
class Bar
{
public:
	// Splits 3,5 onto newlines
	Bar() : Bar(3, 5)
	{
	}

	// No split here
	Bar(
		int x,
		int y
	) : Foo(x, y)
	{
	}

	Foo foo;
};
```

See delegatingctor.cpp, delegatingctor.cpp.uncrustify, delegatingctor.debug in https://github.com/jlee975/uncrustify-tests

Using uncrustify v0.64_d 1f538888ad9b3adc8a46828ebe2ad6578629df29

**Comment by CDanU** [comment]
Those should be the options affected by this:

```sql
# Uncrustify 0.64.414-g06cfd174
nl_func_def_start               = force
nl_func_def_args                = force
nl_func_def_end                 = force
# option(s) with 'not default' value: 3
#
```

Reducing the input to down to:
```cpp
class Bar
{
	Bar() : Bar(3, 5)
	{
	}


	Bar() : Foo(3, 4)
	{
	}
};
```
Creates this output:
```cpp
class Bar
{
Bar() : Bar(
		3,
		5
		)
{
}


Bar() : Foo(3, 4)
{
}
};
```

**Comment by guy-maurel** [comment]
What is the expected result?

**Comment by jlee975** [comment]
Bar(3,5) should be styled the same as Foo(3, 4). Instead, Bar(3,5) is being recognized as a constructor definition and nl_func_def_xxx settings kick in.

**Comment by gmaurel** [comment]
Please as a source I could compare with.

**Comment by CDanU** [comment]
> Instead, Bar(3,5) is being recognized as a constructor definition and nl_func_def_xxx settings kick in.

Ahh, I just now see that this is a new C++11 feature, the [Delegating_constructor](http://en.cppreference.com/w/cpp/language/initializer_list#Delegating_constructor). Without giving to much thought of the example file name I assumed that the nl_func_def_xxx options had to be applied to `Foo` (which would be wrong anyway as Foo and Bar are no function definitions).

------------------------

I tried to make the example you provided compilable but that would need to change Foo(3, 4) to foo(Foo(3,4))

```cpp
#include <iostream>

using namespace std;

class Foo
{
public:
    int x;
    int y;

    Foo(int x_, int y_) : x(x_), y(y_)
    {
    }
};

class Bar
{
public:
    // Splits 3,5 onto newlines
    Bar() : Bar(3, 5)
    {
    }

    // No split here
    Bar(int x, int y) : foo(Foo(x, y))
    {
    }
    Foo foo;
};

int main()
{
   Bar b;
   cout << b.foo.x << b.foo.y << endl;
}
```

Running that through Uncrustify with this config:

```sql
# Uncrustify 0.64.500-g3f3861fa-dirty
nl_func_def_start               = force
nl_func_def_args                = force
nl_func_def_end                 = force
# option(s) with 'not default' value: 3
#
```

Generates this:
```cpp
#include <iostream>

using namespace std;

class Foo
{
public:
int x;
int y;

Foo(
	int x_,
	int y_
	) : x(x_), y(y_)
{
}
};

class Bar
{
public:
// Splits 3,5 onto newlines
Bar() : Bar(
		3,
		5
		)
{
}

// No split here
Bar(
	int x,
	int y
	) : foo(Foo(x, y))
{
}
Foo foo;
};

int main()
{
	Bar b;
	cout << b.foo.x << b.foo.y << endl;
}
```

Which should be this:
```cpp
#include <iostream>

using namespace std;

class Foo
{
public:
int x;
int y;

Foo(
	int x_,
	int y_
	) : x(x_), y(y_)
{
}
};

class Bar
{
public:
// Splits 3,5 onto newlines
Bar() : Bar(3, 5)
{
}

// No split here
Bar(
	int x,
	int y
	) : foo(Foo(x, y))
{
}
Foo foo;
};

int main()
{
	Bar b;
	cout << b.foo.x << b.foo.y << endl;
}
```

**Comment by guy-maurel** [comment]
@jlee975 : could you test again and report?

**Comment by jlee975** [comment]
Still has the problem. Used uncrustify sha e1181d3b3a78ef9fe0f52af53678fdf3340233c5 from 2 hours ago.

O:
```
    Bar() : Bar(
            3,
            5
    )
    {
    }
```

E:
```
    Bar() : Bar(3, 5)
    {
    }
```

Updated delegatingctor.cpp, delegatingctor.cpp.uncrustify, delegatingctor.debug in https://github.com/jlee975/uncrustify-tests

**Comment by guy-maurel** [comment]
I am working on it.

**Comment by guy-maurel** [comment]
#1193 is a proposal for a bugfix. Please test and report.

**Comment by gmaurel** [comment]
The bug is fixed
