### ISSUE TITLE
Multiplication followed by dereference is not treated as such

### ISSUE THREAD

**Issue by jlee975** [uncrustify/uncrustify#1004]
The following two asterisks are globbed together, but are spaced when appearing on their own.

```
int a = b * *p;
```

See doublestar.cpp, doublestar.cpp.uncrustify, doublestar.debug in https://github.com/jlee975/uncrustify-tests

Using uncrustify v0.64_d 1f538888ad9b3adc8a46828ebe2ad6578629df29

**Comment by guy-maurel** [comment]
for just now, you can protect the operation with
```
int a = b * (*p);

```

**Comment by gmaurel** [comment]
The bug is fixed.
Thanks for the message.

**Comment by jlee975** [comment]
Thanks for the fix
