### ISSUE TITLE
Lose the space before global scope operator in friend

### ISSUE THREAD

**Issue by jlee975** [uncrustify/uncrustify#1005]
Space is kept elsewhere in the code:

```
friend void ::test::swap< >(future< T >&, future< T >&);
```

See friend.cpp, friend.cpp.uncrustify, friend.debug in https://github.com/jlee975/uncrustify-tests

Using uncrustify v0.64_d 1f538888ad9b3adc8a46828ebe2ad6578629df29

**Comment by CDanU** [comment]
This also seems to be caused by `sp_before_dc = remove`. 
Additionally `sp_angle_paren_empty = remove` also does not work.

**Comment by gmaurel** [comment]
The bug is fixed

**Comment by jlee975** [comment]
Thanks
