### ISSUE TITLE
access declarations in nested class are aligned to parent

### ISSUE THREAD

**Issue by jlee975** [uncrustify/uncrustify#1006]
Expect to align to self

```
class Out
{
public:
	class In
	{
	// public and private should be aligned to class
	public:
	private:
	};
};
```

See nested.cpp, nested.cpp.uncrustify, nested.debug in https://github.com/jlee975/uncrustify-tests

Using uncrustify v0.64_d 1f538888ad9b3adc8a46828ebe2ad6578629df29

**Comment by CDanU** [comment]
You get your expected results with 

C:
```sql
# Uncrustify 0.64.414-g06cfd174
indent_class                    = false
indent_access_spec_body         = true
# option(s) with 'not default' value: 2
```
I:
```cpp
class Out
{
public:
	class In
	{
	// public and private should be aligned to class
	public:
	private:
	};
};
```
O:
```cpp
class Out
{
public:
	class In
	{
	// public and private should be aligned to class
	public:
	private:
	};
};
```


But I am not sure if the combination of both of this settings does what it should.

**Comment by jlee975** [comment]
If I do that, on a larger example, I get weird behaviour where some things are indented and some aren't.

I:
```
class Out
{
// Comment 1
typedef int test1;
public:
// Comment 2
typedef int test2;

        class In
        {
        // public and private should be aligned to class
        public:
        private:
        };
};
```

O:
```
class Out
{
// Comment 1
typedef int test1;
public:
// Comment 2
        typedef int test2;

        class In
        {
        // public and private should be aligned to class
        public:
        private:
        };
};
```

**Comment by jlee975** [comment]
I think indent_class = true is what I want. The comments and both typedefs "ought" to be indented.

**Comment by guy-maurel** [comment]
What you need is:
```
indent_col1_comment              = true
```
Please try and report.

**Comment by jlee975** [comment]
That fixes one comment, but not both. Updated repo with results. Trying
```
indent_class                    = false
indent_access_spec_body         = true
indent_col1_comment              = true
```

I:
```
class Out
{
// Comment 1
typedef int test1;
public:
// Comment 2
typedef int test2;

        class In
        {
        // public and private should be aligned to class
        public:
        typedef int test3;
        private:
        };
};
```

O:
```
class Out
{
// Comment 1
typedef int test1;
public:
        // Comment 2
        typedef int test2;

        class In
        {
        // public and private should be aligned to class
        public:
                typedef int test3;
        private:
        };
};
```

**Comment by guy-maurel** [comment]
Your config file contains ```indent_access_spec_body         = true```
... Indent the code after an access specifier by one level. ...
Exactly what it is doing!

**Comment by jlee975** [comment]
That's what I was told to do above

**Comment by CDanU** [comment]
As far as I know only those three options are relevant for this issue:
- indent_class
- indent_access_spec_body
- indent_col1_comment

I have generated all possible combinations of this three and applied them on your last. No combination generates what you need. 

The closes one is generated with
```sql
indent_class = False
indent_access_spec_body = True
indent_col1_comment = True
```

This will need either some changes or a new option.

**Comment by jlee975** [comment]
I think there are now two issues getting confused.

My original issue was that the access specifiers weren't getting aligned to their class if the class was nested (but rather to the parent). So in the original I had indent_class=true and indent_access_spec_body=false. With these settings, I expected the nested class to be indented (it was) and that *it's* access specifiers to be indented to the same level (they weren't).

The second issue popped up when I added the typedefs and comments. I really just put them in there to highlight that I really did want indent_class=true, and stumbled upon the weird indenting. I think you may want to open a separate issue for that.

**Comment by jlee975** [comment]
K I was able to dig into the code a bit and I think the relevant code is indent.cpp:1491.

There, the access specifier is sent to column 1 (as per indent_access_spec). To me, this should really be relative to the class' indent, not the literal first column. I'm sorry, I'm not sure how to access the containing class' indent or I'd submit a patch for you to consider.

**Comment by jlee975** [comment]
Nevermind, after all that it seems if I set indent_access_spec to 0 I get exactly what I want. As per the documentation. Closing.
