### ISSUE TITLE
Newline lost in templated cast member function

### ISSUE THREAD

**Issue by jlee975** [uncrustify/uncrustify#1008]
New line deleted before operator, but not in equivalent
(named) member function 

```
	template< class T >
	operator T*() const
	{
		return 0;
	}
```

See operator2.cpp, operator2.cpp.uncrustify, operator2.debug in https://github.com/jlee975/uncrustify-tests

Using uncrustify v0.64_d 1f538888ad9b3adc8a46828ebe2ad6578629df29

**Comment by CDanU** [comment]
Thanks for the repo of uncrustify failures. Is going to take some time to go through all of those :)

**Comment by jlee975** [comment]
I appreciate you looking into it. Sorry to dump 10 bugs on you all at once. I was hoping to fix them myself, but haven't found the time.

I guess I would say nl_func_type_name shouldn't apply here because the "return type" and "function name" are essentially the same thing.

**Comment by guy-maurel** [comment]
May we close the call?

**Comment by CDanU** [comment]
No, my PR mentioned this issue but did not fix it.

**Comment by CDanU** [comment]
@jlee975 Could you test if the changes do what you need?

**Comment by jlee975** [comment]
Seems to work now. Thanks!
