### ISSUE TITLE
Unpack operator treated like var args

### ISSUE THREAD

**Issue by jlee975** [uncrustify/uncrustify#1009]
Seems to treat ... as an argument and inserts spaces before

```
template< class... Args >
std::vector< T > emplace(Args&&... args)
{

	std::vector< T > v(std::forward< Args >(args)...);
	return v;
}
```

See unpack.cpp, unpack.cpp.uncrustify, unpack.debug in https://github.com/jlee975/uncrustify-tests

Using uncrustify v0.64_d 1f538888ad9b3adc8a46828ebe2ad6578629df29

**Comment by guy-maurel** [comment]
First line can be controlled with:
```
sp_before_ellipsis = REMOVE
```
Second and fifth lines: there are no option yet.
Please make a name proposal for them.
They could be added.

**Comment by gmaurel** [comment]
And now? Anything to report?

**Comment by jlee975** [comment]
If it were me, I'd rename sp_before_ellipsis to sp_before_vararg. Applicable only in a parameter list of a function:
```
void myfunc(int arg1, int arg2, ...);
```

That ellipsis has a different meaning than these:
```
template< class... Args >
std::vector< T > emplace(Args&&... args)
{

	std::vector< T > v(std::forward< Args >(args)...);
	return v;
}
```

Which are for the C++11 feature [parameter pack expansion](http://en.cppreference.com/w/cpp/language/parameter_pack)

I guess a good name would be sp_before_param_pack_exp (?)

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
