### ISSUE TITLE
Add option to enforce braces in If/for/while/.. code blocks

### ISSUE THREAD

**Issue by trufae** [uncrustify/uncrustify#1016]
input:
```
int main(int argc) {
if (argc> 2) printf ("Winrar\n");
}
```

expected output:

```
int main(int argc) {
    if (argc > 2) {
      printf ("Winrar\n");
   }
}
```

**Comment by CDanU** [comment]
Try:

mod_full_brace_do
mod_full_brace_for
mod_full_brace_function
mod_full_brace_if
mod_full_brace_if_chain
mod_full_brace_if_chain_only
    mod_full_brace_if_chain
mod_full_brace_nl
mod_full_brace_while
mod_full_brace_using

**Comment by trufae** [comment]
doesnt works

**Comment by CDanU** [comment]
To get exactly your expected result:
```sql
# Uncrustify 0.64.414-g06cfd174
nl_if_brace                     = remove
mod_full_brace_if               = force
# option(s) with 'not default' value: 2
#
```
Input
```cpp
int main(int argc) {
	if (argc> 2) printf ("Winrar\n");
}
```

Output
```cpp
int main(int argc) {
	if (argc> 2) {
		printf ("Winrar\n");
	}
}
```

**Comment by trufae** [comment]
why its not working for me?

im using uncrustify from git and using a file with those 2 lines passed to uncrustify -c uncrustify.cfg foo.c

and the foo.c.uncrustify doesnt have this output

**Comment by trufae** [comment]
nvm. that works!  thanks!
