### ISSUE TITLE
alignment of function parameters with defaults

### ISSUE THREAD

**Issue by wisealex2** [uncrustify/uncrustify#1020]
Hi. Thanks for the very good tool!
 
i ran into an issue with function params alignment with func_split_full
for params without defaults formatting works fine (each param on a separate line), 
but i add defaults formatting is broken - i see several params per line.
here is the result:
void HouseNumberData(Translation const & trans  = Translation { }, Orientation const & orient = Orientation { },
                     CategoryIds const & cats   = CategoryIds(), std::string const & txt    = std::string { }, bool  active = false);

void HouseNumberData(Translation const & trans______________,
                     Orientation const & orient______________________,
                     CategoryIds const & cats_____________________,
                     std::string const & txt___________________,
                     bool active_________);
how to split params with defaults in the same way as params without defaults?

in archive debug.txt, input and output files
[Archive.zip](https://github.com/uncrustify/uncrustify/files/776466/Archive.zip)
version 0.64

Thanks

**Comment by CDanU** [comment]
I can confirm this.

Minimal config:
```sql
code_width                      = 190
ls_func_split_full              = true
```

**Comment by gmaurel** [comment]
The bug is fixed
