### ISSUE TITLE
Coverity Integration Badge

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1022]
As mentioned in #940 and #538 we are already using coverity but we're missing the badge. Surprisingly the old [uncrustify sourceforge project website](http://uncrustify.sourceforge.net/) has it. Maybe we can put it in our README as well. What do you think ?

**Comment by guy-maurel** [comment]
Yes, coverity is fine.

**Comment by guy-maurel** [comment]
@dirk-thomas Could you do it?
