### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1026]
The file uncrustify_emscripten.cpp should contain informations for all the options.
If some one create a new option, I miss a dependency (CMakeLists.txt) with
options.h and options.cpp.
Could we have a script to generate uncrustify_emscripten.cpp ?

**Comment by CDanU** [comment]
Most of what can be automated can be generated with `scripts/genEmscriptenEnumBindingCode.sh`. 
This script generates output for the various enum bindings. This output has to be manually applied to the `uncrustify_emscripten.cpp` file.

I also have a [branch](https://github.com/CDanU/uncrustify/tree/emscripten_update) with updates and fiexes that is going into a PR sometimes _soon_-ish.
