### ISSUE TITLE
Space after pointer star in function declaration / definition

### ISSUE THREAD

**Issue by dm0** [uncrustify/uncrustify#1027]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
Hello, 

uncrustify doesn't handle well a situation when class member returns pointer to a templated type.

Gist with [debug.txt](https://gist.githubusercontent.com/dm0/c15b72858f32114815fc9b40235ccd38/raw/1e74988a54ebf4a549fbcdf8554b3ff9eb0fe493/uncrustify-ptr-star-debug.txt) and [sample.cpp](https://gist.githubusercontent.com/dm0/c15b72858f32114815fc9b40235ccd38/raw/1e74988a54ebf4a549fbcdf8554b3ff9eb0fe493/sample.cpp): [https://gist.github.com/dm0/c15b72858f32114815fc9b40235ccd38](https://gist.github.com/dm0/c15b72858f32114815fc9b40235ccd38)

Sample code: 
```cpp
int * fn1();
mytype * fn2();
myttype<float> * fn3();
myttype<float> * myclass::fn4();
myttype * myclass::fn5();
```

Generated output:
```cpp
int * fn1();
mytype * fn2();
myttype<float> * fn3();
myttype<float> *myclass::fn4();
myttype * myclass::fn5();
```

Expected output should be the same as input. Please note that there is no space between pointer star and method name in the fourth line of generated output.

Uncrustify version:
```
> uncrustify -v
uncrustify 0.64
```

**Comment by CDanU** [comment]
I can confirm this.  The issue is caused by `sp_after_ptr_star               = remove`

**Comment by gmaurel** [comment]
The bug is fixed.
