### ISSUE TITLE
interpretation of - as sign vs minus

### ISSUE THREAD

**Issue by stleusc** [uncrustify/uncrustify#1031]
[uncrustify.cfg](http://pastebin.com/Gk3qvjnH)

input
```C
#if ((DUMMY) >= 1) && ((DUMMY) <= 8)
    #define NEW_DUMMY    ((DUMMY) - 1u)
#endif
```

gets formatted as

```C
#if ((DUMMY) >= 1) && ((DUMMY) <= 8)
    #define NEW_DUMMY    ((DUMMY)-1u)
#endif
```
but the - is not sign but a minus and DUMMY is not a typecast

using latest released version.

Not sure if you can detect the difference between subtraction and typecast here.

**Comment by guy-maurel** [comment]
Parsing in macro is long not perfect

**Comment by gmaurel** [comment]
uncrustify cannot anderstand what `DUMMY` is.
A compiler would be necessary for that.
The bug cannot be solved.
