### ISSUE TITLE
Template angle brackets are parsed as compare operators when used inside square brackets

### ISSUE THREAD

**Issue by dm0** [uncrustify/uncrustify#1032]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Hello,

Template angle brackets are parsed as compare operators when used inside square brackets

Gist with [debug.txt](https://gist.githubusercontent.com/dm0/728a4fb84dfe5b66e619db6910e86492/raw/c705f5225377471edb0e8ee6b09202aae16c45b7/debug.txt) and [sample.cpp](https://gist.githubusercontent.com/dm0/728a4fb84dfe5b66e619db6910e86492/raw/c705f5225377471edb0e8ee6b09202aae16c45b7/sample.cpp): [https://gist.github.com/dm0/728a4fb84dfe5b66e619db6910e86492](https://gist.github.com/dm0/728a4fb84dfe5b66e619db6910e86492)

Sample code:
```cpp
Type variable = items_array[index<int>()];
Type variable = index<int>();
Type variable = Nested<index<int>()>();
Type variable = myfn(index<int>());
```

Generated output
```cpp
Type variable = items_array[index < int > ()];
Type variable = index<int>();
Type variable = Nested<index<int>()>();
Type variable = myfn(index<int>());
```

Expected output is the same as input. Spaces around angle brackets in the first line are caused by `sp_compare=force` option.

Uncrustify version:
```
> uncrustify -v
uncrustify 0.64
```

Thanks!

**Comment by guy-maurel** [comment]
I need a complete source I would like to compile.
Can you push it?

**Comment by dm0** [comment]
I've updated the [gist](https://gist.github.com/dm0/728a4fb84dfe5b66e619db6910e86492). Now it includes complete [sample.cpp](https://gist.github.com/dm0/728a4fb84dfe5b66e619db6910e86492/raw/88683fdd8db62e11d917210af401f543e1f67353/sample.cpp) that reproduces the issue, [debug.txt](https://gist.github.com/dm0/728a4fb84dfe5b66e619db6910e86492/raw/88683fdd8db62e11d917210af401f543e1f67353/debug.txt) also updated.

sample.cpp:
```cpp
#include <vector>
#include <iostream>

int main() {
    std::vector<int> my_vec{10, 20, 30};
    int index = 0;
    my_vec[static_cast<std::vector<int>::size_type>(index)] = 0;
    std::cout << my_vec[0] << std::endl;
    return 0;
}
```

uncrustify output:
```cpp
#include <vector>
#include <iostream>

int main() {
	std::vector<int> my_vec {10, 20, 30};
	int index = 0;
	my_vec[static_cast<std::vector < int>::size_type > (index)] = 0;
	std::cout << my_vec[0] << std::endl;
	return 0;
}
```

I use the following command line to compile:
`clang++-3.5 --std=c++11 -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic sample.cpp`

**Comment by guy-maurel** [comment]
A fix is coming soon.

**Comment by dm0** [comment]
Thanks!

**Comment by gmaurel** [comment]
The bug is fixed
