### ISSUE TITLE
array of function variable mishandled

### ISSUE THREAD

**Issue by rhinoshorn** [uncrustify/uncrustify#1041]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
test.cfg:
`sp_func_call_paren  = remove`

input:
`void (*g_func_table[32])(void);`

expected:
same as input

output:
`void(*g_func_table[32])(void);`
space between type and '(' removed.

**Comment by guy-maurel** [comment]
clang says:
```
VarDecl 0x25f47d8 <rhinoshorn.cpp:1:1, col:30> col:8 g_func_table 'void (*[32])(void)'
```
is it what you expected to have?
Could you push a complete example, with use of it?

**Comment by rhinoshorn** [comment]
@guy-maurel Yes, that's what I expected.

I put example code blocks below due to company firewall policy.

test.cfg:
```
sp_func_call_paren = remove
```
test.c:
```c
#include <stdio.h>

void func_dummy() { printf("%s\n", __func__); }
void func_0() { printf("%s\n", __func__); }
void func_1() { printf("%s\n", __func__); }
void func_2() { printf("%s\n", __func__); }

void (*g_func_table[32])(void) = {
        [0 ... 31] = func_dummy,
        [0] = func_0,
        [1] = func_1,
        [2] = func_2,
};

int main(int argc, char **argv)
{
    int i;
    for(i = 0; i < 32; i++) {
        g_func_table[i]();
    }
    return 0;
}
```

test.c.expected:
```c
#include <stdio.h>

void func_dummy() {
	printf("%s\n", __func__);
}
void func_0() {
	printf("%s\n", __func__);
}
void func_1() {
	printf("%s\n", __func__);
}
void func_2() {
	printf("%s\n", __func__);
}

void (*g_func_table[32])(void) = {
	[0 ... 31] = func_dummy,
	[0] = func_0,
	[1] = func_1,
	[2] = func_2,
};

int main(int argc, char **argv)
{
	int i;
	for(i = 0; i < 32; i++) {
		g_func_table[i]();
	}
	return 0;
}
```

test.c.uncrustify:
```c
#include <stdio.h>

void func_dummy() {
	printf("%s\n", __func__);
}
void func_0() {
	printf("%s\n", __func__);
}
void func_1() {
	printf("%s\n", __func__);
}
void func_2() {
	printf("%s\n", __func__);
}

void(*g_func_table[32])(void) = {
	[0 ... 31] = func_dummy,
	[0] = func_0,
	[1] = func_1,
	[2] = func_2,
};

int main(int argc, char **argv)
{
	int i;
	for(i = 0; i < 32; i++) {
		g_func_table[i]();
	}
	return 0;
}
```

**Comment by gmaurel** [comment]
is fixed

**Comment by rhinoshorn** [comment]
thank you~! :)

**Comment by gmaurel** [comment]
The solution is not complicated enough to solve the problem if assignment is NOT in the same block.

**Comment by guy-maurel** [comment]
#1512 is a better bugfix.
Thanks to @aneesh1127
