### ISSUE TITLE
Crash if logging error of open and close braces not correct

### ISSUE THREAD

**Issue by markuspabst** [uncrustify/uncrustify#1042]
If the code contains an open and close bracket issue, i.e. there are too much open or close braces, the logging function crashes on windows.

When compiling with VS2013 the crash is caused by incorrect format specifier %zu in:
file: uncrustify/src/brace_cleanup.cpp 
line: 430

Changing all %zu to %d and adding casts to the variables avoids the crash.

generated with uncrustify -f "test.cpp" -c test.cfg -o "test2.cpp"
current version: uncrustify 0.63

Example:
https://gist.github.com/markuspabst/b37c46db15bd616cb4ad2fb4a44042c2

**Comment by gmaurel** [comment]
This is not a bug.
We have changed most of the %d to %zu because most of the variables have the type "unsigned ..."
It is more a problem from VS.
uncrustify should be used with compilable sources. It is the better way. uncrustify has not much
error handling.

**Comment by markuspabst** [comment]
Yes, but then you could remove the branch completely. The part of the code is looking for an error (not compilable source) that is causing the crash.
Which compiler are you guys using normally?

**Comment by CDanU** [comment]
The CI uses GCC 4.6 and Clang 3.8 and Visual Studio 14 2015 Win64

**Comment by markuspabst** [comment]
The %zu format specifier causes crash on Visual Studio 2013 32it and 64Bit versions. The prebuilt windows binary is not crashing. Has this been introduced after VS2013?

**Comment by jibsen** [comment]
The `z` type specifier for printf has been in C since C99, and by extension was added to C++ in C++11. Sadly it is one of the C++11 features that did not make it into VS2013 (only has their own non-portable specifiers).

I believe the changes to Uncrustify were made a couple of months ago. Also, I think the binaries are built with mingw-w64.
