### ISSUE TITLE
latest version as of 3/1/2017 crashes with --show-config

### ISSUE THREAD

**Issue by stleusc** [uncrustify/uncrustify#1046]
```C
void print_options(FILE *pfile)
{
   const char *names[] =
   {
      "{ False, True }",
      "{ Ignore, Add, Remove, Force }",
      "Number",
      "{ Auto, LF, CR, CRLF }",
      "{ Ignore, Lead, Trail }",
      "String",
   };
```

names is used for lookup, the index is of type argtype_e which has one entry more (AT_UNUM,    /**< unsigned Number */)

Above array needs to be extended.

Crash happens when running --show-config

**Comment by CDanU** [comment]
I had made a cheap workaround for this: https://github.com/CDanU/uncrustify/commit/a3c2b36c908dd192c451f0c784615ce83b63d393. This does not solve the actual problem though, we need to be able to iterate those enum values if we want to be sure that this does not happen every time another option type is introduced.

**Comment by stleusc** [comment]
I had done the exact same change locally ;-) and I agree, this needs a better official fix or just something that gets caught in testing.

**Comment by gmaurel** [comment]
Thanks for the fix.
