### ISSUE TITLE
#ifdef-ed extern "C" block triggers invalid Unmatched BRACE_CLOSE error

### ISSUE THREAD

**Issue by Soukyuu** [uncrustify/uncrustify#1048]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Currently on uncrustify 0.64 c5c95d2, compiled with MSVC2013 x64. The following example:
```
#ifdef __cplusplus
extern "C"
{
#endif

int myFunc(void);

#ifdef __cplusplus
} // error triggered here
#endif
```
triggers an invalid `Unmatched BRACE_CLOSE` error.

Commenting out the second `#ifdef` block like this:
```
#ifdef __cplusplus
extern "C"
{
#endif

int myFunc(void);

//#ifdef __cplusplus
} // error NOT triggered here anymore
//#endif
```
gets rid off the error message. 

Minimal config:
```
input_tab_size=3
output_tab_size=3
indent_with_tabs=0
```
Can not provide any debug output because of issue #1045

**Comment by Soukyuu** [comment]
Just ran into this again. The biggest problem for me is that uncrustify stops processing once it hits that error, leaving parts of the code crustified.

**Comment by guy-maurel** [comment]
Yes, it is known problem with braces, because uncrustify doesn't calculate the #if preprocessor.
We don't have a solution for that.
Please, don't put any braces in preprocessor lines.
