### ISSUE TITLE
nl_assign_leave_one_liners with NL between = and {

### ISSUE THREAD

**Issue by rolandschulz** [uncrustify/uncrustify#105]
```C
int a[] =
{ 1, 2 };
```
is treated by nl_assign_leave_one_liners=true as one line and isn't reformated. With nl_assign_brace=remove and nl_after_brace_open=true I would expect to produce either
```C
int a[] = { 1, 2 };
```
or
```C
int a[] = { 
   1, 2 
};
```
or
```C
int a[] = 
          { 1, 2 };
```
But it does neither and just leaves it as it is.

**Comment by gmaurel** [comment]
With
sp_assign = force
nl_assign_brace=remove
nl_after_brace_open=true
with the actual git version. It works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!

**Comment by Jorengarenar** [comment]
> With
>sp_assign = force
>nl_assign_brace=remove
>nl_after_brace_open=true
>with the actual git version. It works pretty fine.
>https://github.com/uncrustify/uncrustify
>Please test it!

`nl_assign_leave_one_liners = true` is missing, after which the problem does occur
