### ISSUE TITLE
oneliner struct initializations

### ISSUE THREAD

**Issue by trufae** [uncrustify/uncrustify#1052]
I want uncrustify to indent zero struct initializers like this, when there's only one element, if there's more than one just indent with newlines like it does in the following snippet:

```
-	ut8 u32s[sizeof (ut32)] = {0};
+	ut8 u32s[sizeof (ut32)] = {
+		0
+	};
```

Is there any option in uncrustify to handle this? thanks

**Comment by CDanU** [comment]
I don't get the problem entirely but there is definitely nothing that checks the amount of elements in a struct initializer.

So you want to have everything for n >= 1 elements  in one line
but somehow newlined and indented with n >= 2 elements?

Like this:
ut8 u32s[sizeof (ut32)] = {
		0, 1 ,2 ,3
};

or like this:
ut8 u32s[sizeof (ut32)] = {
		0, 
                1,
                2 ,
                3
};

?

**Comment by trufae** [comment]
No i want it like this:

1 element:

ut8 foo[32] = { 0 };

Instead of

ut8 foo[32] = {
  0
};

For more than one element its ok for me to go like the 2nd snippet

**Comment by guy-maurel** [comment]
PR #2520 is a bugfix proposal.
Please test it and report.
