### ISSUE TITLE
Spacing within in-place new

### ISSUE THREAD

**Issue by plinss** [uncrustify/uncrustify#1056]
uncrustify 0.64

Spaces are always removed between the placement params and the type for in-place new operators, e.g.

```
Foo* foo = new (ptr) Foo();
```
becomes:
```
Foo* foo = new (ptr)Foo();
```

While I can find configuration options to control the space between the new and the (, there doesn't seem to be any control over the space between the ) and the type.

**Comment by CDanU** [comment]
Uncrustify is confusing placement_params with like C casts here.
Until this is fixed you could maybe use `sp_after_cast` set to `add` or `force` as a workaround.

**Comment by plinss** [comment]
sp_after_cast was set to ignore, setting it to force doesn't affect it

**Comment by CDanU** [comment]
It works with the provided example on 0db9f8e2e0178ca6610299b504a2f99df66f386d and on the 0.64 release for me. Could you please post a bigger example and your config file (see [ISSUE_TEMPLATE](https://github.com/uncrustify/uncrustify/blob/master/.github/ISSUE_TEMPLATE))?

**Comment by plinss** [comment]
Tested with a minimal config:
```
sp_after_new                    = add   
sp_between_new_paren            = remove
```

But found the issue with my example:
```Foo* foo = new(ptr) Foo();```
is fine, but a nested parenthesis, like, fails:
```Foo* foo = new(FOO(ptr))Foo();```

**Comment by CDanU** [comment]
Ok, that  confirms that `sp_after_cast` cannot be used as a workaround.

**Comment by plinss** [comment]
sorry about the bad example, was trying to reduce from a more complex code sample and went too far without confirming

**Comment by CDanU** [comment]
@plinss I added following new options that should solve your issue:

- sp_after_newop_paren
- sp_inside_newop_paren
- sp_inside_newop_paren_open
- sp_inside_newop_paren_close

It would be nice if you could confirm that everything is working as intended on your end.

**Comment by guy-maurel** [comment]
It works for me.
