### ISSUE TITLE
ObjC header method alignment

### ISSUE THREAD

**Issue by jtwigg** [uncrustify/uncrustify#1060]
How do I disable this method alignment? 

```
- (NSString *)addressString;
- (BOOL)      containsContactInformation;
```

I'd like "containsContactInformation" to be flush with -(BOOL)containsContactInformation?

I can't figure out how to disable.

Attached Config.
[uncrustify.txt](https://github.com/uncrustify/uncrustify/files/848412/uncrustify.txt)

**Comment by CDanU** [comment]
The problem is caused by
```sql
align_oc_msg_spec_span          = 20
```

**Comment by guy-maurel** [comment]
Could you push a more complete example?

**Comment by gmaurel** [comment]
No answer, we close.
