### ISSUE TITLE
Extra newline using 'nl_after_if'

### ISSUE THREAD

**Issue by invisible-clew** [uncrustify/uncrustify#1068]
Version:
```
dc7b412
```

Config:
```
nl_after_if = force
```

Here's a (dummy) example.
Code before formatting (expected unchanged after formatting):
```
void test()
{
	for ( int j = 0; j < 10; j++ )
		if ( j == 10 )
		{
			j++;
		}
}
```

After formatting:
```
void test()
{
	for ( int j = 0; j < 10; j++ )
		if ( j == 10 )
		{
			j++;
		}

}
```

Note the extra newline before the last closed brace.

**Comment by guy-maurel** [comment]
Such as you configure:
Add or remove blank line after 'if' statement
If you need it, please use:
```
nl_after_if = remove
```

**Comment by invisible-clew** [comment]
I'll try to explain the issue with another example... :)
Sometimes "nl_after_if = force" adds the extra new line before "}", sometimes not.

Before formatting:
```
// No extra line added
void test1()
{
	if ( i == 10 )
		i++;
}

// No extra line added
void test2()
{
	if ( i == 10 )
	{
		i++;
	}
}

// No extra line added
void test3()
{
	if ( i == 10 )
	{
		if ( j == 10 )
		{
			i++;
		}
	}
}

// No extra line added
void test4()
{
	if ( i == 10 )
	{
		if ( j == 10 )
			i++;
	}
}

// Extra line added (after Uncrustify)
void test5()
{
	if ( i == 10 )
		if ( j == 10 )
		{
			i++;
		}
}

// Extra line added (after Uncrustify)
void test6()
{
	if ( i == 10 )
		if ( j == 10 )
			i++;
}
```

After formatting:
```
// No extra line added
void test1()
{
	if ( i == 10 )
		i++;
}

// No extra line added
void test2()
{
	if ( i == 10 )
	{
		i++;
	}
}

// No extra line added
void test3()
{
	if ( i == 10 )
	{
		if ( j == 10 )
		{
			i++;
		}
	}
}

// No extra line added
void test4()
{
	if ( i == 10 )
	{
		if ( j == 10 )
			i++;
	}
}

// Extra line added (after Uncrustify)
void test5()
{
	if ( i == 10 )
		if ( j == 10 )
		{
			i++;
		}

}

// Extra line added (after Uncrustify)
void test6()
{
	if ( i == 10 )
		if ( j == 10 )
			i++;

}
```

Note the different  behaviour in test1/2/3/4 and in test5/6.

**Comment by guy-maurel** [comment]
Which version platform are using? Push your example, the config file as attachments.
 The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!

**Comment by invisible-clew** [comment]
Ok, I'll try the current version!
Probably the issue is already fixed, the first post (and my local build) is 17 days ago.
Thank you!

**Comment by CDanU** [comment]
No, the inconsistencies are still there.

**Comment by guy-maurel** [comment]
Sorry. It works for me, with Linux-Mint.
Here, the important part of the output from -p FILE:
```
# Uncrustify_d-0.64-561-ed81671
nl_after_if                     = remove
# option(s) with 'not default' value: 1
<snip>
#  54>        SEMICOLON[            NONE][ 28/ 28/ 29/  0][3/3/0][ 100000000][0-0]                            ;
#  54>     VBRACE_CLOSE[              IF][ 30/  0/  0/  0][2/2/0][         0][0-0]
#  54>     VBRACE_CLOSE[              IF][ 30/  0/  0/  0][1/1/0][         0][0-0]
#  54>          NEWLINE[            NONE][ 30/ 29/  1/  0][1/1/0][         0][1-0]
#  55>      BRACE_CLOSE[        FUNC_DEF][  1/  1/  2/  0][0/0/0][ 100000000][0-0] }
#  55>          NEWLINE[            NONE][  2/  2/  1/  0][0/0/0][         0][1-0]
# -=====-
```
There is only ONE newline between SEMICOLON and NEWLINE.
Please, push the output of your -p FILE

**Comment by CDanU** [comment]
I used his test5 & 6 for this

<details><summary>Debug</summary><pre>
# Uncrustify-0.64-581-6fe6fc65
nl_after_if                     = force
# option(s) with 'not default' value: 1
#
# -=====-
# Line              Tag           Parent          Columns Br/Lvl/pp     Flag   Nl  Text
#   1>      COMMENT_CPP[   COMMENT_WHOLE][  1/  1/ 39/  0][0/0/0][         0][0-0] // Extra line added (after Uncrustify)
#   1>          NEWLINE[            NONE][ 39/ 39/  1/  0][0/0/0][         0][1-0]
#   2>             TYPE[        FUNC_DEF][  1/  1/  5/  0][0/0/0][     70000][0-0] void
#   2>         FUNC_DEF[            NONE][  6/  6/ 11/  1][0/0/0][         0][0-0]      test5
#   2>      FPAREN_OPEN[        FUNC_DEF][ 11/ 11/ 12/  0][0/0/0][ 100000000][0-0]           (
#   2>     FPAREN_CLOSE[        FUNC_DEF][ 12/ 12/ 13/  0][0/0/0][ 100000000][0-0]            )
#   2>          NEWLINE[            NONE][ 13/ 13/  1/  0][0/0/0][         0][1-0]
#   3>       BRACE_OPEN[        FUNC_DEF][  1/  1/  2/  0][0/0/0][ 100000000][0-0] {
#   3>          NEWLINE[            NONE][  2/  2/  9/  0][1/1/0][         0][1-0]
#   4>               IF[            NONE][  9/  9/ 11/  0][1/1/0][     60000][0-1]         if
#   4>      SPAREN_OPEN[              IF][ 12/ 12/ 13/  1][1/1/0][ 100000000][0-0]            (
#   4>             WORD[            NONE][ 14/ 14/ 15/  1][1/2/0][     40020][0-0]              i
#   4>          COMPARE[            NONE][ 16/ 16/ 18/  1][1/2/0][ 100000020][0-0]                ==
#   4>           NUMBER[            NONE][ 19/ 19/ 21/  1][1/2/0][     40020][0-0]                   10
#   4>     SPAREN_CLOSE[              IF][ 22/ 22/ 23/  1][1/1/0][ 100000000][0-0]                      )
#   4>      VBRACE_OPEN[              IF][ 23/  0/  0/  0][1/1/0][         0][0-0]
#   4>          NEWLINE[            NONE][ 23/ 23/ 17/  0][2/2/0][         0][1-0]
#   5>               IF[            NONE][ 17/ 17/ 19/  0][2/2/0][     60000][0-1]                 if
#   5>      SPAREN_OPEN[              IF][ 20/ 20/ 21/  1][2/2/0][ 100000000][0-0]                    (
#   5>             WORD[            NONE][ 22/ 22/ 23/  1][2/3/0][     40020][0-0]                      j
#   5>          COMPARE[            NONE][ 24/ 24/ 26/  1][2/3/0][ 100000020][0-0]                        ==
#   5>           NUMBER[            NONE][ 27/ 27/ 29/  1][2/3/0][     40020][0-0]                           10
#   5>     SPAREN_CLOSE[              IF][ 30/ 30/ 31/  1][2/2/0][ 100000000][0-0]                              )
#   5>          NEWLINE[            NONE][ 31/ 31/ 17/  0][2/2/0][         0][1-0]
#   6>       BRACE_OPEN[              IF][ 17/ 17/ 18/  0][2/2/0][ 100000000][0-1]                 {
#   6>          NEWLINE[            NONE][ 18/ 18/ 25/  0][3/3/0][         0][1-0]
#   7>             WORD[            NONE][ 25/ 25/ 26/  0][3/3/0][     60000][0-1]                         i
#   7>     INCDEC_AFTER[            NONE][ 26/ 26/ 28/  0][3/3/0][ 100000000][0-0]                          ++
#   7>        SEMICOLON[            NONE][ 28/ 28/ 29/  0][3/3/0][ 100000000][0-0]                            ;
#   7>          NEWLINE[            NONE][ 29/ 29/ 17/  0][3/3/0][         0][1-0]
#   8>      BRACE_CLOSE[              IF][ 17/ 17/ 18/  0][2/2/0][ 100000000][0-1]                 }
#   8>     VBRACE_CLOSE[              IF][ 18/  0/  0/  0][1/1/0][         0][0-0]
#   8>          NEWLINE[            NONE][ 18/ 18/  1/  0][1/1/0][         0][2-0]
#   9>      BRACE_CLOSE[        FUNC_DEF][  1/  1/  2/  0][0/0/0][ 100000000][0-0] }
#   9>          NEWLINE[            NONE][  2/  2/  1/  0][0/0/0][         0][2-0]
#  11>      COMMENT_CPP[   COMMENT_WHOLE][  1/  1/ 39/  0][0/0/0][         0][0-0] // Extra line added (after Uncrustify)
#  11>          NEWLINE[            NONE][ 39/ 39/  1/  0][0/0/0][         0][1-0]
#  12>             TYPE[        FUNC_DEF][  1/  1/  5/  0][0/0/0][     70000][0-0] void
#  12>         FUNC_DEF[            NONE][  6/  6/ 11/  1][0/0/0][         0][0-0]      test6
#  12>      FPAREN_OPEN[        FUNC_DEF][ 11/ 11/ 12/  0][0/0/0][ 100000000][0-0]           (
#  12>     FPAREN_CLOSE[        FUNC_DEF][ 12/ 12/ 13/  0][0/0/0][ 100000000][0-0]            )
#  12>          NEWLINE[            NONE][ 13/ 13/  1/  0][0/0/0][         0][1-0]
#  13>       BRACE_OPEN[        FUNC_DEF][  1/  1/  2/  0][0/0/0][ 100000000][0-0] {
#  13>          NEWLINE[            NONE][  2/  2/  9/  0][1/1/0][         0][1-0]
#  14>               IF[            NONE][  9/  9/ 11/  0][1/1/0][     60000][0-1]         if
#  14>      SPAREN_OPEN[              IF][ 12/ 12/ 13/  1][1/1/0][ 100000000][0-0]            (
#  14>             WORD[            NONE][ 14/ 14/ 15/  1][1/2/0][     40020][0-0]              i
#  14>          COMPARE[            NONE][ 16/ 16/ 18/  1][1/2/0][ 100000020][0-0]                ==
#  14>           NUMBER[            NONE][ 19/ 19/ 21/  1][1/2/0][     40020][0-0]                   10
#  14>     SPAREN_CLOSE[              IF][ 22/ 22/ 23/  1][1/1/0][ 100000000][0-0]                      )
#  14>      VBRACE_OPEN[              IF][ 23/  0/  0/  0][1/1/0][         0][0-0]
#  14>          NEWLINE[            NONE][ 23/ 23/ 17/  0][2/2/0][         0][1-0]
#  15>               IF[            NONE][ 17/ 17/ 19/  0][2/2/0][     60000][0-1]                 if
#  15>      SPAREN_OPEN[              IF][ 20/ 20/ 21/  1][2/2/0][ 100000000][0-0]                    (
#  15>             WORD[            NONE][ 22/ 22/ 23/  1][2/3/0][     40020][0-0]                      j
#  15>          COMPARE[            NONE][ 24/ 24/ 26/  1][2/3/0][ 100000020][0-0]                        ==
#  15>           NUMBER[            NONE][ 27/ 27/ 29/  1][2/3/0][     40020][0-0]                           10
#  15>     SPAREN_CLOSE[              IF][ 30/ 30/ 31/  1][2/2/0][ 100000000][0-0]                              )
#  15>      VBRACE_OPEN[              IF][ 31/  0/  0/  0][2/2/0][         0][0-0]
#  15>          NEWLINE[            NONE][ 31/ 31/ 25/  0][3/3/0][         0][1-0]
#  16>             WORD[            NONE][ 25/ 25/ 26/  0][3/3/0][     60000][0-1]                         i
#  16>     INCDEC_AFTER[            NONE][ 26/ 26/ 28/  0][3/3/0][ 100000000][0-0]                          ++
#  16>        SEMICOLON[            NONE][ 28/ 28/ 29/  0][3/3/0][ 100000000][0-0]                            ;
#  16>     VBRACE_CLOSE[              IF][ 30/  0/  0/  0][2/2/0][         0][0-0]
#  16>     VBRACE_CLOSE[              IF][ 30/  0/  0/  0][1/1/0][         0][0-0]
#  16>          NEWLINE[            NONE][ 30/ 29/  1/  0][1/1/0][         0][2-0]
#  17>      BRACE_CLOSE[        FUNC_DEF][  1/  1/  2/  0][0/0/0][ 100000000][0-0] }
# -=====-
</pre></details>

**Comment by guy-maurel** [comment]
A bugfix is proposed at #1135

**Comment by gmaurel** [comment]
Fixed
