### ISSUE TITLE
New option request

### ISSUE THREAD

**Issue by demothorg** [uncrustify/uncrustify#1070]
I'm sorry if the duplicate and for my english.

I use this options (and indent size = 4):
```
mod_full_brace_if=remove
mod_full_brace_nl=2
```

But for code like this (multiline condition) I want to have braces, because otherwise condition merges with statement.
```
    if (a < 0 || a >= 10 ||
        b < 0 || b >= 100 ||
        c < 0 || c >= 1000 ||
        d < 0 || d >= 1000)
    {
        return -1;
    }
```

Can you add an option (something like `mod_full_brace_cond_nl=2`) that means:
"Don't remove braces around statements if condition (in `if` and `while` operators) span N newlines"?

**Comment by CDanU** [comment]
I am working on this.

**Comment by CDanU** [comment]
Do you actually need an unum option here? It looks like determining if the condition is a mulit line condition should be enough. I don't see the point in blocking brace removal only after lets say for example 4 lines.

**Comment by demothorg** [comment]
> It looks like determining if the condition is a mulit line condition should be enough.

Do you mean the option "Don't remove braces if condition is multiline" { True, False } ?
If so, it sounds good.

**Comment by demothorg** [comment]
Sorry, I just noticed the merge request...
I tested this - works fine. Thank you!
