### ISSUE TITLE
[feature request] add support for aligning on `|`

### ISSUE THREAD

**Issue by h-2** [uncrustify/uncrustify#1077]
The ranges library is already used by many projects and will very likely become part of C++20. It offers pipe operations on views similar to the unix command line:

```c++
    std::vector<int> foo{1, 4, 5, 7567546, 234, 56, 34534};
    auto bar = foo | ranges::view::slice(5, 7)
                   | ranges::view::reverse;
```

It would be great to be able to align on the pipe symbol. 

More information on ranges:
https://ericniebler.github.io/range-v3/

Meanwhile: can I somehow prevent uncrustify from reporting these as false positives?

Thanks!

**Comment by guy-maurel** [comment]
We are working on C++11

**Comment by guy-maurel** [comment]
Please try with:
```
void a()
{
        std::vector<int> foo {1, 4, 5, 7567546, 234, 56, 34534};
        // *INDENT-OFF*
        auto bar = foo | ranges::view::slice(5, 7)
                       | ranges::view::reverse;
        // *INDENT-ON*
}
```

**Comment by gmaurel** [comment]
No answer, we close.
