### ISSUE TITLE
Need support for C++14 integer literals with single quotes

### ISSUE THREAD

**Issue by alllel** [uncrustify/uncrustify#1082]
C++14 allows integer literals with separating of groups of digits with single quotes for readability.
For example following lines:
```
int a = 0x8000'FFFF;
char b = '\n';`
```
produce parsing errors:
```
indent.cpp:2 Garbage in col 12: 5c
indent.cpp:1 Unmatched ASSIGN
indent.cpp:1 Unmatched ASSIGN
```

**Comment by guy-maurel** [comment]
Well, we are completing C++11 just now.
And we still have 150 messages in the queue.
It would be fine if you could join us. Let me know.
