### ISSUE TITLE
Still need to specify "-c file" though .uncrustify.cfg exists my home directory

### ISSUE THREAD

**Issue by andrewhit** [uncrustify/uncrustify#1086]
According to the manual of uncrustify, there is no need to specify config file any longer if $HOME/.uncrustify.cfg exists. However it is not expected.

OPTIONS
   Basic Options:
       -c CFG Use the config file CFG.
              If not specified, uncrustify will use $UNCRUSTIFY_CONFIG or $HOME/.uncrustify.cfg.

azhuang@pek2-office-04-dhcp52:~$ la | grep .cfg
-rw-rw-r--  1 azhuang azhuang 25807 Apr  1 18:01 .uncrustify.cfg

azhuang@pek2-office-04-dhcp52:~/test$ echo $UNCRUSTIFY_CONFIG
/home/azhuang/.uncrustify.cfg

azhuang@pek2-office-04-dhcp52:~/test$ uncrustify -f ngx_http.c -o ngx_http.c.unc
Specify the config file with '-c file' or set UNCRUSTIFY_CONFIG

azhuang@pek2-office-04-dhcp52:~/test$ uncrustify --version
uncrustify 0.64.547-g4fdddba

Since I want to integrate uncrustify into emacs, it is helpful with the default config file, $HOME/.uncrustify.cfg.

**Comment by CDanU** [comment]
ref: [#479](https://github.com/uncrustify/uncrustify/pull/479#issuecomment-219569483)

**Comment by andrewhit** [comment]
Thanks a lot!

Now it works fine.

azhuang@pek2-office-04-dhcp52:~/test$ uncrustify -f ngx_http.c -o ngx_http.c.unc
Parsing: ngx_http.c as language C

**Comment by andrewhit** [comment]
Created #1086 to track $UNCRUSTIFY_CONFIG issue.
