### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by jrosenberger** [uncrustify/uncrustify#1089]
Does uncrustify have a planned release schedule?  A number of bugs have been fixed since 0.64.  I'd like to get these fixes, but avoid building from master for production use.

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by CDanU** [comment]
I don't think that there is a schedule, but @gmaurel maybe can tell you more about this.

Curently Uncrustify has some nasty bugs that _should_ prevent a release at this moment:
- bugs that produce code that fails to compile: #1088, #1048, #223, #945, (#683, #574)
- also important #854

**Comment by gmaurel** [comment]
About may 2017.

**Comment by kratsg** [comment]
@gmaurel thanks! It would be nice to have something more recent than 0.57 in Ubuntu. As far as I can tell, trying to run `uncrustify` with that old version is rather incompatible with some of the newer features such as `--check` and `(en)disable_cmt`.

**Comment by guy-maurel** [comment]
You can find many of the last releases at:
```
https://sourceforge.net/projects/uncrustify/files/uncrustify/
```
Choose Linux or Windows version.
