### ISSUE TITLE
mutli-line preprocessor indentation

### ISSUE THREAD

**Issue by nathanielting** [uncrustify/uncrustify#1090]
Config options:
input_tab_size=2
indent_columns=2
Before:
```
#if defined( TEST_A ) \
    || defined( TEST_B )
test = a \
   + b;
#endif
```
After:
```
#if defined( TEST_A ) \
  || defined( TEST_B )
test = a \
       + b;
#endif
```
Note how the alignment rules seem to be different between preprocessor and C code. There doesn't seem to be any option which specifies alignment for subsequent lines of preprocessor code. Is there any way to configure uncrustify to treat them the same way as C code? Or failing that, at least turn off re-indentation of multiline preprocessor code?

I would expect uncrustify to produce:
```
#if defined( TEST_A ) \
    || defined( TEST_B )
test = a \
       + b;
#endif
```
currently using uncrustify 0.64

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
Correct.
Indenting in the macro for the continuation line is 2.
The assignment line is control with brace(s). 
```
{
#if defined( TEST_A ) \
  || defined( TEST_B )
  test = a \
         + b;
#endif
}
```

**Comment by gmaurel** [comment]
No answer --> I close the call.
