### ISSUE TITLE
C: The left parameters does not align with the 1st parameter within the function call

### ISSUE THREAD

**Issue by andrewhit** [uncrustify/uncrustify#1091]
[debug.txt](https://gist.github.com/andrewhit/722ebb8c11f789642c4143233de84bd6#file-debug-txt)
[ngx_http.c the original file](https://gist.github.com/andrewhit/722ebb8c11f789642c4143233de84bd6#file-ngx_http-c-the-original-file)
[ngx_http.c.unc the uncrustified file](https://gist.github.com/andrewhit/722ebb8c11f789642c4143233de84bd6#file-ngx_http-c-unc-the-generated-result)

azhuang@pek2-office-04-dhcp52:~/test$ uncrustify --version
uncrustify 0.64.547-g4fdddba

line 151 of ngx_http.c
```c
    ctx->main_conf = ngx_pcalloc(cf->pool,
                                 sizeof(void *) * ngx_http_max_module);
```
becomes line 153 of ngx_http.c.unc after curstification
```c
    ctx->main_conf = ngx_pcalloc(cf->pool, 
            sizeof(void *) * ngx_http_max_module);
```

My expectation is no change to the original lines, however it chooses indentation instead of alignment with the previous parameter. I do not figure out how to change the config to fix this issue.

**Comment by CDanU** [comment]
This one is also caused by;
```sql
# The continuation indent. If non-zero, this overrides the indent of '(' and '=' continuation indents.
# For FreeBSD, this is set to 4. Negative value is absolute and not increased for each ( level
indent_continue                 = 4        # number
```

I am not exactly sure If it is in fact a bug here or not.

**Comment by andrewhit** [comment]
Thanks a lot!

I changed the configuration file as below and it works as I want.

# The continuation indent. If non-zero, this overrides the indent of '(' and '=' continuation indents.
# For FreeBSD, this is set to 4. Negative value is absolute and not increased for each ( level
indent_continue               = 0        # number

# True:  indent continued function call parameters one indent level
# False: align parameters under the open paren
indent_func_call_param   = false    # false/true
