### ISSUE TITLE
C: Add one blank line after "for(;;) {"

### ISSUE THREAD

**Issue by andrewhit** [uncrustify/uncrustify#1092]
[debug.txt](https://gist.github.com/andrewhit/722ebb8c11f789642c4143233de84bd6#file-debug-txt)
[ngx_http.c the original file](https://gist.github.com/andrewhit/722ebb8c11f789642c4143233de84bd6#file-ngx_http-c-the-original-file)
[ngx_http.c.unc the uncrustified file](https://gist.github.com/andrewhit/722ebb8c11f789642c4143233de84bd6#file-ngx_http-c-unc-the-generated-result)

azhuang@pek2-office-04-dhcp52:~/test$ uncrustify --version
uncrustify 0.64.547-g4fdddba

line 279 of ngx_http.c
```c
    for (s = 0; s < cmcf->servers.nelts; s++) {

        clcf = cscfp[s]->ctx->loc_conf[ngx_http_core_module.ctx_index];
```
becomes line 281 of ngx_http.c.unc
```c
    for (s = 0; s < cmcf->servers.nelts; s++) {
        clcf = cscfp[s]->ctx->loc_conf[ngx_http_core_module.ctx_index];
```

It was observed the blank line between "for loop" and "clcf = " was erased. And what I want is always adding one single blank line after the "for loop". Is there any configuration to support this feature? And same request of adding one single blank line after "switch () {", "if {", "else {", "while {" and "do {".

**Comment by CDanU** [comment]
This behavior (not bug) is caused by:
```sql
# Whether to remove blank lines after '{'
eat_blanks_after_open_brace     = true     # false/true
```

**Comment by andrewhit** [comment]
Thanks a lot!

I changed it to "eat_blanks_after_open_brace     = false" and it works as expected.
