### ISSUE TITLE
C: || is not correctly aligned within the mixed expression of && and ||

### ISSUE THREAD

**Issue by andrewhit** [uncrustify/uncrustify#1093]
[debug.txt](https://gist.github.com/andrewhit/722ebb8c11f789642c4143233de84bd6#file-debug-txt)
[ngx_http.c the original file](https://gist.github.com/andrewhit/722ebb8c11f789642c4143233de84bd6#file-ngx_http-c-the-original-file)
[ngx_http.c.unc the uncrustified file](https://gist.github.com/andrewhit/722ebb8c11f789642c4143233de84bd6#file-ngx_http-c-unc-the-generated-result)

azhuang@pek2-office-04-dhcp52:~/test$ uncrustify --version
uncrustify 0.64.547-g4fdddba

```c
line 1862 of ngx_http.c
        if (addr[i].hash.buckets == NULL
            && (addr[i].wc_head == NULL
                || addr[i].wc_head->hash.buckets == NULL)
            && (addr[i].wc_tail == NULL
                || addr[i].wc_tail->hash.buckets == NULL)
#if (NGX_PCRE)
            && addr[i].nregex == 0
#endif
            )
        {
```
becomes line 1898 of ngx_http.c.unc
```c
        if ((addr[i].hash.buckets == NULL)
            && ((addr[i].wc_head == NULL)
            || (addr[i].wc_head->hash.buckets == NULL)) 
            && ((addr[i].wc_tail == NULL)
            || (addr[i].wc_tail->hash.buckets == NULL))
#if (NGX_PCRE)
            && addr[i].nregex == 0
#endif
            )
        {
```
It was observed "||" is not correctly alignment and the expected is no change to the current.

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by CDanU** [comment]
This bug is caused by:
```
indent_continue                 = 3
```

**Comment by andrewhit** [comment]
It was caused by the below one.
```
indent_continue          = 4
```
The issue was gone after it was changed as below.
```
indent_continue          = 0
```
