### ISSUE TITLE
C: [Bug] deleting the extra whitespaces between the type and the variable though sp_after_type = ignore

### ISSUE THREAD

**Issue by andrewhit** [uncrustify/uncrustify#1094]
[debug.txt](https://gist.github.com/andrewhit/722ebb8c11f789642c4143233de84bd6#file-debug-txt)
[ngx_http.c the original file](https://gist.github.com/andrewhit/722ebb8c11f789642c4143233de84bd6#file-ngx_http-c-the-original-file)
[ngx_http.c.unc the uncrustified file](https://gist.github.com/andrewhit/722ebb8c11f789642c4143233de84bd6#file-ngx_http-c-unc-the-generated-result)

azhuang@pek2-office-04-dhcp52:~/test$ uncrustify --version
uncrustify 0.64.547-g4fdddba

line 69 of ngx_http.c
```c
ngx_uint_t   ngx_http_max_module;
```
becomes line 71 of ngx_http.c.unc after uncrustification
```c
ngx_uint_t ngx_http_max_module;
```
It was observed that there is only one single whitespace between ngx_int_t and ngx_http_max_module within ngx_http.c.unc . 

And my expectation is no change to the original line. Also is there any way to designate the number of whitespaces between the type and the variable or not deleting the extra whitespaces between them?

**Comment by CDanU** [comment]
# Add or remove space between type and word. Default=Force
sp_after_type                   = ignore   # ignore/add/remove/force

**Comment by andrewhit** [comment]
Thanks @CDanU for your info!

It does not work though "sp_after_type=ignore" is used. And there is always one single whitespace between the type and the word.

**Comment by andrewhit** [comment]
Additionally, "sp_after_type=add" doe not work as well.

**Comment by CDanU** [comment]
Additionally to `sp_after_type` not being `add` or `ignore` the option:
```sql
# The span for aligning struct/union (0=don't align)
align_var_struct_span           = 99       # unsigned number
```
is causing problems. 

This should not happen this is a bug.

**Comment by andrewhit** [comment]
The below configured is also for the alignment of the members within a struct.

'''
# The span for aligning struct/union (0=don't align)
align_var_struct_span           = 99       # unsigned number
'''

**Comment by guy-maurel** [comment]
What you need is:
```
align_keep_extra_space = true
```
The doc says: Whether to keep whitespace not required for alignment.

**Comment by CDanU** [comment]
Yes, that works but I would consider that as being a workaround.

Why is `align_var_struct_span` active in this case? There is no struct to align.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by gmaurel** [comment]
No answer --> I close the call.
