### ISSUE TITLE
Speed of test execution

### ISSUE THREAD

**Issue by stefan-nu** [uncrustify/uncrustify#1095]
Hello All,

I was wondering how long it takes for you to execute all tests on your build system.
When I run "run_test.py" manually it takes between 60 and 120 seconds depending on which machine I am working. 
How long takes the test execution for you?
Are there any plans to improve the test speed?

**Comment by CDanU** [comment]
linux, ssd, i7-3630QM

`make test` ~32 sec
`ctest -j 8` 6,2 sec
`time python run_tests.py --exe ../build/uncrustify`: 20,5 sec total

**Comment by CDanU** [comment]
Btw: my tests run now faster: 
```
ctest -j 8: 4,3 sec
```

because of one of the recent commits that added nullptr checking.

**Comment by stefan-nu** [comment]
I have figured out that on my Windows machine the test execution gets significantly slowed down by my virus scanner. I am using Avast antivirus. Even if I set the project directory on the ignore list of the virus scanner it slows it down. I have to disable the behavioural analysis completely.

**Comment by guy-maurel** [comment]
Linux Mint 17.3, Core i5, 4GB
I get for ctest:
Total Test time (real) =  15.88 sec

**Comment by CDanU** [comment]
For some freakish reasons 83577f2d8833334f38d24decac37acdce96d18bc lets `ctest -j 8` run 2 seconds longer. Could someone confirm this?

**Comment by guy-maurel** [comment]
I now get with
`time ctest` `real    0m15.179s`
`time ctest -j 4` `real    0m6.554s`
`time ctest -j 8` `real    0m5.314s`

**Comment by CDanU** [comment]
What do you get before 83577f2 ?

**Comment by guy-maurel** [comment]
May I close?

**Comment by CDanU** [comment]
yes
