### ISSUE TITLE
[Bug] Still need to specify "-c file" though UNCRUSTIFY_CONFIG is specified instead of using $HOME/.uncrustify.cfg

### ISSUE THREAD

**Issue by andrewhit** [uncrustify/uncrustify#1096]
Today I set UNCRUSTIFY_CONFIG to ~azhuang/.uncrustify/nginx.cfg instead of using ~azhuang/.uncrustify.cfg.

However it does not work.

azhuang@pek2-office-04-dhcp52:~/test$ uncrustify -f ngx_http.c -o ngx_http.c.unc
Specify the config file with '-c file' or set UNCRUSTIFY_CONFIG

azhuang@pek2-office-04-dhcp52:~/test$ echo $UNCRUSTIFY_CONFIG
/home/azhuang/.uncrustify/nginx.cfg

azhuang@pek2-office-04-dhcp52:~$ uncrustify -v
uncrustify 0.64.549-gfa51230

OPTIONS
Basic Options:
-c CFG Use the config file CFG.
If not specified, uncrustify will use $UNCRUSTIFY_CONFIG or $HOME/.uncrustify.cfg.

**Comment by CDanU** [comment]
I can't reproduce that:
```
.... /build/Debug %  UNCRUSTIFY_CONFIG=../..//scripts/Config/mini_d.cfg ./uncrustify /tmp/u/t.cpp 
../..//scripts/Config/mini_d.cfg:2 Unknown symbol 'not_existing_option'
Output suffix: .uncrustify
Parsing: /tmp/u/t.cpp as language CPP
```
390995cc5c374da25f78152d45a49d2ef21be39d

**Comment by andrewhit** [comment]
Here are the steps of reproducing this issue.

1. set UNCRUSTIFY_CONFIG=~azhuang/.uncrustify/nginx.cfg
```
azhuang@pek2-office-04-dhcp52:~/.uncrustify$ echo $UNCRUSTIFY_CONFIG
/home/azhuang/.uncrustify/nginx.cfg
```

2. It works fine because there exists a soft link, .uncrustify.cfg under my home directory.
```
azhuang@pek2-office-04-dhcp52:~/test$ uncrustify -f ngx_http.c -o ngx_http.c.unc
Parsing: ngx_http.c as language C
azhuang@pek2-office-04-dhcp52:~/test$ cd
azhuang@pek2-office-04-dhcp52:~$ la | grep uncr
drwxrwxr-x  2 azhuang azhuang  4096 Apr  6 18:33 .uncrustify/
lrwxrwxrwx  1 azhuang azhuang    35 Apr  5 18:49 .uncrustify.cfg -> /home/azhuang/.uncrustify/nginx.cfg
```

3. Remove .uncrustify.cfg
```
azhuang@pek2-office-04-dhcp52:~$ rm .uncrustify.cfg
rm: remove symbolic link ‘.uncrustify.cfg’? y
```

4. Uncrustify does not work because it does not use the file specified by $UNCRUSTIFY_CONFIG.
```
azhuang@pek2-office-04-dhcp52:~/test$ uncrustify -f ngx_http.c -o ngx_http.c.unc
Specify the config file with '-c file' or set UNCRUSTIFY_CONFIG
Try running with -h for usage information
```

5. Confirm $UNCRUSTIFY_CONFIG has been configured.
```
azhuang@pek2-office-04-dhcp52:~/test$ echo $UNCRUSTIFY_CONFIG
/home/azhuang/.uncrustify/nginx.cfg
azhuang@pek2-office-04-dhcp52:~/test$ ll /home/azhuang/.uncrustify/nginx.cfg
-rw-rw-r-- 1 azhuang azhuang 27535 Apr  6 02:31 /home/azhuang/.uncrustify/nginx.cfg
```

**Comment by andrewhit** [comment]
It is interesting uncrustify always checkes two config files under the user's home directory,

```
.uncrustify.cfg
uncrustify.cfg
```

However the manual says it reads only $HOME/.uncrustify.cfg. Until now, uncrustify does not check $UNCRUSTIFY_CONFIG if the above two files do not exist.

OPTIONS
Basic Options:
-c CFG Use the config file CFG.
If not specified, uncrustify will use $UNCRUSTIFY_CONFIG or $HOME/.uncrustify.cfg.

**Comment by CDanU** [comment]
Here is the [code](https://github.com/uncrustify/uncrustify/blob/390995cc5c374da25f78152d45a49d2ef21be39d/src/uncrustify.cpp#L417-L438) that processes the env var:
```cpp
   string cfg_file;
   if (((p_arg = arg.Param("--config")) != nullptr) ||
       ((p_arg = arg.Param("-c")) != nullptr))
   {
      cfg_file = p_arg;
   }
   else if (!unc_getenv("UNCRUSTIFY_CONFIG", cfg_file))
   {
      /* Try to find a config file at an alternate location */
      string home;

      if (unc_homedir(home))
      {
         struct stat tmp_stat = {};

         const auto  path0 = home + "/.uncrustify.cfg";
         const auto  path1 = home + "/uncrustify.cfg";

         if (stat(path0.c_str(), &tmp_stat) == 0)
         {
            cfg_file = path0;
         }
         else if (stat(path1.c_str(), &tmp_stat) == 0)
         {
            cfg_file = path1;
         }
      }
}
```

It checks fist for the programm args, then it checks the env var and only then does it try to use the default locations. As I have shown above I does work for on my machine, I specifically have chosen a config file that generates an error output to see that Uncrustify is is really loading it:
> ../..//scripts/Config/mini_d.cfg:2 Unknown symbol 'not_existing_option'

I'll do some more tests, but it really seems like the error is not caused by Uncrustify.

**Comment by andrewhit** [comment]
Thanks @CDanU !

After changing the shell variable, UNCRUSTIFY_CONFIG to the environment variable as you pointed out, this issue was gone.

Though UNCRUSTIFY_CONFIG=~/.uncrustify/nginx.cfg is defined my ~/.bashrc, UNCRUSTIFY_CONFIG is not an environment variable.
