### ISSUE TITLE
#1085 introduces a warning

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1098]
Using the compiler option -Wmissing-field-initializers, I get a warning:
```
/home/guy/Software/uncrustify/src/uncrustify.cpp:424:34: warning: missing initializer for member ‘stat::st_dev’ [-Wmissing-field-initializers]
          struct stat tmp_stat = {};
```
@CDanU could you a look to it?

**Comment by CDanU** [comment]
This should be it: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55805

**Comment by guy-maurel** [comment]
Thanks. I have to wait until gcc 5 is coming with Linux Mint.
