### ISSUE TITLE
C: the function pointers do not align within a struct. 

### ISSUE THREAD

**Issue by andrewhit** [uncrustify/uncrustify#1106]
[debug.txt](https://gist.github.com/andrewhit/f3e4547e10393f36892085586f830207)

azhuang@pek2-office-04-dhcp52:~/test/uncrustify$ uncrustify -v
Uncrustify-0.64-561-ed81671

Here is my original file, ngx_stream.h.

```c
typedef struct {
    ngx_int_t             (*postconfiguration)(ngx_conf_t *cf);

    void                 *(*create_main_conf)(ngx_conf_t *cf);
    char                 *(*init_main_conf)(ngx_conf_t *cf, void *conf);

    void                 *(*create_srv_conf)(ngx_conf_t *cf);
    char                 *(*merge_srv_conf)(ngx_conf_t *cf, void *prev,
                                            void *conf);
} ngx_stream_module_t;
```

It became below after the uncrustification. And it was observed that  ```post_configuration``` does not align with the left members, like ```create_main_conf```.
```c
typedef struct {
    ngx_int_t             (*postconfiguration)(ngx_conf_t *cf);

    void *(*create_main_conf)(ngx_conf_t * cf);
    char *(*init_main_conf)(ngx_conf_t * cf, void *conf);

    void *(*create_srv_conf)(ngx_conf_t * cf);
    char *(*merge_srv_conf)(ngx_conf_t * cf, void *prev,
                            void *conf);
} ngx_stream_module_t;
```

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
Why do you use parenthesis such as` (*postconfiguration)`

**Comment by gmaurel** [comment]
No answer --> I close the call.
