### ISSUE TITLE
sp_assign splits map key-value operator => to = > which fails to compile on Salesforce Apex

### ISSUE THREAD

**Issue by sjurgis** [uncrustify/uncrustify#1110]
Hi,
I hope the question is not too specific, but I am having problem with Salesforce's Apex not being able to compile map assignment operator => when it has space in it. Otherwise it's very useful to split assignment and/or other mathematical operators. Is there a way to ignore these?

**Comment by CDanU** [comment]
Let me guess, you are using atom-beautify right? They kinda decided that Uncrustify supports Apex, which it does not.

I don't really know anything about the
> compile map assignment operator =>

so post some code examples, i.e input code, output code, expected code and your config file so we can see if anything can be done for you.

**Comment by sjurgis** [comment]
@CDanU thanks for the response. Say I instantiate a map:
`map<string, string> foo = new map<string, string>{
    'fizz' => 'buzz'
}`

Using sp_assign will split the 'arrow' into: `'fizz' = > 'buzz'`, which in turn get rejected by Apex compiler:
> unexpected token: '>' (Line: 123)

Yes I am using atom-beutify :) I have heavily customised by uncrustify.cfg file. Default works well enough, but I am looking to add spacing around equals and other mathematical operators. Possibly even add uncrustification to CI.

**Comment by CDanU** [comment]
I looked in to this and it seems that this is purely a Apex thing, java does not seem to have it. I would advice against adding another language that none of the devs work with (see the obj-c mess).

You could however define `disable_processing_cmt` and `enable_processing_cmt` that _should_ block Uncrustify from touching the regions inside those comments.

**Comment by sjurgis** [comment]
I guess I am not really looking for additional language support, but for a possible configuration workaround.

Interesting the same problem applies for JS fat arrows. Surely there must be someone out there using uncrustify for JS :)

**Comment by CDanU** [comment]
> Surely there must be someone out there using uncrustify for JS
So you have looked at the source code :), there is no other mention of JS outside the coe. I am not really sure why it is in there, maybe it was planned at one point.

**Comment by sjurgis** [comment]
No, not really, just a random guess based on the odds!

**Comment by CDanU** [comment]
Hmm, I havn't used this options much but you could try the stuff mentioned in the options documentation:

```
# You can force a token to be a type with the 'type' option.
# Example:
# type myfoo1 myfoo2
#
# You can create custom macro-based indentation using macro-open,
# macro-else and macro-close.
# Example:
# macro-open  BEGIN_TEMPLATE_MESSAGE_MAP
# macro-open  BEGIN_MESSAGE_MAP
# macro-close END_MESSAGE_MAP
#
# You can assign any keyword to any type with the set option.
# set func_call_user _ N_
#
# The full syntax description of all custom definition config entries
# is shown below:
#
# define custom tokens as:
# - embed whitespace in token using '' escape character, or
#   put token in quotes
# - these: ' " and ` are recognized as quote delimiters
#
# type token1 token2 token3 ...
#             ^ optionally specify multiple tokens on a single line
# define def_token output_token
#                  ^ output_token is optional, then NULL is assumed
# macro-open token
# macro-close token
# macro-else token
# set id token1 token2 ...
#               ^ optionally specify multiple tokens on a single line
#     ^ id is one of the names in token_enum.h sans the CT_ prefix,
#       e.g. PP_PRAGMA
#
# all tokens are separated by any mix of ',' commas, '=' equal signs
# and whitespace (space, tab)
```

**Comment by CDanU** [comment]
Even after fixing the removal of the equals char, Uncrustify is tokenizing the files in such a way that those punctuators end up being splitted, unless the combination of them is actually hard coded into the source code.

**Comment by Maristie** [comment]
Well I've met the same problem using Atom...
The arrow operator `->` will be parsed to `- >`, and I have no way but to disable `sp_arith`.

**Comment by CDanU** [comment]
@Maristie Could you give me a bit more info  about what you want to achieve? Are we still talking about Apex? 
You case _could_ be different as there already is a '->' defined in the punctuator list.

**Comment by Maristie** [comment]
uncrustify version: 0.64
cfg file: [sun.cfg](https://github.com/uncrustify/uncrustify/blob/master/etc/sun.cfg)

I'm using Atom Beautify to format java code, and when I'm using Lambda Expressions, `->` will be replaced with `- >`.

As a minimal example, the original code
```Java
public class Test {
    public static void main() {
	btn.addActionListener(e->{
	    System.exit(0);
        });
    }
}
```
And after prettify,
```Java
public class Test {
    public static void main() {
	btn.addActionListener(e - > {
	    System.exit(0);
	});
    }
}
```

**Comment by mihaipopescu** [comment]
Seems like the two issues are similar but different and we need to split them. @Maristie, can you create another one for yours? 

I'm not a Java expert but from what I see Lambda Expressions were introduced in Java 8.

I think for each language we need to expressly state what version of the standard we're supporting. This is just like we say for C++ we say that we want to be C++11 compliant and C++14 is out of scope for now.

And for Apex we need to make it clear that Uncrustify doesn't officially supports it. Who knows, maybe by popular demand, we will add this language eventually and start supporting it as patches are welcome. 

I've started a related discussion thread here #1118 to figure how to properly communicate this.

**Comment by Maristie** [comment]
@mihaipopescu I've created another issue now. Sorry for mistaking the two issues. I should have checked supported languages...

**Comment by mihaipopescu** [comment]
Thanks for that and don't be sorry!  👍
