### ISSUE TITLE
Curly baces in constructors moves down parentheses

### ISSUE THREAD

**Issue by Lorac** [uncrustify/uncrustify#1115]
Generated:
```
Test::Test()
	: generator(std::random_device {}
				())
{}
```

Expected :
```
Test::Test()
	: generator(std::random_device {}())
{}
```
Config:
https://pastebin.com/6ucmuxBW

Version
```
uncrustify 0.64_d
```

**Comment by CDanU** [comment]
I assume `std::random_device {}()` is a struct initializer with a call to `operator()`? 
Currently there does not seem to be an option to disable the __default__ (also happens with empty conf) insertion of the newline in this case.

**Comment by Lorac** [comment]
> I assume std::random_device {}() is a struct initializer with a call to operator()?

Correct.

**Comment by guy-maurel** [comment]
I get with the current git version:
```
Test::Test()
        : generator(std::random_device {} ())
{}
```
The config is:
```
input_tab_size   = 4
output_tab_size  = 4
indent_columns   = 4
indent_with_tabs = 2
```
Please test it and report.

**Comment by Lorac** [comment]
Tested and it works.

**Comment by guy-maurel** [comment]
Fine. Please close the call.
