### ISSUE TITLE
Refactor root documentation files

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1118]
I think it would be more relevant for users to be welcomed with general usage/installation rather development. These informations are relevant for developers only and they can be moved to another file (probably to `CONTRIBUTING.md`).

What we have on http://uncrustify.sourceforge.net/ can be a good start to put in the `README.md`. 

I think would clear a lot of confusion about what the tool is doing, what languages are officially supported etc. For instance, I just spotted that the vscode-uncrustify extension asserts that uncrustify support Apex which is not true. Opened an issue here https://github.com/LaurentTreguier/vscode-uncrustify/issues/6.

**Comment by CDanU** [comment]
Good catch, that apex misinformation is slowly starting to spread.

Here is my view about this, maybe I am to much influenced by generally using linux systems, but I generally expect all needed information to be in a manpage or in the output of the -h flag (less optimal). GitHub for me is a place for developers, but as Uncrustify is not having any other web page we could add more info an that here. 

This is the order of information I would like to see in the README:
At the top a short description about what Uncrustify is and what it is doing.
The second part would be about as much as possible info about how to contribute. I think that this should be the most important part of the README.
And finally, down at the bottom, all the user related stuff.

I generally like to see what the people doing that are starring, following or open issues for Uncrustify. Recently we had an issue opened up by plinss.  If inspiration on how to write the user related stuff is needed look up his repos. Here is an example: https://github.com/plinss/acmebot
I'd say that the amount of info is splendid, I however would like a bare minimum in the README in addition to links that point to the (currently missing) GitHub Uncrustify wiki. There we can have the main user instructions.

**Comment by CDanU** [comment]
Here is a first try: https://github.com/CDanU/uncrustify/blob/patch-1/README.md
It's bit much, though. @gmaurel could you open op the wiki for everyone?

**Comment by mihaipopescu** [comment]
I like it ! Thanks for your hard work @CDanU !
