### ISSUE TITLE
Java 8 `->` was split into `- >` in Lambda Expression

### ISSUE THREAD

**Issue by Maristie** [uncrustify/uncrustify#1121]
uncrustify version: 0.64
cfg file: [sun.cfg](https://github.com/uncrustify/uncrustify/blob/master/etc/sun.cfg)

When I'm using Lambda Expressions in Java 8, the arrow operator `->` will be split into `- >` after formatted.

As a minimal example, the original code is
```Java
public class Test {
    public static void main() {
	btn.addActionListener(e->{
	    System.exit(0);
        });
    }
}
```

It's expected to be as the following
```Java
public class Test {
    public static void main() {
	btn.addActionListener( e -> {
	    System.exit(0);
        });
    }
}
```

But after uncrustified
```Java
public class Test {
    public static void main() {
	btn.addActionListener(e - > {
	    System.exit(0);
	});
    }
}
```

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by gmaurel** [comment]
No answer, we close.
