### ISSUE TITLE
nl_before_throw = add can not handle java throws

### ISSUE THREAD

**Issue by xxjapp** [uncrustify/uncrustify#1122]
uncrustify 0.64

can not format from:

private void save() throws IOException {
}

to:

private void save()
throws IOException {
}

with option "nl_before_throw = add" in java

**Comment by guy-maurel** [comment]
Yes, we don't yet have any option for that.

**Comment by guy-maurel** [comment]
PR #2528 is a bugfix proposal.
Please test it and report.

**Comment by xxjapp** [comment]
@guy-maurel

The following version works as expected. Thank you for your great work.

```
> .\uncrustify.exe --version
Uncrustify-0.70.1_f
```
