### ISSUE TITLE
Feature Request: Addition of options/settings to align function parameters and parenthesis with spaces

### ISSUE THREAD

**Issue by pm-energid** [uncrustify/uncrustify#1123]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Hi,

It would be great if you can add my request related to C++ formatting on your improvements list.

I need a newline before the parenthesis for function signatures (i.e. in function declaration and definition) which is achievable using existing options. However, the parenthesis and the function parameters should be aligned at an indent. The following lines show an example of the expected/wanted output.  Please note the indentation and alignment of function signature parentheses and parameters.

```
////// myclass.h
class MyClass
{
   MyClass
      (
      );
      
   void myFunc1
      (
      );
      
   void myFunc2
      (
      int param1,
      int param2
      );
};

/////// myclass.cpp
MyClass::MyClass
   (
   ):
   m_Var1(0),
   m_Var2(4)
{
   // Constructor implementation
}

void MyClass::myFunc1
   (
   )
{
   // myFunc1 implementation
}

void MyClass::myFunc2
   (
   int param1,
   int param2
   )
{
   // myFunc2 implementation
}
```

Using the existing uncrustify options, I was able to generate the following outputs (close but not exactly what I wanted):

```
void MyClass::myFunc1
   ()
{
   // myFunc1 implementation
}
```

and

```
void MyClass::myFunc2
(
   int param1,
   int param2
)
{
   // myFunc2 implementation
}
```

I tried to hack a copy of uncrustify code by myself to get the desired output, but my changes introduced bugs in some other areas. It seems like I'll need to spend a significant time to understand the uncrustify code before I could make any changes. So, I hope you can add the requested feature (the only missing capability before I can switch to uncrustify).

Thanks

**Comment by ttnghia** [comment]
From my perspective, the function call parameters should be aligned, instead of indented. For instance, I usually have code like this:

`auto result = thisIsMyFunctionCall(param1, 
        param2, 
        param3,
        param4);`

That does not look nice. Instead, I want to have this:

`auto result = thisIsMyFunctionCall(param1, 
                                                         param2, 
                                                         param3, 
                                                         param4);`

In particular, I want the 'paramX' in the next lines to be aligned with the open brace '('.

**Comment by mihaipopescu** [comment]
I'm inclined to go more with the style proposed by @ttnghia rather than the one by @pm-energid. And as you may have noticed, I think nowadays there is a bug where function arguments are double-indented (8 spaces instead of 4).

**Comment by pm-energid** [comment]
I wasn't even talking about function calls. The existing options for function calls work just fine. My request is related to function signature (declaration and definition). Current options in uncrustify don't allow what I want to achieve. While everyone has their own preferences, the format I described is the coding standard used by my company. So, I requested an additional option to allow the specified indentation style in my first code section.

**Comment by mihaipopescu** [comment]
Personally I've never seen this coding style but yeah sure, it can be a valid feature request.

**Comment by pm-energid** [comment]
Thanks Mihai. I agree. I found it weird too when I joined.. But it is a
standard being followed here. Thanks for taking it up as a feature request.

On 05-May-2017 6:41 PM, "Mihai Popescu" <notifications@github.com> wrote:

Personally I've never seen this coding style but yeah sure, it can be a
valid feature request.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/uncrustify/uncrustify/issues/1123#issuecomment-299460465>,
or mute the thread

**Comment by mihaipopescu** [comment]
Then, are you going to use uncrustify for your personal sanity or for the entire company ?

Can you fork uncrustify and share your work in progress branch and explain the regressions you are seeing ?

**Comment by pm-energid** [comment]
To begin with, I will use it for myself while trying to maintain my
company's coding standards. After a while, if I find it safe and usable for
everyone to use (no unwanted formatting changes), I'll recommend it for the
entire company.

The changes I did in my local copy were just a hack on existing settings.
And that change caused some function calls like explicit operator calls to
be split in lines and indented in similar manner. As yet, I don't even
understand how to create a new settings option. So, I doubt my changes
would be of any help other than misguiding.


On 06-May-2017 2:22 PM, "Mihai Popescu" <notifications@github.com> wrote:

Then, are you going to use uncrustify for your personal sanity or for the
entire company ?

Can you fork uncrustify and share your work in progress branch and explain
the regressions you are seeing ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/uncrustify/uncrustify/issues/1123#issuecomment-299625938>,
or mute the thread

**Comment by mihaipopescu** [comment]
You can start by adding your input and expected output in the tests folder and then iterate on the code until you all tests are passing, to make sure you are not introducing a regression. I would use the old test runner `tests/run_tests.py` passing the `-g` option to get more debug information like the tokens map and a verbose log file.

**Comment by dkbarto** [comment]
I'd like to 'vote' for this. My company is moving towards automatic code formatting and the alignment of parameters is one that people have expressed a preference for.

**Comment by mihaipopescu** [comment]
One thing I've learned about formatting is that aligning code is a bad idea. It's a source of unrelated changes in PRs that will  make the life of the reviewers miserable. One of the core points of doing automatic code formatting is to avoid the need.od reviewing that. This option puts it back on the table. It's your call but also consider this point of view.

**Comment by dkbarto** [comment]
I'm agreeing with @mihaipopescu comments on May 4, 2017. I think that my 'vote' may have been misunderstood. Sorry for any confusion.

**Comment by guy-maurel** [comment]
Please push your current config file.
I must have a look to it before I go on.

**Comment by dkbarto** [comment]
We have stopped using uncrustify for our formatting and are now using clang’s formatting tool.

You can close this ticket.

	David

**Comment by gmaurel** [comment]
David wrote: "We have stopped using uncrustify  ... "
