### ISSUE TITLE
Feature Request: Options wanted to control new line before and after member '->' or '.' operation

### ISSUE THREAD

**Issue by xxjapp** [uncrustify/uncrustify#1124]
The following 3 options are wanted to control new line before and after member '->' or '.' operation

nl_member              
nl_member_before
nl_member_after

for example format this java source

new URL(url)
    .openConnection();

=>

new URL(url).openConnection();

**Comment by guy-maurel** [comment]
PR #2531 is a bugfix proposal.
Please test it and report.

**Comment by xxjapp** [comment]
@guy-maurel 

The following version works as expected. Thank you for your great work.

```
> .\uncrustify.exe --version
Uncrustify-0.70.1_f
```
