### ISSUE TITLE
indent_ternary_operator not aligning correctly

### ISSUE THREAD

**Issue by CDanU** [uncrustify/uncrustify#1130]
Currently (3b398e961c2729569b24dd147c62dd5594b65dff) with this config:
```sql
# indent the continuation of ternary operator.
# 0: (Default) off
# 1: When the `if_false` is a continuation, indent it under `if_false`
# 2: When the `:` is a continuation, indent it under `?`
indent_ternary_operator         = 2        # unsigned number
```
This input generates the same output
```cpp
(tmp ? chunk_is_newline(tmp) ? "newline"
			     : chunk_is_comment(tmp) ? "comment"
						     : "other"
						     : "---"));
```

I would expect the following output:
```cpp
(tmp ? chunk_is_newline(tmp) ? "newline"
			     : chunk_is_comment(tmp) ? "comment"
						     : "other"
     : "---"));
```
<details><summary>DEBUG</summary>
<pre>
# Uncrustify-0.64-572-97a9ab16
indent_ternary_operator         = 2
# option(s) with 'not default' value: 1
#
# -=====-
# Line              Tag           Parent          Columns Br/Lvl/pp     Flag   Nl  Text
#   1>       PAREN_OPEN[            NONE][  1/  1/  2/  0][0/0/0][ 100060000][0-0] (
#   1>             WORD[            NONE][  2/  2/  5/  0][0/1/0][     40000][0-0]  tmp
#   1>         QUESTION[            NONE][  6/  6/  7/  1][0/1/0][ 100000000][0-0]      ?
#   1>        FUNC_CALL[            NONE][  8/  8/ 24/  1][0/1/0][     40000][0-0]        chunk_is_newline
#   1>      FPAREN_OPEN[       FUNC_CALL][ 24/ 24/ 25/  0][0/1/0][ 100000000][0-0]                        (
#   1>             WORD[            NONE][ 25/ 25/ 28/  0][0/2/0][     40010][0-0]                         tmp
#   1>     FPAREN_CLOSE[       FUNC_CALL][ 28/ 28/ 29/  0][0/1/0][ 100000000][0-0]                            )
#   1>         QUESTION[            NONE][ 30/ 30/ 31/  1][0/1/0][ 100000000][0-0]                              ?
#   1>           STRING[            NONE][ 32/ 32/ 41/  1][0/1/0][     40000][0-0]                                "newline"
#   1>          NEWLINE[            NONE][ 41/ 41/ 30/  0][0/1/0][         0][1-0]
#   2>       COND_COLON[            NONE][ 30/ 30/ 31/  0][0/1/0][ 100000000][0-0]                              :
#   2>        FUNC_CALL[            NONE][ 32/ 32/ 48/  1][0/1/0][     60000][0-0]                                chunk_is_comment
#   2>      FPAREN_OPEN[       FUNC_CALL][ 48/ 48/ 49/  0][0/1/0][ 100000000][0-0]                                                (
#   2>             WORD[            NONE][ 49/ 49/ 52/  0][0/2/0][     40010][0-0]                                                 tmp
#   2>     FPAREN_CLOSE[       FUNC_CALL][ 52/ 52/ 53/  0][0/1/0][ 100000000][0-0]                                                    )
#   2>         QUESTION[            NONE][ 54/ 54/ 55/  1][0/1/0][ 100000000][0-0]                                                      ?
#   2>           STRING[            NONE][ 56/ 56/ 65/  1][0/1/0][     40000][0-0]                                                        "comment"
#   2>          NEWLINE[            NONE][ 65/ 65/ 54/  0][0/1/0][         0][1-0]
#   3>       COND_COLON[            NONE][ 54/ 54/ 55/  0][0/1/0][ 100000000][0-0]                                                      :
#   3>           STRING[            NONE][ 56/ 56/ 63/  1][0/1/0][     60000][0-0]                                                        "other"
#   3>          NEWLINE[            NONE][ 63/ 63/ 54/  0][0/1/0][         0][1-0]
#   4>       COND_COLON[            NONE][ 54/ 54/ 55/  0][0/1/0][ 100000000][0-0]                                                      :
#   4>           STRING[            NONE][ 56/ 56/ 61/  1][0/1/0][     60000][0-0]                                                        "---"
#   4>      PAREN_CLOSE[            NONE][ 61/ 61/ 62/  0][0/0/0][ 100000000][0-0]                                                             )
#   4>      PAREN_CLOSE[            NONE][ 62/ 62/ 63/  0][0/0/0][ 100000000][0-0]                                                              )
#   4>        SEMICOLON[            NONE][ 63/ 63/ 64/  0][0/0/0][ 100000000][0-0]                                                               ;
#   4>          NEWLINE[            NONE][ 64/ 64/  1/  0][0/0/0][         0][1-0]
# -=====-
<pre>
</details>

**Comment by orenbenkiki** [comment]
while poking at the ternary indentation (with `indent_ternary_operator 2`), I also noticed that:
```
a ? b
    + c
  : d
    + e;
```
Is converted to:
```
a ? b
+ c
  : d
+ e;
```
I expected it to have remained as it was.

**Comment by samishchandra** [comment]
Fix at [PR 2662](https://github.com/uncrustify/uncrustify/pull/2662).
