### ISSUE TITLE
incorrect formatting for initializer with aggregated values

### ISSUE THREAD

**Issue by esteve** [uncrustify/uncrustify#1142]
Given this configuration file: https://gist.github.com/esteve/766a20ce521a657d152711e96a6a4765/raw/94a3ab3fa7fd49b95378da77993bd9ce6bab25f5/ament_code_style.cfg

However, this other C++ code: https://gist.github.com/esteve/766a20ce521a657d152711e96a6a4765/raw/94a3ab3fa7fd49b95378da77993bd9ce6bab25f5/various_1.hpp

```c++
struct Various_1
{
  std::vector<int32_t> value_a;
  Various_1()
    : value_a({{1, 2}})
  {
  }
};
```

uncrustify (version Uncrustify-0.64-595-79ba971) leaves the code unchanged, as expected: https://gist.github.com/esteve/766a20ce521a657d152711e96a6a4765/raw/94a3ab3fa7fd49b95378da77993bd9ce6bab25f5/various_1.hpp.uncrustify

However, given this other C++ snippet: https://gist.github.com/esteve/766a20ce521a657d152711e96a6a4765/raw/94a3ab3fa7fd49b95378da77993bd9ce6bab25f5/various_2.hpp

```c++
struct Various_2
{
  std::vector<int32_t> value_a;
  std::vector<int32_t> value_b;
  Various_2()
    : value_a({{1, 2}}),
      value_b({{3, 4}})
  {
  }
};
```

uncrustify reformats it as: https://gist.githubusercontent.com/esteve/766a20ce521a657d152711e96a6a4765/raw/94a3ab3fa7fd49b95378da77993bd9ce6bab25f5/various_2.hpp.uncrustify

```c++
struct Various_2
{
  std::vector<int32_t> value_a;
  std::vector<int32_t> value_b;
  Various_2()
    : value_a({{1, 2}}),
      value_b({{3, 4}}) {
  }
};
```

I don't know if might be caused by the ``{{}}`` aggregated values in the initializers, since the following code is left intact as expected: https://gist.github.com/esteve/766a20ce521a657d152711e96a6a4765/raw/94a3ab3fa7fd49b95378da77993bd9ce6bab25f5/various_3.hpp

```c++

struct Various_3
{
  int32_t value_a;
  int32_t value_b;
  int32_t value_c;
  Various_3()
    : value_a(1),
      value_b(3),
      value_c(5)
  {
  }
};
```

Debug files for the three snippets:

 - various_1.hpp:
https://gist.github.com/esteve/766a20ce521a657d152711e96a6a4765/raw/94a3ab3fa7fd49b95378da77993bd9ce6bab25f5/debug_various_1.txt

- various_2.hpp: https://gist.github.com/esteve/766a20ce521a657d152711e96a6a4765/raw/94a3ab3fa7fd49b95378da77993bd9ce6bab25f5/debug_various_2.txt

- various_3.hpp: https://gist.github.com/esteve/766a20ce521a657d152711e96a6a4765/raw/94a3ab3fa7fd49b95378da77993bd9ce6bab25f5/debug_various_3.txt

**Comment by CDanU** [comment]
Yes this is a bug. The parenthesis `chunk_t` are having the wrong `parent_type`. It should be `CT_FUNC_CTOR_VAR` but is `CT_FUNC_CALL`.

Options involved:
```sql
# Uncrustify-0.64-595-79ba971f
nl_fcall_brace                  = remove
# option(s) with 'not default' value: 1
#
```
<details><summary>DEBUG</summary>
# Uncrustify-0.64-595-79ba971f
nl_fcall_brace                  = remove
# option(s) with 'not default' value: 1
#
# -=====-
# Line              Tag           Parent          Columns Br/Lvl/pp     Flag   Nl  Text
#   1>           STRUCT[            NONE][  1/  1/  7/  0][0/0/0][     70002][0-0] struct
#   1>             TYPE[          STRUCT][  8/  8/ 17/  1][0/0/0][         2][0-0]        Various_2
#   1>          NEWLINE[            NONE][ 17/ 17/  1/  0][0/0/0][         2][1-0]
#   2>       BRACE_OPEN[          STRUCT][  1/  1/  2/  0][0/0/0][ 100000002][0-0] {
#   2>          NEWLINE[            NONE][  2/  2/  3/  0][1/1/0][         2][1-0]
#   3>             TYPE[            NONE][  9/  3/  6/  0][1/1/0][    460402][0-0]         std
#   3>        DC_MEMBER[            NONE][ 12/  6/  8/  0][1/1/0][ 100400402][0-0]            ::
#   3>             TYPE[            NONE][ 14/  8/ 14/  0][1/1/0][    400402][0-0]              vector
#   3>       ANGLE_OPEN[        TEMPLATE][ 20/ 14/ 15/  0][1/1/0][ 100000442][0-0]                    <
#   3>             TYPE[            NONE][ 21/ 15/ 22/  0][1/2/0][     40442][0-0]                     int32_t
#   3>      ANGLE_CLOSE[        TEMPLATE][ 28/ 22/ 23/  0][1/1/0][ 100000442][0-0]                            >
#   3>             WORD[            NONE][ 30/ 24/ 31/  1][1/1/0][   1840402][0-0]                              value_a
#   3>        SEMICOLON[            NONE][ 37/ 31/ 32/  0][1/1/0][ 100000402][0-0]                                     ;
#   3>          NEWLINE[            NONE][ 38/ 32/  3/  0][1/1/0][         2][1-0]
#   4>             TYPE[            NONE][  9/  3/  6/  0][1/1/0][    460402][0-0]         std
#   4>        DC_MEMBER[            NONE][ 12/  6/  8/  0][1/1/0][ 100400402][0-0]            ::
#   4>             TYPE[            NONE][ 14/  8/ 14/  0][1/1/0][    400402][0-0]              vector
#   4>       ANGLE_OPEN[        TEMPLATE][ 20/ 14/ 15/  0][1/1/0][ 100000442][0-0]                    <
#   4>             TYPE[            NONE][ 21/ 15/ 22/  0][1/2/0][     40442][0-0]                     int32_t
#   4>      ANGLE_CLOSE[        TEMPLATE][ 28/ 22/ 23/  0][1/1/0][ 100000442][0-0]                            >
#   4>             WORD[            NONE][ 30/ 24/ 31/  1][1/1/0][   1840402][0-0]                              value_b
#   4>        SEMICOLON[            NONE][ 37/ 31/ 32/  0][1/1/0][ 100000402][0-0]                                     ;
#   4>          NEWLINE[            NONE][ 38/ 32/  3/  0][1/1/0][         2][1-0]
#   5>   FUNC_CLASS_DEF[            NONE][  9/  3/ 12/  0][1/1/0][     60402][0-0]         Various_2
#   5>      FPAREN_OPEN[  FUNC_CLASS_DEF][ 18/ 12/ 13/  0][1/1/0][ 100000502][0-0]                  (
#   5>     FPAREN_CLOSE[  FUNC_CLASS_DEF][ 19/ 13/ 14/  0][1/1/0][ 100000502][0-0]                   )
#   5>          NEWLINE[            NONE][ 20/ 14/  5/  0][1/1/0][         2][1-0]
#   6>     CONSTR_COLON[            NONE][ 17/  5/  6/  0][1/1/0][ 100000502][0-0]                 :
#   6>    FUNC_CTOR_VAR[            NONE][ 19/  7/ 14/  1][1/1/0][     60502][0-0]                   value_a
#   6>      FPAREN_OPEN[   FUNC_CTOR_VAR][ 26/ 14/ 15/  0][1/1/0][ 100000502][0-0]                          (
#   6>       BRACE_OPEN[  FUNC_CLASS_DEF][ 27/ 15/ 16/  0][1/2/0][ 100040412][0-0]                           {
#   6>          NEWLINE[            NONE][ 28/ 16/  0/  0][1/2/0][       412][1-0]
#   6>       BRACE_OPEN[            NONE][ 17/ 16/ 17/  0][2/3/0][ 100060412][0-0]                 {
#   6>           NUMBER[            NONE][ 18/ 17/ 18/  0][3/4/0][     60412][0-0]                  1
#   6>            COMMA[            NONE][ 19/ 18/ 19/  0][3/4/0][ 100000412][0-0]                   ,
#   6>           NUMBER[            NONE][ 21/ 20/ 21/  1][3/4/0][     40412][0-0]                     2
#   6>      BRACE_CLOSE[            NONE][ 22/ 21/ 22/  0][2/3/0][ 100000412][0-0]                      }
#   6>          NEWLINE[            NONE][ 23/ 22/  0/  0][2/3/0][       412][1-0]
#   6>      BRACE_CLOSE[  FUNC_CLASS_DEF][  9/ 22/ 23/  0][1/2/0][ 100000412][0-0]         }
#   6>     FPAREN_CLOSE[   FUNC_CTOR_VAR][ 10/ 23/ 24/  0][1/1/0][ 100000402][0-0]          )
#   6>            COMMA[            NONE][ 11/ 24/ 25/  0][1/1/0][ 100000402][0-0]           ,
#   6>          NEWLINE[            NONE][ 12/ 25/  7/  0][1/1/0][         2][1-0]
#   7>        FUNC_CALL[            NONE][ 17/  7/ 14/  0][1/1/0][     40402][0-0]                 value_b
#   7>      FPAREN_OPEN[       FUNC_CALL][ 24/ 14/ 15/  0][1/1/0][ 100000402][0-0]                        (
#   7>       BRACE_OPEN[            NONE][ 25/ 15/ 16/  0][1/2/0][ 120040412][0-0]                         {
#   7>       BRACE_OPEN[            NONE][ 26/ 16/ 17/  0][2/3/0][ 120060412][0-0]                          {
#   7>           NUMBER[            NONE][ 27/ 17/ 18/  0][3/4/0][  20060412][0-0]                           3
#   7>            COMMA[            NONE][ 28/ 18/ 19/  0][3/4/0][ 120000412][0-0]                            ,
#   7>           NUMBER[            NONE][ 30/ 20/ 21/  1][3/4/0][  20040412][0-0]                              4
#   7>      BRACE_CLOSE[            NONE][ 31/ 21/ 22/  0][2/3/0][ 120000412][0-0]                               }
#   7>      BRACE_CLOSE[            NONE][ 32/ 22/ 23/  0][1/2/0][ 120000412][0-0]                                }
#   7>     FPAREN_CLOSE[       FUNC_CALL][ 33/ 23/ 24/  0][1/1/0][ 100000402][0-0]                                 )
#   7>       BRACE_OPEN[       FUNC_CALL][ 35/ 25/ 26/  1][1/1/0][ 140000402][0-0]                                   {
#   7>          NEWLINE[            NONE][ 36/ 26/  1/  0][2/2/0][         2][2-0]
#   9>      BRACE_CLOSE[       FUNC_CALL][  9/  1/  2/  0][1/1/0][ 140000402][0-0]         }
#   9>          NEWLINE[            NONE][ 10/  2/  0/  0][1/1/0][       402][1-0]
#   9>      BRACE_CLOSE[          STRUCT][  1/  2/  3/  0][0/0/0][ 100000400][0-0] }
#   9>        SEMICOLON[          STRUCT][  2/  3/  4/  0][0/0/0][ 100000000][0-0]  ;
#   9>          NEWLINE[            NONE][  3/  4/  1/  0][0/0/0][         0][1-0]
# -=====-

</details>

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by gmaurel** [comment]
No answer, we close.
