### ISSUE TITLE
Question about "align_var_def_span"

### ISSUE THREAD

**Issue by invisible-clew** [uncrustify/uncrustify#1145]
If I have two variables like these:
```
char *****ptr_a;
unsigned long long *ptr_b;
```
And I use this config:
```
align_var_def_span       = 1
align_var_def_star_style = 2
```
I get this result:
```
char           *****ptr_a;
unsigned long long *ptr_b;
```
It's ok, but I would like this result (without the "overlap" between types and stars):
```
char               *****ptr_a;
unsigned long long     *ptr_b;
```
Is it possible? Maybe I didn't find the right option...

Thanks in advance! :)

**Comment by CDanU** [comment]
No, currently this does not seem to be possible.

**Comment by guy-maurel** [comment]
Yes. You can use the option: `align_var_def_gap = 6`, but you have to calculate yourself the value.

**Comment by invisible-clew** [comment]
Ok, for the moment, I simply rewrite the function "AlignStack::Flush()" (probably in the wrong way :D but it works) for my behaviour.
Thanks for the answers! :)

**Comment by guy-maurel** [comment]
Could you close?

**Comment by invisible-clew** [comment]
You are right, sorry. Closed! :)
