### ISSUE TITLE
Additional (over) indent for readability in definitions of regular functions and constructors

### ISSUE THREAD

**Issue by Alexander-Shukaev** [uncrustify/uncrustify#115]
Parameters in the configuration file look a bit messy, they sometimes appear to be not well structured, or their descriptions are vague and inconsistent. But, anyway, I understand that it is not an easy task to handle right away - so no blaming meant - just a little feedback.

The purpose of this issue is to make it clear whether it is possible to achieve desired alignment (which I describe further) with a current state of `Uncrustify 0.59`. Here we go, I'll show several formatting cases which must hold simultaneously (without reconfiguring `Uncrustify`), i.e. which formatting case is chosen depends exclusively on the structure of input code.

Assuming `indent_columns = 2`:

1:
```c++
PluginDialog::
PluginDialog(QString const&     path,
             QStringList const& fileNames,
             QWidget*           parent): QDialog(parent),
                                         label(new QLabel),
                                         treeWidget(new QTreeWidget),
                                         okButton(new QPushButton(tr("OK"))) {
  setWindowTitle(tr("Plugin Information"));
  ...
```

2: **note the double indent on constructor parameters (should be the case for regular functions as well)**:
```c++
PluginDialog::
PluginDialog(
    QString const&     path,
    QStringList const& fileNames,
    QWidget*           parent): QDialog(parent),
                                label(new QLabel),
                                treeWidget(new QTreeWidget),
                                okButton(new QPushButton(tr("OK"))) {
  setWindowTitle(tr("Plugin Information"));
  ...
```

3: **note the double indent on base class constructor call and member initialization list**:
```c++
PluginDialog::
PluginDialog(QString const&     path,
             QStringList const& fileNames,
             QWidget*           parent):
    QDialog(parent),
    label(new QLabel),
    treeWidget(new QTreeWidget),
    okButton(new QPushButton(tr("OK"))) {
  setWindowTitle(tr("Plugin Information"));
  ...
```

4 **note the double indent on constructor parameters and triple indent on base class constructor call and member initialization list**:
```c++
PluginDialog::
PluginDialog(
    QString const&     path,
    QStringList const& fileNames,
    QWidget*           parent):
      QDialog(parent),
      label(new QLabel),
      treeWidget(new QTreeWidget),
      okButton(new QPushButton(tr("OK"))) {
  setWindowTitle(tr("Plugin Information"));
  ...
```

I am able to achieve all these cases, **BUT** without those "double" and "triple" indent stuff which is essential for readability. So the question is: is it feasible with current version of `Uncrustify`, and of course, if yes, then how?

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
