### ISSUE TITLE
Segfault when align_same_func_call_params=true

### ISSUE THREAD

**Issue by jlack1987** [uncrustify/uncrustify#1150]
The segfault was generated with the following command,
```
uncrustify --replace --no-backup -l CPP -c ~/.config/uncrustify/uncrustify.cfg file.cpp
```
The uncrustify config file can be found [here](https://github.com/uncrustify/uncrustify/files/994361/uncrustify.txt)
Unfortunately the code I have is proprietary and i'm not able to upload it. I am using version 0.59 which is what you get when you `sudo apt-get install uncrustify` in Ubuntu 16.04

**Comment by guy-maurel** [comment]
Well. Without any input... I cannot help.
Please try two things:
Modify your code, only about 10-20 lines to give us the chance to reproduce.
The current git version:
  https://github.com/uncrustify/uncrustify
Please test it.
The next binary is coming soon.

**Comment by CDanU** [comment]
While I also cannot reproduce a segfault with random input, there still is a problem: He mixes `--replace` and `--no-backup`. 


```sql
--replace
        Replace source files (creates a backup).
        This cannot be combined with -f, --prefix, or --suffix.

--no-backup
        Replace files, no backup. Useful if files are under source control
        This cannot be combined with -f, --prefix, or --suffix.
```


For safety reason we should either add code that terminates Uncrustify when both flags are set or `--replace` should overwrite `--no-backup`.

**Comment by jlack1987** [comment]
I have actually found that it only segfaults when I give it a list of like 4 files to reformat. The exact command i'm running is,
```
uncrustify --replace --no-backup -l CPP -c ~/.config/uncrustify/uncrustify.cfg file1.hpp file2.hpp file3.hpp file4.hpp
```
where it's segfaulting right after reformating file4.hpp. I have genericized file4.hpp and it is attached [here](https://github.com/uncrustify/uncrustify/files/996988/TestFile.txt)

The console output I get is the following,
```
jordan@jordan-VirtualBox$ uncrustify --replace --no-backup -l CPP -c ~/.config/uncrustify/uncrustify.cfg file1.hpp file2.hpp file3.hpp file4.hpp
Parsing: file1.hpp as language CPP
Parsing: file2.hpp as language CPP
Parsing: file3.hpp as language CPP
Parsing: file4.hpp as language CPP
Segmentation fault (core dumped)
```
Thanks for being so prompt on the response. Let me know if there's any other testing I can do to help you out.

**Comment by CDanU** [comment]
Hmm no I still can't reproduce that. Could you be so kind and tests your setup against the current git version?

**Comment by jlack1987** [comment]
Thanks @CDanU, any chance Ubuntu 16.04 will get an update?

**Comment by CDanU** [comment]
You should talk about that with the Ubuntu folks.

**Comment by jlack1987** [comment]
Any chance you could explain "talk about that with the Ubuntu folks" more? I was under the impression the developers decided what versions went with what distros and when updates were sent out but from that it sounds like that's not under your control?

**Comment by CDanU** [comment]
No we are not in full control of that, Uncrustify is released under the GPLv2 license, so in the spirit of free and open source software __as long as that the terms are not broken__, anyone can do as they please with the software. 

Btw. you can talk with the Ubuntu guys but I doubt that they will add anything to their LTS versions that is not security related.

**Comment by guy-maurel** [comment]
If you know any mail address(es) of such a/many guy(s), I would be very happy to have the chance to inform them about the changes we are doing. Thanks.

**Comment by guy-maurel** [comment]
We now have:
Ubuntu 18.04 0.66.1
This is the current version.
It works pretty nice.
Please test and report.
