### ISSUE TITLE
Help for using macro-open and macro-close

### ISSUE THREAD

**Issue by fricco** [uncrustify/uncrustify#1152]
Hello, I'm configuring Uncrustify to use it with Salesforce Apex (I know it's not officially supported but works pretty well). Generally speaking is working fine, but I want to customize my formatting of the code to add some indentation in blocks of code that are surrounded by Test.startTest(); and Test.stopTest();
So I updated the defaults.cfg to have the following:
```
macro-open Test.startTest
macro-close Test.stopTest
```
But this is doing nothing. Am I understanding wrong how the macro-open and macro-close work?
Thank you!

**Comment by CDanU** [comment]
The dots are problematic. With them your defined macros are chopped up in 3 chunks. If Test_startTest and Test_stopTest are used the macros are correctly parsed. 
I'll see if something can be done against this problem.
