### ISSUE TITLE
include <algorithm> cannot be compiled under mingw-w32

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1154]
A problem occurs at trying to compile newlines.cpp (probably also indent.cpp).
This is the line with:
`#include <algorithm>`

which produces the error:
```
[ 55%] Building CXX object CMakeFiles/uncrustify.dir/src/newlines.cpp.obj
In file included from /usr/lib/gcc/i686-w64-mingw32/5.3-win32/include/x86intrin.h:29:0,
                 from /usr/lib/gcc/i686-w64-mingw32/5.3-win32/include/c++/i686-w64-mingw32/bits/opt_random.h:33,
                 from /usr/lib/gcc/i686-w64-mingw32/5.3-win32/include/c++/random:50,
                 from /usr/lib/gcc/i686-w64-mingw32/5.3-win32/include/c++/bits/stl_algo.h:66,
                 from /usr/lib/gcc/i686-w64-mingw32/5.3-win32/include/c++/algorithm:62,
                 from /home/guy/Software/uncrustify/src/newlines.cpp:27:
/usr/lib/gcc/i686-w64-mingw32/5.3-win32/include/mmintrin.h: In function ‘__m64 _mm_cvtsi32_si64(int)’:
/usr/lib/gcc/i686-w64-mingw32/5.3-win32/include/mmintrin.h:64:54: error: can’t convert between vector values of different size
   return (__m64) __builtin_ia32_vec_init_v2si (__i, 0);
```
Can anybody help?

**Comment by mihaipopescu** [comment]
Does it also mean we don't have mingw32 build under CI ?

**Comment by CDanU** [comment]
The `<algorithm>` include was added in 2014. How recent is this error? Did we upgraded the version of the mingw gcc recently? According to a quick google search gcc had some problems with the  `mmintrin` header.

**Comment by jibsen** [comment]
> Does it also mean we don't have mingw32 build under CI ?

We have a cross-compile using mingw-w64 on Travis. AppVeyor in the past only included the old mingw32 package, but it [looks like](https://www.appveyor.com/docs/build-environment/#mingw-msys-cygwin) perhaps there are more recent mingw-w64 packages now.

**Comment by guy-maurel** [comment]
Sorry for the noise!
It is my fault. I used a new system which was not correctly configure.
Thanks for helping.
