### ISSUE TITLE
Uncrustify Git Hooks

### ISSUE THREAD

**Issue by CDanU** [uncrustify/uncrustify#1157]
Seeing that I and other people struggle to create PRs that pass the Uncrustify config- and Test_more_Options.sh tests the first time I made this hooks:
(based on https://github.com/githubbrowser/Pre-commit-hooks)

https://gist.github.com/CDanU/15601f1761543cd1b8a73e4613bfa283

Please put them in your Uncrustify/.git/hooks/ directory and give me some feedback.

**Comment by mihaipopescu** [comment]
Aren't these UNIX-compatible shell only ?

**Comment by CDanU** [comment]
Yes, I read that the windows git has its own implementation of bash so that _should_ not be a problem. I have not considered if it is actually possible to write those in python for example.

**Comment by CDanU** [comment]
It is working quiet nice on windows for me, but I have found a bug that I am going to fix soon.

**Comment by mihaipopescu** [comment]
Yes, they could work in git bash as you mentioned but you have to be in that shell when you are running the commit right ?

**Comment by CDanU** [comment]
It did run for me on cmd, it could have been tough that it pulled something from mingw. 
I made an update to the gist and it _should_ work but git acts sometimes unexpectedly so I won't pursue this for now.
