### ISSUE TITLE
Unexpected space before empty while semicolon and embedded cstyle comment

### ISSUE THREAD

**Issue by soeugene** [uncrustify/uncrustify#1158]
uncrustify 0.64

The program generates an unexpected space in two places of my sample code. 

```
void Class1::Func(void)
{
  while (Next());
}

static uint8_t array1[a + 4/*length+crc16*/];
```

1. After the closing empty while parenthesis.
2. Before the c-style comment.

```
void Class1::Func(void)
{
  while (Next()) ;
}

static uint8_t array1[a + 4 /*length+crc16*/];
```

I expect the sample code to be unchanged after running uncrustify.  Please explain what configuration option is causing these changes and how it can be fixed.  Are these bugs?  

[debug.txt](https://github.com/uncrustify/uncrustify/files/1001623/debug.txt)

[uncrustify_test.txt](https://github.com/uncrustify/uncrustify/files/1001627/uncrustify_test.txt)

Thanks!
Eugene

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by CDanU** [comment]
Here is what I get, it does not depend on if your or an empty config is used.

I:
```cpp
void Class1::Func(void)
{
  while (Next());
}

static uint8_t array1[a + 4/*length+crc16*/];
```
O:
```cpp
void Class1::Func(void)
{
	while (Next()) ;
}

static uint8_t array1[a + 4 /*length+crc16*/];
```
<details>
<pre>
# Uncrustify-0.64-630-6b67e6f1
# option(s) with 'not default' value: 0
#
# -=====-
# Line              Tag           Parent          Columns Br/Lvl/pp     Flag   Nl  Text
#   1>             TYPE[        FUNC_DEF][  1/  1/  5/  0][0/0/0][     70000][0-0] void
#   1>             TYPE[        FUNC_DEF][  6/  6/ 12/  1][0/0/0][         0][0-0]      Class1
#   1>        DC_MEMBER[        FUNC_DEF][ 12/ 12/ 14/  0][0/0/0][ 100000000][0-0]            ::
#   1>         FUNC_DEF[            NONE][ 14/ 14/ 18/  0][0/0/0][         0][0-0]              Func
#   1>      FPAREN_OPEN[        FUNC_DEF][ 18/ 18/ 19/  0][0/0/0][ 100000000][0-0]                  (
#   1>             TYPE[            NONE][ 19/ 19/ 23/  0][0/1/0][     40008][0-0]                   void
#   1>     FPAREN_CLOSE[        FUNC_DEF][ 23/ 23/ 24/  0][0/0/0][ 100000000][0-0]                       )
#   1>          NEWLINE[            NONE][ 24/ 24/  1/  0][0/0/0][         0][1-0]
#   2>       BRACE_OPEN[        FUNC_DEF][  1/  1/  2/  0][0/0/0][ 100000000][0-0] {
#   2>          NEWLINE[            NONE][  2/  2/  3/  0][1/1/0][         0][1-0]
#   3>            WHILE[            NONE][  9/  3/  8/  0][1/1/0][     60000][0-0]         while
#   3>      SPAREN_OPEN[           WHILE][ 15/  9/ 10/  1][1/1/0][ 100000000][0-0]               (
#   3>        FUNC_CALL[            NONE][ 16/ 10/ 14/  0][1/2/0][     40020][0-0]                Next
#   3>      FPAREN_OPEN[       FUNC_CALL][ 20/ 14/ 15/  0][1/2/0][ 100000020][0-0]                    (
#   3>     FPAREN_CLOSE[       FUNC_CALL][ 21/ 15/ 16/  0][1/2/0][ 100000020][0-0]                     )
#   3>     SPAREN_CLOSE[           WHILE][ 22/ 16/ 17/  0][1/1/0][ 100000000][0-0]                      )
#   3>      VBRACE_OPEN[           WHILE][ 23/  0/  0/  0][1/1/0][  20000000][0-0]
#   3>        SEMICOLON[            NONE][ 24/ 17/ 18/  0][2/2/0][ 120060000][0-0]                        ;
#   3>     VBRACE_CLOSE[           WHILE][ 26/  0/  0/  0][1/1/0][  20000000][0-0]
#   3>          NEWLINE[            NONE][ 26/ 18/  1/  0][1/1/0][         0][1-0]
#   4>      BRACE_CLOSE[        FUNC_DEF][  1/  1/  2/  0][0/0/0][ 100000000][0-0] }
#   4>          NEWLINE[            NONE][  2/  2/  1/  0][0/0/0][         0][2-0]
#   6>        QUALIFIER[            NONE][  1/  1/  7/  0][0/0/0][    470000][0-0] static
#   6>             TYPE[            NONE][  8/  8/ 15/  1][0/0/0][    410000][0-0]        uint8_t
#   6>             WORD[            NONE][ 16/ 16/ 22/  1][0/0/0][   1800000][0-0]                array1
#   6>      SQUARE_OPEN[            NONE][ 22/ 22/ 23/  0][0/0/0][ 100000000][0-0]                      [
#   6>             WORD[            NONE][ 23/ 23/ 24/  0][0/1/0][     60000][0-0]                       a
#   6>            ARITH[            NONE][ 25/ 25/ 26/  1][0/1/0][ 100000000][0-0]                         +
#   6>           NUMBER[            NONE][ 27/ 27/ 28/  1][0/1/0][     40000][0-0]                           4
#   6>          COMMENT[   COMMENT_EMBED][ 29/ 28/ 44/  0][0/1/0][         0][0-0]                             /*length+crc16*/
#   6>     SQUARE_CLOSE[            NONE][ 45/ 44/ 45/  0][0/0/0][ 100000000][0-0]                                             ]
#   6>        SEMICOLON[            NONE][ 46/ 45/ 46/  0][0/0/0][ 100000000][0-0]                                              ;
#   6>          NEWLINE[            NONE][ 47/ 46/  1/  0][0/0/0][         0][11-0]
# -=====-
</pre>
</details>

**Comment by guy-maurel** [comment]
The second part is not a bug.
The wished space before c-comment are controlled with the two options:
```
sp_before_tr_emb_cmti    = force
sp_num_before_tr_emb_cmt = 5
```
Please test and report.

**Comment by soeugene** [comment]
The first part seems okay now.
Why is the second part not a bug?  There doesn't seem to be anyway to configure it so that a space is NOT added between the 4 and the /*.
