### ISSUE TITLE
Indent continuation and template angle brackets

### ISSUE THREAD

**Issue by soeugene** [uncrustify/uncrustify#1160]
uncrustify 0.64

Using the 'indent_continue' option, uncrustify does not seem to handle template angle brackets properly.  I expect the code to be unchanged by running uncrustify.  However, I see the following problematic behaviour:

In the first block, the continuation indent disappears.
In the second block, the continuation indent is doubled.
In the third block, the continuation indent also disappears. 

Original code:
```
template<typename T1, typename T2>
class Class1
{
public:
    msgpack::type::tuple<uint16_t, uint16_t, int32_t, int32_t, uint16_t, uint16_t, float, float, float,
        uint16_t> info(
        a,
        f1.Timestamp(),
        f2.MaxLoad(),
        f3.MinLoad(),
        0,
        f4(),
        f5(),
        f6(),
        f7(),
        f8());

    status.time_count = boost::chrono::duration_cast<boost::chrono::milliseconds>
        (boost::chrono::steady_clock::now().time_since_epoch()).count();

    boost::function<
        void(const std::string&, const xbee::STATUS, const uint8_t *, const uint8_t)> function2 =
        boost::bind(&c::Handler::CommandStatus, m_x, _1, _2, _3, _4);

};
```

uncrustified code:
```
template<typename T1, typename T2>
class Class1
{
public:
    msgpack::type::tuple<uint16_t, uint16_t, int32_t, int32_t, uint16_t, uint16_t, float, float, float,
    uint16_t> info(
        a,
        f1.Timestamp(),
        f2.MaxLoad(),
        f3.MinLoad(),
        0,
        f4(),
        f5(),
        f6(),
        f7(),
        f8());

    status.time_count = boost::chrono::duration_cast<boost::chrono::milliseconds>
            (boost::chrono::steady_clock::now().time_since_epoch()).count();

    boost::function<
    void(const std::string&, const xbee::STATUS, const uint8_t *, const uint8_t)> function2 =
        boost::bind(&c::Handler::CommandStatus, m_x, _1, _2, _3, _4);

};
```

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
I need some more informations:
your configuration file for this example, and the expected output.
Could you push a source with less details?

**Comment by soeugene** [comment]
Here is a more compressed source and the debug.txt file.  Don't worry about the details.  I just need to make the line length for each of the three blocks long enough to cause continuation.  If you do a diff on the two files you'll see immediately the three issues.

[uncrustify_test.txt](https://github.com/uncrustify/uncrustify/files/1075327/uncrustify_test.txt)
[uncrustify_test_uncrustified.txt](https://github.com/uncrustify/uncrustify/files/1075328/uncrustify_test_uncrustified.txt)
[debug.txt](https://github.com/uncrustify/uncrustify/files/1075318/debug.txt)

**Comment by guy-maurel** [comment]
I asked for "less details" because it is more easier to debug a short source, with less token.
May be you could suppress some tokens and modify the other one to longer (more characters) tokens?

**Comment by soeugene** [comment]
Please try these files.

[debug.txt](https://github.com/uncrustify/uncrustify/files/1079002/debug.txt)
[uncrustify_test_uncrustified.txt](https://github.com/uncrustify/uncrustify/files/1079004/uncrustify_test_uncrustified.txt)
[uncrustify_test.txt](https://github.com/uncrustify/uncrustify/files/1079003/uncrustify_test.txt)

**Comment by guy-maurel** [comment]
I am working on it

**Comment by guy-maurel** [comment]
The line 9 should be:
`status.time_count = duration_cast<::milliseconds>`

**Comment by guy-maurel** [comment]
PR #1308 is a bugfix proposal.
Please test and report

**Comment by kaiser101** [comment]
Will this also address #1109 ?

**Comment by soeugene** [comment]
Seems to give me the same result as before.

[debug.txt](https://github.com/uncrustify/uncrustify/files/1208817/debug.txt)
[uncrustify_test_uncrustified.txt](https://github.com/uncrustify/uncrustify/files/1208819/uncrustify_test_uncrustified.txt)
[uncrustify_test.txt](https://github.com/uncrustify/uncrustify/files/1208818/uncrustify_test.txt)

**Comment by guy-maurel** [comment]
Have a look to the debug file. Is it what you wanted to have?

[m-b.p.txt](https://github.com/uncrustify/uncrustify/files/1215273/m-b.p.txt)

**Comment by gmaurel** [comment]
No answer, we close.
