### ISSUE TITLE
Trenary operator as receiver of Objective-C message makes parser explode.

### ISSUE THREAD

**Issue by DagAgren** [uncrustify/uncrustify#1162]
Unfortunately this codebase is proprietary and I can't post the file itself, but this line of Objective-C made the parser go completely mad:

    headerLabel.text = [ section< self.sectionHeaderTexts.count ? self.sectionHeaderTexts[section] : @"" uppercaseString];

I will happily take "Don't do that, then" as a solution, that is not a line of code you want to have in your codebase. Just thought I'd let you know.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

I get:
```
uncrustify -c DagAgren.cfg -f DagAgren.oc -l oc
Parsing: DagAgren.oc as language OC
headerLabel.text = [ section< self.sectionHeaderTexts.count ? self.sectionHeaderTexts[section] : @"" uppercaseString];
```

**Comment by gmaurel** [comment]
No answer, we close.
