### ISSUE TITLE
C++: incorrect indentation of lambda braces inside another lambda assigned to variable

### ISSUE THREAD

**Issue by parapaul** [uncrustify/uncrustify#1165]
Hi! There's an issue with C++ lambda braces indentation for nested lambdas in the following case:
```
C callback = 
        []()
        {
                C f([]()
                {
	                int i;
                });
        };
```
What I get is:
```
C callback =
        []()
        {
                C f([]()
        {
                int i;
        });
        };
```
And what I expect is the original code to be unchanged after it is uncrustifyed.
You can find debug file here: https://gist.github.com/parapaul/2b151d86cbc235f4cc24c2619111c663, uncrustify version I use is 0.64.

I want to point out that everything works as expected if there is no assignment sign in the beginning:
```
C callback([]()
{
        C f([]()
        {
                int i;
        });
});
```
By "works as expected" I mean that this last code snipped stays unchanged when uncrustifyed.

**Comment by guy-maurel** [comment]
Could you please push an source example which is compilable ?

**Comment by parapaul** [comment]
Sure,
`
#include <functional>

int main()
{
    typedef std::function<void ()> C;
    C callback =
        []()
        {
            C f([]()
        {
            int i;
        });
        };
}
`

**Comment by guy-maurel** [comment]
Please Test and report

**Comment by gmaurel** [comment]
The bug is fixed.
