### ISSUE TITLE
C++ Unexpected line break - class template instantiation

### ISSUE THREAD

**Issue by SayPing** [uncrustify/uncrustify#1171]
I am wondering why uncrustify adds a line break in middle of the template parameter list. The code width is 140.

A line break is added before the template parameter 'TInterface' but there is plenty of space left and the line break is not needed.

Is there an option available to avoid this line break ?

**Input**
```
class TestClass
{
public:
   ::foo::baaar::middlefooo::baaaaaaaar::moooon::FoooooooooooBaaaar<TFooooo, TFooBarFoo, TInterface>& operator=(const ::foo::baaar::middlefooo::baaaaaaaar::moooon::FoooooooooooBaaaar<TFooooo, TFooBarFoo, TInterface>& other)
   {
      return *this;
   }
}
```
**Generated output**
```
class TestClass
{
public:
   ::foo::baaar::middlefooo::baaaaaaaar::moooon::FoooooooooooBaaaar<TFooooo, TFooBarFoo, TInterface>& operator=(
         const ::foo::baaar::middlefooo::baaaaaaaar::moooon::FoooooooooooBaaaar<TFooooo, TFooBarFoo,
         TInterface>& other)
   {
      return *this;
   }

}
```

**Expected result**
```
class TestClass
{
public:
   ::foo::baaar::middlefooo::baaaaaaaar::moooon::FoooooooooooBaaaar<TFooooo, TFooBarFoo, TInterface>& operator=(
         const ::foo::baaar::middlefooo::baaaaaaaar::moooon::FoooooooooooBaaaar<TFooooo, TFooBarFoo, TInterface>& other)
   {
      return *this;
   }

}
```

Uncrustify version: Uncrustify-0.64-636-d7258b0

Uncrustify config:
[Uncrustify_config.txt](https://github.com/uncrustify/uncrustify/files/1011080/Uncrustify_config.txt)

**Comment by CDanU** [comment]
Can confirm. I get the same faulty results.

**Comment by SayPing** [comment]
Is there a chance, that this issue will be fixed soon?

**Comment by guy-maurel** [comment]
Yes! You work with us and push a new PR.

**Comment by guy-maurel** [comment]
It is not a bug.
Have a look to the option: `indent_paren_nl` you are using with the value `TRUE`
The description says: _If an open paren is followed by a newline, indent the next line so that it lines up after the open paren (not recommended)_
Change it to the default value `FALSE` and you get what you wanted to have.
Please test and report.

**Comment by mihaipopescu** [comment]
Could happen as @gmaurel said as you have `indent_paren_nl` and `code_width` set.

**Comment by gmaurel** [comment]
No answer, we close.
