### ISSUE TITLE
struct can not format correctly

### ISSUE THREAD

**Issue by ghost** [uncrustify/uncrustify#1172]
code like this:
struct tst_options options[] = {
	{
 .key  = { "key1"},
 .type = 1
    },
};

after format:
![image](https://cloud.githubusercontent.com/assets/2130033/26207024/fa20d216-3c18-11e7-90fe-1ab5b88531ba.png)
i use the default options, without any extra options, and the version is: uncrustify 0.63 on macos. How to let it format like this:
![image](https://cloud.githubusercontent.com/assets/2130033/26207043/0f2195ba-3c19-11e7-9006-fe488516555e.png)

**Comment by CDanU** [comment]
Thanks for the input, but we can't really work with images here, please post the examples as text in code blocks:
<pre>```[lang]
code
```
</pre>

**Comment by CDanU** [comment]
With this input:
```cpp
struct tst_options options[] = {
{
.key = { "key1"},
.type = 1
},
};
```
and an empty config I get this output:
```cpp
struct tst_options options[] = {
	{
		.key = { "key1"},
		.type = 1
	},
};
```

**Comment by gmaurel** [comment]
Is it what you are looking for?
Please test and report.

**Comment by CDanU** [comment]
This has been inactive for quiet a while and we still haven't received an answer so I am closing this. Reply if this is still a problem for you and I will reopen this issue.
