### ISSUE TITLE
Release 0.65

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1173]
The new release is available under https://sourceforge.net/projects/uncrustify/

```
  uncrustify-0.65.tar.gz
  uncrustify-0.65-win32.zip
  uncrustify-0.65-win64.zip
```

**Comment by mihaipopescu** [comment]
Awesome! Great job!

I've also seen https://github.com/uncrustify/uncrustify/releases/tag/uncrustify-0.nn What is that ?

**Comment by gmaurel** [comment]
It was a test before the tag was generated.

**Comment by CDanU** [comment]
Could you add the win binaries here as well? Btw. the SF link you posted above is broken.

**Comment by guy-maurel** [comment]
Could be find under https://sourceforge.net/projects/uncrustify/files/uncrustify/uncrustify-0.65/
