### ISSUE TITLE
Unwanted deletion of space between semicolon and "while".

### ISSUE THREAD

**Issue by CKD4XXH** [uncrustify/uncrustify#1176]
[debug.txt](https://gist.github.com/CKD4XXH/3229be312e88708f311af8a757aecb87)
```
do zzz(); while (qqq); //nnnnnn
```
```
Parsing: zz.c as language C
do zzz();while (qqq); //nnnnnn
```
I would like to keep that space.

**Comment by CDanU** [comment]
Yes I see the same, it is caused by the option `sp_after_semi = ignore`

**Comment by CDanU** [comment]
Turns out here is an option for that:
```sql
# If True, vbrace tokens are dropped to the previous token and skipped.
sp_skip_vbrace_tokens           = true     # false/true
```

**Comment by CKD4XXH** [comment]
With these settings: [debug.txt](https://gist.github.com/CKD4XXH/1c1745de18e34b16bf4e9524b2b0c52b)
the space is kept.
(I do not know what are vbaces, and could not find that setting myself..)
