### ISSUE TITLE
Version generation is broken

### ISSUE THREAD

**Issue by AMDmi3** [uncrustify/uncrustify#1177]
JFYI, for FreeBSD port I've had to remove whole version generation stuff, it would be nice to have it removed upstream as well (or at least a way to disable it), because it's terminally broken.

- it adds unneeded dependency on python
- it adds unneeded dependency on git
- it's unreliable as it may pick a tag from completely unrelated repository (if uncrustify source directory doesn't have .git, but some parent directory, say ~, does)
- it hinders reproducible builds

**Comment by CDanU** [comment]
While I agree that forcing to have CMAKE_BUILD_TYPE defined can be problematic and that the script currently is is not checking for the right .git directory is a problem I would not say that the generation is downright broken. 
The version string generation was intended to be used if python and git are available, if not the fallback string should be used. I forgot to remove the `find_package(PythonInterp REQUIRED)` stuff.

Would you still need an extra option to remove the version string generation if the problems I mentioned are fixed? I personally don't yet see how it would than hinder reproducible builds.

**Comment by AMDmi3** [comment]
Unfortunately, yes. I absolutely don't want to add python and git dependencies for no reason. If they are not added, build behavior will be inconsistent as it'll depend on whether git and python are actually available.

**Comment by CDanU** [comment]
I don't really see why you want to be so stringent on something that is only altering the version string, but I will make an option so that the fallback string will be used.

**Comment by AMDmi3** [comment]
> I don't really see why you want to be so stringent

I do not want anything beyond the most basic packaging requirements. I've already explained: package builds are required to be predictable, consistent and reproducible. Besides other things, they are only allowed to use depends which are explicitly defined in the package and should build the same way on a clean system where only these depends are available and on a real system where lots of third party packages are installed. Any optional dependency makes a build impossible to test, and each optional dependency makes a build an order of magnitude more fragile.

See also https://reproducible-builds.org/

> on something that is only altering the version string

Don't let yourself be deluded. For "only altering the version string" you're bringing in python (which can be of two incompatible major branches), 100+ lines of non-obvious python code using 6 modules, huge regexps, subprocess calling, complex system interaction and two third party utilities with their own massive complexity, list of depends, compatibility issues and lots of possible versions.

> but I will make an option so that the fallback string will be used even if python and git are around

Fine with me, thank you!

> The main reason for why we use info that is provided by git

I doubt that would be helpful for you, as most people will install uncrustify from packages which will not have git info the same way as FreeBSD package won't. On the other hand, people installing from git are skilled enough to provide you the exact commit and much more useful info the script won't give you anyway.

**Comment by InfernoZeus** [comment]
Struggling with this problem as well. It doesn't make sense that if I download the 0.65 tar from the releases section of Github, and then build following the instructions, I end up with a version of "Uncrustify-0.65_f". This is a different format than in the past when it used to be "Uncrustify 0.XX". Is this an intended change?

It was fine until commit https://github.com/uncrustify/uncrustify/commit/bed25c6f4525f09498ff90cf5484e1b947f0666e#diff-af3b638bc2a3e6c650974192a53c7291 which added automatic computing of the version. It was almost fixed in commit https://github.com/uncrustify/uncrustify/commit/cebd65df4ac632736c044467f8bbad094ac423ce#diff-af3b638bc2a3e6c650974192a53c7291 with the fallback version.

**Comment by CDanU** [comment]
You did everything correct, this is an intended change.

**Comment by mihaipopescu** [comment]
We also had to change our scripts to handle the new version string format so yeah, the change added a little bit of friction.
