### ISSUE TITLE
align_number_left aligns to the right?

### ISSUE THREAD

**Issue by CKD4XXH** [uncrustify/uncrustify#1182]
[debug.txt](https://gist.github.com/CKD4XXH/d239a4eb17f624355827ef38a5a227f0)
Output is the same as input:
```
static struct aaa const yyy[] = {
	{"FFFFF", {{0xFFFFF, 0xFFFFF,     8}, {0xFFFF, 0xFFFFF, 0xFFFFF}}},
	{"AAA",   {{   0xFF, 0xFFFFF, 0xFFF}, {     0,       0,       0}}},
	{"OOOO",  {{0xFFFFF,     0xF, 0xFFF}, {     0,      22,       0}}},
	{"P",     {{ 0xFFFF, 0xFFFFF,   999}, {0xFFFF, 0xFFFFF, 0xFFFFF}}}
};
```
But if I change to `align_number_left=false` (so I request aligning right) then my numbers start to be **left**-aligned!... (Contradicting.)

A side-question: are struct initializers (body) always indented, and always with a full brace-indent level?

**Comment by CDanU** [comment]
Those are the options involved: 
```sql
# Whether to left-align numbers
align_number_left               = true     # false/true

# The span for aligning struct initializer values (0=don't align)
align_struct_init_span          = 1        # unsigned number
```

This is a nice example for the `align_number_left` option.

As you can see you get a __right__ align if `align_number_left=true` and a __left__ align if `align_number_left=false`. 
So I guess the option was named incorrectly? In this case I'd suggest renaming the option to `align_number_right`.

**Comment by CDanU** [comment]
The option was renamed quiet some time ago. Reply if this is still a problem for you and I will reopen this issue.
