### ISSUE TITLE
Hangs when parsing

### ISSUE THREAD

**Issue by alkatena** [uncrustify/uncrustify#1183]
Hi, I'd like to report the next issue I've come across with:

When running `uncrustify -c <config> <file>` in a specific file, it hangs and I have to terminate the execution, of course without parsing the file (also tried with -p debug.txt, no output is generated).

The line  which causes this bug looks like this (the selected one)

![screen shot 2017-05-23 at 1 50 33 pm](https://cloud.githubusercontent.com/assets/8377637/26368507/3b222140-3fc8-11e7-8ecf-d4ae4fe15c6a.png)

and when I move it above (as it's supposed to be):

![screen shot 2017-05-23 at 12 47 21 pm](https://cloud.githubusercontent.com/assets/8377637/26368575/665a1eda-3fc8-11e7-86ec-c17caff46d2f.png)

the program runs fine.

Version: 0.65_f (it doesn't happen in 0.64).

Regards,
Mauricio

**Comment by CDanU** [comment]
Thanks for the report but images are less than ideal to work with, pleas read the [ISSUE_TEMPLATE](https://github.com/uncrustify/uncrustify/blob/master/.github/ISSUE_TEMPLATE)

**Comment by guy-maurel** [comment]
Please push as files:
- your configuration
- your source file.

**Comment by gmaurel** [comment]
No answer --> I close the call.
