### ISSUE TITLE
Feature request: differentiate array declarations from array (member) use.

### ISSUE THREAD

**Issue by CKD4XXH** [uncrustify/uncrustify#1184]
I guess that in current Uncrustify version if I state `sp_before_square=remove` and `sp_before_squares=remove` then all spaces will be removed, even at variable declarations.
Perhaps it would be nice to have an option to differentiate, similarly to the differentiation with function definitions and function calls.
Desired:
```
char buf [2000];
...
buf[0] = 5;
buf[1] = 6;
```
It could ease locating the "definition" of the array.

**Comment by guy-maurel** [comment]
PR #2534 is a bugfix proposal.
Please test it and report.
