### ISSUE TITLE
Crash when processing a file with only defines and comments

### ISSUE THREAD

**Issue by ceeac** [uncrustify/uncrustify#1187]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

When processing a file with only comments and defines, uncrustify crashes.

OS version: **Ubuntu 16.04 (64 bit)**
Uncrustify version: **Uncrustify_d-0.65-10-89e8bc9**

Gist with file and uncrustify cfg:
`https://gist.github.com/ceeac/17be512d424271dd1c96abc7824a0220`

Steps to reproduce:  Run uncrustify with
`uncrustify --no-backup -c ./uncrustify.cfg  -l CPP config.h`

Backtrace:
```
#0  0x00000000004a18db in combine_labels ()
    at /home/ceeac/Documents/CPP/uncrustify/src/combine.cpp:3071
#1  0x0000000000521d85 in uncrustify_start (data=std::deque with 906 elements = {...})
    at /home/ceeac/Documents/CPP/uncrustify/src/uncrustify.cpp:1663
#2  0x0000000000521f24 in uncrustify_file (fm=..., pfout=0x7e7bb0, parsed_file=0x0, 
    defer_uncrustify_end=false) at /home/ceeac/Documents/CPP/uncrustify/src/uncrustify.cpp:1718
#3  0x000000000052127f in do_source_file (
    filename_in=0x7fffffffe1fd "src/libboom/include/config.h", 
    filename_out=0x7fffffffd8c0 "src/libboom/include/config.h", parsed_file=0x0, no_backup=true, 
    keep_mtime=false) at /home/ceeac/Documents/CPP/uncrustify/src/uncrustify.cpp:1312
#4  0x000000000051fa6e in main (argc=7, argv=0x7fffffffddd8)
    at /home/ceeac/Documents/CPP/uncrustify/src/uncrustify.cpp:793
```

**Comment by guy-maurel** [comment]
Without pushed files: configuration and source(s) is it for us not possible to reproduce.
Please push!

**Comment by ceeac** [comment]
The necessary files are in the gist I provided.

**Comment by gmaurel** [comment]
The bug is fixed
