### ISSUE TITLE
Braces in macros

### ISSUE THREAD

**Issue by orenbenkiki** [uncrustify/uncrustify#1192]
Given the input:
```c
#define A {
#define B }
```
I get the error:
```
Parsing: 24 bytes (24 chars) from stdin as language C
Unmatched BRACE_CLOSE
at line=2, column=11
```
With:
```sh
$ uncrustify -v
Uncrustify-0.65-18-c6ce3fb
```

**Comment by guy-maurel** [comment]
Have a look to:
https://github.com/uncrustify/uncrustify/wiki/Known-Problems
please.

**Comment by orenbenkiki** [comment]
My bad, I missed that page.

I discovered I can work around the problem by surrounding the offending macros with `// *INDENT-OFF*` ... `// *INDENT-ON*`. I have mercifully few such macros, for using the C `check` unit test library.

Thanks!
