### ISSUE TITLE
Don't indent comment lines between \code or \verbatim

### ISSUE THREAD

**Issue by rolandschulz** [uncrustify/uncrustify#120]
Doxygen uses \code ... \endcode and \verbatim ... \endverbatim. It would be nice if comment lines between those two commands would not be indented.
E.g. 
``` C
/*! Some comment
 * \code
printf("something");
 * \endcode
 */
```
The printf shouldn't be indented/aligned. One can use cmt_indent_multi=false as a workaround but of course this disables all indentation not just this specific one.

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
