### ISSUE TITLE
Unwanted deletion of semicolon after something like   return vector<int>{1};

### ISSUE THREAD

**Issue by deepseer** [uncrustify/uncrustify#1207]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Uncrustify 0.6.5

Original file:
```
typedef vector<int> VI;
VI func() {
return vector<int>{1};
}
```
It is compiled in g++ 4.8.4 with -std=c++11

Uncrustified file:
```
typedef vector<int> VI;

VI func()
{
  return vector<int>{ 1 }
}
```

```
error: expected ‘;’ before ‘}’ token
 }
 ^
```

**Comment by guy-maurel** [comment]
It works pretty fine for me with an empty configuration file.
1. What is "vector"?
2. Please push your configuration file.

**Comment by deepseer** [comment]
It's a C++ source file. I only posted the relevant part.
`include`, `using namespace std` and `main()` were omitted.
Source file and configuration file have been uploaded to my repository: https://github.com/deepseer/deepseer_repository
