### ISSUE TITLE
Feature Request: sp_after_ellipsis (Ellipsis in Obj-C)

### ISSUE THREAD

**Issue by ferologics** [uncrustify/uncrustify#1213]
I'm using the [`...` in a case statement](https://stackoverflow.com/questions/5327896/how-to-use-ellipsis-in-cs-case-statement)

```objc
switch (foo)
{
  case 0 ... 1: break;
}
```

Uncrustify will remove the ` ` spaces around the operator:

```objc
switch (foo)
{
  case 0...1: break;
}
```

This causes error:
<img width="193" alt="uncrustify_error" src="https://user-images.githubusercontent.com/5576161/27375292-fb054c14-566e-11e7-85f7-58188aa9c921.png">

 What can I use to change the behavior? I googled this for 20 minutes without any results.

EDIT: It also adds a space after the `-` eg.
```objc
switch (foo)
{
  case -10...- 20: break;
}
```

**Comment by CDanU** [comment]
Check if the PR fixes your problem (it should) without opening new bugs.

**Comment by CDanU** [comment]
So?

**Comment by CDanU** [comment]
@mihaipopescu could you test that?

Seeing that the link that he provided is about a gcc extension, is this even useful in OC?  I am closing the PR temporarily.

**Comment by Krizai** [comment]
@CDanU Didn't know about this extension, but true - it exists and is supported in clang.

**Comment by mihaipopescu** [comment]
Totally missed that message. The fix looks good to me.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
