### ISSUE TITLE
Don't split one-line braced C++ uniform initializations

### ISSUE THREAD

**Issue by skycetus** [uncrustify/uncrustify#1214]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

I need an option like nl_assign_leave_one_liners for C++11 uniform initialization:

`# Don't split one-line braced assignments - 'foo_t f = { 1, 2 };'`
`nl_assign_leave_one_liners      = true     # false/true`

`# Don't split one-line braced C++ uniform initializations - 'foo_t f { 1, 2 };'`
`...?`

**Comment by CDanU** [comment]
Could you add examples that shows when an break happens?

**Comment by skycetus** [comment]
Yes, I do.
[example.zip](https://github.com/uncrustify/uncrustify/files/1108902/example.zip)

**Comment by guy-maurel** [comment]
You are using the option `nl_after_brace_open = true`
which splits `int c {1};`
Use the default value and you get what you wanted to have.
