### ISSUE TITLE
Wrong formatting

### ISSUE THREAD

**Issue by vd3d** [uncrustify/uncrustify#1217]
Hi,

When formatting the following code :

    ::new(&_pointer) std::exception_ptr { rhs._pointer };

I got this :

::new(&_pointer) std::exception_ptr {
    rhs._pointer
};

But the { } are just initialization parenthesis, not scope delimiters !

**Comment by CDanU** [comment]
Read the [ISSUE_TEMPLATE](https://github.com/uncrustify/uncrustify/blob/master/.github/ISSUE_TEMPLATE )

Your example stays the same with the default config. I need the config that you used for this.

**Comment by CDanU** [comment]
This has been inactive for quiet a while and I still haven't received an answer so I am closing this. Reply if this is still a problem for you and I will reopen this issue.
