### ISSUE TITLE
Unexpected alignment on return

### ISSUE THREAD

**Issue by AwesomeLemon** [uncrustify/uncrustify#1220]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
Hello.
I can't quite understand why 'return' aligns values the way it does.
The input:
```
return foooooooooooooooooooooooooooo(a, b,
		c + d, e -f);
foooooooooooooooooooooooooooo(a, b,
		c + d, e -f);
```
The output:
```
return foooooooooooooooooooooooooooo(a, b,
			   c + d, e - f);
foooooooooooooooooooooooooooo(a, b,
		c + d, e - f);
```
On the next line after return I get 3 tabs and 3 spaces, while I expect to get 2 tabs. (like in second call of 'foo' [without 'return']).
I haven't been able to find return-concerning options in the config.
I'm using the latest Uncrustify (built from sources): Uncrustify-0.65-69-0f5a557-dirty
Debug file: https://gist.github.com/AwesomeLemon/78fb454a554aaf95906122bc491b8296

There exists a somewhat similar issue: https://github.com/uncrustify/uncrustify/issues/1071 , but the proposed solution of creating option with tabs-only alignment is irrelevant here.

**Comment by CDanU** [comment]
Sooo how often does one find a return that is not inside of a function body? I'd say zero times (and hope that none can prove me wrong)

Despite of this, we should check that Uncrustify is doing only crazy (not __unsafe__) things.

I wrapped your example into a function and can conclude that:
- empty.cfg works
- Removing
  ```sql
  indent_continue                 = 8
  ```
  generates this beauty:
  ```cpp
  void f()
  {
  	return foooooooooooooooooooooooooooo(a, b,
  										 c + d, e - f);
  
  	foooooooooooooooooooooooooooo(a, b,
  								  c + d, e - f);
  }
  ```
  removing 
  ```sql
  indent_with_tabs                = 2
  ``` 
  after that fixes it.
  The options can be broken down to:
  ```sql
  output_tab_size                 = 4
  indent_with_tabs                = 2
  ```

**Comment by AwesomeLemon** [comment]
1) Of course 'return' was inside of function, I've just thought that it wasn't that relevant for the example
2) I can't quite understand what you suggest me to do: I can't remove these options for they're relevant for the code style. Could you please explain what you mean?
Maybe when you say 'removal of those pairs works' you mean that it results in the same output both for 'return foo' and 'foo' cases?

**Comment by CDanU** [comment]
It was more or less note a for myself for later when I am actually dealing with this issue.
I am fairly certain that the generated output with your configuration is buggy.

If the pair of options is removed than the generated outputs looked sane to me. Unfortunately that does not help you as you need those three options.

**Comment by AntonKozlov** [comment]
Hi, 

I face same issue. Testing on 
```
$ cat t.c
int v(void) {
        x = a ||
                        asdf1;

        return a ||
                        asdf2;
}
```
```
$ cat -t t.c 
int v(void) {
^Ix = a ||
^I^I^Iasdf1;

^Ireturn a ||
^I^I^Iasdf2;
}
```
```
$ uncrustify -v
Uncrustify-0.65_f
```
```
$ cat cfg.ini 
indent_continue = 16 
indent_with_tabs = 2
```
```
$ uncrustify -c cfg.ini -f t.c | cat -t
Parsing: t.c as language C
int v(void) {
^Ix = a ||
^I^I^Iasdf1;

^Ireturn a ||
^I       asdf2;
}

```
I'd expect no alignment for `asdf2` in return statement. Is it a bug or misconfiguration?

**Comment by simonbrunel** [comment]
Similar issue with continuation indent after keywords (`return`, `throw`, etc?).

Trying to get the following output:
```cpp
// EXPECTED
float foo(float a, float b, float c)
{
    float bar = a  // indent: 4
        + b        // indent: 8
        + c;       // indent: 8

    return a       // indent: 4
        + b        // indent: 8
        + c;       // indent: 8
}
```
with:
```
indent_columns = 4
indent_continue = 0
indent_with_tabs = 0
```

But uncrustify generates:
```cpp
// ACTUAL
float foo(float a, float b, float c)
{
    // OK
    float bar = a  // indent: 4
        + b        // indent: 8
        + c;       // indent: 8

    // BUG?
    return a       // indent: 4
           + b     // indent: 11
           + c;    // indent: 11
}
```

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
With the config:
```
sp_assign=force
indent_columns = 4
indent_continue = 0
indent_with_tabs = 0
```
I get, all continuation lines are align to the beginnig of the expression:
```
float foo(float a, float b, float c)
{
    float bar = a
                + b
                + c;

    return a
           + b
           + c;
    z = a
        + b
        + c;
}
```

**Comment by simonbrunel** [comment]
@guy-maurel actually, I'm trying to achieve the opposite:

```cpp
float foo(float a, float b, float c)
{
    float bar = a   // indent: 4
        + b         // indent: 8
        + c;        // indent: 8

    return a        // indent: 4
        + b         // indent: 8
        + c;        // indent: 8

    xz = a          // indent: 4
        + b         // indent: 8
        + c;        // indent: 8
}
```

Does it work for you?

**Comment by guy-maurel** [comment]
@simonbrunel : could you please open a new issue for your problem?
It would be easier for us to process different cases.
