### ISSUE TITLE
Break a span at a blank line?

### ISSUE THREAD

**Issue by JRutledg** [uncrustify/uncrustify#1222]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Is it possible (if not, I guess this is a feature request) to stop the various span based options from considering code the other side of a blank line? For example:

```c
int mything1 = 0;
int mything2 = 1;

int mything5 = 3;
int longthing97 = 4;
```

I would like to have longthing97 and mything5 align, but at the moment mything5 is aligning against mything2 because it is within the span, regardless of the blank line.

**Comment by CDanU** [comment]
Well I am missing your config but the option
```sql
# The span for aligning on '=' in assignments (0=don't align)
align_assign_span               = 1        # unsigned number
```

essentially counts the amount of newlines between two assignment equals chars to determine if the option is going to be applied. In your case there are _two_ newlines (not blank lines) between `mything2` and `mything5`. Therefore setting the option to _one_ should do what you want.

**Comment by JRutledg** [comment]
Sorry, I should have been clearer. I normally want the alignment span to be 2 lines, however I want my break up of the file via blank lines to override this behaviour. Effectively, let uncrustify operate as normal unless I've overridden its behaviour by inserting a blank line for my formatting purposes. Is that possible?

**Comment by CDanU** [comment]
The function works as I already described it. You either decrease the setting of the option or add more newlines. There is currently no other handling of this.

I still don't really get what it is that you actually want to achieve. Please show some examples of what you expect the end result to be.

**Comment by JRutledg** [comment]
"The function works as I already described it. You either decrease the setting of the option or add more newlines. There is currently no other handling for this."

Yes, that's what I understood, I thought this might be a feature request, but I was unsure!

I'm trying to lay out my code in such a way that uncrustify can understand that I have intentionally grouped things together with blank lines, so it should consider the blank line to indicate a premature span end, does that make sense?

So I want this sort of behaviour:

```
int mything1     = 0;
int mything2     = 1;
int mything5     = 3;
int longthing97  = 4;
```

And:

```
int mything1 = 0;
int mything2 = 1;

int mything5    = 3;
int longthing97 = 4;
```

**Comment by CDanU** [comment]
Ok, so do you essentially want that all blocks that are not cut by a blank line are aligned the same way? 
How is using `align_assign_span               = 1` to achieve this problematic?

**Comment by JRutledg** [comment]
[uncrustify.txt](https://github.com/uncrustify/uncrustify/files/1119743/uncrustify.txt)

I need to work on the complex and compilable example. I have something, but it will need obfuscating from its company confidential status and is not naturally compilable on its own.

**Comment by guy-maurel** [comment]
How to help you if you cannot push your data?

**Comment by CDanU** [comment]
This has been inactive for quiet a while and we still haven't received an answer so I am closing this. Reply if this is still a problem for you and I will reopen this issue.
