### ISSUE TITLE
New issues from UnityTechnologies

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1223]
Hey guys,

I've made an announcement also on[ uncrustify's googlegroup forum](https://groups.google.com/forum/#!forum/uncrustify) but I'm not sure if the message was received. I'm going to use github to send this message instead while this is not an actual issue.

We have gathered a lot of issues 60+ in our internal issue tracker. I have prepared some scripts to extract them and create github issues. I've been experimenting in my [fork](https://github.com/mihaipopescu/uncrustify/issues) which you can review upfront. I'm afraid though some of them will be quite confusing but I will get back with explanations.

Let me know if there are other concerns before proceeding.

Thanks,
Mihai

**Comment by CDanU** [comment]
Nope, I did not even know that there is a google group out there for Uncrustify.
There are some duplicates but the older ones of those had broken url's, so I assume the problem is fixed and the will be no duplicates in the end.

Some of the issues are a bit older but fortunately it appears that they (all?) have the full version string: `# Uncrustify 0.63.584-gd2d8b38e`
The issues where discovered in the unity fork right?
Some of the issues might not exists anymore, but other than that I see no problems. 

Btw. gmaurel will be unreachable for some weeks.

**Comment by mihaipopescu** [comment]
The googlegroup mailinglist was created to discuss general topics, design, architecture, plans, etc., not necessarily issues. Also, sometimes it's just too much noise on github. Do not hesitate to propose other means of communication.

Yes, the issues are created against our fork but they also fail against master. I'll re-run them on latest master and recreate the issues.

**Comment by mihaipopescu** [comment]
@CDanU I think I'll have to minimize the config as for some tests, we're using new options only present in our fork. I'm going to try your [option_reducer.py](https://gist.github.com/CDanU/54446524c8919b1d490147f6c8165bb6) script.

**Comment by mihaipopescu** [comment]
I assume the scripts don't support `include` and tests using the same config. I'll make some scripts to satisfy these requirements.

**Comment by CDanU** [comment]
No, includes are not supported, as my goal at that time was to remove them. 
It should be possible add that functionality, just don't forget that at a later point in the config the included options can be overwritten by the local options.

**Comment by mihaipopescu** [comment]
Ok, cool. I was using `auto_reducer.py`. Btw, nice scripts. Would be very nice to have them in uncrustify.

**Comment by CDanU** [comment]
The problem is that there is a bug somewhere in `option_reducer.py` as it sometimes deletes the wrong options or leaves options that could be removed. It is most likely a logical bug. Some options are quiet intertwined, maybe it is related to the order in which the options are removed.

Also I had to find out that pythons threading apparently does not really use multiple cores (global interpreter lock - GIL). It just processes something else while it is waiting for I/O.

**Comment by mihaipopescu** [comment]
How does it generate the configs ? How do you remove the config options ?
Looking at the code, I see that you are removing them one by one and checking if the output is preserved. If not, the option is important and should not be removed. Right?

Also, `set` doesn't seems to work, even if there is code that should handle it.

```
set = MACRO_FUNC                   ATTRIBUTE_ALIGN
set = COMMENT                      F_STDCALL
set = COMMENT                      PLATFORM_EXCEPTION_SAFEGUARD_PROLOG
set = COMMENT                      WINAPI
set = COMMENT                      __cdecl 
```

If I can't make it work, I might just end up commenting our options and see if they produce the same result. I don't think the bugs are not dependent on the options we've added but I thought it would be nice if we can have the configs reduced.

**Comment by CDanU** [comment]
>How does it generate the configs ? How do you remove the config options ?
Looking at the code, I see that you are removing them one by one and checking if the output is preserved. If not, the option is important and should not be removed. Right?

Yes that is how it works.
I'll take a look later that day to see whats wrong with the `set`.
Reducing the configs is always nice, the options that are unknown to Uncrustify should be removed, if the formatting depends on it the script will complain that it can't generate the result from the get go (first sanity run).

**Comment by mihaipopescu** [comment]
To support `include` I've wrote [this script](https://github.com/Unity-Technologies/uncrustify/blob/accept-staging-tests/scripts/dry_config.py) to take the non-default options using uncrustify. It could be a first step in the option remover script.

**Comment by CDanU** [comment]
Yes, that works if you don't mind that the include is removed.

**Comment by CDanU** [comment]
Btw. an empty input file with this command should be better: `uncrustify --check -c cfg -f t.cpp -p dbg`

**Comment by mihaipopescu** [comment]
Ok, I've made a fork but we can have a branch against upstream and we can put them in the `scripts` folder (where I suppose you have them).

Yes, using an empty file would be better (unsure if `/dev/null` will work on Windows though - could be just `nul`).

**Comment by mihaipopescu** [comment]
But actually my idea was to generate new configs and leave the old ones behind and edit the `.test` file instead. If, at the end of the process there are orphan configs we can remove them. It's complicated with `include` directive as you can't just edit those base config files.

**Comment by CDanU** [comment]
In cases where a bunch of tests used for example `ben.cfg`, I grepped every test that used that config and them with the `ben.cfg` into the script to reduce the options across all tests.
Later I just copied that `ben.cfg` N times for each test. and the reduced for each specific test.
The include files where handled by just replacing (manually if I remember) the include directive with the file contents.

**Comment by guy-maurel** [comment]
Fine!
Lets go on.

**Comment by mihaipopescu** [comment]
First batch of issues are created. I've realised that the config is not helpful as it's includes are not resolved but it can be extracted with a little bit of work out of the `.unc` file. I can create also a PR against master with all staging tests. Maybe that will help.

**Comment by mihaipopescu** [comment]
If it helps, unlike other issues, the last batch of 9 issues: #1284, #1285, #1286, #1287, #1288, #1289, #1290, #1291 and #1292 are regressions introduced between 0.63 and latest master.

**Comment by mihaipopescu** [comment]
Thanks @CDanU for taking a first dive on most of the issues posted.

**Comment by guy-maurel** [comment]
@mihaipopescu : All the issues are solved, Thanks to UT people!
Please make a test with the current git master, report and move back.

**Comment by mihaipopescu** [comment]
Will do, thanks @gmaurel!
