### ISSUE TITLE
C# Interpolated strings on new line

### ISSUE THREAD

**Issue by JoeMug** [uncrustify/uncrustify#1224]
Hi,
A error occurs after formatting  the following method with the attached config and uncristify 0.65, because the interpolated string is not recognised.
The original method:
 private void AnyMethod()
    {
      var dialogMessage =
        $"{p_Object.Title} \n {p_Object.Instruction} \n {p_Object.Content} \n {p_Object.ExpandedText}";
    }

The actual result after formatting:
 private void AnyMethod()
    {
      var dialogMessage =
        $ "{p_Object.Title} \n {p_Object.Instruction} \n {p_Object.Content} \n {p_Object.ExpandedText}";
    }

The expected result, (same as the original):
 private void AnyMethod()
    {
      var dialogMessage =
        $"{p_Object.Title} \n {p_Object.Instruction} \n {p_Object.Content} \n {p_Object.ExpandedText}";
    }
https://linkToTheFile)"
[InterpolatedStringsIssue.zip](https://github.com/uncrustify/uncrustify/files/1127374/InterpolatedStringsIssue.zip)

Regards 
Hannes

**Comment by mihaipopescu** [comment]
First of all, some remarks about formatting. Please see https://help.github.com/articles/creating-and-highlighting-code-blocks/ for more info about how to properly write code snippets. Also, please remove the executable from the zip file. Is not needed and usually dangerous... I'm not clicking that!

Secondly, I'm not sure why the interpolated strings don't work in this version. Can you try with `0.64` or `0.63` to see if there is a regression ? Our [fork](https://github.com/Unity-Technologies/uncrustify), based on `0.63` properly supports interpolated strings. I remember we've done a lot of fixes in that area which I'm not sure if I've PR-ed here.

**Comment by JoeMug** [comment]
Hi Mihai,
It is in fact a regression from version 0.63 to 0.64. With version 0.63 the interpolated string on the new line is recognised correctly.

Regards
Hannes

**Comment by mihaipopescu** [comment]
We have a test in our fork https://github.com/Unity-Technologies/uncrustify/blob/master/tests/input/staging/UNI-3484.cs and it fails terribly on upstream:
```
input/staging/UNI-3484.cs:4 Garbage in col 54: 5c
input/staging/UNI-3484.cs:5 Garbage in col 63: 5c
input/staging/UNI-3484.cs:8 Garbage in col 40: 5c
input/staging/UNI-3484.cs:24 Garbage in col 8: 5c
input/staging/UNI-3484.cs:24 Garbage in col 9: 5c
input/staging/UNI-3484.cs:24 Garbage in col 10: 5c
input/staging/UNI-3484.cs:24 Garbage in col 20: 5c
input/staging/UNI-3484.cs:24 Garbage in col 26: 5c
input/staging/UNI-3484.cs:40 Garbage in col 31: 5c
Unmatched BRACE_CLOSE
at line=25, column=1
FAILED: 10078
```

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
I get:
```
private void AnyMethod()
{
        var dialogMessage =
                $"{p_Object.Title} \n {p_Object.Instruction} \n {p_Object.Content} \n {p_Object.Expand
edText}";
}

using System;

namespace StringInterpolationTest
{
public partial class Test
{
private void AnyMethod()
{
        var dialogMessage =
                $"{p_Object.Title} \n {p_Object.Instruction} \n {p_Object.Content} \n {p_Object.Expand
edText}";
}
}
}

```

**Comment by gmaurel** [comment]
Is it what you are looking for?
Please test and report.
