### ISSUE TITLE
Debian #867376

### ISSUE THREAD

**Issue by CDanU** [uncrustify/uncrustify#1229]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867376

**Comment by gerasiov** [comment]
I did some research, results are in #1231 

I do not think, that one should try to fix v0.65, for Debian I'll just exclude it for now from s390x, ppc64 and sparc64. But there are still problems exists on master with my patches: 268 tests fail. I hope this could be fixed for next release.

I'll right more information here about tests failure later.

**Comment by mihaipopescu** [comment]
Maybe we could also add at least `ppc64` and `sparc64` to travis test matrix. We have not supported Solaris systems before but it would be interesting to start supporting some RISC architectures as well.

Tangentially, we've got an `arm` build working on android (which is quite nice if you want to work on an android tablet).

**Comment by gmaurel** [comment]
Yes! How to do it?

**Comment by mihaipopescu** [comment]
I don't know. Maybe follow https://github.com/rust-lang/rust/blob/master/.travis.yml or using docker https://github.com/rust-lang/rust/pull/39647.

**Comment by gerasiov** [comment]
@mihaipopescu all arm tests passed in Debian without problem. You can check matrix here: https://buildd.debian.org/status/package.php?p=uncrustify

**Comment by mihaipopescu** [comment]
That is so cool. I didn't even knew uncrustify was compiled on so many architectures. Thanks for all the effort !

**Comment by guy-maurel** [comment]
@mihaipopescu : Is it possible to add a command to the file `run_test.cmake` to get more informations within `if(files_are_different)` such as `more ${TEST_RESULT}`
and (maybe) stop the process ?

**Comment by gmaurel** [comment]
Thanks for the PR

**Comment by mihaipopescu** [comment]
> Is it possible to add a command to the file run_test.cmake to get more informations within if(files_are_different) such as more ${TEST_RESULT}
and (maybe) stop the process ?

Can you elaborate? I don't understand the relation with this issue.

**Comment by guy-maurel** [comment]
Yes.
The bug report: `https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867376` shows that we had a
problem. The output of the test script was very, very big. Because the same error which produces
many lines of output, was call many times.
It would be fine to detect that, make a little more output for debugging _if(files_are_different) such as more ${TEST_RESULT}_ and stop the test script, to only get the error one time. This is the relation.
But: How to add this?

**Comment by mihaipopescu** [comment]
I don't fully understand. Is it because there are a lot of logs from tests and they generate huge log files?

What is the problem ? What is that file or files responsible ? What is the redundant information we are printing in the logs which we can get rid of ?

**Comment by gerasiov** [comment]
Nope. The problem was in AT_UNUM vs AT_NUM conversion. And it was fixed in #1231

Some variables was VERY huge (e.g. indent 8589934592) and generated huge files during testing.

**Comment by mihaipopescu** [comment]
Thanks, this is why I've asked. Then @gmaurel's may be talking about something else...
