### ISSUE TITLE
Extra indent if aligning isn't possible

### ISSUE THREAD

**Issue by rolandschulz** [uncrustify/uncrustify#123]
It would be nice if the options indent_func_param_double and/or indent_continue could be used together with alignment. If there is something to align they should be ignored, but for continuation line which has nothing to align (e.g. linewrap before first function parameter, or wrapped typedef or constructor call), then these options should take effect to influence extra indentation in these cases. 
Alternative there could be an extra option, which would give the indentation level for continuation lines which can't be aligned.

**Comment by gmaurel** [comment]
Is this yet actual?
Could you have a look to the actual git version
  https://github.com/uncrustify/uncrustify

and report.
Thanks.

**Comment by guy-maurel** [comment]
With this option one can use both values of the options ```indent_columns``` and ```indent_param```
