### ISSUE TITLE
Fix alignment underneath #if/else/def/ndef

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1233]
Contents of preprocessor control flow are indented, and Uncrustify (sometimes?) un-indents them. Except where the indented thing is a #if, in which case it leaves it. Result is weird.

We have a lot of issues with #if related indentation. The right fix is probably to have the most recent #if/else/def/ndef's indentation level be used as an adjustment for its contents. Just keep things relative and no more. And use the location of the 'if' and not the '#' in case it's on col 1 or whatever.

Important: if the # or if is on col 1, then do no adjustment to the contents. Maybe think about just altering if it's a negative adjustment?

Or perhaps we should just have Uncrustify totally ignore #if's wrt alignment of contents..

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10049-UNI-1336.cpp" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10049-UNI-1336.cpp"
index e470b1d..5b550e3 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10049-UNI-1336.cpp"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10049-UNI-1336.cpp"
@@ -1,26 +1,26 @@
 // Contents of preprocessor control flow are indented, and Uncrustify (sometimes?) un-indents them.
 // Except where the indented thing is a #if, in which case it leaves it. Result is weird.
 
 // We have a lot of issues with #if related indentation. The right fix is probably to have the most recent
 // #if/else/def/ndef's indentation level be used as an adjustment for its contents.
 // Just keep things relative and no more. And use the location of the 'if' and not the '#' in case it's on col 1 or whatever.
 
 // Important: if the # or if is on col 1, then do no adjustment to the contents. Maybe think about just altering if it's a negative adjustment?
 
 // Or perhaps we should just have Uncrustify totally ignore #if's wrt alignment of contents..
 
 // Platform
 #if defined(__APPLE__)
 #   if !(defined(__arm__) || defined(__arm64__))
 #       define OSX 1
 #   endif
 #elif (defined(_WIN32) || defined(__WIN32__))
 #   define WIN 1
 #elif (defined(linux) || defined(__linux__)) && !defined(ANDROID) \
     && !defined(STV) && !defined(TIZEN)
 #   define LINUX 1
 #endif
 
 #if WIN
-    struct Foo;
+struct Foo;
 #endif
```

Debug support files:
---
[10049-UNI-1336.cpp](https://gist.githubusercontent.com/mihaipopescu/4dd8192ecd8777eb7510ffd8dd48ec43/raw/e470b1d2209620bf29528545878e79e07e04bfaf/10049-UNI-1336.cpp)
[10049-UNI-1336.cpp.log](https://gist.githubusercontent.com/mihaipopescu/4dd8192ecd8777eb7510ffd8dd48ec43/raw/7ed95968f3d832f9488a004bfb0d3d838f165c56/10049-UNI-1336.cpp.log)
[10049-UNI-1336.cpp.unc](https://gist.githubusercontent.com/mihaipopescu/4dd8192ecd8777eb7510ffd8dd48ec43/raw/f323baeb91dfa846246228ddf93204f6a027f6a2/10049-UNI-1336.cpp.unc)
[Uncrustify.Cpp.cfg](https://gist.githubusercontent.com/mihaipopescu/4dd8192ecd8777eb7510ffd8dd48ec43/raw/23d62d9dba5caf352fdc1793792e98eed4b81929/Uncrustify.Cpp.cfg)
[UNI-1336.cpp](https://gist.githubusercontent.com/mihaipopescu/4dd8192ecd8777eb7510ffd8dd48ec43/raw/e470b1d2209620bf29528545878e79e07e04bfaf/UNI-1336.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by guy-maurel** [comment]
As there is no block (defined with `{`) is the indentation `1` OK.

**Comment by guy-maurel** [comment]
Related to #1611
