### ISSUE TITLE
Fix extern "C" block alignment

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1238]
Extern "C" blocks need an alignment option somehow. I can do a "set NAMESPACE extern" in the cfg but that will probably screw other stuff up.

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10057-UNI-1347.cpp" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10057-UNI-1347.cpp"
index 1fa65ab..362e1d3 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10057-UNI-1347.cpp"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10057-UNI-1347.cpp"
@@ -1,10 +1,10 @@
 // Extern "C" blocks need an alignment option somehow. I can do a "set NAMESPACE extern" in the cfg but that will probably screw other stuff up.
 
 // See External\Audio\NativePluginDemo\NativeCode\TeleportLib.h for an example. Yeah it's in external (so have to force-format it) but it's a good case.
 
 // (Actually it's in https://bitbucket.org/Unity-Technologies/nativeaudioplugins, but just published here to external)
 
 extern "C"
 {
-	typedef EXPORT_API int (*Foo)(int arg);
+typedef EXPORT_API int (*Foo)(int arg);
 };
```

Debug support files:
---
[10057-UNI-1347.cpp](https://gist.githubusercontent.com/mihaipopescu/0d1e7e942268ba13ffec724f0f0a0682/raw/1fa65abe3d103036ccbe48d82a92a589b64ce8c6/10057-UNI-1347.cpp)
[10057-UNI-1347.cpp.log](https://gist.githubusercontent.com/mihaipopescu/0d1e7e942268ba13ffec724f0f0a0682/raw/bd2c3d5cbe4d3f531690764f3602d0c0920c40bd/10057-UNI-1347.cpp.log)
[10057-UNI-1347.cpp.unc](https://gist.githubusercontent.com/mihaipopescu/0d1e7e942268ba13ffec724f0f0a0682/raw/6b2b31fcbd39478584705bce148d251ef29d3afb/10057-UNI-1347.cpp.unc)
[Uncrustify.Cpp.cfg](https://gist.githubusercontent.com/mihaipopescu/0d1e7e942268ba13ffec724f0f0a0682/raw/23d62d9dba5caf352fdc1793792e98eed4b81929/Uncrustify.Cpp.cfg)
[UNI-1347.cpp](https://gist.githubusercontent.com/mihaipopescu/0d1e7e942268ba13ffec724f0f0a0682/raw/362e1d38f5a0cd89f4923e191791bd04f34f6776/UNI-1347.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by gmaurel** [comment]
Fixed at 35f88c9cefe046a1d75642ea740e674f9f718963, Jan 17 17:48:43 2018
