### ISSUE TITLE
#pragma pack should indent just like a struct or typedef

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1239]
These should align normally with the parent scope. (Uncrustify leaves them alone, no matter what indentation level they're at.)

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10058-UNI-1348.cpp" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10058-UNI-1348.cpp"
index c3eca6d..4aa6ebe 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10058-UNI-1348.cpp"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10058-UNI-1348.cpp"
@@ -1,16 +1,16 @@
-// These should align normally with the parent scope. 
+// These should align normally with the parent scope.
 // (Uncrustify leaves them alone, no matter what indentation level they're at.)
 
 namespace dude
 {
-    namespace convert
+namespace convert
+{
+#pragma pack(1)
+    typedef struct
     {
-        #pragma pack(1)
-            typedef struct
-            {
-                unsigned char reserved3;
-                unsigned char name[16];
-            } HEADER;
-        #pragma pack()
-    }
+        unsigned char reserved3;
+        unsigned char name[16];
+    } HEADER;
+#pragma pack()
+}
 }
```

Debug support files:
---
[10058-UNI-1348.cpp](https://gist.githubusercontent.com/mihaipopescu/8fa05161d89845f54ac34cdf10f608fb/raw/c3eca6d5cd3d6d16353c43d522d41cd38fe6c73a/10058-UNI-1348.cpp)
[10058-UNI-1348.cpp.log](https://gist.githubusercontent.com/mihaipopescu/8fa05161d89845f54ac34cdf10f608fb/raw/f577a0f9aa6d1c88dc2493347a75fb6173a5eecd/10058-UNI-1348.cpp.log)
[10058-UNI-1348.cpp.unc](https://gist.githubusercontent.com/mihaipopescu/8fa05161d89845f54ac34cdf10f608fb/raw/c5a0537c2e6f7aeaa2d8b750dd6fc88442cf42fd/10058-UNI-1348.cpp.unc)
[Uncrustify.Cpp.cfg](https://gist.githubusercontent.com/mihaipopescu/8fa05161d89845f54ac34cdf10f608fb/raw/23d62d9dba5caf352fdc1793792e98eed4b81929/Uncrustify.Cpp.cfg)
[UNI-1348.cpp](https://gist.githubusercontent.com/mihaipopescu/8fa05161d89845f54ac34cdf10f608fb/raw/ca56ececde6947eaad20de0bf50f4ddeae7f50af/UNI-1348.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by KalyanaChakravarthi** [comment]
namespace indentation issue caused by the option indent_namespace_single_indent=true.
#pragma pack() is not a block preprocessor directive, so the indentation under #pragma pack() can not be achieved.

**Comment by mihaipopescu** [comment]
I agree with that resolution. I think this is a "will not fix".

**Comment by gmaurel** [comment]
OK. I close the call.
