### ISSUE TITLE
Closing brackets of message expressions in Objective-C when blocks are present are affected by nl_after_func_body preventing a more aesthetically appealing style

### ISSUE THREAD

**Issue by ghost** [uncrustify/uncrustify#124]
This is a request for an additional configuration option for formatting message expressions in Objective-C when a block is present in the message expression.

For blocks of this form

```
- (void) addInt:(int)x withInt:(int)y
{
    [ self printInt:(int) ^(int x, int y)  {
        x = 1;
        y = 2;
        return (int)(x + y);
    }

    ];
}
```

`nl_after_func_body` affects the positioning of the closing bracket. To get the appearance found in the [Google Objective-C Style Guide](http://google-styleguide.googlecode.com/svn/trunk/objcguide.xml) for blocks, the closing bracket should be allowed to be on the same line as the closing curly bracket of the block.

```
- (void) addInt:(int)x withInt:(int)y
{
    [ self printInt:(int) ^(int x, int y)  {
        x = 1;
        y = 2;
        return (int)(x + y);
    } ];
}
```

**Comment by guy-maurel** [comment]
Is the problem solved?

**Comment by gmaurel** [comment]
No answer, we close.
