### ISSUE TITLE
Get sp_inside_braces_struct working

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1240]
Can't set sp_inside_braces_struct=add otherwise Uncrustify starts applying it to initializers combined with old-C-style struct usage.

    struct in_addr addr = {0};
    ... --> ...
    struct in_addr addr = { 0 };

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10060-UNI-1350.cpp" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10060-UNI-1350.cpp"
index 8fc358d..e3a60f5 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10060-UNI-1350.cpp"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10060-UNI-1350.cpp"
@@ -1,5 +1,5 @@
 // Can't set sp_inside_braces_struct=add otherwise Uncrustify starts applying it to initializers combined with old-C-style struct usage.
 
-struct in_addr addr = {0};
+struct in_addr addr = { 0 };
 // ... --> ...
 struct in_addr addr = { 0 };
```

Debug support files:
---
[10060-UNI-1350.cpp](https://gist.githubusercontent.com/mihaipopescu/997dc0a9b7ef2ee45189b3756da8db78/raw/8fc358d54d30e89cd1f0d4c5344dea36cd92930e/10060-UNI-1350.cpp)
[10060-UNI-1350.cpp.log](https://gist.githubusercontent.com/mihaipopescu/997dc0a9b7ef2ee45189b3756da8db78/raw/8422878012a5fa42de5fe3ba4f506a68b2c51002/10060-UNI-1350.cpp.log)
[10060-UNI-1350.cpp.unc](https://gist.githubusercontent.com/mihaipopescu/997dc0a9b7ef2ee45189b3756da8db78/raw/52380e3f9c3d6a6d180af71edaa08641f363044e/10060-UNI-1350.cpp.unc)
[UNI-1350.cfg](https://gist.githubusercontent.com/mihaipopescu/997dc0a9b7ef2ee45189b3756da8db78/raw/6d0632ec76c048e7dc43dba5d6c9f177e74c2f67/UNI-1350.cfg)
[UNI-1350.cpp](https://gist.githubusercontent.com/mihaipopescu/997dc0a9b7ef2ee45189b3756da8db78/raw/8fc358d54d30e89cd1f0d4c5344dea36cd92930e/UNI-1350.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by gmaurel** [comment]
Fixed at 5098d6f7467491b1ce0896616ac6438da6334da0, Dec 28 10:29:21 2017
