### ISSUE TITLE
Formatting MIDL_INTERFACE classes

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1242]
Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10063-UNI-1358.cpp" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10063-UNI-1358.cpp"
index da2ec15..c2051eb 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10063-UNI-1358.cpp"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10063-UNI-1358.cpp"
@@ -1,15 +1,15 @@
 // MIDL_INTERFACE includes 'class' in its definition but is not tokenised as such
 // A pretty common pattern would be nice to have proper formatting.
 
 EXTERN_C const IID IID_IFileDialogEvents;
 
 MIDL_INTERFACE("973510db-7d7f-452b-8975-74a85828d354")
-IFileDialogEvents : public IUnknown
+IFileDialogEvents: public IUnknown
 {
 public:
     virtual HRESULT STDMETHODCALLTYPE OnStuff(
         /* [in] */ __RPC__in_opt IFileDialog *pfd,
         /* [in] */ __RPC__in_opt IShellItem *psi,
         /* [out] */ __RPC__out FDE_SHAREVIOLATION_RESPONSE *pGoodResponse,
         /* [out] */ __RPC__out FDE_OVERWRITE_RESPONSE *pBadResponse) = 0;
 };
```

Debug support files:
---
[10063-UNI-1358.cpp](https://gist.githubusercontent.com/mihaipopescu/8940e0716af96fb3b3dbc0e1c4230f86/raw/da2ec1523f2a5e44e62e203ff064dba0c2bb0d27/10063-UNI-1358.cpp)
[10063-UNI-1358.cpp.log](https://gist.githubusercontent.com/mihaipopescu/8940e0716af96fb3b3dbc0e1c4230f86/raw/b90ded3fc8a67c49bd13f1465ad497316459d86f/10063-UNI-1358.cpp.log)
[10063-UNI-1358.cpp.unc](https://gist.githubusercontent.com/mihaipopescu/8940e0716af96fb3b3dbc0e1c4230f86/raw/aa562b65542fe7eb168716b5f161d6b6f95cafce/10063-UNI-1358.cpp.unc)
[Uncrustify.Cpp.cfg](https://gist.githubusercontent.com/mihaipopescu/8940e0716af96fb3b3dbc0e1c4230f86/raw/23d62d9dba5caf352fdc1793792e98eed4b81929/Uncrustify.Cpp.cfg)
[UNI-1358.cpp](https://gist.githubusercontent.com/mihaipopescu/8940e0716af96fb3b3dbc0e1c4230f86/raw/60e89ceed7a1bd0f304c53260f4691c15694586c/UNI-1358.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by gmaurel** [comment]
Fixed at f6276899bca10209efc5336feb4a4b632f626df8, Jan 22 20:46:32 2018
