### ISSUE TITLE
Fix space added in generic type name

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1243]
`typeof(Dictionary<,>)` is getting changed to `typeof(Dictionary<, >)`

(space added after comma)

Definitely not typical for C#. Needs special handling.

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10065-UNI-1975.cs" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10065-UNI-1975.cs"
index fd4debb..4c048ec 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10065-UNI-1975.cs"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10065-UNI-1975.cs"
@@ -1,23 +1,23 @@
 // typeof(Dictionary<, >)
 
 // is getting changed to
 
 // typeof(Dictionary<, >)
 
 // (space added after comma)
 
 // Definitely not typical for C#. Needs special handling.
 
 public class Class
 {
     public void foo(Type type)
     {
         if (type == typeof(List<>))
         {
         }
-        else if (type == typeof(Dictionary<,>))
+        else if (type == typeof(Dictionary<, >))
         {
-            var bar = typeof(Dictionary<,>).Bar();
+            var bar = typeof(Dictionary<, >).Bar();
         }
     }
 }
```

Debug support files:
---
[10065-UNI-1975.cs](https://gist.githubusercontent.com/mihaipopescu/bb8ca7c94aa69e481a88c8dafa24b42d/raw/fd4debb7e3e6030c61247211558547fae3d7f2b5/10065-UNI-1975.cs)
[10065-UNI-1975.cs.log](https://gist.githubusercontent.com/mihaipopescu/bb8ca7c94aa69e481a88c8dafa24b42d/raw/b8b650ccb8cc63b13ea820792c72336fbfbb57d9/10065-UNI-1975.cs.log)
[10065-UNI-1975.cs.unc](https://gist.githubusercontent.com/mihaipopescu/bb8ca7c94aa69e481a88c8dafa24b42d/raw/dd8a39fdfe6277d4d4e0a9d864fa8f4fee19afb2/10065-UNI-1975.cs.unc)
[Uncrustify.CSharp.cfg](https://gist.githubusercontent.com/mihaipopescu/bb8ca7c94aa69e481a88c8dafa24b42d/raw/1d064c1fabb76ce328dd015ed40023207de20ca1/Uncrustify.CSharp.cfg)
[UNI-1975.cs](https://gist.githubusercontent.com/mihaipopescu/bb8ca7c94aa69e481a88c8dafa24b42d/raw/613035dfd99cc59bfb9794c7aecb48ef0e005f57/UNI-1975.cs)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by gmaurel** [comment]
Fixed at 23c01ed1d151a0770a55ec3526204249405f76e1, Dec 29 17:59:24 2017
