### ISSUE TITLE
Fix issue where tab preceding comment will not get tab-to-space conversion

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1244]
We specifically avoid our own tab-space in GenericFormat because of the @"" issue. So we must rely on Uncrustify getting it right, and it nearly does - except for the "Layout has changed, bail out now" where it does not replace the tab preceding the comment.

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10066-UNI-1977.cs" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10066-UNI-1977.cs"
index 4331fff..7f11f7f 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10066-UNI-1977.cs"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10066-UNI-1977.cs"
@@ -1,18 +1,18 @@
 // We specifically avoid our own tab-space in GenericFormat because of the @"" issue.
 // So we must rely on Uncrustify getting it right, and it nearly does - except for the
 // "Layout has changed, bail out now" where it does not replace the tab preceding the comment.
 
 namespace Namespace
 {
     class Class
     {
         public void Foo()
         {
             if (bar)
             {
-                //  Layout has changed, bail out now.
+                //	Layout has changed, bail out now.
                 bar = false;
             }
         }
     }
 }
```

Debug support files:
---
[10066-UNI-1977.cs](https://gist.githubusercontent.com/mihaipopescu/daea4c3c9ce919a31d42b5234f0eee94/raw/4331fff55a2cd72538ce0624a63d0215123a9f87/10066-UNI-1977.cs)
[10066-UNI-1977.cs.log](https://gist.githubusercontent.com/mihaipopescu/daea4c3c9ce919a31d42b5234f0eee94/raw/51eee1806b55d8ed896378b9b2162054b14c57ea/10066-UNI-1977.cs.log)
[10066-UNI-1977.cs.unc](https://gist.githubusercontent.com/mihaipopescu/daea4c3c9ce919a31d42b5234f0eee94/raw/c68ba58336d3a8d83b73cea04e73631a3dbc1bce/10066-UNI-1977.cs.unc)
[Uncrustify.CSharp.cfg](https://gist.githubusercontent.com/mihaipopescu/daea4c3c9ce919a31d42b5234f0eee94/raw/1d064c1fabb76ce328dd015ed40023207de20ca1/Uncrustify.CSharp.cfg)
[UNI-1977.cs](https://gist.githubusercontent.com/mihaipopescu/daea4c3c9ce919a31d42b5234f0eee94/raw/f6fc2647195aa9feda9223a10548d258948894dc/UNI-1977.cs)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by gmaurel** [comment]
Fixed at 1eafa489cea72e7aed48d2ac20a01ee8dcf65ac2,  Jan 14 18:38:51 2018
