### ISSUE TITLE
We're not getting newlines for multiline braces that hug previous line

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1245]
`new[] {` on darkSkinColors and lightSkinColors should have brace on following line

Can easily find many examples with this rx: `new\[\][ \t]*\{\s*\n`

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10067-UNI-1978.cs" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10067-UNI-1978.cs"
index 762c205..bc7bbf0 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10067-UNI-1978.cs"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10067-UNI-1978.cs"
@@ -1,19 +1,18 @@
 // `new[] {` on colors12345636 should have brace on following line
 
 namespace Namepsace
 {
     internal static class Colors
     {
-        static Color[] colors12345636 = new[]
-        {
-            new Color(123/123f, 123/123f,   0/123f),
-            new Color(123/123f, 123/123f,   4/123f),
-            new Color(123/123f,  75/123f,  36/123f),
-            new Color(123/123f,  97/123f, 136/123f),
-            new Color(123/123f, 123/123f, 136/123f),
-            new Color( 13/123f, 123/123f, 136/123f),
-            new Color(  0/123f, 123/123f, 136/123f),
-            new Color(123/123f, 123/123f,   1/123f)
+        static Color[] colors12345636 = new[] {
+            new Color(123 / 123f, 123 / 123f,   0 / 123f),
+            new Color(123 / 123f, 123 / 123f,   4 / 123f),
+            new Color(123 / 123f,  75 / 123f,  36 / 123f),
+            new Color(123 / 123f,  97 / 123f, 136 / 123f),
+            new Color(123 / 123f, 123 / 123f, 136 / 123f),
+            new Color(13 / 123f, 123 / 123f, 136 / 123f),
+            new Color(0 / 123f, 123 / 123f, 136 / 123f),
+            new Color(123 / 123f, 123 / 123f,   1 / 123f)
         };
     }
 }
```

Debug support files:
---
[10067-UNI-1978.cs](https://gist.githubusercontent.com/mihaipopescu/8fce30e35e2f0a47f1598b7e3da0f734/raw/762c20528ffd9e5cc47efa9c4436abd4f24464e0/10067-UNI-1978.cs)
[10067-UNI-1978.cs.log](https://gist.githubusercontent.com/mihaipopescu/8fce30e35e2f0a47f1598b7e3da0f734/raw/78c204df3a0a8e2b9fd4f26653bcc1a4dd43c5a9/10067-UNI-1978.cs.log)
[10067-UNI-1978.cs.unc](https://gist.githubusercontent.com/mihaipopescu/8fce30e35e2f0a47f1598b7e3da0f734/raw/8aea0809f3b5cc8193d882183ce051afac7d477d/10067-UNI-1978.cs.unc)
[Uncrustify.CSharp.cfg](https://gist.githubusercontent.com/mihaipopescu/8fce30e35e2f0a47f1598b7e3da0f734/raw/1d064c1fabb76ce328dd015ed40023207de20ca1/Uncrustify.CSharp.cfg)
[UNI-1978.cs](https://gist.githubusercontent.com/mihaipopescu/8fce30e35e2f0a47f1598b7e3da0f734/raw/5d87696c701298eef593361bb9c25a61ef0ef9e8/UNI-1978.cs)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by guy-maurel** [comment]
#1487 is a bugfix proposal, adopted from UT

**Comment by gmaurel** [comment]
The bug is fixed.
Thanks to satish puppala
