### ISSUE TITLE
Start of column-1 literal strings forced to normal alignment (C#)

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1246]
This has to do with the @" that opens a literal string getting aligned when we don't want it to.
 (click for more details)
Test code:

    void Func()
    {
        OtherFunc(
    @"multi
    line");
    }

...becomes:

    void Func()
    {
        OtherFunc(
            @"multi
    line");
    }

(This also happens with var x = \n@"" and probably a few other scenarios.)

There's no way to keep it from indenting the first line of the string literal. We want to leave it at column 1 because it's being used for a "here doc" that doesn't want leading spaces from indentation. It's weird looking for just the first line to be indented.
This likely requires a new Uncrustify feature to support.
Workaround: start the @" on the previous line and permit the string to have an extra empty first line, like this:

    void Func()
    {
        OtherFunc(@"
    multi
    line");
    }

That might be ok for many cases, especially here-docs that are for script source.

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10074-UNI-2020.cs" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10074-UNI-2020.cs"
index 549d7ee..81ce553 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10074-UNI-2020.cs"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10074-UNI-2020.cs"
@@ -1,32 +1,32 @@
 // This has to do with the @" that opens a literal string getting aligned when we don't want it to.
 // Test code:
 
 void Func()
 {
     OtherFunc(
-@"multi
+        @"multi
 line");
 }
 
 // ...becomes:
 
 void Func()
 {
     OtherFunc(
         @"multi
 line");
 }
 
 // (This also happens with var x = \n@"" and probably a few other scenarios.)
 // There's no way to keep it from indenting the first line of the string literal. We want to leave it at column 1 because it's being used for a "here doc" that doesn't want leading spaces from indentation. It's weird looking for just the first line to be indented.
 // This likely requires a new Uncrustify feature to support.
 // Workaround: start the @" on the previous line and permit the string to have an extra empty first line, like this:
 
 void Func()
 {
     OtherFunc(@"
 multi
 line");
 }
 
 // That might be ok for many cases, especially here-docs that are for script source.
```

Debug support files:
---
[10074-UNI-2020.cs](https://gist.githubusercontent.com/mihaipopescu/849fd01dd6acee02bd43969038ff8111/raw/549d7ee235cefd26525f57c0a7c06a2410373cb2/10074-UNI-2020.cs)
[10074-UNI-2020.cs.log](https://gist.githubusercontent.com/mihaipopescu/849fd01dd6acee02bd43969038ff8111/raw/80fca4d036b1bc157876738905584eb1798853a2/10074-UNI-2020.cs.log)
[10074-UNI-2020.cs.unc](https://gist.githubusercontent.com/mihaipopescu/849fd01dd6acee02bd43969038ff8111/raw/7ed22e1a2523a7ec409caee478b2c8dc901212d1/10074-UNI-2020.cs.unc)
[Uncrustify.CSharp.cfg](https://gist.githubusercontent.com/mihaipopescu/849fd01dd6acee02bd43969038ff8111/raw/1d064c1fabb76ce328dd015ed40023207de20ca1/Uncrustify.CSharp.cfg)
[UNI-2020.cs](https://gist.githubusercontent.com/mihaipopescu/849fd01dd6acee02bd43969038ff8111/raw/549d7ee235cefd26525f57c0a7c06a2410373cb2/UNI-2020.cs)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by gmaurel** [comment]
Fixed at f6f31b2621da06a9babaa56b214f2b3ce9fda82e, Jan 14 18:26:34 2018
