### ISSUE TITLE
Non-indented two-line func+body

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1247]
Non-indented two-line func+body
Test code:

    int Func()
        { return 0; }

The contents of the method will get aligned with 'int'. Sometimes we want this, sometimes we don't.

There is no workaround; would require a new Uncrustify feature.
Re-indentation of wrapped args leaves hanging previous-line args
This:

```cs
EditorUtility.DisplayCustomMenu (position, fullFlagNames.ToArray (),
                                 // Only show selections if we are not multi-editing
                                 EditorGUI.showMixedValue ? new int[] {} : selectedFlags.ToArray (),
                                 MaskCallbackInfo.m_Instance.SetMaskValueDelegate, null);

```
becomes this:

```cs
EditorUtility.DisplayCustomMenu(position, fullFlagNames.ToArray(),
    // Only show selections if we are not multi-editing
    EditorGUI.showMixedValue ? new int[] {} : selectedFlags.ToArray(),
    MaskCallbackInfo.m_Instance.SetMaskValueDelegate, null);
```

but we'd rather have this:

```cs
EditorUtility.DisplayCustomMenu(
    position, fullFlagNames.ToArray(),
    // Only show selections if we are not multi-editing
    EditorGUI.showMixedValue ? new int[] {} : selectedFlags.ToArray(),
    MaskCallbackInfo.m_Instance.SetMaskValueDelegate, null);
```

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10075-UNI-2021.cs" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10075-UNI-2021.cs"
index 8d52189..919e17b 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10075-UNI-2021.cs"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10075-UNI-2021.cs"
@@ -1,43 +1,41 @@
 // Non-indented two-line func+body
 // Test code:
 
 int Func()
-    { return 0; }
+{ return 0; }
 
 // The contents of the method will get aligned with 'int'. Sometimes we want this, sometimes we don't.
 
 // There is no workaround; would require a new Uncrustify feature.
 // Re-indentation of wrapped args leaves hanging previous-line args
 // This:
 
 // ```cs
 
-UtilityFunctions.DisplayAwesomeness(
-    position, fullFlagNames.ToArray(),
+UtilityFunctions.DisplayAwesomeness(position, fullFlagNames.ToArray(),
     // Only show selections if we are not multi-editing
     GUI.showMixedValue ? new int[] {} : selectedFlags.ToArray(),
     Boo.m_Instance.Foo, null);
 // ```
 // becomes this:
 
 // ```cs
 
-UtilityFunctions.DisplayAwesomeness(
-    position, fullFlagNames.ToArray(),
+UtilityFunctions.DisplayAwesomeness(position, fullFlagNames.ToArray(),
     // Only show selections if we are not multi-editing
     GUI.showMixedValue ? new int[] {} : selectedFlags.ToArray(),
     Boo.m_Instance.Foo, null);
 
 // ```
 
 // but we'd rather have this:
 
 // ```cs
 
 UtilityFunctions.DisplayAwesomeness(
     position, fullFlagNames.ToArray(),
     // Only show selections if we are not multi-editing
     GUI.showMixedValue ? new int[] {} : selectedFlags.ToArray(),
     Boo.m_Instance.Foo, null);
 
 // ```
```

Debug support files:
---
[10075-UNI-2021.cs](https://gist.githubusercontent.com/mihaipopescu/f1bcf805e09eb688f415d8d060d4be8c/raw/8d52189e60621142024c30727fb5f044fab635d5/10075-UNI-2021.cs)
[10075-UNI-2021.cs.log](https://gist.githubusercontent.com/mihaipopescu/f1bcf805e09eb688f415d8d060d4be8c/raw/eceaeb4b619af00bca27ea44004139974cab7acb/10075-UNI-2021.cs.log)
[10075-UNI-2021.cs.unc](https://gist.githubusercontent.com/mihaipopescu/f1bcf805e09eb688f415d8d060d4be8c/raw/4508838d401e2c89c7ed338b02eaac81d9aae6b4/10075-UNI-2021.cs.unc)
[Uncrustify.CSharp.cfg](https://gist.githubusercontent.com/mihaipopescu/f1bcf805e09eb688f415d8d060d4be8c/raw/1d064c1fabb76ce328dd015ed40023207de20ca1/Uncrustify.CSharp.cfg)
[UNI-2021.cs](https://gist.githubusercontent.com/mihaipopescu/f1bcf805e09eb688f415d8d060d4be8c/raw/78145bbee5ef1ec4803c54842ed571642ba97be2/UNI-2021.cs)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by gmaurel** [comment]
fixed at 28daffafa7868789e13b538a2580103e40c87a07, Jan 22 15:25:39 2018
