### ISSUE TITLE
Uncrustify improvements to namespace rewriting

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1248]
Need to...

* Deal with the newline-after-opening and brace arrangement thing (eat_blanks_after_open_brace etc - see note in Uncrustify.Cpp.cfg)
* Terminate with //namespace if greater than x lines (like with #ifdef)

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10076-UNI-1343.cs" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10076-UNI-1343.cs"
index 1634963..e39007f 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10076-UNI-1343.cs"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10076-UNI-1343.cs"
@@ -1,19 +1,19 @@
 // Need to...
 
 // * Deal with the newline-after-opening and brace arrangement thing (eat_blanks_after_open_brace etc - see note in Uncrustify.Cpp.cfg)
 // * Terminate with //namespace if greater than x lines (like with #ifdef)
 
 namespace Unity
 {
     public static void foo1()
     {
     }
 
     public static void foo2()
     {
     }
 
     public static void foo3()
     {
     }
-} // namespace Unity
+}
```

Debug support files:
---
[10076-UNI-1343.cs](https://gist.githubusercontent.com/mihaipopescu/6a232a509db58aa10fba6eb32c97f5df/raw/1634963d8714a7c205e4b32b573dcbd74dd655b2/10076-UNI-1343.cs)
[10076-UNI-1343.cs.log](https://gist.githubusercontent.com/mihaipopescu/6a232a509db58aa10fba6eb32c97f5df/raw/9dd84b5b00ca7934ecff70cb94825df3ecd1a032/10076-UNI-1343.cs.log)
[10076-UNI-1343.cs.unc](https://gist.githubusercontent.com/mihaipopescu/6a232a509db58aa10fba6eb32c97f5df/raw/7cb6596b044388d2775bec69024d5a04bb1daf60/10076-UNI-1343.cs.unc)
[Uncrustify.CSharp.cfg](https://gist.githubusercontent.com/mihaipopescu/6a232a509db58aa10fba6eb32c97f5df/raw/1d064c1fabb76ce328dd015ed40023207de20ca1/Uncrustify.CSharp.cfg)
[UNI-1343.cs](https://gist.githubusercontent.com/mihaipopescu/6a232a509db58aa10fba6eb32c97f5df/raw/5af093655f92f2b63354047879c7c3613bd22f38/UNI-1343.cs)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by gmaurel** [comment]
Fixed at f6f31b2621da06a9babaa56b214f2b3ce9fda82e, Jan 14 18:26:34 2018
