### ISSUE TITLE
Uncrustify bug: should not remove space between '::' and keyword

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1249]
If setting sp_before_dc=remove, it will remove the space after 'class' in `friend class ::GameObject`, which we definitely don't want. Should limit removal to words.

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10080-UNI-10496.cpp" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10080-UNI-10496.cpp"
index 65637ef..8dc8f33 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\10080-UNI-10496.cpp"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\10080-UNI-10496.cpp"
@@ -1,11 +1,11 @@
 friend class ::GameObject;
 void GameObject::Foo();
 
 auto x = ::GlobalFunc();
 
 friend void ::testing::PrintDebugInformationForFakesInUse();
 
 template<class TransferFunction>
-void ::DateTime::Transfer(TransferFunction & transfer)
+void::DateTime::Transfer(TransferFunction & transfer)
 {
 }
```

Debug support files:
---
[10080-UNI-10496.cpp](https://gist.githubusercontent.com/mihaipopescu/a62c717da6df0b73ef6751dc67a60358/raw/65637efe47047b3c42ba6f0739b5cee45fa1a43c/10080-UNI-10496.cpp)
[10080-UNI-10496.cpp.log](https://gist.githubusercontent.com/mihaipopescu/a62c717da6df0b73ef6751dc67a60358/raw/9797f807315348426046b3c4a2080a4976ed3df3/10080-UNI-10496.cpp.log)
[10080-UNI-10496.cpp.unc](https://gist.githubusercontent.com/mihaipopescu/a62c717da6df0b73ef6751dc67a60358/raw/5af4f321f95075ed699be5745b511371f6253cac/10080-UNI-10496.cpp.unc)
[UNI-10496.cfg](https://gist.githubusercontent.com/mihaipopescu/a62c717da6df0b73ef6751dc67a60358/raw/242c2adef25d9fe03fbf5f2f0434d0197ee26bdc/UNI-10496.cfg)
[UNI-10496.cpp](https://gist.githubusercontent.com/mihaipopescu/a62c717da6df0b73ef6751dc67a60358/raw/975dc82c9f7ad5aca70a63032ac225414af2c7e1/UNI-10496.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by guy-maurel** [comment]
The bug is fixed

**Comment by satishp87** [comment]
In unity fork this issue is addressed with below PR
https://github.com/Unity-Technologies/uncrustify/pull/30
