### ISSUE TITLE
Expressions that involve nested func calls get wrapped more than they should

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1252]
```
A(B(C(
    D(a |
        b | c))));
```

Results in an indentation of "D" for each nested func.

```
A(B(C(
            D(a |
                b | c))));
```

What we want instead is what is in the original - each newline should cause a single indent, regardless of nesting.

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60003-UNI-2680.cpp" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60003-UNI-2680.cpp"
index 22353e1..90415f5 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60003-UNI-2680.cpp"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60003-UNI-2680.cpp"
@@ -1,10 +1,10 @@
 if (Application.platform == RuntimePlatform.LinuxEditor)
 {
     return new ProcessStartInfo("smthg")
-        {
-            Arguments = string.Format ("-9 --ss -S aa \"{0}\"", file),
-            WorkingDirectory = Directory.GetCurrentDirectory(),
-            UseShellExecute = false,
-            CreateNoWindow = true
-        };
+           {
+               Arguments = string.Format("-9 --ss -S aa \"{0}\"", file),
+               WorkingDirectory = Directory.GetCurrentDirectory(),
+               UseShellExecute = false,
+               CreateNoWindow = true
+           };
 }
```

Debug support files:
---
[60003-UNI-2680.cpp](https://gist.githubusercontent.com/mihaipopescu/a45967ec65a7144c9527c77584f789d0/raw/22353e1f76f5bdbac212ab2d27a156fdeb8942e5/60003-UNI-2680.cpp)
[60003-UNI-2680.cpp.log](https://gist.githubusercontent.com/mihaipopescu/a45967ec65a7144c9527c77584f789d0/raw/5b88aa11f99e2fde8add6f99fa89d43e8fb9f153/60003-UNI-2680.cpp.log)
[60003-UNI-2680.cpp.unc](https://gist.githubusercontent.com/mihaipopescu/a45967ec65a7144c9527c77584f789d0/raw/f67be62532dacbb8d1d40fbcbfadf0b4cdf28ec0/60003-UNI-2680.cpp.unc)
[Uncrustify.Cpp.cfg](https://gist.githubusercontent.com/mihaipopescu/a45967ec65a7144c9527c77584f789d0/raw/23d62d9dba5caf352fdc1793792e98eed4b81929/Uncrustify.Cpp.cfg)
[UNI-2680.cpp](https://gist.githubusercontent.com/mihaipopescu/a45967ec65a7144c9527c77584f789d0/raw/38ded76c4633130b4d6461891488bda2d9996317/UNI-2680.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by CDanU** [comment]
Min cfg
```sql
sp_func_call_paren              = remove # can be removed
indent_columns                  = 4
indent_with_tabs                = 0
```

**Comment by hschlichter** [comment]
@mihaipopescu is the indentation here actually what we want?
```
return new ProcessStartInfo("smthg")
    {
        Arguments = string.Format ("-9 --ss -S aa \"{0}\"", file),
        WorkingDirectory = Directory.GetCurrentDirectory(),
        UseShellExecute = false,
        CreateNoWindow = true
    };
```

We don't want this instead?
```
return new ProcessStartInfo("smthg")
{
    Arguments = string.Format ("-9 --ss -S aa \"{0}\"", file),
    WorkingDirectory = Directory.GetCurrentDirectory(),
    UseShellExecute = false,
    CreateNoWindow = true
};
```

**Comment by mihaipopescu** [comment]
@hschlichter Yes, you are right and I think that's already working on our side (we added new options for it) but now I see that the bug report is wrong. The description doesn't match with the input files. Let me check what happened.

**Comment by mihaipopescu** [comment]
I'll close this and create a new one.
