### ISSUE TITLE
Need ability to force newline on opening a delegate/lambda

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1253]
// Make sure browser-side code finishes executing before we kill the window
	EditorApplication.CallDelayed(() => {
		foreach (CollabToolbarWindow window in Resources.FindObjectsOfTypeAll<CollabToolbarWindow>())
			window.Close();
	}, 1f);

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60004-UNI-2684.cs" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60004-UNI-2684.cs"
index 0c91b08..11725a9 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60004-UNI-2684.cs"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60004-UNI-2684.cs"
@@ -1,4 +1,4 @@
 EditorApplication.CallDelayed(() => {
-    foreach (CollabToolbarWindow window in Resources.FindObjectsOfTypeAll<CollabToolbarWindow>())
-        window.Close();
-}, 1f);
\ No newline at end of file
+        foreach (CollabToolbarWindow window in Resources.FindObjectsOfTypeAll<CollabToolbarWindow>())
+            window.Close();
+    }, 1f);
```

Debug support files:
---
[60004-UNI-2684.cs](https://gist.githubusercontent.com/mihaipopescu/c7a22295348ef815eab42f8539e67e66/raw/0c91b081244ce5ff9c590521067b5f186dbb8b0c/60004-UNI-2684.cs)
[60004-UNI-2684.cs.log](https://gist.githubusercontent.com/mihaipopescu/c7a22295348ef815eab42f8539e67e66/raw/4a81ab636990f2db0eab38f739575a3fbc423227/60004-UNI-2684.cs.log)
[60004-UNI-2684.cs.unc](https://gist.githubusercontent.com/mihaipopescu/c7a22295348ef815eab42f8539e67e66/raw/b38448204f1443ec499c54f3f5f8897408799eea/60004-UNI-2684.cs.unc)
[Uncrustify.CSharp.cfg](https://gist.githubusercontent.com/mihaipopescu/c7a22295348ef815eab42f8539e67e66/raw/1d064c1fabb76ce328dd015ed40023207de20ca1/Uncrustify.CSharp.cfg)
[UNI-2684.cs](https://gist.githubusercontent.com/mihaipopescu/c7a22295348ef815eab42f8539e67e66/raw/0c91b081244ce5ff9c590521067b5f186dbb8b0c/UNI-2684.cs)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by gmaurel** [comment]
Fixed at 2a3650a24177e58085c0ee84527cfe19db483a09, Jan 16 16:15:24 2018
