### ISSUE TITLE
uncrustify inserts a space before 0x1000

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1256]
```
 class ClassWithCtorICall
    {
        public ClassWithCtorICall()
        {
            DoICall();
        }

        [MethodImpl((MethodImplOptions)0x1000)]
        static extern void DoICall();
    }
```

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60007-UNI-3083.cs" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60007-UNI-3083.cs"
index 969471a..90493fb 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60007-UNI-3083.cs"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60007-UNI-3083.cs"
@@ -1,11 +1,11 @@
 class ClassWithCtorICall
 {
     public ClassWithCtorICall()
     {
         DoICall();
     }
 
     //It shouldn't add an extra space before 0x1000
-    [MethodImpl((MethodImplOptions)0x1000)]
+    [MethodImpl((MethodImplOptions) 0x1000)]
     static extern void DoICall();
 }
```

Debug support files:
---
[60007-UNI-3083.cs](https://gist.githubusercontent.com/mihaipopescu/6611e3113a4c32789e1bfe3c162f15cc/raw/969471a25480b61360617ffe83478b7a93d84880/60007-UNI-3083.cs)
[60007-UNI-3083.cs.log](https://gist.githubusercontent.com/mihaipopescu/6611e3113a4c32789e1bfe3c162f15cc/raw/5eb05339eebeaf73e38c68beb07c4a5240f52ed1/60007-UNI-3083.cs.log)
[60007-UNI-3083.cs.unc](https://gist.githubusercontent.com/mihaipopescu/6611e3113a4c32789e1bfe3c162f15cc/raw/c9aafafa3d0df1ecf2f969376b4ce0c1bc958c8f/60007-UNI-3083.cs.unc)
[Uncrustify.CSharp.cfg](https://gist.githubusercontent.com/mihaipopescu/6611e3113a4c32789e1bfe3c162f15cc/raw/1d064c1fabb76ce328dd015ed40023207de20ca1/Uncrustify.CSharp.cfg)
[UNI-3083.cs](https://gist.githubusercontent.com/mihaipopescu/6611e3113a4c32789e1bfe3c162f15cc/raw/969471a25480b61360617ffe83478b7a93d84880/UNI-3083.cs)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by gmaurel** [comment]
Fixed at 9f71c400a4313e919a89a95d2df1f4172d4030e2, Jan 25 18:41:36 2018
