### ISSUE TITLE
Feature Request: Newline between @interface / @implementation and open brace

### ISSUE THREAD

**Issue by ryanmaxwell** [uncrustify/uncrustify#126]
I would like an option to control the newline between the @interface / @implementation directive and the ivars declared within the following braces. I don't believe there is one but please let me know if I'm mistaken :)

e.g Class Header:

```
@interface MyClass : NSObject {
    BOOL _myPublicBoolean;
    NSString *_myPublicName;
}
```

vs

```
@interface MyClass : NSObject 
{
    BOOL _myPublicBoolean;
    NSString *_myPublicName;
}
```

e.g. Class Extension

```
@interface MyClass () {
    NSString *_myPrivateString;
}
```

vs

```
@interface MyClass () 
{
    NSString *_myPrivateString;
}
```

e.g Class Implementation

```
@implementation MyClass {
    BOOL _myPrivateBoolean;
}
```

vs

```
@implementation MyClass 
{
    BOOL _myPrivateBoolean;
}
```

**Comment by guy-maurel** [comment]
#1712 is a proposal implemting the request.
Please test and report.
