### ISSUE TITLE
Wrong indentation of `#if` wrapped code

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1262]
```diff
 #if UNITY_EDITOR
     #include "Tools/UnityShaderCompiler/ShaderCompilerTypes.h"
-    class GraphicsSettings;
+class GraphicsSettings;
 #endif
```

```
#if UNITY_GFX_EXTERNAL_SELECT_RENDERING_API

    #if PLATFORM_ANDROID || PLATFORM_TIZEN // should it be ENABLE_EGL?
extern "C" int UnityGetSelectedGLESVersion();
    #elif UNITY_APPLE_PVR
extern "C" int UnityGetSelectedRenderingAPI();
    #endif
```

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60014-UNI-14107.cpp" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60014-UNI-14107.cpp"
index 3872d71..874168f 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60014-UNI-14107.cpp"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60014-UNI-14107.cpp"
@@ -1,14 +1,14 @@
 #if UNITY_EDITOR
      #include "Tools/UnityShaderCompiler/ShaderCompilerTypes.h"
-    class GraphicsSettings;
+class GraphicsSettings;
 #endif
 
 #if UNITY_GFX_EXTERNAL_SELECT_RENDERING_API
 
     #if PLATFORM_ANDROID || PLATFORM_TIZEN // should it be ENABLE_EGL?
-    extern "C" int UnityGetSelectedGLESVersion();
+extern "C" int UnityGetSelectedGLESVersion();
     #elif UNITY_APPLE_PVR
-    extern "C" int UnityGetSelectedRenderingAPI();
+extern "C" int UnityGetSelectedRenderingAPI();
     #endif
 
 #endif
```

Debug support files:
---
[60014-UNI-14107.cpp](https://gist.githubusercontent.com/mihaipopescu/01d2b500f7ea693d33eb36486d881319/raw/3872d71aabd683196ed7c176d620e1e7a93874d6/60014-UNI-14107.cpp)
[60014-UNI-14107.cpp.log](https://gist.githubusercontent.com/mihaipopescu/01d2b500f7ea693d33eb36486d881319/raw/275ec0c2d137cbf217b9d4317e6f81fea3c4b968/60014-UNI-14107.cpp.log)
[60014-UNI-14107.cpp.unc](https://gist.githubusercontent.com/mihaipopescu/01d2b500f7ea693d33eb36486d881319/raw/7d1317bee50f55ca205cec90923ea5bd549e432c/60014-UNI-14107.cpp.unc)
[Uncrustify.Cpp.cfg](https://gist.githubusercontent.com/mihaipopescu/01d2b500f7ea693d33eb36486d881319/raw/23d62d9dba5caf352fdc1793792e98eed4b81929/Uncrustify.Cpp.cfg)
[UNI-14107.cpp](https://gist.githubusercontent.com/mihaipopescu/01d2b500f7ea693d33eb36486d881319/raw/3872d71aabd683196ed7c176d620e1e7a93874d6/UNI-14107.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by CDanU** [comment]
Also happens with empty config, just in case keep options
```sql
indent_namespace                = true
indent_namespace_single_indent  = true
```

**Comment by mihaipopescu** [comment]
Those sound to be the correct options but we have those disabled. But yeah, if you say that they still don't fix it it's still a bug then.

**Comment by guy-maurel** [comment]
Not exactly.
As already written, the indentation with the preprocessor commands made a second administration for it, independent of the administration for the braces.
I think it is not a bug but a wish of an extension of uncrustify, we cannot implement today.
I'll change the status of the call.

**Comment by gmaurel** [comment]
Have a look to #1604
