### ISSUE TITLE
An space is introduced before a parenthesis when the parameter is a positive number  

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1265]
format bug with c#:
expected:
```
5.Clamp(2, 10).ShouldBe(5);
```
actual:
```
5.Clamp (2, 10).ShouldBe(5);
```
(space is added before paren)

note that this only happens with positive int literals. if i use a float with a decimal, or 'c' or "abc" or whatever, or even `(-5)`, it's ok.

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60019-UNI-18780.cs" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60019-UNI-18780.cs"
index 0eea713..111aab8 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60019-UNI-18780.cs"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60019-UNI-18780.cs"
@@ -1,7 +1,7 @@
 // note that this only happens with positive int literals. if i use a float with a decimal, or 'c' or "abc" or whatever, or even `(-5)`, it's ok.
-5.Clamp(2, 10).ShouldBe(5);
-5.Clamp(-5, 10).ShouldBe(5);
-5.Clamp("a", 10).ShouldBe(5);
+5.Clamp (2, 10).ShouldBe(5);
+5.Clamp (-5, 10).ShouldBe(5);
+5.Clamp ("a", 10).ShouldBe(5);
 
 "4".Clamp(2, 10).ShouldBe(5);
 (-5).Clamp(2, 10).ShouldBe(5);
```

Debug support files:
---
[60019-UNI-18780.cs](https://gist.githubusercontent.com/mihaipopescu/49962746b7855e78cdfa889fc53e3c15/raw/0eea713ed2594b35223812b1314025eb828ffa8b/60019-UNI-18780.cs)
[60019-UNI-18780.cs.log](https://gist.githubusercontent.com/mihaipopescu/49962746b7855e78cdfa889fc53e3c15/raw/4251213e343a62d4890317605f34ec3ee79624bf/60019-UNI-18780.cs.log)
[60019-UNI-18780.cs.unc](https://gist.githubusercontent.com/mihaipopescu/49962746b7855e78cdfa889fc53e3c15/raw/2bd6a0881d58fd1341fa3bcf71e88e2649b36cd8/60019-UNI-18780.cs.unc)
[Uncrustify.CSharp.cfg](https://gist.githubusercontent.com/mihaipopescu/49962746b7855e78cdfa889fc53e3c15/raw/1d064c1fabb76ce328dd015ed40023207de20ca1/Uncrustify.CSharp.cfg)
[UNI-18780.cs](https://gist.githubusercontent.com/mihaipopescu/49962746b7855e78cdfa889fc53e3c15/raw/0eea713ed2594b35223812b1314025eb828ffa8b/UNI-18780.cs)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by satishp87** [comment]
In unity fork this issue is addressed with below PR
https://github.com/Unity-Technologies/uncrustify/pull/51

**Comment by gmaurel** [comment]
Bugfix with PR #1515
