### ISSUE TITLE
Uncrustify fails formatting tuple syntax

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1266]
format bug with modern c#
expected:
```
public static (bool updated, Warnings warnings) UpdateIncludesInFile(
    string fileToUpdate, string oldIncludeFile, string newIncludeFile)
{
    // ...
}
```
actual:
```
public static (bool updated, Warnings warnings)UpdateIncludesInFile(
    string fileToUpdate, string oldIncludeFile, string newIncludeFile)
{
    // ...
}
```
uncrustify needs to learn tuple syntax

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60020-UNI-18829.cs" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60020-UNI-18829.cs"
index b3fd9ef..4bac370 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60020-UNI-18829.cs"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60020-UNI-18829.cs"
@@ -1,6 +1,6 @@
 // It shouldn't detele the space after the tuple definition
-public static (bool updated, Warnings warnings) UpdateIncludesInFile(
+public static (bool updated, Warnings warnings)UpdateIncludesInFile(
     string fileToUpdate, string oldIncludeFile, string newIncludeFile)
 {
     // ...
 }
```

Debug support files:
---
[60020-UNI-18829.cs](https://gist.githubusercontent.com/mihaipopescu/569b70bf6e704ed6acd1adf63185cbba/raw/b3fd9ef97c6717cd592fbc9fa4db7f4aaa6ac773/60020-UNI-18829.cs)
[60020-UNI-18829.cs.log](https://gist.githubusercontent.com/mihaipopescu/569b70bf6e704ed6acd1adf63185cbba/raw/4d11faae2857338788de82299f4691eef85dcdb0/60020-UNI-18829.cs.log)
[60020-UNI-18829.cs.unc](https://gist.githubusercontent.com/mihaipopescu/569b70bf6e704ed6acd1adf63185cbba/raw/109d94b8d27355e474e4db2e987b8aa90a21586c/60020-UNI-18829.cs.unc)
[Uncrustify.CSharp.cfg](https://gist.githubusercontent.com/mihaipopescu/569b70bf6e704ed6acd1adf63185cbba/raw/1d064c1fabb76ce328dd015ed40023207de20ca1/Uncrustify.CSharp.cfg)
[UNI-18829.cs](https://gist.githubusercontent.com/mihaipopescu/569b70bf6e704ed6acd1adf63185cbba/raw/b3fd9ef97c6717cd592fbc9fa4db7f4aaa6ac773/UNI-18829.cs)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by gmaurel** [comment]
Fixed at 9ad37b97b251cfa83dfe6720315c39de9899435d, Jan  2 18:30:01 2018
