### ISSUE TITLE
Space removed in `ALIGN_TYPE(16)StructName`

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1267]
Probably need a new entry in our custom rules, a new MACRO_FUNC or something.

Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60021-UNI-12046.cpp" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60021-UNI-12046.cpp"
index 5ffc0da..f0ee4df 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60021-UNI-12046.cpp"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60021-UNI-12046.cpp"
@@ -1,2 +1,2 @@
 //The space shouldn't be removed. This is a STRUCT
-struct ALIGN_TYPE(16) StructName;
+struct ALIGN_TYPE(16)StructName;
```

Debug support files:
---
[60021-UNI-12046.cpp](https://gist.githubusercontent.com/mihaipopescu/b0b78179f5a5d7aca06ce536f1d7fffc/raw/5ffc0da9cae2e2882a19e2f22e038af3f131582e/60021-UNI-12046.cpp)
[60021-UNI-12046.cpp.log](https://gist.githubusercontent.com/mihaipopescu/b0b78179f5a5d7aca06ce536f1d7fffc/raw/cce273a8107bb71395aced0c2fca4e10db2698d3/60021-UNI-12046.cpp.log)
[60021-UNI-12046.cpp.unc](https://gist.githubusercontent.com/mihaipopescu/b0b78179f5a5d7aca06ce536f1d7fffc/raw/35a7d329a1ea4dbc0c88a8ea6dd45d4ade66688f/60021-UNI-12046.cpp.unc)
[Uncrustify.Cpp.cfg](https://gist.githubusercontent.com/mihaipopescu/b0b78179f5a5d7aca06ce536f1d7fffc/raw/23d62d9dba5caf352fdc1793792e98eed4b81929/Uncrustify.Cpp.cfg)
[UNI-12046.cpp](https://gist.githubusercontent.com/mihaipopescu/b0b78179f5a5d7aca06ce536f1d7fffc/raw/9cc7b13f3d534a41b7917b06492f36f3217180b4/UNI-12046.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by guy-maurel** [comment]
#1542 is a proposal for a bugfix.
