### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by amacara1** [uncrustify/uncrustify#1279]
Application crashes when fed below C file. -p option does not create a debug file.
Version: 0.65, windows 7, 64 bit
cmd line: uncrustify.exe -p debug.txt -c c:\defaults.cfg a.c

Content of a.c:
{
#ifdef bla	
}
#endif

Complete crash info:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	uncrustify.exe
  Application Version:	0.0.0.0
  Application Timestamp:	591dbf59
  Fault Module Name:	msvcrt.dll
  Fault Module Version:	7.0.7601.17744
  Fault Module Timestamp:	4eeaf722
  Exception Code:	c0000005
  Exception Offset:	0000d193
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\windows\system32\en-US\erofflps.txt

**Comment by guy-maurel** [comment]
Remenber: uncrustify works pretty well only with compilable file.
We recommand not to use brace within preprocessor block.

**Comment by mihaipopescu** [comment]
@amacara1 Can you give a non-synthetic concrete example ? On the other hand, I think uncrustify should not crash but give an error.  Isn't this somehow related to #1228 ?

**Comment by amacara1** [comment]
Here is an example, different, though. Crash comes from 'if' in the assembly comment:
asm void foo(void){
  and.  r10, r7, r9             # Check if 
}

**Comment by amacara1** [comment]
And another crash, this one is wrong in the number of ending braces:
void foo()
{
	do
	{
		if(0)
		{            			            
			if(0) 
			{				
			}
		}
		} //this one is the culprit
	}
	while (0);
}

**Comment by amacara1** [comment]
This new one is completely funny. It reproduces only with -l C
And moving line 3 (public inheritance) over to the end of line 2 makes it work smoothly instead of crashing:

namespace testing {
class c a
    : public b {
};

namespace internal {
class c a {
};
}  // namespace internal
}  // namespace testing

**Comment by mihaipopescu** [comment]
@amacara1 Can you edit your comments adding code blocks using github-flavoured markdown syntax?

**Comment by mihaipopescu** [comment]
Can you try to give examples from compilabe code? What is `a` ? And there are no classes in C.

**Comment by gmaurel** [comment]
Is it what you are looking for?
Please test and report.
