### ISSUE TITLE
Incorrect report of "Unmatched BRACE_CLOSE"

### ISSUE THREAD

**Issue by amacara1** [uncrustify/uncrustify#1280]
Application outputs "Unmatched BRACE_CLOSE" when fed below C file. 
Version: 0.65, windows 7, 64 bit
cmd line: uncrustify.exe -p debug.txt -c c:\defaults.cfg a.c

Content of a.c:
#ifdef bla	
{
#endif
#ifdef bla	
}
#endif

**Comment by guy-maurel** [comment]
see #1279

**Comment by gmaurel** [comment]
Is it what you are looking for?
Please test and report.
