### ISSUE TITLE
Bad tokenization of function pointers from function arguments

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1285]
Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60028-UNI-21509.cpp" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60028-UNI-21509.cpp"
index c89583f..3813c39 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60028-UNI-21509.cpp"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60028-UNI-21509.cpp"
@@ -1,11 +1,15 @@
 void (*foo)(int);
 static bar(void (*foo)(int))
 {
 }
 
 bool (*comp_func)(const TypeA*const a, const TypeB& value) = NULL;
-static foo(bool (*comp_func)(const TypeA*const a, const TypeB& value) = NULL)
+static foo(bool (*comp_func)(const TypeA * const a, const TypeB&value));
+static foo(bool (*comp_func)(const TypeA * const a, const TypeB&value) = NULL)
 {
 }
 
-void qsort(void *base, size_t nmemb, size_t size, int(*compar)(const void*, const void&));
+void qsort(void *base, size_t nmemb, size_t size, int(*compar)(const TypeA* lhs, const TypeB&rhs));
+void qsort(void *base, size_t nmemb, size_t size, int(*compar)(const TypeA* lhs, const TypeB&rhs) = NULL)
+{
+}
```

Debug support files:
---
[60028-UNI-21509.cpp](https://gist.githubusercontent.com/mihaipopescu/62c214b02de026c02a8a0f0f36f3bece/raw/c89583f8d9f31d6afa7cad2153b2df79e99f936b/60028-UNI-21509.cpp)
[60028-UNI-21509.cpp.log](https://gist.githubusercontent.com/mihaipopescu/62c214b02de026c02a8a0f0f36f3bece/raw/ff64332b7134bc7ec5abadfd0a392f3a05ab0273/60028-UNI-21509.cpp.log)
[60028-UNI-21509.cpp.unc](https://gist.githubusercontent.com/mihaipopescu/62c214b02de026c02a8a0f0f36f3bece/raw/df9f74583721e624e2c537e03446d561b3754aa4/60028-UNI-21509.cpp.unc)
[Uncrustify.Cpp.cfg](https://gist.githubusercontent.com/mihaipopescu/62c214b02de026c02a8a0f0f36f3bece/raw/23d62d9dba5caf352fdc1793792e98eed4b81929/Uncrustify.Cpp.cfg)
[UNI-21509.cpp](https://gist.githubusercontent.com/mihaipopescu/62c214b02de026c02a8a0f0f36f3bece/raw/6a9f6bed5a7d3d9955d5ed954f23e3128004c56b/UNI-21509.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by gmaurel** [comment]
Fixed at 78af3bb958fe603ba778fad654af38b520079bc3, on Dec 19 16:03:19 2017
