### ISSUE TITLE
Extra space added after namespace resolution operator for return type of a friend function

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1288]
Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60031-UNI-21728.cpp" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60031-UNI-21728.cpp"
index 94444cf..1917062 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60031-UNI-21728.cpp"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60031-UNI-21728.cpp"
@@ -1 +1 @@
-friend std::ostream& operator<<(std::ostream& os, const ScriptingObjectPtr& o);
+friend std ::ostream& operator<<(std::ostream& os, const ScriptingObjectPtr& o);
```

Debug support files:
---
[60031-UNI-21728.cpp](https://gist.githubusercontent.com/mihaipopescu/4ec61f122b3144d43c68b74072a77fee/raw/94444cf913938a0ec0092c60d0340f8323310ae5/60031-UNI-21728.cpp)
[60031-UNI-21728.cpp.log](https://gist.githubusercontent.com/mihaipopescu/4ec61f122b3144d43c68b74072a77fee/raw/9783c60890ae9acf3971453dca88a387b6313bff/60031-UNI-21728.cpp.log)
[60031-UNI-21728.cpp.unc](https://gist.githubusercontent.com/mihaipopescu/4ec61f122b3144d43c68b74072a77fee/raw/a445e700a1331e99722c4a92c6de2d1e18db2525/60031-UNI-21728.cpp.unc)
[Uncrustify.Cpp.cfg](https://gist.githubusercontent.com/mihaipopescu/4ec61f122b3144d43c68b74072a77fee/raw/23d62d9dba5caf352fdc1793792e98eed4b81929/Uncrustify.Cpp.cfg)
[UNI-21728.cpp](https://gist.githubusercontent.com/mihaipopescu/4ec61f122b3144d43c68b74072a77fee/raw/94444cf913938a0ec0092c60d0340f8323310ae5/UNI-21728.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by guy-maurel** [comment]
#1456 is a bugfix proposal
Please test it and report

**Comment by gmaurel** [comment]
The bug #1288 is fixed.

**Comment by satishp87** [comment]
In unity fork this issue is addressed with below PR
https://github.com/Unity-Technologies/uncrustify/pull/30
