### ISSUE TITLE
Bad tokenization of double-pointers

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1289]
Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60032-UNI-21729.cpp" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60032-UNI-21729.cpp"
index 4266347..09d6f60 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60032-UNI-21729.cpp"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60032-UNI-21729.cpp"
@@ -1,3 +1,3 @@
-extern "C" void __declspec(dllexport) GetAccountNameAndDomain(HWND /*hwndParent*/, int string_size, TCHAR * variables, stack_t** stacktop, extra_parameters* /*extra*/)
+extern "C" void __declspec(dllexport) GetAccountNameAndDomain(HWND /*hwndParent*/, int string_size, TCHAR * variables, stack_t * *stacktop, extra_parameters* /*extra*/)
 {
 }
```

Debug support files:
---
[60032-UNI-21729.cpp](https://gist.githubusercontent.com/mihaipopescu/381b7181ee8fdf631e74bc8dc96c73d3/raw/42663477ae49626f1e17b7c2ff6fc049381ff6fb/60032-UNI-21729.cpp)
[60032-UNI-21729.cpp.log](https://gist.githubusercontent.com/mihaipopescu/381b7181ee8fdf631e74bc8dc96c73d3/raw/06dd12122c3362c89f48fd563a67f46eb50b3c88/60032-UNI-21729.cpp.log)
[60032-UNI-21729.cpp.unc](https://gist.githubusercontent.com/mihaipopescu/381b7181ee8fdf631e74bc8dc96c73d3/raw/b2b8a49a93285ef8600a21202053688e36189407/60032-UNI-21729.cpp.unc)
[Uncrustify.Cpp.cfg](https://gist.githubusercontent.com/mihaipopescu/381b7181ee8fdf631e74bc8dc96c73d3/raw/23d62d9dba5caf352fdc1793792e98eed4b81929/Uncrustify.Cpp.cfg)
[UNI-21729.cpp](https://gist.githubusercontent.com/mihaipopescu/381b7181ee8fdf631e74bc8dc96c73d3/raw/42663477ae49626f1e17b7c2ff6fc049381ff6fb/UNI-21729.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by gmaurel** [comment]
The bug #1289 is fixed
