### ISSUE TITLE
Extra space added before ellipsis on variadic templated struct

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1291]
Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60034-UNI-21731.cpp" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60034-UNI-21731.cpp"
index 227aebb..cad2d71 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60034-UNI-21731.cpp"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60034-UNI-21731.cpp"
@@ -1,4 +1,4 @@
 template<class R, typename ... FArgs>
-struct invoke_fptr<R(VKAPI_PTR*)(FArgs...)>
+struct invoke_fptr<R(VKAPI_PTR*)(FArgs ...)>
 {
 };
```

Debug support files:
---
[60034-UNI-21731.cpp](https://gist.githubusercontent.com/mihaipopescu/4d395242e8062fba6c52a789f976140e/raw/227aebb4570bac3e216d3d92e38d32c06530467c/60034-UNI-21731.cpp)
[60034-UNI-21731.cpp.log](https://gist.githubusercontent.com/mihaipopescu/4d395242e8062fba6c52a789f976140e/raw/3db7a5ecb8f9298e3fa6f5297e040294e13095d9/60034-UNI-21731.cpp.log)
[60034-UNI-21731.cpp.unc](https://gist.githubusercontent.com/mihaipopescu/4d395242e8062fba6c52a789f976140e/raw/cff59d6b32aa0b618293abccbc1ba56ce2ad9c48/60034-UNI-21731.cpp.unc)
[Uncrustify.Cpp.cfg](https://gist.githubusercontent.com/mihaipopescu/4d395242e8062fba6c52a789f976140e/raw/23d62d9dba5caf352fdc1793792e98eed4b81929/Uncrustify.Cpp.cfg)
[UNI-21731.cpp](https://gist.githubusercontent.com/mihaipopescu/4d395242e8062fba6c52a789f976140e/raw/227aebb4570bac3e216d3d92e38d32c06530467c/UNI-21731.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by guy-maurel** [comment]
Work at the current git version.

**Comment by gmaurel** [comment]
whiout the patch from KalyanaChakravarthi

**Comment by mihaipopescu** [comment]
Thanks @gmaurel. We will verify.
