### ISSUE TITLE
Investigate extra newline added between } and #endif in C#

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1292]
Expected versus output diff:
---
```diff
diff --git "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60035-UNI-11993.cs" "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60035-UNI-11993.cs"
index 7f51a16..bb4e322 100644
--- "a/C:\\work\\external\\uncrustify\\tests\\output\\staging\\60035-UNI-11993.cs"
+++ "b/C:\\work\\external\\uncrustify\\tests\\results\\staging\\60035-UNI-11993.cs"
@@ -1,11 +1,12 @@
 namespace Namespace
 {
     public class Class
     {
         #if DEBUG
         public statc foo()
         {
         }
+
         #endif
     }
 }
```

Debug support files:
---
[60035-UNI-11993.cs](https://gist.githubusercontent.com/mihaipopescu/945a73097f753f217c61c75f79945923/raw/7f51a1680731aaae90c31fb888b03e9eb3dd1c41/60035-UNI-11993.cs)
[60035-UNI-11993.cs.log](https://gist.githubusercontent.com/mihaipopescu/945a73097f753f217c61c75f79945923/raw/ccdbf5e3d7756a2aeb6b8041176b6ea81c9e907a/60035-UNI-11993.cs.log)
[60035-UNI-11993.cs.unc](https://gist.githubusercontent.com/mihaipopescu/945a73097f753f217c61c75f79945923/raw/630cdf168ebf774b94095fcec3a67e69e83abec6/60035-UNI-11993.cs.unc)
[Uncrustify.CSharp.cfg](https://gist.githubusercontent.com/mihaipopescu/945a73097f753f217c61c75f79945923/raw/1d064c1fabb76ce328dd015ed40023207de20ca1/Uncrustify.CSharp.cfg)
[UNI-11993.cs](https://gist.githubusercontent.com/mihaipopescu/945a73097f753f217c61c75f79945923/raw/7f51a1680731aaae90c31fb888b03e9eb3dd1c41/UNI-11993.cs)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by gmaurel** [comment]
Fixed at 1dfde8dfdec2341afd6c9524633e2968319dbb9c, on Feb 13 18:13:22 2018
