### ISSUE TITLE
Option to avoid extra indentation of C++ lambda body

### ISSUE THREAD

**Issue by ArseniyShestakov** [uncrustify/uncrustify#1296]
I working on formatting of relatively large C++ project and while it's was easy to get formatting we need for list initializers that also contain assignments I can't achieve the same for lambda expressions.

Full test file: [lambda.cpp](https://gist.github.com/ArseniyShestakov/bd5e1822bd028e77cc8a75c0aefaa49a)
Debug information: [debug.txt](https://github.com/uncrustify/uncrustify/files/1163846/debug.txt)

Current output:
```
	auto lambda2 = [&]()
		{
			code();
		};
```
Output that we need to have:
```
	auto lambda2 = [&]()
	{
		code();
	};
```
Lambda expressions without assignment, inlined inside if-else conditions or function calls don't get extra indent and this is exactly what we need. I suppose this is feature request and I could try to implement it myself, but I'll really appreciate some advice if there some option I missed.

PS: Full config file with all options is available [here](https://github.com/vcmi/vcmi-uncrustify/blob/329d6420bb891ef540a3bee57665f36ece25e52f/uncrustify.cfg) and all our codebase changes [are here](https://github.com/vcmi/vcmi/pull/347).

UPD1: Uploaded correct debug file from Uncrustify master build.

**Comment by mihaipopescu** [comment]
There are several issues related to double indentation in C# but as always it's better to have various cases. Thanks for reporting.

**Comment by ArseniyShestakov** [comment]
@mihaipopescu could you please point me to one? I probably used search wrong because didn't think about that as "double indentation" and I know little to nothing about C#.

Also there were certainly some changes in uncrustify after 0.65 and latest master with some options enabled make it add indent even to some of inline lambdas inside function calls. So I didn't expect it's not indented at all.

**Comment by mihaipopescu** [comment]
I've double checked through the 60+ issues I've created and we have a lot of "extra" and "double" indentation issues but nothing similar with this one.

So you're saying that it's not happening in released 0.65 but happening on master ?

**Comment by ArseniyShestakov** [comment]
@mihaipopescu I only talked about difference for inline lambdas. E.g on 0.65 this remained untouched:
```
obj->callback([]()
{
    return true;
});
```
On newer version it's could go like that:
```
obj->callback([]()
    {
        return true;
    });
```

Also this isn't "extra" or  "double" indentation issue. I suppose current uncrustify behavior is totally intended, but our project code style require no indention at all for lambda body so we need some option for that.

**Comment by mihaipopescu** [comment]
Oh ok. You have `tab_size=8` but visually I thought it's double as I'm used to 4 spaces. Ok, this is a new issue and a new regression from what you are saying.

**Comment by guy-maurel** [comment]
Please use the option:
  `indent_with_tabs = 0`
to get rid of TABs.
The second part https://github.com/uncrustify/uncrustify/issues/1296#issuecomment-319919832 remained untouched.

**Comment by bartholomule** [comment]
I am also seeing this with the latest build of 0.66 from github.
This is even with trying to explicitly set indent_cpp_lambda_body = false

Input sample:
```
int main()
{
    const auto f = [](int i, int j) -> int
    {
        return i + j;
    }; // This whole block is indented one too far
}
```

Output sample:
```
int main()
{
    const auto f = [](int i, int j) -> int
        {
            return i + j;
        }; // This whole block is indented one too far
}
```

Full test file, log, and config attached.

[uncrustify_test3.cfg.txt](https://github.com/uncrustify/uncrustify/files/1553578/uncrustify_test3.cfg.txt)
[uncrustify_test3.cpp.txt](https://github.com/uncrustify/uncrustify/files/1553579/uncrustify_test3.cpp.txt)
[uncrustify_test3.log](https://github.com/uncrustify/uncrustify/files/1553580/uncrustify_test3.log)

**Comment by guy-maurel** [comment]
We need a new option on the assignment to suppress the indentation.

**Comment by guy-maurel** [comment]
Must be tested

**Comment by guy-maurel** [comment]
@aneesh1127 : no. The user has a cpp source.

**Comment by gmaurel** [comment]
Thanks

**Comment by ArseniyShestakov** [comment]
This one fixed for sure. Thanks!

**Comment by Art-Stea1th** [comment]
Hello. Please tell me what I'm doing wrong.
I cloned the last actual state of the 'master' branch, build the 'uncrustify' and I still have this issue.

[config](https://github.com/uncrustify/uncrustify/files/1875097/test.cfg.txt):
```
indent_with_tabs = 0
output_tab_size = 4
indent_continue = output_tab_size # if 0 incorrect
indent_columns = output_tab_size
indent_cpp_lambda_body = false
nl_cpp_ldef_brace=force
```

[input](https://github.com/uncrustify/uncrustify/files/1875099/input.cpp.txt):
```
int main()
{
    const auto f = [](int i, int j) -> int { return i + j; };
}
```
[expected](https://github.com/uncrustify/uncrustify/files/1875100/expected.cpp.txt):
```
int main()
{
    const auto f = [](int i, int j) -> int
    {
        return i + j;
    };
}
```
[actual](https://github.com/uncrustify/uncrustify/files/1875101/actual.cpp.txt):
```
int main()
{
    const auto f = [](int i, int j) -> int
        {
            return i + j;
        };
}
```
thank you in advance for your response
Regards

**Comment by Art-Stea1th** [comment]
@ArseniyShestakov 
Thank you for reply. It's works perfectly!
