### ISSUE TITLE
Option to indent multi-line if-else conditions instead of aligning

### ISSUE THREAD

**Issue by ArseniyShestakov** [uncrustify/uncrustify#1297]
Our project need option somewhat similar to ```indent_var_def_cont = true```, but for multi-line if-else conditions. Problem that currently even with ```indent_with_tabs = 2``` new lines within if-else parentheses always aligned with 3 spaces.

Debug file: [debug-if-else-condition.txt](https://github.com/uncrustify/uncrustify/files/1163823/debug-if-else-condition.txt)
Output that we need to have (same as unformatted source):
```
if (pinfo  //player exists
	&& (ev.players & 1<<player.getNum()) //event is enabled to this player
	&& ((ev.computerAffected && !pinfo->human)
		|| (ev.humanAffected && pinfo->human)))
{
	return;
}
```
Current output:
```
if(pinfo //player exists
   && (ev.players & 1 << player.getNum())    //event is enabled to this player
   && ((ev.computerAffected && !pinfo->human)
       || (ev.humanAffected && pinfo->human)))
{
	return;
}
```
Or at least even keep all conditions on same line:
```
if (pinfo  //player exists
	&& (ev.players & 1<<player.getNum()) //event is enabled to this player
	&& ((ev.computerAffected && !pinfo->human)
	|| (ev.humanAffected && pinfo->human)))
{
	return;
}
```
Alternatively It's could be good to just make Uncrustify not replace our tabs with spaces. I probably tried all possible options to avoid any aligning with spaces at all with no change.

**Comment by ArseniyShestakov** [comment]
Yeah I suppose this is similar or duplicate of #1071.

**Comment by guy-maurel** [comment]
Your whish is not what we are following.
The && indentation is aligned after the column of `pinfo`, these have the same if-condition-level.
The ||  indentation is aligned after the column of `(`, these have the same if-condition-level.
