### ISSUE TITLE
Indent access specifier within nested classes

### ISSUE THREAD

**Issue by dianarg** [uncrustify/uncrustify#1298]
I think this is more of a feature request than a bug. I want the access specifiers of nested (inner) classes to be indented relative to the class. This might be related to #691. I would be happy to try to work on a fix if it makes sense.

Ran with 'uncrustify -c indent_nested_class.cfg -f nested_class.cpp -p nested_class_parse.txt':

Input (nested_class.cpp):
```
class Outer {
    int w;
public:
    int x;
private:
    int y;
protected:
    int z;
    class Inner {
        int w;
private:
        int x;
public:
        int y;
protected:
        int z;
    };
};
```

Output: 
```
class Outer {
    int w;
  public:
    int x;
  private:
    int y;
  protected:
    int z;
    class Inner {
        int w;
  private:
        int x;
  public:
        int y;
  protected:
        int z;
    };
};
```
Desired output:
```
class Outer {
    int w;
  public:
    int x;
  private:
    int y;
  protected:
    int z;
    class Inner {
        int w;
      private:
        int x;
      public:
        int y;
      protected:
        int z;
    };
};
```

[nested_class_parse.txt](https://gist.github.com/dianarg/f6231ea58c585af03f26b3bf1036ad6b.js)

**Comment by romanso** [comment]
the following indent_nested_class.cfg does exactly what you want:
```
indent_columns = 4
indent_class = true
indent_access_spec = -2
```

**Comment by guy-maurel** [comment]
Thanks to @romanso

**Comment by gmaurel** [comment]
Thanks

**Comment by dianarg** [comment]
Thanks @romanso, this works for me.
