### ISSUE TITLE
bad code (won't compile) and incorrect indentation with mod_full_brace_*

### ISSUE THREAD

**Issue by clach04** [uncrustify/uncrustify#1302]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 

This file:

    void bad_braces(int x)
    {
    #ifdef MACRO_1
        if (x == 1)
    #else
    #ifdef MACRO_2
        if (x == 2) // yes this is dumb, its the smallest test case I could find to trigger this
    #endif  // MACRO_2
    #endif  // MACRO_1
    #if defined (MACRO_1) || defined(MACRO_2)
        {
            ;
        }
    #endif  /* macro 1 and 2 */

        if (x == 99)
        {
            ;
        }

    }

when used with the attached mini config file (not sure yet which option causes this) generates:

    void bad_braces(int x)
    {
    #ifdef MACRO_1
        if (x == 1)
    #else
    #ifdef MACRO_2
        if (x == 2) // yes this is dumb, its the smallest test case I could find to trigger this
    #endif  // MACRO_2
    #endif  // MACRO_1
    #if defined (MACRO_1) || defined(MACRO_2)
        {
            ;
        }
    #endif /* macro 1 and 2 */ {

            if (x == 99)
            {
                ;
            }
        }

    }

NOTE open paren on `#endif` line and (mismatched) close paren before end of function body. Also indentation of last if is incorrect.

Config file:

    # Add or remove braces on single-line 'do' statement
    mod_full_brace_do             = add   # ignore/add/remove/force

    # Add or remove braces on single-line 'for' statement
    mod_full_brace_for            = add   # ignore/add/remove/force

    # Add or remove braces on single-line function defintions. (Pawn)
    mod_full_brace_function       = add   # ignore/add/remove/force

    # Add or remove braces on single-line 'if' statement
    mod_full_brace_if             = add   # ignore/add/remove/force

    # Don't remove braces around statements that span N newlines
    mod_full_brace_nl             = 0        # number

    # Add or remove braces on single-line 'while' statement
    mod_full_brace_while          = add   # ignore/add/remove/force

[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 

Uncrustify-0.65
win32 binary from sf.net

[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by clach04** [comment]
Attached

[bug_config.cfg.txt](https://github.com/uncrustify/uncrustify/files/1181221/bug_config.cfg.txt)
[bad_braces.c.txt](https://github.com/uncrustify/uncrustify/files/1181222/bad_braces.c.txt)

They need to be renamed, remove `.txt` (github rejects otherwise)

**Comment by clach04** [comment]
There is a workaround, modify the code slightly by moving ifdefs (its easy to argue the test case code is hard to read and should be refactored 😉 ):

    void bad_braces(int x)
    {
    #if defined (MACRO_1) || defined(MACRO_2)
    #ifdef MACRO_1
        if (x == 1)
    #else
    #ifdef MACRO_2
        if (x == 2) // yes this is dumb, its the smallest test case I could find to trigger this
    #endif  // MACRO_2
    #endif  // MACRO_1
        {
            ;
        }
    #endif  /* macro 1 and 2 */


        if (x == 99)
        {
            ;
        }

    }

The #defined check is moved up higher.

**Comment by gmaurel** [comment]
uncrustify cannot deal correctly with brace in a pp block.
You should modify your code to prevent this.

**Comment by clach04** [comment]
@gmaurel  can you clarify the comment about "pp block"? I'm not sure what pp is in this context. I'm trying to workout a technique to identify brace in a pp blocks.

**Comment by guy-maurel** [comment]
Well. With "pp" I mean "pre processor"
Let say:
```
#ifdef a
... block TRUE
#else 
... block FALSE
#endif 
```
If one wants uncrustify should evaluate A (very difficult because there might be many other included files to read and evaluate), the next question is:
**which block** TRUE or FALSE should be "uncrustifyed"?
The answer cannot be useful for everybody.
I prefer that all blocks should be procceded, without taking care of the evaluation of A.
