### ISSUE TITLE
segfault with newline as first character of C++ source file

### ISSUE THREAD

**Issue by brianw1** [uncrustify/uncrustify#1303]
Having a newline '\n' as the first character in a C++ source file triggers a segfault.

Using version 0.64
[uncrustify.cfg](https://github.com/uncrustify/uncrustify/files/1195085/uncrustify.cfg.txt)

Triggers a segfault
```c++
<empty line>
bool spin() {
}
```
Works
```c++
bool spin() {
}
```

**Comment by mihaipopescu** [comment]
@brianw1 thanks for report. This is quite bad. Could you also narrow down which option is responsible for this ?

**Comment by brianw1** [comment]
This is the offending config option:
```
nl_comment_func_def=1
```

**Comment by guy-maurel** [comment]
I cannot reproduce with 0.65.
Could you test again and report?

**Comment by brianw1** [comment]
Yes, I can confirm the bug is not present in 0.65, thanks.

**Comment by gmaurel** [comment]
Fine
