### ISSUE TITLE
Something like align_var_def_span for function prototypes?

### ISSUE THREAD

**Issue by brian-armstrong** [uncrustify/uncrustify#1306]
Hi,

Is there an option like `align_var_def_span` that works on multiline function signatures?

If I have
```
int foo(int x,
        unsigned int y);
```

I want
```
int foo(int          x,
        unsigned int y)
```

**Comment by brian-armstrong** [comment]
Ah, on closer inspection, it seems my case is actually more complicated. I believe uncrustify does this, but it is getting confused by a macro that's present.

The actual signature that sees issue then is
```FOO() FOO(_bar)(int     x,
                           unsigned int y)
```

**Comment by guy-maurel** [comment]
Use the option `align_func_params = true`, which does the work for a function prototype.
Uncrustify doesn't interpret macros.

**Comment by gmaurel** [comment]
Is it what you are looking for?
Please test and report.
