### ISSUE TITLE
remove sp_after_dc not working in some cases

### ISSUE THREAD

**Issue by iuyte** [uncrustify/uncrustify#1310]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

[debug.txt](https://gist.github.com/iuyte/d8dd108579632acc176c8c984a766087)
`uncrustify -v`: Uncrustify-0.65-128-9220abb

The option in my config, `sp_after_dc` is set to `remove`. In some cases, it fails to do so.
Actual behavior:
```Cpp
#include "../include/main.h"

namespace sensors {
  Quad::Quad(unsigned char port1, unsigned char port2, bool inverted)
    : inverted(inverted) {
    ports[0] = port1;
    ports[1] = port2;
    zero     = 0;
    request  = 0;
  }

  void Quad:: init(void) {
    enc = encoderInit(Quad::ports[0], Quad::ports[1], Quad::inverted);
  } // Quad::init
}
```
Expected behavior:
```Cpp
#include "../include/main.h"

namespace sensors {
  Quad::Quad(unsigned char port1, unsigned char port2, bool inverted)
    : inverted(inverted) {
    ports[0] = port1;
    ports[1] = port2;
    zero     = 0;
    request  = 0;
  }

  void Quad::init(void) {
    enc = encoderInit(Quad::ports[0], Quad::ports[1], Quad::inverted);
  } // Quad::init
}
```

**Comment by guy-maurel** [comment]
You are using the option `align_mix_var_proto = true`
which uses a gap of 1.
Do you need it?

**Comment by iuyte** [comment]
I do not, and removing that line fixed the problem. I had not noticed that setting. Thanks a billion!
