### ISSUE TITLE
wrong indentation with default settings in some enum (C code)

### ISSUE THREAD

**Issue by pksadiq** [uncrustify/uncrustify#1315]
Source (C Program, say, write in file.c):
```
typedef enum
{
  A = 0,
  B = 1 << 0,
  C = 1 << 1
};
```

indenting the file with uncrustify with default settings (eg, with an empty cfg file), results in the following indentation:

```
typedef enum
{
        A = 0,
        B = 1 << 0,
                C = 1 << 1
};
```

This was tested using uncrustify from current git master.

Thanks

**Comment by guy-maurel** [comment]
The problem is that the `<<` is interpreted as `CT_ARITH`.
We have to found some more deinitions for it.
Please test if you could use the option:
`align_left_shift = false`
and report.

**Comment by guy-maurel** [comment]
Thank for the message.
Please test and report.

**Comment by pksadiq** [comment]
Sorry for the delay. The applied patch seems to fix the issue. I have only tested with the above test cause though. Hopefully this can be closed.

Thanks
