### ISSUE TITLE
Weird indentation with multiline c++11 using type alias

### ISSUE THREAD

**Issue by u3shit** [uncrustify/uncrustify#1318]
I don't know why, but uncrustify adds at least an extra indentation level when an using statement is broken into two lines. With `indent_align_assign = true`, it's even worse (even though is shouldn't matter in this case since `=` is followed by a newline. Setting `indent_continue = 1` or to -2 fixes the using directive, but breaks the variable definition below.

Input:
```c++
using Foo =
  int;
Foo Bar =
  3;
```

Expected output: unchanged
Actual output:
```c++
using Foo =
    int;
Foo Bar =
  3;
```
Debug file: [debug.txt](https://github.com/uncrustify/uncrustify/files/1233100/debug.txt)

Tried with 0.64 (from Gentoo package) and from git master (0.65-141-353ffe33), both produced the same results.

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by u3shit** [comment]
It looks like it indents twice, once for `using` and once for the assignment. Removing the `pc->type == CT_USING` check from [indent.cpp line 1896](https://github.com/uncrustify/uncrustify/blob/353ffe33b3eb4b595174558ea8f4ed5d53cc50d2/src/indent.cpp#L1896) fixes this problem (but probably causes others).

**Comment by guy-maurel** [comment]
It is not a bug.
Please use the option
`indent_using_block = false`
to get what you wish.

**Comment by KVic** [comment]
> Please use the option
> `indent_using_block = false`

Is this option affect C++ `using`? In C++ `using` `pc->type' is 'CT_USING` but not `CT_USING_STMT`, which is affected by `indent_using_block` ([brace_cleanup.cpp line 847](https://github.com/uncrustify/uncrustify/blob/9ced1ed62a82479c43b9d2af4a6d876eac57166a/src/brace_cleanup.cpp#L847)).

**Comment by gmaurel** [comment]
The bug is fixed
