### ISSUE TITLE
Problem with C comments in uncrustify

### ISSUE THREAD

**Issue by victor-accarini** [uncrustify/uncrustify#1320]
I have a multi-line C comment that should be splitted, and I have set a space before and after the comment star '*', but to get the correct behavior I have to uncrustify the file two times.

Input File:
```
/** Doxygen comment that has more characters in one single line than it should, how uncrustify will handle it?
 *
 * Another doxygen comment line that has more characters in one single line than it should.
 * Just a comment
 */
```

Output File:
```
/** Doxygen comment that has more characters in one single line than it should,
 * how uncrustify will handle it?
 *
 * Another doxygen comment line that has more characters in one single line than
 *it should. <-- If I pass the second time I get --> ' * it should'
 * Just a comment
 */
```

[Debug File](https://pastebin.com/PfjGzJQr)

Is this the expected behavior?

Thanks

**Comment by guy-maurel** [comment]
Yes. In your case uncrustify needs two runs to do the works.
This is because there is no loop for this case.
Let run a third run, you could see the input is no more changed.

**Comment by gmaurel** [comment]
Is it what you are looking for?
Please test and report.
