### ISSUE TITLE
c++11 noexcept specifier not handled

### ISSUE THREAD

**Issue by u3shit** [uncrustify/uncrustify#1321]
Input:
```cpp
#include <utility>

template <typename Fun, typename ... Args>
inline decltype(auto) Invoke(Fun&& f, Args&&... args)
  noexcept(noexcept(std::forward<Fun>(f)(std::forward<Args>(args) ...)))
{ return std::forward<Fun>(f)(std::forward<Args>(args) ...); }
```

Generated result:
```cpp
#include <utility>

template <typename Fun, typename ... Args>
inline decltype(auto)Invoke(Fun&& f, Args&&... args)
noexcept(noexcept(std::forward<Fun>(f)(std::forward<Args>(args) ...)))
{
  return std::forward<Fun>(f)(std::forward<Args>(args) ...);
}
```

[Debug file](https://github.com/uncrustify/uncrustify/files/1234977/debug.txt)

As far as I can tell from the debug file, it parses the noexcept specifier as FUNC_CALL, and thus it won't count the next opening brace as function definition brace, so it will break the one liner, even though I have `nl_func_leave_one_liners = true` in the config. If I remove the noexcept line (or replace it with something that uncrustify understands, like the deprecated `throw()`), it will keep the function body single line.

Also note that it removed the space after `decltype(auto)`, even though I didn't enable any space removal that should warrant this.

Tested using Uncrustify-0.65-141-353ffe33.

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
#1363 is a bugfix proposal
Olease test and report.

**Comment by guy-maurel** [comment]
The bugfix is merged.
Please test it.
