### ISSUE TITLE
space before pointer star (Objective-C)

### ISSUE THREAD

**Issue by dave256** [uncrustify/uncrustify#133]
There doesn't seem to be a way to make certain the space before the \* in:
- (NSString *)f;

is removed without also removing the space before the \* in:

for (NSString *s in items) {
}

Or am I missing something? Thanks.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

with:
```
sp_before_unnamed_ptr_star=remove
sp_before_ptr_star=force
```

**Comment by gmaurel** [comment]
Fixed
