### ISSUE TITLE
"Unmatched BRACE_OPEN" emitted for start of namespace scope

### ISSUE THREAD

**Issue by johnmcfarlane** [uncrustify/uncrustify#1330]
I'm working on a project which generates config files from source code.  It's called [unformat](https://github.com/johnmcfarlane/unformat).  It currently supports *clang-format* and I'm adding *uncrustify* support.  However, uncrustify emits errors and/or crashes under certain conditions.  Here is one such example.

* Description: error message emitted for valid C++14 code on `namespace Foo {` line.
* [debug.txt](https://gist.githubusercontent.com/johnmcfarlane/a399d068b7940d4c18d5fb21a0235cfe/raw/285db2056f438c95b1e18a63bfcc6eb026800ce2/debug.txt)  
* [source file](https://github.com/johnmcfarlane/cnl/blob/c87a9a6154772cc6c326a1f7c03bc1842a472e12/include/cnl/num_traits.h)  
* Command line: `uncrustify -c .uncrustify --assume /home/john/cnl/include/cnl/num_traits.h`
* Error message:
  ```
  Parsing: 16333 bytes (16333 chars) from stdin as language CPP
  stdin:19 Unmatched BRACE_OPEN
  ```

* Versions: 
  * `uncrustify 0.64` (The Debian Stretch repo version installed with `apt install uncrustify`
  * `Uncrustify-0.65-153-37c30cf5` (Built with GCC 7.1)

* Notes:
  * With default configuration, the error is not present
  * When I comment out the `namespace foo {` and matching `}` lines, the error goes away.

My project is little short of an uncrustify fuzzer and I'd be happy to provide you with a build that uncovers multiple issues if you're interested.  In the mean time, thanks and keep up the good work!

**Comment by CDanU** [comment]
That seems to be a bug caused by the
```sql
# Try to limit code width to N number of columns
code_width                      = 4        # unsigned number
```
option in your config.

**Comment by guy-maurel** [comment]
Use the default value `code_width = 0` or don't use the option at all.
The project is very interesting for me. Let us know about the results.
Thanks.

**Comment by mihaipopescu** [comment]
Yes, very interesting project. It'll probably be a very good fuzz test as uncrustify has almost 600 options which can take multiple values. If you find any other issue please report them all.

**Comment by mihaipopescu** [comment]
@johnmcfarlane What is the status for adding uncrustify support?

Does the issue still reproduces with the latest master?

**Comment by johnmcfarlane** [comment]
Sorry for delay. Still in a branch, I'm afraid. I cannot say when I'll get back to working on it due to other commitments.
