### ISSUE TITLE
3 autotests failed on mips64el

### ISSUE THREAD

**Issue by gerasiov** [uncrustify/uncrustify#1336]
I sent version based on 3503c92607ca5dbd83e02450f6755d0dfc16541f to Debian archive and it failed on only one arch: mips64el.
When building Debian package, 3 autotests fail:

> The following tests FAILED:
>	 51 - c_00007 (Failed)
>	 52 - c_00008 (Failed)
>	 53 - c_00009 (Failed)
>Errors while running CTest

When I enter this host I found, that when I compile uncrustify with default option (build type Debug) everything is ok, but debian toolchain uses some other flags and this version does not pass autotests:

```
$ ../obj-mips64el-linux-gnuabi64/uncrustify -p debug.txt -l C -c config/cpp_to_c-1.cfg -f input/c/comment-convert.c -o results/c/00007-comment-convert.c
Parsing: input/c/comment-convert.c as language C

$ diff output/c/00007-comment-convert.c results/c/00007-comment-convert.c
9c9
<     /* Comment with embedded / * C comment * / */
---
>     /* Comment with embedded  / * C comment  * / */
14c14
<     /* Multi-line comment with embedded / * C comment * / and junk */
---
>     /* Multi-line comment with embedded  / * C comment  * / and junk */
[1]    1148 exit 1     diff output/c/00007-comment-convert.c results/c/00007-comment-convert.c
```

Again: if I run uncrustify compiled with default options every test passes ok.
Default options:
>/usr/bin/c++  -DDEBUG -I/home/gq/uncrustify/build   -Wall -Wextra -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align   -std=gnu++0x

Debian ones:
>/usr/bin/c++   -I/home/gq/uncrustify/obj-mips64el-linux-gnuabi64  -g -O2 -fdebug-prefix-map=/home/gq/uncrustify=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align   -std=gnu++0x 

debug.txt does not differ in both cases.

I need an advice, how to debug this behavior. Where is the code generating this lines (comments)? Any clues what I should look at?

**Comment by mihaipopescu** [comment]
It could be tricky... I would deactivate optimizations and test the debug build again.

**Comment by gerasiov** [comment]
Debug version works OK.

I think the problem is somewhere in aligning or packing in structs and not very accurate casts. There are (at least was until last fixes) some in the code which fires on exotic architectures.

Could you please point the way uncrustify handle comments? Do not want to dig from the beginning =)

**Comment by gerasiov** [comment]
On current master only mips64el fails: https://buildd.debian.org/status/package.php?p=uncrustify

**Comment by gerasiov** [comment]
valgrind does not show problems too =(

**Comment by mihaipopescu** [comment]
So you only get the issue on Release build ? It's going to be hard to pin down. You can try to bisect.

You can also use the old test runner `tests/un_tests.py` and send the `-g` option which will turn on more logging but I'm afraid on debug there won't be a lot more..

**Comment by CDanU** [comment]
It seems that some of the additional build flags add runtime safety checks. You could try to add the `-V` flag to `ctest` to see if some errors are thrown. I think that those are not printed without the flag.

**Comment by gerasiov** [comment]
> So you only get the issue on Release build ? It's going to be hard to pin down.

Yes, release with some hardening options. I'm not sure it's reasonable to find out which flag triggers errors. I'd better instrument code with some debug output and compare builds to find out where the error come from.

>It seems that some of the additional build flags add runtime safety checks. You could try to add the -V flag to ctest to see if some errors are thrown. I think that those are not printed without the flag.

Nope, I found the exact tests, run them by hand. There are no errors from uncrustify itself, only files which differ.

**Comment by guy-maurel** [comment]
save the two build uncrustify under different names, let say U1 and U2, then run
```
U1 ... -L A  2>A1.txt
U2 ... -L A  2>A2.txt
```
and compare the A*.txt files. I get pretty informations with the command:
`meld A1.txt A2.txt`

**Comment by gerasiov** [comment]
Damn it!
Looks like this is compiler bug =(

Had to add some debug output, because optimized code is not very friendly in debugger:

Without optimization:
add_comment_text(" Multi-line comment with embedded /* C comment */ and junk")
line:973 esc_close=1 was_star=0 was_slash=0 text[idx]=  in_word=0 unc_isspace=8192
line:988 add_char(" ")
line:973 esc_close=1 was_star=0 was_slash=0 text[idx]=M in_word=0 unc_isspace=0
line:988 add_char("M")
line:973 esc_close=1 was_star=0 was_slash=0 text[idx]=u in_word=1 unc_isspace=0
line:988 add_char("u")


With optimization:
add_comment_text(" Multi-line comment with embedded /* C comment */ and junk")
line:973 esc_close=1 was_star=0 was_slash=0 text[idx]=  in_word=0 unc_isspace=8192
line:988 add_char(" ")
line:973 esc_close=1 was_star=**730144440320** was_slash=0 text[idx]=M in_word=0 unc_isspace=0
line:988 add_char("M")
line:973 esc_close=1 was_star=**730144440320** was_slash=0 text[idx]=u in_word=1 unc_isspace=0
line:988 add_char5("u")

But was_star is modified with
`was_star  = (text[idx] == '*');`

When I add a little bit more debug output, was_slash starts to corrupt.
Now I think this is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=871514
