### ISSUE TITLE
Unmatched open brace in an ifdef is breaking `mod_paren_on_return=remove` to break the code

### ISSUE THREAD

**Issue by Rassi** [uncrustify/uncrustify#1337]
```cpp
static type foo(const type &x)
{
#if defined(__FOO__)
	return type(1);
#elif defined(__BAR__)
	return type((2);
#else
	return (x < 0) - (x > 0);
#endif
}
```

but we get the parenthesis badly removed resulting in uncompilable code.
```diff
-       return (x < 0) - (x > 0);
+       return x < 0) - (x > 0;
```

We expect to get an error like this:
```
parse_cleanup(435): input/staging/UNI-99999.cpp:53 Error: Unexpected '}' for 'PAREN_OPEN', which was on line 49
input/staging/UNI-99999.cpp:47 Unmatched BRACE_OPEN
input/staging/UNI-99999.cpp:49 Unmatched RETURN
input/staging/UNI-99999.cpp:49 Unmatched FPAREN_OPEN
input/staging/UNI-99999.cpp:47 Unmatched BRACE_OPEN
input/staging/UNI-99999.cpp:49 Unmatched RETURN
input/staging/UNI-99999.cpp:49 Unmatched FPAREN_OPEN
```

Expected versus output diff:
---
```diff
diff --git "a/C:\\dev\\uncrustify\\tests\\output\\staging\\60037-UNI-24755.cpp" "b/C:\\dev\\uncrustify\\tests\\results\\staging\\60037-UNI-24755.cpp"
index 1ee124d..c337969 100644
--- "a/C:\\dev\\uncrustify\\tests\\output\\staging\\60037-UNI-24755.cpp"
+++ "b/C:\\dev\\uncrustify\\tests\\results\\staging\\60037-UNI-24755.cpp"
@@ -1,10 +1,10 @@
 static type foo(const type &x)
 {
 #if defined(__FOO__)
 	return type(1);
 #elif defined(__BAR__)
 	return type((2);
 #else
-	return (x < 0) - (x > 0);
+	return x < 0) - (x > 0;
 #endif
 }
```

Debug support files:
---
[60037-UNI-24755.cpp](https://gist.githubusercontent.com/Rassi/788d0f7d01b19bc6b19a6596e8b78f21/raw/1ee124d260698a5c999637771065f72b78b0ed90/60037-UNI-24755.cpp)
[60037-UNI-24755.cpp.log](https://gist.githubusercontent.com/Rassi/788d0f7d01b19bc6b19a6596e8b78f21/raw/089065913a5cd7dd38ae4a9dcecd4098f6152129/60037-UNI-24755.cpp.log)
[60037-UNI-24755.cpp.unc](https://gist.githubusercontent.com/Rassi/788d0f7d01b19bc6b19a6596e8b78f21/raw/dc1d1b62d73bd91889a67f51004cb616340ca27f/60037-UNI-24755.cpp.unc)
[UNI-24755.cfg](https://gist.githubusercontent.com/Rassi/788d0f7d01b19bc6b19a6596e8b78f21/raw/82f98df29dde91613bac8b4efaa29702ea0bdb06/UNI-24755.cfg)
[UNI-24755.cpp](https://gist.githubusercontent.com/Rassi/788d0f7d01b19bc6b19a6596e8b78f21/raw/1ee124d260698a5c999637771065f72b78b0ed90/UNI-24755.cpp)

Disclaimer:
---
Note: This is a generated issue from our internal issue tracker.
Expect a dry description which could be insufficient to properly understand the issue.
On the other hand, the support files should be sufficient to easily reproduce and debug the issue,
but please comment if it's still unclear and I will get back with clarifications.
See main discussion thread here #1223.

**Comment by Rassi** [comment]
If it is not apparent from the description, the issue seems to be caused by the line `	return type((2);` which has a missing closing parenthesis.

**Comment by gmaurel** [comment]
Correct: This is not a bug!

**Comment by mihaipopescu** [comment]
I disagree. It is a bug because uncrustify should detect the unmatched parenthesis and terminate with an error and not continue with formatting and breaking the code making it very difficult to debug.

**Comment by mihaipopescu** [comment]
@gmaurel can you reopen the bug so I can edit the bug with clarifications ? Thanks

**Comment by mihaipopescu** [comment]
@CDanU, with the new test framework for CLI can we assert that we expect an error to be returned by uncrustify ?

**Comment by CDanU** [comment]
I am not entirely sure what you mean or how this is related. 
There isn't really a new test framework. I just moved the existing CLI tests which where a bit scattered in the script directory and moved them into the new `/tests/cli` location. Additionally I almost one to one translated the existing shell script to python so that Windows users can run it locally. This way they don't  have to wait for results until Travis finishes running the shell script.

**Comment by mihaipopescu** [comment]
@CDanU I have not looked at the cli tests in depth and I don't know if they support what I'm saying.

We want to test the console output from uncrustify. It would be useful when you expect that some snippets should always generate an error from uncrustify, like this issue here, where we expect a mismatch oben brace error to be thrown while it's not.
