### ISSUE TITLE
Alignment for continued variable declarations

### ISSUE THREAD

**Issue by MdXMaxX** [uncrustify/uncrustify#1339]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

I seem to be unable to keep continued variable declarations aligned.  Say I have these lines:
```c++
uint32_t i = foo0,
         j = foo1,
         k = foo2;
```
Uncrustify will always indent lines 2 and 3 rather than keeping them aligned:
```c++
uint32_t i = foo0,
   j = foo1,
   k = foo2;
```
It would seem the indent_align_assign option set to true (which it is by default) should maintain the original alignment, but it does not.  I can't seem to find any other options that affect this alignment.  I've messed with the align_var_def_xxx options but they don't seem to have any effect.

This applies to bitfields as well.  These lines
```c++
struct
{
   uint32_t i : 16,
            j : 8,
            k : 8;
};
```
will become
```c++
struct
{
   uint32_t i : 16,
      j : 8,
      k : 8;
};
```

Additionally, if these variables happen to be references, they seem to be treated as statements and are not indented at all.  These lines
```c++
uint32_t &i = foo0,
         &j = foo1,
         &k = foo2;
```
will become
```c++
uint32_t &i = foo0,
&j = foo1,
&k = foo2;
```

Is this a bug or am I overlooking some options?

Here's the config I'm using: https://pastebin.com/14r5UMmr

Debug output (case 1):
```
# -=====-
# Line              Tag           Parent          Columns Br/Lvl/pp     Flag   Nl  Text
#   1>             TYPE[            NONE][  1/  1/  9/  0][0/0/0][  10470000][0-0] uint32_t
#   1>             WORD[            NONE][ 10/ 10/ 11/  1][0/0/0][  11800000][0-0]          i
#   1>           ASSIGN[            NONE][ 12/ 12/ 13/  1][0/0/0][ 100000000][0-0]            =
#   1>             WORD[            NONE][ 14/ 14/ 18/  1][0/0/0][     40000][0-0]              foo0
#   1>            COMMA[            NONE][ 18/ 18/ 19/  0][0/0/0][ 100000000][0-0]                  ,
#   1>          NEWLINE[            NONE][ 19/ 19/ 10/  0][0/0/0][         0][1-0]
#   2>             WORD[            NONE][  4/ 10/ 11/  0][0/0/0][  10840000][0-0]    j
#   2>           ASSIGN[            NONE][  6/ 12/ 13/  1][0/0/0][ 100000000][0-0]      =
#   2>             WORD[            NONE][  8/ 14/ 18/  1][0/0/0][     40000][0-0]        foo1
#   2>            COMMA[            NONE][ 12/ 18/ 19/  0][0/0/0][ 100000000][0-0]            ,
#   2>          NEWLINE[            NONE][ 13/ 19/ 10/  0][0/0/0][         0][1-0]
#   3>             WORD[            NONE][  4/ 10/ 11/  0][0/0/0][  10840000][0-0]    k
#   3>           ASSIGN[            NONE][  6/ 12/ 13/  1][0/0/0][ 100000000][0-0]      =
#   3>             WORD[            NONE][  8/ 14/ 18/  1][0/0/0][     40000][0-0]        foo2
#   3>        SEMICOLON[            NONE][ 12/ 18/ 19/  0][0/0/0][ 100000000][0-0]            ;
# -=====-
```
Debug output (case 3):
```
# -=====-
# Line              Tag           Parent          Columns Br/Lvl/pp     Flag   Nl  Text
#   1>             TYPE[            NONE][  1/  1/  9/  0][0/0/0][  10460000][0-0] uint32_t
#   1>            BYREF[            NONE][ 10/ 10/ 11/  1][0/0/0][ 110400000][0-0]          &
#   1>             WORD[            NONE][ 11/ 11/ 12/  0][0/0/0][  11800000][0-0]           i
#   1>           ASSIGN[            NONE][ 13/ 13/ 14/  1][0/0/0][ 100000000][0-0]             =
#   1>             WORD[            NONE][ 15/ 15/ 19/  1][0/0/0][     40000][0-0]               foo0
#   1>            COMMA[            NONE][ 19/ 19/ 20/  0][0/0/0][ 100000000][0-0]                   ,
#   1>          NEWLINE[            NONE][ 20/ 20/ 10/  0][0/0/0][         0][1-0]
#   2>            BYREF[            NONE][  1/ 10/ 11/  0][0/0/0][ 110040000][0-0] &
#   2>             WORD[            NONE][  2/ 11/ 12/  0][0/0/0][  10800000][0-0]  j
#   2>           ASSIGN[            NONE][  4/ 13/ 14/  1][0/0/0][ 100000000][0-0]    =
#   2>             WORD[            NONE][  6/ 15/ 19/  1][0/0/0][     40000][0-0]      foo1
#   2>            COMMA[            NONE][ 10/ 19/ 20/  0][0/0/0][ 100000000][0-0]          ,
#   2>          NEWLINE[            NONE][ 11/ 20/ 10/  0][0/0/0][         0][1-0]
#   3>            BYREF[            NONE][  1/ 10/ 11/  0][0/0/0][ 110040000][0-0] &
#   3>             WORD[            NONE][  2/ 11/ 12/  0][0/0/0][  10800000][0-0]  k
#   3>           ASSIGN[            NONE][  4/ 13/ 14/  1][0/0/0][ 100000000][0-0]    =
#   3>             WORD[            NONE][  6/ 15/ 19/  1][0/0/0][     40000][0-0]      foo2
#   3>        SEMICOLON[            NONE][ 10/ 19/ 20/  0][0/0/0][ 100000000][0-0]          ;
# -=====-
```

Thanks

**Comment by guy-maurel** [comment]
Well. It is **very** recommented to define only one variable pro line.
Please make a test and report.
