### ISSUE TITLE
Alignment issue when passing lambda as function parameter

### ISSUE THREAD

**Issue by ttnghia** [uncrustify/uncrustify#1340]
Hi,

I have an alignment issue when using lambda. Usually, I have successfully set up uncrustify config and get the alignment like this:
```
double t    = 0; 
double t1   = 0; 
double t111 = 0;
```
When I write a lambda, I also get the desired effect:
```
auto f = [](double x) -> double
         {
             double t    = 0;
             double t1   = 0;
             double t111 = 0;

             return ...;
         };
```

However, when I write a lambda as a parameter passed to a function, I cannot get the assignment '=' of variables t, t1, t111 aligned anymore:
```
std::transform(v1.begin(), v1.end(), v2.begin(),
               [](double x) -> double
               {
                   double t = 0;
                   double t1 = 0;
                   double t111 = 0;

                   return ...;
               }; );
```

For nested lambda, I don't have such problem:
```
auto f = [](double x) -> double
         {
             auto f = [](double x) -> double
                      {
                          auto f = [](double x) -> double
                                   {
                                       double t    = 0;
                                       double t1   = 0;
                                       double t111 = 0;

                                       return ...;
                                   };

                          return ...;
                      };

             return ...;
         };
```

I have tried to change many parameters in the config file including _align_assign_span_ and _align_assign_thresh_, but could not succeed. Did I miss something?

**Comment by guy-maurel** [comment]
Are you using an empty configuration file?
If not, push it just now.

**Comment by ttnghia** [comment]
I have a lot of configs in my config file. Here it is: [MyUncrustify.txt](https://github.com/uncrustify/uncrustify/files/1349678/MyUncrustify.txt)

**Comment by guy-maurel** [comment]
I am working on it.

**Comment by guy-maurel** [comment]
#1375 is a bugfix proposal.
Please test and report.

**Comment by ttnghia** [comment]
Tested. That works! Thanks very much 👍
