### ISSUE TITLE
Newline between bodieless while function and ';'

### ISSUE THREAD

**Issue by InfoMathze** [uncrustify/uncrustify#1341]
Hello,

I encountered a problem while trying to force newlines between a `while(condition)` and an open brace. Uncrustify does everythig as expected. But forcing a new line like `while(...)\n{` also forces a newline after the closing parentheses and a semicolon, if the while  loop has no body. This looks like that then: `while(...)\n\t;`. Is there a way to disable that or is this feature just not yet implemented.

Thank You in advance!
Best regards.

**Comment by mihaipopescu** [comment]
Please look at [issue template](https://github.com/uncrustify/uncrustify/blob/master/.github/ISSUE_TEMPLATE) to know what we need to fully reproduce the issue on our side.
At minimum, you should to provide an input snippet, expected result, uncrustify output and your configuration. Thanks.

**Comment by InfoMathze** [comment]
Hi,

sure sorry for not providing that. 
The test file, that is also the expected result: https://pastebin.com/9WD1Af1x
The config file: https://pastebin.com/z7nhL5Qb
And the debuf file: https://pastebin.com/tvyDDq0n

My uncrustify version is: Uncrustify-0.65_f

The issue is still the same.
Thanks for Your effort!
Best regards.

**Comment by CDanU** [comment]
Related: https://stackoverflow.com/questions/46056313

**Comment by InfoMathze** [comment]
Yeah, I know. It is my post. ;)

**Comment by InfoMathze** [comment]
Are there any updates?

**Comment by guy-maurel** [comment]
The issue-list is long.
The helper-list is short.

If you could join us and help it would be fine!

**Comment by kusumarajuprasanth** [comment]
Are there any updates?

**Comment by guy-maurel** [comment]
Please push as attachments your input, config, output and expected files.

**Comment by CDanU** [comment]
I, E:
```cpp
int main()
{
    int i = 20000;
    while(i--);
    return 0;
}
```

O:
```cpp
int main()
{
    int i = 20000;
    while (i--)
        ;
    return 0;
}
```
C:
```sql
# Add or remove newline between 'while' and '{'.
nl_while_brace                  = force    # ignore/add/remove/force

# Change a one-liner while statement into simple unbraced while
# 'while (i<5) foo(i++);' => 'while (i<5)\n foo(i++);'.
nl_split_while_one_liner        = true     # false/true

```

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by CDanU** [comment]
I still get the same faulty behaviour that I described above O != (I = E).
There are no braces to be newlined for `nl_while_brace` also the while loop has no body to work on for `nl_split_while_one_liner`. Yes I know that there are vbraces, but in this example they causing rather confusing behaviour.
As it is now I think this is a valid bug, we don't need any further info.

**Comment by mwoehlke** [comment]
Indeed, the current behavior seems to directly contradict `nl_after_vbrace_open_empty`...

I wonder if that is because `VBRACE_OPEN`, `SEMICOLON`, `VBRACE_CLOSE` isn't considered "empty"... but if not, I don't know how you ever could have a vbrace pair that *is* "empty".
