### ISSUE TITLE
Indentation of if...else conditional blocks inside a preprocessor condition

### ISSUE THREAD

**Issue by kudaravalli** [uncrustify/uncrustify#1369]
Hi,
   We see that the indentation doesn't seem correct when if/else conditional statement are inside preprocessor conditional statements. Please see the snippets below:

Input source:
```
void func()
{
  unsigned int a = 0;
  unsigned int b = 1;
  unsigned int t;

#if PP
if (!a)
{
  a = 2;
#endif
  t = a;
#if PP
}
else {
  t = b;
}
#endif

  return;
}

```
Expected output: 
```
void func()
{
	unsigned int a = 0;
	unsigned int b = 1;
	unsigned int t;

#if PP
	if (!a)
	{
		a = 2;
#endif
		t = a;
#if PP
	}
	else {
		t = b;
	}
#endif

	return;
}

```

Generated output with version 0.65: 
```
void func()
{
	unsigned int a = 0;
	unsigned int b = 1;
	unsigned int t;

#if PP
	if (!a)
	{
		a = 2;
#endif
	t = a;
#if PP
}
else {
	t = b;
}
#endif

	return;
}

```
Uncrustify debug text: https://pastebin.com/u5ZbBANg
Uncrustify config file: http://uncrustify.sourceforge.net/default.cfg

Thanks,
-K

**Comment by gmaurel** [comment]
It is known.
Please don't use such a structure.
