### ISSUE TITLE
closing comment sequence is not aligned when not using cmt_star_cont

### ISSUE THREAD

**Issue by koeppea** [uncrustify/uncrustify#1371]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

I have a C file that starts with a C-style multi-line commend w/o leading stars.
```c
/*
   This is a little test file.
   It has mutliple line comment at the beginning of the file w/o leading
   stars in front of each line. The opening sequence is located at column 0.
   The closing sequence should also be located at column 0.
   Let's see if I can configure uncrustify to keep this style.
*/
```
Generated output is (_note the leading space before the closing comment sequence_):
```c
/*
   This is a little test file.
   It has mutliple line comment at the beginning of the file w/o leading
   stars in front of each line. The opening sequence is located at column 0.
   The closing sequence should also be located at column 0.
   Let's see if I can configure uncrustify to keep this style.
 */

```

Expected output should be:
```c
/*
   This is a little test file.
   It has mutliple line comment at the beginning of the file w/o leading
   stars in front of each line. The opening sequence is located at column 0.
   The closing sequence should also be located at column 0.
   Let's see if I can configure uncrustify to keep this style.
*/

```

Link to uncrustify debug file: [Gist](https://gist.github.com/koeppea/9d78d4e7310c27fa7067abefeb4b9fc0)

Current uncrustify version: 0.64

If I would enable the **cmt_star_cont** option, the stars would be perfectly aligned from the opening to the closing comment sequence.
But this is not what I expect. Is there a way, to configure uncrustify that in the case **cmt_star_cont** is NOT used, the closing `*/` is aligned with the opening `/*`?

**Comment by CDanU** [comment]
You can either disable multi-line comment changes:

```sql
# If False, disable all multi-line comment changes, including cmt_width. keyword substitution and leading chars.
# Default=True.
cmt_indent_multi                = false    # false/true
```

or use this option:
```sql
cmt_indent_multi                = true    # false/true

# For multi-line comments with a '*' lead, remove leading spaces if the first and last lines of
# the comment are the same length AND if the length is bigger as the first_len minimum. Default=4
cmt_multi_first_len_minimum     = 0       # unsigned number
```

To be honest I am not entirely sure what this option does, but it seems to do what you want as long as you only have `/*` and `*/` at the beginning and end lines of your comment (actually this behavior looks like a bug, as there is no `*` lead in your example).

**Comment by koeppea** [comment]
Perfect! That does the trick. Would have never got to that combination since it's definitely not obvious.
However leaving this issue open as said.

**Comment by koeppea** [comment]
I've been a little too euphoric.
The comments in the middle of some source file do have leading starts in multi-line comments. Those are now (on purpose) unaligned.
```
/*
* this is the main function
*/
void main();
```

**Comment by eddyp** [comment]
> 
> 
> I've been a little too euphoric.
> The comments in the middle of some source file do have leading starts in multi-line comments. Those are now (on purpose) unaligned.
> 
> ```
> /*
> * this is the main function
> */
> void main();
> ```

A similar issue occurs with Doxygen comments, where I would like to have the stars unaligned:

```
/**
* @brief ...
*
* Some commetns
*/
```

As seen here, the first and last comment line can't be identical. From what I can see, I think there is a need for a **'no spaces before * on multiline comments'** option.

**Comment by koeppea** [comment]
:+1:

**Comment by eddyp** [comment]
I'm a little confused that answer was waited for in this issue. Maybe @koeppea or @gmaurel can provide some extra info.

**Comment by koeppea** [comment]
Well the answer or expected response to this issue would have been a pull-request / patch that makes the opening and closing comment tag aligned with each other when being a multi-line comment. It makes me resist completely uncrustifying our project.
