### ISSUE TITLE
Regression on newlines after constructors

### ISSUE THREAD

**Issue by byron-hawkins** [uncrustify/uncrustify#1376]
There appears to be a regression on issue #411. For example, if I start with:

    class Foo {                                                                            
        public:                                                                            
            Foo();                                                                         
            bool isBar();                                                                  
            void setBar(bool bar);                                                         
    };  
    
and then format with these settings:

    nl_after_func_proto = 2
    nl_after_func_proto_group = 2

the uncrustified result has no space between the constructor and the function `isBar`:

    class Foo {                                                                            
    public:                                                                                
        Foo();                                                                             
        bool                                                                               
        isBar();                                                                           
                                                                                           
        void                                                                               
        setBar(bool bar);                                                                  
    };   

[debug.txt](https://github.com/uncrustify/uncrustify/files/1376445/debug.txt)

    > uncrustify --version
    Uncrustify-0.65-208-9ced1ed

**Comment by guy-maurel** [comment]
Which version is running correctly ?

**Comment by byron-hawkins** [comment]
I just started using Uncrustify this week, so I have only ever tried this one version. But since issue #411 is closed, I assume there must be some working version from around that time.

**Comment by guy-maurel** [comment]
This is not a bug:
You are using:
`nl_func_type_name_class  = force`
which means:
_Add or remove newline between return type and function name inside a class {}_
Change the option to:
`nl_func_type_name_class  = remove`
to get what you wanted to get.

**Comment by byron-hawkins** [comment]
Setting `nl_func_type_name_class = remove` gives me this incorrect format:

    class Foo {
        public:
            Foo();
            bool isBar();
            void setBar(bool bar);
    };

Perhaps the original issue description was unclear? Where I said "the uncrustified result", it means "the uncrustified result _which I do not want_". Here is the format that I want:

    class Foo {
        public:
            Foo();
            
            bool 
            isBar();
            
            void 
            setBar(bool bar);
    };

Notice that there is a blank line after the constructor. This is what I want, but I cannot get it from uncrustify.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
I get, just now:
```.log
Uncrustify_d-0.70.0-5-a5979b17-dirty
class Foo {
public:
    Foo();
    bool isBar();

    void setBar(bool bar);
};
```

**Comment by byron-hawkins** [comment]
Yes, it's working for me too, as of several weeks ago when I pulled the latest. Thanks for the improvement, my code has lots of structs that often have a method or two, so this is really much nicer.
