### ISSUE TITLE
Objective-C: spaces added around colon in messages to string literals

### ISSUE THREAD

**Issue by julienp** [uncrustify/uncrustify#138]
When sending a message to a @"..." string literal, spaces are added before and after the colon, but they shouldn't be.

Input:
```objective-c
NSString *string1 = [@"foo" stringByAppendingFormat:bar];
NSString *string2 = [foo stringByAppendingFormat:bar];
```

Expected output should be equal to the input.

Actual output:
```objective-c
NSString *string1 = [@"foo" stringByAppendingFormat : bar];
NSString *string2 = [foo stringByAppendingFormat:bar];
```

Config:
```
sp_after_send_oc_colon       = remove
sp_before_send_oc_colon      = remove
```

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
