### ISSUE TITLE
Unknown symbol error in linux but not in mac

### ISSUE THREAD

**Issue by akrishna03** [uncrustify/uncrustify#1391]
Hi. I'm using uncrustify to fix the indents. 
When running on my mac, it works fine. But when i shift it to docker, I get unknown symbol error for a bunch of instructions in the config file.
I checked, and the version of uncrustify is same in both. `Uncrustify-0.65_f`

Can anyone help me understand what the issue is?

[errors_uncrustify.txt](https://github.com/uncrustify/uncrustify/files/1414510/errors_uncrustify.txt)

**Comment by mihaipopescu** [comment]
@akrishna03 Can you post your findings?
