### ISSUE TITLE
align_same_func_call_params does not work for function call following another function call

### ISSUE THREAD

**Issue by ttnghia** [uncrustify/uncrustify#1395]
Let me state the first problem. Normally, I have my code aligned as desired (var1, var22, .......var666666 are aligned by columns):
```
blank_line;
callFunction(var1,    var22,    var333);
callFunction(var4444, var55555, var666666);

callFunction(var1,    var22,    var333,    [&]() { foo(); });
callFunction(var4444, var55555, var666666, [&]() { foo(); });
```

However, when I call a function from an object resulted from another function call, I cannot get the varxxx aligned anymore:
```
blank_line;
getObject().callFunction(var1, var22, var333);
getObject().callFunction(var4444, var55555, var666666);

getObject().callFunction(var1, var22, var333, [&]() { foo(); });
getObject().callFunction(var4444, var55555, var666666, [&]() { foo(); });
```

FYI, I found a very similar issue (which is now fixed) here: https://sourceforge.net/p/uncrustify/bugs/567/.
---
Here is the second problem. uncrustify produces the following result:
```
Type tmp = call_function(getObj().x,
                         getObj().y,
                         getObj().z,
                         getObj().w);
                         getObj().result = tmp;
```

The correct result should be this:
```
Type tmp = call_function(getObj().x,
                         getObj().y,
                         getObj().z,
                         getObj().w);
getObj().result = tmp;
```
---
For generating the examples above, I use just two lines of config for uncrustify:
```
align_same_func_call_params = true
nl_cpp_lambda_leave_one_liners  = true
```

**Comment by guy-maurel** [comment]
For the first message you need to set the option:
`nl_cpp_lambda_leave_one_liners = true`
to get what you want to get.

**Comment by guy-maurel** [comment]
#1658 is a bugfix proposal.
Please test and report

**Comment by guy-maurel** [comment]
Fixed
