### ISSUE TITLE
segmentation fault with malformed input file

### ISSUE THREAD

**Issue by waldyrious** [uncrustify/uncrustify#1400]
Any file ending with a `#`, without newline at the end, crashes Uncrustify with a segmentation fault (found by experimenting with [afl-fuzz](http://lcamtuf.coredump.cx/afl/)).

Reproduction steps:

    $ uncrustify -v
    Uncrustify-0.65-270-bc41097
    $ echo -n '#' > crash.c
    $ uncrustify -c etc/defaults.cfg crash.c
    Output suffix: .uncrustify
    Parsing: crash.c as language C
    Segmentation fault

(calling with `-p debug.txt` produces no debug.txt file)

Edit: this also happens if the `#` is followed by whitespace (` `, `\v`, `\t`), but not `\n` or `\r`. If the line contains any non-whitespace character, there's no crash.

**Comment by waldyrious** [comment]
Two other simple patterns found by afl-fuzz:

- Any file starting echo `&&` followed by anything other than whitespace (`echo '&&a' > crash.c`)
- Any file starting with `<<`, regardless of what follows (`echo '<<' > crash.c`)

**Comment by CDanU** [comment]
Unfortunately I believe that should be a significant amount of similar issues. Some errors can be easily found with clang tools, fuzzying should find even more. 

It would be nice if you could provide some execution scripts or a short writeup on how to use afl-fuzz.

**Comment by waldyrious** [comment]
> It would be nice if you could provide some execution scripts or a short writeup on how to use afl-fuzz.

That was my plan, yeah :) I have some assorted notes that, once cleaned up, I'll submit as a [tldr-pages](https://github.com/tldr-pages/tldr) entry. It may take a few days or weeks, depending on available time.

**Comment by jibsen** [comment]
Just for reference:
  - `#` crashes at indent.cpp:391 with pc=0
  - `&&a` crashes at tokenize_cleanup.cpp:844 with prev=0
  - `<<` crashes at align_stack.cpp:180 with ref=0

**Comment by waldyrious** [comment]
For convenience:

> `#` crashes at indent.cpp:391 with pc=0

https://github.com/uncrustify/uncrustify/blob/5194333f3c8fbfd949375f3ac1d7eebd3abe3949/src/indent.cpp#L391-L392

> `&&a` crashes at tokenize_cleanup.cpp:844 with prev=0

https://github.com/uncrustify/uncrustify/blob/5194333f3c8fbfd949375f3ac1d7eebd3abe3949/src/tokenize_cleanup.cpp#L844

> `<<` crashes at align_stack.cpp:180 with ref=0

https://github.com/uncrustify/uncrustify/blob/5194333f3c8fbfd949375f3ac1d7eebd3abe3949/src/align_stack.cpp#L180

**Comment by mihaipopescu** [comment]
I'm quite sure they are plenty of cases found with fuzz testing in which uncrustify can crash and they can represent valid issues but I'm not sure if it's uncrustify's main concern right now. Sure it would be very nice to get these fixed and to make it bulletproof but the main problem is that uncrustify has issues with normal, compilable code which because it is not parsed correctly is formatted incorrectly, it is broken by uncrustify after is was formatted (like remove  semicolons) or even crash the program.

Still I think the worse kind of bugs are the silent ones when everything seem to go well but code gets broken in some `#ifdef`'ed code which you find out very late when it's very expensive to fix.

If a tool crashes, then you know something's wrong and we you can investigate. That's what we do. Even the user can say: "huh, that's really bad but maybe I shouldn't feed it garbage".

Maybe it would be more interesting to find real compilable snippets that crash uncrustify, maybe taken from github itself (a script can do that).

**Comment by waldyrious** [comment]
> Maybe it would be more interesting to find real compilable snippets that crash uncrustify, maybe taken from github itself (a script can do that).

I actually just yesterday found out about [csmith](http://embed.cs.utah.edu/csmith/), a tool that can generate valid, compilable code examples. It could be used to stress-test uncrustify this way -- i.e. with non-malformed code. I suppose that might be easier than fetching code from Github (but of course both approaches be used).

**Comment by mihaipopescu** [comment]
Great find!

**Comment by gmaurel** [comment]
Fine.
Could you make some integration work to add it in uncrustify?

**Comment by waldyrious** [comment]
I'm afraid I don't have the skills to do so. I had been curious about afl-fuzz for a while and decided to try it out, and uncrustify seemed like an interesting target. Other than that, I don't really know much about setting it up properly.

What I mean by this is that the AFL documentation mentions [several](https://github.com/mirrorer/afl/blob/007fa4e/docs/README#L142-L161) [preliminary](https://github.com/mirrorer/afl/blob/007fa4e/docs/parallel_fuzzing.txt#L11-L17) [adjustments](https://github.com/mirrorer/afl/blob/master/docs/perf_tips.txt), without which a naive approach (like what I did) would almost certainly just waste CPU cycles trying to brute-force a huge number of irrelevant paths.

Besides, it would probably be impractical to run such tests at the continuous integration level with the usual resources available for this kind of project (the developers' own machines, TravisCI, etc.). For integration, the way to go seems to be joining Google's [OSS-Fuzz program](https://github.com/google/oss-fuzz) -- which I also just found out about last week :)

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by mihaipopescu** [comment]
We should have some (cli) tests with malformed code to ensure it works and uncrustify doesn't crashes.

**Comment by waldyrious** [comment]
> The current git version works pretty fine.
> Please test it and report!

Indeed, none of the failing test cases mentioned in the two opening comments above produces a segmentation fault anymore.

I'll go ahead and mark this as closed :)
