### ISSUE TITLE
Feature request: Display line number and offset when error encountered

### ISSUE THREAD

**Issue by jcwren** [uncrustify/uncrustify#1417]
Feature request: Display line number and line offset and/or byte offset into file where an error occurred.

I had to use ```hexdump -Cv lp.c | grep ' 00 '``` to find the offset, and then find the matching line. Having the errored line and offset would have been handy.

```
$ uncrustify.exe -c ~/uc.cfg lp.c
Output suffix: .uncrustify
Parsing: lp.c as language C
An embedded 0 was found in 'lp.c'.
The file may be encoded in an unsupported Unicode format.
Aborting.
```

**Comment by CDanU** [comment]
Test if the referenced PR generates what you want to see.

**Comment by jcwren** [comment]
Looks good to me. Ship it!

**Comment by CDanU** [comment]
@gmaurel close this one
