### ISSUE TITLE
Objective C: Ellipsis used in conjunction with numbers in Switch blocks

### ISSUE THREAD

**Issue by pivotal-alex-christodoulou** [uncrustify/uncrustify#142]
case 400000 ... 499999: {
                //Visa
                type = @"Visa";
            } break;

becomes
            case 400000...499999: {
                //Visa
                type = @"Visa";
            } break;

Which is not valid code. I've set sp_before_ellipsis to add but with no luck. Spaces before and after the ellipsis are required to make the syntax valid.

**Comment by mobits** [comment]
Having the same problem. Any news from this "bug" yet?

**Comment by gmaurel** [comment]
Works fine
`switch (19) {
case 400000...499999: {
        //Visa
        type = @"Visa";
} break;
}`
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
