### ISSUE TITLE
Version 0.66 is now available

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1423]
There are still some little problems:
The tag 0.66 within git is not exactly at the right place, some documentation files are created some minutes later.
Build under buildwin-xx generate some warnings:
```
[  5%] Building CXX object CMakeFiles/uncrustify.dir/src/align.cpp.obj
In file included from /home/guy/Software/uncrustify/src/base_types.h:16:0,
                 from /home/guy/Software/uncrustify/src/uncrustify_types.h:15,
                 from /home/guy/Software/uncrustify/src/align.h:11,
                 from /home/guy/Software/uncrustify/src/align.cpp:10:
/home/guy/Software/uncrustify/src/windows_compat.h:12:0: warning: "NOMINMAX" redefined [enabled by default]
 #define NOMINMAX
 ^
In file included from /usr/include/c++/4.8/i686-w64-mingw32/bits/c++config.h:426:0,
                 from /usr/include/c++/4.8/bits/stl_algobase.h:59,
                 from /usr/include/c++/4.8/vector:60,
                 from /home/guy/Software/uncrustify/src/uncrustify_types.h:12,
                 from /home/guy/Software/uncrustify/src/align.h:11,
                 from /home/guy/Software/uncrustify/src/align.cpp:10:
/usr/include/c++/4.8/i686-w64-mingw32/bits/os_defines.h:45:0: note: this is the location of the previous definition
 #define NOMINMAX 1
 ^
```

**Comment by CDanU** [comment]
> The tag 0.66 within git is not exactly at the right place, some documentation files are created some minutes later.
Could you explain the problem a bit more? I will add a `#ifdef` check for `NOMINMAX` that should fix the error.

**Comment by CDanU** [comment]
Yes it is possible to change the tags without changing the commit hashes: 
```
git tag -d uncrustify-0.66
git tag -a uncrustify-0.66 0b0f999250e0992363cad7a1680ff03b769df491
git push --tags
```
I had to use -f (foce) for the last push command on my fork, try __without__ it. 
If this succeeds you maybe have to recreate the release zip.

**Comment by CDanU** [comment]
@gerasiov Do you know if ^ would cause problems for you?

**Comment by AMDmi3** [comment]
I haven't quite catched, is the tag correct now? I'm planning to update the port in short time, it would be a problem if tag is changed afterwards. For now, it builds fine and all tests pass on amd64.

**Comment by gerasiov** [comment]
Please do not change tags in public repo. Create 0.66.1 instead.
I uploaded package to Debian based on archive i got from github on Wed Nov 8 18:15:58 2017

I also should mention, that there are some bugs on several arches (e.g. on i386) see #1428

**Comment by gmaurel** [comment]
Thanks for testing other architectures. I have only x86_64.

**Comment by AMDmi3** [comment]
So, is current 0.66 tag safe to use?

**Comment by guy-maurel** [comment]
Please still wait one or two weeks until version 0.66.1
Thanks

**Comment by AMDmi3** [comment]
Ok

**Comment by guy-maurel** [comment]
Thanks for helping

**Comment by AMDmi3** [comment]
FYI, FreeBSD port was updated to 0.66.1
