### ISSUE TITLE
dependency is missed

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1429]
I am missing a dependency between the last created "tag" and the file uncrustify_version.h.
How to do it?

**Comment by CDanU** [comment]
I don't entirely get the question. Is this still relevant?

**Comment by guy-maurel** [comment]
Yes, it is still relevant.
As "admin", I make a new tag every 6 months.
I wish to get a new `uncrustify_version.h` file generated as it could be defined in the `CMakeLists.txt`.

**Comment by CDanU** [comment]
The `uncrustify_version.h` inside the src dir was replaced with the change to CMake to `uncrustify_version.h.in`. This file is used to generate the `uncrustify_version.h` based on the variables inside `CMakeLists.txt`. It already does what you want.

**Comment by guy-maurel** [comment]
NO. I havn't any `uncrustify_version.h` in the `src` directory, but the `uncrustify_version.h.in` , which created the desired `build/uncrustify_version.h` by using `cmake ..` inside the `build` dir.
I get something such as:
`#define UNCRUSTIFY_VERSION    "Uncrustify-0.66-52-e4f8c41-dirty`
as there are many commits after the tag 0.66

After making a new tag, such as `0.66.1`, I would like to run `cmake ..` again and get a new file,
but `CMakeLists.txt` doesn't have any dependency to do that.
Today, I need to remove the file myself to get a new one.
I wish it better.

**Comment by CDanU** [comment]
Hmm I still feel like I am missing something .. 

Inside the [CMakeLists.txt:155](https://github.com/uncrustify/uncrustify/blob/master/CMakeLists.txt#L155)  the `configure_file` is set up to generate the `uncrustify_version.h`. It does so, successfully, every time If execute `cmake ..`. Is that what you mean by dependency?

**Comment by guy-maurel** [comment]
- copy the <uncrustify> dir to uncrustify-test
# build it new
- `mkdir build; cmake ..; make`
- uncrustify-test/build $ `./uncrustify -v`
Uncrustify-0.66-98-64dbc43
# introduce a new tag
- uncrustify-test $ `git tag -a uncrustify-0.66.1`
# make it new
-uncrustify-test/build $ `make`
[100%] Built target uncrustify
# nothing is to do
- guy@renard ~/Software/uncrustify-test/build $ `./uncrustify -v`
Uncrustify-0.66-98-64dbc43
The version doesn't change. But
I wish some "target" to produce the change

**Comment by CDanU** [comment]
So the problem is that you want the `configure_file` command to be executed without manually calling cmake.

**Comment by guy-maurel** [comment]
No. I only wish a new target.
If there is a new git-tag, such as (just now) 0.66.1, the file should be new generated as I start make the first time after creating the new git-tag.
