### ISSUE TITLE
C++: function prototype with template return type is incorrectly marked by mark_function_return_type

### ISSUE THREAD

**Issue by parapaul** [uncrustify/uncrustify#1432]
There is a bug with 'nl_after_func_proto_group' option, which reproduces for function prototypes with template return type. A group of function prototypes like this
```
void set();
vector<int> get();
```
is formatted like this when nl_after_func_proto = 0 and nl_after_func_proto_group = 2 
```
void set();

vector<int> get();
```
 -- function prototypes group wasn't recognized here, because the second prototype return type ('vector') parent type wasn't set to 'FUNC_PROTO' by 'mark_function_return_type' function:
```
...
#   2>          TYPE[         NONE][ 1/ 1/ 7/ 0][0/0/0][    460000][0-0] vector
#   2>    ANGLE_OPEN[     TEMPLATE][ 7/ 7/ 8/ 0][0/0/0][ 100000040][0-0]       <
#   2>          TYPE[         NONE][ 8/ 8/11/ 0][0/1/0][     40040][0-0]        int
#   2>   ANGLE_CLOSE[   FUNC_PROTO][11/11/12/ 0][0/0/0][ 100000040][0-0]           >
#   2>    FUNC_PROTO[         NONE][13/13/16/ 1][0/0/0][    840000][0-0]             get
...
```
I'll create pull-request with suggested fix soon.

**Comment by guy-maurel** [comment]
Fixed at #1433
