### ISSUE TITLE
C++: now nl_after_struct affects forward declarations of structs

### ISSUE THREAD

**Issue by parapaul** [uncrustify/uncrustify#1439]
Found this problem while migrating from version 0.62: option 'nl_after_struct' now affects forward declarations of structs (I don't think it is intended since 'nl_after_class' doesn't affect forward declarations of classes). To be clear, now with 'nl_after_struct = 2' code like this 
```
struct A;
struct B;
```
becomes this:
```
struct A;

struct B;
```

The root cause of this problem is that parent type for semicolon is incorrectly set to 'CT_STRUCT' in struct forward declarations. This line of code that caused this behaviour: https://github.com/uncrustify/uncrustify/commit/51f902e77b55f8a96a4edaa5c79cded7fc9f928c#diff-24fd9315bbb9c220fccf13e249282697R2545

Will suggest fix soon.

**Comment by gmaurel** [comment]
Fixed at #1554
