### ISSUE TITLE
Use of .editorconfig for formating rules

### ISSUE THREAD

**Issue by cYCL157** [uncrustify/uncrustify#1442]
I have use this tool for awhile and loved it!  With the incorporation of .editorconfig support in VS2017, it would be really nice to know that I could guarantee the same rules between my experience in VS and with the command line uncrustify.  I am doing some code generation and would like to not have issues with "reformatting" commits.

**Comment by CDanU** [comment]
Could you be more specific about what it is that you need? I assume you are talking about this: [editorconfig.org](http://editorconfig.org/), more specifically about [EditorConfig-Properties](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties), right? Looking shortly through it it looks like we have matching options for most properties.

Keep in mind that Uncrustify does __not__ change the `charset` of a file, it can read ascii, utf8 and both utf16 encodings. For whitespace trimming look at #132

```sql
# Try to limit code width to N number of columns
code_width                      = 0       # unsigned number
```
which matches `max_line_length` can be problematically. Also we don't have something that matches
`indent_style = tab`, the closest thing would be:

```sql
# How to use tabs when indenting code
# 0=spaces only
# 1=indent with tabs to brace level, align with spaces (default)
# 2=indent and align with tabs, using spaces when not on a tabstop
indent_with_tabs                = 2        # unsigned number
``` 
but that also has issues.
