### ISSUE TITLE
Strange indentation of function in a struct

### ISSUE THREAD

**Issue by byron-hawkins** [uncrustify/uncrustify#1452]
This tarball contains the test input file, the configuration input file, and the debug output:

[test-with-debug.tar.gz](https://github.com/uncrustify/uncrustify/files/1503158/test-with-debug.tar.gz)

Here is the sample input file:

    struct foobar {
        char *foobar() { return "foobar"; }
        char *foo_bar() { return "foo_bar"; }

        int foo;
    };

Uncrustify should line-wrap at the function names, with no indent, like this:

    struct foobar {
        char *
        foobar() { return "foobar"; }
        char *
        foo_bar() { return "foo_bar"; }

        int foo;
    };

Instead uncrustify ignores the function `foobar()`, but indents the function `foo_bar()` like this:

    struct foobar {
        char *foobar() { return "foobar"; }
        char *
            foo_bar() { return "foo_bar"; }

        int foo;
    };

Adding or removing characters from the name of `foobar()` will cause it to be indented similarly--the behavior is quite illogical. 

I built uncrustify from github recently:

    > uncrustify -v
    Uncrustify-0.65-208-9ced1ed

Since I am new to uncrustify, I do not know of any past version that formats this file correctly.

**Comment by guy-maurel** [comment]
If you want to test with old versions, you could get them under:
  https://sourceforge.net/projects/uncrustify/files/uncrustify/

**Comment by CDanU** [comment]
068c651d87863f8ecda20d79e1b244ee045fb98f has the same behavior.

reduced config:
```sql

# Don't split one-line braced statements inside a class xx { } body.
nl_class_leave_one_liners       = true     # false/true

# Add or remove newline between return type and function name in a function definition.
nl_func_type_name               = force    # ignore/add/remove/force

# The span for aligning struct/union (0=don't align)
align_var_struct_span           = 99       # unsigned number
```
```
