### ISSUE TITLE
initialization list alignment

### ISSUE THREAD

**Issue by tizzleboy** [uncrustify/uncrustify#146]
Hi,

"nl_class_init_args = add" doesn't seem to work,

Apart from that, indentation of the initializer list is different for inherented classes:

// ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
class Foo
{};

class Boo
{
public:
....Boo() :
........a_(0),
........b_(0)
....{}
....int a_;
....int b_;
};

int main()
{}
// ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ----------

vs.

// ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
class Foo
{};

class Boo : Foo
{
public:
....Boo() :
....a_(0),
....b_(0)
....{}
....int a_;
....int b_;
};

int main()
{}
// ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ----------

**Comment by tmbeniamin** [comment]
This is for me to. 
I've used the settings:

    Virtual indent from the ':' for member initializers. Default is 2
    indent_ctor_init_leading = 2

    Additional indenting for constructor initializer list
    indent_ctor_init = 2

And I have the code:
```
one_class::one_class(
 const std::string& name,
 i_event_processing_callback* const event_processing_callback ):
 inherited_class( name, event_processing_callback ),
 status( t_status::NEW ),
 run_and_event_mutex(),
 run_and_event_condition(),
 worker_thread(),
 m_run( false ) 
{
    // Nothing to do...
}
```
And I want to have as follow:
```
one_class::one_class(
 const std::string& name,
 i_event_processing_callback* const event_processing_callback ):
  inherited_class( name, event_processing_callback ),
  status( t_status::NEW ),
  run_and_event_mutex(),
  run_and_event_condition(),
  worker_thread(),
  m_run( false )    
{
    // Nothing to do...
}
```

I've also asked [here](http://stackoverflow.com/questions/38452977/uncrustify-options-indent-ctor-init-and-indent-ctor-init-leading-seems-not-to-wo) but with no answer till now (20.07.2016).

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
