### ISSUE TITLE
setting a keyword as comment doesn't work right [C]

### ISSUE THREAD

**Issue by pksadiq** [uncrustify/uncrustify#1460]
version: Uncrustify-0.66.1-22-b91ffd80 (current HEAD as of writing)

When I set a keyword as a comment, the following line is dismantled.

A minimal configuration:

```
# Hack to avoid indentation of following line
set COMMENT G_DECLARE_FINAL_TYPE
sp_arith = force
```

Input file (test.h):

```
#define MGT_TYPE_WINDOW (mgt_window_get_type ())

G_DECLARE_FINAL_TYPE (MgtWindow, mgt_window, MGT, WINDOW, GtkApplicationWindow)

MgtWindow *mgt_window_new (MgtApplication *app);
```

When uncrustify is run on the code, no change should be made. But after uncrustify the last line changes to:
`MgtWindow * mgt_window_new (MgtApplication * app);`

I'm trying to workaround #1316.Please let me know if there is alternate way of doing this.
Thanks

**Comment by CDanU** [comment]
If you look at a debug file for your example you will see that is sets only `G_DECLARE_FINAL_TYPE` as comment token but does not squash the next tokens until a next line into it as it does for actual comments. So that won't work. 

Based on the conversation on #643 I made a dirty prototype that does a similar to the above, not in your example occurring, squashing, only that it is done while a clean up after the rough tokenization is actually finished.

I am yet not entirely sure if such a _hack_ is actually something that should be integrated, but you can test it out and give me feedback if you want.

```diff
diff --git a/src/ListManager.h b/src/ListManager.h
index b91d047c..ee86bbf5 100644
--- a/src/ListManager.h
+++ b/src/ListManager.h
@@ -128,6 +128,79 @@ public:
       }
    }
 
+   /**
+    * @brief deletes an element from a linked list
+    *
+    * @param[in] obj  list element to remove, ptr will be deleted
+    */
+   void Erase(T *obj)
+   {
+       if(obj == nullptr)
+       {
+           return;
+       }
+
+       this->Pop(obj);
+       delete obj;
+   }
+
+
+   /**
+    * @brief deletes a range of elements from a linked list
+    *
+    * @param[in] objS  first list element to remove, ptr will be deleted
+    *                  is set to first list list element if nullptr
+    * @param[in] objE  last list element to remove, ptr will be deleted
+    *                  is set to last list element if nullptr
+    *
+    */
+   void Erase(T *objS, T *objE)
+   {
+       if(objS == nullptr && objE == nullptr)
+       {
+           return;
+       }
+       if(objS == nullptr)
+       {
+           objS = first;
+       }
+       if(objE == nullptr)
+       {
+           objE = last;
+       }
+
+       auto pre = objS->prev;
+       auto post = objE->next;
+
+       if (pre != nullptr && post != nullptr)
+       {
+           pre->next = post;
+           post->prev = pre;
+       }
+       else if(pre != nullptr)
+       {
+           pre->next = nullptr;
+           last = pre;
+       }
+       else if(post != nullptr)
+       {
+           post->prev = nullptr;
+           first = post;
+       }
+       // else: everything gets deleted, so don't bother
+
+
+       auto cur = objS;
+       while(cur != nullptr && cur != objE)
+       {
+           auto d = cur;
+           cur = cur->next;
+
+           delete d;
+       }
+       delete objE;
+   }
+
 
    //! swap two elements of a list
    void Swap(T *obj1, T *obj2)
diff --git a/src/chunk_list.cpp b/src/chunk_list.cpp
index 535f8f21..975d1d3b 100644
--- a/src/chunk_list.cpp
+++ b/src/chunk_list.cpp
@@ -465,8 +465,12 @@ chunk_t *chunk_add_before(const chunk_t *pc_in, chunk_t *ref)
 void chunk_del(chunk_t *pc)
 {
    chunk_log(pc, "chunk_del:");
-   g_cl.Pop(pc);
-   delete pc;
+   g_cl.Erase(pc);
+}
+
+void chunk_del(chunk_t *pcS, chunk_t *pcE)
+{
+   g_cl.Erase(pcS, pcE);
 }
 
 
diff --git a/src/chunk_list.h b/src/chunk_list.h
index a4c5c3a7..6b66f2a5 100644
--- a/src/chunk_list.h
+++ b/src/chunk_list.h
@@ -91,6 +91,15 @@ chunk_t *chunk_add_before(const chunk_t *pc_in, chunk_t *ref);
 void chunk_del(chunk_t *pc);
 
 
+/**
+ * delete a chunk range from a chunk list
+ *
+ * @param pcS  first chunk to delete
+ * @param pcE  last chunk to delete
+ */
+void chunk_del(chunk_t *pcS, chunk_t *pcE);
+
+
 /**
  * move a chunk to after the reference position in a chunk list
  *
diff --git a/src/token_enum.h b/src/token_enum.h
index 1bb4006d..723836a9 100644
--- a/src/token_enum.h
+++ b/src/token_enum.h
@@ -46,6 +46,7 @@ enum c_token_t
    CT_COMMENT_ENDIF, // C-comment, single line, after ENDIF
 
    CT_IGNORED,       // a chunk of ignored text
+   CT_IGNORED_WORDPAREN, // ignore a word(*) pattern, use 'set WORDPAREN_IGN word', word will be set to CT_IGNORED
 
    CT_WORD,          // variable, type, function name, etc
    CT_NUMBER,
diff --git a/src/tokenize_cleanup.cpp b/src/tokenize_cleanup.cpp
index a70e2255..3a33767f 100644
--- a/src/tokenize_cleanup.cpp
+++ b/src/tokenize_cleanup.cpp
@@ -21,7 +21,11 @@
 #include "combine.h"
 #include "keywords.h"
 #include <cstring>
+#include <string>
+#include <sstream>
 
+using std::string;
+using std::stringstream;
 
 /**
  * If there is nothing but CT_WORD and CT_MEMBER, then it's probably a
@@ -162,6 +166,59 @@ void tokenize_cleanup(void)
    next = chunk_get_next_ncnl(pc);
    while (pc != nullptr && next != nullptr)
    {
+      if (pc->type == CT_IGNORED_WORDPAREN && chunk_is_paren_open(next))
+      {
+         auto paren_open  = next;
+         auto paren_close = chunk_skip_to_match(next);
+         if (paren_close != nullptr)
+         {
+//            pc->type = CT_IGNORED;
+
+            stringstream ss;
+//            ss << string(pc->column, ' ') << pc->str.c_str();
+            ss << pc->str.c_str();
+
+            next = paren_open;
+            for (auto cur = pc
+                 ; next != paren_close
+                 ; cur = next, next = chunk_get_next(next))
+            {
+               if (next->type == CT_NEWLINE)
+               {
+                  pc->str = ss.str();
+                  pc->next = next;
+                  ss.clear();
+                  chunk_del(chunk_get_next(pc), chunk_get_prev(next));
+
+                  pc = chunk_get_next(pc);
+                  if (pc == nullptr)
+                  {
+                     break;
+                  }
+                  pc->type = CT_IGNORED;
+                  ss << pc->str.c_str();
+
+                  cur  = pc;
+                  next = chunk_get_next(pc);
+                  if (next == nullptr)
+                  {
+                     break;
+                  }
+               }
+
+               const auto cur_len = cur->orig_col_end - cur->orig_col;
+               const auto nr_spaces = next->column - (cur->column + cur_len);
+               ss << string(nr_spaces, ' ') << next->str.c_str();
+            }
+            ss << paren_close->str.c_str();
+            pc->str = ss.str();
+            pc->next = paren_close->next;
+
+            chunk_del(paren_close);
+            next = chunk_get_next_ncnl(pc);
+         }
+      }
+
       if (pc->type == CT_DOT && (cpd.lang_flags & LANG_ALLC))
       {
          set_chunk_type(pc, CT_MEMBER);
diff --git a/src/unc_text.cpp b/src/unc_text.cpp
index e4d37087..835765e1 100644
--- a/src/unc_text.cpp
+++ b/src/unc_text.cpp
@@ -548,7 +548,7 @@ void unc_text::append(const unc_text &ref)
    m_logtext.pop_back();
    m_logtext.insert(std::end(m_logtext),
                     std::begin(ref.m_logtext), std::end(ref.m_logtext));
-   m_logtext.push_back('\0');
+   //\0 added from ref
 
 
    m_chars.insert(m_chars.end(), ref.m_chars.begin(), ref.m_chars.end());
```

**Comment by pksadiq** [comment]
> I am yet not entirely sure if such a hack is actually something that should be integrated, but you can test it out and give me feedback if you want.
You are right. But I'm just trying to work around until the other bug is fixed.

The patch seems not working. Actually what I'm trying to mock is some variable, which if I set, will consider the keyword as `//` so that whatever follows will be considered as comment.

On a cursory look on the code, it seems like a paren has to be followed.

**Comment by CDanU** [comment]
Yes you can add

```
set IGNORED_WORDPAREN G_DECLARE_FINAL_TYPE
```

and it will set G_DECLARE_FINAL_TYPE and everything inside the following braces to on token with the type `IGNORED_WORDPAREN`.

I tested you example and indeed that dosn't solve your problem as the star sill will be treated as `CT_ARITH`.
I guess there is some another bug. I will check that later.

**Comment by guy-maurel** [comment]
The problem is caused by the missing semicolon at the end of the 3.rd line.
This is NOT a bug.

**Comment by pksadiq** [comment]
> The problem is caused by the missing semicolon at the end of the 3.rd line.
> This is NOT a bug.

If you mean the line `G_DECLARE_FINAL_TYPE (MgtWindow, mgt_window, MGT, WINDOW, GtkApplicationWindow)`, yes, there is a missing semicolon, and that's the point of this bug report/feature request.

macros can be defined in various ways. Consider `G_DECLARE_FINAL_TYPE` a macro defining a function, or say, it already ends with a semicolon. So it shouldn't end with a semicolon.

**Comment by guy-maurel** [comment]
_So it shouldn't end with a semicolon._
But it is not forbidden!
Your configuration file:
```.cfg
set COMMENT G_DECLARE_FINAL_TYPE
```
What is _COMMENT_ ?
Is it a C comment? Such as
```.c
/* G_DECLARE_FINAL_TYPE */
```
If C comment, what is _(MgtWindow, mgt_window, MGT, WINDOW, GtkApplicationWindow)_ for the compiler?

Is it a CPP comment? Such as
```.cpp
// (MgtWindow, mgt_window, MGT, WINDOW, GtkApplicationWindow)
```
Then please use **COMMENT_CPP** instead of.
And the rest of the line should be also be the comment.
It is not yet, it is a bug.
Which one do you wish to get?

**Comment by pksadiq** [comment]
> _So it shouldn't end with a semicolon._
> But it is not forbidden!

Well, I could create some examples where an extra semicolon is forbidden (eg: for a single line `if` statement followed by an `else`). But may be in that case, marking it as comment wouldn't be an option either.

> Then please use **COMMENT_CPP** instead of.
> And the rest of the line should be also be the comment.
> It is not yet, it is a bug.
> Which one do you wish to get?

Yeah, I think this is what I need. But it still seems to have some issue:

example config:
```
sp_cmt_cpp_start = force
set COMMENT_CPP G_DECLARE_FINAL_TYPE
```

example code (`header.h`):
```c
G_DECLARE_FINAL_TYPE (CcWindow, cc_window, CC, WINDOW, GtkApplicationWindow)
```

resulting code:
```c
G_ DECLARE_FINAL_TYPE(MgtWindow, mgt_window, MGT, WINDOW, GtkApplicationWindow)
```

The space before `(` is gone. Am I doing something wrong?

**Comment by guy-maurel** [comment]
PR #2552 is a bugfix proposal.
Please test it and report.

**Comment by pksadiq** [comment]
Sorry, for the delay. I tested and it  breaks if space after comment is forced.

Example code (header.h):
```c
G_DECLARE_FINAL_TYPE(MgtWindow, mgt_window, MGT, WINDOW, GtkApplicationWindow)
```

config:
```
sp_cmt_cpp_start = force
set COMMENT_CPP G_DECLARE_FINAL_TYPE
```

Result:
```c
G_ DECLARE_FINAL_TYPE(MgtWindow, mgt_window, MGT, WINDOW, GtkApplicationWindow)
```

a space is inserted after `G_` and no space after `...TYPE`

Expected result:
```c
```c
G_DECLARE_FINAL_TYPE (MgtWindow, mgt_window, MGT, WINDOW, GtkApplicationWindow)
```

**Comment by guy-maurel** [comment]
Please, make a test, just now and report.

**Comment by pksadiq** [comment]
Hi,

The issue specified in https://github.com/uncrustify/uncrustify/issues/1460#issuecomment-558986765 still exists

**Comment by guy-maurel** [comment]
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by pksadiq** [comment]
> Please test it and report!

Looks like it does work. I no longer want to even set the macro as a comment. Though the issue specified in https://github.com/uncrustify/uncrustify/issues/1460#issuecomment-558986765 persists
