### ISSUE TITLE
Comparison inside template parameter causes unmatched ANGLE_OPEN

### ISSUE THREAD

**Issue by bartholomule** [uncrustify/uncrustify#1462]
If comparisons with > or < appear within a template, the result is an unmatched ANGLE_OPEN.
GCC emits (or used to emit) warnings if these comparisons were not done within parentheses.

Example (see full code in [test.cpp.txt]):
```
template <
    typename... Args,
    typename E = typename std::enable_if<(sizeof...(Args) >= 1), bool>::type
>
void fun1(Args&& ...args)
{
}
```
Config file used: default.cfg
Uncrustify version: Uncrustify-0.66.1-22-b91ffd8 (Latest from git -- commit b91ffd8011e59c68d9f0a9ad89a621872eb6194c)
Expected: Code should be formatted properly.

Result:
Errors are emitted:
> $ ./uncrustify -p debug.txt -c default.cfg -f test.cpp -o test.cpp.new
> Parsing: test.cpp as language CPP
> test.cpp:3 Unmatched ANGLE_OPEN
> test.cpp:11 Unmatched ANGLE_OPEN
> test.cpp:3 Unmatched ANGLE_OPEN
> test.cpp:11 Unmatched ANGLE_OPEN

The attached patch ([uncrustify_patch1.txt]) to tokenize_cleanup.cpp seems to fix it by only incrementing or decrementing the template level if there are no outstanding (unbalanced) paren.

I haven't tested more complex metaprogramming with it.  I suspect that it may still be possible to come up with something using nested templates that will still break it.

[debug.txt](https://github.com/uncrustify/uncrustify/files/1512406/debug.txt)
[test.cpp.txt](https://github.com/uncrustify/uncrustify/files/1512408/test.cpp.txt)
[uncrustify_patch1.txt](https://github.com/uncrustify/uncrustify/files/1512409/uncrustify_patch1.txt)

**Comment by guy-maurel** [comment]
Please, make a "PR" (pull request) with your patch.
The servers will make more tests for you.

**Comment by CDanU** [comment]
I don't think that the parenthesis are what is causing the problem, here is how the frm.pse_tos changes in your example (last brace pair ommited)
```
     ANGLE_OPEN:  1: 10 | 0 -> 1
         ASSIGN:  3: 16 | 1 -> 2
     ANGLE_OPEN:  3: 41 | 2 -> 3
     PAREN_OPEN:  3: 42 | 3 -> 4
     PAREN_OPEN:  3: 52 | 4 -> 5
    PAREN_CLOSE:  3: 57 | 5 -> 4
         ASSIGN:  3: 60 | 4 -> 5
    PAREN_CLOSE:  3: 63 | 5 -> 4
    PAREN_CLOSE:  3: 63 | 4 -> 3
    ANGLE_CLOSE:  3: 70 | 3 -> 2
    FPAREN_OPEN:  5: 10 | 2 -> 3
   FPAREN_CLOSE:  5: 25 | 3 -> 2
      SEMICOLON:  5: 26 | 2 -> 1
```

**Comment by guy-maurel** [comment]
PR #2577 is a bugfix proposal.
Please test it and report.
