### ISSUE TITLE
missing test data for some options

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1463]
After having reduce the options at the tests/config/*.cfg files, I take all cfg files together.
Sort the data, make lines unique and compare with the etc/defaults.cfg.
There are (today) 127 options without any tests data!
The list is attached [missing.txt](https://github.com/uncrustify/uncrustify/files/1515052/missing.txt)
Can anybody suply any test-data for those?
Thanks.

**Comment by CDanU** [comment]
Here is a list with the commits that introduced the options:
<details><summary>List</summary>
<pre>
               UO_sp_inside_braces_enum 149a79e095ef9809ad40f5ae23d808d2b18c3140 Import release 0.0.5
                     UO_nl_define_macro 149a79e095ef9809ad40f5ae23d808d2b18c3140 Import release 0.0.5
                      UO_sp_paren_brace 149a79e095ef9809ad40f5ae23d808d2b18c3140 Import release 0.0.5
                     UO_indent_paren_nl 1a600153e23c2f8474ce351950e14051a5bae9c5 add option to indent open paren follows by newline. default to one tabstop
                     UO_align_keep_tabs fe53aeaa17f05f5d593d298980e27b406dea3ab2 tab aligning improvements
                 UO_sp_func_class_paren 4c31b675655818afa52aaf47571837fc489f5c90 a bunch of fixes for C++
               UO_align_enum_equ_thresh 9bb746bc87b1e337f1c39db16abdb1fcea9ee149 implement the align stack class
                       UO_sp_macro_func 00fb218e7734b9a41a83231c14a64ea6e5e7a96f add a bunch of stuff
                            UO_sp_macro 00fb218e7734b9a41a83231c14a64ea6e5e7a96f add a bunch of stuff
                    UO_sp_square_fparen b45a4713859adf5fdb700449e13dc8525991242c more pawn stuff
                    UO_indent_square_nl 3bbe63edbfcba7ed5d5e95cd7717aa5f93099900 add indent_square_nl
                 UO_indent_brace_parent a8c34815f25954fc359e999fc2cfef77064ead15 add klaus style support
                         UO_nl_after_do 6eda43fb9a3ea2e08ea72a1da48d0250313c7877 add enhancements from Clark Bassett
              UO_cmt_sp_after_star_cont 16f282e989345dcfb5918e5f18ef09c647bb010a add cmt_sp_before_star_cont and cmt_sp_after_star_cont
                    UO_sp_brace_finally 72da37b49317afe80d317ca84f8c190b6142d40d add sp_catch_brace, sp_brace_catch, sp_finally_brace, sp_brace_finally,
                    UO_sp_finally_brace 72da37b49317afe80d317ca84f8c190b6142d40d add sp_catch_brace, sp_brace_catch, sp_finally_brace, sp_brace_finally,
                      UO_sp_brace_catch 72da37b49317afe80d317ca84f8c190b6142d40d add sp_catch_brace, sp_brace_catch, sp_finally_brace, sp_brace_finally,
                      UO_sp_catch_brace 72da37b49317afe80d317ca84f8c190b6142d40d add sp_catch_brace, sp_brace_catch, sp_finally_brace, sp_brace_finally,
                        UO_sp_try_brace 72da37b49317afe80d317ca84f8c190b6142d40d add sp_catch_brace, sp_brace_catch, sp_finally_brace, sp_brace_finally,
                    UO_nl_brace_finally 18a016e88223ed42054921a7213f540bd0e554e1 add nl_brace_catch, nl_brace_finally
                     UO_sp_getset_brace 7aecb40fe9161d1b1c7b311912e76cd88c5f115e Add sp_getset_brace and nl_getset_brace
                 UO_string_escape_char2 dc445e0510e55c18ae639587090a76e9250585bb add string_escape_char2
                   UO_indent_case_shift 79391932121e4553a094d4094d10f82e2f47e6b0 add indent_case_shift as an experimental feature
                  UO_nl_multi_line_cond 9daef580a6013daee01e1ccbc3089b7d563d23d8 add nl_multi_line_cond
                       UO_sp_after_semi 8e78cc40db61ad36148411c301d0a52581438484 add sp_after_semi_for_empty
              UO_nl_after_square_assign 46bc5762b4836cdc8ca6f927c5c3ca2dd27d1d7a a bunch of D language improvements
                      UO_cmt_c_nl_start f0a819580d5e5a59483933a6f41d367f1458b9e6 Add cmt_width, cmt_c_group, cmt_c_nl_start, cmt_c_nl_end
                            UO_sp_deref cfab90859a09827cd30a0ad2424b709b06e316b7 Add sp_inv, sp_not, sp_addr, sp_deref (default to remove)
                              UO_sp_inv cfab90859a09827cd30a0ad2424b709b06e316b7 Add sp_inv, sp_not, sp_addr, sp_deref (default to remove)
                              UO_sp_not cfab90859a09827cd30a0ad2424b709b06e316b7 Add sp_inv, sp_not, sp_addr, sp_deref (default to remove)
                 UO_indent_preserve_sql 1a2d1834efc7027900863f59c2cd3fb60c4b992c Add indent_preserve_sql
              UO_nl_if_leave_one_liners a067282543bb4ffabaaad5108a6fab86696802f2 add nl_func_leave_one_liners and nl_if_leave_one_liners
                           UO_sp_incdec f2ddb69cb8eaad5c9cf1a431d2c9d61d23154238 Add sp_sign and sp_incdec
                             UO_sp_sign f2ddb69cb8eaad5c9cf1a431d2c9d61d23154238 Add sp_sign and sp_incdec
                           UO_sp_member f188e088aac073e919388de17d4e8b1a5a389701 Add sp_member for spacing around '->' and '.'
               UO_sp_before_class_colon f10a34bd353c30a18e86219ce34c7952f6a63eda Add sp_after_class_colon, sp_before_class_colon, and sp_after_type
                UO_sp_after_class_colon f10a34bd353c30a18e86219ce34c7952f6a63eda Add sp_after_class_colon, sp_before_class_colon, and sp_after_type
UO_indent_relative_single_line_comments 193bf3b47aa3c5d035bb2cd3995d1f52265ef9bb Add indent_relative_single_line_comments
             UO_align_single_line_brace d4c756839aa860a047e7322dec443e04e75e1fe0 Add align_single_line_brace and align_single_line_func
         UO_align_single_line_brace_gap 0698c26ac5f6e7b37f2e1389dbd119f46fbe4b8b Add align_var_def_gap, align_var_def_colon_gap, align_var_struct_gap,
             UO_align_var_def_colon_gap 0698c26ac5f6e7b37f2e1389dbd119f46fbe4b8b Add align_var_def_gap, align_var_def_colon_gap, align_var_struct_gap,
                UO_align_var_struct_gap 0698c26ac5f6e7b37f2e1389dbd119f46fbe4b8b Add align_var_def_gap, align_var_def_colon_gap, align_var_struct_gap,
                     UO_nl_before_throw 545e418e5ed0ec459c48e0700e62042665e1133a Add nl_before_throw and indent 'throw' if after a prototype
             UO_sp_before_unnamed_byref 1a27e094ee8e57178ad63879d917501972230b55 Add sp_before_unnamed_byref and sp_before_unnamed_ptr_star
               UO_indent_template_param 0cc7f99885c4502305998d38f4dac2792f9405c8 Treat the template '<' the same as '(' for indenting Add indent_template_param
                 UO_align_right_cmt_gap 95bb182e0bce8f9481d35ffe6acc6f5796cb0724 Add align_right_cmt_gap
             UO_sp_func_call_user_paren 2fe3814353adfaed60684fd4a29c3b6760ce7689 Add the 'set' config option which lets you create arbitrary keywords Add
             UO_sp_before_ptr_star_func 2afefac0ecdec867ccfee67ccc544bf391624595 add sp_before_ptr_star_func, sp_after_byref_func, sp_before_byref_func
                UO_sp_before_byref_func 2afefac0ecdec867ccfee67ccc544bf391624595 add sp_before_ptr_star_func, sp_after_byref_func, sp_before_byref_func
                 UO_sp_after_byref_func 2afefac0ecdec867ccfee67ccc544bf391624595 add sp_before_ptr_star_func, sp_after_byref_func, sp_before_byref_func
                 UO_nl_comment_func_def ef1ea3632594378c44b8c2b7c6ea6e781d5d74f9 Add nl_comment_func_def
                 UO_indent_align_assign fa6ee8f0d4fd3e93221691638e536bffe7f540d8 Add indent_align_assign
                UO_sp_before_case_colon 8b86c01d4da46a3604f474826710c9fadab472f2 Add sp_before_case_colon
            UO_sp_after_invariant_paren eda4708c7974daab1bf71cd615bb205442d6373e Fix D 'invariant' handling Add sp_invariant_after_paren and sp_invariant_paren
                  UO_sp_invariant_paren eda4708c7974daab1bf71cd615bb205442d6373e Fix D 'invariant' handling Add sp_invariant_after_paren and sp_invariant_paren
               UO_sp_enum_before_assign b622af4b8eb4156f3fada9deb58e50b6fc0ceb42 Add sp_before_assign, sp_after_assign, sp_before_enum_assign, and
                UO_sp_enum_after_assign b622af4b8eb4156f3fada9deb58e50b6fc0ceb42 Add sp_before_assign, sp_after_assign, sp_before_enum_assign, and
                    UO_sp_before_assign b622af4b8eb4156f3fada9deb58e50b6fc0ceb42 Add sp_before_assign, sp_after_assign, sp_before_enum_assign, and
                     UO_sp_after_assign b622af4b8eb4156f3fada9deb58e50b6fc0ceb42 Add sp_before_assign, sp_after_assign, sp_before_enum_assign, and
                     UO_cmt_reflow_mode ff15cba16bffe30e06a5571247348597b0c5373e Add cmt_reflow_mode (Ger Hobbelt)
              UO_indent_namespace_level d76c937f535b2d77f3e7a4ac10324e36edbfca6a Add indent_namespace_level (James LewisMoss)
                        UO_sp_endif_cmt ff4780d68465eb8b480a096c89310f85c5664f73 Add new option sp_endif_cmt
          UO_nl_after_vbrace_open_empty 18dba54313c8aea3e59593fdab2a7beeb01fe5e2 Add new option: nl_after_vbrace_open_empty
           UO_nl_func_decl_start_single 2daa03ce4df9479178d4c84c5965af895eb4d41d Add nl_func_decl_start_single and nl_func_decl_end_single
             UO_nl_func_decl_end_single 2daa03ce4df9479178d4c84c5965af895eb4d41d Add nl_func_decl_start_single and nl_func_decl_end_single
                UO_indent_cmt_with_tabs 51c1f51f86cc4f79f8b0f050122035ec5599ddfd Add indent_cmt_with_tabs and rework the comment output code.
               UO_nl_after_vbrace_close 541ca14b9226aad5184ebffba9ee463857ce0afc New option: nl_after_vbrace_close
                 UO_align_oc_decl_colon 6a360a75b81c6e5e821d4711b0e2e8d375e7afa7 Add option: align_oc_decl_colon
          UO_sp_inside_oc_at_sel_parens 42b1ed31999d4926188acf881912b49958282dac Add sp_inside_oc_at_sel_parens and sp_after_oc_at_sel_parens. Make some
           UO_sp_after_oc_at_sel_parens 42b1ed31999d4926188acf881912b49958282dac Add sp_inside_oc_at_sel_parens and sp_after_oc_at_sel_parens. Make some
                      UO_nl_using_brace e2fd5395a37392dd0ec26a0acc402aee2fe28794 Detect the C# using statement - using (xx) { } Add mod_full_brace_using and
                      UO_sp_paren_comma 495501c3a2e6e6450b4654b7524e4b87aee99775 Add sp_paren_comma to handle the super-rare missing first argument in a macro.
            UO_nl_func_def_start_single 2d1e4acc633a1ddf65d1f6a19c0c25ca29b8bbe8 Add nl_func_def_paren, nl_func_def_start, nl_func_def_start_single,
              UO_nl_func_def_end_single 2d1e4acc633a1ddf65d1f6a19c0c25ca29b8bbe8 Add nl_func_def_paren, nl_func_def_start, nl_func_def_start_single,
            UO_nl_after_func_body_class ef8350ecdbcf65988f708f8d072513deb85bfd5a Add option nl_after_func_body_class
                     UO_nl_after_struct 7501cad6f93119ae3862a3b84d3934d6c9bd9df0 Add new options: nl_after_class and nl_after_struct
                          UO_utf8_force a44d84381db4f0882a5fa2a47f49f4ecc73a12fa Rework the Byte Order Mark stuff (more options)
                            UO_utf8_bom a44d84381db4f0882a5fa2a47f49f4ecc73a12fa Rework the Byte Order Mark stuff (more options)
                 UO_nl_case_colon_brace 2b6a3105f5bfeaef74821ffb714799871376ad62 Add option nl_case_colon_brace
            UO_align_pp_define_together db9c795e9d756ed3eff50510311b62436f51ac20 From: Todd Richmond New option: align_pp_define_together Align #define functions
                       UO_ls_code_width 8c2cc60bbe4fedf012331d8641fec5dce27d97df From: Todd Richmond Create new option ls_code_width to better control line width
                UO_nl_typedef_blk_start 2e95b3c8bf4bf9d7ec688c769803ffaf3ca4be29 From: Todd Richmond Add a slew of new options: nl_typedef_blk_start,
                UO_nl_var_def_blk_start 2e95b3c8bf4bf9d7ec688c769803ffaf3ca4be29 From: Todd Richmond Add a slew of new options: nl_typedef_blk_start,
                  UO_nl_typedef_blk_end 2e95b3c8bf4bf9d7ec688c769803ffaf3ca4be29 From: Todd Richmond Add a slew of new options: nl_typedef_blk_start,
                  UO_nl_var_def_blk_end 2e95b3c8bf4bf9d7ec688c769803ffaf3ca4be29 From: Todd Richmond Add a slew of new options: nl_typedef_blk_start,
                   UO_nl_typedef_blk_in 2e95b3c8bf4bf9d7ec688c769803ffaf3ca4be29 From: Todd Richmond Add a slew of new options: nl_typedef_blk_start,
                   UO_nl_var_def_blk_in 2e95b3c8bf4bf9d7ec688c769803ffaf3ca4be29 From: Todd Richmond Add a slew of new options: nl_typedef_blk_start,
                   UO_nl_unittest_brace 91701a4e5ec5de9cb4f71847da44e7f1ed3d8c26 Add option: nl_unittest_brace
                      UO_nl_scope_brace 72c9645f0b57017063ed83f5db7e3d845eab56a7 Add option: nl_scope_brace Affects D
                    UO_nl_version_brace 2a220107fd1e0e9139c5bbe312b14b3b12e2cee7 Add option: nl_version_brace Affects D
               UO_sp_permit_cpp11_shift 9fa0183f6a2f08e4b5c0a5f433481277fce0cb52 Add sp_permit_cpp11_shift From: Oleg Smolsky
             UO_sp_before_oc_dict_colon f91bb5a01c76caef5ba035f73c20b5ff3424161a Add options: sp_before_oc_dict_colon and sp_after_oc_dict_colon
              UO_sp_after_oc_dict_colon f91bb5a01c76caef5ba035f73c20b5ff3424161a Add options: sp_before_oc_dict_colon and sp_after_oc_dict_colon
                 UO_nl_brace_struct_var b875c33fe318810b0a69317c0800e46b25f32685 Add new option: nl_brace_struct_var
               UO_sp_inside_sparen_open 5f403057e4bc4cfe0adf5e10a9702d1c68af257d Add option sp_inside_sparen_open to mirror sp_inside_sparen_close
                 UO_sp_annotation_paren b332a27a8f5fcd253bc736df4ed1d06b5882049a Add basic support for Java annotations. New options: sp_annotation_paren
              UO_sp_before_pp_stringify 3bb91cc5cdf5c914e59b630b0d1153c2aef8cc34 Add option sp_before_pp_stringify and default sp_pp_stringify to ignore.
                UO_sp_after_oc_property 126a8b4474e9c260775a571804725316073a5db0 Add option sp_after_oc_property
                  UO_sp_after_for_colon 3c3db622f1eb8bd5496d542ea2d80c88c0cd59a9 Add options: sp_before_for_colon and sp_after_for_colon
                     UO_sp_extern_paren 3e92b23534e7e96e57f360fc24082eff6b06025d Add option sp_extern_paren to control space in 'extern (C)' (D)
            UO_align_oc_msg_colon_first e6248d0b55c066e76bc18c64245ebb0d6975f9da Add option: align_oc_msg_colon_first
                 UO_indent_oc_msg_colon fa87f91938e520251d1380e0ebd2d69f7d11e1d7 New option: indent_oc_msg_colon
                 UO_indent_oc_block_msg 67d055ccfbcf7c3e9b2078b791e991c813eb847e Add option: indent_oc_block_msg
              UO_sp_before_constr_colon cdadf3b0127a3c7ce37efa9525bcbbf45f0789e3 Add options sp_after_constr_colon and sp_before_constr_colon
               UO_sp_after_constr_colon cdadf3b0127a3c7ce37efa9525bcbbf45f0789e3 Add options sp_after_constr_colon and sp_before_constr_colon
                     UO_nl_brace_square 7c85198f51d813884447bd2c8f2f9823aabc5252 Allow removal or addition of newlines after blocks.
UO_indent_oc_msg_prioritize_first_colon b4c8b3610166b580f557e0f90f9c091b63830e25 * Fix a segfault parsing Objective-C blocks 0CMakeLists.txt appveyor.yml AUTHORS
             UO_indent_paren_open_brace 1a16cfc6e2d6d40d2b4862ac391e9ebe7c73d409 Indent by brace in '({\n', add option indent_paren_open_brace to revert
              UO_indent_min_vbrace_open 343cfd27900724643762613fec811fd1c2d1b785 Introduced new options indent_min_vbrace_open and indent_vbrace_open_on_tabstop.
           UO_nl_while_leave_one_liners eef47c5b357912fe1c0136e338a895f580dc256e add nl_while_leave_one_liners
                     UO_sp_cmt_cpp_qttr 15ee014c5261a26d46d3479f0f7330db719f183a Doxygen comments in CPP style like '//:', '//=', '//~' where not handled
          UO_use_indent_func_call_param 9f702d6844f1e2793294f6851aa6c19998e9bb85 Introduce use_indent_continue_only_once New macros: for_each Q_FOREVER Change
     UO_nl_after_func_class_proto_group c160070067af35a4da47a7a8f997295c8438c3f2 The issue #411 is partialy fixed.
UO_use_options_overriding_for_qt_macros 8c345570b444ab662d4e4a7b2495357903850f32 Added option to be able to disable Qt macros special formatting option
            UO_indent_token_after_brace 5c18adbc8458899011dac7d4aee8398c07d61b02 Make the "indent to token following a brace" optional
              UO_align_var_class_thresh 192ba81ce677a821827a0e80ab6fd05d0b3e6f4b Introducing align_var_class_span and friends
                 UO_align_var_class_gap 192ba81ce677a821827a0e80ab6fd05d0b3e6f4b Introducing align_var_class_span and friends
  UO_mod_sort_oc_property_setter_weight 4c56a7269ede96333cc8cac1c2e4d35b6fe195a2 Cherry pick of "Adds support for sorting @property in obj-c" (c68a89b) from
                  UO_include_category_1 006b86a5f0dd4e2ffefa32fbc4a1845f13adb81e sort includes with prioritiezed category
                  UO_include_category_2 006b86a5f0dd4e2ffefa32fbc4a1845f13adb81e sort includes with prioritiezed category
   UO_mod_sort_oc_property_class_weight 48915336906c77d3e76e3bb71ee946c1c5e27c49 Added missing properties Fixed work of mod_sort_oc_properties with
                  UO_pp_indent_func_def 3ab54b019508986d4fbbf2cd72da02e2eae7cdd5 Add options for preprocessor block indentations
                    UO_indent_switch_pp 3ab54b019508986d4fbbf2cd72da02e2eae7cdd5 Add options for preprocessor block indentations
                    UO_pp_indent_extern 3ab54b019508986d4fbbf2cd72da02e2eae7cdd5 Add options for preprocessor block indentations
                     UO_pp_indent_brace 3ab54b019508986d4fbbf2cd72da02e2eae7cdd5 Add options for preprocessor block indentations
                      UO_pp_indent_case 3ab54b019508986d4fbbf2cd72da02e2eae7cdd5 Add options for preprocessor block indentations
                      UO_sp_angle_colon 185b46876c0916633b950c37f3b06b3e94312450 Introduce a new option: sp_angle_colon

</pre>
</details>

**Comment by mihaipopescu** [comment]
Nice. That could be used as a script for coverage reporting to github so we can track that. We can add a badge on the README and more, we can use Coveralls.io (or other similar services) can help with more coverage information.

**Comment by CDanU** [comment]
Yes, I also was thinking about something like this.
So far I have a script that aligns the *.test files, one that checks if single option configuration files are named according to a specific pattern and with some additional tweaks the option_reducer script can be used to check if new config files are reduced, while ignoring changes in comments, namespaces, etc.

@mihaipopescu I have seen that you have a diff checker bot for the Unity fork. 
I would like to have a bot account or something like that too, in order to automatically (or triggered via a custom comment) push commits into an open PR to fix stuff like test/source file formatting, the CLI outputs, etc. I have seen similar GitHub bots on other projects too but I don't know anything about them. Are you using some kind of service for that or do you have your own server running code somewhere?

**Comment by mihaipopescu** [comment]
Yeah we have a bot account which uses just github API. I guess it uses a webhook to listen to comments made on PRs but @rassi please correct me if I'm wrong and complete the picture.

What is the flow you are thinking?

**Comment by CDanU** [comment]
When creating PRs github auto sets the option to allow the maintainer to edit the PR branch. 
I guess the workflow would be like this:
- make a PR
- let the CI find errors (using the python scripts I mentioned above)
- post a message for the bot here
- the bot kicks in and fixes what it can fix (also via the scripts), makes a commit and pushes it on top of the PR branch
- a new CI round starts

This way some of the boring work can be alleviated (formatting, CLI outputs, etc.), while PR submitter and maintainer still have the control over the changes before anything is merged.

By webhook you mean the GitHub webhook functionality right? As far as I know that is somewhat like a ping to a server that starts doing its _thing_ when it receives one. 
The server part would be a problem, we would need to have a free vps or something similar.
