### ISSUE TITLE
Changelogs do not highlight #1393, changing option 'align_number_left' to 'align_number_right'

### ISSUE THREAD

**Issue by richardhendricks** [uncrustify/uncrustify#1476]
Our current config file is returning an error due to undocumented change #1393 

New 0.66.1
rihendri@NB0010640 ~
$ uncrustify -c uncrustify.cfg -l C --no-backup *.c *.h
uncrustify.cfg:40 Unknown symbol 'align_number_left'
Parsing: init.c as language C

Old 0.65
rihendri@NB0010640 ~
$ uncrustify-0.65 -c uncrustify.cfg -l C --no-backup *.c *.h
Parsing: init.c as language C

Please add info to changelogs, thanks.

**Comment by guy-maurel** [comment]
Thanks. I changed it.

**Comment by richardhendricks** [comment]
Thanks.

**Comment by bertwesarg** [comment]
No backwards handling in place, seriously?

**Comment by bertwesarg** [comment]
No backwards handling in place, seriously?
