### ISSUE TITLE
failing objective-c.test 50410

### ISSUE THREAD

**Issue by CDanU** [uncrustify/uncrustify#1481]
After the introduction of 0fc6091 objective-c.test 50410 is failing. I think that the commit is just displaying a bug that was more or less _dormant_ up until now.

The test [output](https://github.com/uncrustify/uncrustify/blob/b5275083a9f8bcc29b6a245b07506659fa4e1536/tests/output/oc/50410-oc_cond_colon.m#L8-L9) ([connfig](https://github.com/uncrustify/uncrustify/blob/b5275083a9f8bcc29b6a245b07506659fa4e1536/tests/config/oc_cond_colon.cfg)) itself, expects that before the colon two tabs and 4 spaces are printed.
Should there be an indentation in the first place? I actually don't think so as there is nothing that would enforce one (like for example an opening brace).

I would say however that there is a continuation indent:
```
# The continuation indent. If non-zero, this overrides the indent of '(' and '=' continuation indents.
# For FreeBSD, this is set to 4. Negative value is absolute and not increased for each '(' level.
indent_continue                 = 0        # number
```
I am not exactly sure if this matters here.

If not, there is no indent and according to:
```sql
# How to use tabs when indenting code
# 0=spaces only
# 1=indent with tabs to brace level, align with spaces (default)
# 2=indent and align with tabs, using spaces when not on a tabstop
indent_with_tabs                = 1       # unsigned number
```
the current result (without tabs) is correct.

If there should be an indent see:
<details>

In that case problem is here:    [indent.cpp:2252](https://github.com/uncrustify/uncrustify/blob/a128cc0edfbd9844800702f69065a3a56a2c4b26/src/indent.cpp#L2252)

When the `CT_COND_COLON` (form the above mentioned [test](https://github.com/uncrustify/uncrustify/blob/b5275083a9f8bcc29b6a245b07506659fa4e1536/tests/input/oc/oc_cond_colon.m#L8-L9)) hits that line value 1 is assigned to  `pc->column_indent`. It should be something higher so that the output function in [output.cpp:617-627](https://github.com/uncrustify/uncrustify/blob/a128cc0edfbd9844800702f69065a3a56a2c4b26/src/output.cpp#L617-L627) executes the `output_to_column` function that adds the tabs.
</details>

-------

I would also like to use this issue to discuss the option `indent_ternary_operator`:
```sql
# indent the continuation of ternary operator.
# 0: (Default) off
# 1: When the `if_false` is a continuation, indent it under `if_false`
# 2: When the `:` is a continuation, indent it under `?`
indent_ternary_operator         = 0        # unsigned number
```
If I understand the terminology correctly this option is about alignments instead of indentations, right?

Other than replacing indent with align I'd also change the descriptions to
```sql
# 1: When the negative branch has a continuation, align it below ':' 
# 2: When the whole negative branch is a continuation, align it below `?`
```

Do we currently have something that is handling the case where the positive branch is a continuation?

**Comment by mihaipopescu** [comment]
> If I understand the terminology correctly this option is about alignments instead of indentations, right?

My understanding is the same. 👍 for this change.
