### ISSUE TITLE
mod_full_brace_for can cause bugs

### ISSUE THREAD

**Issue by audetto** [uncrustify/uncrustify#149]
This option can change the behaviour of the underlying code.

In the following file, uncrustfy does not understand that SWAP(a, b) is a "statement" and joins it with return till the next semicolon (by putting braces).

The issue is that the SWAP macro does not behave as a normal statement (it does not require a ; at the end).

Not sure what you can do about it, but maybe a word in the doc, saying that it is a dangerous option (i.e. mod_full_brace_for).

Andrea

#define SWAP(a, b) { int c; }

void foo()
{
  int a, b;
  int i;
  for (i = 0; i < 10; ++i)
    SWAP(a, b)
  return;
}

**Comment by gmaurel** [comment]
This is correct. 
uncrustify doesn't know what a macro is.
The actual git version
  https://github.com/uncrustify/uncrustify
Please test it!
