### ISSUE TITLE
Number of lines between prototypes

### ISSUE THREAD

**Issue by BigfootN** [uncrustify/uncrustify#1494]
Hello,

I would like to know, if by any chance, it would be possible to force the number of lines between prototypes. Let me explain with this input:

```C
void foo();

void bar();
```
There is only one line. I would like the output to be as the following:

```C
void foo();
void bar();
```
Here is my [configuration](https://gist.github.com/BigfootN/fad067766718302ab929e602be43fa52).

Thank you very much in advance

**Comment by CDanU** [comment]
No that would require a new option.

For some reason:

```sql
# The number of newlines before a multi-line function prototype body.
nl_before_func_body_proto       = 1        # unsigned number
```

does remove the newline in your example.

**Comment by BigfootN** [comment]
Thank you for answer.

It now seems to work.
