### ISSUE TITLE
why the compiler warning?

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1498]
Please, have a look to the build:
`https://travis-ci.org/uncrustify/uncrustify/jobs/316536579`
about line 613.
We get a warning about the variable `next` which is not used at the function ‘void indent_text()’
Can anybody explain this?

**Comment by jibsen** [comment]
I am guessing because `chunk_is_newline()` is declared inline, the compiler fails to print the place it is called from. It looks like there are a few places In intent.cpp where `chunk_is_newline(next)` is used without checking if next is nullptr (1867, 2107)

**Comment by jibsen** [comment]
Oh it says uninitialized .. could be somewhere else then I guess .. but the warning does list indent.cpp.

**Comment by CDanU** [comment]
This error only occurs on the builds 1707.2 and 1709.2, both are from PR #1497. I haven't seen anything suspicious in the change set though.

**Comment by jibsen** [comment]
Perhaps it would be a good idea to initialize next to nullptr at the top of indent_text()?

**Comment by CDanU** [comment]
That is most likely the problem.
I tested on of my branches with some refactorings (#1499) in there I limited the scope of next and always had a value assigned.

**Comment by guy-maurel** [comment]
I prefer to suppress ALL the warning messages. They show us, we have a/some problem(s) that should be solve.
Don't hesitate any more.
