### ISSUE TITLE
obj C block parameters "C Style" when lines are split

### ISSUE THREAD

**Issue by ghost** [uncrustify/uncrustify#150]
When my line limit is reached, block params are reformatted to align under the first paren

![image](https://f.cloud.github.com/assets/1238595/241053/b157d042-897b-11e2-9767-92bdc15292f8.png)

Can there be or is there an option to wrap this to the next line either at the beginning of the block or the beginning of the parameter without forcing my params into that style?

**Comment by gmaurel** [comment]
Please push your example as a file, not as a picture.

**Comment by gmaurel** [comment]
NoResponse
