### ISSUE TITLE
align_assign_span broken by fix for #1112 when 3 levels of namespaces are used

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#1509]
Alignment on assignment operator (=) does not work when the function call on the RHS has three levels of namespaces. It does work when there are two levels.

I can get it to work if I modify combine.cpp as follows:
```
--- a/src/combine.cpp
+++ b/src/combine.cpp
@@ -4224,7 +4224,7 @@ static void mark_function(chunk_t *pc)
             LOG_FMT(LFCN, " <skip '%s'>", prev->text());
             D_LOG_FMT(LFCN, "\n");
             // Issue #1112
-            prev = chunk_get_prev_ncnlnpnd(prev);
+            prev = chunk_get_prev_ncnlnp(prev);
             if (prev == nullptr)
             {
                LOG_FMT(LFCN, "nullptr\n");
```
however, that is likely to break the fix for issue #1112

[debug.txt] https://pastebin.com/d7i4LSC5

test.cpp
```
namespace A {
   namespace B {
         int foo();
      namespace C {
         int bar();
      }
   }
}

void f()
{
   int i = A::B::C::bar();
   int ii = A::B::C::bar();

   int j = A::B::foo();
   int jj = A::B::foo();
}
```
Generated results
```
namespace A {
namespace B {
int foo();
namespace C {
int bar();
}
}
}

void f()
{
	int i = A::B::C::bar();
	int ii = A::B::C::bar();

	int j  = A::B::foo();
	int jj = A::B::foo();
}
```
Expected result
```
namespace A {
namespace B {
int foo();
namespace C {
int bar();
}
}
}

void f()
{
	int i  = A::B::C::bar();
	int ii = A::B::C::bar();

	int j  = A::B::foo();
	int jj = A::B::foo();
}

```

./uncrustify -v
Uncrustify-0.66.1-110-f8d8864

The following version is the last one that works:
Uncrustify-0.65-236-0307255

The following version is the first one with the problem:
Uncrustify-0.65-244-4dd498a

**Comment by gmaurel** [comment]
Could you make some "Pull Request" (PR) for your proposals?
It would be fine

**Comment by arneforlie** [comment]
But, I'm quite sure that my proposal breaks whatever #1112 was supposed to fix.
I had hoped that someone more familiar with the code would be able to fix both.

**Comment by CDanU** [comment]
I am going to look into this one.

**Comment by CDanU** [comment]
can be closed
