### ISSUE TITLE
align_var_def_span broken by fix for #1112 when 3 levels of namespaces are used

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#1510]
The following issue is similar to #1509 and seems to have the same cause, but another config. parameter is involved:
align_var_def_span  = 1

If only two levels of namespaces are used, the formatting is correct.

I can get rid of the issue by the same fix as suggested in #1509 (but it probably breaks the fix for #1112)
```
--- a/src/combine.cpp
+++ b/src/combine.cpp
@@ -4224,7 +4224,7 @@ static void mark_function(chunk_t *pc)
             LOG_FMT(LFCN, " <skip '%s'>", prev->text());
             D_LOG_FMT(LFCN, "\n");
             // Issue #1112
-            prev = chunk_get_prev_ncnlnpnd(prev);
+            prev = chunk_get_prev_ncnlnp(prev);
             if (prev == nullptr)
             {
                LOG_FMT(LFCN, "nullptr\n");
```

[debug.txt] https://pastebin.com/mnUrVJKZ

test.cpp
```
#include <iostream>

namespace A {
   namespace B {
      namespace C {
         int bar();
      }
   }
}

void g()
{
   std::cout << A::B::C::bar();
   int i(A::B::C::bar());
}
```
Generated results:
```
#include <iostream>

namespace A {
namespace B {
namespace C {
int bar();
}
}
}

void g()
{
	std::cout << A::B::C::bar();
	int          i(A::B::C::bar());
}
```
Expected results:
```
#include <iostream>

namespace A {
namespace B {
namespace C {
int bar();
}
}
}

void g()
{
	std::cout << A::B::C::bar();
	int i(A::B::C::bar());
}
```

./uncrustify -v
Uncrustify-0.66.1-110-f8d8864

The following version is the last one that works:
Uncrustify-0.65-236-0307255

The following version is the first one with the problem:
Uncrustify-0.65-244-4dd498a

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by arneforlie** [comment]
Thanks, this seems to fix the issue.
