### ISSUE TITLE
Ignore 'nl_func_type_name' for single-line functions

### ISSUE THREAD

**Issue by Leandros** [uncrustify/uncrustify#1511]
By setting `nl_func_type_name` to `force`, the following would be uncrustified:

```
int getFoo() { return foo; }
```

into 

```
int
getFoo() { return foo; }
```

Could an override be added, to let single-line functions be excluded from `nl_func_type_name` if they fit into the current max column?

**Comment by CDanU** [comment]
The option
```sql
# Don't split one-line function definitions - 'int foo() { return 0; }'.
nl_func_leave_one_liners        = true     # false/true
```
__*should*__ do what you want, but it seems that it does not work.

**Comment by Leandros** [comment]
I have that set. It works to the extent that it doesn't split the braces and return statement according to my settings, but seems to ignore the return type.

**Comment by CDanU** [comment]
No it is not solved - I tried but if I remember correctly it is a pita in certain cases to find the border between where something ends and where a return type starts.

**Comment by gmaurel** [comment]
The option nl_func_leave_one_liners works only on the part:
`{ return foo; }`
of your code.
More is feature request.

**Comment by gmaurel** [comment]
PR #2549  is a bugfix proposal.
Please test it and report.
