### ISSUE TITLE
C++ new line variable block

### ISSUE THREAD

**Issue by BigfootN** [uncrustify/uncrustify#1516]
Hello,

I noticed that, in C++, when I wrote a function with those variables (in the body):
```c++
void myClass::foo() {
    int bar;
    std::string str;
}
```

The output was the following:
```c++
void myClass::foo() {
    int bar;

    std::string str;
}
```

It adds one line after before the `std::string`. But if I first declare the `std::string` then no new line is added.

If it is a group of int, or char or C types, there is absolutely no problem. There only seems to be a problem with C++ and C types.

Here is my [configuration](https://gist.github.com/BigfootN/fad067766718302ab929e602be43fa52).

Thank you very much in advance for any help.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by BigfootN** [comment]
Thank you very much. It now works :+1:
