### ISSUE TITLE
Space added after '$ character

### ISSUE THREAD

**Issue by billwaters** [uncrustify/uncrustify#1518]
The Keil compiler uses the '$' character in its function patching scheme.  It looks like this.

```
void test(void)
{
    $Super$$func();
}
```

This is in a file named test.c.  When I run uncrustify with an empty config file, I get this output.  There is a space added after the first '$' character and before the first '(' after that.  Is there a way to disable this behavior?  The Keil compiler doesn't like the space after the '$', and I would prefer to get rid of both of the spaces.

```
void test(void)
{
	$ Super$$func ();
}
```

**Comment by guy-maurel** [comment]
Are those the only places where a **$** is present?

**Comment by billwaters** [comment]
Yes, this is the only text in the file.

```
void test(void)
{
    $Super$$func();
}
```

**Comment by guy-maurel** [comment]
The question is not "in the file" but
"in all the files one is able to compile with this compiler"
or
"where does the compiler work with the dollar-sign"?

**Comment by billwaters** [comment]
Ah.  This is the only time that the compiler uses the '$' character.  The compiler can use the "$Sub$$" or "$Super$$" prefix in front of a function name.

**Comment by billwaters** [comment]
I think that this is worth addressing for the other Keil users out there (and this may likely apply to other ARM compilers).  But, if you had a suggestion as to where to hack the uncrustify source code to get around this, that would be great.  I looked at the source, but couldn't figure out where to make the hack.  And it may be a more complicated, layered thing.  I think I was seeing that the first '$' was getting tokenized and then the formatting follows from that.

I think that there needs to be an option for C compilers where '$' is treated as another character in the alphabet.  Or, just treat is like an underscore character.

**Comment by CDanU** [comment]
The '$' sign in a function name is not in the C or C++ standard. 
I hate supporting things like that and also don't really care about Keil, but unfortunately MSVC and even GCC allow '$' signs in the beginning on a function name. So this should be taken care of.

So far I haven't looked into the code for this issue, the problem seems to be that the first $ sign is tokenized as `CT_SQL_EXEC`. For a fast & dirty fix I would imagine that removing the according entry from the tokens list could maybe fix it.

**Comment by billwaters** [comment]
Thanks.  I found this area in the code when I was initially poking around.  So, I was close, but I wasn't sure what to hack.  It's still not clear.  It seems that the '$' has already become  a token when you get to this part of the code.  And that seems too late to make a hack??

**Comment by CDanU** [comment]
As the name of the file suggests this happens during the tokenizing process. The function I wrote above changes the type of the current chunk `pc`  to to CT_SQL_EXEC. If you remove that line or rather the whole block it is in  (`if` block that handles the sql stuff) it does not get the special SQL treatment and __*should*__ behave like a normal function name.

**Comment by billwaters** [comment]
That fixed it.  Thanks!

**Comment by CDanU** [comment]
Keep this open until there is a proper fix.

**Comment by billwaters** [comment]
Yeah, I would like to get the official fix.

I ran my hacked version on my entire code base, and it looks good.

There is one really big file that crashed when I ran my version of uncrustify with it.  I am not worried about this though.  The last official release version of uncrustify does not crash with this file.

```
Parsing: ./ace2_app_config/build/jumptable.c as language C
terminate called after throwing an instance of 'std::out_of_range'
  what():  erase:684 - idx + len >= m_chars.size()
Aborted (core dumped)
```

**Comment by CDanU** [comment]
Hmm I am hover a bit worried, does that also happen with the current master (without the hack)?

**Comment by billwaters** [comment]
It does happen with and without the hack.  I can make it happen with a file with only this in it.

```
void FuncA(void)
{
}

void FuncB(void)
{
}
```

**Comment by CDanU** [comment]
Please move that into a new issue so we can discuss this there, we already have way to much comments here. 
I will delete my own comments that are not directly related to this issue and shorten down the others where necessary. I would like if you could do the same.

**Comment by billwaters** [comment]
@CDanU, is there any chance that you can generate an exe with this hack?  My build was done with Cygwin and I am finding that it is not portable.  Others on my team can not run it on their PC.

**Comment by CDanU** [comment]
As in giving you the exe, checking if the exe builds or checking if the exe does stuff as it should? 
I made a PR on my fork: https://github.com/uncrustify/uncrustify/pull/1537

**Comment by billwaters** [comment]
@CDanU, sorry, I am asking for you to generate an exe and send it to me.  Thanks.

The latest uncrustify build cleans up a formatting bug... the old version that we were using was adding an extra four spaces of indentation in "random" spots.  I ran the new build on our code and checked all of the changes in.  Then I found out that others on my team were getting errors when they try to run the new uncrustify.exe that I created.  And, now, I don't want to go back to the older version and back out the "extra four spaces" updates.

**Comment by CDanU** [comment]
No, unfortunately I can't do that right now. Currently I have no Windows system. 

I don't think that it is the hack that is causing this. The other issue you opened up today will however throw errors if you use the header stuff that is currently broken. I plan on fixing that this night so you can test it tomorrow.

**Comment by CDanU** [comment]
To get both working would need better SQL parsing. I'd had to know how to differentiate between a dollar sign notation SQL statement and anything else that is starting with a dollar. I guess something could be done if the SQL keywords are known but apparently there are at least [825](https://www.drupal.org/docs/develop /coding-standards/list-of-sql-reserved-words) of them. 

An, easier and far less complex, solution would be to just drop the embedded SQL dollar sign notation, expecting that embedded SQL only starts with the EXEC keyword. 

That however would break things. Embedded SQL seems to be used by commercial dino SQL databases (db2, oracle). Is there any one out there who is using those in combination with Uncrustify?

I would choose to do either the second option or mark this as wontfix.
