### ISSUE TITLE
Partial file formatting

### ISSUE THREAD

**Issue by jacky309** [uncrustify/uncrustify#1519]
It would be convenient to have an option to format only portions of a file. This is a feature of clang-format ("-lines" command-line parameter) already. 
The "--check" option should be aware of that "lines" options in such a way that the check will be performed only on the specified portions of the file.
This feature is useful if a project has an existing unformatted code base, and wants to start using uncrustify to format any new piece of code. Applying a huge "formatting only" commit on that project would screw up the information provided by the "git blame" command.

**Comment by jacky309** [comment]
I do not think this issue should have the "C and C++11" label.

**Comment by Jorengarenar** [comment]
Has any work been done on this? Or has anyone come up with some wrapper/workaround?

**Comment by guy-maurel** [comment]
No.
I prefer to work on the whole file.

**Comment by Jorengarenar** [comment]
No problem for me; I'm already working on [an universal Git "integration" for formatters](https://github.com/Jorengarenar/git-fmt-diff)
