### ISSUE TITLE
Uncrustify source distros have odd layout

### ISSUE THREAD

**Issue by madscientist** [uncrustify/uncrustify#1533]
I tried to download the 0.66.1 source tarball and I expected to get a tarball containing one top-level directory named `uncrustify-0.66.1`.

When I downloaded the source tarball from GitHub 
https://github.com/uncrustify/uncrustify/releases the directory in it is `uncrustify-uncrustify-0.66.1` (two "uncrustify" in the directory name).

Even more unusual, when I download the source tarball from Sourceforge https://sourceforge.net/projects/uncrustify/files/uncrustify/ there is no top level directory in it at all; the code is extracted directory into the current directory.

It would be nice for the source tarballs followed standard convention (in particular not having a top-level directory at all, as with Sourceforge, is quite annoying to clean up if you don't happen to notice before you unpack).

Cheers!

**Comment by gmaurel** [comment]
Could you point me to the standard conventions?
Thanks
