### ISSUE TITLE
Add Nl Func Decl Args does not work in v0.60, but works fine in v0.54

### ISSUE THREAD

**Issue by edarn** [uncrustify/uncrustify#154]
Hi!

I am evaluting if we can use uncrustify here at ST-Ericsson, Lund, Sweden for some of our audio software written in C.

As I recently upgraded from 0.54 to 0.60 I noticed that the setting which is named "Add Nl Func Decl Args" in universalIndentGUI does not work any more. It only works for function prototypes, but not where you implement the function.
<pre>
void f(int a, int b);
becomes
void f(int a,
       int b);
</pre>
but
<pre>
void f(int a, int b)
{
return 0;
}
</pre>
does not get changed into
<pre>
void f(int a, 
       int b)
{
return 0;
}
</pre>
any more.

Kind Regards
Thomas Hermansson

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
