### ISSUE TITLE
#ifdef among function parameters fail in v0.6

### ISSUE THREAD

**Issue by edarn** [uncrustify/uncrustify#155]
When having a #ifdef statement among the parameters in a function uncrustify fails.
<pre>
void f(Some_very_long_type b,
         int a
#ifdef XX
         ,int c
#endif
        );
</pre>
is transformed to

<pre>
void f(Some_very_long_type b,
         int a
#ifdef                             XX
         ,int                        c
#endif
        );
</pre>
So the ifdef parameter gets treated as a variable and is aligned with b and c. But a is not aligned.

This is seen in v0.60

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
