### ISSUE TITLE
Tell uncrustify to do only specific things

### ISSUE THREAD

**Issue by rahul-ramadas** [uncrustify/uncrustify#156]
Currently it looks like uncrustify performs all the formatting it know about, using defaults options if something is not explicitly specified. Is there some way I can configure it to perform only specific changes? For instance, I want to perform only changes related to nl_func_type_name.

**Comment by gmaurel** [comment]
Please give us an source example and what you wanted to get.

**Comment by rahul-ramadas** [comment]
This was so long ago I honestly don't even remember what I was doing at the time :smiley:.
