### ISSUE TITLE
Avoid nested statements to be detected as single line

### ISSUE THREAD

**Issue by albfan** [uncrustify/uncrustify#1561]
uncrustify 0.63

Using `indent_braces = force`  and `nl_if_brace = force` this:

    if (1 == 0) {
       printf("hello");
    }

became:

    if (1 == 0) 
      {
        printf("hello");
      }

Is it possible to avoid `mod_full_brace_if = remove` to remove braces on single line bodies that are statements too:

like:

    if (1 == 0) 
      {
        if (0 == 0)
          {
            printf("hello");
            printf("bye");
          }
      }

becoming

    if (1 == 0) 
        if (0 == 0)
          {
            printf("hello");
            printf("bye");
          }

seems helpful to keep those braces, more when more long is nested statement

I can provide a failed test for this in a wip/branch if you find interesting, and maybe an implementation

**Comment by CDanU** [comment]
I assume this here is a bug and a feature request in one issue.

Is the problem the two spaces before the braces? It seems like you used `
indent_brace                    = 2` to generate your output.
You are using a almost two year old version of Uncrustify, the current master with only the two mentioned options generates results I would expect.

I don't get what your feature request is really about. Please post input/generated output/expected output.
If you have code/tests you can of course post/link them.

**Comment by albfan** [comment]
Is. It very clear, yes. I just try to describe a config (first part) and then a feature request: do not remove braces for single nested statements. In still working on test case
