### ISSUE TITLE
Migrate html documentation to wiki

### ISSUE THREAD

**Issue by albfan** [uncrustify/uncrustify#1562]
uncrustify 0.63

http://uncrustify.sourceforge.net/options.html is not linked to any anchor in http://uncrustify.sourceforge.net/index.html and http://uncrustify.sourceforge.net/options_NewLines.html#nl_after_access_spec do not link to documentation.

Given that `--show-config-with-doc` documents every property, is it possible to migrate all info into a wiki? I find it really useful

**Comment by CDanU** [comment]
Thanks for the info about the missing links. 
I am nor entirely sure if we actually still need Sourceforge. GitHub pretty much can do everything Sourceforge does. 

About the `--show-config-with-doc`: As far as I know the wiki is open to everybody(?) I wouldn't however advice to manually add the output in there. It is bound to get out of date that way and will cause more confusion that having it currently only inside the application itself.

**Comment by albfan** [comment]
I think too sourceforge is not the way anymore, but is not bad to fix there too. Is there a GitHub Page for uncrustify?

Yes, wiki is for everyone, but I find people respectful, and little scared to edit there (but don't known for a project with this traction). Maybe https://hotdoc.github.io/installing.html is an option. I think a good example is meson.  It starts with GitHub wiki and finally migrated all to hotdoc

https://readthedocs.org which uses sphinx is a even better option

I can help to migrate if you want to do so

**Comment by gmaurel** [comment]
Sourceforge is historical.
github is pretty fine to hold the code and start some tests.
Sourceforge is used to hold binaries.
Any help to complete the documentation is welcome.

**Comment by CDanU** [comment]
Github can also hold binaries. If we decide to switch we would need to do that gradually and we would need to notify all of the distro package owners. 

------------------

No we don't have an github.io page (or for that matter a fancy logo) yet. 

I don't particularly like that the hotdoc generated documentations seem to rely on JS, I do however like readthedocs. How good is sphinx at supporting C++ nowadays?

We started to discuss this a bit in #875. I am not sure if we need a full blown static page, but as mentioned we need automation. 
We could write some scripts that are triggered by Travis to update the wiki but that seems be be too much work. Maybe readthedocs could reduce that.

**Comment by albfan** [comment]
All sounds D's great. Let's start small.

- Make all the docs reachable from index
- Expose on github wiki
- Script something to generate docs from existing options like `--show-config`

Futures:
- Automate with Travis
- Link to github releases

**Comment by albfan** [comment]
A first quick migration to markdown using pandoc:

https://github.com/albfan/uncrustify/blob/wip/wiki/documentation/htdocs/index.md

    cd documentation/htdocs
    for html in *.html; do pandoc $html -o $(basename $html .html).md; done

I'm sure it can be better automated, but I will rework manually from that (except someone knows any trick or extension to pandoc that automagically fix other things)

**Comment by CDanU** [comment]
I think we are going a bit in the wrong direction so here is a short write up on how I imagine we can start do gradually add documentation.

1.  **decide upon a static website generator system**
    it should support markdown, html, css, syntax coloring and maybe svg

1. **automate option entries**
    - we need to write (preferably a python) script that just grabs the output of `--show-config` and generates a documentation page (based on the provided minimal option documentation string) for every not yet existing option
1. **use some kind of server**  
    - that receives a webping, starts the above mentioned script and updates the page with the newly generated pages (maybe netlify or now.sh, those are free). 
    - I would like to use the github pages for that. The free server exposes everything which is a problem when we want to store a private github ssh key there to make commits. (Or would it store the public key?) 
    - If we want to use the free server to host the site itself instead of github we would need to get a free and non fugly domain name.

    in both cases the content should be on a github repo
1. ???

After we have that in place we can start to add better descriptions, example code, diffs and so on.

**Comment by albfan** [comment]
Any approach from maintainers is ok. So let me reread this and work on it. You lead the way

**Comment by CDanU** [comment]
I played around a bit with netlify, so far I can't figure out how I can git push into a repo even tough it takes itself quiet a bunch of right for my github account and additionally for the repo. 

Hosting in on netlify itself so far works and I can execute python scripts during the build process. This should allow to generate files that are going to be displayed but they can't be added to a repo. They basically have to be regenerated every single time a build is made. 

I am not that satisfied with that solution. Its seems like finding a service that is able to securely push commits is going to be a problem.

**Comment by albfan** [comment]
I'm reading https://www.netlify.com/docs/continuous-deployment/ If you can share some config for it we can refine later.

I will work on python script to parse `--show-config`.

Don't now what is that `now.sh`

**Comment by mihaipopescu** [comment]
We're using mkdocs with material design. Looks quite nice. 
You can read it here http://www.mkdocs.org/user-guide/deploying-your-docs/ and here
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/ how to set it up.

**Comment by albfan** [comment]
Aha. Let me check
