### ISSUE TITLE
C macro parsing issue since 9ad37b97

### ISSUE THREAD

**Issue by smaeul** [uncrustify/uncrustify#1570]
I'm using uncrustify to format a C project, and recently it started spuriously removing one specific space in [this file](https://github.com/crust-firmware/crust/blob/4b15bb875fc36bbc2a7901c583d864d943a0b276/drivers/msgbox/sunxi-msgbox.c):
```
@@ -32,7 +32,7 @@
 #define MSG_STATUS_MASK         BITMASK(0, 3)

 #define XMIT_MSG_DATA_REG(n)    (0x0184 + 0x8 * (n))
-#define RECV_MSG_DATA_REG(n)    (0x0180 + 0x8 * (n))
+#define RECV_MSG_DATA_REG(n)    (0x0180 + 0x8 *(n))

 static inline msg_handler
 get_handler(struct device *dev, uint8_t chan)
```

I bisected this to commit 9ad37b97b251cfa83dfe6720315c39de9899435d.
Bad [debug.txt](https://github.com/uncrustify/uncrustify/files/1650307/debug.txt) (from 9ad37b97b251cfa83dfe6720315c39de9899435d)
Good [debug.txt](https://github.com/uncrustify/uncrustify/files/1650310/debug.txt) (from b76a2c2c83726be8ac4921e38160cad9ff4e13e1)

**Comment by CDanU** [comment]
Affected option:
```sql
# Add or remove space after a pointer star '*', if followed by a func proto/def.
sp_after_ptr_star_func          = remove   # ignore/add/remove/force
```

**Comment by guy-maurel** [comment]
The current combine.cpp has another change as @CDanU shows:
```
      // Changing words to types into tuple return types in CS.
      bool is_return_tuple = false;
      if (pc != nullptr && pc->type == CT_PAREN_CLOSE && (pc->flags & PCF_IN_PREPROC) == 0)
      {
         first           = chunk_skip_to_match_rev(pc);
         is_return_tuple = true;
      }
```
The output code is correct.
May we stay there and close?

**Comment by smaeul** [comment]
Yes, this was fixed a while back by the commit that added that. Thanks!
