### ISSUE TITLE
Spaces removed even with empty config file

### ISSUE THREAD

**Issue by h00l00v00** [uncrustify/uncrustify#1578]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Hello there

I've noticed that there is some whitespace missing even with an empty config file.
And i didn't find any options to medicate the situation in the following to cases:

* Input file
 ```
__weak typeof(self) welf = self;

wishToSave.tags = ([results objectForKey:@"label"]
                        ?[results objectForKey:@"labelAn"]
                        : [results objectForKey:@"labs"]);
 ```

* Generated result
```
__weak typeof(self)welf = self;

wishToSave.tags = ([results objectForKey:@"label"]
                   ?[results objectForKey:@"labelAn"]
                   :[results objectForKey:@"labs"]);
 ```
* Expected result
 ```
__weak typeof(self) welf = self;

wishToSave.tags = ([results objectForKey:@"label"]
                   ?[results objectForKey:@"labelAn"]
                   : [results objectForKey:@"labs"]);
 ```

the space between ```typeof(self)``` and  ```welf```
and between ```:``` and ```[results objectForKey:@"labs"]``` is the ones which are removed.

* current version: Uncrustify-0.66.1_f 719c56d6417a6b5a83361f9b0833874ba8b914b0

* debug file : [debug.txt](https://pastebin.com/g0azY77n)

**Comment by guy-maurel** [comment]
The first line works pretty well.
uncrustify has only 3 options around the `sp_cond_question=` option.
Add or remove space around the '?' in 'b ? t : f'.

**Comment by gmaurel** [comment]
It is a new feature request.

**Comment by guy-maurel** [comment]
```
It is already there! Use the option:
sp_cond_colon = force
```

**Comment by gmaurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
