### ISSUE TITLE
why do we get a warning

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1584]
The current test:
https://ci.appveyor.com/project/gmaurel/uncrustify/build/1337/job/5mmn8dc13e2s1hmi

produces a warning:
`C:\projects\uncrustify\src\indent.cpp(408): warning C4804: '>': unsafe use of type 'bool' in operation`

can anybody solve that?

**Comment by guy-maurel** [comment]
The code is:
```
static size_t calc_indent_continue(const ParseFrame &frm, size_t pse_tos)
{
   const int ic = cpd.settings[UO_indent_continue].n;

   if (ic < 0 && frm.at(pse_tos).indent_cont > 0)
   {
```

**Comment by CDanU** [comment]
This MSVC warning is good. The `indent_cont` member is a bool (the naming for the variable is a bit misleading). This is either an ancient C-ism or `indent_cont` got confused to be an int value.

**Comment by guy-maurel** [comment]
Why don't we get a warning message with other compilers (ie /usr/bin/c++)?

**Comment by CDanU** [comment]
Difference in implementation I guess. MS is claiming that their MSCV compiler is generating more and better error messages.

**Comment by guy-maurel** [comment]
Fine.
https://github.com/uncrustify/uncrustify/pull/1587 is a proposal for a bugfix.

**Comment by gmaurel** [comment]
fixed
