### ISSUE TITLE
indent_paren_close - closing parenthesis is mis-indented if expression is used in assignment

### ISSUE THREAD

**Issue by AmokHuginnsson** [uncrustify/uncrustify#1589]
1TBS (or OTBS) for curly brackets is known:

```
int foo( int arg ) {
  ...
  if ( cond ) {
    ...
  }
  ...
}
```

The same style could be used for parentheses, unfortunately,
currently uncrustify breaks it with indentation of closing parenthesis.

1TPS would look like:
```
  ...
  int x = foo(
    someLongArg,
    even_longer_call()
  );
  ...
  while (
    long_condition_call() > 0
  ) {
    code...
  }
  ...
```

Currently for all possible setting values of indent_paren_close
uncrustify adds indentation for closing parenthesis.

[sample.cpp](https://gist.github.com/AmokHuginnsson/7f21fa542efdb364ff92a2edf3f07cb9/raw/b9ca2e52b7095ac78199f2e381cc6fdb573c780e/uncrustify_indent_paren_close.cpp)
[debug.txt](https://github.com/uncrustify/uncrustify/files/1692063/debug.txt)

Expected behavior for attached sample.cpp is for uncrustify to leave
closing call parenthesis at call indentation level.
```
uncrustify -v
Uncrustify-0.66.1_f
```

UPDATE:
I appears that this problem occurs only if there is an assignment  operator involved,
I have updated the sample provided.

**Comment by CDanU** [comment]
Try: 
```sql
# Controls the indent of a close paren after a newline.
# 0: Indent to body level
# 1: Align under the open paren
# 2: Indent to the brace level
indent_paren_close              = 2        # unsigned number
```

**Comment by CDanU** [comment]
Config: your debug + `indent_paren_close              = 2`

I:
```cpp
int long_function_name( int );
int foo( int, int, int, int );

int main( int argc_, char** ) {
	int firstArgument( 0 );
	int alsoLongName( 1 );
	int veryLongArgument( 2 );
	firstArgument = foo(
		firstArgument,
		alsoLongName,
		long_function_name( 3 ),
		veryLongArgument
);
	return ( 0 );
}
```

O:
```cpp
int long_function_name( int );
int foo( int, int, int, int );

int main( int argc_, char** ) {
	int firstArgument( 0 );
	int alsoLongName( 1 );
	int veryLongArgument( 2 );
	firstArgument = foo(
		firstArgument,
		alsoLongName,
		long_function_name( 3 ),
		veryLongArgument
	);
	return ( 0 );
}

```

on libUncrustify.js: Uncrustify-0.66.1-302- 5e483817

**Comment by AmokHuginnsson** [comment]
Yes. Thank you!
