### ISSUE TITLE
Objective-c blocks does not follow new-line rules

### ISSUE THREAD

**Issue by OlofT** [uncrustify/uncrustify#159]
First off: Thanks so much for all the hard work put into uncrustify.

Blocks does not seem to follow the rules (or I am missing something). Normal code works (of-course) fine:

```
- (void) show: (int) param{
if (true){
return;
}
}
```

Which becomes:

```
- (void) show: (int) param
{
    if (true)
    {
        return;
    }
}
```

Block code does not get its new line:

```
dispatch_async(dispatch_get_global_queue(0, 0), ^(void){
//code
});
```

Becomes:

```
dispatch_async(dispatch_get_global_queue(0, 0), ^(void) {
    //code
});
```

**Comment by guy-maurel** [comment]
Please push your config file and what you expected to get.

**Comment by gmaurel** [comment]
No answer, we close.

**Comment by OlofT** [comment]
Oh, sorry - I completely forgot about this. Too much work and other chores. Will get back to this after vacation.
