### ISSUE TITLE
align_func_params : how should it work?

### ISSUE THREAD

**Issue by TTTMike** [uncrustify/uncrustify#1596]
Hi everybody,

I have a question regarding align_func_params:

If i set align_func_params = true i get the following output for function prototypes and definitions:
```
uint32_t foo ( uint8_t param1
             , some_datatype param2
             , datatype param3
             , another_datatype *param4
             , uint16_t param5
             , uint32_t *param6
             );
```

What i expect is something like this:

```
uint32_t foo ( uint8_t           param1
             , some_datatype     param2
             , datatype          param3
             , another_datatype  *param4
             , uint16_t          param5
             , uint32_t          *param6
             );
```

Is there a way to do achieve this with uncrustify?

Thank you very much,
Michael

**Comment by CDanU** [comment]
Hmm that should do it:
C:
```sql
# Align variable definitions in prototypes and functions.
align_func_params               = true     # false/true

# The span for aligning parameter definitions in function on parameter name (0=don't align).
align_func_params_span          = 1        # unsigned number
```

<table>
<tr>
<td>

I:<code>

```cpp
uint32_t foo ( uint8_t param1
               , some_datatype param2
               , datatype param3
               , another_datatype *param4
               , uint16_t param5
               , uint32_t *param6
               );

uint32_t foo ( uint8_t param1,
               some_datatype param2, 
               datatype param3, 
               another_datatype *param4, 
               uint16_t param5,
               uint32_t *param6
               );
```
</code>
</td>
<td>

O:<code>

```cpp
uint32_t foo ( uint8_t param1
               , some_datatype param2
               , datatype param3
               , another_datatype *param4
               , uint16_t param5
               , uint32_t *param6
               );

uint32_t foo ( uint8_t           param1,
               some_datatype     param2,
               datatype          param3,
               another_datatype *param4,
               uint16_t          param5,
               uint32_t *        param6
               );
```
</code>

</td>
</tr>
</table>


As you can see for some reason your coma placement is breaking this functionality.

I will take a look at this next week.

PS: additionally using `
pos_comma                       = lead_force   # ignore/join/lead/lead_break/lead_force/trail/trail_break/trail_force` also doesn't work

**Comment by TTTMike** [comment]
Okay, thank you very much!

I also noticed that using `pos_comma = lead` requires two executions of uncrustify on the same file to move the commas correctly in front of the parameters.

I could use `pos_comma = lead_break` which works correctly on the first execution but this option again messes with `ls_func_split_full = true` in a way that `pos_comma = lead_break` leads to functions beeing split even if they are shorter than `code_width`.

**Comment by guy-maurel** [comment]
Using the config options:
```
align_func_params_span   = 1
pos_comma                = lead_force
align_var_def_star_style = 2
```
is what you wanted to get.
Please test and report.

**Comment by TTTMike** [comment]
Since #1606 everything works as expected, thank you very much!
