### ISSUE TITLE
nl_if_leave_one_liners = true - ignore

### ISSUE THREAD

**Issue by Keepun** [uncrustify/uncrustify#160]
Config:
nl_if_leave_one_liners = true
nl_if_brace = add

Code:
if (true1) return(-1);
else if (true2) return(1);

Result:
if (true1) return(-1);
else if (true2)
          return(1);

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!

**Comment by CDanU** [comment]
It does not:
O:
```cpp
if (true1) return(-1);
else if (true2)
	return(1);
```
The 2nd return should stay on the else if line. Please reopen.

<details>
<pre>
# Uncrustify-0.64-595-79ba971f
nl_if_leave_one_liners          = true
nl_if_brace                     = add
# option(s) with 'not default' value: 2
#
# -=====-
# Line              Tag           Parent          Columns Br/Lvl/pp     Flag   Nl  Text
#   1>               IF[            NONE][  1/  1/  3/  0][0/0/0][     60000][0-0] if
#   1>      SPAREN_OPEN[              IF][  4/  4/  5/  1][0/0/0][ 100000000][0-0]    (
#   1>             WORD[            NONE][  5/  5/ 10/  0][0/1/0][     40020][0-0]     true1
#   1>     SPAREN_CLOSE[              IF][ 10/ 10/ 11/  0][0/0/0][ 100000000][0-0]          )
#   1>      VBRACE_OPEN[              IF][ 11/  0/  0/  0][0/0/0][  20000000][0-0]
#   1>           RETURN[            NONE][ 12/ 12/ 18/  1][1/1/0][  20060000][0-0]            return
#   1>       PAREN_OPEN[          RETURN][ 18/ 18/ 19/  0][1/1/0][ 120040000][0-0]                  (
#   1>              NEG[            NONE][ 19/ 19/ 20/  0][1/2/0][ 120040000][0-0]                   -
#   1>           NUMBER[            NONE][ 20/ 20/ 21/  0][1/2/0][  20040000][0-0]                    1
#   1>      PAREN_CLOSE[          RETURN][ 21/ 21/ 22/  0][1/1/0][ 120000000][0-0]                     )
#   1>        SEMICOLON[            NONE][ 22/ 22/ 23/  0][1/1/0][ 120000000][0-0]                      ;
#   1>     VBRACE_CLOSE[              IF][ 24/  0/  0/  0][0/0/0][  20000000][0-0]
#   1>          NEWLINE[            NONE][ 24/ 23/  1/  0][0/0/0][         0][1-0]
#   2>             ELSE[            NONE][  1/  1/  5/  0][0/0/0][     70000][0-0] else
#   2>           ELSEIF[            NONE][  6/  6/  8/  1][0/0/0][         0][0-0]      if
#   2>      SPAREN_OPEN[          ELSEIF][  9/  9/ 10/  1][0/0/0][ 100000000][0-0]         (
#   2>             WORD[            NONE][ 10/ 10/ 15/  0][0/1/0][     40020][0-0]          true2
#   2>     SPAREN_CLOSE[          ELSEIF][ 15/ 15/ 16/  0][0/0/0][ 100000000][0-0]               )
#   2>      VBRACE_OPEN[          ELSEIF][ 16/  0/  0/  0][0/0/0][  20000000][0-0]
#   2>          NEWLINE[            NONE][ 16/ 16/  0/  0][0/0/0][         0][1-0]
#   2>           RETURN[            NONE][  9/ 17/ 23/  1][1/1/0][  20060000][0-0]         return
#   2>       PAREN_OPEN[          RETURN][ 15/ 23/ 24/  0][1/1/0][ 120040000][0-0]               (
#   2>           NUMBER[            NONE][ 16/ 24/ 25/  0][1/2/0][  20040000][0-0]                1
#   2>      PAREN_CLOSE[          RETURN][ 17/ 25/ 26/  0][1/1/0][ 120000000][0-0]                 )
#   2>        SEMICOLON[            NONE][ 18/ 26/ 27/  0][1/1/0][ 120000000][0-0]                  ;
#   2>     VBRACE_CLOSE[          ELSEIF][ 20/  0/  0/  0][0/0/0][  20000000][0-0]
#   2>          NEWLINE[            NONE][ 20/ 27/  1/  0][0/0/0][         0][1-0]
# -=====-
<pre></details>
