### ISSUE TITLE
Space removed when declaring variable with decltype

### ISSUE THREAD

**Issue by hdwobben** [uncrustify/uncrustify#1607]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
Hi, 

When using decltype to declare or define a variable in C++, uncrustify removes the space after ```decltype(expression)``` and the variable name. I used an empty config file. I couldn't find any config options to change this behaviour. The problem was also mentioned [here](https://github.com/uncrustify/uncrustify/issues/1321) but that issue was closed.

- input:
```
int i = 5;
double d = 3.14;
decltype(i * d) prod = i * d;
decltype(i + d) sum;
```
- result:

```
int i = 5;
double d = 3.14;
decltype(i * d)prod = i * d;
decltype(i + d)sum;
```
- expected
```
int i = 5;
double d = 3.14;
decltype(i * d) prod = i * d;
decltype(i + d) sum;
```

- current version: Uncrustify-0.66.1-296-4b87296

**Comment by CDanU** [comment]
I can't reproduce this on the current master: uncrustify-0.66.1-327-g228e2407
It got fixed somewhere in between.

**Comment by CDanU** [comment]
You could however make a PR to add this example as testcase so that this definitely won't happen again.

**Comment by hdwobben** [comment]
You're right, this was indeed fixed. I'll make a test case for this. Thanks.
