### ISSUE TITLE
$(filename) not working in inserted footer file

### ISSUE THREAD

**Issue by jgdye** [uncrustify/uncrustify#1608]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

When trying to include a file footer, the $(filename) variable is not being filled. I've included a debug file at this [gist](https://gist.github.com/jgdye/839e2ed6bcac76986cee9798ecafe5c7).
Start file:
```
int main(){}
```
Generated results:
```
// library.cpp
int main(){}

// $(filename)
```
Expected results:
```
// library.cpp
int main(){}

// library.cpp
````
I'm using Uncrustify-0.66.1-331-c93e085, but it seems to also be an issue in the Debian packaged 0.66.1 and 0.59 versions.  The inserted file header and footer files in this particular case are simply // $(filename), and while separate files, one is a copy of the other.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by jgdye** [comment]
Sorry for the long delay. I didn't seem to get the GitHub notification in my email. I did a pull today, and have the same result, an identical file for header and footer gives me the file name in the header and $(filename) in the footer.
