### ISSUE TITLE
Objective-C Properties: Space always inserted before colon for value of "setter" attribute

### ISSUE THREAD

**Issue by macserv** [uncrustify/uncrustify#161]
@property (setter = setCDATA :) NSData* cdata;
                             // ^ This space is always added.

According to the log output, uncrustify thinks that the colon here is a "CLASS_COLON", however, changing settings relating to "class_colon" have no effect on this space.  While this code currently compiles without issue, it's definitely ugly.

**Comment by mittsh** [comment]
Same issue here! Would love a fix :D

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
