### ISSUE TITLE
Support for @available syntax in ObjC

### ISSUE THREAD

**Issue by Krizai** [uncrustify/uncrustify#1613]
Input:
```
if (@available(macOS 10.13.1, iOS 11, *)) {
 // The compiler will not warn about uses of APIs from macOS 10.13
 // or iOS 11 here
}
```
Output:
```
if (@available(macOS 10.13 .1, iOS 11, *)) {
    // The compiler will not warn about uses of APIs from macOS 10.13
    // or iOS 11 here
}
```

Uncrustify puts a space beetween `10.13` and `.1` as it consider them as two numbers.

**Comment by CDanU** [comment]
Can you provide documentation for that ? Those parameters look like strings but are not? 

So far I only have found [info](https://forums.developer.apple.com/thread/88869) that this available compiler directive is somehow similar to #available in swift and that it got imported by clang for xcode 9.

> — Each parameter except the last indicates the minimum version of an OS/platform. The version number is in the form X, X.Y or X.Y.Z.
> — The last "*" indicates that the code is also for all other platforms beyond the ones listed in the test.

**Comment by Krizai** [comment]
I also didn't found explicit documentation about the format, the only official thing I found is [this](http://clang.llvm.org/docs/LanguageExtensions.html#objective-c-available).
I believe it's pretty safe to consider everything inside @available() as a string and just don't touch it during formatting.

**Comment by Krizai** [comment]
I think we can close this as https://github.com/uncrustify/uncrustify/pull/1639 was merged
