### ISSUE TITLE
Function split on the next line after '='

### ISSUE THREAD

**Issue by tawmoto** [uncrustify/uncrustify#1615]
Hello,
I have the following options

```
input_tab_size = 4
output_tab_size = 4
indent_columns = 4
code_width = 110
```

and the following code

```
int main()
{
    if (1)
    {
        if (1)
        {
            internal_rc = option_get_option(test_ilib, lib_tester_fd, TESTER_OPTION_DETECT_TEST, &option_value);
        }

    }
}
```

After the uncrustify (0.66.1-294-a9e70a5) I get:
```
internal_rc =
      option_get_option(test_ilib, lib_tester_fd, TESTER_OPTION_DETECT_TEST, &option_value);
```
and I expect:
```
internal_rc = option_get_option(test_ilib, lib_tester_fd,
			        TESTER_OPTION_DETECT_TEST,
			        &option_value);
```
or
```
internal_rc = option_get_option(test_ilib, lib_tester_fd, TESTER_OPTION_DETECT_TEST,
			        &option_value);
```
If I set the column limit between 80-100 (instead of 110), it works perfectly. I just don't want to split after the '=', but on parameter.
If it's needed, i will add also debug file.

Thank you.

**Comment by tawmoto** [comment]
Perhaps it's related, but I get also another similar ugly formatting.

`terminal_message = (0 == user_data->scan_keywords) ?AV_string_from_cstr(SCAN_KEYWORD_OK_STR) : get_scan_keywords_str(user_data->scan_keywords);`

to this:
```
            terminal_message =
                (0 ==
                 user_data->scan_keywords) ? AV_string_from_cstr(SCAN_KEYWORD_OK_STR) : get_scan_keywords_str(
                    user_data->scan_keywords);
```
I think this would look a lot better
```
            terminal_message = (0 == user_data->scan_keywords) ? 
                                AV_string_from_cstr(SCAN_KEYWORD_OK_STR) : 
                                get_scan_keywords_str(user_data->scan_keywords);
```

Perhaps someone can tell me which option to set in order NOT to go to a next line after an "=" character, thanks.

**Comment by tawmoto** [comment]
Another one. I have a lot of options (which will pollute this topic) that causes all function arguments to be one on each line if column_limit is reached.

    if (OPTION_S_OK == user_data->OPTIONlib->symbols.OPTION_get(user_data->wdata->lib_OPTION_fd, (OPTION_OPTION)option, st_char_buffer, &st_char_size))

got
   ```
 if (OPTION_S_OK ==
        user_data->OPTIONlib->symbols.OPTION_get(user_data->wdata->lib_OPTION_fd, (OPTION_OPTION)option,
                                                 st_char_buffer, &st_char_size))
```
expected
 ```
 if (OPTION_S_OK == user_data->OPTIONlib->symbols.OPTION_get(user_data->wdata->lib_OPTION_fd, 
                                                             (OPTION_OPTION)option,
                                                             st_char_buffer, 
                                                             &st_char_size))
```

**Comment by guy-maurel** [comment]
Some of the options are working if the open-parenthesis and the close-parenthesis ARE NOT on the same lines.
Help uncrustify a little bit!
As example, using an input such as:
```cpp
int main()
{
    if (1)
    {
        if (1)
        {
            internal_rc = option_get_option(test_ilib, lib_tester_fd,
TESTER_OPTION_DETECT_TEST, &option_value);
terminal_message = (0 == user_data->scan_keywords) ?
AV_string_from_cstr(SCAN_KEYWORD_OK_STR) 
: get_scan_keywords_str(user_data->scan_keywords);
        }
if (OPTION_S_OK == user_data->OPTIONlib->symbols.OPTION_get(user_data->wdata->lib_OPTION_fd, (OPTION_OPTION)option,
st_char_buffer, &st_char_size))
        {

    }
    }
}
```
and adding some options to the configuration file:
```
#input_tab_size = 4
#output_tab_size = 4
indent_with_tabs = 0
indent_columns   = 4
code_width       = 110
nl_func_call_args_multi_line = true
```
you get it pretty:
```cpp
int main()
{
    if (1)
    {
        if (1)
        {
            internal_rc = option_get_option(test_ilib,
                                            lib_tester_fd,
                                            TESTER_OPTION_DETECT_TEST,
                                            &option_value);
            terminal_message = (0 == user_data->scan_keywords) ?
                               AV_string_from_cstr(SCAN_KEYWORD_OK_STR)
                               : get_scan_keywords_str(user_data->scan_keywords);
        }
        if (OPTION_S_OK == user_data->OPTIONlib->symbols.OPTION_get(user_data->wdata->lib_OPTION_fd,
                                                                    (OPTION_OPTION)option,
                                                                    st_char_buffer,
                                                                    &st_char_size))
        {

        }
    }
}
```

**Comment by tawmoto** [comment]
@guy-maurel Thank you for the answer, I am trying to uncrustify a project with unlimited number of columns(some lines are 250 columns length), everything is on the same line, .
I have "nl_func_call_args_multi_line = true", I did not include it to simplify my example.

What are my options in this case? To manually set the closing parantheses to another line and then uncrustify?

Best regards.

**Comment by guy-maurel** [comment]
Don't use:
```
input_tab_size
output_tab_size
```
Most of the editors don't know what you have choosen.
Use also:
`indent_with_tabs = 0`  # which is `0=spaces only`
`code_width = 80` is best appropriate to the monitor(s) one is using.
It might be wise to use more temporary variable. I would preffer to split your last if statement to:
```
       TheTypeOfOptionLib *tmp = user_data->OPTIONlib;
       TheTypeOfWdata *wtemp   = user_data->wdata;
       if (OPTION_S_OK == tmp->symbols.OPTION_get(wtemp->lib_OPTION_fd,
                                                  (OPTION_OPTION)option,
                                                  st_char_buffer,
                                                  &st_char_size))
        {
```
You might need more than two runs to get a "better" layout!

**Comment by tawmoto** [comment]
Thank you for the answer, I will try to help uncrustify a bit. Unfortunetaly the code_witdth=80 is not really appropriate for our 27inch monitors, because almost half of the screen is left blank. (some of us don't like to split the screen)
Regards :+1:
