### ISSUE TITLE
C++ class::method colon's breaking code.

### ISSUE THREAD

**Issue by caseybasichis** [uncrustify/uncrustify#163]
I am trying to use Uncrustify but all configurations are breaking my code when working in xcode

std::vector<int> a;
becomes

std: : vector<int> a;
Is there a way to prevent this so that the :: is held together.  Currently it is breaking all of my code.

I have tried all of the colon setting to no avail.

**Comment by szalap** [comment]
How to specify language in .cfg file?

**Comment by gmaurel** [comment]
NOT in the config file BUT in the command with
  -l           : Language override: C, CPP, D, CS, JAVA, PAWN, OC, OC+, VALA.
or the file name such as my_example.cpp
