### ISSUE TITLE
Only UT tests are adopted

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1630]
@mihaipopescu : Only UT tests and the necessary source code are adopted.
There are still portions of source code without any tests. I couldn't prove the code is necessary.
UT might have some more code to test that.
Please push it!
Thanks.
Such an example is:
395689950791ef6d51498a1eb5bb365515b8a3de,
the added lines at

```
@@ -3353,21 +3356,26 @@ static void mark_function(chunk_t *pc)
          {
             LOG_FMT(LFCN, " --> Stopping on %s [%s]\n",
                     prev->str.c_str(), get_token_name(prev->type));
             /* certain tokens are unlikely to precede a proto or def */
             if ((prev->type == CT_ARITH) ||
                 (prev->type == CT_ASSIGN) ||
                 (prev->type == CT_COMMA) ||
                 (prev->type == CT_STRING) ||
                 (prev->type == CT_STRING_MULTI) ||
                 (prev->type == CT_NUMBER) ||
-                (prev->type == CT_NUMBER_FP))
+                (prev->type == CT_NUMBER_FP) ||
+                (prev->type == CT_COMPARE) ||
+                ((prev->type == CT_AS) && (cpd.lang_flags & LANG_CS)) ||
+                ((prev->type == CT_SCOMPARE) && (cpd.lang_flags & LANG_CS)) ||
+                ((prev->type == CT_BOOL) && (cpd.lang_flags & LANG_CS)) ||
+                ((prev->type == CT_COLON) && (cpd.lang_flags & LANG_CS)))
```

**Comment by mihaipopescu** [comment]
It's been more than 3 years ago and I cannot find any additional information and it's also unlikely that @simonm-unity will have anything on this as well.

**Comment by gmaurel** [comment]
Well, we can let the master such at it is just know. And way until new messages are coming.

**Comment by gmaurel** [comment]
No more comment?

**Comment by mihaipopescu** [comment]
No let's close it. I have no idea why those changes were made. The changes predates me starting to contribute to this project. I'm sorry. What I know it's that they just work.
