### ISSUE TITLE
Where is the documentation for config files?

### ISSUE THREAD

**Issue by nowox** [uncrustify/uncrustify#1635]
There is only one [example](https://raw.githubusercontent.com/uncrustify/uncrustify/master/documentation/htdocs/ben.cfg.txt) file  for the config file, but no documentation. It is said that there are 609 configurable options, but this config file is not complete. 

Where can I find the documentation?

**Comment by gmaurel** [comment]
The beginning of the html documentation can be found at
  https://github.com/uncrustify/uncrustify/blob/master/documentation/htdocs/index.html
Also have a look to (all the options, less details):
  https://github.com/uncrustify/uncrustify/blob/master/etc/defaults.cfg

**Comment by CDanU** [comment]
I am not entirely sure why it has update in the name but using `--update-config-with-doc` is always going to be the safest bet to get minimal documentation until we sometime in the future set up a proper documentation.
