### ISSUE TITLE
New feature: Add or remove space between reference signs '&'

### ISSUE THREAD

**Issue by iendeavor** [uncrustify/uncrustify#1636]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Like this:
\# Add or remove space between pointer stars '*'.
sp_between_ptr_star             = remove   # ignore/add/remove/force

I think we need the feature for "rvalue reference" in cpp:
\# Add or remove space between reference signs '&'.
sp_between_byref             = remove   # ignore/add/remove/force
and
\# Add or remove space after a pointer star '*', if followed by a reference sign '&'.
sp_after_ptr_start_byref             = remove   # ignore/add/remove/force

**Comment by CDanU** [comment]
Check if:
```sql

# How to align the star in variable definitions.
#  0=Part of the type     'void *   foo;'
#  1=Part of the variable 'void     *foo;'
#  2=Dangling             'void    *foo;'
align_var_def_star_style        = 1        # unsigned number

# How to align the '&' in variable definitions.
#  0=Part of the type
#  1=Part of the variable
#  2=Dangling
align_var_def_amp_style         = 1        # unsigned number
``` 
helps you and report.

**Comment by paulthomson** [comment]
Note that this isn't just a C++11 issue. It also applies to the following. I think the star is parsed as multiplication.

```cpp
void F(int *&Provider) // becomes int * &Provider
{
}
```

**Comment by guy-maurel** [comment]
No.
```.txt
# Uncrustify-0.67-64-837b75b-dirty
# -=====-
# Line                Tag              Parent          Columns Br/Lvl/pp     Flag   Nl  Text
#   1>               TYPE[           FUNC_DEF][  1/  1/  5/  0][0/0/0][     70000][0-0] void
#   1>           FUNC_DEF[               NONE][  6/  6/  7/  1][0/0/0][         0][0-0]      F
#   1>        FPAREN_OPEN[           FUNC_DEF][  7/  7/  8/  0][0/0/0][ 100000000][0-0]       (
#   1>               TYPE[               NONE][  8/  8/ 11/  0][0/1/0][    440008][0-0]        int
#   1>           PTR_TYPE[               NONE][ 12/ 12/ 13/  1][0/1/0][ 100000008][0-0]            *
#   1>              BYREF[               NONE][ 13/ 13/ 14/  0][0/1/0][ 100000008][0-0]             &
#   1>               WORD[               NONE][ 14/ 14/ 22/  0][0/1/0][    800008][0-0]              Provider
#   1>       FPAREN_CLOSE[           FUNC_DEF][ 22/ 22/ 23/  0][0/0/0][ 100000000][0-0]                      )
#   1>            NEWLINE[               NONE][ 23/ 23/  1/  0][0/0/0][         0][1-0]
#   2>         BRACE_OPEN[           FUNC_DEF][  1/  1/  2/  0][0/0/0][ 140000000][0-0] {
#   2>            NEWLINE[               NONE][  2/  2/  1/  0][1/1/0][         0][1-0]
#   3>        BRACE_CLOSE[           FUNC_DEF][  1/  1/  2/  0][0/0/0][ 140000000][0-0] }
#   3>            NEWLINE[               NONE][  2/  2/  1/  0][0/0/0][         0][1-0]
```
What do you think?
