### ISSUE TITLE
Function in namespace with same name can result in extra whitespace

### ISSUE THREAD

**Issue by jibsen** [uncrustify/uncrustify#164]
If you call a function in a namespace with the same name as the function, then sometimes an extra space is added before the argument. As an example,

```C++
void foo()
{
    pump::choose(&gas);
    pump::pump(&gas);
}
```

becomes

```C++
void foo()
{
    pump::choose(&gas);
    pump::pump( &gas);
}
```

Of course one could argue that having a function with the same name as the namespace it is in is not a good idea, but Visual C++ and GCC did not complain.

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
