### ISSUE TITLE
regression with nl_fdef_brace and nested namespaces

### ISSUE THREAD

**Issue by dirk-thomas** [uncrustify/uncrustify#1646]
I just tried to upgrade from an older version of `uncrustify` but the behavior seem to have been regressed for the following input:

```
int
ns1::ns2::func()
{
  return 0;
}
```

With the setting `nl_fdef_brace = force` I expect the newline between the `()` and the `{` to stay and the output to be equal to the input. At least that was the behavior before. The current version changes the output to:

```
int
ns1::ns2::func() {
  return 0;
}
```

The full configuration used with the [latest hash](https://github.com/uncrustify/uncrustify/commit/f02af8c39b380e155581a9079262fad52750041e) of `uncrustify` can be found [here](https://github.com/ament/ament_lint/blob/e0b8fbb29136934db99063dbdcc82e4cf7fbe3f4/ament_uncrustify/ament_uncrustify/configuration/ament_code_style.cfg).

The "working" version of `uncrustify` is from Sep 29, 2017 using [this](https://github.com/ament/ament_lint/blob/391089687a0b6dc511a13aee4a104e8a7274aa9f/ament_uncrustify/ament_uncrustify/configuration/ament_code_style.cfg) configuration file.

It seems to be that the option `nl_fdef_brace` doesn't even apply in this case. The behavior stays the same independent of what value the option has. Maybe this case get misclassified due to a recent change?

Please let me know if there is any further information I can provide to resolve the regression.

**Comment by CDanU** [comment]
This is caused  by the
```sql
# Add or remove newline between a function call's ')' and '{', as in:
# list_for_each(item, &list) { }.
nl_fcall_brace                  = remove   # ignore/add/remove/force
```
option. It is one of those pre 0.0.5 version options. `list_for_each` is a linux kernel macro for a loop. So that really isn't a function call. I'll do a bisect to see what caused this.

**Comment by dirk-thomas** [comment]
Thank you for your comment. Setting `nl_fcall_brace` to `ignore` is working around the problem for me (since we don't use any code which should actually match `nl_fcall_brace`).

**Comment by gmaurel** [comment]
may we close?

**Comment by dirk-thomas** [comment]
I would say rather no. This is still a regression miss-classifying a function with a nested namespace. It would be good to fix this.

**Comment by guy-maurel** [comment]
Where is the miss-classifying a function?
I get:
```.txt
# Line                Tag              Parent          Columns Br/Lvl/pp     Flag   Nl  Text
#   1>               TYPE[           FUNC_DEF][  1/  1/  4/  0][0/0/0][     60000][0-0] int
#   1>            NEWLINE[               NONE][  4/  4/  1/  0][0/0/0][         0][1-0]
#   2>               TYPE[           FUNC_DEF][  1/  1/  4/  0][0/0/0][         0][0-0] ns1
#   2>          DC_MEMBER[           FUNC_DEF][  4/  4/  6/  0][0/0/0][ 100000000][0-0]    ::
#   2>               TYPE[           FUNC_DEF][  6/  6/  9/  0][0/0/0][         0][0-0]      ns2
#   2>          DC_MEMBER[           FUNC_DEF][  9/  9/ 11/  0][0/0/0][ 100000000][0-0]         ::
#   2>           FUNC_DEF[               NONE][ 11/ 11/ 15/  0][0/0/0][         0][0-0]           func
#   2>        FPAREN_OPEN[           FUNC_DEF][ 15/ 15/ 16/  0][0/0/0][ 100000000][0-0]               (
#   2>       FPAREN_CLOSE[           FUNC_DEF][ 16/ 16/ 17/  0][0/0/0][ 100000000][0-0]                )
#   2>            NEWLINE[               NONE][ 17/ 17/  1/  0][0/0/0][         0][1-0]
#   3>         BRACE_OPEN[           FUNC_DEF][  1/  1/  2/  0][0/0/0][ 100000000][0-0] {
#   3>            NEWLINE[               NONE][  2/  2/  3/  0][1/1/0][         0][1-0]
#   4>             RETURN[               NONE][  3/  3/  9/  0][1/1/0][     60000][0-0]   return
#   4>             NUMBER[               NONE][ 10/ 10/ 11/  1][1/1/0][     40000][0-0]          0
#   4>          SEMICOLON[               NONE][ 11/ 11/ 12/  0][1/1/0][ 100000000][0-0]           ;
#   4>            NEWLINE[               NONE][ 12/ 12/  1/  0][1/1/0][         0][1-0]
#   5>        BRACE_CLOSE[           FUNC_DEF][  1/  1/  2/  0][0/0/0][ 100000000][0-0] }
#   5>            NEWLINE[               NONE][  2/  2/  1/  0][0/0/0][         0][1-0]
```
func is classified as FUNC_DEF

**Comment by dirk-thomas** [comment]
> Where is the miss-classifying a function?
> func is classified as FUNC_DEF

I was just assuming it is classified incorrectly. 

Why is `nl_fdef_brace = force` not inserting the newline between the closing parenthesis and the open curly brace? But `nl_fcall_brace` does affect the code - there is no function call in this piece of code?

**Comment by gmaurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by dirk-thomas** [comment]
> > Why is `nl_fdef_brace = force` not inserting the newline between the closing parenthesis and the open curly brace?

> The current git version works pretty fine.

Just to make sure what to check for: so with the current master `nl_fdef_brace = force` does insert the newline and `nl_fcall_brace` doesn't affect the code anymore?

**Comment by gmaurel** [comment]
Have a look to the description of the option nl_fdef_brace:
_Add or remove newline between a function call's ')' and '{', as in 'list_for_each(item, &amp;list) { }'._
This is not related to the test data you have provided.
