### ISSUE TITLE
regression inserting space between noexcept an open parenthesis

### ISSUE THREAD

**Issue by dirk-thomas** [uncrustify/uncrustify#1649]
I just tried to upgrade from an older version of `uncrustify` but the behavior seem to have been regressed for the following input:

```
Foo()
noexcept()
{}
```

With the default settings I expect the output to be equal to the input. At least that was the behavior before. The current version changes the output to (note the added space between `noexept` and `(`):

```
Foo()
noexcept ()
{}
```

The "working" version of `uncrustify` is from Sep 29, 2017.

Looking at the debug output I noticed the following [warning](https://github.com/uncrustify/uncrustify/blob/67b707eee0329a668b0950b9699ea60ff40912ba/src/space.cpp#L2159) which seems to be related to the inserted space:

> do_space(2146): WARNING: unrecognize do_space:

Please let me know if there is any further information I can provide to resolve the regression.

**Comment by CDanU** [comment]
The commit 666617918013bdf3e64b5ee0714d87d20358b6fb introduced a token type for noexcept, before that It most likely was a CT_WORD. Currently there are no spacing rules for `CT_NOEXCEPT` so the default operation is used which (unfortunately) is `AV_ADD`.

This can be fixed if you introduce a new rule:
```cpp
   if (first->type == CT_NOEXCEPT && second->type == CT_PAREN_OPEN)
   {
      log_rule("AV_IGNORE");
      return(AV_IGNORE);
   }
```

or better yet make some new options properly to control that.

**Comment by dirk-thomas** [comment]
@CDanU Thank you for the quick feedback.

**Comment by gmaurel** [comment]
A new option will be the better way

**Comment by guy-maurel** [comment]
#1680 is a bugfix proposal

**Comment by guy-maurel** [comment]
Fixed
