### ISSUE TITLE
Preprocessor directives indented wrong in some multi-line string literals

### ISSUE THREAD

**Issue by jibsen** [uncrustify/uncrustify#165]
```C++
void foo()
{
    printf("multiple lines "
#ifdef FOO
        "adding together "
#else
        "being concatenated "
#endif
        "into one");

    std::cout << "multiple lines "
#ifdef FOO
        "adding together "
#else
        "being concatenated "
#endif
        "into one";
}
```

Produces the correct indentation for printf, but not for std::cout.

**Comment by addonszz** [comment]
Here is my output for your entry processed by uncrustify 0.61. It is lacking the indentation at std::cout.
```
void foo()
{
    printf("multiple lines "
#ifdef FOO
            "adding together "
#else
            "being concatenated "
#endif
            "into one");
    
    std:: cout<<"multiple lines "
#ifdef FOO
    "adding together "
#else
    "being concatenated "
#endif
    "into one";
}
```

**Comment by gmaurel** [comment]
@jibsen Is there anything new?

**Comment by jibsen** [comment]
Sorry, I should check my old issues. With the current git version, I get the same output as @addonszz. If I remove the preprocessor lines, it indents the strings, so I guess they are the bit that is confusing uncrustify.

**Comment by jibsen** [comment]
Anyway, it's not an issue I've run into again in the three years since I opened the issue, so I guess it's not too bad.
