### ISSUE TITLE
'if constexpr` blocks not correctly indented

### ISSUE THREAD

**Issue by Leandros** [uncrustify/uncrustify#1661]
Trying to format a file using C++17's new `if constexpr` fails, with the following error:

```
check_complex_statements(889): foo.cpp, orig_line is 4, Error: Expected '(', got 'constexpr' for 'IF'
```
Though, it still formats the file, it just fails to indent the if correctly. Example:

```
void foo()
{
    if constexpr (true)
        bar();
}
```

is transformed into

```
void foo()
{
    if constexpr (true)
    bar();
}
```

**Uncrustify version:** 0.66.1

**Attachments:** [debug.zip](https://github.com/uncrustify/uncrustify/files/1792439/debug.zip), containing `debug.txt`, uncrustify's debug output and `foo.cpp`, the file which I tried formatting.

**Comment by CDanU** [comment]
Check out 7c8a9cbb19a07ec1d2e7cf4bc339c7cb32b247e9 (#1470)

**Comment by KVic** [comment]
> @KVic there is a FIXME in the comment line, does this need any alteration?

In my opinion, in normal code there should not be comparisons of keywords with standalone string literals. Such as `pc->str.equals("constexpr")`, `chunk_is_str(br_o, "mutable", 7)` in [combine.cpp](https://github.com/uncrustify/uncrustify/blob/master/src/combine.cpp#L5289), and so on. At least, keyword string literals must be defined through constants:
```
static const char* KW_constexpr = "constexpr";
static const char* KW_mutable   = "mutable";
```
But it's best to associate them with the [keywords table](https://github.com/uncrustify/uncrustify/blob/master/src/keywords.cpp#L57). Maybe like [this](https://godbolt.org/g/QhBxpH) (this is C++14 code, C++11 does not implement `for` in the `constexpr` function, but it can be done through a recursive function).

**Comment by pyssling** [comment]
Any news on this issue? @gmaurel ?

**Comment by guy-maurel** [comment]
Too many mails, not enought people!

**Comment by guy-maurel** [comment]
I get, just now:
```.cpp
void foo();
void bar()
{
        if constexpr (true)
                foo();
}
```
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
