### ISSUE TITLE
Ignoring align_var_def_amp_style and sp_before_byref, no space around &

### ISSUE THREAD

**Issue by Massimo-B** [uncrustify/uncrustify#1669]
With the current version of uncrustify from git, there is no space around '&'.

Reproduce with this bash one-liner:
```cpp
$ (cfg="https://bitbucket.org/massimo/test/raw/6abd6f81cb80f8d62539c1c90526bd208f714179/crusty-test_014.cfg" ; input="https://bitbucket.org/massimo/test/raw/f21560578b410a5635e5a2d67d3f4da15135f1f9/crusty-test_014.cpp" ; uncrustify -v ; curl -s "$input" ; curl -s "$input" | uncrustify -l cpp -c <(curl -s "$cfg") )
Uncrustify-0.66.1-424-daf73ad7
class MyBase
{
    protected:
        const QString&  getErrorText() const;
        const QString&  getErrorTextTranslated() const;
};
Parsing: 135 bytes (135 chars) from stdin as language CPP
class MyBase
{
    protected:
        const QString&getErrorText() const;
        const QString&getErrorTextTranslated() const;
};
```

[[Configuration]](https://bitbucket.org/massimo/test/raw/6abd6f81cb80f8d62539c1c90526bd208f714179/crusty-test_014.cfg) [[Source]](https://bitbucket.org/massimo/test/raw/f21560578b410a5635e5a2d67d3f4da15135f1f9/crusty-test_014.cpp)

At least one of these options should change that behaviour, but has no efect: 
```
align_var_def_amp_style  2
sp_before_byref  force
```

The same issue applies to the * sign.
It could be part of the type or part of the name, but having no space at all doesn't make sense and I can't find the option to change that.

**Comment by Massimo-B** [comment]
```
sp_type_func = force
```
...could also be related.

**Comment by guy-maurel** [comment]
You are using:
`sp_after_byref_func             = remove`

The result is correct.
I cannot see any bug.

**Comment by CDanU** [comment]
While this is technically doing what the op wants we still should prevent this behavior.
If I remember correctly we already do have cases where we ignore removes if they would generate code that breaks a compile.

**Comment by guy-maurel** [comment]
`g++ -std=c++11  Massimo-B.cpp`
doesn't produce any breaks under linux
