### ISSUE TITLE
Objective-C method signature, newline before brace ('{')

### ISSUE THREAD

**Issue by JanX2** [uncrustify/uncrustify#167]
My preferred style is to add a newline between method declarations and the opening brace. 

So this

```
- (void)dealloc {
    [self closeFile];

    [self setData:nil];

    [super dealloc];
}
```

becomes this

```
- (void)dealloc
{
    [self closeFile];

    [self setData:nil];

    [super dealloc];
}
```

This can already be done using

```
# Add or remove newline between function signature and '{'
nl_fdef_brace                            = force   # ignore/add/remove/force
```

My problem is that I don’t want the newline between function signatures and the '{'. Only for method signatures! It would be great, if the two could be separated and a new option added like so:

```
# Add or remove newline between method declaration and '{'
nl_oc_mdef_brace                            = force   # ignore/add/remove/force
```

**Comment by guy-maurel** [comment]
Could you push two examples so we could see which differences between _function signatures_ and _method signatures_ ? I am not an OC expert. Thanks.
