### ISSUE TITLE
Invalid formatting of templates

### ISSUE THREAD

**Issue by Neargye** [uncrustify/uncrustify#1672]
Add extra space newline between 'template<>' and whatever follows.

before:
```
template<class T> void f(T t)
```

expected:
```
template<class T>
void f(T t)
```

after:
```
template<class T>

void f(T t)
```

uncrustify config should influence this:
```
# Add or remove newline between 'template<>' and whatever follows.
nl_template_class               = force   # ignore/add/remove/force

# The number of newlines before a multi-line function def body.
nl_before_func_body_def         = 2        # unsigned number

# Whether to put a newline after brace open.
# This also adds a newline before the matching brace close.
nl_after_brace_open             = true    # false/true
```

Version: Uncrustify-0.66.1
[uncrustify_conf.txt](https://github.com/uncrustify/uncrustify/files/1811200/uncrustify_conf.txt)

**Comment by guy-maurel** [comment]
Your configuration file has an error. Correct is:
`pos_enum_comma                  = trail_force`
The current git version works:
```
Uncrustify_d-0.66.1-477-47ba574
Parsing: Terik23.cpp as language CPP
template<class T>
void f(T t)
```

**Comment by CDanU** [comment]
I can't reproduce the behavior described by op in the current master (2e91534fb2c125a2506f59932bd02c8fb6936d34), the expected output is generated.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
