### ISSUE TITLE
Invalid collapse empty blocks between '{' and '}' with multi-line comments.

### ISSUE THREAD

**Issue by Neargye** [uncrustify/uncrustify#1673]
before:
```
case CASE_A:
{
    /* Long
    * comment */
} break;
```

expected:
```
case CASE_A:
{
    /* Long
    * comment */
}
break;
```

after:
```
case CASE_A:
{
    /* Long
    * comment */}
    break;
```

before:
```
case CASE_A:{} break;
```

expected:
```
case CASE_A:
{
}
break;
```

after:
```
case CASE_A:
{}
break;
```

uncrustify config should influence this:
```
# Whether to collapse empty blocks between '{' and '}'.
nl_collapse_empty_body          = false    # false/true

# The number of newlines before a multi-line function def body.
nl_before_func_body_def         = 2        # unsigned number

# Whether to put a newline after brace open.
# This also adds a newline before the matching brace close.
nl_after_brace_open             = true    # false/true

# If True, it will move a 'break' that appears after a fully braced 'case' before the close brace.
mod_move_case_break             = false    # false/true
```

Version: Uncrustify-0.66.1
[uncrustify_conf.txt](https://github.com/uncrustify/uncrustify/files/1811200/uncrustify_conf.txt)

**Comment by guy-maurel** [comment]
You need to have a look on the option:
`mod_move_case_break`
If True, it will move a 'break' that appears after a fully braced 'case' before the close brace.

**Comment by Terik23** [comment]
In [uncrustify_conf.txt](https://github.com/uncrustify/uncrustify/files/1811200/uncrustify_conf.txt) set mod_move_case_break = false

**Comment by guy-maurel** [comment]
Current git sources produce:
```
Uncrustify_d-0.66.1-457-be0a6a7-dirty
Parsing: Terik23.cpp as language CPP
switch (a)
{
    case CASE_A:
    {
        /* Long
         * comment */
    }
    break;
}

switch (a)
{
    case CASE_A:
    {}
    break;
}
```
which is correct.
Your configuration file has an error at:
`pos_enum_comma = trail_froce`

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
