### ISSUE TITLE
regression for sp_arith + align_var_def_amp_style

### ISSUE THREAD

**Issue by bithium** [uncrustify/uncrustify#1675]
Using the configuration file:
```
sp_arith  = force    # ignore/add/remove/force
align_var_def_amp_style  = 1          # unsigned number
```

On the following code:
```
void ns::my_type::foobar(other &param)
{
    std::cout << param << std::endl;
}
```

Results in the following code:
```
void ns::my_type::foobar(other & param)
{
    std::cout << param << std::endl;
}
```
The expected output would be for the code to not change.

I have bisected the problem to commit 4cb6218.

Thank you.

**Comment by bithium** [comment]
Hello,

I have updated the comment above as I realized that the example did not express the proper situation, i.e. function definition. 

Thank you.

**Comment by gmaurel** [comment]
Fine

**Comment by CDanU** [comment]
Is this one fixed? I seems so but the reference is missing ...
