### ISSUE TITLE
./test_cli_options.py produces differents results

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1677]
Using the script from different directories produce different results.
Using:
```
<uncrustify_dir>./tests/cli/test_cli_options.py 
Uncrustify binary found: tests/cli/../../build/uncrustify
all tests are OK
```
Using:
```
cd tests/cli
./test_cli_options.py 
Uncrustify binary found: ../../build/uncrustify

Problem with results/mini_d_error0.txt
use: '--diff' to find out why results/mini_d_error0.txt output/mini_d_error.txt are different
```
(and some more ...)

**Comment by CDanU** [comment]
Yes there is a problem with one of the tests as it prints a path, that, depending from where you start the script, changes. 
I have to look if there is something that can be done about this. Is commit 1f923a7fae128c1980a043ce1aa791b3ba58d216 related to this?

**Comment by guy-maurel** [comment]
Yes
