### ISSUE TITLE
OC: Respect tab/space selection while indenting empty lines

### ISSUE THREAD

**Issue by Krizai** [uncrustify/uncrustify#1687]
Based on the comment https://github.com/uncrustify/uncrustify/commit/fa13566a9e5aff6fdd73ae98326d76080827c87d#comments

**Comment by guy-maurel** [comment]
Sorry, I don't anderstand.
Can you push an input example, the expected output and the configuration files

**Comment by Krizai** [comment]
The mentioned PR contains fix which indents empty lines. But it was noted in the comment it always indents them with spaces regardless of the tab/space configuration. It should respect the configuration and indent according to it.

**Comment by gmaurel** [comment]
PR #2213 is a bugfix proposal
