### ISSUE TITLE
Double space issues

### ISSUE THREAD

**Issue by 1951FDG** [uncrustify/uncrustify#169]
```objc
struct usave
{
	struct  timeval u_start;
};

ki->curpri  = ((struct policy_timeshare_info *)buf)->cur_priority;
```

Notice the double space between struct & timeval u_start as well as the double space between curpri & =.

I noticed there is "nl_max" but no "sp_max", consider "sp_max" a feature request.

**Comment by gmaurel** [comment]
The third example is solved.

**Comment by 1951FDG** [comment]
```objc
struct usave
{
	struct  timeval u_start;
};

ki->curpri  = ((struct policy_timeshare_info *)buf)->cur_priority;
```

Only the above example is solved.
