### ISSUE TITLE
Regression: Alignment of variables  broken when type is std::string&&

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#1691]
The following case used to work correctly, but no longer does so.
I would expect alignment to work the same irrespective of the type.

[debug.txt] https://pastebin.com/WWWkMeyx

Test case
```
#include <string>

std::string foo()
{
   return std::string{"abc"};
}
int main()
{
   const std::string&& name1 = foo();
   std::string&& name2 = foo();

   const auto&& name3 = foo();
   auto&& name4 = foo();
}

```
Generated result
```
#include <string>

std::string foo()
{
	return std::string{"abc"};
}
int main()
{
	const std::string&& name1 = foo();
	std::string&& name2 = foo();

	const auto&& name3 = foo();
	auto&&       name4 = foo();
}
```
Expected result
```
#include <string>

std::string foo()
{
	return std::string{"abc"};
}
int main()
{
	const std::string&& name1 = foo();
	std::string&&       name2 = foo();

	const auto&& name3 = foo();
	auto&&       name4 = foo();
}
```

Current version: Uncrustify-0.66.1-471-4db1877
Working version: Uncrustify-0.66.1-318-effb329

The regression was introduced in commit 8439fc7f2cc86911200aa581f438af21c9c07e8e

**Comment by guy-maurel** [comment]
I am looking for that.

**Comment by guy-maurel** [comment]
#1705 is a bugfix proposal. 
Sorry for removing #548

**Comment by arneforlie** [comment]
Thanks,
I have tested the patch and it works fine.
