### ISSUE TITLE
add option to align "break" with "case"

### ISSUE THREAD

**Issue by v01d** [uncrustify/uncrustify#1692]
I'm used to writing switch statements with "case" and "break" aligning to the same column, and I don't see a way to state this with uncrustify:

<pre>
switch (a)
{
  case 0:
    // code
  break;
}
</pre>

**Comment by AmokHuginnsson** [comment]
Yes! Please.
I wanted to request exactly the same feature.

**Comment by guy-maurel** [comment]
PR #2551 is a bugfix proposal.
Please test it and report.
