### ISSUE TITLE
Indent switch case with tabs

### ISSUE THREAD

**Issue by nxrighthere** [uncrustify/uncrustify#1695]
In places where I have
```
switch (netEvent.Type) {
case EventType.Connect: {
```
I want to make one tab to indent `case`, like this
```
switch (netEvent.Type) {
	case EventType.Connect: {
```
I found an `indent_switch_case` option, but it only makes spaces instead of tabs. Any workaround for this issue?

**Comment by gmaurel** [comment]
You have to choose over the source:
```
"indent_with_tabs=0|indent_with_tabs=1                 |indent_with_tabs=2"
"Spaces only       |Indent with tabs, align with spaces|Indent and align with tabs"
```

**Comment by nxrighthere** [comment]
@gmaurel Yea, I set `indent_with_tabs = 2`, but it still makes spaces instead of tabs.

**Comment by gmaurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
Please complete the command with the command option `uncrustify ... -o out.cpp`
With the configuration:
```
indent_with_tabs   = 2
indent_switch_case = 8
```
I get what you wish:
```
more out.cpp 
switch (netEvent.Type) {
        case EventType.Connect: {
        }
}
```

**Comment by nxrighthere** [comment]
Thank you! It works with `indent_switch_case = 8`.

**Comment by nxrighthere** [comment]
@gmaurel I just don't want to open a new issue and will just ask a few questions here, if you don't mind. 😺

Any idea how to make a newline between try/catch braces from this
```
private static string BytesToString(byte[] bytes) {
	try {
		return Encoding.ASCII.GetString(bytes, 0, Native.strlen(bytes));
	}
	catch {
		return null;
	}
}
```
to this
```
private static string BytesToString(byte[] bytes) {
	try {
		return Encoding.ASCII.GetString(bytes, 0, Native.strlen(bytes));
	}
	
	catch {
		return null;
	}
}
```
And, it's possible to remove blank spaces here
```
public bool Equals(Address address) {
	return Type == address.Type && Port == address.Port
	       && Native.memcmp(GetHostBytes(), address.GetHostBytes());
}
```
to make it look like this one-liner
```
public bool Equals(Address address) {
	return Type == address.Type && Port == address.Port && Native.memcmp(GetHostBytes(), address.GetHostBytes());
}
```

**Comment by CDanU** [comment]
There are no options that do what you want in the above examples.
For the first example there is `nl_brace_catch`, but that only adds one newline not multiple ones. 
The second example can be achieved with `pos_bool = join` but that is rather broadly scoped.

**Comment by nxrighthere** [comment]
@CDanU Thank you, it's better than nothing. 😺 

I'm also trying to find an option for removing newlines between variable members of a class. Any idea?

**Comment by CDanU** [comment]
Play around with the `nl_var_def_blk_*` options.

```sql
# The maximum consecutive newlines within a block of variable definitions
# 0 = No change (default).
nl_var_def_blk_in               = 1        # unsigned number
```

**Comment by nxrighthere** [comment]
Yea, I saw these options, but unfortunately, I can't achieve the desired behavior. Anyway, thanks for the help.
