### ISSUE TITLE
[Question] About spacing of the paren's inside

### ISSUE THREAD

**Issue by Dry8r3aD** [uncrustify/uncrustify#1701]
Hello :)

As I implement Uncrustify to my project, I noticed that there's variety of options(confs) for spacing of the paren's outside, such as...
> * sp_sizeof_paren : "sizeof (int)" vs "sizeof(int)"  
> * sp_func_call_paren : "foo (" vs "foo("

But I could not find variety of options(confs) for spacing of the paren's inside.
Such as...
* sizeof( A ) vs sizeof(A)
* (A) ? (A & foo( C )) : D vs ( A ) ? ( A & foo( C ) ) : D 

What I wanted to do is
* By default, spacing inside of the parens is forced.
* But as a exception, sizeof and some value assign should not be spaced.

Is there any way to do what I want, just like above in current Uncrusity version?
If not, is there a plan to support options(confs) like this in the future? 

I'm willing to develop this option if currently not supported but there's some need by Uncrusify's users. :)

**Comment by CDanU** [comment]
1. Should be handled by:
  ```sql
  # Add or remove space inside '(' and ')'.
  sp_inside_paren                 = force    # ignore/add/remove/force
  ```
2. Would need a new option, if you want you can submit a PR for that, look into https://github.com/uncrustify/uncrustify/blob/aea2e224f4f5c39b8d526e2a7e1cefb99bb6c5c9/src/space.cpp#L144
