### ISSUE TITLE
Increment and decrement operators spacing error

### ISSUE THREAD

**Issue by Dry8r3aD** [uncrustify/uncrustify#1704]
Hello again :)

I have some questions about inc. and dec. operators!

This is solved when I use paren. around the expression, like below.
```C
#define INC_REF_COUNT(ref_count) (++ref_count)
```
But I was wondering if there's any other way then this.
Strangly, only below this example is spaced, and other hundreds of lines with ind/dec operators in the project is not spaced. (weird..)

**Uncrusity information**
Link to Debug file : [debug_new.txt](https://github.com/uncrustify/uncrustify/files/1870718/debug_new.txt)
Link to Config : [uncrustify.txt](https://github.com/uncrustify/uncrustify/files/1870619/uncrustify.txt)
uncrustify version : Uncrustify-0.65_f

Original code
```C
#define INC_REF_COUNT(ref_count) ++ref_count
```

Expected code
```C
#define INC_REF_COUNT( ref_count ) ++ref_count
```

Output code
```C
#define INC_REF_COUNT( ref_count ) ++ ref_count
```

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by CDanU** [comment]
Yes, that's a bug.

**Comment by gmaurel** [comment]
PR #2448 is a bugfix proposal.
Please test it and report.

**Comment by Dry8r3aD** [comment]
I've tested, and looks like PR #2448 has solved this issue.
I'll close this issue.

Thank you @guy-maurel for summiting a PR!
