### ISSUE TITLE
Uncrustify won't output a debug file

### ISSUE THREAD

**Issue by dcommander** [uncrustify/uncrustify#1707]
What am I doing wrong?  I tried 0.66_f from MacPorts, as well as a custom build from the current Git master branch.

_To reproduce:_
Create **test.c**:
```
#include <stdio.h>

int main(void)
{
	printf("Hello, World!\n");
	return 0;
}
```

```
uncrustify --update-config -o default.cfg
uncrustify -p debug.txt -c default.cfg test.c
```

_Expected behavior:_
debug.txt is generated

_Actual behavior:_
No debug file is generated

**Comment by dcommander** [comment]
It seems that it works properly if I specify `-f test.c`, so that at least provides a workaround.  I still assert that this is a bug, however.

**Comment by CDanU** [comment]
Duplicate of: #930

**Comment by guy-maurel** [comment]
#930 is fixed.
Please test again and report
