### ISSUE TITLE
problems with formatting constuctor initalization list

### ISSUE THREAD

**Issue by gmaderecker** [uncrustify/uncrustify#1708]
I like to Format Code snippets like this (this should also be the result of formatting):

namespace de
{
    namespace gateway
    {

        Board::Board()
            :   statusLedRedPin     {GpioPort::_0, GpioPin::_25, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                statusLedGreenPin   {GpioPort::_0, GpioPin::_3,  GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                statusLedBluePin    {GpioPort::_1, GpioPin::_1,  GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                doorOpenSwitchPin   {GpioPort::_1, GpioPin::_3,  GpioDirection::input,  GpioPull::disabled, signal::Polarity::activeHigh},
                doorOpenStatusPin   {GpioPort::_0, GpioPin::_9,  GpioDirection::input,  GpioPull::disabled, signal::Polarity::activeHigh},
                mLockStatusLedPin   {{GpioPort::_0, GpioPin::_22, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                                    {GpioPort::_0, GpioPin::_23, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                                    {GpioPort::_0, GpioPin::_14, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                                    {GpioPort::_0, GpioPin::_12, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                                    {GpioPort::_0, GpioPin::_28, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                                    {GpioPort::_0, GpioPin::_27, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow}}
        { }
    }
}

What I get is:
namespace de
{
    namespace gateway
    {

        Board::Board()
            :   statusLedRedPin     {GpioPort::_0, GpioPin::_25, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                statusLedGreenPin   {GpioPort::_0, GpioPin::_3,  GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                statusLedBluePin    {GpioPort::_1, GpioPin::_1,  GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                doorOpenSwitchPin   {GpioPort::_1, GpioPin::_3,  GpioDirection::input,  GpioPull::disabled, signal::Polarity::activeHigh},
                doorOpenStatusPin   {GpioPort::_0, GpioPin::_9,  GpioDirection::input,  GpioPull::disabled, signal::Polarity::activeHigh},
                mLockStatusLedPin   {{
                GpioPort::_0, GpioPin::_22, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow
            },
                    {GpioPort::_0, GpioPin::_23, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                    {GpioPort::_0, GpioPin::_14, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                    {GpioPort::_0, GpioPin::_12, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                    {GpioPort::_0, GpioPin::_28, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
                    {GpioPort::_0, GpioPin::_27, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow}}
        { }
    }
}

It seems there is a problem with the double {{ before an array of objects is generated.
What can be the problem? I have tested the complete settings, but I found not the correct one to get the correct Output.

best regards,
Georg

**Comment by CDanU** [comment]
Post the  config file that you have used, with an empty config I get:
```cpp
namespace de
{
namespace gateway
{

Board::Board()
	:   statusLedRedPin     {GpioPort::_0, GpioPin::_25, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
	statusLedGreenPin   {GpioPort::_0, GpioPin::_3,  GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
	statusLedBluePin    {GpioPort::_1, GpioPin::_1,  GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
	doorOpenSwitchPin   {GpioPort::_1, GpioPin::_3,  GpioDirection::input,  GpioPull::disabled, signal::Polarity::activeHigh},
	doorOpenStatusPin   {GpioPort::_0, GpioPin::_9,  GpioDirection::input,  GpioPull::disabled, signal::Polarity::activeHigh},
	mLockStatusLedPin   {{GpioPort::_0, GpioPin::_22, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
	                     {GpioPort::_0, GpioPin::_23, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
	                     {GpioPort::_0, GpioPin::_14, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
	                     {GpioPort::_0, GpioPin::_12, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
	                     {GpioPort::_0, GpioPin::_28, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow},
	                     {GpioPort::_0, GpioPin::_27, GpioDirection::output, GpioPull::disabled, signal::Polarity::activeLow}}
{
}
}

}
```

**Comment by gmaderecker** [comment]
this is the config file I have used:
[uncrustify.zip](https://github.com/uncrustify/uncrustify/files/1883672/uncrustify.zip)

**Comment by gmaderecker** [comment]
Thank you for your feedback. It looks like it works.
Where can I find the master *.exe or must I build it by my own?

**Comment by CDanU** [comment]
We don't have public builds for the current master, you have to build it yourself.

**Comment by gmaurel** [comment]
Fine
