### ISSUE TITLE
How to achieve single line while statement with no newline before semicolon

### ISSUE THREAD

**Issue by 1951FDG** [uncrustify/uncrustify#171]
```objc
while (line == fgets(line, 256, fp))
;
```

Prefer this:

```objc
while (line == fgets(line, 256, fp));
```

**Comment by gmaurel** [comment]
Pleas use the new option
  nl_create_while_one_liner=true

with
  https://github.com/uncrustify/uncrustify
Please test it!

**Comment by 1951FDG** [comment]
Tested the option but adds a space between the `)` and `;`

`while (line == fgets(line, 256, fp)) ;`
