### ISSUE TITLE
regression in inlined asm management

### ISSUE THREAD

**Issue by vsiles** [uncrustify/uncrustify#1710]
version: Uncrustify-0.66.1-491-aea2e22
configuration: https://pastebin.com/S7KnChQE

Hi !
Starting from commit 043430593839ad6f46be886e4a6a99b76fee978d, I saw a diff in the management of asm volatile code:
```
    asm volatile ("vmrs    %[reg], fpexc @ Read FPEXC\n"
                  : [reg] "=r" (reg));
```
is now
```
    asm volatile ("vmrs    %[reg], fpexc @ Read FPEXC\n"
                  :[reg] "=r" (reg)); /* notice the deleted space between : and [
```

I don't think it was made on purpose so I'm thinking this is a regression. Is that the case ?

**Comment by guy-maurel** [comment]
The current git version gives:
```cpp
Uncrustify_d-0.66.1-498-b5bfc18-dirty
Parsing: vsiles.cpp as language CPP
asm volatile ("vmrs    %[reg], fpexc @ Read FPEXC\n"
              : [reg] "=r" (reg));
```
I cannot reproduce. Could you give more information?

**Comment by vsiles** [comment]
I'll try again on Tuesday, and with the current git to check if the issue is still there. I'll keep you posted, thanks !

**Comment by vsiles** [comment]
Hi !
With the current tip (be6a7c62f8fccbc603a743f680b1b7684d73adbc) the issue is no more. Do you want me to bissect to check when it was corrected ? Otherwise, feel free to close the issue, it is ok now :)

**Comment by gmaurel** [comment]
Fine.
