### ISSUE TITLE
[regression] Space before logical && removed.

### ISSUE THREAD

**Issue by AmokHuginnsson** [uncrustify/uncrustify#1713]
[debug.txt](https://github.com/uncrustify/uncrustify/files/1909811/debug.txt)
Test case:

```
int reset( void );

int main( int argc_, char** ) {
  int refCnt( 0 );
  refCnt && reset();
  return ( 0 );
}
```

Expected result: no change in contents
Actual result:
```
int reset( void );

int main( int argc_, char** ) {
  int refCnt( 0 );
  refCnt&& reset();
  return ( 0 );
}
```

Note space that is removed from before `&&` operator.

Tested with: Uncrustify-0.66.1-498-b5bfc18b
Version that worked: aea2e224
Version that is broken: 34c48336

**Comment by guy-maurel** [comment]
`refCnt && reset();` is a bool operation. What are you doing with the result?
Note that uncrustify doesn't know what is _refCnt_.

**Comment by AmokHuginnsson** [comment]
`refCnt && reset();` is just an equivalent of:
```
if ( refCnt ) {
  reset();
}
```

But I see that because of local function declarations this is an ambiguous syntax :-(
Am I right to be afraid that it is impossible for uncrustify to distinguish between the two?

**Comment by CDanU** [comment]
Yes, because of the way Uncrustify was implemented this sort of ambiguities can't be properly handled.

Generally the only two things you can to in such a cases is either to add comments that disable formatting:
<code>

```sql
# Override the default ' *INDENT-OFF*' in comments for disabling processing of part of the file.
disable_processing_cmt          = " *INDENT-OFF*"        # string

# Override the default ' *INDENT-ON*' in comments for enabling processing of part of the file.
enable_processing_cmt           = " *INDENT-ON*"        # string
```

</code>

or give Uncrustify hints about what a specific token is (set **TYPE** _refCnt_, does not work for this case).

**Comment by AmokHuginnsson** [comment]
I think I will just change the code in question on my side.
But in theory some future version of uncrustify could use libclang to actually know semantic meaning of each symbol. I wonder if it could make some of uncrustify's code simpler.

**Comment by CDanU** [comment]
We are thinking about integrating clang somehow, but still need to find out how and what clang exactly does.
As far as I know one of the drawback of clang and its tools is that it needs, up to a certain point, compilable code, right?. Having to have a build setup (with all the includes and libs) in place just to format random/unknown code makes things more complicated. 

From my point of view if we decide to integrate clang at some point we should use it as an additional option for the improved parsing.

**Comment by AmokHuginnsson** [comment]
I agree completely, clang based improvements must be opt-in for the user. Uncrustify might use dynamic loading (`dlopen()`) to use libclang not to introduce rather large dependencies.

**Comment by guy-maurel** [comment]
An idea from uncrustify is to get a code which is better to read and understand.
You define` int refCnt( 0 );` but use it as a bool. What about the other return values.
Better could be:
```cpp
if (refCnt == DO_RESET)
{
   ...
}
```
You define` int reset( void );`
but don't use the return values!

**Comment by AmokHuginnsson** [comment]
This code is trimmed down version of larger code.
I agree that I can rewrite it in unambiguous way.
Still, the actual code is perfectly valid and correct.
reset() return value is ignored in this case in particular, but is used in other call.

Using libclang to help uncrustify could be a good idea in general.
This issue can be closed though and maybe new feature request opened for libclang support.
