### ISSUE TITLE
Broken ternary not indented inside if/while/return.

### ISSUE THREAD

**Issue by AmokHuginnsson** [uncrustify/uncrustify#1715]
Test case:
```
void foo( bool a, int b, int c ) {
  int z = a
    ? b
    : c;
  if (
    a
      ? b
      : c
  ) {
  }
  return (
    a
      ? b
      : c
  );
}
```

Expected result: no change in contents.

Actual result:
```
void foo( bool a, int b, int c ) {
  int z = a
    ? b
    : c;
  if (
    a
    ? b
    : c
  ) {
  }
  return (
    a
    ? b
    : c
  );
}
```

Tested with: Uncrustify-0.66.1-498-b5bfc18b
[debug.txt](https://github.com/uncrustify/uncrustify/files/1909885/debug.txt)

**Comment by guy-maurel** [comment]
Please help me.
I don't anderstand what the if statement is doing.
Might be incomplete?
Push a compilable example.

**Comment by AmokHuginnsson** [comment]
To compile example from original report simply change `void foo` to `int foo`.
`if` statement has empty body because problem is not in the body but in the control clause of `if`.
The meaning of expression on control clause of `if` is as following:
if `a` is true use `b` as value tested by if, use `c` other wise.

**Comment by guy-maurel** [comment]
As `b` and `c` are `int`, you probably add `== 5`

**Comment by AmokHuginnsson** [comment]
It does not matter for the problem at hand.

**Comment by guy-maurel** [comment]
There is no way today to get what you wanted to get.

**Comment by samishchandra** [comment]
Fix at [PR 2662](https://github.com/uncrustify/uncrustify/pull/2662).
