### ISSUE TITLE
blank spaces are added between code and c++-style comments

### ISSUE THREAD

**Issue by rastersoft** [uncrustify/uncrustify#1716]
I'm using uncrustify to format my C and Vala code, and found a problem with C++-style comments: when they are put at the end of a line with code, each time I format the code, uncrustify adds new blank spaces between the end of the code and the start of the comment, so if I format the code several times, I end with dozens of blank spaces between the code and the comment itself, because each time the code is formatted, new blanks are added, no matter if there were already enough blanks.

Example:

original code:
```
    printf("A piece of code\n"); // this comment explains the printf
```
after first execution (blank spaces added):
```
    printf("A piece of code\n");     // this comment explains the printf
```
after second execution (blank spaces added):
```
    printf("A piece of code\n");         // this comment explains the printf
```
after third execution (more blank spaces added):
```
    printf("A piece of code\n");             // this comment explains the printf
```
after fourth execution (even more blank spaces added):
```
    printf("A piece of code\n");                 // this comment explains the printf
```
after fifth execution (and even more blanks spaces are added):
```
    printf("A piece of code\n");                     // this comment explains the printf
```
And so on.

How can I prevent this from happening?

I'm using uncrustify 0.66.1-f

**Comment by CDanU** [comment]
Post your config.

**Comment by rastersoft** [comment]
#
# My favorite format
#

newlines                = LF		# AUTO (default), CRLF, CR, or LF

indent_with_tabs			= 1		# 1=indent to level only, 2=indent with tabs
input_tab_size				= 8		# original tab size
output_tab_size			= 4		# new tab size
indent_columns				= output_tab_size
# indent_label				= 0		# pos: absolute col, neg: relative column
indent_align_string		= False		# align broken strings
indent_brace				= 0
indent_class				= true

nl_start_of_file			= remove
# nl_start_of_file_min	= 0
nl_end_of_file				= force
nl_end_of_file_min		= 1
nl_max						= 4
nl_before_block_comment	= 2
nl_after_func_body		= 2
nl_after_func_proto_group 	= 2

nl_assign_brace			= remove		# "= {" vs "= \n {"
nl_enum_brace				= remove		# "enum {" vs "enum \n {"
nl_union_brace				= remove		# "union {" vs "union \n {"
nl_struct_brace			= remove		# "struct {" vs "struct \n {"
nl_do_brace					= remove		# "do {" vs "do \n {"
nl_if_brace					= remove		# "if () {" vs "if () \n {"
nl_for_brace				= remove		# "for () {" vs "for () \n {"
nl_else_brace				= remove		# "else {" vs "else \n {"
nl_while_brace				= remove		# "while () {" vs "while () \n {"
nl_switch_brace			= remove		# "switch () {" vs "switch () \n {"
nl_func_var_def_blk		= 0
nl_before_case				= 1
nl_fcall_brace				= remove		# "foo() {" vs "foo()\n{"
nl_fdef_brace				= remove		# "int foo() {" vs "int foo()\n{"
nl_after_return			= TRUE
nl_brace_while				= remove
nl_brace_else				= remove
nl_squeeze_ifdef			= TRUE

pos_bool						= trail		# BOOL ops on trailing end

eat_blanks_before_close_brace	= TRUE
eat_blanks_after_open_brace	= TRUE


mod_paren_on_return		= ignore	# "return 1;" vs "return (1);"
mod_full_brace_if			= force		# "if (a) a--;" vs "if (a) { a--; }"
mod_full_brace_for		= force		# "for () a--;" vs "for () { a--; }"
mod_full_brace_do			= force		# "do a--; while ();" vs "do { a--; } while ();"
mod_full_brace_while		= force		# "while (a) a--;" vs "while (a) { a--; }"

sp_before_byref			= remove
sp_before_semi				= remove
sp_paren_paren				= remove	# space between (( and ))
sp_return_paren			= force	# "return (1);" vs "return(1);"
sp_sizeof_paren			= remove	# "sizeof (int)" vs "sizeof(int)"
sp_before_sparen			= force		# "if (" vs "if("
sp_after_sparen			= force		# "if () {" vs "if (){"
sp_after_cast				= force	# "(int) a" vs "(int)a"
sp_inside_braces			= force		# "{ 1 }" vs "{1}"
sp_inside_braces_struct	= force		# "{ 1 }" vs "{1}"
sp_inside_braces_enum	= force		# "{ 1 }" vs "{1}"
sp_inside_paren			= remove
sp_inside_fparen			= remove
sp_inside_sparen			= remove
sp_inside_square			= remove
#sp_type_func				= ignore
sp_assign					= force
sp_arith						= force
sp_bool						= force
sp_compare					= force
sp_assign					= force
sp_after_comma				= force
sp_func_def_paren			= remove	# "int foo (){" vs "int foo(){"
sp_func_call_paren		= remove	# "foo (" vs "foo("
sp_func_proto_paren		= remove	# "int foo ();" vs "int foo();"
sp_func_class_paren		= remove
sp_before_angle			= remove
sp_after_angle				= force
sp_inside_angle			= remove
sp_sparen_brace			= add
sp_fparen_brace			= add
sp_after_ptr_star		 	= remove
sp_before_ptr_star		= force
sp_between_ptr_star		= remove

align_with_tabs			= FALSE		# use tabs to align
align_on_tabstop			= FALSE		# align on tabstops
align_enum_equ_span		= 4
align_nl_cont				= TRUE
align_var_def_span		= 1
align_var_def_thresh		= 12
align_var_def_inline		= TRUE
align_var_def_star		= TRUE
align_var_def_colon		= TRUE
align_assign_span			= 1
align_assign_thresh		= 12
align_struct_init_span	= 3
align_var_struct_span	= 99
align_right_cmt_span		= 3
align_pp_define_span		= 3
align_pp_define_gap		= 4
align_number_right		= TRUE
align_typedef_span		= 5
align_typedef_gap			= 3

cmt_star_cont				= TRUE

indent_namespace        = true
indent_namespace_single_indent  = true
indent_namespace_level   = 1
nl_namespace_brace       = remove

**Comment by CDanU** [comment]
Ok thanks, now please delete that comment, I am posting your reduced config here:

**Comment by rastersoft** [comment]
Done.

**Comment by CDanU** [comment]
Hmm I can't reproduce that with the given short line ... post a bit more code.

**Comment by CDanU** [comment]
Its caused by a combination of:

```sql
# The original size of tabs in the input. Default=8.
input_tab_size                  = 8        # unsigned number

# The size of tabs in the output (only used if align_with_tabs=true). Default=8.
output_tab_size                 = 4        # unsigned number
```

To remove this issue either drop the `output_tab_size` setting or set input_tab_size also to 4. 

I will look up why this combination behaves that way later.

**Comment by rastersoft** [comment]
Thanks!
