### ISSUE TITLE
Alignment on = of destructor = default with other defaulted/deleted methods fails when parameter is named

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#1717]
I would have expected the following two class definitions to be formatted identically.
The only difference is that X14 has named the copy constructor parameter.
That causes the destructor's = to not align with the copy constructor's =.

Test Case
```
class X13
{
public:
~X13() = default;
X13(const X13&) = delete;
};


class X14
{
public:
~X14() = default;
X14(const X14& rhs) = delete;
};
```

Generated output:
```
class X13
{
public:
~X13()          = default;
X13(const X13&) = delete;
};


class X14
{
public:
~X14() = default;
X14(const X14& rhs) = delete;
};
```

Expected output
```
class X13
{
public:
~X13()          = default;
X13(const X13&) = delete;
};


class X14
{
public:
~X14()              = default;
X14(const X14& rhs) = delete;
};
```

[debug.txt](https://pastebin.com/Pi0e2Ahg)

Uncrustify-0.66.1-500-be6a7c6

**Comment by guy-maurel** [comment]
I am working on it

**Comment by guy-maurel** [comment]
#1721 is a bugfix proposal.
Please test it and report.

**Comment by gmaurel** [comment]
Fixed
