### ISSUE TITLE
Unrcustify freezes with preproccesor statements inside of switch

### ISSUE THREAD

**Issue by amelNetatmo** [uncrustify/uncrustify#1718]
Hi,
I have an issue with Uncrustify hanging on the check of a C file containing the following piece of code:

```
switch (code)
{
case A:
#ifdef XXX
	func(code);
#endif
	break;
}
```
I found that the problem was caused by the  option `indent_switch_pp` when it is set to `false`.
I am using the default configuration file with only the following change:
`indent_switch_pp                = false `

Current version: Uncrustify-0.66.1_f

**Comment by guy-maurel** [comment]
I am working on it.

**Comment by guy-maurel** [comment]
#1718 is a bugfix proposal.
Please test it and report.

**Comment by amelNetatmo** [comment]
Thanks @guy-maurel! It works, it doesn't freeze anymore! However, the option doesn't have any effect on the `#ifdef`indentation... I get no correction for the code above whatever `indent_switch_pp` value is.
