### ISSUE TITLE
Uncrustify VS Roslyn

### ISSUE THREAD

**Issue by nikitach2** [uncrustify/uncrustify#1725]
Hello. I am a developer and currently i'm looking for reliable formatter for c# source. I was thinking of using you software or Roslyn. Can you say what are benefits of using your software over Roslyn formatting features?

**Comment by CDanU** [comment]
I don't know what roslyn is, so you have to test both of them and report. 

It seems however that the roslyn project it is more comparable to libclang than to Uncrustify as it isn't specifically a source code formatter but an source code analysis tool.  You could build a formatter on top of that, so maybe there is something like that somewhere inside roslyn.

**Comment by mihaipopescu** [comment]
There is a Roslyn Formatter already build on top of that but I'm not entirely sure if it requires the code to be compilable.
