### ISSUE TITLE
Definition of conversion operator can get extra space after initial ::

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#1733]
When a C++ conversion operator is defined with global scoping, we get an unwanted space after the ::

Test case:
```
class X15
{
enum Enum
{
	e1
};

operator Enum();
};

::X15::operator ::X15::Enum()
{
	return e1;
}
```

Generated result
```
class X15
{
enum Enum
{
	e1
};

operator Enum();
};


::X15::operator :: X15::Enum()
{
	return e1;
}
```

I expected the output to be identical to the input. I.e. there should be no space after ::

Debug file: [debug.txt](https://github.com/uncrustify/uncrustify/files/1961640/debug.txt)

uncrustify -v
Uncrustify-0.66.1-515-a36a0e0

Note: We could instead defined the operator as (in which case the problem goes away)
```
::X15::operator Enum()
{
	return e1;
}
```
but the colleague that reported the issue to me was insistent on that there was no reason to change his code :-)

**Comment by guy-maurel** [comment]
PR #2228 is a bugfix proposal.
Please test it and report.
