### ISSUE TITLE
nl_after_func_body causes extra newlines after a function try block

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#1734]
A function try block is not handled identically by nl_after_func_body as a normal try block.
Consider the case:

Test case
```
class X16
{
public:
X16();
};

X16::X16()
try
{
}
catch (...)
{
}
```

Generated result:
```
class X16
{
public:
X16();
};

X16::X16()
try
{
}


catch (...)
{
}
```

I would expect the output to be identical to the input, because nl_after_func_body=3 should recognise that the try isn't a function body.

[debug.txt](https://github.com/uncrustify/uncrustify/files/1961773/debug.txt)

Uncrustify-0.66.1-515-a36a0e0

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by arneforlie** [comment]
Sorry, I can' see any change/improvement.
[debug.txt](https://github.com/uncrustify/uncrustify/files/3613565/debug.txt)

**Comment by guy-maurel** [comment]
I am missing some braces. Should it not be:
```.cpp
Uncrustify_d-0.69.0-202-32a055c2-dirty
class X16
{
public:
X16();
};

X16::X16()
{
        try
        {
        }
        catch (...)
        {
        }
}
```

**Comment by arneforlie** [comment]
No, this is a function try block,.
Ref. https://en.cppreference.com/w/cpp/language/function-try-block

**Comment by guy-maurel** [comment]
PR #2451 is a bugfix proposal.
Please test it and report.

**Comment by arneforlie** [comment]
Looks good!

**Comment by guy-maurel** [comment]
2. run. PR #2456

**Comment by arneforlie** [comment]
Closing this. It works to my satisfaction.
