### ISSUE TITLE
Uncrustify tools

### ISSUE THREAD

**Issue by nikitach2** [uncrustify/uncrustify#1735]
What tools uncrustify use for code analysis and formatting?

**Comment by mihaipopescu** [comment]
Can you elaborate your question?

**Comment by CDanU** [comment]
If you mean 3rd party libraries: None, currently Uncrustify does not use any. 
We do format the source code with Uncrustify itself. 
The only thing that we use to build Uncrustify that isn't part of the project itself are CMake and Python.
