### ISSUE TITLE
Automatic config finder

### ISSUE THREAD

**Issue by haferburg** [uncrustify/uncrustify#1736]
> highly configurable - 609 configurable options as of version 0.66.1

While it's good to have many options, it can also be a bit overwhelming. I like the approach of the "Universal Indent GUI", but in my opinion it's still a lot of work to find a configuration.

What I would very much like to have is a tool that can create a configuration file from code samples. The goal is to find a [minimal?] configuration file such that the samples are modified as little as possible.

Has anybody involved with the project thought about something like this? Does it already exist, maybe? If not, is it even feasible? How does one search in a space like that? 2^609 is already a lot, and many options aren't even binary. What kind of string metric would you use? How could one break down this problem? It probably would be good to know which options are interdependent, independent, or irrelevant, but how do you find this out?

**Comment by mihaipopescu** [comment]
As far as I understood, this is the goal of unformat project for which there is an open feature request to add support for uncrustify https://github.com/johnmcfarlane/unformat/issues/21 (initially investigated by the author). The project is using machine learning to crunch a search space of that size.

Our [option reducer script](https://github.com/uncrustify/uncrustify/blob/master/scripts/option_reducer.py) is sightly similar but it has a different goal. In a way it's similar as it's trying to find the minimum set of options that successfully reproduce an issue but the search space is limited as we already know what configs we are dealing with and what are their values (provided config for the test). I can let @CDanU explain the algorithm but it's interesting to see different approaches around a "similar" kind of problem.

**Comment by guy-maurel** [comment]
You can use the command option
 _--detect                 : Detects the config from a source file. Use with '-f FILE'.
                            Detection is fairly limited._

**Comment by guy-maurel** [comment]
The number **2^609** is not correct because some options may have 4 values, and some other options have a number as values... which made a bigger space!
One of the goals of uncrustify is to give you (and all other users) all the freedom you wanted to have to formate your sources as you whish.

**Comment by haferburg** [comment]
@guy-maurel So it does exists! Thanks for the pointer.

For the purpose of finding a config it might not be necessary to search the entire space of possibilities. If two options don't influence each other, one could check all possibilities for the first option, choose the best one, then all possibilities for the second option, and again, choose the best one. For example, I believe `nl_func_call_args_multi_line` and `nl_func_call_end_multi_line` are independent of each other (searching 4+4 possibilities is ok), but `nl_after_brace_open_cmt` depends on `nl_after_brace_open` (must search 2*2 possibilities). So the relevant space for searching is probably a lot smaller than my original estimate.

This issue here is a duplicate, by the way: https://github.com/uncrustify/uncrustify/issues/694
