### ISSUE TITLE
unexpected colon in col 22 n-parent=NONE c-parent=C_CAST l=1 bl=1

### ISSUE THREAD

**Issue by Sam-Tygier** [uncrustify/uncrustify#1737]
Uncrustify gives "unexpected colon" warning on the following code:

```
template<class T>
class foo 
{
public:
	T x;
	foo<T>(int a): x(a) {}
};

int main()
{
	foo<double> a = 6;
	return a.x;
}
```
Removing the `<T>` from the constructor removes the warning. I don't think the `<T>` is needed in this case, but I think its is still valid C++, neither gcc or clang give a warning or error.

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 

[debug.txt](https://pastebin.com/se1Put8S)

[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

I get this with Uncrustify 0.64_d and 0.66.1_f

**Comment by guy-maurel** [comment]
What is the meaning of the colon?
Where to you find it is still valid?

**Comment by guy-maurel** [comment]
PR #2241 is a bugfix proposal.
Please test it and report.
