### ISSUE TITLE
Plans for 0.67 milestone

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1740]
Hey guys,

Do you have any plans for the upcoming 0.67 release? Is there any critical issue you really want to fix before the release or you will just take latest master and release that?

For better visibility I guess we could start using Github Projects tab https://blog.github.com/2016-09-14-a-whole-new-github-universe-announcing-new-tools-forums-and-features/#manage-your-ideas-with-projects.

Thanks,
Mihai

**Comment by mihaipopescu** [comment]
I think this issue is about figuring out what work needs to be done before a release like this one https://github.com/uncrustify/uncrustify/pull/1415

**Comment by guy-maurel** [comment]
About mid-end of may

**Comment by mihaipopescu** [comment]
related PR #1744

**Comment by arneforlie** [comment]
I'm a bit confused about the state of 0.67.
I can see that it has been tagged, and it is available under releases. But I also note that some 0.67-related changes were commited yesterday, and consequently not included in 0.67 tag (or tar ball).
Is the currently tagged commit a kind of release candidate?

**Comment by guy-maurel** [comment]
You should not be confused with my work!
The change(s) after the tagging are little changes about the (little) problem(s)
I had to push the release.
Thanks for commenting.

**Comment by mihaipopescu** [comment]
Also https://sourceforge.net/projects/uncrustify/files/uncrustify/uncrustify-0.67/ is empty. Are you still going to publish there the release files?I still think this process should be done automatically and you should not do it manually. Even publishing to sourceforge can be done from a script that can run on specific action.

Releasing a new version should be as simple as you pushing a new tag on master.

**Comment by guy-maurel** [comment]
No more. Thanks for the message.

**Comment by guy-maurel** [comment]
As one need an admin login I prefer to do it manually

**Comment by mihaipopescu** [comment]
So are you discontinuing sourceforge releases?

**Comment by mihaipopescu** [comment]
Oh, I misunderstood your message. I saw you uploaded them, nice! 👍
