### ISSUE TITLE
Building CXX object CMakeFiles/uncrustify.dir/src/align.cpp.o FAILS?

### ISSUE THREAD

**Issue by migithub15** [uncrustify/uncrustify#1741]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Hi, I'm building this for my engs I tried the the simple instructions but it fails with lots of errors?

Please see below, any idea why it's failing please? Is this due to Unknown version control system? That's odd we do have git and svn?

-- scripts/make_version.py exited with code 64: Unknown version control system in '/tools/icad/src/uncrustify/0.66.1'.

which git svn
/usr/bin/git
/custom/tools/apps/release6/bin/svn

git version 1.7.1
svn, version 1.6.2 (r37639)

Thanks!
Mohammed.

cmake ../
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CXXFLAG_Wall
-- Performing Test CXXFLAG_Wall - Success
-- Performing Test CXXFLAG_Wextra
-- Performing Test CXXFLAG_Wextra - Success
-- Performing Test CXXFLAG_Wshadow
-- Performing Test CXXFLAG_Wshadow - Success
-- Performing Test CXXFLAG_Wpointer_arith
-- Performing Test CXXFLAG_Wpointer_arith - Success
-- Performing Test CXXFLAG_Wcast_qual
-- Performing Test CXXFLAG_Wcast_qual - Success
-- Performing Test CXXFLAG_Wcast_align
-- Performing Test CXXFLAG_Wcast_align - Success
-- Performing Test CXXFLAG_Wc_11_extensions
-- Performing Test CXXFLAG_Wc_11_extensions - Failed
-- Looking for C++ include inttypes.h
-- Looking for C++ include inttypes.h - found
-- Looking for C++ include memory.h
-- Looking for C++ include memory.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include stdlib.h
-- Looking for C++ include stdlib.h - found
-- Looking for C++ include strings.h
-- Looking for C++ include strings.h - found
-- Looking for C++ include string.h
-- Looking for C++ include string.h - found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - found
-- Looking for C++ include utime.h
-- Looking for C++ include utime.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Looking for memset
-- Looking for memset - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strchr
-- Looking for strchr - not found
-- Looking for strdup
-- Looking for strdup - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strtol
-- Looking for strtol - found
-- Looking for strtoul
-- Looking for strtoul - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of _Bool
-- Check size of _Bool - done
-- Found PythonInterp: /custom/tools/lang/release6/python3.6.5/bin/python (found version "3.6.5")
-- scripts/make_version.py exited with code 64: Unknown version control system in '/tools/icad/src/uncrustify/0.66.1'.

As a fallback, version 'Uncrustify-0.66.1_f' will be used.
-- Configuring done
-- Generating done
-- Build files have been written to: /tools/icad/src/uncrustify/0.66.1/build

make
[  2%] Generating token_names.h
Scanning dependencies of target uncrustify
[  4%] Building CXX object CMakeFiles/uncrustify.dir/src/align.cpp.o
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_stack(ChunkStack&, size_t, bool, log_sev_t)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:308: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_add(ChunkStack&, chunk_t*, size_t&, size_t, bool)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:327: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void quick_align_again()':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:372: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_all()':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:446: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:456: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_oc_msg_spec(size_t)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:513: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_backslash_newline()':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:532: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_right_comments()':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:548: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:590: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_struct_initializers()':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:608: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_preprocessor()':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:637: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'chunk_t* align_assign(chunk_t*, size_t, size_t, size_t*)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:708: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:730: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:833: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'chunk_t* align_func_param(chunk_t*)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:874: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_func_params()':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:923: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_params(chunk_t*, std::deque<chunk_t*, std::allocator<chunk_t*> >&)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:949: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_same_func_call_params()':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:979: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:998: error: expected initializer before ':' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1002: error: could not convert 'fcn_as.AlignStack::NewLines(pc->chunk_t::nl_count)' to 'bool'
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1003: error: expected primary-expression before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1003: error: expected ')' before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1003: error: expected primary-expression before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1003: error: expected ';' before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1013: error: expected initializer before ':' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1018: error: expected primary-expression before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1018: error: expected ')' before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1018: error: expected primary-expression before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1018: error: expected ';' before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1078: error: expected initializer before ':' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1083: error: expected primary-expression before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1083: error: expected ')' before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1083: error: expected primary-expression before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1083: error: expected ';' before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1131: error: expected initializer before ':' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1135: error: expected primary-expression before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1135: error: expected ';' before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1135: error: expected primary-expression before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1135: error: expected ')' before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1135: error: expected primary-expression before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1135: error: expected ';' before '}' token
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'chunk_t* step_back_over_member(chunk_t*)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1144: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_func_proto(size_t)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1173: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'chunk_t* align_var_def_brace(chunk_t*, size_t, size_t*)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1215: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1246: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1288: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'chunk_t* align_nl_cont(chunk_t*)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1489: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1502: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'comment_align_e get_comment_align_type(chunk_t*)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1518: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'chunk_t* align_trailing_comments(chunk_t*)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1553: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'chunk_t* skip_c99_array(chunk_t*)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1635: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'chunk_t* scan_ib_line(chunk_t*, bool)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1643: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_init_brace(chunk_t*)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1773: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_typedefs(size_t)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1941: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_left_shift()':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:1980: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_oc_msg_colon(chunk_t*)':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:2102: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:2141: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_oc_msg_colons()':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:2203: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_oc_decl_colon()':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:2225: error: 'nullptr' was not declared in this scope
/tools/icad/src/uncrustify/0.66.1/src/align.cpp: In function 'void align_asm_colon()':
/tools/icad/src/uncrustify/0.66.1/src/align.cpp:2294: error: 'nullptr' was not declared in this scope
make[2]: *** [CMakeFiles/uncrustify.dir/src/align.cpp.o] Error 1
make[1]: *** [CMakeFiles/uncrustify.dir/all] Error 2
make: *** [all] Error 2

**Comment by guy-maurel** [comment]
Have a look to:
http://en.cppreference.com/w/cpp/language/nullptr
we can see:
nullptr |   | (since C++11)
which compiler do you have?
Please use the VERBOSE option with the ccmake command to see
the complete compile command (push only the first edrror)

**Comment by mihaipopescu** [comment]
Maybe cmake should check for C++11 support of the compiler? https://stackoverflow.com/questions/10984442/how-to-detect-c11-support-of-a-compiler-with-cmake

**Comment by migithub15** [comment]
Hi, thanks for the email. Default picked up by cmake is:

-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works

I have gcc version 6.3.0 in my $PATH but cmake refuse to use it unlike configure/ make, how can I get cmake use. Sorry, in EDA not s/w expert and cmake works so differently to good old configure. Thanks!

**Comment by guy-maurel** [comment]
Please, use the command` ccmake ..`
There, type **t** to show all the options.
Choose the options to change the compiler, scrolling down you find: `CMAKE_CXX_COMPILER`
Type "RETURN" to be able to edit. Type "RETURN" again to exit.
Choose `CMAKE_VERBOSE_MAKEFILE` and change to "ON" to get more info.
Use "c" to configure again and "g", to generate.
You may also use an editor to make the changes directly in the file _CMakeCache.txt_
Let it run and push important parts of the output.

**Comment by guy-maurel** [comment]
I push my
[CMakeCache.txt](https://github.com/uncrustify/uncrustify/files/1995943/CMakeCache.txt)
Try to see what is different and report.
