### ISSUE TITLE
ls_func_split_full doesn't work for splitting at comma in function prototype

### ISSUE THREAD

**Issue by igor-sadchenko** [uncrustify/uncrustify#1742]
Function prototype is being splitted between type and argument name instead of being splitted at comma while using option _ls_func_split_full_

Config: [a.cfg](https://github.com/igor-sadchenko/uncrustify-issues/blob/master/a.cfg)
Source: [a.cpp](https://github.com/igor-sadchenko/uncrustify-issues/blob/master/a.cpp)
Result : [a.cpp.uncrustify](https://github.com/igor-sadchenko/uncrustify-issues/blob/master/a.cpp.uncrustify)
Debug: [debug.txt](https://github.com/igor-sadchenko/uncrustify-issues/blob/master/debug.txt)
Version: Uncrustify-0.66.1-491-aea2e224

**Comment by guy-maurel** [comment]
The option **ls_code_width** is used (in the code) first.
If set, your next option **ls_func_split_full** is never used.

**Comment by guy-maurel** [comment]
PR #2234 is a bugfix proposal.
Please test it and report.
