### ISSUE TITLE
assignment in wrapped expression not working (Or I don't understand it)

### ISSUE THREAD

**Issue by mentaal** [uncrustify/uncrustify#1743]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

I am trying to prevent assignments being broken at the assignment operator. 
I have tried this option but it doesn't seem to help:

    # The position of assignment in wrapped expressions.
    # Do not affect '=' followed by '{'.
    pos_assign                      = join   # ignore/join/lead/lead_break/lead_force/trail/trail_break/trail_force

Related stackoverflow question:  https://stackoverflow.com/questions/50269331/uncrustify-function-call-break-at-assignment

Config: [uncrustify.cfg.txt](https://github.com/uncrustify/uncrustify/files/1995388/uncrustify.cfg.txt)
Source: 
[uncrustify_issue.c.txt](https://github.com/uncrustify/uncrustify/files/1995398/uncrustify_issue.c.txt)
Result: 
[uncrustify_output.c.txt](https://github.com/uncrustify/uncrustify/files/1995406/uncrustify_output.c.txt)
Version: Uncrustify-0.66.1

**Comment by guy-maurel** [comment]
The list of used options is:
```.cfg
indent_columns                  = 4
indent_with_tabs                = 0
code_width                      = 100
cmt_star_cont                   = true
cmt_sp_after_star_cont          = 1
```
mod_remove_extra_semicolon      = true
the option **code_width** makes the splitting here.
