### ISSUE TITLE
make of 0.59 version has errors on Ubuntu 16.04

### ISSUE THREAD

**Issue by coppered** [uncrustify/uncrustify#1747]
Here is a log of configure and then make command for version 0.59 

uncrustify-0.59$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... none
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... none
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking utime.h usability... yes
checking utime.h presence... yes
checking for utime.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for working memcmp... yes
checking for memset... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strtol... yes
checking for strtoul... yes
checking whether our compiler supports __func__... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating man/Makefile
config.status: creating man/uncrustify.1
config.status: creating src/uncrustify_version.h
config.status: creating src/config.h
config.status: executing depfiles commands

uncrustify-0.59$ make
Making all in src
make[1]: Entering directory '/home/me/Uncrustify/uncrustify-0.59/src'
make  all-am
make[2]: Entering directory '/home/me/Uncrustify/uncrustify-0.59/src'
  CXX    uncrustify-uncrustify.o
uncrustify.cpp: In function ‘bool file_content_matches(const string&, const string&)’:
uncrustify.cpp:891:16: error: ‘close’ was not declared in this scope
       close(fd1);
                ^
uncrustify.cpp:899:45: error: ‘read’ was not declared in this scope
          len1 = read(fd1, buf1, sizeof(buf1));
                                             ^
uncrustify.cpp:903:45: error: ‘read’ was not declared in this scope
          len2 = read(fd2, buf2, sizeof(buf2));
                                             ^
uncrustify.cpp:918:13: error: ‘close’ was not declared in this scope
    close(fd1);
             ^
uncrustify.cpp: In function ‘void do_source_file(const char*, const char*, const char*, bool, bool)’:
uncrustify.cpp:1034:46: error: ‘unlink’ was not declared in this scope
             (void)unlink(filename_tmp.c_str());
                                              ^
Makefile:326: recipe for target 'uncrustify-uncrustify.o' failed
make[2]: *** [uncrustify-uncrustify.o] Error 1
make[2]: Leaving directory '/home/me/Uncrustify/uncrustify-0.59/src'
Makefile:217: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/me/Uncrustify/uncrustify-0.59/src'
Makefile:307: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

the version of gcc

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.5.0-12ubuntu1~16.04' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1~16.04)

**Comment by coppered** [comment]
can be resolved by adding
#include <unistd.h>   /* For open(), creat() */
to ./src/uncrustify.cpp

**Comment by guy-maurel** [comment]
Better is to use the current git version: 0.66.1 at:
  https://github.com/uncrustify/uncrustify
and report. Thanks

**Comment by guy-maurel** [comment]
Better is to use the current git version: 0.66.1 at:
  https://github.com/uncrustify/uncrustify
and report. Thanks
