### ISSUE TITLE
Configuration to place space between ) and { doesn't work

### ISSUE THREAD

**Issue by dkbarto** [uncrustify/uncrustify#1748]
Or at least I can't figure out the configuration option to make it work.
I am getting:
if (test){
I would like to see
if (test) {
The options for parens are set to add (or force, I tried both) a space between ) and { (sp_paren_brace) and it doesn't appear to be working.

Any assistance? I expect it is a problem with my setup, not something inherent in the code.
Using uncrustify-66.1_f

     David

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by CDanU** [comment]
That should be the default, if there isn't a space printer after the ) some option in your config is causing this. 
Check `sp_after_sparen` or `sp_sparen_brace` and post your config.

**Comment by dkbarto** [comment]
Thanks, that did the trick.
