### ISSUE TITLE
Fatal: Negative value (while parsing dlmalloc.cpp)

### ISSUE THREAD

**Issue by dkbarto** [uncrustify/uncrustify#1749]
Using the call_Uncrustify.cfg file I got the error
FATAL: negative value.
   pc->orig_col=0 prev->orig_col_end=68

Using Uncrustify-0.66.1-523-b8166fee

generated with: "uncrustify -f dlmalloc.cpp -c call_Uncrustify.cfg -o /tmp/dlmalloc.cpp"

I tried to use "-p debug.txt" but that file never got created.

[call_Uncrustify.cfg.zip](https://github.com/uncrustify/uncrustify/files/2009660/call_Uncrustify.cfg.zip)
[dlmalloc.cpp.zip](https://github.com/uncrustify/uncrustify/files/2009658/dlmalloc.cpp.zip)

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by gmaurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by dkbarto** [comment]
1533_ indent -U dlmalloc.cpp
Indenting one file dlmalloc.cpp.cpp
Parsing: dlmalloc.cpp.cpp as language CPP
FATAL: negative value.
   pc->orig_col=0 prev->orig_col_end=68
Formatted  /Users/barto/CSI/ubsan/source/utils/dlmalloc.cpp
1534_ uncrustify --version
Uncrustify-0.68-202-ed3d58b7
[dlmalloc.cpp.gz](https://github.com/uncrustify/uncrustify/files/2974414/dlmalloc.cpp.gz)
[call_Uncrustify.cfg.gz](https://github.com/uncrustify/uncrustify/files/2974416/call_Uncrustify.cfg.gz)

**Comment by guy-maurel** [comment]
uncrustify cannot deal correctly with preprocessor and braces.
Please change your code a little bit to:
```.cpp
#ifdef __cplusplus
extern "C" { 
LONG __cdecl _InterlockedCompareExchange(LONG volatile *Dest, LONG Exchange, LONG Comp);
LONG __cdecl _InterlockedExchange(LONG volatile *Target, LONG Value);
}
#else
LONG __cdecl _InterlockedCompareExchange(LONG volatile *Dest, LONG Exchange, LONG Comp);
LONG __cdecl _InterlockedExchange(LONG volatile *Target, LONG Value);
#endif /* __cplusplus */
```
