### ISSUE TITLE
Not able to Format macro bodies where backslashes are followed by spaces

### ISSUE THREAD

**Issue by Prasanth-kusumaraju** [uncrustify/uncrustify#1752]
Auto fix bad macro continuations to white space.
Input:
---
```
#define WARN_IF(EXP) \ 
        do { if (EXP) \ 
        fprintf (stderr, "Warning: " #EXP "\n"); } \
```
Here in the above input  ' \ ' is followed by a 'space' hence the next token is identified wrongly.

Output:
---
```
#define WARN_IF(EXP) \ 
do { if (EXP) \ 
fprintf (stderr, "Warning: " #EXP "\n"); } \
```
Expected Output
---
```
#define WARN_IF(EXP) \
        do { if (EXP) \
        fprintf (stderr, "Warning: " #EXP "\n"); } \

```

**Comment by Prasanth-kusumaraju** [comment]
In unity fork this issue is addressed with below PR
Unity-Technologies#132

**Comment by guy-maurel** [comment]
#1754 is a bugfix adopted from UT

**Comment by gmaurel** [comment]
Fixed
Thanks to Prasanth-kusumaraju
