### ISSUE TITLE
Misidentification of '*' in ternary expression

### ISSUE THREAD

**Issue by Sam-Tygier** [uncrustify/uncrustify#1753]
`sp_arith = add` is not applied correctly to the `*` on the last line. All the others are fine. 

```void a()
{
	a = c*d();
	a = b?c+d:e;
	a = b?c*d:e;
	a = b?c+d():e;
	a = b?c*d():e;
}
```
Giving:

```void a()
{
	a = c * d();
	a = b ? c + d : e;
	a = b ? c * d : e;
	a = b ? c + d() : e;
	a = b ? c*d() : e;
}
```

[debug.txt](https://pastebin.com/WvG75LYt)

This happens with Uncrustify 0.64_d and 0.66.1_f.

From the debug, comparing the 4 and 5th expersions, it looks like where the '+' is identified as a `ARITH` the '*' is identified as a FUNC_PROTO.

**Comment by guy-maurel** [comment]
PR #2233 is a bugfix proposal.
Please test it and report.
