### ISSUE TITLE
Uncrustify failed to detect braced blocks

### ISSUE THREAD

**Issue by sgarnotel** [uncrustify/uncrustify#1758]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

When I use uncrustify in such a loop, containing a bradec block, it remove the braces of the for loop (it detects it as a one line for loop)

```
for(int f=0; f<(Element::nf)*2; f++)
{
	if (f%2==1) {p = p-1;}
	{
	this->pInterpolation[i]=p;
	this->cInterpolation[i]=0.;
	this->dofInterpolation[i]=e+f;
	this->coefInterpolation[i]=1.;
	i++;
	p++;
	}
}
```

EDIT: this bug does not appear if:
```
# Add or remove braces on single-line 'for' statement.
mod_full_brace_for              = force   # ignore/add/remove/force
```

**Comment by guy-maurel** [comment]
Please push your config and the output you expect to get with.

**Comment by sgarnotel** [comment]
The configuration file can be found [here](https://github.com/FreeFem/FreeFem-sources/blob/079f9e7dcff7c8f82c9d7cab6fbac0575e22367d/tools/.uncrusify).

I expect to get:
```
for (int f = 0; f < (Element::nf)*2; f++) {
	if (f%2 ==1 ) {p = p-1;}
	{
		this->pInterpolation[i] = p;
		this->cInterpolation[i] = 0.;
		this->dofInterpolation[i] = e + f;
		this->coefInterpolation[i] = 1.;
		i++;
		p++;
	}
}
```
But I obtain:
```
for (int f = 0; f < (Element::nf)*2; f++)
	if (f%2 ==1 ) {p = p-1;}
{
	this->pInterpolation[i] = p;
	this->cInterpolation[i] = 0.;
	this->dofInterpolation[i] = e + f;
	this->coefInterpolation[i] = 1.;
	i++;
	p++;
}
```

**Comment by guy-maurel** [comment]
NO. I obtain:
```.cpp
for (int f = 0; f < (Element::nf)*2; f++)
        if (f % 2 == 1) p = p - 1;

        {
                this->pInterpolation[i] = p;
                this->cInterpolation[i] = 0.;
                this->dofInterpolation[i] = e + f;
                this->coefInterpolation[i] = 1.;
                i++;
                p++;
        }
```
Have a look to the if: the braces are removed also.

**Comment by sgarnotel** [comment]
I do not.
I clean some old files in a larger code. Clearly, there is no reason to open a new block here.

**Comment by guy-maurel** [comment]
The new statements block is yet not recognize --> this look like a single statement --> remove the braces.
As workaround for just now, you can add any new statement, such as 
```.cpp
   int a = 1;
```
to get the bount bigger as 1.

**Comment by guy-maurel** [comment]
#1758 is a bugfix proposal.
Please test and report.

**Comment by guy-maurel** [comment]
Fixed
