### ISSUE TITLE
Objective C nl_after_brace_close = true causes two new lines after the block's close brace inside a function

### ISSUE THREAD

**Issue by m2orris** [uncrustify/uncrustify#176]
The following code:

```
- (void) foo {
    someFunction(^{
        NSLog(@"something inside block");
    });
}
```
uncrustifies as:

```
- (void)foo
{
    someFunction ( ^{
        NSLog(@"something inside block");
    }

                   );
}
```

instead of:

```
- (void) foo {
    someFunction(^{
        NSLog(@"something inside block");
    });
}
```

There are two issues:
1) The double new line after the block's closing brace.
2) The space between ```someFunction``` and ```(``` . Note if there is an argument, like ```bar``` before the the block (i.e. ```someFunction(bar, ^{...```),  there is no space.  This might be a config I have set improperly.

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
