### ISSUE TITLE
option align_assign_span = 1 considers = 0 to indicate pure virtual to be an assignment

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#1760]
Uncrustify 0.67 and option align_assign_span = 1 mistakingly considers "= 0" used to indicate pure virtual, to be an assignment. This causes unwanted alignment with = used to give a default value.

This behaviour started with commit a36a0e0. I.e. 9e3d8db was OK.

[debug.txt](https://github.com/uncrustify/uncrustify/files/2042651/debug.txt)

Test case
```
class X16
{
public:
virtual void f(int x, int y) = 0;
void g(int x = 0);
};
```
Generated:
```
class X16
{
public:
virtual void f(int x, int y) = 0;
void g(int x                 = 0);
};
```
Expected is identical to input.

**Comment by arneforlie** [comment]
I tried a few other cases, and found that the behaviour depends on no. of parameters to function f(). So an improved test case is:
```
class X16
{
public:
virtual void f() = 0;
void g(int x = 0);
};

class X17
{
public:
virtual void f(int x) = 0;
void g(int x = 0);
};

class X18
{
public:
virtual void f(int x, int y) = 0;
void g(int x = 0);
};
```

Generated result with commit a36a0e0 (I consider all three cases to be bad here)
```
class X16
{
public:
virtual void f() = 0;
void g(int x     = 0);
};

class X17
{
public:
virtual void f(int x) = 0;
void g(int x          = 0);
};

class X18
{
public:
virtual void f(int x, int y) = 0;
void g(int x                 = 0);
};
```

Generated result with commit 9e3d8db (here only X17 is bad)
```
class X16
{
public:
virtual void f() = 0;
void g(int x = 0);
};

class X17
{
public:
virtual void f(int x) = 0;
void g(int x          = 0);
};

class X18
{
public:
virtual void f(int x, int y) = 0;
void g(int x = 0);
};
```

I did a bit of bisecting, and the problem with X17 was introduced in commit e8afec5.

Generated result with commit 80bfbd5 (here all cases are as expected)
```
class X16
{
public:
virtual void f() = 0;
void g(int x = 0);
};

class X17
{
public:
virtual void f(int x) = 0;
void g(int x = 0);
};

class X18
{
public:
virtual void f(int x, int y) = 0;
void g(int x = 0);
};
```

**Comment by guy-maurel** [comment]
I am working on it.
The information we have within uncrustify are just now not suffisant to solve the bug.
I will introduce something such as "Block Number" to control if two (or more) assignments
are / are not in the same block. Please, wait a little.

**Comment by guy-maurel** [comment]
#1841 is a bugfix proposal.
Please test and report.

**Comment by arneforlie** [comment]
It looks good. Thanks.

**Comment by arneforlie** [comment]
Following discussion in PR #1841 I add the following test case which shows that = default and = delete suffer from the same problem.
```
class X19
{
public:
X19();
~X19() = default;
X19(const X19& rhs) = default;
X19& operator=(const X19& rhs) = default;
X19(X19&& rhs) = delete;
X19& operator=(X19&& rhs) = delete;
virtual void f(int x, int y) = 0;
void g(int x = 0);
};
```
is formatted as:
```
class X19
{
public:
X19();
~X19()                         = default;
X19(const X19& rhs)            = default;
X19& operator=(const X19& rhs) = default;
X19(X19&& rhs)                 = delete;
X19& operator=(X19&& rhs)      = delete;
virtual void f(int x, int y)   = 0;
void g(int x                   = 0);
};
```

**Comment by arneforlie** [comment]
The functionally is OK, so you may close.

However, the new option's description uses the term indent for value = 1 and 2, shouldn't that have been align?
````
# Defines how align_assign_span is applied onto function decl. with: virtual ... = 0, = delete, = default.
# 0 - default align_assign_span behavior
# 1 - indent the '=' on their own, with each other
# 2 - don't indent
align_assign_decl_func          = 1        # unsigned number
```

**Comment by CDanU** [comment]
Yes you right, I'll make a PR for that.
