### ISSUE TITLE
Cannot build under win

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1762]
can anybody help at the error:
https://ci.appveyor.com/project/gmaurel/uncrustify/build/1578
Thanks

**Comment by CDanU** [comment]
> Creating "uncrustify.dir\Release\uncrustify.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
> CustomBuild:
>   Generating punctuator_table.h
>   
>   Process failed because: %1 is not a valid Win32 application
>   
>   for command: ../scripts/punc.py 1> punctuator_table.h
>   Generating token_names.h
> 

I guess Windows does not know what to do with your .py file ... try calling python itself  in order to exec the script.

**Comment by guy-maurel** [comment]
A new test raises problem with redirect.
What is wrong?
```.log
...
InitializeBuildStatus:
  Creating "uncrustify.dir\Debug\uncrustify.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Generating punctuator_table.h
  /**
   * @file punctuator_table.h
```
The output doesn't go to the file.

**Comment by guy-maurel** [comment]
I only need to use **OUTPUT_FILE**
