### ISSUE TITLE
alignas c++ keyword not supported?

### ISSUE THREAD

**Issue by edwinchenloo** [uncrustify/uncrustify#1764]
I'm attaching my uncrustify.cfg with some trivial alignment settings.  

Using the fairly recent version: Uncrustify-0.67-34-b8c67e3-dirty

I can't get the 'alignas' variables to be aligned properly in my class definition:

`
class Buffer
{

    public:
        Buffer( const Buffer& )                                 = delete;
        Buffer&                     operator =( const Buffer& ) = delete;
        SetSegment                      _setSegment;
        std::atomic_uint_fast32_t       _uSegmentNotEmpty{ 0 };
        alignas( 64 ) Segment* _pRead                           = nullptr;
        size_t                          _uRead      = 0;
        int                             _nValid1    = 12345678;
        alignas( 64 ) Segment* _pWrite                          = nullptr;
        size_t                          _uWrite     = 0;
        int                             _nValid2    = 12345678;
        const char                      _cThreadId;
        const uint32_t                  _uId;
        bool                            _bQueueable = true;

    };
`
[test.zip](https://github.com/uncrustify/uncrustify/files/2046004/test.zip)

In a way the 'alignas( 64 )' ought to be treated the same as the 'const' modifier when declaring a member variable.

**Comment by CDanU** [comment]
Its not inside the [keywords.cpp](https://github.com/uncrustify/uncrustify/blob/master/src/keywords.cpp), so it is not supported yet.

**Comment by guy-maurel** [comment]
Please push what you expect to get

**Comment by edwinchenloo** [comment]
```
class Buffer
{
public:
    Buffer( const Buffer& )                                 = delete;
    Buffer&                     operator =( const Buffer& ) = delete;
    SetSegment                  _setSegment;
    std::atomic_uint_fast32_t   _uSegmentNotEmpty{ 0 };
    alignas( 64 ) Segment*      _pRead                      = nullptr;
    size_t                      _uRead                      = 0;
    int                         _nValid1                    = 12345678;
    alignas( 64 ) Segment*      _pWrite                     = nullptr;
    size_t                      _uWrite                     = 0;
    int                         _nValid2                    = 12345678;
    const char                  _cThreadId;
    const uint32_t              _uId;
    bool                        _bQueueable                 = true;
};
```

**Comment by bertwesarg** [comment]
please reopen, there is the expected output now

**Comment by edwinchenloo** [comment]
i don't have permission to reopen.
