### ISSUE TITLE
Bad indent on struct member declarations

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#1781]
Okay, this one I just don't get. Given the input:

```c++
struct foo
{
  void none( int const& x )
  { return; }
};

class bar
{
  void none( int const& x )
  { return; }
};
```

...uncrustify produces:

```c++
struct foo
{
 void none( int const& x )
  { return; }
};

class bar
{
  void none( int const& x )
  { return; }
};
```

Note the difference in indentation of `void none`.

Grammatically, there is *no* difference between the two, but for some reason, uncrustify wants to mess up the indent on the `struct`, but not the `class`. (I am, in fact, quite surprised that uncrustify makes an internal distinction between `struct` and `class`, given that they are grammatically identical and the only semantic distinction between the two is default access protection.)

[debug.txt](https://github.com/uncrustify/uncrustify/files/2081985/debug.txt)

Is there some option to control this that I am just not seeing?

**Comment by guy-maurel** [comment]
Because you are using:
`indent_var_def_blk              = 2`

**Comment by mwoehlke-kitware** [comment]
How does that result in something indented by *one* space? And why does it make a difference that it is a `struct` vs. a `class`? (TBH, I am... concerned that `struct` and `class` are handled differently for C++ code. That just seems wrong.)

**Comment by mwoehlke-kitware** [comment]
Hrmm... okay, I finally figured out the "only one space" issue... because positive values indent *to an absolute column*, i.e. `1` effectively means "no indent". (IOW, I wanted `indent_var_def_blk = -2`.)

I still think this happening in struct and not class is fishy, though. (Turns out it happens in function bodies, also...)

**Comment by mwoehlke-kitware** [comment]
> I wanted indent_var_def_blk = -2

Nope, that didn't work either. I'm beginning to think that either that option is broken, or I really, really don't understand what it's supposed to do (in which case, I suppose at least the doc could use work)...

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
