### ISSUE TITLE
Poor handling of parameter packs

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#1783]
Uncrustify doesn't seem to understand parameter packs. Consider this code:

```c++
template < typename A..., int B... >
struct foo : bar< A..., ( sizeof...(A) + B )... >;
```

...which gets mangled into:

```c++
template < typename A..., int B... >
struct foo : bar< A..., ( sizeof ... (A) +B ) ... >;
```

([debug.txt](https://github.com/uncrustify/uncrustify/files/2085035/debug.txt))

There are two definite problems here, and one possible problem. The most obvious is that `sizeof...` is not recognized as a single entity. I believe this is the cause of the undesired space added between `sizeof...` and the `(`, as well as between `sizeof` and `...`. (I suppose there "should" be an option whether or not to add space for the latter; personally, I don't want it.) The second is that space is undesirably added before the `...` which represents pack expansion; this should either have its own separate option or else be treated like any other postfix operator.

The *possible* issue is the space being removed before `B` in the second line. According to the debug output, this is being considered `POS`, which I guess means 'the unary `+` operator', where in actuality it is the binary addition operator (i.e. should be an `ARITH`). I mention this as "possible" because I suspect this only occurs because `(A)` is not being recognized as a function call, i.e. if `sizeof...` was being recognized as the same as `sizeof`, this would not happen. (A test with `sizeof...` replaced by `sizeof` seems to support this conclusion.)

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by mwoehlke-kitware** [comment]
Taking a sledgehammer approach to part of the issues here:

```diff
diff --git a/src/options.cpp b/src/options.cpp
index 9188cbea..636c8f0a 100644
--- a/src/options.cpp
+++ b/src/options.cpp
@@ -477,6 +477,8 @@ void register_options(void)
                   "Add or remove space between an open paren and comma: '(,' vs '( ,'. Default=Force.");
    unc_add_option("sp_before_ellipsis", UO_sp_before_ellipsis, AT_IARF,
                   "Add or remove space before the variadic '...' when preceded by a non-punctuator.");
+   unc_add_option("sp_paren_ellipsis", UO_sp_paren_ellipsis, AT_IARF,
+                  "Add or remove space before ')' and '...'.");
    unc_add_option("sp_after_class_colon", UO_sp_after_class_colon, AT_IARF,
                   "Add or remove space after class ':'.");
    unc_add_option("sp_before_class_colon", UO_sp_before_class_colon, AT_IARF,
@@ -501,6 +503,8 @@ void register_options(void)
                   "Add or remove space between the type and open paren in a C++ cast, i.e. 'int(exp)' vs 'int (exp)'.");
    unc_add_option("sp_sizeof_paren", UO_sp_sizeof_paren, AT_IARF,
                   "Add or remove space between 'sizeof' and '('.");
+   unc_add_option("sp_sizeof_ellipsis", UO_sp_sizeof_ellipsis, AT_IARF,
+                  "Add or remove space between 'sizeof' and '...'.");
    unc_add_option("sp_after_tag", UO_sp_after_tag, AT_IARF,
                   "Add or remove space after the tag keyword (Pawn).");
    unc_add_option("sp_inside_braces_enum", UO_sp_inside_braces_enum, AT_IARF,
diff --git a/src/options.h b/src/options.h
index 2ece57e8..7d068537 100644
--- a/src/options.h
+++ b/src/options.h
@@ -227,6 +227,7 @@ enum uncrustify_options
    UO_sp_between_mdatype_commas,    //
    UO_sp_paren_comma,               //
    UO_sp_before_ellipsis,           // space before '...'
+   UO_sp_paren_ellipsis,            // space between ')' and '...'
    UO_sp_after_class_colon,         // space after class ':'
    UO_sp_before_class_colon,        // space before class ':'
    UO_sp_after_constr_colon,        // space after class constructor ':'
@@ -239,6 +240,7 @@ enum uncrustify_options
    UO_sp_inside_paren_cast,         // spaces inside the parens of a cast
    UO_sp_cpp_cast_paren,            //
    UO_sp_sizeof_paren,              // space between 'sizeof' and '('
+   UO_sp_sizeof_ellipsis,           // space between 'sizeof' and '...'
    UO_sp_after_tag,                 // pawn: space after a tag colon
    UO_sp_inside_braces_enum,        // space inside enum '{' and '}' - '{ a, b, c }'
    UO_sp_inside_braces_struct,      // space inside struct/union '{' and '}'
diff --git a/src/space.cpp b/src/space.cpp
index 011af1f4..b0111de8 100644
--- a/src/space.cpp
+++ b/src/space.cpp
@@ -471,6 +471,11 @@ static argval_t do_space(chunk_t *first, chunk_t *second, int &min_sp)
          log_rule("sp_sizeof_paren");
          return(cpd.settings[UO_sp_sizeof_paren].a);
       }
+      if (chunk_is_token(second, CT_ELLIPSIS))
+      {
+         log_rule("sp_sizeof_ellipsis");
+         return(cpd.settings[UO_sp_sizeof_ellipsis].a);
+      }
       log_rule("FORCE");
       return(AV_FORCE);
    }
@@ -615,6 +620,13 @@ static argval_t do_space(chunk_t *first, chunk_t *second, int &min_sp)
          return(cpd.settings[UO_sp_before_ellipsis].a);
       }
 
+      if (  chunk_is_token(first, CT_FPAREN_CLOSE)
+         || chunk_is_token(first, CT_PAREN_CLOSE))
+      {
+         log_rule("sp_paren_ellipsis");
+         return(cpd.settings[UO_sp_paren_ellipsis].a);
+      }
+
       if (chunk_is_token(first, CT_TAG_COLON))
       {
          log_rule("FORCE");
```

This fixes the second issue and adds an option that is possibly desired anyway for the first. However, it does not address that a `(` following `sizeof...` needs to have the same class and context as if it followed `sizeof`, which I imagine is more involved.

Does this seem at all like a reasonable approach? If so, what else do I need to do in order to add new options?

**Comment by guy-maurel** [comment]
No, it is not a sledgehammer.
Please make a pull request on your proposal.
