### ISSUE TITLE
Uncrustify mishandles consecutive open braces

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#1786]
Consider the following code:

```c++
foo bar = { { 1, 2, 3 } };
```

Uncrustify incorrectly applies `sp_type_brace_init_lst` between the `{`s. (Tracking this down was not helped by the lack of a `log_rule` for `sp_type_brace_init_lst`!)

Here is a proposed fix:

```diff
diff --git a/src/space.cpp b/src/space.cpp
index 011af1f4..937dca7a 100644
--- a/src/space.cpp
+++ b/src/space.cpp
@@ -1161,9 +1161,12 @@ static argval_t do_space(chunk_t *first, chunk_t *second, int &min_sp)
       return(cpd.settings[UO_sp_inside_braces_empty].a);
    }
 
-   if (chunk_is_token(second, CT_BRACE_OPEN) && second->parent_type == CT_BRACED_INIT_LIST)
+   if ( !chunk_is_token(first, CT_BRACE_OPEN)
+      && chunk_is_token(second, CT_BRACE_OPEN)
+      && second->parent_type == CT_BRACED_INIT_LIST)
    {
       // 'int{9}' vs 'int {9}'
+      log_rule("sp_type_brace_init_lst");
       return(cpd.settings[UO_sp_type_brace_init_lst].a);
    }
 
```

(What's the best way to set up a test case for this? I am sort of thinking to copy `type_brace_init_lst.cpp` and recycle the configs for that, but I'm not sure how to number the resulting tests...)

**Comment by mwoehlke-kitware** [comment]
This suggests a related question: is it desirable to allow `{{` with no space when otherwise adding spaces inside of braces? Can uncrustify even do so without major changes? Is it even *sane* to try to apply such a rule? (My code currently uses `{{` with no space for explicit initializer lists with elided type name, but considering the possible overlap between this and a list of initializer lists, I'm not entirely convinced that supporting this isn't outrageously difficult or even just plain wrong, in which case I'm pretty sure I can live with adding a space.)

**Comment by CDanU** [comment]
@mwoehlke-kitware thanks for your recent activities. Regarding the tests: besides that the numbers should be unique inside a test file there are no real rules. You can pretty much do whatever you like to do. 

I personally like to get tests that are already preformatted by uncrustify with a empty config file in order to see only changes that are done because of new options when I diff input and output files.
Also it would be really great to get a minimal set of config options in the tests. Unleass you really need to only include the option that you are testing.

**Comment by mwoehlke-kitware** [comment]
I just pushed a *partial* fix, with test cases, to my fork. Unfortunately, cases like `func({{args}})` are still broken. This is because in code like `std::vector<int> x = {{1}};`, or even `func(type{{args}})`, the first brace has parent `BRACED_INIT_LIST`, but in the broken cases, it has parent `NONE`. As this is broken somewhere in the bowels of parsing, and not in how the spacing rules are applied, I have not thus far figured out how to correct it.

I probably won't be able to do any more digging for at least a few days, so if someone else wants to build on the code I already committed, please feel free to do so!

Note: 4/6 of the test cases in my branch currently fail, because the expected output is what the output *should* be with this other glitch fixed. Thus, the tests I added should also suffice to test a fix for this remaining issue.
