### ISSUE TITLE
Function macros not handled as function

### ISSUE THREAD

**Issue by Josar** [uncrustify/uncrustify#1787]
Uncrustify is configured to set the open bracket for functions in a new line. 
But unfortunatly this does not account for macros.

Is there a configuration to get uncrustify to format following code to the below?
```
#ifdef TIMER_1_ISRC
ISR(TIMER_1_ISRC, ISR_BLOCK){
    _isr(1, 2);
}
#endif  /* TIMER_1_ISRC */
```

```
#ifdef TIMER_1_ISRC
ISR(TIMER_1_ISRC, ISR_BLOCK)
{
    _isr(1, 2);
}
#endif  /* TIMER_1_ISRC */
```

**Comment by Josar** [comment]
Thank you @mwoehlke-kitware. I think this achieves what i tried to get.

```
set FUNC_DEF ISR   # Define ISR as function
```

It's a macro which expands to a function prototype in an other file.
Is it posible to set a list after `FUNC_DEF ` or do i have to define each key word (macro) in a seperated define line?

**Comment by mihaipopescu** [comment]
Try `PROTO_WRAP`

**Comment by mwoehlke-kitware** [comment]
> Is it posible to set a list after `FUNC_DEF`?

According to the doc:

```
# - Token(s) can be treated as specific type(s) with the 'set' option:
#     `set tokenType tokenString [tokenString...]`
#
#     Example:
#       `set BOOL __AND__ __OR__`
```

...so, yes, apparently.

**Comment by Josar** [comment]
Thank you @mwoehlke-kitware and @mihaipopescu .

**Comment by Josar** [comment]
Is it possible to use wildcard tokens, did not find it in the doc?

Then the special case could be extended using token like like set `PROTO_WRAP *ISR`? This way it will also cover `UART_X_ISR`, `TIMER_X_ISR`.

Or is the list the only solution for that?

**Comment by CDanU** [comment]
> Is it possible to use wildcard tokens
No, we don't have any wildcard support.

**Comment by Josar** [comment]
Thank you @CDanU for that information.
