### ISSUE TITLE
Support for OSX

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1788]
Uncrustify compiles fine under OSX but it _would be nice_ to add it to our travis test matrix.
See https://docs.travis-ci.com/user/reference/osx/ how to do it.

**Comment by mihaipopescu** [comment]
A bit offtopic:

I'm unsure if we can provide OSX binaries in our releases (due to Xcode license requirement for signed apps) but maybe we can convince travis to upload the artifacts in github releases which is the way we should do it not from @guy-maurel's machine.

In any case, there is a [brew](https://brew.sh) formula for uncrustify so Mac users are happy. Maybe we should provide a [chocolatey](https://chocolatey.org/search?q=uncrustify) one to make Windows users happy as well.

**Comment by guy-maurel** [comment]
It would be fine. Please make a change proposal for it.

**Comment by guy-maurel** [comment]
Could you close it?
