### ISSUE TITLE
Master branch build causes a stack dump

### ISSUE THREAD

**Issue by kaiser101** [uncrustify/uncrustify#1789]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

When I build using the latest master branch it causes a stack dump as follows

assertion "ARRAY_SIZE(token_names) == CT_TOKEN_COUNT_" failed: file "/d/uncrusti
fy/src/uncrustify.cpp", line 412, function: int main(int, char**)
      2 [main] uncrustify 1448 cygwin_exception::open_stackdumpfile: Dumping sta
ck trace to uncrustify.exe.stackdump

**Comment by kaiser101** [comment]
Yes I am building it using cmake as instructed.

**Comment by mihaipopescu** [comment]
Is cygwin a personal preference or a must? Cmake compiles uncrustify perfectly fine as a native Windows app through Visual Studio solution generators. I'm unsure how it behaves under that environment. Cygwin gave me a lot of headaches in the past and I try to avoid it (because of the dependencies on its dlls). You can try use MSYS (mingw32) if you want to build uncrustify even if uncrustify doesn't depend on POSIX headers or libraries.

The error comes from a code generation part of the cmake build, where we generate the token names from an enum by doing some string operations (eg. CT_STRING => "STRING") which is used in debug logs.

Now I'm not sure what went wrong but maybe you can debug. Also, make sure the token_names.h was properly generated and it's in the right location.

What does `which cmake` tells you under cygwin? Maybe it gets confused about multiple installations.

**Comment by kaiser101** [comment]
Hi Mihail, I am not using Cygwin. I am using MSYS (mingw32). The following is the output of my build process.

$ cmake ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
CMake Warning at /usr/share/cmake-3.10.2/Modules/Platform/MSYS.cmake:15 (message                                                                                                                ):
  CMake no longer defines WIN32 on MSYS!

  (1) If you are just trying to build this project, ignore this warning or
  quiet it by setting CMAKE_LEGACY_CYGWIN_WIN32=0 in your environment or in
  the CMake cache.  If later configuration or build errors occur then this
  project may have been written under the assumption that MSYS is WIN32.  In
  that case, set CMAKE_LEGACY_CYGWIN_WIN32=1 instead.

  (2) If you are developing this project, add the line

    set(CMAKE_LEGACY_CYGWIN_WIN32 0) # Remove when CMake >= 2.8.4 is required

  at the top of your top-level CMakeLists.txt file or set the minimum
  required version of CMake to 2.8.4 or higher.  Then teach your project to
  build on Cygwin without WIN32.
Call Stack (most recent call first):
  /usr/share/cmake-3.10.2/Modules/CMakeSystemSpecificInformation.cmake:27 (inclu                                                                                                                de)
  CMakeLists.txt:3 (project)


-- Check for working C compiler: /usr/bin/cc.exe
-- Check for working C compiler: /usr/bin/cc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CXXFLAG_Wall
-- Performing Test CXXFLAG_Wall - Success
-- Performing Test CXXFLAG_Wextra
-- Performing Test CXXFLAG_Wextra - Success
-- Performing Test CXXFLAG_Wshadow
-- Performing Test CXXFLAG_Wshadow - Success
-- Performing Test CXXFLAG_Wpointer_arith
-- Performing Test CXXFLAG_Wpointer_arith - Success
-- Performing Test CXXFLAG_Wcast_qual
-- Performing Test CXXFLAG_Wcast_qual - Success
-- Performing Test CXXFLAG_Wcast_align
-- Performing Test CXXFLAG_Wcast_align - Success
-- Performing Test CXXFLAG_Wc_11_extensions
-- Performing Test CXXFLAG_Wc_11_extensions - Failed
-- Looking for C++ include inttypes.h
-- Looking for C++ include inttypes.h - found
-- Looking for C++ include memory.h
-- Looking for C++ include memory.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include stdlib.h
-- Looking for C++ include stdlib.h - found
-- Looking for C++ include strings.h
-- Looking for C++ include strings.h - found
-- Looking for C++ include string.h
-- Looking for C++ include string.h - found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - found
-- Looking for C++ include utime.h
-- Looking for C++ include utime.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Looking for memset
-- Looking for memset - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strchr
-- Looking for strchr - found
-- Looking for strdup
-- Looking for strdup - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strtol
-- Looking for strtol - found
-- Looking for strtoul
-- Looking for strtoul - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of _Bool
-- Check size of _Bool - done
-- Found PythonInterp: /usr/bin/python2.7.exe (found version "2.7.13")
-- scripts/make_version.py exited with code 74: Failed to retrieve version from                                                                                                                 git

As a fallback, version 'Uncrustify-0.67_f' will be used.
-- Configuring done
-- Generating done
-- Build files have been written to: /d/uncrustify/build

Gargi@Gargi-PC MSYS /d/uncrustify/build
$ cmake --build .
[  2%] Generating token_names.h
[  4%] Generating punctuator_table.h
Scanning dependencies of target uncrustify
[  6%] Building CXX object CMakeFiles/uncrustify.dir/src/align.cpp.o
[  9%] Building CXX object CMakeFiles/uncrustify.dir/src/align_stack.cpp.o
[ 11%] Building CXX object CMakeFiles/uncrustify.dir/src/args.cpp.o
[ 13%] Building CXX object CMakeFiles/uncrustify.dir/src/backup.cpp.o
[ 16%] Building CXX object CMakeFiles/uncrustify.dir/src/braces.cpp.o
[ 18%] Building CXX object CMakeFiles/uncrustify.dir/src/brace_cleanup.cpp.o
[ 20%] Building CXX object CMakeFiles/uncrustify.dir/src/ChunkStack.cpp.o
[ 23%] Building CXX object CMakeFiles/uncrustify.dir/src/chunk_list.cpp.o
[ 25%] Building CXX object CMakeFiles/uncrustify.dir/src/combine.cpp.o
[ 27%] Building CXX object CMakeFiles/uncrustify.dir/src/compat_posix.cpp.o
[ 30%] Building CXX object CMakeFiles/uncrustify.dir/src/compat_win32.cpp.o
[ 32%] Building CXX object CMakeFiles/uncrustify.dir/src/defines.cpp.o
[ 34%] Building CXX object CMakeFiles/uncrustify.dir/src/detect.cpp.o
[ 37%] Building CXX object CMakeFiles/uncrustify.dir/src/helper_for_print.cpp.o
[ 39%] Building CXX object CMakeFiles/uncrustify.dir/src/indent.cpp.o
[ 41%] Building CXX object CMakeFiles/uncrustify.dir/src/keywords.cpp.o
[ 44%] Building CXX object CMakeFiles/uncrustify.dir/src/lang_pawn.cpp.o
[ 46%] Building CXX object CMakeFiles/uncrustify.dir/src/language_tools.cpp.o
[ 48%] Building CXX object CMakeFiles/uncrustify.dir/src/logger.cpp.o
[ 51%] Building CXX object CMakeFiles/uncrustify.dir/src/logmask.cpp.o
[ 53%] Building CXX object CMakeFiles/uncrustify.dir/src/md5.cpp.o
[ 55%] Building CXX object CMakeFiles/uncrustify.dir/src/newlines.cpp.o
[ 58%] Building CXX object CMakeFiles/uncrustify.dir/src/options.cpp.o
[ 60%] Building CXX object CMakeFiles/uncrustify.dir/src/options_for_QT.cpp.o
[ 62%] Building CXX object CMakeFiles/uncrustify.dir/src/output.cpp.o
[ 65%] Building CXX object CMakeFiles/uncrustify.dir/src/parens.cpp.o
[ 67%] Building CXX object CMakeFiles/uncrustify.dir/src/frame_list.cpp.o
[ 69%] Building CXX object CMakeFiles/uncrustify.dir/src/ParseFrame.cpp.o
[ 72%] Building CXX object CMakeFiles/uncrustify.dir/src/punctuators.cpp.o
[ 74%] Building CXX object CMakeFiles/uncrustify.dir/src/semicolons.cpp.o
[ 76%] Building CXX object CMakeFiles/uncrustify.dir/src/sorting.cpp.o
[ 79%] Building CXX object CMakeFiles/uncrustify.dir/src/space.cpp.o
[ 81%] Building CXX object CMakeFiles/uncrustify.dir/src/tokenize.cpp.o
[ 83%] Building CXX object CMakeFiles/uncrustify.dir/src/tokenize_cleanup.cpp.o
[ 86%] Building CXX object CMakeFiles/uncrustify.dir/src/uncrustify.cpp.o
[ 88%] Building CXX object CMakeFiles/uncrustify.dir/src/unc_text.cpp.o
[ 90%] Building CXX object CMakeFiles/uncrustify.dir/src/unc_tools.cpp.o
[ 93%] Building CXX object CMakeFiles/uncrustify.dir/src/unicode.cpp.o
[ 95%] Building CXX object CMakeFiles/uncrustify.dir/src/universalindentgui.cpp.                                                                                                                o
[ 97%] Building CXX object CMakeFiles/uncrustify.dir/src/width.cpp.o
[100%] Linking CXX executable uncrustify.exe
[100%] Built target uncrustify

**Comment by mihaipopescu** [comment]
I have no experience building uncrustify under such environments, maybe @gmaurel has some pointers but it looks like cmake gets somehow confused (it thinks it's msys but then complains something about cygwin and the exe crashes with a cygwin exception).

Have you tried with a more recent version of cmake?

**Comment by gmaurel** [comment]
You can modify the code and add a statement like:
```.cpp
fprintf(stderr, "%s(%d): ARRAY_SIZE(token_names) is %d\n",
           __func__, __LINE__, ARRAY_SIZE(token_names));
```
do see what is hapening, and report.

**Comment by kaiser101** [comment]
Hi Guy,

I commented out the assert and added the line you suggested. Then I ran the command using uncrustify -c uncrustify.cfg -p debug.txt --replace SavingsInvestingParticipantDataFileItemReader.java

I got the following on the console.
main(413): ARRAY_SIZE(token_names) is 280
Parsing: \Sudharma\SavingsInvestingParticipantDataFileItemReader.java as language JAVA

**Comment by guy-maurel** [comment]
What is the value of `CT_TOKEN_COUNT_` ?

**Comment by mihaipopescu** [comment]
@kaiser101 Can you find any of the older versions of mercurial (you can try them by tags) that compile fine under cygwin? I saw some related commits but it's nowhere we make it clear that we support this environment.

@gmaurel if we want, then we need to ensure that in appveyor as it has cygwin installed https://www.appveyor.com/docs/build-environment/#mingw-msys-cygwin as well as msys. Maybe need to ensure we can build in these environments or just to know if/when they fail.

**Comment by kaiser101** [comment]
@gmaurel The values are as follows
main(413): ARRAY_SIZE(token_names) is 280
main(415): CT_TOKEN_COUNT_ is 292
Parsing: \Sudharma\SavingsInvestingParticipantDataFileItemReader.java as language JAVA

@mihaipopescu I am not using Cygwin. I installed a fresh copy of mingw yesterday. I am building it using mingw32 and msys.

**Comment by kaiser101** [comment]
Hi @gmaurel 
I have uploaded my config and the file I am trying to uncrustify.

[SavingsInvestingParticipantDataFileItemReader.txt](https://github.com/uncrustify/uncrustify/files/2090469/SavingsInvestingParticipantDataFileItemReader.txt)
[uncrustify.txt](https://github.com/uncrustify/uncrustify/files/2090472/uncrustify.txt)

**Comment by guy-maurel** [comment]
We must first anderstand why the two values 280 and 292 are produced.

**Comment by guy-maurel** [comment]
Please insert the code:
```.cpp
   // Issue #1789
   if (ARRAY_SIZE(token_names) != CT_TOKEN_COUNT_)
   {
      for (size_t token = 0; token < ARRAY_SIZE(token_names); token++)
      {
         fprintf(stdout, "1789: token_names[%3zu]: %s\n",
                 token, token_names[token]);
      }          
      log_flush(true);
      exit(EX_SOFTWARE);
   }

   // make sure we have token_names.h in sync with token_enum.h
```
Run uncrustify by redirecting the output to a file.
Report and attach the file.

**Comment by kaiser101** [comment]
Hi @gmaurel 

Need some help out here. I am not really a c++ developer, so you need to tell me exactly where to insert these lines.

Also by redirecting output to a file you mean to run it with the -p debug.txt flag right. When I do that however no file is generated. Is there any additional flag or setting I need to add?

**Comment by mihaipopescu** [comment]
The lines can be inserted right before the assert that is causing the problem:

```
   // make sure we have token_names.h in sync with token_enum.h
   assert(ARRAY_SIZE(token_names) == CT_TOKEN_COUNT_);
```

Also, you need to use the `-f` arg when using the `-p` (see recent PR https://github.com/uncrustify/uncrustify/pull/1798)

**Comment by kaiser101** [comment]
[debug.txt](https://github.com/uncrustify/uncrustify/files/2098908/debug.txt)

**Comment by guy-maurel** [comment]
Fine. I look after...

**Comment by kaiser101** [comment]
Thanks @gmaurel

**Comment by guy-maurel** [comment]
You probably have the file `token_names.h` at the old directory <uncrustify_dir>/src
This is no more correct.
Remove the file, let `cmake` run again to create the new one at the right place:
`<uncrustify_dir>/build/token_names.h`
and `make` again. Please report.

**Comment by mihaipopescu** [comment]
I think Guy is right. Clean your repo and do a clean build in another folder.
