### ISSUE TITLE
Bad indentation of C# verbatim strings

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1795]
With the adoption of a change from our fork https://github.com/uncrustify/uncrustify/commit/b26b7205f47ea9b04de35525eecfe953863410ed a new issue was introduced.

We wanted to have multiline C# verbatim strings indented to column 1 but apparently, it looks like that it's happening also for those that are *not multiline*. This is not ok as it was not indented and we consider it to be a bug.

Basically, in addition to the specified commit, we would like this snippet to suffer no changes after it has been formatted with the same config.

```cs
namespace Namespace
{
    class Class
    {
       private static string Foo
        {
            get
            {
                return string.Join("\r\n", new[]
                {
                    @"Line1",
                    @"Line2"
                }
            }
        }
    }
}
```

**Comment by guy-maurel** [comment]
PR #2242 is a bugfix proposal.
Please test it and report.
