### ISSUE TITLE
Test c-sharp_12004 is failing on Debian for various big-endian architectures

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1817]
Issue received by mail from an unknown developer.

> Uploaded new version into archive and got errors on powerpc64, s390x, sparc64
> https://buildd.debian.org/status/package.php?p=uncrustify
> Do not have time for debug right now.

Let's discuss publicly here.

**Comment by gerasiov** [comment]
twas me. =)
(broken mail client)

**Comment by gerasiov** [comment]
>In any case, we have to see how we can find out about these issues before the release, not after.

May be ubuntu project have some build farms external projects could use? At least they have s390x in their architectures.

**Comment by mihaipopescu** [comment]
@gerasiov would they be opened to use github API and automatically create issues whenever a _nightly_ build start failing (if they even have such a thing)?

Also, what would be a proper way of testing? Isn't it kinda hard to debug on powerpc64 without having any kind of local setup.

**Comment by mihaipopescu** [comment]
@gerasiov do you think we could get more debug info for this issue? Can you run the tests and get the debug logs?

**Comment by gerasiov** [comment]
Yes I have an access to those boxes, but have no time for this right now. I keep it in my doto list for now.

**Comment by gerasiov** [comment]
```
44: Test command: /usr/bin/cmake "-DTEST_PROGRAM=/home/gq/uncrustify-0.67+dfsg1/build/uncrustify" "-DTEST_LANG=cs" "-DTEST_CONFIG=config/verbatim_strings.cfg" "-DTEST_RERUN_CONFIG=config/verbatim_strings.cfg" "-DTEST_INPUT=input/cs/verbatim_strings.cs" "-DTEST_RESULT=results/cs/12004-verbatim_strings.cs" "-DTEST_RESULT_2=results_2/cs/12004-verbatim_strings.cs" "-DTEST_OUTPUT=output/cs/12004-verbatim_strings.cs" "-DTEST_RERUN_OUTPUT=output/cs/12004-verbatim_strings.cs" "-DTEST_DIR=/home/gq/uncrustify-0.67+dfsg1/tests" "-P" "/home/gq/uncrustify-0.67+dfsg1/tests/run_test.cmake"
44: Test timeout computed to be: 1500
44: Uncrustify error. The ERR-1.txt file is:
44: Parsing: input/cs/verbatim_strings.cs as language CS
44: input/cs/verbatim_strings.cs:4 Detected non-replaceable tab char in literal string
44: CMake Error at /home/gq/uncrustify-0.67+dfsg1/tests/run_test.cmake:58 (message):
44:   Uncrustify error_code (Pass 1)
44: 
44: 
44: Uncrustify error. The ERR-2.txt file is:
44: Parsing: output/cs/12004-verbatim_strings.cs as language CS
44: output/cs/12004-verbatim_strings.cs:4 Detected non-replaceable tab char in literal string
44: CMake Error at /home/gq/uncrustify-0.67+dfsg1/tests/run_test.cmake:96 (message):
44:   Uncrustify error_code (Pass 2)
44: 
44: 
1/1 Test #44: c-sharp_12004 ....................***Failed    0.05 sec

```

**Comment by guy-maurel** [comment]
@mihaipopescu Could you have a look on it?

**Comment by gerasiov** [comment]
output of PR #1835

> 44: Test timeout computed to be: 1500
> 44: Uncrustify error. The ERR-1.txt file is:
> 44: Parsing: input/cs/verbatim_strings.cs as language CS
> 44: parse_cs_string(1251): input/cs/verbatim_strings.cs: orig_line is 4, orig_col is 28, Detected non-replaceable tab char in literal string
> 44: parse_cs_string(1253): Warning is given if doing tab-to-	 replacement and we have found one in a C# verbatim string literal.
> 44: CMake Error at /home/gq/uncrustify-0.67+dfsg1/tests/run_test.cmake:58 (message):
> 44:   Uncrustify error_code (Pass 1)
>

**Comment by guy-maurel** [comment]
@gerasiov Thanks for helping.

**Comment by gerasiov** [comment]
If you need any experiments feel free to ask me. Unfortunatelly I'm still lack of free time to debug myself, but could run your tests from time to time.

**Comment by gmaurel** [comment]
This would be fine. Thanks.
