### ISSUE TITLE
Question: How to force Allmann brace style

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#1818]
Is it possible to force Allmann brace style for namespaces?

For instance, I have the following test case:
```
namespace a { namespace b {
}
}
```
which I want to be changed to this:
```
namespace a
{
   namespace b
   {
   }
}
```

I have tried a number of options using Uncrustify-0.67-87-d75a44a but all I'm able to get is:
```
namespace a
{ namespace b
{
}}
```

Config params were:
```
nl_namespace_brace              = force
indent_namespace_level          = 3
indent_columns                  = 3
```

There is probably an option that I'm overlooking, so any hint is appreciated.

**Comment by CDanU** [comment]
```sql
# Whether the 'namespace' body is indented.
indent_namespace                = true     # false/true

# Newline between namespace and {.
nl_namespace_brace              = force    # ignore/add/remove/force

# Whether to put a newline after brace open.
# This also adds a newline before the matching brace close.
nl_after_brace_open             = true     # false/true
```

**Comment by arneforlie** [comment]
Thanks, it solved that problem.

But nl_after_brace_open is a bit too eager and introduces a different issue:
```
#include <vector>

std::vector<int>
getVector()
{
  return {1, 2, 3};
}
```
becomes:
```
#include <vector>

std::vector<int>
getVector()
{
   return {
	     1, 2, 3
   };
}
```

**Comment by CDanU** [comment]
Hmm yeah that will need a new option then (`nl_namespace_brace`). The above behavior isn't really desirable, maybe that will also get a new one.

**Comment by arneforlie** [comment]
I should probably not say it, but I currently use uncrustify to do most of the formatting, and then astyle to ensure that I get the Allman brace style. I'm trying to reduce my dependency on astyle, but the issue discussed here is one of the reasons I can't drop it.

That said, I think that C++'s uniform initialization syntax, and lambdas, probably require some special handling so that one doesn't treat them in the same way as the braces used to specify blocks. However, I haven't thought this through, so I'll leave the solution to you.

**Comment by guy-maurel** [comment]
I am using the current git with:
```.cfg
indent_namespace_level          = 3
indent_columns                  = 3

# Whether the 'namespace' body is indented.
indent_namespace                = true

# Newline between namespace and {.
nl_namespace_brace              = force

# Whether to put a newline after brace open.
# This also adds a newline before the matching brace close.
nl_after_brace_open             = true

```
for the input:
```.cpp
namespace a { namespace b {
}
}

#include <vector>

std::vector<int>
getVector()
{
  return {1, 2, 3};
}
```

and get:
```.cpp
Uncrustify_d-0.68.1-83-f72c97d4-dirty
Parsing: arneforlie.cpp as language CPP
namespace a
{
   namespace b
   {
   }
}

#include <vector>

std::vector<int>
getVector()
{
   return {1, 2, 3};
}
```
Is there any difference(s) with your wish?

**Comment by arneforlie** [comment]
Thanks, this works well.
