### ISSUE TITLE
Provide static binary of releases

### ISSUE THREAD

**Issue by misery** [uncrustify/uncrustify#1824]
Hi there!

Thanks for uncrustify. We use it a lot... also in continuous integration. It would be helpful if you could provide a static (linux) binary of uncrustify (https://github.com/uncrustify/uncrustify/releases) like some other projects do (https://github.com/BurntSushi/ripgrep/releases).

Any distribution has another uncrustify version as a package. As every version of uncrustify is a little bit different in formatting it would be helpful to get a unified version for all developers / bots from official releases.

Maybe you could use Travis-CI to automatically upload tagged releases:
https://docs.travis-ci.com/user/deployment/releases/

I recommend musl as a libc as it can be statically linked without any problems into the uncrustify binary.

**Comment by mihaipopescu** [comment]
Hi @misery.

In fact we do but they are uploaded here https://sourceforge.net/projects/uncrustify/files/.

I have proposed to automate the release process here https://github.com/uncrustify/uncrustify/issues/1740#issuecomment-395972817 but Guy prefers to do them manually on his own machine (because reasons).

**Comment by mihaipopescu** [comment]
hmmm... that's correct. Ok, In that case, I agree 👍

**Comment by mihaipopescu** [comment]
Can you open a proposal PR for this? I'm definitely on board. And I'd also like to switch to a statically linked executable with no dependencies on other dynamic libraries to avoid making it dependent on specific distributions.
