### ISSUE TITLE
Enabling nl_create_func_def_one_liner can freeze uncrustify

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1825]
With the adoption of #1603, the newly added option `nl_create_func_def_one_liner` can freeze uncrustify in some scenarios.

I have just tried enabling this option in our global config and it looks like it ends up in an infinite loop for a test like `tests/input/cs/ifcomment.cs`.

Options are to either backout the changes or to fix it.

**Comment by guy-maurel** [comment]
PR #2382 is a bugfix proposal.
Please test it and report.
