### ISSUE TITLE
Option mod_paren_on_return=remove is not stable

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#1826]
If you have:

```cs
namespace Namespace
{
    class Class
    {
        private bool Foo()
        {
            return (
                (m_bar1) // working
                //|| (m_bar2) // not working
                //|| (m_bar3) // wrong
                );
        }
    }
}
```

after 1st format you will have:

```cs
namespace Namespace
{
    class Class
    {
        private bool Foo()
        {
            return
                (m_bar1) // working
                //|| (m_bar2) // not working
                //|| (m_bar3) // wrong
                ;
        }
    }
}
```

and the second one:
```cs
namespace Namespace
{
    class Class
    {
        private bool Foo()
        {
            return
                m_bar1 // working
                //|| (m_bar2) // not working
                //|| (m_bar3) // wrong
                ;
        }
    }
}
```

**Comment by guy-maurel** [comment]
It is NOT instable.
The source needs two runs to be complete.
Use the sign !, such as:
`c-sharp.test:60009! UNI-9917.cfg                         cs/UNI-9917.cs`

If the 3rd run is not OK, we may speak about instablity

**Comment by mihaipopescu** [comment]
I'm not talking about the same kind of instability like we have in our testing framework (sometimes using a rerun config). But if a snippet of code needs two runs to be formatted it means that the formatting is not stable.

In mathematical terms I expect something like this `f o f = f` (where `o` is function composition and `f` is the formatting funciton). This means that for any number of consecutive runs on the previous output of the formatted file the file formatting should be stable, in the sense that it should not change the second time when you have the _same_ config.

Without this feature, it will render any formatter impossible to be integrated into a large-scale development workflows as we have at Unity (commit hooks, format verifications for CI/CD, etc).

You might have the same problem as uncrustify is formatted with itself. If the formatting is unstable then you would always have to do run it two times and the same in the CI jobs.

I hope now it's more clear.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
