### ISSUE TITLE
Do we really need --show-config?

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#1865]
While working on #1852, I paid attention to `--show-config` for the first time. While this helpfully documents all available options, the output format is a little strange, and TBH, I am having trouble seeing what purpose it serves that is not served better by `--update-config-with-doc`. Do we really need this option, or could we get rid of it? (Or at least, make it a synonym for `--update-config-with-doc`.)

The several differences in output format result in a non-trivial chunk of additional code (that isn't even entirely correct, e.g. the list of possible tokenpos options is incomplete).

**Comment by mihaipopescu** [comment]
Actually we're using that to generate our own base config so yeah, at least for us is useful.

**Comment by mwoehlke-kitware** [comment]
Are you talking about [documentation/htdocs/config.txt](https://github.com/uncrustify/uncrustify/blob/738981d167bd7c79d80bf608968e9b8a8293f7dd/documentation/htdocs/config.txt)?

If yes, I don't really see how that addresses the question. The question isn't really about having an option named `--show-config`, it's whether we need the *two different formats*, or if we could get rid of the `--show-config` format and have only the `--update-config-with-doc` format.

Note:

----
#### `--show-config`
```
newlines                        { Auto, LF, CR, CRLF }
  The type of line endings. Default=Auto.
```
----
#### `--update-config-with-doc`
```
# The type of line endings. Default=Auto.
newlines                        = auto     # auto/lf/crlf/cr
```
----
The former is inconsistent and incomplete. What advantage does it provide over the latter?
