### ISSUE TITLE
Feature request: nl_multi_line_class

### ISSUE THREAD

**Issue by shhccie** [uncrustify/uncrustify#187]
Uncrustify has the option nl_multi_line_cond to control the newline between ')' and '{' of  the if/for/etc if they are on a different line, which overrides nl_for_brace, nl_if_brace, etc. 

I'd like there is also an option nl_multi_line_class to override nl_class_brace, nl_struct_brace, etc if multiple lines exist before the class body open brace, for example:

<pre><code>
struct foooooooooooooooooooo
:   private baarrrrrrrrrrrr111111111111111111
    someotherveryverylongbaseclasses
{
    vod somememberfunctiondeclaration1();
    vod somememberfunctiondeclaration2222222();
    int i;
    int j;
    ...
}
</code></pre>

**Comment by gmaurel** [comment]
Can you push as an example the output you expected to get?

**Comment by gmaurel** [comment]
No answer!
