### ISSUE TITLE
C# lambda expressions are broken with mod_full_paren_if_bool option

### ISSUE THREAD

**Issue by MKoep** [uncrustify/uncrustify#1872]
Version is: Uncrustify-0.67_f
Options is: **mod_full_paren_if_bool = true**

Original Code is:
```cs
List<int> list = new List<int>();
if (list.All(i => i > 5 && i < 9))
{
	return;
}
```
Output Code is:
```cs
List<int> list = new List<int>();
if (list.All((i => i > 5) && (i < 9)))
{
	return;
}
```
The added braces break the C# syntax.

**Comment by guy-maurel** [comment]
PR #2247 is a bugfix proposal.
Please test it and report.
