### ISSUE TITLE
Unwanted changes inside of comments (tabs to space conversion)

### ISSUE THREAD

**Issue by MKoep** [uncrustify/uncrustify#1873]
Version is: Uncrustify-0.67_f

Original Code is:
```cs
/// <summary>
/// 	Event handler.
/// </summary>
```
There is a **space** followed by a **tab** before the word "Event".

Output Code is:
```cs
/// <summary>
///     Event handler.
/// </summary>
```
The **tab** is replaced by **spaces**.

There is no option to prevent these changes. The desired output should have **NO** changes inside of comments.

**Comment by mihaipopescu** [comment]
Not that I know of but can you add your config as well?

**Comment by MKoep** [comment]
Sure, this is our config: [config.txt](https://github.com/uncrustify/uncrustify/files/2184271/config.txt)

**Comment by MKoep** [comment]
I think the problem is:
````cpp
// explicitly disallow a tab after a space
if (ch == '\t' && cpd.last_char == ' ')
{
	size_t endcol = next_tab_column(cpd.column);
	while (cpd.column < endcol)
	{
		add_char(' ');
	}
	return;
}
````
in output.cpp, line 275, function _add_char_

**Comment by mihaipopescu** [comment]
Nice. Can you propose the fix in a PR?

**Comment by guy-maurel** [comment]
PR #2248 is a bugfix proposal.
Please test it and report.
