### ISSUE TITLE
How do I get alignment for if parameters on multiple lines?

### ISSUE THREAD

**Issue by dkbarto** [uncrustify/uncrustify#1876]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
My debug.txt
[debug.txt](https://github.com/uncrustify/uncrustify/files/2184966/debug.txt)

The original shows that the parameters are aligned on the if statement:
```
int main(
  int argc, char *argv[]
  )
{
  if ((ColTypeInvalid == vartype) || (ColTypeURI == vartype) ||
      (ColTypePred == vartype) || (ColTypeVariable == varitype)) {
    contain_compvars = true;
  }
}
```

However after running uncrustify the parameters no longer align the same way;
```
int main(
  int argc, char *argv[]
  )
{
  if ((ColTypeInvalid == vartype) || (ColTypeURI == vartype) ||
    (ColTypePred == vartype) || (ColTypeVariable == vartype))
  {
    contain_compvars = true;
  }
}
```
What configuration do I need to adjust to get the if expression to align as I would like (if possible)?
There is another issue related to the placement of the { aligning with the if as I believe the two issues are un-related.

**Comment by mwoehlke-kitware** [comment]
> What configuration do I need to adjust to get the if expression to align as I would like (if possible)?

Try `indent_continue=0` (or remove it; `0` is the default). I don't think there's an option to not apply this only to control statements, but if you really want that, you're asking for a complex style that coders are probably going to have trouble remembering how to apply.

> There is another issue related to the placement of the { aligning with the if [...]

Try `nl_if_brace=remove`.

**Comment by dkbarto** [comment]
Already set `nl_if_brace=remove`. Doesn’t fix the issue in question.

The problem with `indent_continue=0` is that setting it to 0 (or unsetting it) means that the parameters to the functions get aligned under the open (, rather than at a reasonable indent setting.

Setting it to ‘4’ gives us the alignment we (mostly) want, but shifts the parameters on a function declaration by 4. We use an indent setting of 2 for our code.

Seems the two things are merged and should be separate configuration settings.

	David

**Comment by mwoehlke-kitware** [comment]
> Already set `nl_if_brace=remove`. Doesn’t fix the issue in question.

It works for me.

Input:
```c++
if ((foo() && bar()) ||
(bar() && !foo()))
{none();}
```

Output:
```c++
if ((foo() && bar()) ||
    (bar() && !foo())) {
        none();
}
```

...there is probably something else in your configuration that is overriding it.

> The problem with `indent_continue=0` is that setting it to 0 (or unsetting it) means that the parameters to the functions get aligned under the open (, rather than at a reasonable indent setting.

If you're talking about wanting this:
```c++
int long_function_name(int first_parameter,
  int second_parameter);
```

...then IMHO you're weird :smile:. Personally, I loathe that style, and don't know that it is anywhere recommended. However, if you're talking about:
```c++
int foo(
        int x);
```

...then I agree that's horrible, but is also ***what you asked for*** with `indent_paren_nl=true`.

I would encourage you to try formatting your code with a clean config and only turning on options that you *know* you want. This should help you figure out if uncrustify really *can't* do what you want, or if it's doing what you *told* it to do, which isn't what you *want* it to do, and may also help you find which options are responsible for that.

**Comment by mwoehlke-kitware** [comment]
(I'm guessing from #1881 that you got `nl_if_brace` working?)

**Comment by dkbarto** [comment]
yes. Knowing that there are conflicting options, and with an improvement (with suggested improvement) open, this is being closed.
