### ISSUE TITLE
More support for C++11 braced initializer lists

### ISSUE THREAD

**Issue by shhccie** [uncrustify/uncrustify#188]
In issue #181, berenm has proposed changes to make Uncrustify  work better with C++11 braced initializer lists in class member initialization. Here I want to point out two scenarios where we could improve Uncrustify further in regard to working with C++11 braced initializer lists. Consider

<pre><code>
pair&lt;int, int&gt; foo()
{
    // ...
    pair&lt;int, int&gt; p{ 0, 0 };
    // ...
    return { 1, 1 };
}
</code></pre>

Under the new standard, this is legal code and the formatting is what I expect. But with

<pre><code>
nl_after_brace_open        = true
mod_remove_extra_semicolon = true
</code></pre>

It becomes

<pre><code>
pair&lt;int, int&gt; foo()
{
    // ...
    pair&lt;int, int&gt; p{ 
        0, 0 
    };
    // ...
    return { 
        1, 1
    }
}
</code></pre>

Three issues here:
<ol>
   <li>The initializer list for the variable p is not kept one line;</li>
   <li>The initializer list in the return statement is not kept one line; and</li>
   <li>The semicolon of the return statement has been removed.</li>
</ol>

The suggested solution:
add this to src/newlines.cpp after line 1853
<pre><code>

      if ((pc->type == CT_BRACE_OPEN) &amp;&amp;
          (pc->parent_type == CT_NONE))
      {
         chunk_t *prev = chunk_get_prev(pc);
         if ((prev &amp;&amp; prev->type == CT_WORD) &amp;&amp;
             (prev->parent_type == CT_NONE))
         {
            LOG_FMT(LNL1LINE, "false (C++ uniform initialization)\n");
            return(false);
         }
         if (prev &amp;&amp; prev->type == CT_RETURN)
         {
            LOG_FMT(LNL1LINE, "false (returning initializer list)\n");
            return(false);
         }
      }
</code></pre>

and in src/semicolons.cpp toward the end add

<pre><code>
(pc->type != CT_RETURN)
</code></pre>

to the if condition.

**Comment by gmaurel** [comment]
Well!
It is a long time ago...
The newlines has changed at many places.
I cannot find the right place for your suggestion.
The actual git version can be found at
  https://github.com/uncrustify/uncrustify
Please test it and make a new suggestion for that.
Thanks.
