### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by dkbarto** [uncrustify/uncrustify#1881]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Extend the comments for `nl_if_brace` etc. to indicate that `nl_multi_line_cond` can override it.
```
[Nl If Brace]
Category=3
Description="<html>Add or remove newline between 'if' and '{'.<BR>nl_multi_line_cond overrides this setting</html>"
Enabled=false
EditorType=multiple
Choices="nl_if_brace=ignore|nl_if_brace=add|nl_if_brace=remove|nl_if_brace=force"
ChoicesReadable="Ignore Nl If Brace|Add Nl If Brace|Remove Nl If Brace|Force Nl If Brace"
ValueDefault=0

[Nl For Brace]
Category=3
Description="<html>Add or remove newline between 'for' and '{'.<BR>nl_multi_line_cond overrides this setting</html>"
Enabled=false
EditorType=multiple
Choices="nl_for_brace=ignore|nl_for_brace=add|nl_for_brace=remove|nl_for_brace=force<BR>"
ChoicesReadable="Ignore Nl For Brace|Add Nl For Brace|Remove Nl For Brace|Force Nl For Brace"
ValueDefault=0

[Nl Catch Brace]
Category=3
Description="<html>Add or remove newline between 'catch' and '{'.<BR>nl_multi_line_cond overrides this setting</html>"
Enabled=false
EditorType=multiple
Choices="nl_catch_brace=ignore|nl_catch_brace=add|nl_catch_brace=remove|nl_catch_brace=force"
ChoicesReadable="Ignore Nl Catch Brace|Add Nl Catch Brace|Remove Nl Catch Brace|Force Nl Catch Brace"
ValueDefault=0


[Nl Brace While]
Category=3
Description="<html>Add or remove newline between '}' and 'while' of 'do' statement.<BR>nl_multi_line_cond overrides this setting</html>"
Enabled=false
EditorType=multiple
Choices="nl_brace_while=ignore|nl_brace_while=add|nl_brace_while=remove|nl_brace_while=force"
ChoicesReadable="Ignore Nl Brace While|Add Nl Brace While|Remove Nl Brace While|Force Nl Brace While"
ValueDefault=0

[Nl Switch Brace]
Category=3
Description="<html>Add or remove newline between 'switch' and '{'.<BR>nl_multi_line_cond overrides this setting</html>"
Enabled=false
EditorType=multiple
Choices="nl_switch_brace=ignore|nl_switch_brace=add|nl_switch_brace=remove|nl_switch_brace=force"
ChoicesReadable="Ignore Nl Switch Brace|Add Nl Switch Brace|Remove Nl Switch Brace|Force Nl Switch Brace"
ValueDefault=0
```

**Comment by mwoehlke-kitware** [comment]
There are a *lot* of options that override other options: `sp_arith_additive`, `sp_cpp_lambda_assign`, `sp_before_assign`, `sp_after_assign`, `sp_enum_before_assign`, `sp_enum_after_assign`, `sp_inside_sparen_open`, `sp_inside_sparen_close`, `sp_after_operator_sym_empty`, `sp_fparen_brace_initializer`, `sp_cond_colon_before`, `sp_cond_colon_after`, `sp_cond_question_before`, `sp_cond_question_after`, `sp_cond_ternary_short`, `sp_inside_newop_paren_open`, `sp_inside_newop_paren_close`, `indent_continue`, `indent_continue_class_head`, `indent_param`, `nl_multi_line_cond` (as noted in this issue), `nl_case_colon_brace`, `nl_func_paren_empty`, `nl_func_def_paren_empty`, `nl_func_call_paren_empty`, `nl_func_decl_start_single`, `nl_func_def_start_single`, `nl_func_decl_end_single`, `nl_func_def_end_single`, `nl_after_access_spec`, and `mod_full_brace_if_chain`... that are clearly labeled. *If* we change one, I would feel strongly that they should *all* be changed, for consistency.

Or... you could read the documentation of what options you're twiddling and not turn them on if you don't want them to override other options? :slightly_smiling_face:

Given the large number of options that would be affected, as well as the added maintenance burden of trying to keep such cross-references up to date, I don't plan on making this change myself. Given the impact, I'd appreciate if any such change, if it happens, could be post-#1852...

p.s. The formatting of your proposed change is pretty useless. Just posting the updated descriptions would be easier to read, and no more difficult to apply.

**Comment by guy-maurel** [comment]
and now? Could we close?

**Comment by dkbarto** [comment]
I’ve had no time to work on this right now. I promise I’ll update the bug when I’ve had time.

Sorry.

	David

**Comment by dkbarto** [comment]
I make your suggested changes to the ifdef’s and still wound up with the same error. Do I need a newer/different uncrustify?

1272_ indent -U dlmalloc.cpp
Indenting one file dlmalloc.cpp.cpp
Parsing: dlmalloc.cpp.cpp as language CPP
FATAL: negative value.
   pc->orig_col=0 prev->orig_col_end=68
Formatted  /Users/barto/CSI/sparqlverse/source/utils/dlmalloc.cpp.cpp

1273_ uncrustify --version
Uncrustify-0.68-210-4bd81b7d

**Comment by guy-maurel** [comment]
Please push your example file and the configuration

**Comment by dkbarto** [comment]
The latest version of uncrustify (released today) works with the minor edit to remove the enclosing #if __cplusplus / #endif that surround the matching pair of { and } in the file.
This can be closed.

**Comment by dkbarto** [comment]
In fact it works fine even when those are not removed. Major step up for this version of the program. Good stuff. Thanks to all the developers.
