### ISSUE TITLE
Feature request: Align single-line-if bodys

### ISSUE THREAD

**Issue by shhccie** [uncrustify/uncrustify#189]
In one place,

<pre><code>
std::wstring characteristicsToWstring(DWORD dw, const std::wstring& fill)
{
    // ...
    std::wstring ret;
    if (dw & NCCF_ALL_USERS)
        ret += fill + L"Connection is available to all users. (0x1)\n";
    if (dw & NCCF_ALLOW_DUPLICATION)
        ret += fill + L"Connection is duplicable.             (0x2)\n";
    if (dw & NCCF_ALLOW_REMOVAL)
        ret += fill + L"Connection is removable.              (0x4)\n";
    if (dw & NCCF_ALLOW_RENAME)
        ret += fill + L"Connection can be renamed.            (0x8)\n";
    if (dw & NCCF_INCOMING_ONLY)
        ret += fill + L"Direction is \"incoming\" only.         (0x20)\n";
    if (dw & NCCF_OUTGOING_ONLY)
        ret += fill + L"Direction is \"outgoing\" only.         (0x40)\n";
    if (dw & NCCF_BRANDED)
        ret += fill + L"Icons are branded.                    (0x80)\n";
    if (dw & NCCF_SHARED)
        ret += fill + L"Connection is shared.                 (0x100)\n";
    if (dw & NCCF_BRIDGED)
        ret += fill + L"Connection is bridged.                (0x200)\n";
    if (dw & NCCF_FIREWALLED)
        ret += fill + L"Connection is firewalled.             (0x400)\n";
    // ...
    return ret;
}
</code></pre>

In another,

<pre><code>
    // ...
    if (0 &lt; result) cout &lt;&lt; "Player 1 wins!";
    else if (result &lt; 0) cout &lt;&lt; "Player 2 wins!";
    else cout &lt;&lt; "Game draw!";
    // ...
</code></pre>

In these cases, the code would be clearer if we were able to align the if bodies.

<pre><code>
std::wstring characteristicsToWstring(DWORD dw, const std::wstring& fill)
{
    // ...
    std::wstring ret;
    if (dw & NCCF_ALL_USERS)         ret += fill + L"Connection is available to all users. (0x1)\n";
    if (dw & NCCF_ALLOW_DUPLICATION) ret += fill + L"Connection is duplicable.             (0x2)\n";
    if (dw & NCCF_ALLOW_REMOVAL)     ret += fill + L"Connection is removable.              (0x4)\n";
    if (dw & NCCF_ALLOW_RENAME)      ret += fill + L"Connection can be renamed.            (0x8)\n";
    if (dw & NCCF_INCOMING_ONLY)     ret += fill + L"Direction is \"incoming\" only.         (0x20)\n";
    if (dw & NCCF_OUTGOING_ONLY)     ret += fill + L"Direction is \"outgoing\" only.         (0x40)\n";
    if (dw & NCCF_BRANDED)           ret += fill + L"Icons are branded.                    (0x80)\n";
    if (dw & NCCF_SHARED)            ret += fill + L"Connection is shared.                 (0x100)\n";
    if (dw & NCCF_BRIDGED)           ret += fill + L"Connection is bridged.                (0x200)\n";
    if (dw & NCCF_FIREWALLED)        ret += fill + L"Connection is firewalled.             (0x400)\n";
    // ...
    return ret;
}
</code></pre>

<pre><code>
    // ...
    if (0 &lt; result)      cout &lt;&lt; "Player 1 wins!";
    else if (result &lt; 0) cout &lt;&lt; "Player 2 wins!";
    else                 cout &lt;&lt; "Game draw!";
    // ...
</code></pre>

**Comment by gmaurel** [comment]
As you see, no proposal was coming over the last 3 years.
Because we prefer to spend some more braces. One-line codes are mostly difficult to read.
Use braces and some new lines and you get the statements "count" aligned.
