### ISSUE TITLE
A question about objective C with the option sp_oc_catch_brace

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1894]
The description is:
_Add or remove space between `@catch` and '{' if on the same line._

I never found any example for that. But something such as:
https://www.tutorialspoint.com/objective_c/objective_c_exception_handling.htm

```.oc
   @try  {
      NSString *string = [array objectAtIndex:10];
   } @catch (NSException *exception) {
      NSLog(@"%@ ",exception.name);
      NSLog(@"Reason: %@ ",exception.reason);
   }
```

I see always a _(NSException *exception)_ after `catch` and before the brace.

If this is correct, we could remove the case.
Any comment from "OC" people?

**Comment by mihaipopescu** [comment]
cc @aet

**Comment by nivekkagicom** [comment]
An example for sp_oc_catch_brace can be found in Objective-C test 50512. In the bar message implementation is `@catch (NSException* const inException){` and the configuration specifies that uncrustify should add a space before the '{' to produce `@catch (NSException* const inException) {`. Functionally it is identical to the C++ options for catch statements (e.g., `catch(std::exception const& inException){`). Because some people like different formatting for the two exception statements uncrustify has sets of options for C++ and Objective-C to allow this customization. Because other people like the same formatting for either exception if any of the sp_oc_catch_* settings is ignore then the uncrustify behavior falls through to the more generic sp_catch_* setting. For example, sp_oc_catch_brace falls through to sp_catch_brace if the first is set to ignore.

Is this the information you are looking for?

**Comment by guy-maurel** [comment]
Yes and no.
The description is:
_Add or remove space between '@catch' and '{' if on the same line._
The code is:
```.cpp
   if (  language_is_set(LANG_OC)
      && chunk_is_token(first, CT_CATCH)
      && chunk_is_token(second, CT_BRACE_OPEN)
      && (cpd.settings[UO_sp_oc_catch_brace].a != AV_IGNORE))
   {
      log_rule("sp_oc_catch_brace");
      return(cpd.settings[UO_sp_oc_catch_brace].a);
   }
```
You speak about:
_@catch (NSException* const inException){_

The description, the space.cpp code work on:
_@catch {_

This is **NOT** the same.
Following (for C++) https://en.cppreference.com/w/cpp/language/try_catch

We could introduce **two new options**, such as:
1 _Add or remove space between '@catch' and the '(' of the declarator if on the same line._
2 _Add or remove space between the '(' of the declarator and '{' if on the same line._

and mark the old option as _deprecated_
using a changed options.h|cpp while introducing a new member of `argtype_e` `AT_DEPRECATED`

For me, it is very important, not to break any option.
Option marked as `AT_DEPRECATED` are still present in the system. The user will get a message,
(error or warning) with a proposal showing to the new, more appropriated options.

I am working on https://coveralls.io/builds/17772219/source?filename=src/space.cpp
and found some more options which cannot be reached because the description, the code
do not matched to the syntax. I will make a PR for that.

**Comment by nivekkagicom** [comment]
I believe the two options you suggest already exist:
```
# Add or remove space between '@catch' and '(' in '@catch (something) { }'
# If set to ignore, sp_catch_paren is used.
sp_oc_catch_paren               = ignore   # ignore/add/remove/force
```
which corresponds to the option sp_catch_paren: 
```
# Add or remove space between 'catch' and '(' in 'catch (something) { }'
# If set to ignore, sp_before_sparen is used.
sp_catch_paren                  = force    # ignore/add/remove/force
```
And:
```
# Add or remove space between '@catch' and '{' if on the same line.
# If set to ignore, sp_catch_brace is used.
sp_oc_catch_brace               = ignore   # ignore/add/remove/force
```
which corresponds to the option sp_brace_catch:
```
# Add or remove space between 'catch' and '{' if on the same line.
sp_catch_brace                  = force    # ignore/add/remove/force
```
While the `sp_catch_*` variations can be used for C++ and other languages that allow for a `catch` statement Objective-C++ allows both `catch` and `@catch` in the same source file and the two need separate formatting controls to allow one to have slightly different formatting for the two statements if desired.

FWIW there are 5 pairs of options related to catch and @catch that allow formatting of C++ catch and Objective-C @catch in the same source file:
```
sp_oc_catch_paren               = ignore   # ignore/add/remove/force
sp_catch_paren                  = add      # ignore/add/remove/force
sp_oc_catch_brace               = add      # ignore/add/remove/force
sp_catch_brace                  = force    # ignore/add/remove/force
sp_oc_brace_catch               = add      # ignore/add/remove/force
sp_brace_catch                  = force    # ignore/add/remove/force
nl_oc_catch_brace               = remove   # ignore/add/remove/force
nl_catch_brace                  = remove   # ignore/add/remove/force
nl_oc_brace_catch               = add      # ignore/add/remove/force
nl_brace_catch                  = remove   # ignore/add/remove/force
```
Therefore, all these options are still valid and functional. **Please do not deprecate any of them**.

The code you quote is functionally equivalent to the code used by the sp_catch_brace case:
```
   if (chunk_is_token(first, CT_CATCH) && chunk_is_token(second, CT_BRACE_OPEN))
   {
      log_rule("sp_catch_brace");
      return(cpd.settings[UO_sp_catch_brace].a);
   }

```
It was my understanding that this is used by the C++ `catch (expression) {` case as well. If this is not so then perhaps the code you cite is broken and should be fixed. I am not immediately aware of any language that has `catch {` so perhaps both of these are in error and should both be fixed. I will spend some time as soon as possible looking at how the brace following a catch is handled in the languages I use (C++, Java and Objective-C). If someone knows a language that specifically allows the `catch {` then perhaps it would be reasonable to have separate options for the `catch (expression) {` and the `catch {` case; however, I would be disinclined to have separate formatting options in this case and feel that `sp_catch_brace` should apply in both situations. I certainly can find no test case that would cover a `catch {` case and, therefore, suspect that both `sp_oc_catch_brace` and `sp_catch_brace` are broken and need fixing

If the complaint is really just the warding in the description for `sp_oc_catch_brace` by all means update it if you prefer. It is simply the same wording as used in the `sp_catch_brace` though updated to use `@catch` in place of `catch`.

**Comment by nivekkagicom** [comment]
FWIW these two settings also make no mention of an intervening expression and yet both control the use of newline between the `catch` statement and the brace:
```
   unc_add_option("nl_catch_brace", UO_nl_catch_brace, AT_IARF,
                  "Add or remove newline between 'catch' and '{'.");
   unc_add_option("nl_oc_catch_brace", UO_nl_oc_catch_brace, AT_IARF,
                  "Add or remove newline between '@catch' and '{'.\n"
                  "If set to ignore, nl_catch_brace is used.");
```
Therefore, I am inclined to believe that the `sp_catch_brace` and `sp_oc_catch_brace` settings are simply broken and should both be fixed to operate on the brace following the expression following the catch keyword. That is they should operate on statements like `catch (expression)<this space>{` just as the `nl_catch_brace` and `nl_oc_catch_brace` operate on the statement `catch (expression)<this newline>{`. In all 4 cases it seems reasonable to update the wording of the description to properly reflect that the location in question follows the expression and before the brace in a catch statement.

**Comment by nivekkagicom** [comment]
I have gone ahead and created PR #1900 to correct the handling of both `sp_catch_brace` and `sp_oc_catch_brace`.
