### ISSUE TITLE
Changing existing test configurations to gain coverage is resulting in untested behaviors

### ISSUE THREAD

**Issue by nivekkagicom** [uncrustify/uncrustify#1905]
For example, I believe the `sp_oc_catch_paren` in sp_oc_catch.cfg was recently changed from `ignore` to `force` in order to improve coverage; however, this in turn disables the check for fall-though behavior of `sp_oc_catch_paren` when it is set to `ignore`. While one could argue that the original test was incomplete simply changing the value of the setting in the test leaves the `ignore` behavior untested and worse open for alteration. IMHO If one is going to change values like this to gain coverage then there needs to be a new test to allow the original test to the check that the previous behavior is still functional. Anyone else agree or am I the only one?

**Comment by CDanU** [comment]
As far as I know gcov based coverage only tells about how much % of lines are covered but not how much % of all possible combinations (if branches) are taken right? If so I have to agree that this changes can cause unwanted behaviour. 

The problem with what you describe is most likely that the previous behaviour was something that just happened without the author of the test knowing that it in fact does cover more than he anticipated.

I'd rather have a clearly defined test for that extra behaviour. Unfortunately as it is unanticipated a proper test for that will only be written once we receive a bug report or if someone like you notices it. 

So shouldn't we touch old tests? _Maybe_, I can't clearly say no or yes to that one.
Should we just plainly copy the test and add the new change? No! I want **clearly** defined tests. 
In the case that you have mentioned it would have been better to write an entirely new one.

**Comment by mwoehlke-kitware** [comment]
FWIW, I agree that I'd rather see new tests that are specifically targeting a narrow code path rather than fiddling with existing tests.

**Comment by gmaurel** [comment]
It would be fine to get more proposals for new tests cases than only create a new issue.

**Comment by guy-maurel** [comment]
can we close?
