### ISSUE TITLE
mod_full_brace_if=remove is too zealous (instability)

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#1907]
Consider the following code:
```c++
if (expr)
{
 stmt;
  // comment
}
```

`mod_full_brace_if=remove` wants to remove the braces here, when it probably shouldn't, since doing so causes the comment to lose the context that it exists inside the `if`'s scope. In particular, this manifests as an instability in test c:02102. (See also https://github.com/uncrustify/uncrustify/pull/1821#issuecomment-403633879.)

**Comment by guy-maurel** [comment]
and now?
