### ISSUE TITLE
Strange spacing when reflowing comments (instability)

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#1908]
Test cpp:30815 has this input:
```c
/* Start Change #95 */
/*INITIALIZE Variable(contExtnElgInd); /# Change #61 #/ */
/*/# Start Change #35 #/ */
```

After one round of formatting, it produces this output:
```c
/* Start Change #95
 *INITIALIZE Variable(contExtnElgInd); /# Change #61 #/
 * /# Start Change #35 #/
 */
```

However, after a second round, it produces:
```c
/* Start Change #95
 * INITIALIZE Variable(contExtnElgInd); /# Change #61 #/
 * /# Start Change #35 #/
 */
```

Besides the instability, this feels like a bug, i.e. that the second pass output should have been produced from the first pass. (See also https://github.com/uncrustify/uncrustify/pull/1821#issuecomment-403633879.)

**Comment by guy-maurel** [comment]
and now, what is to do?

**Comment by guy-maurel** [comment]
PR #2377 is a bugfix proposal.
Please test it and report.
