### ISSUE TITLE
nl_before_func_body_def is inconsistent (instability)

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#1909]
I don't really have a cogent explanation for this one, except that it manifests as an instability in test cpp:34113. The input consists of function definitions intermixed with blank lines and comment in varying configurations, with `nl_before_func_body_def=1`. Running uncrustify over the input multiple times produces a different result. (See also https://github.com/uncrustify/uncrustify/pull/1821#issuecomment-403633879.)

**Comment by guy-maurel** [comment]
should we implement a loop?

**Comment by guy-maurel** [comment]
PR #2370 is a bugfix proposal.
Please test it and report.
