### ISSUE TITLE
A issue that remove spaces in Objective-C method call

### ISSUE THREAD

**Issue by Whirlwind** [uncrustify/uncrustify#191]
I found a issue, but I don't know whether it is a bug: (Objective-C)
```
[(WNodeViewModel *)self.superViewModel longKeyPathForKeyPath : keyPath ofTarget : target];
```

I can not remove the space around with `:`, but I can remove the space like this:
```
[self.superViewModel longKeyPathForKeyPath:keyPath ofTarget:target];
```

I just add `(WNodeViewModel *)`. What should I do?

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
