### ISSUE TITLE
Don't parenthesize return statements

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#1917]
Uncrustify has `mod_paren_on_return=add`:
https://github.com/uncrustify/uncrustify/blob/8aff3b63d2d9fb5ef1a630bdc1f946efe689b9dd/forUncrustifySources.cfg#L147

However, this prevents C++11 type elision:
```
error: could not convert ‘({...})’ from ‘void’ to ‘<return type>’
   return({});
```

How would y'all feel about changing this to `mod_paren_on_return=remove` (or even just `ignore`)? ...or is preventing type elision desired?

**Comment by mwoehlke-kitware** [comment]
I suppose I *could*, but that would imply having:
```c++
  return(false);
  return{};
  return{0};
```

That feels a little inconsistent to me, but then I'm used to (and prefer) the style that's equivalent to `mod_paren_on_return=remove`.

So I guess that adds a third option to what really is a question about uncrustify's preferred code style:
- Disallow type elision in `return` (current behavior).
- Switch to `mod_paren_on_return=remove`.
- Add and use an option that requires `return(...)` ***or*** `return{...}`.

**Comment by CDanU** [comment]
I saw that behaviour too, I personally think that this is a bug. If a return statement uses braces the  `mod_paren_on_return` option shouldn't add parenthesis around them.

**Comment by mwoehlke-kitware** [comment]
Okay, I guess unless @gmaurel wants to chime in otherwise, the consensus is to a) make `mod_paren_on_return=add` not do so if the `return` is followed by a `{`, and I suppose b) add `sp_return_brace` (set to `remove` in `forUncrustifySources.cfg`)?

**Comment by gmaurel** [comment]
It is OK for me.

**Comment by mwoehlke-kitware** [comment]
Um... small problem here. Currently, we add spaces inside `{}`s, but not inside `()`s. That is going to lead to an inconsistency:

```c++
return(0);
return{ 0 };
```

Removing the space is going to cause all manner of code churn (I tried, it wasn't pretty).

That being the case, does that change anyone's thoughts on this issue? If the above is okay, we can go with that. Other options include:
- `sp_paren_brace=force` (no other changes)
- `sp_paren_brace=force` and `mod_paren_on_return=remove`
- remove space inside `{}`s in spite of the churn

**Comment by mwoehlke-kitware** [comment]
> You mean as in removing changing the default behaviour from force to ignore without a specific option for that?

No, I mean:
```diff
diff --git a/forUncrustifySources.cfg b/forUncrustifySources.cfg
index 5da3c2fe..be900ae1 100644
--- a/forUncrustifySources.cfg
+++ b/forUncrustifySources.cfg
@@ -39,6 +39,8 @@ sp_after_cast                   = remove
 sp_sizeof_paren                 = remove
 sp_inside_braces_enum           = force
 sp_inside_braces_struct         = force
+sp_after_type_brace_init_lst_open = remove
+sp_before_type_brace_init_lst_close = remove
 sp_inside_braces                = force
 sp_func_proto_paren             = remove
 sp_func_def_paren               = remove
```

We already have options, I'm just talking about changing which we use in `forUncrustifySources.cfg`. I tried, and it resulted in many places in uncrustify's sources changing format.

To phrase differently what I think are our options:
1. We could make the above change. Returns are consistent, but lots of other code changes also. (Arguably, this would also be more consistent with e.g. not having spaces inside `()`s, but that's a pretty common "inconsistency", and one which I may even be partial to myself.)
1. We can live with returns (i.e. `return(0)` vs. `return{ 0 }`) being inconsistent.
   - In this case, we probably want to consider if we would prefer `sp_return_brace` to be `remove` or `force`.
1. We could change our minds about `mod_paren_on_return`, which, with `sp_return_brace=force` would also be reasonably consistent. (Also, `mod_paren_on_return=add` is a somewhat uncommon code style.)
1. I *suppose* we could add options to override space inside initializer lists following a return, but that seems overly specific and not very consistent.

Personally, I like (3) :slightly_smiling_face:, but a) it's a lot of churn, and b) I am probably outvoted. (2) is clearly the path of least resistance, but in that case, do we still want to squelch the space after `return` for that case?

Really, what I'm asking is just whether, realizing that `return{0}` is problematic, if that changes anyone's thoughts, or if we just want to stick with `return{ 0 }` (with no space after `return` as originally conceived).
