### ISSUE TITLE
C# bit shift operator treated as two comparation char 

### ISSUE THREAD

**Issue by sobbczakm** [uncrustify/uncrustify#192]
When I parse cs file and options sp_compare is set to add or force uncrustify separated shift bit operator. Example:

File content before:

<pre>

class TestClass
{
    static void Main(string[] args)
    {

        int data = 5;
        data = data >> 2;
        System.Console.WriteLine(data);
    }
}

</pre>

File content after:

<pre>
class TestClass
{
static void Main (string[] args)
{
        int data = 5;

        data = data > > 2;
        System.Console.WriteLine (data);
}
}
</pre>

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
Please test it!
