### ISSUE TITLE
sp_arith modifies function reference involving cast

### ISSUE THREAD

**Issue by nmenon** [uncrustify/uncrustify#1942]
All files are available here:
https://gist.github.com/nmenon/648989066a5c924e274fcb47ed245304 

Summary:
if sp_arith is set to force or add, a function dereference involving cast gets messed up.

Debug Log (including configuration)
--------------
[debug.txt](https://gist.github.com/nmenon/648989066a5c924e274fcb47ed245304#file-debug-txt)
[uncrustify_options.cfg](https://gist.github.com/nmenon/648989066a5c924e274fcb47ed245304#file-uncrustify_options-cfg)

Test Code:
----------------------
[goodcode.c](https://gist.github.com/nmenon/648989066a5c924e274fcb47ed245304#file-goodcode-c)
```
.arg	= (u32) &my_func,
```

Generated result:
----------------------
Become [crustified_badcode.c](https://gist.github.com/nmenon/648989066a5c924e274fcb47ed245304#file-crustified_badcode-c)
```
.arg	= (u32) & my_func,
```
Notice the space between '&' and my_func - '&' is not a math operator as it is a function reference.

Other observations:
-------------------------
However, if I change in uncrustify_options.cfg the following:
```
sp_arith = force
```
To:
```
sp_arith = ignore
```

The good code is retained (basically dont introduce a " " on a function reference). However this introduces a side effect:
```
x = x+1;
````
there is no space introduced around the math operator. 

The other observation is to remove the cast entirely
```
.arg	=  &my_func,
```
This does not get messed up no matter the setting of sp_arith - However, we do the cast for a specific reason in the code.

Uncrustify version
----------------------
$ uncrustify -v
Uncrustify-0.67_f

Not sure if this worked in any previous version. I do have access to 0.58 prebuilt binary and the behavior is the same there as well.

**Comment by nmenon** [comment]
Closing this.. I think I understand the problem looking at the debug log of example code.

I think the proper solution is to identify that u32 is a type. Yes, it is kinda specific to linux kernel and few other projects such as those.. but uncrustify.cfg needs to be specifically told about it. Adding this to uncrustify.cfg resolves the issue
```
type           u32
```

**Comment by mwoehlke-kitware** [comment]
Yeah... unfortunately, uncrustify is not a full C[++] parser. This means it has to guess from context if an identifier is a type, variable, function, or whatnot. Given that, I'm not sure it's possible to correctly determine that `(u32)&func` is a cast and not an arithmetic; if `u32` and `func` were variables, it *would* be an arithmetic.
