### ISSUE TITLE
Objective-C's protocol not follow `angle` rule, it follow `compare` rule.

### ISSUE THREAD

**Issue by Whirlwind** [uncrustify/uncrustify#195]
this code:

```
id < MYMapViewAnnotationViewProtocol > view;
```

When I use the config:

```
sp_inside_angle = remove
```

it like this:

```
id <MYMapViewAnnotationViewProtocol> view
```

It is right!

But, if I use the protocol to cast a object, it not works:

```
[self annotationView:(id< MYMapViewAnnotationViewProtocol >) view];
```

The space that after `<` and before `>` will not be removed!
Is it a bug?

And I use this config:

```
sp_compare = remove
```

It will remove the spaces and like this:

```
[self annotationView:(id<MYMapViewAnnotationViewProtocol>) view];
```

But the code `a < b` will remove the space : `a<b`.

**Comment by ericb0774** [comment]
+1

**Comment by mgrebenets** [comment]
+1

Same story for type declarations in blocks, for example in enumeration

``` objective-c
[self.observers enumerateObjectsUsingBlock:^(id < Observer > observer, BOOL *stop) {
                            // ...
                        }];
```

Note extra spaces inside `< Observer >`, this is due to forcing space for comparison operators. Settings for templates do not have effect in this case.

**Comment by achappell** [comment]
+1

**Comment by awg0020** [comment]
+1

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
