### ISSUE TITLE
How to run coveralls

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1954]
I would like to run coveralls under Window (emulation?)
How should I configure the .travis.yml file?

**Comment by mihaipopescu** [comment]
Coveralls is just the UI for the coverage data `lcov` is generating.

You can also generate the coverage data locally running `make coverage_html` (if you are using a Gnu make generator) after building and running tests but I've never tried it on Windows so I'm unsure.

How do you build under windows?

**Comment by gmaurel** [comment]
I wish this to see coverage/coveralls difference(s) between the runs 1) under linux, 2) under Windows.

**Comment by mihaipopescu** [comment]
Our code is not very platform dependent so I won't expect too much of a difference. Why do you think there could be one?
