### ISSUE TITLE
C comment end-marker */ mistaken for arithmetic operator

### ISSUE THREAD

**Issue by rblaine** [uncrustify/uncrustify#1966]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp
' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

When running uncrustify-0.67 against this file:

```
#define FLAG1               0x101  /* struct foo should not be used.
The struct is unsafe */
```
with these options:

```
pp_ignore_define_body = True
sp_arith                = Add
```

uncrustitfy fails to recognize that there is a C block comment at the end of that #define line. The result is that it attempts to format the comment as code, in particular treating the '\*/' as an arithmetic operator ('\*') which requires a space afterwards (per sp_arith=Add). This corrupts the end marker of the block comment:

```
#define FLAG1               0x101  /* struct foo should not be used.
The struct is unsafe * /
```

Here is debug output:

```
# Uncrustify-0.67
sp_arith                        = add
pp_ignore_define_body           = true
# option(s) with 'not default' value: 2
#
# -=====-
# Line              Tag           Parent          Columns Br/Lvl/pp     Flag   Nl  Text
#   1>          PREPROC[       PP_DEFINE][  1/  1/  2/  0][1/1/0][ 1000e0001][0-0] #
#   1>        PP_DEFINE[            NONE][  2/  2/  8/  0][1/1/0][     10001][0-0]  define
#   1>        PP_IGNORE[            NONE][  9/  9/ 14/  1][1/1/0][     40001][0-0]         FLAG1
#   1>        PP_IGNORE[            NONE][ 29/ 29/ 69/ 15][1/1/0][         1][0-0]                             0x101  /* struct foo should not be used.
#   1>          NEWLINE[            NONE][ 69/ 69/  1/  0][0/0/0][         0][1-0]
#   2>             WORD[            NONE][  1/  1/  4/  0][0/0/0][     70000][0-0] The
#   2>           STRUCT[            NONE][  5/  5/ 11/  1][0/0/0][     10000][0-0]     struct
#   2>             TYPE[          STRUCT][ 12/ 12/ 14/  1][0/0/0][     10000][0-0]            is
#   2>             WORD[          STRUCT][ 15/ 15/ 21/  1][0/0/0][   1800000][0-0]               unsafe
#   2>         PTR_TYPE[            NONE][ 22/ 22/ 23/  1][0/0/0][ 100000000][0-0]                      *
#   2>            ARITH[            NONE][ 24/ 23/ 24/  0][0/0/0][ 100040000][0-0]                        /
#   2>          NEWLINE[            NONE][ 25/ 24/  1/  0][0/0/0][         0][1-0]
# -=====-
```

**Comment by rblaine** [comment]
This patch seems to fix the issue, although I've no idea how kosher this approach is or whether it has other side-effects:

```
diff --git a/src/tokenize.cpp b/src/tokenize.cpp
index a2ae8009..6e4f67e1 100644
--- a/src/tokenize.cpp
+++ b/src/tokenize.cpp
@@ -1775,8 +1775,8 @@ static bool parse_next(tok_ctx &ctx, chunk_t &pc)
             break;
          }
 
-         // Quit on a C++ comment start
-         if ((ch == '/') && (ctx.peek(1) == '/'))
+         // Quit on a C or C++ comment start
+         if ((ch == '/') && ((ctx.peek(1) == '/') || (ctx.peek(1) == '*')))
          {
             break;
          }
@@ -2069,6 +2069,7 @@ void tokenize(const deque<int> &data, chunk_t *ref)
    chunk_t *rprev       = nullptr;
    bool    last_was_tab = false;
    size_t  prev_sp      = 0;
+   int     num_stripped = 0;
 
    cpd.unc_stage = unc_stage_e::TOKENIZE;
 
@@ -2126,12 +2127,18 @@ void tokenize(const deque<int> &data, chunk_t *ref)
                break;
             }
             chunk.str.pop_back();
+            num_stripped++;
          }
       }
 
       // Store off the end column
       chunk.orig_col_end = ctx.c.col;
 
+      if ((chunk.type == CT_COMMENT_MULTI || chunk.type == CT_COMMENT || chunk.type == CT_COMMENT_CPP)
+          && pc && pc->type == CT_PP_IGNORE) {
+            chunk.orig_col_end -= num_stripped;
+      }
+
       // Add the chunk to the list
       rprev = pc;
       if (rprev != nullptr)
@@ -2201,7 +2208,7 @@ void tokenize(const deque<int> &data, chunk_t *ref)
          else if (cpd.in_preproc == CT_PP_IGNORE)
          {
             // ASSERT(cpd.settings[UO_pp_ignore_define_body].b);
-            if (pc->type != CT_NL_CONT && pc->type != CT_COMMENT_CPP)
+            if (pc->type != CT_NL_CONT && pc->type != CT_COMMENT_CPP && pc->type != CT_COMMENT && pc->type != CT_COMMENT_MULTI)
             {
                set_chunk_type(pc, CT_PP_IGNORE);
             }
```

**Comment by gmaurel** [comment]
Please, make a PR of it.

**Comment by mihaipopescu** [comment]
@rblaine a PR will trigger our tests to be verified with your change. Diff looks decent.

**Comment by guy-maurel** [comment]
PR #2269 is a bugfix proposal.
Please test it and report.
