### ISSUE TITLE
invalid indentation with C++11 initializer lists

### ISSUE THREAD

**Issue by falko-strenzke** [uncrustify/uncrustify#1968]
This is what uncrustify "Uncrustify-0.67_f" produces, see the indentation error under case 1:

            switch(m_hndshk_msg_nb++) // increment only if we actually use it
            {
                case 0:
                  result = std::vector<dtls_hndsh_fragm_offs_and_len_t>(
                    {std::make_pair(5, 6), std::make_pair(
                       0,
                       8
                     ),
                     std::make_pair(7, hndsh_msg_len - 7)}
                  );
                  break;
                case 1:
                  result = std::vector<dtls_hndsh_fragm_offs_and_len_t>(
          {
            std::make_pair(0, 1 + offset),
            std::make_pair(1 + offset, 2),
            std::make_pair(3 + offset, 4),
            std::make_pair(6 + offset, 6),
            std::make_pair(10 + offset, 6),
            std::make_pair(11 + offset, 6),
            std::make_pair(49 + offset, hndsh_msg_len - (49 + offset)),

            std::make_pair(45 + offset, 4),
            std::make_pair(35 + offset, 5),
            std::make_pair(25 + offset, 5),
            std::make_pair(15 + offset, 5),
            std::make_pair(5 + offset, 5),
            std::make_pair(40 + offset, 5),
            std::make_pair(30 + offset, 5),
            std::make_pair(20 + offset, 5),
            std::make_pair(10 + offset, 5)
          }
                  );
                  break;
                default:
                  result = std::vector<dtls_hndsh_fragm_offs_and_len_t>(
                    {std::make_pair(0, 1), std::make_pair(
                       5,
                       6
                     ),
                     std::make_pair(0, 8),
                     std::make_pair(7, hndsh_msg_len - 7)}
                  );
            }

**Comment by guy-maurel** [comment]
Please push the input and the config files.
If possible, put away what is not necessary
