### ISSUE TITLE
use_options_overriding_for_qt_macros doesn't override some options

### ISSUE THREAD

**Issue by pento** [uncrustify/uncrustify#1969]
I've noticed this with the `sp_before_unnamed_ptr_star` and `sp_inside_angle` options on my codebase, but there may be others.

Test `uncrustify.cfg`:

```cfg
use_options_overriding_for_qt_macros = true

sp_before_unnamed_ptr_star = Force
sp_inside_angle = Force
```

Input:

```cpp
Foo::Foo() {
	// sp_before_unnamed_ptr_star
	connect( a, SIGNAL(b(c*)), this, SLOT(d(e*)) );
	// sp_inside_angle
	connect( a, SIGNAL(b(c<d>)), this, SLOT(e(f<g>)) );
}
```

Generated result:

```cpp
Foo::Foo() {
	// sp_before_unnamed_ptr_star
	connect( a, SIGNAL(b(c *)), this, SLOT(d(e *)) );
	// sp_inside_angle
	connect( a, SIGNAL(b(c< d >)), this, SLOT(e(f< g >)) );
}
```

Expected result:

```cpp
Foo::Foo() {
	// sp_before_unnamed_ptr_star
	connect( a, SIGNAL(b(c*)), this, SLOT(d(e*)) );
	// sp_inside_angle
	connect( a, SIGNAL(b(c<d>)), this, SLOT(e(f<g>)) );
}
```

Debug output: https://gist.github.com/pento/fa3bdbbe13f22ca5dc89ed007112e019

Uncrustify version: Uncrustify-0.67_f

**Comment by mwoehlke-kitware** [comment]
> I've noticed this with the `sp_before_unnamed_ptr_star` and `sp_inside_angle` options on my codebase, but there may be others.

That's entirely possible. Well, they'll be easier to add, with #1973. I suppose someone should, at some point, try to do an audit of all the existing options.
