### ISSUE TITLE
sp_after_semi at the end of a structure

### ISSUE THREAD

**Issue by villytiger** [uncrustify/uncrustify#197]
Using the default config uncrustify adds space between semicolon and closing brace of a structure.
// Before uncrustify
struct A {int a;};
// After uncrustify
struct A {int a; };

I think it would be better if uncrustify could process it without adding space. Maybe the sp_after_semi rule should be ignored if there is a closing brace before semicolon.

**Comment by scottbilas** [comment]
FYI this change caused a big regression for us for all single-line methods, especially get/set property methods. We're investigating how to work around it. :/

**Comment by gmaurel** [comment]
Fine, because the actual tests don't rise a problem.
