### ISSUE TITLE
Lining up initialization lists

### ISSUE THREAD

**Issue by jbree** [uncrustify/uncrustify#1979]
Is there a way to line up initialization lists like this?

```
class Foo {
public:
    Foo (
            int p1,
            int p2
            )
    : param1(p1)
    , param2(p2)
    {
    }

private:
    int param1;
    int param2;
};
```

Closest I've been able to come is with this configuration:
```
indent_class                    = true
indent_columns                  = 4
indent_with_tabs                = 0
indent_continue                 = 8
indent_func_class_param         = true

nl_constr_colon                 = add
nl_constr_init_args             = add
nl_fdef_brace                   = add

pos_constr_comma                = lead
pos_constr_colon                = lead

sp_after_comma                  = add

nl_func_def_start_multi_line    = true
nl_func_def_args                = add
nl_func_def_end_multi_line      = true
```

which produces the following:

```
class Foo {
public:
    Foo (
            int p1,
            int p2
            )
        : param1(p1)
        , param2(p2)
    {
    }

private:
    int param1;
    int param2;
};
```

Everything is the way I'd like it, except I can't find a way to move the initialization list to be lined up with the constructor name and open/close braces.

Thanks

**Comment by mwoehlke** [comment]
Didn't try, but I think some combination of `indent_constr_colon`, `indent_ctor_init_leading` and/or `indent_ctor_init` may be what you are looking for?

**Comment by jbree** [comment]
Aha! Thank you. I had previously tried setting `indent_ctor_init = -4` to no effect, but after reading your comment it occurred to me that `indent_constr_colon = true` must be set for the aforementioned setting to take effect. I get my desired output by adding the following to my previous configuration:

```
indent_constr_colon             = true
indent_ctor_init_leading        = 0
indent_ctor_init                = -4
```
