### ISSUE TITLE
nl_before_func_body_def doesn't work on operators

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#2005]
`nl_before_func_body_def` adds newlines before e.g. `int bar::bar() {...}`, but not e.g. `int bar::operator!() {...}`. Same for freestanding operators (e.g. `int operator!(ClassType) {...}` and operators defined inside a class body.

I suspect something inside of `newlines_func_pre_blank_lines` needs tweaking...

**Comment by guy-maurel** [comment]
Do you have any example, input and config files?
