### ISSUE TITLE
compiler warning at chunk_list.cpp

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#2009]
Using /usr/bin/c++, I get a warning under LinuxMint 19:
```.txt
/home/guy/Software/uncrustify/src/chunk_list.cpp:98:17: warning: unused function 'chunk_ppa_search' [-Wunused-function]
static chunk_t *chunk_ppa_search(chunk_t *cur, const check_t check_fct, const scope_e scope = scope_e::ALL, const direction_e dir ...
```
Please, have a look!

**Comment by mwoehlke-kitware** [comment]
Oops... good catch! (Alas, my interesting warnings get buried under a pile of `-Wconversion`, which probably has something to do with how I missed this... sorry!)
