### ISSUE TITLE
New lines configuration conflict

### ISSUE THREAD

**Issue by sorenvonsarvort** [uncrustify/uncrustify#2021]
Assume we have some CPP source:

```c++
if (user->Exists(firstName, lastName)) {
	printSomeStuff();
	return false;
}
```

I want it to be formatted as:

```c++
if (user->Exists(
	firstName,
	lastName
)) {
	printSomeStuff();
	return false;
}
```

But Uncrustify puts redundant spaces:

```c++
if (user->Exists(
	firstName,
	lastName
    )) {
	printSomeStuff();
	return false;
}
```

The part of the config responsible for this looks like:

```
# Controls the indent of a close paren after a newline.
# 0: Indent to body level
# 1: Align under the open paren
# 2: Indent to the brace level
indent_paren_close              = 2        # unsigned number
```

Are there any options to make it formatted like in the 2nd version?

**Comment by guy-maurel** [comment]
I cannot reproduce.
Please push your complete configuration file.

**Comment by sorenvonsarvort** [comment]
I have lost the config and cannot reproduce the problem with `Uncrustify-0.68_f`

Let's assume the problem was fixed in some commit.
