### ISSUE TITLE
Add support for "Kevlin Henney-inspired style" with newline before function opening parenthesis

### ISSUE THREAD

**Issue by martinmoene** [uncrustify/uncrustify#2025]
**Edit**: initially I attributed the style described below to Kevlin Henney, however it is not present in his presentation referenced. Nonetheless, it looks like a natural continuation of it to me.

Inspired on the part [*Sustainable spacing*](https://www.slideshare.net/Kevlin/seven-ineffective-coding-habits-of-many-programmers/18) ([video](https://vimeo.com/97329157#t=14m35s)) in Kevlin Henney's presentation *Seven Ineffective Coding Habits of Many Programmers*, I'd like to suggest to support a layout for a function declaration/definition/call where `(` and `)` are on different lines *with the opening parenthesis on its own line*:
```
int foo
(
    char chr
    ....
)
{
    ....
}
```

Currently there are configuration options:
```
# Whether to add newline after '(' in a function declaration if '(' and ')' are in different lines.
nl_func_decl_start_multi_line   = true    # false/true

# Whether to add newline after '(' in a function definition if '(' and ')' are in different lines.
nl_func_def_start_multi_line    = true    # false/true

# Whether to add newline after '(' in a function call if '(' and ')' are in different lines.
nl_func_call_start_multi_line   = true    # false/true
```
with which one can produce:
```
int foo(
    char chr
    ....
)
{
    ....
}
```
Suggested style might need these options:
- Whether to add newline *before* '(' in a function declaration if '(' and ')' are in different lines.
- Whether to add newline *before* '(' in a function definition if '(' and ')' are in different lines.
- Whether to add newline *before* '(' in a function call if '(' and ')' are in different lines.

Edit: similarly for template parameters
```
template
<
    typename T
    ....
>
void foo
(
    T tee
    ....
)
{
    ....
}
```

**Comment by guy-maurel** [comment]
And now?
I don't understand what you wanted to get.
Could you please push some files to explain?
