### ISSUE TITLE
Prevent aligning multi line strings on var assignments?

### ISSUE THREAD

**Issue by flodnv** [uncrustify/uncrustify#2038]
Hi!
working version: uncrustify 0.67
We have this C++ code snippet:
```cpp
    std::string query;

    if (condition) {
        query = "SELECT value "
            "FROM table "
            "WHERE name='something' "
              "AND value=" + SQ(otherVar);
    } else {
        ...
    }
```

We need the `"AND value=" + SQ(otherVar);` line to stay where it is. Currently, uncrustify fixes the alignment and places all double quotes on the same column. I understand why, but we don't want this to happen (because we want to align our query strings differently to optimize for readability).   

I tried a lot of things, but I found no option that allows to control this. Is it just not possible to control this? Would you consider adding this as an improvement?

PS: We love what you do, thanks a lot!

**Comment by guy-maurel** [comment]
Not yet possible with uncrustify, sorry
