### ISSUE TITLE
Option for unbuffered output

### ISSUE THREAD

**Issue by pierpaolobagnasco** [uncrustify/uncrustify#2043]
When I execute Uncrustify and I redirect both stdout and stderr to the same file, the outputs are mixed.
For instance, when I execute:
`uncrustify -c config.cfg source_code.c --check > log.txt 2>&1`
log.txt contains mixed output:
```
[...]
Parsing: source_code.c as languaFAIL: source_code.c (File size changed from 803 to 800)
ge C
[...]
```
I solved this by adding the following lines to the Uncrustify's main function:
```c
setvbuf(stdout, NULL, _IONBF, 0);
setvbuf(stderr, NULL, _IONBF, 0);
```
But I'd prefer to stick with master/release version, and not to create my own Uncrustify's version.

Is it possible to always use unbuffered output, or at least to add an option for it?

Thanks!

**Comment by gmaurel** [comment]
Could you please make a PR (push request) for it?

**Comment by gmaurel** [comment]
No more comment since 26 Oct 2018
I close.
