### ISSUE TITLE
Continuation of C array declaration

### ISSUE THREAD

**Issue by psnsilva** [uncrustify/uncrustify#2045]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Given the following snippet of code:
```C
static void wpa_smk_send_error(struct wpa_authenticator *wpa_auth,
			       struct wpa_state_machine *sm, const u8 *peer,
			       u16 mui, u16 error_type)
{
	u8 kde[2 + RSN_SELECTOR_LEN + ETH_ALEN +
	       2 + RSN_SELECTOR_LEN + sizeof(struct rsn_error_kde)];
	u8 *pos;
	struct rsn_error_kde error;

	wpa_auth_logger(wpa_auth, sm->addr, LOGGER_DEBUG,
			"Sending SMK Error");
(...)
```
applying `uncrustify` on it, I was expecting to have the `u8 kde[...]` definition continuation line  indented by 2 tabs (as defined by `indent_continue = 8`) or at least unchanged.

However, applying `uncrustify` (debug file attached: [debugfile.txt](https://github.com/uncrustify/uncrustify/files/2491011/debugfile.txt)), the result is the following:
```C
static void wpa_smk_send_error(struct wpa_authenticator *wpa_auth,
		struct wpa_state_machine *sm, const u8 *peer,
		u16 mui, u16 error_type)
{
	u8 kde[2 + RSN_SELECTOR_LEN + ETH_ALEN +
	2 + RSN_SELECTOR_LEN + sizeof(struct rsn_error_kde)];
	u8 *pos;
	struct rsn_error_kde error;

	wpa_auth_logger(wpa_auth, sm->addr, LOGGER_DEBUG,
			"Sending SMK Error");
(...)
```

**Comment by gmaurel** [comment]
Please push your config

**Comment by psnsilva** [comment]
I assumed the debug file was enough. Here it is the configuration file (renamed to *.txt as GitHub does not allow *.cfg files): [uncrustify.txt](https://github.com/uncrustify/uncrustify/files/2515806/uncrustify.txt)

**Comment by psnsilva** [comment]
> #2147 is bugfix proposal.
> Please test it and report.

I had the chance to test your branch but it seems like is still not corrected.

Original:
```C
int function()
{
	uint8_t kde[2 + RSN_SELECTOR_LEN + ETH_ALEN +
2 + RSN_SELECTOR_LEN + sizeof(struct rsn_error_kde)];
	uint8_t *pos;
	struct rsn_error_kde error;
}
```
Expected:
```C
int function()
{
	uint8_t kde[2 + RSN_SELECTOR_LEN + ETH_ALEN +
						2 + RSN_SELECTOR_LEN + sizeof(struct rsn_error_kde)];
	uint8_t *pos;
	struct rsn_error_kde error;
}
```
Got:
```C
int function()
{
	uint8_t kde[2 + RSN_SELECTOR_LEN + ETH_ALEN +
	2 + RSN_SELECTOR_LEN + sizeof(struct rsn_error_kde)];
	uint8_t *pos;
	struct rsn_error_kde error;
}
```

**Comment by guy-maurel** [comment]
Please check we have the same the options:
```.cfg
indent_columns  = 4
indent_continue = 8
indent_with_tabs = 0
```
I get:
```.cpp
static void wpa_smk_send_error(struct wpa_authenticator *wpa_auth,
        struct wpa_state_machine *sm, const u8 *peer,
        u16 mui, u16 error_type)
{
    u8 kde[2 + RSN_SELECTOR_LEN + ETH_ALEN +
            2 + RSN_SELECTOR_LEN + sizeof(struct rsn_error_kde)];
    u8 *pos;
    struct rsn_error_kde error;

    wpa_auth_logger(wpa_auth, sm->addr, LOGGER_DEBUG,
            "Sending SMK Error");
}

int function()
{
    uint8_t kde[2 + RSN_SELECTOR_LEN + ETH_ALEN +
            2 + RSN_SELECTOR_LEN + sizeof(struct rsn_error_kde)];
    uint8_t *pos;
    struct rsn_error_kde error;
}
```
Please test and report.
