### ISSUE TITLE
Revisit Python "requirement"?

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#2055]
Right now, we have a "hard" dependency on Python. However, it appears that we currently only need Python for a) testing, b) emscripten and c) retrieving the git version.

Not all users will care about these things. For someone that just wants to build uncrustify, it might be convenient to be able to skip the Python dependency (especially on Windows).

For that matter, we *might* be able to rewrite the version script in pure CMake.

**Comment by CDanU** [comment]
We also use it to generate punc.py: #1761

**Comment by mwoehlke-kitware** [comment]
Ack, my bad :flushed:.

Actually, I'm an idiot; since #1852 we use it a whole bunch. But there is only [one line](https://github.com/uncrustify/uncrustify/blob/ab9eaa20f77182629448d78cec6433836536e642/CMakeLists.txt#L186) where it is mentioned, because it gets used through a macro, and apparently I managed to overlook that one line when looking for uses.

Never mind!
