### ISSUE TITLE
Questions about align_var_def_span, align_var_def_gap and align_var_def_thresh

### ISSUE THREAD

**Issue by larixsoft** [uncrustify/uncrustify#2056]
Would you please give me more details about how to use these three options?
I guess the align_var_def_gap is used to define how many spaces can be put between the variable type and the variable itself when it is aligned with other variables, right?

How about the definition of align_var_def_span and align_var_def_thresh? 

Thank you so much!

**Comment by guy-maurel** [comment]
_align_var_def_gap_
The gap for aligning variable definitions.

_align_var_def_span_
The span for aligning variable definitions.
0 = Don't align (default).

_align_var_def_thresh_
The threshold for aligning variable definitions.
Use a negative number for absolute thresholds.
0 = No limit (default)

Try the program **universalindentgui** to better see what is going on.
