### ISSUE TITLE
Different default rules on OSX and Linux

### ISSUE THREAD

**Issue by MartinDelille** [uncrustify/uncrustify#2063]
I noticed that running uncrustify on two different plateform give diffent result with the following configuration: https://gist.github.com/MartinDelille/66bc527587764a6ec215690bf95f5b42

Given the following code:

```
parser.addOptions({
	{{ "a", "actor" },
	  "Name of the actor",
	  "actor",
	  "Julie" },
	{{ "f", "file" },
	  "File to output the recording",
	  "file" }
});
```

OSX version leaves it unaffected, but linux version give the following result (notice the space between to consecutive `{`):

```
parser.addOptions({
	{ { "a", "actor" },
	  "Name of the actor",
	  "actor",
	  "Julie" },
	{ { "f", "file" },
	  "File to output the recording",
	  "file" }
});
```

I finally manage to have a consistent configuration by adding the following line:

```
sp_type_brace_init_lst = add
```

**Comment by mwoehlke-kitware** [comment]
You didn't tell us what version of uncrustify you are using. Are you running the same version of uncrustify in both cases? I suspect the difference isn't the platform, but different versions of uncrustify. (There is very little platform specific code in uncrustify, and most of it is for Windows, because that is not a POSIX platform.)

**Comment by MartinDelille** [comment]
I'm using Uncrustify-0.67_f on my mac (installed from Brew).

@imadKimouche Can you tell me which one you are using on Linux?

**Comment by imadKimouche** [comment]
```
Name         : uncrustify
Version      : 0.64
Release      : 2.fc26
Arch         : x86_64
```

**Comment by mwoehlke-kitware** [comment]
0.64 vs. 0.67... that would do it. There have been changes/fixes for handling braced initializer lists since 0.64 (n.b. `sp_type_brace_init_lst` was introduced in 0.65, and #1786 which will be fixed in the upcoming 0.68).

**Comment by MartinDelille** [comment]
Ok sorry we should have checked that. 

Since my configuration is not complete, I was wondering if there was a way to identify the missing configuration introduced by the new versions?

**Comment by mwoehlke-kitware** [comment]
[The changelog](https://github.com/uncrustify/uncrustify/blob/master/ChangeLog) lists new options. You can also use `uncrustify --update-config` to add unspecified options to your config.

**Comment by MartinDelille** [comment]
Great! Thank you so much! Would you accept donation via https://liberapay.com/?
