### ISSUE TITLE
Unexpected indentation for "if condition + Function call + Parameters in Multi line " line

### ISSUE THREAD

**Issue by ssaju2** [uncrustify/uncrustify#2077]
I am getting the following indentation problem from 0.60 version to 0.67 version.  This is specifically observed with "if condition + Function call + Parameters in Multi line " statement.   What settings I have to change ? I am attaching here with config file.
[defaults_merged.zip](https://github.com/uncrustify/uncrustify/files/2590615/defaults_merged.zip)

    if (GetFilename(FileHandle,
            FilePath,
            (Loca),
            &(Value),
            sizeof(Value)) !=
        sizeof(Value))
    {

    
    if (GetFilename(FileHandle,
        FilePath,
        (Loca),
        &(Value),
        sizeof(Value)) !=
        sizeof(Value))
    {

**Comment by CDanU** [comment]
I assume your first block is the input and it should stay the same, the 2nd block is the output that you are currently getting, right? 

See if adding both of those options helps:

```sql
# True:  indent continued function call parameters one indent level
# False: align parameters under the open paren.
indent_func_call_param          = true     # false/true

# Double the indent for indent_func_xxx_param options.
# Use both values of the options indent_columns and indent_param.
indent_func_param_double        = true     # false/true
```

**Comment by ssaju2** [comment]
The second option give another one more indentation(4 space). It fixes the issue I have mentioned earlier. But it cause indentation for all function definition as well as function calls.
STATUS
Device::PciRead(
    IN Context Adapter
    )
{

STATUS
Device::PciRead(
        IN Context Adapter
        )
{



TraceInfo(Adapter, TRACE, "LogMessage",
                        Adapter->GetContext,

TraceInfo(Adapter, TRACE
[uncrustify.zip](https://github.com/uncrustify/uncrustify/files/2592169/uncrustify.zip)
, "LogMessage",
                            Adapter->GetContext,

**Comment by ssaju2** [comment]
I would like to say function param indentation not working with in if-condition.

**Comment by ssaju2** [comment]
Any more help ?

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by ssaju2** [comment]
I don't see any difference with latest version.  Will try with different options.
