### ISSUE TITLE
Trying to add a option and getting a test failure

### ISSUE THREAD

**Issue by Gary-Ash** [uncrustify/uncrustify#2079]
I'm getting a source format error when I run the test rig where do a look to fix it?
Output below:
Test project /Users/garyash/Documents/Personal/Projects/uncrustify/build
      Start  1: c-sharp
 1/14 Test  #1: c-sharp ..........................   Passed    1.41 sec
      Start  2: c
 2/14 Test  #2: c ................................   Passed    3.44 sec
      Start  3: cpp
 3/14 Test  #3: cpp ..............................   Passed    6.78 sec
      Start  4: d
 4/14 Test  #4: d ................................   Passed    0.64 sec
      Start  5: ecma
 5/14 Test  #5: ecma .............................   Passed    0.07 sec
      Start  6: imported
 6/14 Test  #6: imported .........................   Passed    0.06 sec
      Start  7: java
 7/14 Test  #7: java .............................   Passed    0.36 sec
      Start  8: objective-c
 8/14 Test  #8: objective-c ......................   Passed    1.36 sec
      Start  9: pawn
 9/14 Test  #9: pawn .............................   Passed    0.19 sec
      Start 10: vala
10/14 Test #10: vala .............................   Passed    0.14 sec
      Start 11: staging
11/14 Test #11: staging ..........................   Passed    0.07 sec
      Start 12: sources_format
12/14 Test #12: sources_format ...................***Failed    2.08 sec
      Start 13: cli_options
13/14 Test #13: cli_options ......................   Passed    0.18 sec
      Start 14: sanity
14/14 Test #14: sanity ...........................   Passed    0.00 sec

93% tests passed, 1 tests failed out of 14

Total Test time (real) =  16.80 sec

The following tests FAILED:
	 12 - sources_format (Failed)
Errors while running CTest

**Comment by CDanU** [comment]
This means some of the  source arn't formatted correctly, we have a build target that should handle this ... it should be `format-sources`

**Comment by Gary-Ash** [comment]
that did it. Thank you!
