### ISSUE TITLE
Improving Robustness: Prevent Aweful Crashes

### ISSUE THREAD

**Issue by Alexander-Shukaev** [uncrustify/uncrustify#208]
Uncrustify will crash on the following:

```c++
namespace MyNamespace {
```

and this as well:

```c++
class MyClass::Private {
```

There are probably more examples, but they are all trivial, and crashing on such simple snippets is just unacceptable. Please fix it, probably by introducing proper errors, like you've already done for unmatched parentheses.

If your question is why would someone format a snippet like this? Imagine fragmented formatting when Uncrustify is integrated in some text editor.

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
