### ISSUE TITLE
cannot build for win 32/64

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#2083]
Trying to build for win 32/64, by using:
```.txt
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-mingw32.cmake -DCMAKE_EXE_LINKER_FLAGS="-static -s" ..
```
I get an error:
```.txt
    /usr/bin/cc      -Wl,--whole-archive CMakeFiles/cmTC_412f9.dir/objects.a -Wl,--no-whole-archive  -o cmTC_412f9.exe -Wl,--out-implib,libcmTC_412f9.dll.a -Wl,--major-image-version,0,--minor-image-version,0 
    /usr/bin/ld: unrecognized option '--major-image-version'
```
Some info is to get at:
https://forum.qt.io/topic/89498/gcc-error-during-cross-compile-setup
and sugest:
`set(CMAKE_SYSTEM_NAME Generic) in your cmake toolchain file`

Is it correct?

**Comment by jibsen** [comment]
Cross compile is [working on Travis](https://travis-ci.org/uncrustify/uncrustify/jobs/456521142) as of yesterday, did you change something on your dev machine?

The toolchain file should do this, but try setting CC and CXX to the cross compiler binaries and see if that helps?

**Comment by guy-maurel** [comment]
Thanks!
G++-mingw-w64 was missed.
