### ISSUE TITLE
Various issues with the output of --update-config-with-doc

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#2084]
This is a collection of various documentation issues I noticed in 0.68

First create a default configuration file:
uncrustify --update-config-with-doc -o default.cfg

When inspecting default.cfg, I find the following:
1. There are nine cases of a character that is outside the standard ASCII range. This used to be --> but is now some UTF-8 character. The first two cases are on line 913 (in the documentation of indent_brace_parent.)
Is that intentional?

2. The following type of block appears several times:
```
# How to align the '*' in variable definitions.
#
# 0: Part of the type     'void *   foo;' (default)
# 1: Part of the variable 'void     *foo;'
# 2: Dangling             'void    *foo;'
align_var_def_star_style        = 0        # unsigned number
```
Is it intentional that here is a space between void and * for style 0? It says "part of the type", but as it is written, it is not "part of the type".

And, there is no explanation of "Dangling" and I'm not sure that users understand the difference between style 1 and style 2.

3. Possibly wrong typename used in the following:
```
# How to align the '&' in typedefs.
#
# 0: Align on typedef type, ignore '&' (default)
# 1: The '&' is part of type name: 'typedef int  &pint;'
# 2: The '&' is part of the type, but dangling: 'typedef int &pint;'
align_typedef_amp_style         = 0        # unsigned number
```
I think the new type ought to be named intref because the p in pint will probably be understood as pointer.

And this case makes the dangling form really confusing.

4. Possible wrong term used in the following:
```
# Add or remove newline between return type and function name inside a class
# definition. If set to ignore, nl_func_type_name or nl_func_proto_type_name
# is used instead.
nl_func_type_name_class         = ignore   # ignore/add/remove/force
```
Should this not have been "... inside a class **declaration**. ..." ?

**Comment by mwoehlke-kitware** [comment]
> There are nine cases of [UTF-8...] Is that intentional?

Yes. It's 2018, and English is not the only language in existence.

> This used to be --> but is now some UTF-8 character.

Right. It's now '→', which is the same thing, sans ASCIIfication. ("Some UTF-8 character"? Doesn't your computer understand UTF-8?)

> Is it intentional that [in (2)] is a space between void and * for style 0?

Eh... "part of the type" doesn't mean "the type" can't have spaces ("`unsigned int`" :slightly_smiling_face:), and depending on your other options, it might. OTOH I'm not sure how much it matters... anyone else have a preference? (Anyway, that's how it was in 0.67... I changed these to use `0: text` instead of `0=text`, but the examples are unchanged.)

> And, there is no explanation of "Dangling"

Same thing (hasn't changed). Any suggestions? (Preferably a better explanation that is only a few words?)

> Possibly wrong typename[...]

Well, it's just an example :slightly_smiling_face:. Okay, it's a fairly lousy example. Again, I'll take suggestions? (We probably should try to make this more consistent with `align_var_def_{star,amp}_style`. Alas, I missed that in the Great Documentation Polishing.)

> Should this not have been "... inside a class *declaration*. ..." ?

No. A class declaration doesn't have an "inside".

Note:
```c++
// declaration
class foo;

// definition
class foo {
  void /*nl_func_type_name_class*/ bar();
};
```

In general, things called "declarations" (which I believe is usually or always synonymous with "*forward* declaration") in C++ don't have bodies.

**Comment by arneforlie** [comment]
>> There are nine cases of [UTF-8...] Is that intentional?

>    Yes. It's 2018, and English is not the only language in existence.

I use a non-English language every day, so I'm quite aware of that. But, according to the coding standard I live with, none-ASCII characters are still not acceptable in source files.
But, if the uncrustify developers are happy, I have no objection. I just thought it was an oversight.

>>    This used to be --> but is now some UTF-8 character.

>    Right. It's now '→', which is the same thing, sans ASCIIfication. ("Some UTF-8 character"? Doesn't your computer understand UTF-8?)

It does of course show up as a right arrow, I meant to say that I didn't know the exact UTF-8 name of it.

>>    Is it intentional that [in (2)] is a space between void and * for style 0?

> Eh... "part of the type" doesn't mean "the type" can't have spaces ("unsigned int" slightly_smiling_face), and depending on your other options, it might.

My intention was to contrast it with style 1 "part of the variable" where there is no space. 
If there can be a space, perhaps "close to the type" and "close to the variable" are better?

> OTOH I'm not sure how much it matters... anyone else have a preference? (Anyway, that's how it was in 0.67... I changed these to use 0: text instead of 0=text, but the examples are unchanged.)

I'm not saying it was any better in 0.67, but since the help text states:
```
There are currently 657 options and minimal documentation.
Try UniversalIndentGUI and good luck.
```
I am merely trying to suggest that it will be easier for users if the option description in config file is consistent.

>>    And, there is no explanation of "Dangling"

> Same thing (hasn't changed). Any suggestions? (Preferably a better explanation that is only a few words?)

To be honest I'm not sure what it means. I think it means that the */& will not be taken into account when aligning variable definitions, like this:
```
char    *foo;
char     foo;
```

>>    Possibly wrong typename[...]
> Well, it's just an example slightly_smiling_face. Okay, it's a fairly lousy example. Again, I'll take suggestions? (We probably should try to make this more consistent with align_var_def_{star,amp}_style. Alas, I missed that in the Great Documentation Polishing.)

I suggested intref

>>    Should this not have been "... inside a class declaration. ..." ?

> No. A class declaration doesn't have an "inside".

You are quite right, I had it wrong.

**Comment by mwoehlke-kitware** [comment]
> But, according to the coding standard I live with, none-ASCII characters are still not acceptable in source files.

Yeah, that's a thing... but slowly changing from what I can tell, thankfully.

> I meant to say that I didn't know the exact UTF-8 name of it.

Ah; your phrasing made me wonder if it was not rendering for you... (FTR, it is "rightwards arrow" :wink:, at least according to kcharselect.)

> But, if the uncrustify developers are happy, I have no objection. I just thought it was an oversight.

Okay... and bringing it up is fair. For my part, though (as the one that made the change) it was intended. (In the process, I also bludgeoned the tests into being Unicode-safe. That was... fun.)

> I think it means that the `*`/`&` will not be taken into account when aligning variable definitions

Yes, that is my understanding. (Well, "taken into account" may not be exactly correct, but that they will be left of the 'alignment line', as in your example.)

> I suggested intref

Alas, that is just the start of the less-than-helpfulness of that option's description. For just that change, I don't know if I'd bother. The whole thing could use rewriting; I was hoping for suggestions for *that* :slightly_smiling_face:. (As in, I agree it's not ideal, but offhand I don't have any better ideas...)

**Comment by guy-maurel** [comment]
PR #2283 is a proposal.
Please have a look and report.
