### ISSUE TITLE
Compiler warning with mingw32

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#2088]
As I try to build with:
```.txt
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-mingw32.cmake -DCMAKE_EXE_LINKER_FLAGS="-static -s" ..
make
```
I get some warnings:
```
[ 60%] Building CXX object CMakeFiles/uncrustify.dir/src/output.cpp.obj
src/output.cpp: In function 'void output_parsed(FILE*)':
src/output.cpp:436:53: warning: unknown conversion type character 'z' in format [-Wformat=]
               pc->flags, pc->nl_count, pc->after_tab);
                                                     ^
src/output.cpp:436:53: warning: format '%s' expects argument of type 'char*', but argument 4 has type 'size_t {aka unsigned int}' [-Wformat=]
src/output.cpp:436:53: warning: unknown conversion type character 'z' in format [-Wformat=]
```
Can anybody help?

**Comment by mwoehlke-kitware** [comment]
Wow... uh, really? See #1913. What version is that compiler?

Given that we're using C++11 these days, and AFAIK C++11 specifies `%z` ([note](https://en.cppreference.com/w/cpp/io/c/fprintf)), that's a compiler bug.

**Comment by mwoehlke-kitware** [comment]
Note: AFAICT, `make_message` didn't actually try to work around *missing* `%z` either, i.e. we've always relied on it working at the library level... it just added some gyrations *literally* for the sole purpose of disguising the code from the compiler's `-Wformat` warning.

That being the case, I'm inclined to recommend... well, ideally, get a non-broken compiler, but failing that, just build with `-Wno-format`.

**Comment by mwoehlke-kitware** [comment]
(On further thought, if it's bothering anyone enough, I'd be okay adding some logic to a "high level" header to try to detect this brain-dead compiler and issue a pragma to turn off -Wformat.)
