### ISSUE TITLE
Sorting of includes is not case sensitive

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#2091]
This is a continuation of a comment I had to #1929 where my comment about sorting and case sensitivity became a bit off topic.

I reported that the sorting of #includes is not case sensitive, resulting in an unexpected ordering.
Test case:
```
#include <AClass.h>
#include <SomeClass.h>
#include <TheClass.h>
#include <iostream>
#include <vector>
```
Generated result:
```
#include <AClass.h>
#include <iostream>
#include <SomeClass.h>
#include <TheClass.h>
#include <vector>
```
Expected output is identical to input.

Debug file
[debug.txt](https://github.com/uncrustify/uncrustify/files/2612579/debug.txt)

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by arneforlie** [comment]
I can't see any improvement.
The sorting is still case-insensitive and the test case behaves the same as before. I have attached the new debug-file.
[debug.txt](https://github.com/uncrustify/uncrustify/files/2727522/debug.txt)

**Comment by arneforlie** [comment]
So the original test case from Nov 24, 2018 isn't sufficient?
Or, do you want me to create a pull request where I add the necessary test to the test directory?
I'll be happy to do so. Do you have any documentation on how to add such a test?

**Comment by mihaipopescu** [comment]
No documentation but a couple of examples you can find in the `staging.test` file. For the tests in that file, the testing framework works differently. We ensure the tests fail and when they will pass the test framework will complain.

I would propose to use a naming convention for github issues, say `gh-2091.[ext]` where ext is the file extension for config, input and output files.

The idea is to make this process more automatic with time, probably with a github bot. But for now we have to create PRs manually.

**Comment by arneforlie** [comment]
Created PR #2161

**Comment by arneforlie** [comment]
Why did you close this? The original problem (i.e. sorting is not case sensitive) is still not solved.
Or are you implying that case insensitive sorting is the correct behaviour?

**Comment by gmaurel** [comment]
I propose to introduce a new option such as:
   mod_sort_include_case_sensitive

Any comment?

**Comment by guy-maurel** [comment]
To be used with the other options **mod_sort_using** and **mod_sort_using**, the name should be:
_mod_sort_case_sensitive_

**Comment by arneforlie** [comment]
Why yet another option? Why not just change the behaviour so that it becomes sensible?
Who ever wants to sort #includes case insensitively?

**Comment by guy-maurel** [comment]
Because sorting was introduced on Nov 26 04:54:26 2007.
Many years ago!
There might give some more users who do not want to change.

**Comment by guy-maurel** [comment]
PR #2293 is a bugfix proposal.
Please test it and report.

**Comment by arneforlie** [comment]
Seems to work fine.
