### ISSUE TITLE
Question: How are include_category_[012] supposed to be used?

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#2092]
While struggling with case insensitive sorting of #includes in #2091 I became aware of the include_category options.
But, I have no idea on how to use them.
I searched the test cases for some example, but I couldn't find anything.

So, given that I would like the #includes in CurrentClass.cpp to be sorted as shown:
```
#include <CurrentClass.h>
#include <AnotherClass.h>
#include <TheClass.h>
#include <iostream
```
I.e. first the header file that matches the name of the current .cpp
Thereafter all other header files sorted case sensitively

Can the include_category options be of any help for this?

**Comment by mihaipopescu** [comment]
As per #959, `include_category_X` defines a regex for the category with priority X (lower numbers have higher priority; current range is [0, 2] but can be extended).

We have only a C# test at the moment with this [config](https://github.com/uncrustify/uncrustify/blob/de24ba6570c209bef7fc927718965a8b27246976/tests/config/sort_using_categ.cfg) but let me know if an equivalent configuration for C++ doesn't work.

As said before, the idea originates from `clang-format` _IncludeCategories_ (see [this](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)) so you can inspire from those regexes (with the note that we're using the regex support from C++).

**Comment by arneforlie** [comment]
I had looked at the C# test but it didn't give much of a clue on how to write a meaningful regex for C++.

Anyway, some googling on how to configure clang-format gave me some hints. I ended up with:
```
mod_sort_include      = true
include_category_0    = ^<[A-Z].*\.h>
include_category_1    = ^<.*
include_category_2    = ""
```

It doesn't move the "main" include to the top though.
Uncrustify doesn't seem to have an equivalent to `IncludeIsMainRegex`

**Comment by mihaipopescu** [comment]
In what usecase would you use it? How would that help?

**Comment by mwoehlke-kitware** [comment]
> In what usecase would you use it?

Always?

> How would that help?

It's common practice that the include corresponding to the current source is first. This helps verify that every header is self-contained.

I believe #1929 (note esp. the point about "gaps") would address this.

**Comment by mihaipopescu** [comment]
Oh, I didn't knew what it was. I'm pasting the feature description here for reference.

```
IncludeIsMainRegex (std::string)

    Specify a regular expression of suffixes that are allowed in the file-to-main-include mapping.

    When guessing whether a #include is the “main” include (to assign category 0, see above), use this regex of allowed suffixes to the header stem. A partial match is done, so that: - “” means “arbitrary suffix” - “$” means “no suffix”

    For example, if configured to “(_test)?$”, then a header a.h would be seen as the “main” include in both a.cc and a_test.cc.
```

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by arneforlie** [comment]
Hmm, I do not understand.
Have you improved the documentation?
or have you implemented support for IncludeIsMainRegex?
or have you added test cases appropriate for C++?

What exactly am I supposed to test?

**Comment by mihaipopescu** [comment]
It's mainly my fault I didn't added more samples but from your previous comments sounded like you found the proper incantation. Didn't you?

**Comment by arneforlie** [comment]
I did eventually found out how to use include_category.
But guy-marels comment seemed to indicate that uncrustify had changed (improved) in some way.
I take it that that isn't the case.

Perhaps I should create a feature request for better documentation (and test case) for include_category.
And another one for adding support for IncludeIsMainRegex.

Following that this issue could be closed.
Do you agree?

**Comment by mihaipopescu** [comment]
I totally agree. Better docs plus samples for each language in the form of tests.

**Comment by arneforlie** [comment]
After adding two new issues, I propose that this is closed.
