### ISSUE TITLE
search for an example for option sp_paren_comma

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#2093]
Has anybody an example for the use of the option **sp_paren_comma** ?
The source:
```.cpp
a(, 1);
```
doesn't works because it is a function call.

**Comment by mwoehlke-kitware** [comment]
Hmm... I'm not sure `(,` is even valid syntax.

I suppose it *might* occur in a macro invocation, but I think that would still parse as a function call:
```c++
#define STR(...) #__VA_ARGS__
char const* const x = STR(, 5);
```
...and even that's arguably pathological.

**Comment by guy-maurel** [comment]
Yes, this is a function call, not what I am looking for:
```.txt
#   4>          FUNC_CALL[               NONE][ 23/ 23/ 26/  1][0/0/0][     40000][0-0]                       STR
```
Any other proposal(s)?
