### ISSUE TITLE
Incorrect formatting of macro

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2097]
Version:  0.68
Config file:  empty (default).

// Test.cpp
`#define UUID_COM_INTERFACE BF08EC25-63D4-4B8B-9409-2D30D3F64546`
`#define VERSION 1.2.3`

// After formatting:
`#define UUID_COM_INTERFACE BF08EC25-63D 4-4B8B-9409-2D 30D 3F64 546`
`#define VERSION 1.2 .3`

These changes will break the code.

The only solution here is to use *INDENT-OFF*.
I would suggest to add an option to globally avoid formatting macros.

**Comment by mwoehlke-kitware** [comment]
You do realize that's *already* broken code, right? `2D30D3F64546` is not a valid token sequence. Nor is `1.2.3`. How do you use these macros?

Normally, constants such as you've shown would be strings...

> I would suggest to add an option to globally avoid formatting macros.

Does `pp_ignore_define_body` help?

**Comment by chris-mich** [comment]
Oh yeah, this is the option I was looking for.  Thank you, case closed! :-)
