### ISSUE TITLE
Whitespace removed around ":" in ternary operator within Objective C method

### ISSUE THREAD

**Issue by regexident** [uncrustify/uncrustify#21]
**uncrustify** turns this:

    [string appendFormat:@"%s", (foo) ? "foo" : "bar"];

into this:

    [string appendFormat:@"%s", (foo) ? "foo":"bar"];

which sucks.

Not sure though, if this happens exclusively when used within methods, or also in other situations.

It will properly preserve the whitespace in this line though:

    char *fooBar = (foo) ? "foo" : "bar";

**Comment by jordanwhitney** [comment]
This is no longer a problem now with #355.  There still isn't a version unfortunately so you have to make your own binary to not have this problem.

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
