### ISSUE TITLE
Bug with align_func_proto_span and align_single_line_func

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2100]
```
# Uncrustify-0.68
indent_columns         = 4
indent_with_tabs       = 0
align_func_proto_span  = 2
align_single_line_func = true
```

// Test.cpp (no formatting is expected)
```
CDictionaryEntryId SectionLabelGet()
{
    int* val( Func< bool >() );
    return 0;
}
```

// Output
```
CDictionaryEntryId SectionLabelGet()
{
    int*           val( Func< bool >() );
    return 0;
}
```

This combination incorrectly aligns "val" with the function name.
Seems like a special case.  If I remove the "*" or "< bool >", it works OK.

**Comment by chris-mich** [comment]
This option is really useful to align function prototypes. For instance (if span = 2):

```
void Func1();
int Func2();

double Func3()
```

Result will be:
```
void   Func1();
int    Func2();

double Func3()
```

For the moment, we set align_func_proto_span=1 to work around the problem, but we would prefer 2.

**Comment by gmaurel** [comment]
#2177 is a bugfix

**Comment by chris-mich** [comment]
I still have the problem in uncrustify-0.72 win64.
