### ISSUE TITLE
1ui32 syntax not supported

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2102]
```
# Uncrustify-0.68
indent_columns   = 4
indent_with_tabs = 0

```
// Test.cpp (no changes are expected)
`unsigned __int32 b = 1ui32;`

// Output
`unsigned __int32 b = 1ui 32;`

This syntax is probablement ms-specific, but this code will not compile anymore.

**Comment by guy-maurel** [comment]
Please make a test and report.
