### ISSUE TITLE
Problem with & operator and enum classes

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2103]
```
# Uncrustify-0.68
indent_columns   = 4
indent_with_tabs = 0
sp_before_byref  = remove

```
// Test.cpp (no changes are expected)
```
int i1 = EEnumType::a & EEnumType::b;
int i2 = a & b;

```

// Output
```
int i1 = EEnumType::a& EEnumType::b;
int i2 = a & b;

```

When dealing with enum classes, Uncrustify seems to have trouble with the & operator.

**Comment by chris-mich** [comment]
Still a problem in uncrustify-0.72 win64

**Comment by chris-mich** [comment]
Still a problem in uncrustify-0.73 win64

**Comment by guy-maurel** [comment]
Sorry, I cannot reproduce.
Show more data, please

**Comment by chris-mich** [comment]
You are right, the problem as mentioned above is fixed!
However, if found this particular case:

Before: 
`int i1 = EEnumType::Enum1 & myEnum;`

After:
`int i1 = EEnumType::Enum1& myEnum;`

Where "EEnumType::Enum1" is the enum value, and "myEnum" is a variable of type "EEnumType" for instance.
Like in the exemple below:

```
enum class EEnumType
{
   Enum1,
   Enum2
};

void Test( EEnumType myEnum )
{
   int i = EEnumType::Enum1 & myEnum;
}
```

**Comment by guy-maurel** [comment]
PR #3459 is a bugfix proposal.
Please test it and report.
