### ISSUE TITLE
align_same_func_call_params not working as expected

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2105]
```
# Uncrustify-0.68
indent_columns   = 4
indent_with_tabs = 0
align_same_func_call_params      = true
align_same_func_call_params_span = 1

```

// Test.cpp
```
void Test()
{
    CallFunction( aa, bb, cc );       // Params should be aligned
    CallFunction( a,  b,  c );        // Params should be aligned
    CallFunction( aaa, bbbb, cccc );
    CallFunction2( aaaa,  bbbbb,   ccccc );
    CallFunction3( aaaaa, bbbbbbb, ccccccc );
}
```
// Output 
```
void Test()
{
    CallFunction( aa,  bb,   cc );          // Good
    CallFunction( a,   b,    c );           // Good 
    CallFunction( aaa, bbbb, cccc );        
    CallFunction2( aaaa, bbbbb, ccccc );    // Bad
    CallFunction3( aaaaa, bbbbbbb, ccccccc );   
}
```

// Expected result
```
void Test()
{
    CallFunction( aa,  bb,   cc );
    CallFunction( a,   b,    c );
    CallFunction( aaa, bbbb, cccc );
    CallFunction2( aaaa,  bbbbb,   ccccc );
    CallFunction3( aaaaa, bbbbbbb, ccccccc );
}
```

The parameters of "CallFunction" are aligned correctly.
However, I'm wondering with Uncrustify is messing with the alignment of CallFunction2. 

```

**Comment by chris-mich** [comment]
It looks to me like "align_same_func_call_params" is doing the right thing, as it is aligning the parameters of successive calls to the SAME function (CallFunction), as shown in my example.

The problem is that the option is messing with the alignment of the other functions with a DIFFERENT name (CallFunction2 in my example).

**Comment by guy-maurel** [comment]
Is it a typo?
I get:
Uncrustify_d-0.68.1-94-fcba5989
Parsing: chris-mich.cpp as language CPP
```.cpp
void Test()
{
    CallFunction( aa,  bb,   cc );    // Params should be aligned
    CallFunction( a,   b,    c );     // Params should be aligned
    CallFunction( aaa, bbbb, cccc );
    CallFunction2( aaaa,  bbbbb,   ccccc );
    CallFunction2( aaaaa, bbbbbbb, ccccccc );
}
```

**Comment by chris-mich** [comment]
No, it was not a typo.  :-)
Like I pointed out, "align_same_func_call_params" works well for aligning arguments of MULTIPLE (SAME) calls to the same function.

The problem we have is that it is messing up the alignment of a SINGLE (NOT SAME) function call.  

In my example, the programmer manually aligned the parameters of CallFunction2 and CallFunction3, because he  knew  that Uncrustify would not be able to make this alignment itself.
He expected Uncrustify to align CallFunction, but not the two others, since they are different function calls.

Let's try with another example.


Before:
```
void Test()
{
    DoubleAdd( doubleValue, dv );
    FloatAdd(  floatValue,  fv );    // Developer made this alignment himself
}
```
After:
```
void Test()
{
    DoubleAdd( doubleValue, dv );
    FloatAdd( floatValue, fv );   // Manual alignment is lost!!
}
```

**Comment by guy-maurel** [comment]
Yes, because os sp_inside_fparen and sp_after_comma

**Comment by chris-mich** [comment]
Here is my configuration.  Same problem.  Since "sp_inside_fparen" and "sp_after_comma" are set to "add", I would not expect any collapsing...

```
indent_columns   = 4
indent_with_tabs = 0
align_same_func_call_params      = true
align_same_func_call_params_span = 1
sp_inside_fparen = add
sp_after_comma   = add
```

**Comment by chris-mich** [comment]
Oops, I hit the wrong button. :-)

**Comment by guy-maurel** [comment]
I get just now:
```.cpp
Uncrustify_d-0.68.1-246-424ebc97
Parsing: chris-mich.cpp as language CPP
void Test()
{
    CallFunction( aa,  bb,   cc );    // Params should be aligned
    CallFunction( a,   b,    c );     // Params should be aligned
    CallFunction( aaa, bbbb, cccc );
    CallFunction2( aaaa,  bbbbb,   ccccc );
    CallFunction2( aaaaa, bbbbbbb, ccccccc );
}

void Test()
{
    banana( aa, bb, cc );
    mango( xx, yyyyyy, zz );
    coconut( p1, p22222222222, p3 );
}

void Test()
{
    DoubleAdd( doubleValue, dv );
    FloatAdd( floatValue, fv );      // Developer made this alignment himself
}
```
What do you think about?

**Comment by chris-mich** [comment]
It does not solve anything...

- The first test case is wrong. The last function call should be  **CallFunction3**, not 2.
- The banana case is not part of my initial issue.
- In the last test case, I expect uncrustify to leave the code as-is (not removing the spaces), since the two function calls are NOT the same.

**Comment by guy-maurel** [comment]
You need to use the option:
```
# Whether to keep whitespace not required for alignment.
align_keep_extra_space = true
```

**Comment by chris-mich** [comment]
Now this is working!!   I still think that "align_same_func_call_params" has a confusing name ("same" should not be there) but since your workaround works, I will close this issue.  I was hoping that this option would solve #2101 as well, but it does not...  :-)

 Thank you for the tip!!
