### ISSUE TITLE
nl_fdef_brace = remove does not work properly with nl_collapse_empty_body = true

### ISSUE THREAD

**Issue by Benio101** [uncrustify/uncrustify#2116]
### Issue
`nl_fdef_brace = remove` does not work properly with `nl_collapse_empty_body = true`.

### Details
Version: `Uncrustify-0.68_f`
Debug file: [debug.txt](https://pastebin.com/raw/nmdtqtsg)
Tests: [issue-2109.patch](https://pastebin.com/embed_iframe/1FxFHPgj)

### Repro
Config:
```.cfg
nl_fdef_brace                   = remove
nl_collapse_empty_body          = true
```

Expected result:
```.cpp
void f(){}
```

Generated result:
```.cpp
void f()
{}
```

### Note
`nl_fdef_brace = remove` works properly with `nl_collapse_empty_body = false`.

**Comment by guy-maurel** [comment]
Please test it and report

**Comment by Benio101** [comment]
Works well now, thanks.
