### ISSUE TITLE
uncrustify-0.68.1 tag slip?

### ISSUE THREAD

**Issue by AMDmi3** [uncrustify/uncrustify#2119]
I've noticed that contents of the named tag have changed, here's the diff:

https://people.freebsd.org/~amdmi3/uncrustify.patch

Has the tag been moved? Please don't do this ever again. I also suggest to release a new version (maybe pointing to the same commit) to avoid fetch and checksum errors for downstreams.

**Comment by guy-maurel** [comment]
I have the tag 0.68.1 at 3358389a6191e5acd8a20b08a3371dc31e8262b3

Do you mean the same?

**Comment by AMDmi3** [comment]
On GitHub, tag is at 8c80bd8.

**Comment by mwoehlke-kitware** [comment]
```
Fetching origin
From git://github.com/uncrustify/uncrustify
 t [tag update]        uncrustify-0.68.1 -> uncrustify-0.68.1
```

I think it used to be 8c80bd84d023d9ae220c2721e68b09d10403bb41? Should I reset it back to that or would that be worse than leaving it alone now that it moved? (I think that's a reasonable place for it to be, anyway; @guy-maurel, do we need the changes since then? If so, should that be 0.68.2?)

**Comment by AMDmi3** [comment]
> Should I reset it back to that or would that be worse than leaving it alone now that it moved?

It doesn't matter really as it's already broken for somebody in either case. I vote for a new unambiguous tag. It can point to the [correct] place where 0.68.1 was intended to point to.

**Comment by AMDmi3** [comment]
Ping? I'll stress on this: because of the tag slip, uncrustify package is likely to be broken in some distros, so this needs ASAP fix.

As a side note, the contents of the 0.68.1 tag by the time I've updated FreeBSD port of uncrustify are equal to dbe32c0.

**Comment by gmaurel** [comment]
Yes, make a new tag.

**Comment by AMDmi3** [comment]
Why was this closed? The problem was not fixed, there's still no unambiguous latest tag.

**Comment by gmaurel** [comment]
The next release 0.69.0 will be ready soon, mid of may

**Comment by guy-maurel** [comment]
The release 0.69.0 is ready.
Please test and report. Thanks.

**Comment by AMDmi3** [comment]
0.69.0 works, but I can't really test whether there will be no further tag slips. Hopefully there won't.
