### ISSUE TITLE
Likelihood attribute applied to statement issues superflous obrace

### ISSUE THREAD

**Issue by Benio101** [uncrustify/uncrustify#2124]
## Issue
[Likelikehood](https://en.cppreference.com/w/cpp/language/attributes/likely) attribute (※ [dcl.attr.likelihood](http://eel.is/c++draft/dcl.attr#likelihood)) applied to statement (_ie_ `if`) issues superflous obrace, either virtual (by default, `VBRACE_OPEN`) or non–virtual (`BRACE_OPEN`).

### Info
**Version**: `Uncrustify-0.68-16-3358389a`

### Example 1
**Config**: default
**Debug**: [debug.txt](https://pastebin.com/raw/aUQQpei2)

#### Input
```.cpp
if(x)
	[[likely]]
{}

a();
```

#### Output
```.cpp
if(x)
	[[likely]]
	{}

	a();
```

#### Expected output
```.cpp
if(x)
	[[likely]]
{}

a();
```

Neither `{}` nor `a();` should be indented to the right.
No `VBRACE_OPEN` should be issued between `SPAREN_CLOSE` and a newline before `ATTRIBUTE`:
```.txt
#   1>        VBRACE_OPEN[                 IF][  6/  0/  0/  0][0/0/0][         0][0-0]
```

### Example 2
Things are getting critical when we use simple config, _ie_:

#### Config
```.cfg
mod_full_brace_if_chain         = true
mod_full_brace_nl               = 1
```

**Debug**: [debug.txt](https://pastebin.com/raw/ZJt49xdg)
**Input**: _same as in Example 1_

#### Output
```.cpp
if(x) {
	[[likely]]
	{}

	a();
}
```

#### Expected output
```.cpp
if(x)
	[[likely]]
{}

a();
```

No superflous `BRACE_OPEN` should be issued between `SPAREN_CLOSE` and a newline before `ATTRIBUTE`:
```.txt
#   1>         BRACE_OPEN[                 IF][  7/  0/  0/  0][0/0/0][1000000000][0-0]       {
```
Even if we ignore `[[likely]]` attribute incorrectly moved after obrace instead applying to `if` statement, `a();` is called only `if(x`) instead of always. This is crucial, as it reflows content, changing logic and may lead to catastrophic results.

### Example 3
Finally, some valid code does not even gets parsed correctly.

**Config**: default
**Debug**: _empty_

#### Input
```.cpp
if(x)
	[[likely]]
{
	if(y)
		[[likely]]
	{}
}
```

**Output**: _empty_

#### Expected output
```.cpp
if(x)
	[[likely]]
{
	if(y)
		[[likely]]
	{}
}
```

##### Input
```.txt
uncrustify -c config.cfg -f input.cpp -o output.cpp -p debug.txt
```
##### Output
```.txt
Parsing: input.cpp as language CPP
parse_cleanup(425): input.cpp, orig_line is 7, Error: Unexpected '}' for 'VBRACE_OPEN', which was on line 4
Unmatched BRACE_CLOSE
at orig_line=7, orig_col=1
Try the option 'tok_split_gte = true'
```

### Note
Likelikehood attributes are important part of a modern C++, and they are already supported in stable verion of GCC (_see [compiler support](https://en.cppreference.com/w/cpp/compiler_support)_) and shall come live to more compilers, like clang and Visual Studio 2019 very soon.

Lack of distinguishing types of attributes leads to critical issues already and makes it impossible to use uncrustify in a modern C++ code until attributes shall be distinguished and handled properly.

**Comment by gmaurel** [comment]
Yes. It is (since C++20).
Could you make a bugfix proposal?
