### ISSUE TITLE
Space Inside Braces Priority Over Space After Semicolon

### ISSUE THREAD

**Issue by Alexander-Shukaev** [uncrustify/uncrustify#213]
This:

```
sp_inside_braces = remove
```

should have higher priority than:

```
sp_after_semi = add
```

so that this:

```c++
{int x;}
```

can be the case. But currently it's as ugly as this:

```c++
{int x; }
```

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
