### ISSUE TITLE
Please make the encoding support - visualforce (like HTML)

### ISSUE THREAD

**Issue by Domovikx** [uncrustify/uncrustify#2135]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Hello, please make the **encoding** support - **visualforce** (like HTML). 
Currently, VS Code is installed on Ubuntu and gives an error - **There is no document formatter for 'visualforce'-files installed.**
The error is present only on **ApexPage - apexFile.page**

**Comment by guy-maurel** [comment]
Please push an example.

**Comment by CDanU** [comment]
> A source code beautifier for C, C++, C#, ObjectiveC, D, Java, Pawn and VALA

We do not support: anything slaesforce/apex related, formatting of any kind of html and we do not maintain the VS Code Uncrustify plugin.
