### ISSUE TITLE
Feauture request: Add option for controlling space between ')' in function declaration and function specifier

### ISSUE THREAD

**Issue by ttnghia** [uncrustify/uncrustify#2138]
Hello,

Currently, I have difficulty in controlling space in function declaration and function specifier keyword. Assume that I have the original code:
```
void funcName()                       const;
```

The desired result should look like this:
```
void funcName() const;
```

However, uncrustify cannot format the code to remove/add/force space between the parentheses and the `const` keyword (of course, the same thing for other keywords such as `override`).

**Comment by guy-maurel** [comment]
#2157 is a proposal.
Please test and report
