### ISSUE TITLE
Misalignment of closing brackets for enums with values initilized with shift operators

### ISSUE THREAD

**Issue by uwerat** [uncrustify/uncrustify#2149]
Using origin/master f72c97d40761ecdd963dfc8cf2b17a900f30ebb3 ( 19/1/4 )

```
indent_namespace   = true
indent_continue         = 8
indent_shift                 = true
```

My code looks like this:

```
namespace
{ 
    enum EnumValue
    {
        EnumValue1 = 1 << 1
    }
}
```

The result has a wrong indentation for the closing bracket

```
namespace
{
	enum EnumValue
	{
		EnumValue1 = 1 << 1
		}
}
```

**Comment by guy-maurel** [comment]
Using a semi colon at the end of the line is a workaround.
I still looking for.

**Comment by guy-maurel** [comment]
#2171 is a bugfix proposal.
Please test it and report.
