### ISSUE TITLE
logical & operator misinterpreted as reference operator

### ISSUE THREAD

**Issue by uwerat** [uncrustify/uncrustify#2151]
Using origin/master f72c97d40761ecdd963dfc8cf2b17a900f30ebb3 ( 19/01/04 ) with the following option:
```
sp_before_unnamed_byref         = remove
```
The code looks like this:
```
void f( int a )
{
	namespace C { enum { Value }; }
	const bool ok = ( a & C::Value ) && true;
}
```
In the result the space of the logical '&' operator is removed - as if it was interpreted as a reference operator.

```
void f( int a )
{
	namespace C { enum { Value }; }
	const bool ok = ( a& C::Value ) && true;
}
```

**Comment by mwoehlke-kitware** [comment]
Ah, yes... getting these right seems to be one of the banes of uncrustify. Thanks for the test cases! (#2152 is probably a duplicate, but I'll leave it alone for now in case I'm wrong.)

**Comment by mihaipopescu** [comment]
Yes. It's always good to have extra samples.   @uwerat can you make a PR with a staging test for this please?

**Comment by uwerat** [comment]
What is a PR or a staging test in the context of uncrustify - and how is this superior to reporting a problem as issue ?

As a side note: your github project page references the sourceforge project page giving probably outdated informations about how to deal with bug reports. At least there seems to be no mailing list anymore and "Use the sourceforge.net bug tracker" is not in line with the information given on the github page.

( Actually mailing list and bug tracker are the main features, that make sourceforge superior to github. And as the combination of having a sourceforge project linked to a github repository is a supported combination ... )

**Comment by mihaipopescu** [comment]
> What is a PR or a staging test in the context of uncrustify - and how is this superior to reporting a problem as issue ?

Just commented on #2091 about this but it's mainly a new experimental process we are trying out for bug reports to which I was inviting you to take part from.

As for Github vs. Sourceforge, the project migrated to Github a couple of years ago but we kept Sourceforge around just for binary distribution and refer everything back  to github. The bug tracker we like this one and we have a mailing list on Google groups. I did not know about Sourceforge mailing list at that time and I'm unsure how much superior is it but I think the cost of switching back is higher than just sticking with what we have. 

On the other hand, thanks for pointing out the inconsistencies on Sourceforge project side. @gmaurel can fix those as he has admin access.

**Comment by gmaurel** [comment]
Yes, I could correct it... if I am pointed exactly to what you are writing.
Where do you found:

>  At least there seems to be no mailing list anymore and "Use the sourceforge.net bug tracker" is not in line with the information given on the github page.

Where do you found any:

> inconsistencies on Sourceforge project side

I would be glad to do the job.

**Comment by uwerat** [comment]
When entering uncrustify at google the first hit is: http://uncrustify.sourceforge.net.

In the "Want to help" section you find "Use the sourceforget.net bug tracker" or "There is one mailing list for Uncrustify - uncrustify-developer@lists.sourceforge.net" - where the archive is empty.

**Comment by guy-maurel** [comment]
Thanks for the info.

**Comment by guy-maurel** [comment]
PR #2299 is a bugfix proposal.
Please test it and report.
