### ISSUE TITLE
nl_before_func_body_def misbehaves when returning a reference in C++

### ISSUE THREAD

**Issue by mxmlnkn** [uncrustify/uncrustify#2163]
This problem seems to belong into the `bug_902.ccp` test.

I have this input:

```C++
/*
 * m
 */
void
m(){ return 0; }
/*
 * n
 */
void
n(){ return 0; }
/*
 * n
 */
int&
n( int& x ){ return x; }
```

The output, using commit 29d7dab95973835a41ea7413fa48f458f2330098 is:

```C++
/*
 * m
 */
void
m(){
	return 0;
}

/*
 * n
 */
void
n(){
	return 0;
}
/*
 * n
 */
int&

n( int& x ){
	return x;
}
```

The first function seems to be uncrustified correctly, i.e., the associated comment and return type is detected. But in the second function the `nl_before_func_body_def` newlines are inserted between the function return type and the function name.

Expected output:

```C++
/*
 * m
 */
void
m(){
	return 0;
}

/*
 * n
 */
void
n(){
	return 0;
}

/*
 * n
 */
int&
n( int& x ){
	return x;
}
```

[debug.txt](https://github.com/uncrustify/uncrustify/files/2755107/debug.txt)

Uncrustify version: `Uncrustify-0.68-93-29d7dab9`

This problem is exacerbated when enforcing the return type to be on an extra line with:

    nl_func_proto_type_name = force

**Comment by guy-maurel** [comment]
#2196 is a bugfix proposal.
Please test it and report
