### ISSUE TITLE
Uncrustify crashes with unmatched BRACE_OPEN in lambda within a function call

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2165]
Version: 0.68
Config: default

```
// test.cpp
void f1()
{
    // This code does not compile. Note the extra brace before "return"
    f2( [](){ { return true; } );   
}
```

Result:
```
parse_cleanup(425): test.cpp, orig_line is 3, Error: Unexpected ')' for 'BRACE_OPEN', which was on line 3
test.cpp:2 Unmatched BRACE_OPEN
test.cpp:3 Unmatched PAREN_OPEN
test.cpp:2 Unmatched BRACE_OPEN
test.cpp:3 Unmatched PAREN_OPEN
```

Event viewer:
```
Faulting application name: uncrustify.exe, version: 0.0.0.0, time stamp: 0x5bf411e7
Faulting module name: uncrustify.exe, version: 0.0.0.0, time stamp: 0x5bf411e7
Exception code: 0xc0000005
Fault offset: 0x0000000000067a00
```

Normally, uncrustify does not format anything when braces do not match (this is fine).
In this specific case, it looks like it's trying to format anyway, and crashes.

Of course, this code does not compile.  But we started using uncrustify with Code Beautifier Visual Studio extension, with the "Format on save" option activated.  So formatting "bad" code is more likely to happen... :-)

**Comment by guy-maurel** [comment]
Under Linux it doesn't crash.
Which sytem are you using?
Right, the code is not OK.
I get:
```.txt
Uncrustify_d-0.68.1-94-fcba5989
Parsing: chris-mich.cpp as language CPP
parse_cleanup(428): chris-mich.cpp, orig_line is 4, Error: Unexpected ')' for 'BRACE_OPEN', which was on line 4
chris-mich.cpp:2 Unmatched BRACE_OPEN
chris-mich.cpp:4 Unmatched PAREN_OPEN
chris-mich.cpp:2 Unmatched BRACE_OPEN
chris-mich.cpp:4 Unmatched PAREN_OPEN
void f1()
{
        // This code does not compile. Note the extra brace before "return"
        f2 ( [](){
                { return true; } );
        }
```

**Comment by guy-maurel** [comment]
Could you point to some source code lines?

**Comment by chris-mich** [comment]
What do you mean?  You want me to compile Uncrustify?

**Comment by guy-maurel** [comment]
Do you have tested the proposal from mihai?
Please test it and report!

**Comment by chris-mich** [comment]
I have downloaded version 0.69 and gave it a try.
I now have the following output:

```
Parsing: test.cpp as language CPP
parse_cleanup(440): pc->orig_line is 4, orig_col is 32, text() is ')', type is PAREN_CLOSE
parse_cleanup(442): (frm.top().type + 1) is BRACE_CLOSE
parse_cleanup(447): File: test.cpp, orig_line is 4, orig_col is 32, Error: Unexpected ')' for 'BRACE_OPEN', which was on line 4
indent_text(3155): size is 3
indent_text(3157): File: test.cpp, open_line is 2, parent is NONE: Unmatched BRACE_OPEN
indent_text(3155): size is 3
indent_text(3157): File: test.cpp, open_line is 4, parent is NONE: Unmatched PAREN_OPEN
indent_text(3155): size is 3
indent_text(3157): File: test.cpp, open_line is 2, parent is NONE: Unmatched BRACE_OPEN
indent_text(3155): size is 3
indent_text(3157): File: test.cpp, open_line is 4, parent is NONE: Unmatched PAREN_OPEN
```

The "just in time debugger" didn't pop this time.

HOWEVER. Uncrustify did try to format the code anyway, which I think is worse than before.  In my opinion, Uncrustify should not try to format something it can not parse...

Resulting "test.cpp" with version 0.69:
```
void f1()
{
	// This code does not compile. Note the extra brace before "return"
	f2 ( [](){
		{ return true; } );
	}
```

**Comment by guy-maurel** [comment]
uncrustify cannot catch all problems with not compilable sources.
Provide a right source and report again. Thanks.

**Comment by chris-mich** [comment]
I agree with you, uncrustify can't catch all problems, as it is not a compiler.
However, I think that it **should not** try to format code that it can not understand (code with parsing errors, like in my example).  Uncrustify should leave the code as it is, and simply report errors.    Then, the developer can take action, fix the code and invoke Uncrustify again.

What do you think?

**Comment by guy-maurel** [comment]
difficult!

**Comment by CDanU** [comment]
Seems to me to be a worthwhile endeavour

```diff
diff --git i/src/brace_cleanup.cpp w/src/brace_cleanup.cpp
index fe14ef8ba..205a720c3 100644
--- i/src/brace_cleanup.cpp
+++ w/src/brace_cleanup.cpp
@@ -465,6 +465,7 @@ static void parse_cleanup(BraceState &braceState, ParseFrame &frm, chunk_t *pc)
frm.top().pc->orig_line);
print_stack(LBCSPOP, "=Error  ", frm);
cpd.error_count++;
+            exit(EXIT_FAILURE);
}
}
else
```

Does work for the above case, one D test fails though.
