### ISSUE TITLE
Bad handling of & in C++14 lambda capture

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2166]
Version 0.68
Config:
```
nl_cpp_lambda_leave_one_liners = true
sp_before_byref = remove
```
Input
```
// Test.cpp
void f1()
{
	auto lambda1 = [ &a ](){ return true; };
	auto lambda2 = [ &a = b ](){ return true; };
}
```
Output.  Note that the space was removed before & on line 4.
```
void f1()
{
	auto lambda1 = [ &a ](){ return true; };
	auto lambda2 = [&a = b ](){ return true; };
}
```

No changes were expected.  
It seems that uncrustify does not recognize this C++14 syntax, and applies "sp_before_byref" here.

**Comment by guy-maurel** [comment]
Sorry, I am not an expert for C++14.
Please explain to me the differences.

**Comment by chris-mich** [comment]
This is a bit complicated to explain, but cppreference has it all covered:

[Click here](https://en.cppreference.com/w/cpp/language/lambda#Lambda_capture)

Scroll down about one page, the explanation is in the first box where "(since C++14)" is mentioned.

This is not a major Uncrustify issue, at least the code still compiles. :-)

**Comment by guy-maurel** [comment]
I cannot find it! Please more explanations. Thanks

**Comment by chris-mich** [comment]
There you go!

> A capture with an initializer acts as if it declares and explicitly captures a variable declared with type auto, whose declarative region is the body of the lambda expression (that is, it is not in scope within its initializer), except that:
> 
> if the capture is by-copy, the non-static data member of the closure object is another way to refer to that auto variable.
> if the capture is by-reference, the reference variable's lifetime ends when the lifetime of the closure object ends
> This is used to capture move-only types with a capture such as x = std::move(x).
> 
> This also makes it possible to capture by const reference, with &cr = std::as_const(x) or similar.
> 

```
int x = 4;
auto y = [&r = x, x = x + 1]()->int
    {
        r += 2;
        return x * x;
    }(); // updates ::x to 6 and initializes y to 25.
```

**Comment by guy-maurel** [comment]
PR #2356 is a bugfix proposal.
Please test it and report.
