### ISSUE TITLE
Fix for #1340 breaks align_assign_decl_func (and others?)

### ISSUE THREAD

**Issue by rwiesenfarth** [uncrustify/uncrustify#2170]
Failing version: Uncrustify-0.68-2-8c80bd84

Running uncrustify with align_assign_span = 1 on this snippet:

```
class Foo
{
  public:
    Foo( int bar = 1 );
    Foo( const Foo & ) = delete;
    Foo &operator= ( const Foo & ) = delete;
    ~Foo();
};
```

results in

```
class Foo
{
  public:
    Foo( int bar                   = 1 );
    Foo( const Foo & )             = delete;
    Foo &operator= ( const Foo & ) = delete;
    ~Foo();
};
```

even if align_assign_decl_func is set to 1.

Removing the comment in align.cpp line 717 (fix for #1340) brings back the intended behavior.

**Comment by rwiesenfarth** [comment]
Above mentioned location corresponds to align_assign.cpp line 56 on master d3feedbc01...

**Comment by guy-maurel** [comment]
Thank for the message.
#2177 is a proposal for a bugfix.
Please test it and report.
