### ISSUE TITLE
Option align_func_proto_thresh missing

### ISSUE THREAD

**Issue by p4pyru5** [uncrustify/uncrustify#2173]
The threshold option for aligning function prototypes is not implemented.
Suitable option name would be `align_func_proto_thresh`.

**Comment by uncletall** [comment]
Indeed, I came across the same issue. This is the code that I have in my class definition and it is not what I would expect. could you please assist in implementing this feature?

void                                                                                    f1();
void                                                                                    f2();
void                                                                                    f3();
void                                                                                    f4();
void                                                                                    f5();
void                                                                                    f6();
void                                                                                    f7();
void                                                                                    f8();
SomeLongClassNameThatIsReturnedByAnotherFunction GetIt();

**Comment by uncletall** [comment]
Fixed it but am not sure what tests are required to be changed.

**Comment by uncletall** [comment]
Can this be closed?
