### ISSUE TITLE
Unable to stop uncrustify producing backup files when input/output files are specified

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#2174]
Today, the `--no-backup` command line argument is not working in combination with `-f` or `-o` and it makes uncrustify to fail with `Cannot use --replace or --no-backup with -f or -o`. Consequently, there is no way to stop uncrustify to produce backup files when input/output files are specified.

I fail to see any apparent reason why it should be like this. This constraint seems to be as _per initial design_ from @bengardner more than 9 years ago but unfortunately the reason **why** was not preserved.

While I can understand that the backups feature is a nice safety default option to have, uncrustify should trust users when they explicitly request they want no backups, especially when they also set the input and output files.

**Comment by guy-maurel** [comment]
Should we try?

**Comment by mihaipopescu** [comment]
There is an _essential_ piece of information I omitted from my initial bug report. In my use-case, the input and output file are the same (it's actually a backup file that I create on my own before calling uncrustify) and therefore, in good faith, uncrustify creates backup files. This definitely should remain the default behavior but when the user explicitly asks for no backups, uncrustify should respect that.

**Comment by mwoehlke-kitware** [comment]
I am... somewhat, though not terribly, surprised that works; it seems uncrustify *is* written in a way such that input and output do not overlap and break things.

That being the case... I am a little surprised that a backup is created in this instance, especially when I can fairly easily circumvent it:
```
$ ln -s foo.c bar.c
$ uncrustify -c... -f foo.c -o bar.c
```
...which overwrites the input file *without* creating a backup.
