### ISSUE TITLE
nl_fdef_brace remove not working

### ISSUE THREAD

**Issue by nrbrook** [uncrustify/uncrustify#2175]
Uncrustify-0.68_f

[debug.txt](https://github.com/uncrustify/uncrustify/files/2800882/debug.txt)

[config file](https://raw.githubusercontent.com/CocoaLumberjack/CocoaLumberjack/a8fe4f049169a955f524e6c4ecb158070b6fc65a/uncrustify.cfg)

[problem file](https://raw.githubusercontent.com/CocoaLumberjack/CocoaLumberjack/a8fe4f049169a955f524e6c4ecb158070b6fc65a/Benchmarking/BaseNSLogging.m)

Problem is that `nl_fdef_brace` is set to `remove` and new line after `+ (void)speedTest0` is not removed

**Comment by guy-maurel** [comment]
using the calling option **-p p.txt**
you get:
```.txt
#  20>           OC_SCOPE[        OC_MSG_DECL][  1/  1/  2/  0][0/0/0][ 100060000][0-0] +
#  20>         PAREN_OPEN[        OC_MSG_DECL][  3/  3/  4/  1][0/0/0][2100040000][0-0]   (
#  20>               TYPE[               NONE][  4/  4/  8/  0][0/1/0][2000040000][0-0]    void
#  20>        PAREN_CLOSE[        OC_MSG_DECL][  8/  8/  9/  0][0/0/0][2100000000][0-0]        )
#  20>        OC_MSG_DECL[        OC_MSG_DECL][  9/  9/ 19/  0][0/0/0][         0][0-0]         speedTest0
#  20>            NEWLINE[               NONE][ 19/ 19/  1/  0][0/0/0][         0][1-0]
```
One may see: **speedTest0** is tokenize as **OC_MSG_DECL**, which is:
`token_enum.h:263: CT_OC_MSG_DECL,      // ObjC: msg decl '-(void) func: (int) i { }'`
I am not expert for OC.

**Comment by nrbrook** [comment]
I'm not sure what you are saying. "add" works, but "remove" does not.

**Comment by guy-maurel** [comment]
You need to use another option:
```.cfg
#(OC) Add or remove newline between method declaration and '{'.
nl_oc_mdef_brace = remove
```

**Comment by nrbrook** [comment]
Thanks
