### ISSUE TITLE
Add support for break-before-operator long lines

### ISSUE THREAD

**Issue by orenbenkiki** [uncrustify/uncrustify#218]
When I write very long lines (which I try to avoid), I do it like this:
```c
if (foo ...
 || (bar ...
  && baz ...
 || qux) {
}

x = foo ...
  + (bar ...
   * baz ...)
  + qux;
```
This makes the expression tree clearly visible, where everything (including the 1st line) is properly aligned. Currently the result is something like this:
```c
if (foo ...
    || (bar ...
        && baz ...
    || qux) {
}

x = foo ...
    + (bar ...
       * baz ...)
    + qux;
```
Where the 1st line is "special" and the rest are aligned. The fix is to, compared to today, unindent a continuation line that starts with an operator by the (width of the operator + 1).

It would be nice if there was an option to do that...

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!

**Comment by orenbenkiki** [comment]
Yes, the current behavior is pretty fine.

It would have been even sweeter to have an option adjusting the offset of the operator relative to the parenthesis in the preceding line (taking the current behavior to be offset 0, my ideal formatting would have been an offset of -2). But, even as it is today, it is much better than it used to be.

Thanks!

**Comment by orenbenkiki** [comment]
Another nit is that this is a special case for Boolean expressions.
There's no equivalent for arithmetic operations.
That is, with the options `indent_bool_paren True` and `indent_first_bool_expr True`, I get the (much nicer):

```c
if (  foo
   || (  bar
      && baz)
   || qux) {
};
```

But it does not help with:

```c
x = foo
    + (bar
       * baz)
    + qux;
```

So, while this is a huge improvement - thanks again!
And at the risk of coming off as "there's no pleasing some people" https://www.youtube.com/watch?v=U74s8nFE7No :-)
Perhaps you might be willing to re-open this issue to cover the more general case (low  priority though it may be)?
