### ISSUE TITLE
C++ var decl alignment by "grouping"?

### ISSUE THREAD

**Issue by asmaloney** [uncrustify/uncrustify#2180]
I started with [ben.cfg](https://github.com/uncrustify/uncrustify/blob/master/etc/ben.cfg) and made a couple of changes.

When I use it on this code:

```cpp
struct IndexPacket
{
      static constexpr unsigned MAX_ENTRIES = 2048;

      const uint8_t     packetType = INDEX_PACKET;

      uint8_t     packetFlags = 0;    // flag bitfields
      uint16_t    packetLogicalLengthMinus1 = 0;
      uint16_t    entryCount = 0;
      uint8_t     indexLevel = 0;
      uint8_t     reserved1[9] = {};   // must be zero

      struct IndexPacketEntry
      {
            uint64_t    chunkRecordNumber = 0;
            uint64_t    chunkPhysicalOffset = 0;
      } entries[MAX_ENTRIES];
};
```

I get this:

```cpp
struct IndexPacket
{
   static constexpr unsigned MAX_ENTRIES = 2048;

   const uint8_t             packetType = INDEX_PACKET;

   uint8_t                   packetFlags = 0; // flag bitfields
   uint16_t                  packetLogicalLengthMinus1 = 0;
   uint16_t                  entryCount = 0;
   uint8_t                   indexLevel = 0;
   uint8_t                   reserved1[9] = {}; // must be zero

   struct IndexPacketEntry
   {
      uint64_t chunkRecordNumber = 0;
      uint64_t chunkPhysicalOffset = 0;
   }
                             entries[MAX_ENTRIES];
};
```

I cannot figure out how to get the result I want, which is this:

```cpp
struct IndexPacket
{
   static constexpr unsigned MAX_ENTRIES = 2048;

   const uint8_t packetType = INDEX_PACKET;

   uint8_t     packetFlags = 0; // flag bitfields
   uint16_t    packetLogicalLengthMinus1 = 0;
   uint16_t    entryCount = 0;
   uint8_t     indexLevel = 0;
   uint8_t     reserved1[9] = {}; // must be zero

   struct IndexPacketEntry
   {
      uint64_t chunkRecordNumber = 0;
      uint64_t chunkPhysicalOffset = 0;
   } entries[MAX_ENTRIES];
};
```

It's close, but there are so many options!

I'd like to:
1) Align variables, but not across the entire struct - just by "grouping" (based on newlines).
2) Avoid `} entries[MAX_ENTRIES];` from being split onto a new line

(Maybe these are related.)

I can't seem to find an option to do this.

Current version: `Uncrustify-0.68_f` on macOS via homebrew

(Aside - is there an online tool [like this](https://zed0.co.uk/clang-format-configurator/) to help configure uncrustify?)

Thank you!

**Comment by mwoehlke-kitware** [comment]
Try changing `align_var_struct_span` to `1`? (I'm pretty sure it is one of the `*_span` or `*_gap` anyway that controls this.)

**Comment by asmaloney** [comment]
That helps me get close! Thanks @mwoehlke-kitware.

```cpp
struct IndexPacket
{
   static constexpr unsigned MAX_ENTRIES = 2048;

   const uint8_t packetType = INDEX_PACKET;

   uint8_t  packetFlags = 0;          // flag bitfields
   uint16_t packetLogicalLengthMinus1 = 0;
   uint16_t entryCount = 0;
   uint8_t  indexLevel = 0;
   uint8_t  reserved1[9] = {};         // must be zero

   struct IndexPacketEntry
   {
      uint64_t chunkRecordNumber = 0;
      uint64_t chunkPhysicalOffset = 0;
   }
   entries[MAX_ENTRIES];
};
```

1) Still can't get `entries[MAX_ENTRIES];` to stay on the line with `}`.
2) Not sure what I did that the comments are moved over...
3) `align_var_struct_gap` only applies to structs - member vars in classes aren't formatted properly and I can't find the  equivalent for classes (I would expect it to be the same since `struct` and `class` are - for our purposes - the same thing).

Here's my config: [uncrustify.cfg.zip](https://github.com/uncrustify/uncrustify/files/2837891/uncrustify.cfg.zip)

**Comment by mwoehlke-kitware** [comment]
> Still can't get entries[MAX_ENTRIES]; to stay on the line with }.

That would be one of the `nl_*` options, possibly `nl_after_brace_close`.

> Not sure what I did that the comments are moved over...

Trying looking at the `align_right_cmt_*` options?

----

In general, I'm not sure starting with an existing configuration is helpful. You might be better off starting with an *empty* configuration and going through the options one by one.

Another technique I find useful is to delete half of your config and see if "problems" persist. If yes, undo that and delete the other half instead. Once you identify the half causing the problem, repeat the process with half of the half, and so on, until you find the option causing the problem. This often works, but can get tricky if a "problem" is caused by a combination of options.
