### ISSUE TITLE
Improper #if paren spacing

### ISSUE THREAD

**Issue by troyerta** [uncrustify/uncrustify#2181]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

I'm experiencing consistent bad formatting. I wanted to verify that this is correct behavior, since it could change this issue from a bug report to a feature request.

Working with Uncrustify-0.68-1-1ea49f32, Windows binary

Here is my C code input snippet:
```
#if( FLAG )
    someFunction();
#endif
```
Output:
```
#if ( FLAG )
    someFunction();
#endif
```
Unexpected space after `#if`

When does this happen? All the time. All config files I have on hand produce this same result.
So I tried to narrow down the config file to something with just 1 unrelated config:
`nl_max                          = 2`

ran this with

`uncrustify -c my.cfg -f snippet.c -o snippet_out.c -p parsed.txt`

to read the chunks, but the program stopped after printing "segmentation fault".

So I ran again with
`uncrustify -c my.cfg -f snippet.c -o snippet_out.c -L A`
This reports
```
output_text(488): text() is #, type is PREPROC, orig_col is 1, column is 1, nl is 0
output_text(647): orig_line is 1, column is 1, column_indent is 1, cpd.column is 1
output_text(488): text() is if, type is PP_IF, orig_col is 2, column is 2, nl is 0
output_text(672): at column 2(FALSE)
output_text(488): text() is (, type is PAREN_OPEN, orig_col is 4, column is 5, nl is 0
output_text(672): at column 5(FALSE)
```

So the program acknowledges that the column for the paren has changed, but I cannot figure out exactly why. Perhaps output_text(488) refers to commit 07fc9a7 concerning --frag option indentation?

This is as far as I go to understand this issue - before I need to get back to work.

Can someone confirm this is intended? If so, I would be interested in keeping parenthesis where I put them.

Thanks!

**Comment by guy-maurel** [comment]
We don't have any rule for that. The default rule ADD is used.
