### ISSUE TITLE
Trailing doxygen comments are not aligned

### ISSUE THREAD

**Issue by mathiasplans** [uncrustify/uncrustify#2185]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
Perhaps it should work like that but when I use doxygen comments for enums/structs and they get split, the comments will not be aligned after two calls of uncrustify.

Input:
```
typedef enum {
  HAL_USART_ENABLED = 64,                   ///< Requested task impossible while
                                            ///< peripheral in question is
                                            ///< enabled
  HAL_USART_DISABLED,                       ///< Requested task impossible while
                                            ///< peripheral in question is
                                            ///< disabled
  HAL_USART_GPIO_ERROR,                     ///< GPIO tied with USART peripheral
                                            ///< returned error state
  HAL_USART_BUFFER_DEPLETED,                ///< Not enough data to be read
  HAL_USART_BUFFER_FULL                     ///< Data requested to be written
                                            ///< didn't fit into buffer
} hal_usart_errors_t;
```

Output:
```
typedef enum {
  HAL_USART_ENABLED = 64,                   ///< Requested task impossible while
  ///< peripheral in question is
  ///< enabled
  HAL_USART_DISABLED,                       ///< Requested task impossible while
  ///< peripheral in question is
  ///< disabled
  HAL_USART_GPIO_ERROR,                     ///< GPIO tied with USART peripheral
  ///< returned error state
  HAL_USART_BUFFER_DEPLETED,                ///< Not enough data to be read
  HAL_USART_BUFFER_FULL                     ///< Data requested to be written
  ///< didn't fit into buffer
} hal_usart_errors_t;
```

Expected result:
```
typedef enum {
  HAL_USART_ENABLED = 64,                   ///< Requested task impossible while
                                            ///< peripheral in question is
                                            ///< enabled
  HAL_USART_DISABLED,                       ///< Requested task impossible while
                                            ///< peripheral in question is
                                            ///< disabled
  HAL_USART_GPIO_ERROR,                     ///< GPIO tied with USART peripheral
                                            ///< returned error state
  HAL_USART_BUFFER_DEPLETED,                ///< Not enough data to be read
  HAL_USART_BUFFER_FULL                     ///< Data requested to be written
                                            ///< didn't fit into buffer
} hal_usart_errors_t;
```

When I tried with regular comments (//), everything stayed aligned.
I'm using Uncrustify-0.66.1_f. [Debug data](https://pastebin.com/auiiR6sn).

**Comment by guy-maurel** [comment]
You need to use the right value(s) for the options:
```.cfg
mod_add_long_ifdef_endif_comment = 16
mod_add_long_ifdef_else_comment  = 16
```
But it is not the bug. I look...

**Comment by guy-maurel** [comment]
Ref. #1205

**Comment by mathiasplans** [comment]
The behavior persists even after changing the values, as you suggested. Looking at the bug fix, as I understand it the code aligns trailing comments only if they are NOT Doxygen comments.

In src/indent.cpp:
``` 
/*
 * Here we want to align comments that are relatively close one to another
 * but not when the comment is a Doxygen comment
 */
```

**Comment by guy-maurel** [comment]
#2193 is a bugfix proposal.
Please test it and report.

**Comment by mathiasplans** [comment]
Tested it and everything works as expected.
