### ISSUE TITLE
[vala] Strange indentation with classes, namespaces and lambdas

### ISSUE THREAD

**Issue by brendanlong** [uncrustify/uncrustify#2189]
This is simplified from [FeedReader](https://github.com/jangernert/FeedReader/blob/master/src/FeedReader.vala#L234).

Input:

```
namespace FeedReader {

public class FeedReaderApp : Gtk.Application {

private void SetupActions()
{
	new SimpleAction("quit", null).activate.connect(() => {
				if(Settings.state().get_boolean("currently-updating"))
				{
				        while(Settings.state().get_boolean("currently-updating"))
				        {
				                Gtk.main_iteration();
					}
				}
				else
				{
				        Logger.debug("No Sync ongoing -> Quit right away");
				}
			});
}
}
}
```

Output (same as input):

```
namespace FeedReader {

public class FeedReaderApp : Gtk.Application {

private void SetupActions()
{
	new SimpleAction("quit", null).activate.connect(() => {
				if(Settings.state().get_boolean("currently-updating"))
				{
				        while(Settings.state().get_boolean("currently-updating"))
				        {
				                Gtk.main_iteration();
					}
				}
				else
				{
				        Logger.debug("No Sync ongoing -> Quit right away");
				}
			});
}
}
}
```

Expected:

```

namespace FeedReader {

public class FeedReaderApp : Gtk.Application {

private void SetupActions()
{
	new SimpleAction("quit", null).activate.connect(() => {
		if(Settings.state().get_boolean("currently-updating"))
		{
			while(Settings.state().get_boolean("currently-updating"))
			{
				Gtk.main_iteration();
			}
		}
		else
		{
			Logger.debug("No Sync ongoing -> Quit right away");
		}
	});
}
}
}
```

I'm using the latest version of uncrustify from master (fcb9ad9a280cd619332728719a0b6fdbbee429b1) with the default settings (empty config file).

I *think* there are two issues:
 - Something weird is happening to the indentation inside the function body when it's surrounded with a namespace/class
 - Lambdas are getting double-indented, similar to what happened in C++ before #1296

**Comment by guy-maurel** [comment]
Please use the command **uncrustify ... -p p.tx**t to get a list after tokenizing.
Push the file p.txt after looking if all the results of tokenizing are correct.
Report if you find any problems

**Comment by brendanlong** [comment]
I don't see anything obviously wrong with it:

[p.txt](https://github.com/uncrustify/uncrustify/files/2872198/p.txt)

(Note: I'm running uncrustify as `uncrustify -c /dev/null -f example.vala`)

**Comment by guy-maurel** [comment]
You want to suppress two indentings.
The first one is introduced by the _PAREN_ after **connect(** , the second one after _BRACE_ **=> {** at the line:
```.vala
        new SimpleAction("quit", null).activate.connect(() => {
```
uncrustify has nothing to suppress that.
