### ISSUE TITLE
Possible bug with nl_after_semicolon

### ISSUE THREAD

**Issue by mcleary** [uncrustify/uncrustify#219]
In a class definition it was expected that a newline would be inserted between the ctor definition and the first method definition.

```C++
class MyClass
{
public:
    MyClass();
    // a newline should be inserted here
    void init();
};
```

The nl_after_semicolon should work in this case or there is another option?

**Comment by gmaurel** [comment]
Please use the option
  nl_before_func_body_proto = 2
