### ISSUE TITLE
a compile error

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#2190]
With dce98d017d879d7c5a5128bd1b8b1322feb7acfa, we get a new script.
The file option_enum.cpp.in has a line:
```.cpp
#pragma GCC diagnostic ignored "-Wswitch-bool"
```
which is not correctly compiled at:
https://travis-ci.org/uncrustify/uncrustify/jobs/489179630, line 723:
```.txt
/home/travis/build/uncrustify/uncrustify/build/src/option_enum.cpp:22:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wswitch-bool"
                                ^
```
How can it be corrected?

**Comment by mwoehlke-kitware** [comment]
Didn't we have this conversation before? Huh...
