### ISSUE TITLE
align_assign_decl_func = 1 breaks align_assign_span = 1

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#2197]
Something strange happened in commit 9ff42ee.
It introduces align_assign_decl_func.
When set set to 1 it causes align_assign_span = 1 to no longer take effect.

This still doesn't work on the current master (5457a13)

Test case
```
void
f()
{
   int  aa = 0;
   int  aaa = 0;
}
```

Expected output (this is what I get when align_assign_decl_func = 0)  [debug1.txt](https://github.com/uncrustify/uncrustify/files/2872989/debug1.txt)
```
void
f()
{
	int aa  = 0;
	int aaa = 0;
}
```

Generated result (when align_assign_decl_func = 1) [debug2.txt](https://github.com/uncrustify/uncrustify/files/2872990/debug2.txt)

```
void
f()
{
	int aa = 0;
	int aaa = 0;
}
```

**Comment by guy-maurel** [comment]
PR #2200 is a bugfix proposal.
Please test it and report.

**Comment by arneforlie** [comment]
Yes, it now works for my previous test case.
But there are some strange side effect, consider the case
```
typedef int GlobalT;

void
f()
{
   ::GlobalT a = 0;
   int aa = 0;
   int aaa = 0;
}
```
With align_assign_decl_func = 0 I get [debug1.txt](https://github.com/uncrustify/uncrustify/files/2877445/debug1.txt):
```
typedef int GlobalT;

void
f()
{
	::GlobalT a = 0;
	int aa  = 0;
	int aaa = 0;
}
```

However, when align_assign_decl_func = 1 I get [debug2.txt](https://github.com/uncrustify/uncrustify/files/2877447/debug2.txt):
```
typedef int GlobalT;

void
f()
{
	::GlobalT a = 0;
	int aa      = 0;
	int aaa     = 0;
}
```

I actually think that the latter is correct, but it is non-intuitive (and IMHO incorrect) that alignment of assignment to global types is controlled by align_assign_decl_func.

And, consider the case:
```
void
f2()
{
   bool q = true;
   q &= (0 < 1);
}
```

With align_assign_decl_func = 0 I get [debug3.txt](https://github.com/uncrustify/uncrustify/files/2877455/debug3.txt):
```
void
f2()
{
	bool q = true;
	q &= (0 < 1);
}
```
But with align_assign_decl_func = 1 I get [debug4.txt](https://github.com/uncrustify/uncrustify/files/2877457/debug4.txt):
```
void
f2()
{
	bool q = true;
	q     &= (0 < 1);
}
```

Again, it is non-intuitive (and incorrect) that alignment of &= is controlled by align_assign_decl_func

**Comment by guy-maurel** [comment]
We have (today) some differents ASSIGN:
(from src/token_enum.h)
```.h
CT_ASSIGN,              // =, +=, /=, etc
CT_ASSIGN_DEFAULT_ARG,  // Default argument such as
                        // Foo( int Foo = 5 );
CT_ASSIGN_FUNC_PROTO,   // function prototype modifier such as
                        // void* operator new(std::size_t) = delete;
                        // Foo( const Foo & ) = default;
                        // Foo( const Foo & ) = 0
```
Following your arguments, we should have some more.
Please comment!

**Comment by arneforlie** [comment]
I don't know the implementation details, so I'm not able to comment on how many ASSIGNs you need to get the formatting correct.

It could be that I misunderstand align_assign_decl_func=1, but from the documentation in the config file:
```
# How to apply align_assign_span to function declaration "assignments", i.e.
# 'virtual void foo() = 0' or '~foo() = {default|delete}'.
#
# 0: Align with other assignments (default)
# 1: Align with each other, ignoring regular assignments
# 2: Don't align
align_assign_decl_func          = 0        # unsigned number
```
I expect it to ONLY apply to function declarations.

But, as my example showed, the parameter had some unexpected side effects because it reformatted code that had nothing to do with function declarations.
There seems to be a few bugs in the processing of ASSIGNs, and they appear when align_assign_decl_func = 1.

**Comment by gmaurel** [comment]
It is not possible for uncrustify to get information about the "level" or "Block number"
where the variables ( you wanted to aligned or not aligned) are declared. This would
be the way to separe.
```.cpp
{
	::GlobalT a = 0;
	int aa  = 0;
        ::GlobalT b = 0;
	int aaa = 0;
}
```
would not be very pretty!
