### ISSUE TITLE
Protocol casts get messed up in Objective C code (whitespace)

### ISSUE THREAD

**Issue by regexident** [uncrustify/uncrustify#22]
This:

    - (void)aMethod {
        return [(id<MyProtocol>)myVar myMethod:myArgument];
    }

turns into:

    - (void)aMethod {
        return [(id < MyProtocol >) myVar myMethod:myArgument];
    }

which sucks.

And so I'm forced to do this:

    - (void)aMethod {
        return [((id<MyProtocol>)myVar) myMethod:myArgument];
    }

which will turn into this:

    - (void)aMethod {
        return [((id < MyProtocol >)myVar) myMethod:myArgument];
    }

which sucks a little less, but still sucks way too much. ;)

But apart from this and my previous small tickets **uncrustify** is incredibly awesome! Keep up the great work!

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
