### ISSUE TITLE
Ampersand is mistaken for a reference sign in bitwise & expression with a namespaced variable

### ISSUE THREAD

**Issue by briankendall** [uncrustify/uncrustify#2205]
My config file:
```
# Uncrustify-0.68_f
sp_after_byref = remove
indent_columns = 4
```
Input:
```
namespace Foo {
int flags = 0x01;
}

void bar() {
    int value = 0x0F;
    int flags = 0x02;
    
    if ((value & flags) == 0) {
        doSomething();
    }

    if ((value & Foo::flags) == 0) {
        doSomething();
    }
}
```
Expected output should be unchanged, but actual output is:
```
namespace Foo {
int flags = 0x01;
}

void bar() {
    int value = 0x0F;
    int flags = 0x02;

    if ((value & flags) == 0) {
	doSomething();
    }

    if ((value &Foo::flags) == 0) {
	doSomething();
    }
}
```
Note that the space after the ampersand `&` in line 13 is removed, but not in line 9.

It looks like the use of a namespace causes uncrustify to think that `value & Foo::flags` is a type (or something) instead of a bitwise operator expression.

I can work around the issue by enclosing `Foo::flags` in parentheses, i.e.:
```
    if ((value & (Foo::flags)) == 0) {
```

**Comment by gmaurel** [comment]
uncrustify tokenizes **value** (in the second case) as a **type in a cast**.
There are (today) no way to to it better as your workaround proposal with the parentheses.

**Comment by briankendall** [comment]
It seems strange to me that `value` would be considered a type in a cast. For that to be the case wouldn't it have to be written as something like `(value) &Foo::flags` or `value(&Foo::flags)`?

**Comment by Letme** [comment]
This issue manifests now in even more simple case in 0.76 version (latest as well) of uncrustify (while it does not in 0.75).
So I have a line with normal `&` operator in a header file define (https://github.com/melexis/mlx90632-library/blob/master/inc/mlx90632.h#L132):
```
#define MLX90632_EE_REFRESH_RATE(ee_val) (ee_val &MLX90632_EE_REFRESH_RATE_MASK)
```

And that is changed to in uncrustify 0.76 :
```
#define MLX90632_EE_REFRESH_RATE(ee_val) (ee_val &MLX90632_EE_REFRESH_RATE_MASK)
```

I did bisect between `uncrustify-0.75.0` and `uncrustify-0.76.0` and found out that space is removed by commit @guy-maurel : bc13ab56e6b9f4e6e4338e4c36ae07a164754061 (does exactly what commit message said, but it should not).

**Comment by guy-maurel** [comment]
your example is wrong: no space after &

**Comment by guy-maurel** [comment]
you need to use:
`sp_addr        = force`

**Comment by Letme** [comment]
If I use `sp_addr = force` then also legimite lines like

```
ret = mlx90632_i2c_read(MLX90632_RAM_3(2), &read_tmp);
```

Get a space:

```
ret = mlx90632_i2c_read(MLX90632_RAM_3(2), & read_tmp);
``
which is not bitwise AND, but a pointer and that in my opinion is wrong.

**Comment by guy-maurel** [comment]
what should be & tokenized?

**Comment by Letme** [comment]
When there is space around ampersand on right side you should not trim or force the whitespace as you change pointer to bitwise and.  The removal is what is now happening and it is really wrong.

**Comment by Letme** [comment]
please add to your test case the following statement

```
#define MLX90632_EE_REFRESH_RATE(ee_val) (ee_val & MLX90632_EE_REFRESH_RATE_MASK)
```

In this case `MLX90632_EE_REFRESH_RATE_MASK` should not be classified as ADDR then, but TEXT/STRING. Not to mention even if it is marked as addr, space before address changes that to bitwise AND in anycase based on C standard.

**Comment by guy-maurel** [comment]
Yes.
The change was introduced by bc13ab56e6b9f4e6e4338e4c36ae07a164754061.
```.diff
+         else if (  pc->flags.test(PCF_IN_PREPROC) // Issue #3559
+                 && chunk_is_token(pc, CT_AMP)
+                 && chunk_is_token(next, CT_WORD))
+         {
+            //LOG_FMT(LGUY, " ++++++++++ pc->flags: ");
+            //log_pcf_flags(LGUY, pc->flags);
+            set_chunk_type(pc, CT_ADDR);
+         }
```
But I don't how to do it better.
Any idea?

**Comment by Letme** [comment]
For me, previous version did not need fixing, while thisone does. I rather have correct behavior than a backwards incompatibility.

But I am afraid I do not know enough about the repo to give a valid idea. But if there is space to right by default it should be clear indication that it is meant as an operator and not as a pointer.

**Comment by guy-maurel** [comment]
PR #4074 is a bug fix proposal.
Please test it and report.

**Comment by NanXiao** [comment]
Hello, It seems I found a similar bug. For following code:
```
#define ACK 0x01
#define A(a) (((a) & ACK) != 0)
```
It will be formatted as:
```
#define A(a) (((a)&ACK) != 0)
```
And my `uncrustify` configurations:
```
......
sp_after_byref = remove
sp_addr  = remove
......
```
If need other configurations for debug, I can provide, thanks very much in advance!

**Comment by NanXiao** [comment]
> Can you add your uncrustify version?

@Letme I use both `0.78.1` and the master code which I build myself. Both have same problem.
