### ISSUE TITLE
Problem in splitting two  variable declaration statements

### ISSUE THREAD

**Issue by nimisha-agarwal** [uncrustify/uncrustify#2207]
Hi,
 I have a statement in a code which looks like the following:
float x1; /\*x co-ordinate of 1st point\*/ float x2;                            /\*x co- ordinate of 2nd point\*/

I want to put declarations in separate lines along with their comments such as:
float x1; /\*x co-ordinate of 1st point\*/ 
float x2;                            /\*x co- ordinate of 2nd point\*/

Even without comments will also work.
Is there a way in "uncrustify" to do so?

**Comment by gmaurel** [comment]
NO. You should split yourself first.
