### ISSUE TITLE
Objective-C. Redundant spaces won't be deleted.

### ISSUE THREAD

**Issue by jaybowong** [uncrustify/uncrustify#221]
The spaces before getter won't be deleted.

<pre>
@property (readonly,   getter = model) NSString *model;
@property (readonly, getter = manufacturer) NSString *manufacturer;
@property (readonly, getter = brand) NSString *brand;
</pre>

And spaces between '[' and 'self'. Also 'self' and ']'.

<pre>
        manufacturer = [     self propertyWithKey:propertyKeyManufacturer];
        manufacturer = [     self propertyWithKey:propertyKeyManufacturer       ];
</pre>

Add then I found this:

<pre>
@synthesize whatItShouldBe = _whatItShouldBe;
@synthesize       b = _b;
@synthesize c =      _c;
@synthesize d      = _d;
@synthesize e    =    _e;
</pre>

**Comment by guy-maurel** [comment]
The best you could get with the current git version is:
  https://github.com/uncrustify/uncrustify
Please test it and report!
config:
```
#sp_after_comma=remove
sp_after_comma=force

#sp_inside_square=remove
sp_inside_square=force

indent_align_assign=true
align_assign_span=1
sp_arith_additive=force
sp_assign=force
```
gives the output:
```
@property (readonly, getter = model) NSString *model;
@property (readonly, getter = manufacturer) NSString *manufacturer;
@property (readonly, getter = brand) NSString *brand;

manufacturer = [ self propertyWithKey:propertyKeyManufacturer ];
manufacturer = [ self propertyWithKey:propertyKeyManufacturer ];

@synthesize whatItShouldBe = _whatItShouldBe;
@synthesize       b        = _b;
@synthesize c              = _c;
@synthesize d              = _d;
@synthesize e              = _e;
```

**Comment by gmaurel** [comment]
No answer, we close.
