### ISSUE TITLE
Better handling of macros / ignoring single lines

### ISSUE THREAD

**Issue by davidrohr** [uncrustify/uncrustify#2215]
I am using macros to generate C++ code, which take segments of C++ code as parameters. Understandably. uncrustify cannot understand the macros and misformats the code. I am wondering why there is no simple solution to exclude macros or keywords from the processing.

I can use disable/enable_processing_cmt comments, but this requires always at least two lines. Is it possible to add a setting like ignore_line_cmt for a comment which would just ignore the current line. This would already help a lot.

Even better would be a list of macros, which can be defined in the config file, such that uncrustify could ignore the macro and all its parameters automatically.

**Comment by gmaurel** [comment]
Yes. uncrustify doesn't interpret the macros.
Make your question/proposal more details what you expected to get/how?

**Comment by davidrohr** [comment]
I suggest the following two things:

1. To add a new config setting disable_processing_line_cmt = [SOME STRING]. Whenever there is a comment at the end of a line containing [SOME STRING], this line is not reformatted (just as if there was the disable_processing_cmt before the line and enable_processing_cmt after the line. However, the line should still be indented to brace level.

2. To add a new config setting disable_macro_formatting = [MACRO_NAME1], [MACRO_NAME2]. If set, each macro content MACRO_NAME?(....) is not reformatted. The interior should be passed like a C macro, considering only normal braces (), commas, strings and comments but e.g. not curly braces.

**Comment by gmaurel** [comment]
I suggest: make a PR for that.
Thanks

**Comment by davidrohr** [comment]
OK, I might have a look when I find some time, but I guess I'd need to have a deeper look at the uncrustify code first... closing this.
