### ISSUE TITLE
Should align_assign_func_proto have been named align_assign_func_proto_span?

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#2216]
PR #2177 introduced the option align_assign_func_proto, and according to the documentation in options.h this is a 'span'.
```
// The span for aligning on '=' in function prototype modifier.
//
// 0 = Don't align (default).
extern BoundedOption<unsigned, 0, 5000>
align_assign_func_proto;
```

Since all other 'span' options have a _span suffix, I think it would be more correct if the option was named align_assign_func_proto_span. Or, is the documentation incorrect?

**Comment by guy-maurel** [comment]
PR #2220 do it
Thanks

**Comment by uncletall** [comment]
Should it be removed completely as it is not used in the code?
