### ISSUE TITLE
Array of structure initialization new line

### ISSUE THREAD

**Issue by BigfootN** [uncrustify/uncrustify#2217]
Hello,

I would like to know if there is an option that would force a new line after each structure initialization in an array of structure.

For example if I take this structure:

```C
struct foo {
    int a;
    int b;
};
```

I would like to get when creating an array of it:
```C
struct foo array_foo[] = {
    {0, 1},
    {2, 3}
};
```

And I get:
```C
struct foo array_foo[] = {
    {0, 1}, {2, 3}
};
```
The problem seems to be that I use in my configuration:
```
nl_remove_extra_new_lines = 1
```
and this option is very important to me.

Hoping that my question was clear enough, thank you very much in advance for any help.

**Comment by gmaurel** [comment]
It is a well known problem, we cann't solve now.
