### ISSUE TITLE
mod_full_brace_* = remove removes newline after closing brace

### ISSUE THREAD

**Issue by davidrohr** [uncrustify/uncrustify#2219]
Mod_full_brace_for remove removes the newline after a closing brace and appends the next source-code line to the line with the for loop, if the full loop was in one line before.

Tested with current master branch: Uncrustify-0.68-172-81f03dcd-dirty

Config: default config, only change: mod_full_brace_for = remove.
(The problem is not specific to for loops, mod_full_brace_if etc. produce the exact same misformatting. Also, the second line in the function must not necessarily be a for loop but can be anything.)

The following code
void foo()
{
   for(int i = 0;i < 1;i++) {return (false);}
   for(int i = 0;i < 1;i++) {return (false);}
}
is formatted as
void foo()
{
	for(int i = 0; i < 1; i++) return (false); for(int i = 0; i < 1; i++) return (false);
}
while it should become
void foo()
{
	for(int i = 0; i < 1; i++) return (false);
        for(int i = 0; i < 1; i++) return (false);
}

**Comment by guy-maurel** [comment]
PR #2222 is a bugfix proposal.
Please test it and report.

**Comment by davidrohr** [comment]
fixes the issue, thx

**Comment by guy-maurel** [comment]
Please test again with https://github.com/uncrustify/uncrustify/pull/2222/commits/fffeaac4cc490ab43984724d12a11f140bc5088f

**Comment by davidrohr** [comment]
the segmentation fault is fixed with fffeaac, but I think I found another issue with the newline after closing brace, creating a minimum example.

**Comment by davidrohr** [comment]
@guy-maurel : The issue is not fully fixed. The following example:

int foo()
{
    if (false) {return 1;}
    if (true) {return 2;}
    float a = 0;
}

is formatted as

int foo()
{
        if (false) return 1;
        if (true) return 2;float a = 0;
}

while it should ba

int foo()
{
        if (false) return 1;
        if (true) return 2;
        float a = 0;
}

**Comment by guy-maurel** [comment]
I get just now:
Uncrustify_d-0.68.1-158-1a6bf803
```.cpp
int foo()
{
        if (false) {return 1;}
        if (true) {return 2;}
        float a = 0;
}
```

**Comment by davidrohr** [comment]
You need to set mod_full_brace_if=remove to reproduce it.
Sorry, I should have been more specific!

Btw: the problem appears only with if statements, I cannot reproduce it with for loops.

**Comment by davidrohr** [comment]
@gmaurel : Why did you close this, the problem with the two if statements is still not fixed, or did I miss something? Or shall I open a new issue for it?

**Comment by davidrohr** [comment]
#2229 is fixed now
