### ISSUE TITLE
C/OC function call issue

### ISSUE THREAD

**Issue by qokelate** [uncrustify/uncrustify#2221]
version: Uncrustify-0.68-141-bcb1b18c/Uncrustify-0.68-162-81f03dcd
config: default
command: `uncrustify -c ~/.uncrustify_obj_c.cfg -o bb.m -f aa.m`

source:

```
else
{
   assert(header.payload_length<126 && header.payload_length >= 0);
}
```

result:

```
else
{
   assert(header.payload_length<126 && header.payload_length> = 0);
}
```

issue at `header.payload_length> = 0);`

**Comment by gmaurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by samishchandra** [comment]
No longer issue with latest master.

**Comment by qokelate** [comment]
test passed
