### ISSUE TITLE
Segmentation fault running uncrustify

### ISSUE THREAD

**Issue by davidrohr** [uncrustify/uncrustify#2224]
Uncrustify gives a segmentation fault running with the following config file [config.cfg](https://qon.jwdt.org/nmls/tmp/uncrustify-qon.cfg) on the following code:

static void GPUFailedMsgA(const long long int error, const char* file, int line)
{
  if (GPUFailedMsgAI(error, file, line)) {
    throw std::runtime_error("Failure");
  }
}

Command: uncrustify -c config.cfg -f a.h
Version: Uncrustify-0.68-182-2e821b42-dirty with the patch from uncrustify/uncrustify#2219
I could not produce a debug file with the -p debug command, probably because it crashes beforehand.

In case it helps: the stack trace is:
#0  0x00005555555a315b in convert_brace(chunk_t*) ()
#1  0x00005555555a5910 in do_braces() ()
#2  0x000055555561b02d in uncrustify_file(file_mem const&, _IO_FILE*, char const*, bool) ()
#3  0x000055555561d452 in do_source_file(char const*, char const*, char const*, bool, bool) ()
#4  0x0000555555586518 in main ()

**Comment by guy-maurel** [comment]
Please, test again with https://github.com/uncrustify/uncrustify/pull/2222/commits/fffeaac4cc490ab43984724d12a11f140bc5088f

**Comment by davidrohr** [comment]
fixed with fffeaac
