### ISSUE TITLE
Unbalanced double quote inserting whitespace

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2225]
Uncrustify-0.68
Configuration file:  default.

Input:

```
#include "Framework/UI/Window/CDlgComponentSubstitute.h>  // Compile error here...

// A lot of code here...

void Test()
{
    const char* const myString = "My string";
    // ...
}
```

Ouput:

```
#include "Framework/UI/Window/CDlgComponentSubstitute.h>

// A lot of code here...

void Test()
{
    const char* const myString = "My string ";     // Note that a whitespace was added!
    // ...
}
```

This is a tricky one, I'm not sure that something can be done about it!
Here's what happened.

- This is a small example. but the real file was much bigger, and the string was in the last function.
- The developer made a mistake.  He added a new include, but got confused and mixed " and <>.
- He ran Unscrutify.  He did not notice that the string was modified (added space) since it was at the end of the file.
- He then compiled the file. There was a compile error at line #1, of course.
- He corrected the error, so everything compiles now.
- He committed his changes.

Fortunately, our regression tests catched this one...

Ideally, Unscrustify shouldn't do anything since the " are not balanced...  but I'm not sure if this is possible!

**Comment by guy-maurel** [comment]
The characters from `Framework/...` untill `myString =` are tokenized as:
`#   1>       STRING_MULTI`
have a look to the output of `uncrustify ... -p p.txt`
which might be correct.

**Comment by chris-mich** [comment]
I tried the following command line:

`uncrustify.exe -c test.cfg -l CPP -f test.cpp -p test.txt`

It creates an empty "test.txt" file....

**Comment by guy-maurel** [comment]
My run, under Linux produces at the console:
```.txt
Parsing: chris-mich-ohne.cpp as language CPP
#include "Framework/UI/Window/CDlgComponentSubstitute.h>  // Compile error here...

// A lot of code here...

void Test()
{
    const char* const myString = "My string ";
    // ...
}
```
The test.txt file is:
```.txt
# Uncrustify_d-0.68.1-184-8a0eb7fd
# option(s) with 'not default' value: 0
#
# -=====-
# Line                Tag              Parent          Columns Br/Lvl/pp     Flag   Nl  Text
#   1>            PREPROC[         PP_INCLUDE][  1/  1/  2/  0][0/0/0][ 100080001][0-0] #
#   1>         PP_INCLUDE[               NONE][  2/  2/  9/  0][0/0/0][         1][0-0]  include
#   1>       STRING_MULTI[               NONE][ 10/ 10/ 37/  1][0/0/0][     10001][6-0]          "Framework/UI/Window/CDlgCompone
ntSubstitute.h>  // Compile error here...␤␤// A lot of code here...␤␤void Test()␤{␤    const char* const myString = "My
#   7>               WORD[               NONE][ 38/ 38/ 44/  1][0/0/0][         1][0-0]                                      stri
ng
#   7>       STRING_MULTI[               NONE][ 45/ 44/  1/  0][0/0/0][         1][3-0]                                          
   ";␤    // ...␤}␤
# -=====-
```

**Comment by gmaurel** [comment]
Remember, uncrustify is not a compiler.
It works at best on compilable source.

**Comment by chris-mich** [comment]
Still a problem with version 0.72 win64. 
Since we are using Uncrustify "on save", this behavior can produce nasty bugs!  We experienced one last week... :-(

**Comment by chris-mich** [comment]
Still present in version 0.73 win64.
This problem introduces bugs in our source code at least twice a year. :-(

**Comment by guy-maurel** [comment]
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!
```.txt
Uncrustify_d-0.74.0-44-f02c9c5d
do_source_file(1505): Parsing: chris-mich.cpp as language CPP
#include "Framework/UI/Window/CDlgComponentSubstitute.h>"  // Compile error here...

// A lot of code here...

void Test()
{
        const char* const myString = "My string";
        // ...
}
```

**Comment by chris-mich** [comment]
What about this example:
```
#include "vector>

void Test()
{
	char* myString = "My string";
}
```

I get a space inserted at the end of the string.

**Comment by chris-mich** [comment]
Still a problem in version 0.76.  This issue introduces bugs regularly in production code...

**Comment by guy-maurel** [comment]
Sorry, I cannot see the problem:
```cpp
void Test()
{
        const char* const myString = "My string";
        // ...
}
```
If necessary, join a NEW fille to be tested, merci

**Comment by chris-mich** [comment]
You missed the include file.  Let's do it all over again.

Uncrustify-0.76
Configuration file: default.

Input:
```
#include "vector>  // Parsing error here

void Test()
{
        char* myString = "My string";
}
```

Output:  (uncrustify does not issue any parsing errors, which is strange)
```
#include "vector>  // Parsing error here

void Test()
{
        char* myString = "My string ";    // <--- Note the extra space added here, causing a bug in production code.
}
```

I would expect that, in general, Uncrusfity should NOT change a file that is unable to parse.  For some reason, it does not issue any errors in that particular case...

**Comment by guy-maurel** [comment]
PR #3978 is a bug fix proposal.
Please test it and report.
