### ISSUE TITLE
mod_full_brace_if=remove removes newline after 2 consecutive one-liners

### ISSUE THREAD

**Issue by davidrohr** [uncrustify/uncrustify#2229]
This problem is related to uncrustify/uncrustify#2219, but it seems to appear only with mod_full_brace_if (mod_full_brace_for seems unaffected).

Steps to reproduce:
Tested with current master: 8a0eb7fdc6bf1c04b4c7e5660a85b5948b5b4cee
Change the following settings wrt. default config:
mod_full_brace_if               = remove
mod_full_brace_if_chain         = true

failing code sample:
int foo()
{
        if (false) {return 1;}
        if (true) {return 2;}
        float a = 0;
}

output:
int foo()
{
        if (false) return 1;
        if (true) return 2; float a = 0;
}

should be:
int foo()
{
        if (false) return 1;
        if (true) return 2;
        float a = 0;
}

**Comment by guy-maurel** [comment]
PR #2231 is a bugfix proposal. 
Olease test it and report.

**Comment by davidrohr** [comment]
The issue is no fully fixed with the new PR, thanks.
