### ISSUE TITLE
Uncrustify needs to support C++ R"FOO(....)FOO" raw string literals

### ISSUE THREAD

**Issue by orenbenkiki** [uncrustify/uncrustify#223]
Right now, uncrustify messes them up. Never mind the code looks ugly, it stops compiling, because uncrustify adds spaces and newlines between the `R` and the `"FOO(` parts.

**Comment by gmaurel** [comment]
I need an example and the config file.
Please add what you expected to get.

**Comment by CDanU** [comment]
I have tested this and could not reproduce the insertion of newline between `R`   and `"FOO(`.
The options `nl_max` (alters string content), `nl_after_access_spec` and `nl_var_def_blk_start` (newline issues before after the string) cause some problems.
