### ISSUE TITLE
mod_full_brace_if removes following blank line

### ISSUE THREAD

**Issue by davidrohr** [uncrustify/uncrustify#2232]
Affected version: master
Settings: default settings + mod_full_brace_if=remove

The exact same problem appears also with loops (mod_full_brace_for=remove).

Code:
void main()
{
  if (true) { return;}

  mInitialized = true;
  return 0;
}

Result:
void main()
{
  if (true) return;
  mInitialized = true;
  return 0;
}

Expected:
void main()
{
  if (true) return;

  mInitialized = true;
  return 0;
}

**Comment by gmaurel** [comment]
You need to add the option:
nl_after_if = force

**Comment by davidrohr** [comment]
Unfortunately, this is not what I want. I want the new line to be ignored, i.e., the new line should remain if it was there before.
nl_after_if = force adds a new line even if there was no new line before, which is not what I want.

**Comment by gmaurel** [comment]
Your example is not correct for what you are writting.

**Comment by davidrohr** [comment]
I do not understand, why the example would not be correct?
I want uncrustify to remove the braces, but not touch the new lines. So I expect the code with the newline (like in "Expected:"), but instead the newline is removed, like in "Result:".
I have only set mod_full_brace_if=remove, so I do not expect it to remove the newline.

**Comment by guy-maurel** [comment]
OK. Thanks for the message.
PR #2335 is a bugfix proposal.
Please test it and report.

**Comment by davidrohr** [comment]
works for me, thx
