### ISSUE TITLE
Spaces are not removed before "override" keyword

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2235]
Uncrustify-0.68
indent_class = true
align_func_proto_span = 1

Input:
```
class A
{
public:
    void     f()    override    ;     // Lots of extra spaces to remove
};
```

Output:
```
class A
{
public:
    void f()    override;   // Spaces not removed before "override", why?
};
```

We were wondering why spaces were not removed before "override" in that case.  Similar problem exists with "noexept" keyword.

Might not be a bug, just a missing option....

Cheers!

**Comment by guy-maurel** [comment]
You need to use the option:
sp_paren_qualifier    = force

**Comment by chris-mich** [comment]
This new option works well in version 0.69, thanks you! ;-)
