### ISSUE TITLE
Space not removed between else / elseif(...) and {

### ISSUE THREAD

**Issue by davidrohr** [uncrustify/uncrustify#2237]
Steps to reproduce:
version: f3ceb23e
configuration: default except as:
nl_brace_else                   = remove
nl_elseif_brace                 = remove
nl_else_brace                   = remove

Test case:
void foo()
{
  if (true)
  {
    bar();
    blah();
  }
  else if (false)
  {
    bar();
    blah();
  }
}

Expected:
void foo()
{
        if (true)
        {
                bar();
                blah();
        }else if (false) { <-- 1 space
                bar();
                blah();
        }
}

Result:
void foo()
{
        if (true)
        {
                bar();
                blah();
        }else if (false)  { <-- 2 spaces
                bar();
                blah();
        }
}

After running uncrustify twice, I get the expected result.

**Comment by guy-maurel** [comment]
You need to use some more options:
```cfg
sp_paren_brace   = force
sp_brace_else    = force
```

**Comment by davidrohr** [comment]
I have tried with the settings that you recommend, but the result is worse (now there are 3 spaces instead of 2):

Result:
void foo()
{
if (true)
{
bar();
blah();
}else if (false) { <-- 3 spaces
bar();
blah();
}
}

**Comment by guy-maurel** [comment]
Please push the p.txt and A.txt files from the command:
uncrustify -c davidrohr.cfg -f davidrohr.cpp  -L A 2>A.txt

**Comment by guy-maurel** [comment]
uncrustify -c davidrohr.cfg -f davidrohr.cpp -p p.txt -L A 2>A.txt

**Comment by davidrohr** [comment]
The test case and the files you requested are here: https://qon.jwdt.org/nmls/tmp/testcase.tar.bz2

**Comment by gmaurel** [comment]
Sorry for delay.
You have to use the option:
`sp_sparen_brace                 = force`

**Comment by davidrohr** [comment]
works, thx
