### ISSUE TITLE
split only string more then code width

### ISSUE THREAD

**Issue by amiya-elear** [uncrustify/uncrustify#2239]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
**************************
working version: Uncrustify-0.68-204-f3ceb23

i want to split string more then code width 

for an example 

input

if (ec_deallocate(deleteParamPayload) == -1) {
    ec_debug_log(LOG_ALERT, "Fatal :eshkc kashck ahskch khscka kshkjcx khskc asckjahsdjc cadcnjdc dkcjkdsvckvsdv sdkdsjvcbsdvbsd vdjvbkjdsbvjd vsdvsdvjbsdkvbksdjv sd vsdkvbksdjv sdjvjdsvjkdsv jjjjjsdvb sdjvkbssssssssssssssssv sdkjkkkkkkkkkkv sdkjvbkteParamPayload ,\
              exiting %s", ecSuicideString);

getting out put 
********
if (ec_deallocate(deleteParamPayload) == -1) {
    ec_debug_log(LOG_ALERT,
                 "Fatal :eshkc kashck ahskch khscka kshkjcx khskc asckjahsdjc cadcnjdc dkcjkdsvckvsdv sdkdsjvcbsdvbsd vdjvbkjdsbvjd vsdvsdvjbsdkvbksdjv sd vsdkvbksdjv sdjvjdsvjkdsv jjjjjsdvb sdjvkbssssssssssssssssv sdkjkkkkkkkkkkv sdkjvbkteParamPayload ,\
              exiting %s", ecSuicideString);

but it not spliting string means data inside " " 
 "Fatal :eshkc kashck ahskch khscka kshkjcx khskc asckjahsdjc cadcnjdc dkcjkdsvckvsdv sdkdsjvcbsdvbsd vdjvbkjdsbvjd vsdvsdvjbsdkvbksdjv sd vsdkvbksdjv sdjvjdsvjkdsv jjjjjsdvb sdjvkbssssssssssssssssv sdkjkkkkkkkkkkv sdkjvbkteParamPayload ,\
              exiting %s"
*******
i want to split this string if the size is more then code width 

excepted output should split string also if its more then code width

my code width=102
thanks in advance

**Comment by guy-maurel** [comment]
A closing brace is missed at the end of the statement.
NO!
A question: is it reasonable to use a so long string?
Could you use some more little strings?

**Comment by amiya-elear** [comment]
thanks for your replay, yes i miss that brace . some time its require very long string but my question is that if i select code width and ls code width = true it should break every line more then code width but its not breaking , is it possible to break those string or developer have to take care of those string

**Comment by guy-maurel** [comment]
yes, the developer has to help uncrustify

**Comment by amiya-elear** [comment]
Thanks maurel for your support 
so could you please help me one thing that what are the best practices  to handle those function call ,conditions and string exceeding code width given in config file. i need help on that .

**Comment by gmaurel** [comment]
Please give an example
