### ISSUE TITLE
C++11 user defined literals get a space inserted making it invalid

### ISSUE THREAD

**Issue by mteske** [uncrustify/uncrustify#2244]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
```
// legal C++11 user defined literal suffix _d8
double operator""_d8 (const char *s) {return 0.0;}

double xxx = 1.1_d8;
```
[//]: # "  • include the generated results"
```
// legal C++11 user defined literal suffix _d8
double operator""_d8 (const char *s) {
	return 0.0;
}

double xxx = 1.1_d 8
```
[//]: # "  • include the expected results"
```
// legal C++11 user defined literal suffix _d8
double operator""_d8 (const char *s) {
	return 0.0;
}

double xxx = 1.1_d8;
```
[//]: #
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"

Uncrustify-0.68_f
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
uncrustify can't recognize the user defined literal suffix.
