### ISSUE TITLE
Space added before colon in Objective-C message preceded by a cast

### ISSUE THREAD

**Issue by alanf** [uncrustify/uncrustify#225]
`Foo *viewController = (id)[self firstParentViewControllerOfClass:[Foo class]];`

becomes

`Foo *viewController = (id)[self firstParentViewControllerOfClass :[Foo class]];`

even if no rules are specified, and even if colon-space-removing rules are specified.

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
