### ISSUE TITLE
C++: indentation of initializer list

### ISSUE THREAD

**Issue by ghost** [uncrustify/uncrustify#226]
The initializer list is intended, althoug I used intend_ctor = 0 option and intend class option.

class A : public B;

class A::A(std::string m)
    : B(m)
{

}

Should be:

class A : public B;

class A::A(std::string m)
: B(m)
{

}

For class I want inheritance in same line and for constructor I want initializer list on next line without indentation.

how to do that correctly?

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
