### ISSUE TITLE
align_assign_span = 1 incorrectly aligns default values with = 0 that indicates pure virtual

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#2262]
Something strange happened in commit 3e4faf3 related to align_assign_span = 1
The example shows the situation.
Input:
```
class X16
{
public:
virtual void f() = 0;
void g(int x = 0);
};
```

Result:
```
class X16
{
public:
virtual void f() = 0;
void g(int x     = 0);
};
```
As we see, the default value is aligned with the = 0 that indicates pure virtual.
The expected result is that no reformatting should occur. This was the behaviour in the previous commit, fc26fbb.
[debug.txt](https://github.com/uncrustify/uncrustify/files/3086760/debug.txt)
[config.txt](https://github.com/uncrustify/uncrustify/files/3086767/config.txt)

**Comment by gmaurel** [comment]
You need to use the option:
`align_assign_decl_func = 1`

**Comment by guy-maurel** [comment]
PR #2267 is a bugfix proposal.
Please test it and report.

**Comment by arneforlie** [comment]
It looks good, so I'm closing the issue.
