### ISSUE TITLE
The operation `&` of boost - Archive is not formatted as expected

### ISSUE THREAD

**Issue by YvesZHI** [uncrustify/uncrustify#2265]
Here is my code:
```
class Test
{
public:
    Test() = default;
    template <typename Archive>
    void serialize(Archive &ar, const unsigned int version)
    {
        ar &a &b &ch;
    }

    int a, b;
    char ch;
};
```
This code comes from here: https://www.boost.org/doc/libs/1_69_0/libs/serialization/doc/tutorial.html

For us, obviously `ar &a &b &ch` is an operation, instead of reference, but it seems that it is regarded as the reference.

Here is a part of my config of Uncrustify:
```
sp_arith = force
sp_before_byref = force
sp_before_unnamed_byref = force
sp_after_byref = remove
```

**Comment by guy-maurel** [comment]
uncrustify doesn't know what ar is , at line 8.
It is NOT a compiler. The template is not "decode".
