### ISSUE TITLE
Random NL after open paren of macro call

### ISSUE THREAD

**Issue by kevkdev** [uncrustify/uncrustify#2268]
Uncrustify-0.66.1_f

A random NL is inserted after an open paren for a MACRO call embedded in a literal string. 

If I have XSTR(MAX_ENTRIES) on a separate line, it still wants to insert a NL after XSTR(.

Source:
```
void foo() {
	static std::string triggerQuery(
		"CREATE TRIGGER IF NOT EXISTS " TABLE_NAME "_limit"
		" BEFORE INSERT "
		" ON " TABLE_NAME
		" WHEN (SELECT COUNT(1) FROM " TABLE_NAME ") >= " XSTR(MAX_ENTRIES)
		" BEGIN"
		"  DELETE FROM " TABLE_NAME " WHERE " POWER_DOWN_COLUMN " = (SELECT MIN(" POWER_DOWN_COLUMN ") FROM " TABLE_NAME ");"
		" END;");
}
```

Output:
```
void foo() {
	static std::string triggerQuery(
		"CREATE TRIGGER IF NOT EXISTS " TABLE_NAME "_limit"
		" BEFORE INSERT "
		" ON " TABLE_NAME
		" WHEN (SELECT COUNT(1) FROM " TABLE_NAME ") >= " XSTR(
			MAX_ENTRIES)
		" BEGIN"
		"  DELETE FROM " TABLE_NAME " WHERE " POWER_DOWN_COLUMN " = (SELECT MIN(" POWER_DOWN_COLUMN ") FROM " TABLE_NAME ");"
		" END;");
}
```

Expected:
No Change

[PowerOnLog.txt](https://github.com/uncrustify/uncrustify/files/3118023/PowerOnLog.txt)
[debug.txt](https://github.com/uncrustify/uncrustify/files/3118025/debug.txt)
[uncrustify.cfg.txt](https://github.com/uncrustify/uncrustify/files/3118031/uncrustify.cfg.txt)

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
