### ISSUE TITLE
Unexpected new line in structure when a function pointer variable is used.

### ISSUE THREAD

**Issue by marlo200** [uncrustify/uncrustify#2275]
current version: Uncrustify-0.68-249-424ebc97

[debug2.txt, test2.c, test2_out.c, test2_expected.c](https://gist.github.com/marlo200/d3fe8dd57cc7d3d994235670f63e7073)"

When a function pointer is a variable in a structure a new line is added above the variable when the settings is: nl_var_def_blk_end  = 2.
This seems like an unexpected behavior inside a structure.

**Comment by gmaurel** [comment]
Suppress the parenthesis around *read to get what you wanted to have

**Comment by guy-maurel** [comment]
The new line is NOT present with the current git version.
