### ISSUE TITLE
Align function parameters with function pointer is confused

### ISSUE THREAD

**Issue by marlo200** [uncrustify/uncrustify#2276]
current version: Uncrustify-0.68-249-424ebc97

[debug3.txt, test3.c, test3_out.c, test3_expected.c](https://gist.github.com/marlo200/9d37232efd36c12989d3145e36e46871)"

the align variable
align_func_params               = true

aligns the function pointer function variable's parameters at the level of the original function parameters somewhat.  the files shows the issues.

**Comment by guy-maurel** [comment]
Right.
uncrustify needs a more complicated solution, which takes care of the level.

**Comment by guy-maurel** [comment]
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!
```.txt
Uncrustify_d-0.74.0-44-f02c9c5d
bool foo1( int     callbackID,
           void ( *pFn )( void *pArg1,
                          void *pArg2,
                          void *pArg3 ) );
```
