### ISSUE TITLE
Bracket alignment around function pointers when aligning function parameters

### ISSUE THREAD

**Issue by marlo200** [uncrustify/uncrustify#2277]
current version: Uncrustify-0.68-249-424ebc97

[debug4.txt, test4.c, test4_out.c, test4_expected.c](https://gist.github.com/marlo200/bded4c048121552fd3c041ae0dde3887)"

The second parameter in the function prototype is a function pointer with one parameter.
The brackets around the function pointer name gets moved to the left near the parameter type instead of staying put.

Uses:
align_func_params               = true
align_var_def_star_style        = 2

**Comment by guy-maurel** [comment]
You need to use the option with one of:
```.cfg
sp_after_type = ignore
sp_after_type = add
```
