### ISSUE TITLE
Align function parameters with function pointers gets very confused with 4 settings

### ISSUE THREAD

**Issue by marlo200** [uncrustify/uncrustify#2278]
current version: Uncrustify-0.68-249-424ebc97

[debug5.txt, test5.c, test5_out.c, test5_expected.c](https://gist.github.com/marlo200/bc1bf71b302ab941094193894d25d48c)"

Look at the output file.  the function prototypes get vary mangled.

Settings:
code_width                      = 100
ls_code_width                   = true
align_func_params               = true
align_var_def_star_style        = 2

**Comment by guy-maurel** [comment]
It is caused by the option:
 ` ls_code_width = true`
Please try with:
 ` ls_code_width = true`
I get:
```.c
bool foo1( LIST_tzHEAD               *pList,
           tucBOOL (                 *pFn )(
                   struct LIST_zNODE *pNode,
                   struct LIST_zDATA *pListData,
                   void              *arg ),
           void                      *arg );


```

**Comment by guy-maurel** [comment]
PR #2761 is a bugfix proposal.
Please test it and report.
