### ISSUE TITLE
Variable alignment gets changed when preceeded with special comments

### ISSUE THREAD

**Issue by marlo200** [uncrustify/uncrustify#2279]
current version: Uncrustify-0.68-249-424ebc97

[debug6.txt, test6.c, test6_out.c, test6_expected.c](https://gist.github.com/marlo200/b9504edee8af6ee624204b75341841aa)"

A variable after a comment line "/*| END |*/" mashed the variable alignment.
Line 9 of the output file.

options:
sp_arith = force

**Comment by guy-maurel** [comment]
PR #2280 is a bugfix proposal.
Please test it and report.

**Comment by guy-maurel** [comment]
PR #2288 is a bugfix proposal.
Please test it and report.
PR #2280 is closed.
