### ISSUE TITLE
Uncrustify fails to parse single-statement for loop which is an @autoreleasepool

### ISSUE THREAD

**Issue by zachriggle** [uncrustify/uncrustify#2289]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Uncrustify fails to parse Objective-C code which uses an `@autoreleasepool` inside a `for` loop when the pool is not enclosed in a brace.  This does not happen with the default configuration (i.e. no config specified).  This DOES happen with the linked configuration.

```
$ uncrustify --version
Uncrustify-0.68_f
```

Failing code:

```
+ (void)foo:(bar)block {
    for (int i = 0; i < 5; i++) @autoreleasepool {
    	// stuff
    }
}
```

Working code, which is functionally identical (`@autoreleasepool` is a single statement)

```
+ (void)foo:(bar)block {
    for (int i = 0; i < 5; i++) { 
        @autoreleasepool {
    	    // stuff
        }
    }
}
```

Errors on the failing example:

```
Parsing: test.m as language OC
parse_cleanup(425): test.m, orig_line is 5, Error: Unexpected '}' for 'VBRACE_OPEN', which was on line 2
Unmatched BRACE_CLOSE
at orig_line=5, orig_col=1
Try the option 'tok_split_gte = true'
```

Configuration used: https://github.com/zachriggle/config/blob/master/.uncrustify.cfg
Logging output: https://gist.github.com/zachriggle/f1ab3b7861a3e85c7928f82391350ce2

For clarity, the suggested `tok_split_gte` is not relevant here

**Comment by guy-maurel** [comment]
Thanks for the message.
PR #2289 is a bugfix proposal.
Please test it and report.

**Comment by zachriggle** [comment]
Looks like it works! Sorry for the delay
