### ISSUE TITLE
Windows 10 64 bit-program immediately closes

### ISSUE THREAD

**Issue by Paul47** [uncrustify/uncrustify#2290]
uncrustify-0.68.1-win32.zip downloaded from Sourceforge and unzipped. Ran uncrustify.exe. A window flashes on the screen then immediately closes. It appears to the program window rather than a message. Too quick to get any other information. 
Windows 10, 64 bit, latest windows updates

I downloaded source from github with the latest commit 0be1b1e. Tried to compile in VS2017 but had a number of errors.

**Comment by jibsen** [comment]
Uncrustify is a command-line tool, if you run it by double-clicking the executable, it will open a command prompt run the executable (which prints the help message), and then immediately close the window as uncrustify exits.

You can open the command prompt (which is an interactive terminal window that allows you to run commands without it closing as soon as they exit) and run uncristify.exe there, or I believe there are some GUI tools that can use uncrustify under the hood (see end of README).
