### ISSUE TITLE
"<>" in embedded sql

### ISSUE THREAD

**Issue by slfmessi** [uncrustify/uncrustify#2291]
Hello, everyone.

When I use uncrustify to format embedded-SQL code, I found it will change "<>" to "< >".

I can set ` sp_compare = ignore` to avoid this problem, but I still want to format compare operators. Are there other options?

**Comment by gmaurel** [comment]
Please push an example.

**Comment by slfmessi** [comment]
Thanks, Here is the example.
My uncrustify version: 
```
D:\Work\SVN\bsp>uncrustify --version
Uncrustify-0.68.1
```
Raw code:  
`EXEC SQL SELECT COUNT(1) FROM DP007 WHERE AGE<>20;`

After formatting:  
`EXEC SQL SELECT COUNT(1) FROM DP007 WHERE AGE < > 20;`

**Comment by guy-maurel** [comment]
Please make a test with your data:
`uncrustify -c slfmessi.cfg -f slfmessi.cpp -p p.txt`
and push the p.txt file
