### ISSUE TITLE
Force line ending

### ISSUE THREAD

**Issue by Josar** [uncrustify/uncrustify#2294]
Is it possible to force line endings?

It seems that the setting
```
# The type of line endings. Default=Auto.
newlines                        = auto     # auto/lf/crlf/cr
```
 when set to a specific line ending, only changes the line endings for lines that are modified.

**Comment by guy-maurel** [comment]
Yes.
Have a look to the test examples:
_<uncrustify>/tests/input/cpp/lineEndings-*.cpp_

which have:
```.txt
file input/cpp/lineEndings-*
input/cpp/lineEndings-Mac.cpp:  ASCII text, with CR line terminators
input/cpp/lineEndings-Unix.cpp: ASCII text
input/cpp/lineEndings-Win.cpp:  ASCII text, with CRLF line terminators
```

**Comment by guy-maurel** [comment]
Any comment?

**Comment by Josar** [comment]
Tests showed behaviour as expected. All line endings are changed. Could not reproduce the wrong behaviour described by my colleague. This can be closed.
