### ISSUE TITLE
Ternary operator issue

### ISSUE THREAD

**Issue by modsrm** [uncrustify/uncrustify#23]
The following exception is thrown when "assert ( a != null ) && ( b != null ) : Messages.getString( "awt.74" );" is parsed:

JavaBug2.java:5 unexpected colon in col 47 n-parent=NONE c-parent=NONE l=2 bl=2

The following exception is thrown when "
while( skipped < length && ( count = read( buffer, 0, ( length - skipped > buffer.length ) ? buffer.length : length - skipped ) ) >= 0 ) {
            skipped += count;
        }
" is parsed:

JavaBug.java:5 Error: Unexpected '>' for 'PAREN_OPEN', which was on line 5
JavaBug.java:5 Error: Unexpected ')' for 'ANGLE_OPEN', which was on line 5
JavaBug.java:11 Error: Unexpected '}' for 'ANGLE_OPEN', which was on line 5
JavaBug.java:12 Error: Unexpected '}' for 'ANGLE_OPEN', which was on line 5
JavaBug.java:1 Unmatched BRACE_OPEN
JavaBug.java:3 Unmatched BRACE_OPEN
JavaBug.java:5 Unmatched SPAREN_OPEN
JavaBug.java:5 Unmatched ANGLE_OPEN
JavaBug.java:1 Unmatched BRACE_OPEN
JavaBug.java:3 Unmatched BRACE_OPEN
JavaBug.java:5 Unmatched SPAREN_OPEN
JavaBug.java:5 Unmatched ANGLE_OPEN

They are likely both related to the ternary operator.

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
