### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by ios-sagar** [uncrustify/uncrustify#2300]
I was successfully using uncrustify for my ongoing 2 projects on MAC OS with Xcode version 10.1
However I got update from Apple for my MAC OS and now my OS is 10.14.2
after this update when I try to use uncrustify on my new code, every time it gives the error,
"Failed to load"
Though the file path is given the correct one, I can jump to file using same path, but uncrustify not working now.

This is the message -
Failed to load (Qphoto/Class⁩/View/LeftMenuViewController⁩/LeftMenuViewController.m)

Can anyone please help me out in this.

Thanks.

**Comment by guy-maurel** [comment]
Yes.
Please push the complete command you are using. Or a screen shot.

**Comment by ios-sagar** [comment]
I just solved that
there was a problem while drag and drop the file path from Finder to Terminal after updating to system to new one.
So I need to write the file path manually and then I tried, it worked.
Thanks
