### ISSUE TITLE
Constructor colon not recognized in nested class of class template

### ISSUE THREAD

**Issue by troiganto** [uncrustify/uncrustify#2305]
This is continued from #2302, but does not require its bug fix, nor the `noexcept` specifier. Tested against the current master, 3b667c905bf5b16610e5dd23738c9842c7f7a405.

Custom uncrustify settings:
```
nl_class_colon  = force
nl_constr_colon = remove
```
Example code:
```cpp
template<class T>
class Foo<T>::Bar {
  Bar() : i(0) // gets split, but shouldn't
  {}
};
```
Expected output:
```cpp
template<class T>
class Foo<T>::Bar {
Bar() : i(0)   // gets split, but shouldn't
{
}
};
```
Actual output:
```cpp
template<class T>
class Foo<T>::Bar {
Bar() :
	i(0)   // gets split, but shouldn't
{
}
};
```

[Debug file](https://github.com/uncrustify/uncrustify/files/3233490/debug-output.txt)

Thank you for your time and please tell me if you need any further information.

**Comment by gmaurel** [comment]
Use an empty configuration file.

**Comment by troiganto** [comment]
Input:
```cpp
template <class T>
class Foo<T>::Bar {
    Bar() : i(0) // gets split, but shouldn't
    {}
};
```

Output:
```cpp
template <class T>
class Foo<T>::Bar {
Bar() : i(0)     // gets split, but shouldn't
{
}
};
```

[Debug file](https://github.com/uncrustify/uncrustify/files/3275450/debug.txt)

It seems the bug only occurs if you pick different settings for class colon and constructor colon.

**Comment by guy-maurel** [comment]
Show me the first lines of the command
uncrustify ... -L A
Do you get:
Parsing: troiganto-2305.cpp as language CPP
or:
Parsing: troiganto-2305.cpp as language C

**Comment by troiganto** [comment]
Executing this line:
```bash
uncrustify -c empty.cfg -p debug.txt -f c.cpp -L A
```
gives, among other things, these lines:
```
Will export parsed data to: debug.txt
config_file = empty.cfg
output_file = null
source_file = c.cpp
source_list = null
prefix      = null
suffix      = null
assume      = null
replace     = 0
no_backup   = 0
detect      = 0
check       = 0
if_changed  = 0
load_mem_file: 'c.cpp' encoding looks like ASCII (0)
Parsing: c.cpp as language CPP
```
so the file does get interpreted as C++.

I've attached the full log for completeness' sake: [full.log](https://github.com/uncrustify/uncrustify/files/3277442/full.log). I've noticed that the problematic colon is tokenized as `COLON`. If I change the second line from `class Foo<T>::Bar` to `class Bar`, it is instead tokenized as `CONSTR_COLON`.

Thank you again for your help, I really appreciate it!

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
I get:
`#   3>       CONSTR_COLON[           FUNC_DEF][  9/ 21/ 22/  1][1/1/0][ 108000400][0-0]         :`

**Comment by troiganto** [comment]
That is strange. With the latest commit (294af57, 2 days ago), this code:
```cpp
template<class T>
class Foo<T>::Bar {
  Bar() : i(0) // gets split, but shouldn't
  {}
};
```
still produces:
```
#   3>        CLASS_COLON[               NONE][  7/  9/ 10/  1][1/1/0][ 100000400][0-0]       :
```
([Full log](https://github.com/uncrustify/uncrustify/files/3339593/debug.txt))

Am I maybe on the wrong branch? What is the commit hash of the version that gives `CONSTR_COLON` on a `Foo<T>::Bar`?

**Comment by guy-maurel** [comment]
I think it is: 294af57b9cf5b8d3426a5fcf25999d7b76a174d9 on 2019-06-26 16:13:35

**Comment by guy-maurel** [comment]
Your code is NOT correct.
I modify it to:
```.cpp
template<class T>
class Foo<T>::Bar {
  void Bar(int iii) : iii(0)
  {}
};
```

**Comment by troiganto** [comment]
```cpp
template<class T>
class Foo<T>::Bar {
  void Bar(int iii) : iii(0)
  {}
};
```
I can confirm that with `void` in front of `Bar()`, the colon `:` gets parsed as `CONSTR_COLON`.

However, I don't think this is valid C++. Normal functions have a return type in front of the function name, yes, but constructors and destructors don't. For example, check the examples on the bottom of the [constructors page](https://en.cppreference.com/w/cpp/language/default_constructor) and [destructors page](https://en.cppreference.com/w/cpp/language/destructor) of CppReference.Com:

```cpp
struct A
{
    int i;
 
    A ( int i ) : i ( i ) 
    {
        std::cout << "ctor a" << i << '\n';
    }
 
    ~A()
    {
        std::cout << "dtor a" << i << '\n';
    }
};
 ```

And for these constructors, which don't have a return type before them, Uncrustify at commit 294af57 does not parse the colon `:` correctly.

**Comment by guy-maurel** [comment]
Yes.

**Comment by guy-maurel** [comment]
PR #2325 is a bugfix proposal.
Please test it and report.

**Comment by troiganto** [comment]
Works like a charm! Thank you for all your help!
