### ISSUE TITLE
Array initializer list alignment

### ISSUE THREAD

**Issue by davxy** [uncrustify/uncrustify#2306]
Hi,
Given this code snip:

```
static const unsigned char exp_tab[] = {
    32,  1,  2,  3,  4,  5,
     4,  5,  6,  7,  8,  9,
     8,  9, 10, 11, 12, 13,
    12, 13, 14, 15, 16, 17,
    16, 17, 18, 19, 20, 21,
    20, 21, 22, 23, 24, 25,
    24, 25, 26, 27, 28, 29,
    28, 29, 30, 31, 32,  1
};
```
I wuold like uncrustify to format it properly (indeed as it was originally above).

After parsing it it outputs the following:

```
static const unsigned char exp_tab[] = {
	32,  1,  2,  3,  4,  5,
	4,  5,  6,  7,  8,  9,
	8,  9, 10, 11, 12, 13,
	12, 13, 14, 15, 16, 17,
	16, 17, 18, 19, 20, 21,
	20, 21, 22, 23, 24, 25,
	24, 25, 26, 27, 28, 29,
	28, 29, 30, 31, 32,  1
};

```

I've tried several combinations of the following flags with no success:
- align_number_right = tried both left/right
- align_var_struct_span  = tried 0,1,3,6 ..
- align_var_struct_thresh  = tried 0,1,3,6...
- align_var_struct_gap = tried 0,1,3,6

At least it would be useful to instruct the tool the leave the array "as is".

**Comment by gmaurel** [comment]
It is a known problem.
