### ISSUE TITLE
uncrustify does not handle handle nested closing braces of static_cast <template_function<T>>

### ISSUE THREAD

**Issue by bshm** [uncrustify/uncrustify#2309]
Uncrustify does not seem to like consecutive closing angle braces when a static_cast is involved and tok_split_gte is configured to false:

### example.cpp
```cpp
#include <type_traits>
enum class EC {};
int main()
{
  return static_cast<std::underlying_type_t<EC>>(17);
}
```

### invocation
```
$ ./uncrustify  -p debug.txt -c ../tests/config/aet.cfg -f example.cpp
Parsing: example.cpp as language CPP
parse_cleanup(442): pc->orig_line is 6, orig_col is 1, text() is '}', type is BRACE_CLOSE
parse_cleanup(444): (frm.top().type + 1) is ANGLE_CLOSE
parse_cleanup(451): File: example.cpp, orig_line is 6, orig_col is 1, Error: Unexpected '}' for 'ANGLE_OPEN', which was on line 5
parse_cleanup(759): Unmatched BRACE_CLOSE
   orig_line is 6, orig_col is 1
parse_cleanup(763): Try the option 'tok_split_gte = true'
$ echo $?
1
```
debug.txt is not created :-(

### Version
```
./uncrustify -v
Uncrustify-45b836c
```

### generated results:
uncrustify exits with error 1

### expected results:
uncrustify exits without error

[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
You need to use the options:
```.cfg
tok_split_gte         = true
sp_permit_cpp11_shift = true
```

**Comment by bshm** [comment]
with `sp_permit_cpp11_shift = true` the angle braces are always split, no matter how `tok_split_gte` is set
```
return static_cast<std::underlying_type_t<EC> >(17);
```
But I can live with that... I'm closing this as uncrustify does not crash anymore
Thanks
