### ISSUE TITLE
Regression for --no-backup argument

### ISSUE THREAD

**Issue by MathPlayer** [uncrustify/uncrustify#2313]
The 0.69 version introduced a regression for the `--no-backup` argument (the argument does not work as before).

Consider the following commands:
```shell
~ $ uncrustify --update-config -o output.cfg
~ $ echo """
#include <iostream>
int main() { return 0; }
""" > main.cpp
~ $ uncrustify -c output.cfg --no-backup main.cpp
```
For `Uncrustify-0.68_f`, the `main.cpp` file is updated in-place and no backup is created; the output after the last command above is:
```
Parsing: main.cpp as language CPP
```
For `Uncrustify-0.69.0_f`, the `main.cpp` file is updated in-place and a `main.cpp.uncrustify` backup file is created; the output after the last command above is:
```
Output suffix: .uncrustify
Parsing: main.cpp as language CPP
```

Both versions of uncrustify were installed with `brew`.

The problem is easily solved by providing both `--replace` and `--no-backup`.

**Comment by guy-maurel** [comment]
Have a look to 01692961425f91a492d8bb2f48ad374c4d66a787
It shows details about the change.

**Comment by MathPlayer** [comment]
If the intended behavior is to use `--replace` in conjunction with `--no-backup`, I would say `--no-backup` needs a better documentation. If not, playing a bit with the conditions should fix this small issue.
I can work on addressing this in either of the ways, as long as you point me in the right direction.

**Comment by guy-maurel** [comment]
Please, make a proposal. It is welcome.

**Comment by mihaipopescu** [comment]
This is indeed a good find. Thanks @MathPlayer.
