### ISSUE TITLE
Hang on small syntax error

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2315]
Uncrustify-0.69.0
Config:  default

Source code:
```
void main()
{
    test)          // Syntax error here
    func();
}
```

This code has a syntax error and does not compile.  Uncrustify is issuing some errors, which is OK:

```
parse_cleanup(440): pc->orig_line is 3, orig_col is 13, text() is ')', type is PAREN_CLOSE
parse_cleanup(442): (frm.top().type + 1) is BRACE_CLOSE
parse_cleanup(447): File: test.cpp, orig_line is 3, orig_col is 13, Error: Unexpected ')' for 'BRACE_OPEN', which was on  line 2
```

However, Uncrustify is hanging there and never returns.

**Comment by guy-maurel** [comment]
Thanks for the message.
PR #2316 is a bugfix proposal.
Please test it and report.

**Comment by chris-mich** [comment]
Seems ok in version 0.72 win64, thank you!!
