### ISSUE TITLE
nl_if_brace=add and nl_split_if_one_liner=false don't work together

### ISSUE THREAD

**Issue by deitry** [uncrustify/uncrustify#2318]
Consider config options:
```
nl_split_if_one_liner           = false
nl_if_brace                     = add
```
I expect to this line stay the same:
```
if (true) return;
```
but in fact it reformats to
```
if (true)
    return;
```

Docs for `nl_if_brace` say: `# Add or remove newline between 'if' and '{'.`, but actually it touches non-braced scope too.

Tested on 0.68_f (actually, it's [ament_uncrustify](https://github.com/ament/ament_lint/tree/master/ament_uncrustify) with custom config file) and current master, `Uncrustify-0.69.0-26-45b836cf`.

**Comment by guy-maurel** [comment]
You need to use the option:
`nl_if_leave_one_liners = true`

**Comment by krys-g** [comment]
`nl_if_leave_one_liners=true` solves the issue for me.

However, I have a similar problem with array or struct initializers.

For example, this .cpp source:
```
   int q[] = {};
   int r[] = { 1, 2 };
```
with this configuration:
```
nl_assign_brace=add
nl_assign_leave_one_liners=true
nl_class_leave_one_liners=true
# ...
# all nl_*_leave_one_liners are set to true.
```
yields
```
	int q [] =
	{
	};
	int r [] =
	{
		1, 2
	};
```

**Comment by deitry** [comment]
@guy-maurel Excuse me, missed this option somehow. Confirm, it works as expected.

@krys-g I guess it deserves its own issue, so I close this one
