### ISSUE TITLE
Objective-C Bug: Space is removed in "for in" loops with method call

### ISSUE THREAD

**Issue by benny-shotvibe** [uncrustify/uncrustify#232]
This is similar to #141 

This is what uncrustify gives, notice the space has been removed after the "in" word:

```
for (Child *c in[parent getChildren]) {
    // ...
}
```

This appears to be caused by `sp_before_square`

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
