### ISSUE TITLE
Short array/struct initializers always spilt

### ISSUE THREAD

**Issue by krys-g** [uncrustify/uncrustify#2321]
As seen with Uncrustify-0.69.0-26-45b836cf, short one-liners for array or struct initializers are split, but I wish they weren't.

For example, this .cpp source:
```
   int q[] = {};
   int r[] = { 1, 2 };
```

with this configuration:
```
nl_assign_brace=add
nl_assign_leave_one_liners=true
nl_class_leave_one_liners=true
# ...
# all nl_*_leave_one_liners are set to true.
```
yields
```
	int q [] =
	{
	};
	int r [] =
	{
		1, 2
	};
```

I expected the one-liners to be kept in a single line.

It's a bit similar to https://github.com/uncrustify/uncrustify/issues/1052, but I don't care about the number of elements.

**Comment by guy-maurel** [comment]
Please use this:
 ` uncrustify -c krys-g.cfg -f krys-g.cpp -p p.txt -L A 2>A.txt`

And push the p.txt and A.txt files.

**Comment by krys-g** [comment]
Hi Guy,

As instructed; please refer to the attached files. I also provided the source example.

[A.txt](https://github.com/uncrustify/uncrustify/files/3340457/A.txt)
[krys-g.cfg.txt](https://github.com/uncrustify/uncrustify/files/3340458/krys-g.cfg.txt)
[krys-g.cpp.txt](https://github.com/uncrustify/uncrustify/files/3340459/krys-g.cpp.txt)
[p.txt](https://github.com/uncrustify/uncrustify/files/3340460/p.txt)

Thank you.

**Comment by guy-maurel** [comment]
The pushed files are from another problem!

**Comment by krys-g** [comment]
Sorry, I did not follow what you said. I tested again by downloading the files attached above, regenerated A.txt and p.txt, and got the same outputs. The formatted code has the problem I reported in the ticket description (provided krys-g.cpp.txt is renamed as krys-g.cpp).

**Comment by guy-maurel** [comment]
You have created the issue with the source:
```.cpp
   int q[] = {};
   int r[] = { 1, 2 };
```
Very different from krys-g.cpp.txt

**Comment by krys-g** [comment]
Thank you.
