### ISSUE TITLE
Confusion with anonymous namespace

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2324]
Config:
```
# Uncrustify-0.68.0

indent_class    = true
sp_before_byref = remove
sp_after_byref  = add
sp_after_angle  = force
sp_before_dc    = remove
```

Input (no changes are expected):
```
namespace
{

class CMyClass
{
public:
    double Compute( const std::vector< double >& values_ );
};

}

double ::CMyClass::Compute( const std::vector< double >& values_ )
{
    // Do stuff
}
```

Output:
```
namespace
{

class CMyClass
{
public:
    double Compute( const std::vector< double >& values_ );
};

}

double::CMyClass::Compute( const std::vector< double > &values_ )
{
    // Do stuff
}
```

This is a tricky one!!  Two things:

1. White space was removed between "double" and "::"
2. On the same line, "&" should be next to the type (like in the method declaration)

Not sure if Uncrustify has a way to know that "double" is a return type... ;-)

**Comment by guy-maurel** [comment]
PR #2327  is a bugfix proposal.
Please test it and report.

@chris-mich: where do you live?

**Comment by chris-mich** [comment]
Thank you for the fix, I will give it a try when version 0.70 will be out!
I live in Quebec, Canada.

**Comment by guy-maurel** [comment]
@chris-mich : Bonsoir! Dans quelle ville?
Je suis déjà passé plusieurs fois entre Montréal, Chibougameau et Pointe de Percé.

**Comment by chris-mich** [comment]
Chibougamau, vraiment!!  Je n'y suis jamais allé!  Vous avez donc fait pas mal le tour, il vous reste la Côte-Nord. ;-)
Pour ma part, je demeure dans la ville de Québec.

**Comment by guy-maurel** [comment]
Voici mon adresse de courriel: guy.j@maurel.de pour le prochain message.
Au dernier passage, nous avons fait le tour des cantons de l'est et
une pointe au musée acadien de Bonaventure, QC G0C 1E0.
C'est fort intéressant.
À + le plaisir de te lire.

**Comment by chris-mich** [comment]
There is still a small problem, but I'm not sure that Uncrustify can do something about it.  Here's a simplified version of the original issue.

Config:
```
# Uncrustify-0.76
sp_before_dc = remove
```

Input (no changes are expected)
```
double ::CMyClass::Compute()
{
	return 0.0;
}
```

Output: 
```
double::CMyClass::Compute()     // <-- Note the space that was removed after "double".
{
	return 0.0;
}
```

Here, "double" is the return type.  "::" before CMyClass is used to indicate that the class was declared in the anynomous namespace.
