### ISSUE TITLE
Request: Add support for trailing return types

### ISSUE THREAD

**Issue by elnull** [uncrustify/uncrustify#2330]
Can you add support for trailing return types? Now `->` is processed as operator, but it should be possible to add or remove spaces around with separate options.

**Comment by guy-maurel** [comment]
Please push an example about what you wanted to get.

**Comment by elnull** [comment]
In function declaration it should be possible to configure spaces count around `->` operator. For, example
```cpp
auto max(int a, int b)->int;
```
could be transformed to
```cpp
auto max(int a, int b) -> int;
```

**Comment by guy-maurel** [comment]
You need to use the option:
  ` sp_member = force`

**Comment by elnull** [comment]
No. I'd like to have no spaces around member operator `->`, but have spaces around trailing return type operator `->`.

**Comment by guy-maurel** [comment]
PR #2341 is a bugfix proposal.
Please test it and report.

**Comment by elnull** [comment]
It works to me. Thank you.

**Comment by guy-maurel** [comment]
Thanks.
Please test it again and report.

**Comment by elnull** [comment]
Now all of my cases work as expected.
