### ISSUE TITLE
It is not possible to exclude the CT_ASM_COLON for option sp_before_square in C asm

### ISSUE THREAD

**Issue by pietvr** [uncrustify/uncrustify#2331]
Please refer to the option sp_before_square from uncrustify.cfg:

```
## Add or remove space before '[' (except '[]')
sp_before_square                = remove   # ignore/add/remove/force
```

Altough
```
#define SET_STACK(stack)            \
    do {                            \
        __asm__ __volatile__ (      \
            "mov S, %[oper]"        \
            :                       \
            :[oper] "r" (stack)    \
            : "S"                   \
            );                      \
    } while(0)
```
is valid C, most code written is with space near the ':['
```
            : [oper] "r" (stack)**    \
```

So to make  **sp_before_square** really useful we should be able to exclude this change

The easiest working diff for this is:
```
git diff  ../src/space.cpp
diff --git a/src/space.cpp b/src/space.cpp
index ac967c90..1a1e7288 100644
--- a/src/space.cpp
+++ b/src/space.cpp
@@ -957,6 +957,10 @@ static iarf_e do_space(chunk_t *first, chunk_t *second, int &min_sp)
       {
          return(IARF_FORCE);
       }
+      if (chunk_is_token(first, CT_ASM_COLON))
+      {
+         return(IARF_FORCE);
+      }
 
       log_rule("sp_before_square");
       return(options::sp_before_square());
```

But when this is not acceptable an option like 
**sp_before_square_exclude_asm** could be added.

**Comment by pietvr** [comment]
When the maintainers think sp_before_square_exclude_asm is a good idea, I'm willing to implement.
But not anytime soon ....

**Comment by guy-maurel** [comment]
Fine.
Please make a PR of it, add an example with expected output.

**Comment by pietvr** [comment]
What do you think is the best approach?
1) Just exclude the CT_ASM_COLON as above in the sample code or
2) Provide an option to control this CT_ASM_COLON behavior?

For us is 1) is fine. But maintainers could like 2) more as the behavior will then be customizable.
I can make a PR for both. 1) is of course a lot easier ...

**Comment by guy-maurel** [comment]
Provide a PR with a new option.

**Comment by guy-maurel** [comment]
Have a look to the test data for it, bug_2331.c, and the expected data.
I get an error:
```.txt
index 86d9286f..67088d94 100644
--- a/home/guy/Software/uncrustify/tests/expected/c/10006-bug_2331.c
+++ b/home/guy/Software/uncrustify/build/tests/results/c/10006-bug_2331.c
@@ -6,6 +6,6 @@
                        : [oper] "r" (stack)    \
                        : "S"                   \
                        );                      \
-       } while(0)
+       } while (0)
 
 int somearray[10];

```
Unfortunatly, I have merge your PR before testing again.
@pietvr : Please make a new PR to solve it.
Thanks

**Comment by pietvr** [comment]
I will do this today.
