### ISSUE TITLE
Alignment problem when switching function call to method call

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2332]
Uncrustify-0.69.0

Configuration:  default.

Input:
```
struct CPoint
{
    int x, y, z;
};

CPoint GetPoint()
{
    return { GetCoordinateXFromObject(),
             GetCoordinateYFromObject(),
             GetCoordinateZFromObject() };
}

CPoint GetPoint( CObject obj_ )
{
    return { obj_.GetCoordinateXFromObject(),
             obj_.GetCoordinateYFromObject(),
             obj_.GetCoordinateZFromObject() };
}
```

Output (no changes are expected):
```
struct CPoint
{
    int x, y, z;
};

CPoint GetPoint()
{
    return { GetCoordinateXFromObject(),
             GetCoordinateYFromObject(),
             GetCoordinateZFromObject() };
}

CPoint GetPoint( CObject obj_ )
{
    return { obj_.GetCoordinateXFromObject(),
                 obj_.GetCoordinateYFromObject(),
                 obj_.GetCoordinateZFromObject() };
}
```

We have code looking like this.  We are constructing a CPoint within the return statement and initializing the x, y, z members from the return values of the three function calls.   

In the first GetPoint() overload, Uncrustify aligns the function calls, which is great!!
In the second GetPoint() overload, the alignment is different, just because we call a method instead of a function...

Thanks a lot or your great support!! :-)

**Comment by gmaurel** [comment]
PR #2731  is a bugfix proposal.
Please test it and report.
