### ISSUE TITLE
Unable to meet our code style and other issues

### ISSUE THREAD

**Issue by smaxdax** [uncrustify/uncrustify#2338]
We are currently desperate, because we are not able to meet our code style by our current uncrustify configuration. We already spent plenty hours setup our configuration correctly, but there are still issues we are not able to fix. To show our issues I prepared a code example that shows our wanted code style where I marked the issues by a comment. 

This is the example for the code style we want to have:
[WantedResult.txt](https://github.com/uncrustify/uncrustify/files/3367300/WantedResult.txt)

When we run uncrustify with our current configuration, we get following result:
[UncrustifyResult.txt](https://github.com/uncrustify/uncrustify/files/3367304/UncrustifyResult.txt)

This is our current configuration:
[config.txt](https://github.com/uncrustify/uncrustify/files/3367310/config.txt)

Here is a screenshot of the compare between wanted and real result:
![Compare](https://user-images.githubusercontent.com/52651748/60794186-80706b80-a169-11e9-918d-bd44bf4fbc7b.png)

We are not sure if some of the marked issues are a wrong configuration from our side or a bug. 
Could you please help us.

**Comment by guy-maurel** [comment]
A first comment:
```.cfg
# guy maurel, July 2019
# ISSUE_1:
nl_ds_struct_enum_close_brace = true
#
# ISSUE_9:
nl_before_if = remove

```
Next comment soon

**Comment by guy-maurel** [comment]
Please add some code to make it compiable with clang.

**Comment by guy-maurel** [comment]
Issue_2:
why do you use parenthesis around ?

Issue_3:
The problem is: Spliting at comma gives:
```.cpp
private:
    virtual void sendNewMessageToDoSomething(const bool isRequest, 
                                             const bool isConsiderCondition = true) const;
```
The second part is also too long (more than code_width=80)
An alternative is to use:
`ls_func_split_full = true`

Issue_10:
Please use the option:
  `pos_bool = lead_force`

**Comment by smaxdax** [comment]
Sorry for my late response, but I got no notifications about your comments.
First thanks for your fast help. 
Your advice for the issues 1, 3 and 9 works well. 

About issue_2:
The parenthesis from my point are needed. Maybe you can send me an example, what was your idea.

About issue_10:
This will not fix our problem. We it only moves the Operators to the next line, as you can see here
    if (isSmallerThanMinimum
        || isBiggerThanMaximum
        || isAppChangeForbidden_) {
        access_ = true:
    }
But our intention is to indent the condition lines 4 spaces more then the following code. It is a bit similar to issue_5, where we want to indent the parameter lines more then the following code.

Finally I modified the example that it can be compiled:
[WantedResult_compileable.txt](https://github.com/uncrustify/uncrustify/files/3395518/WantedResult_compileable.txt)

**Comment by smaxdax** [comment]
In particular the issues 5 and 10 (increased indentation as following Code) would be important for the decision to use uncrustify in our current projects. With the other issues we could live with. 
Are there any ideas about issue 5 and 10 from some expert?

**Comment by guy-maurel** [comment]
Issue_5 is solved: Use the option (or not):
  ` indent_continue = 8`

Issue_10:
The proposal I have down give you a gut readability, but
uncrustify has yet not what you wanted to have.
It should be necessary to create a new option for that.
I'll do it to a later time.
OR, you join us, it will be quicklier

**Comment by smaxdax** [comment]
Thanks for the hint with indent_continue. 
I tried this, but it is not fully doing what we expect.
First this option solves following 2 items of our intended indenting style:
1) Indenting if statements and therefore it seems to solve also issue_10
2) Indenting of function definitions (at least if the first parameter is on the first line).
But it has also some side effects we do not want:
3) Indenting of function calls e.g.
wrapper->setSomething(somePointer, 
        someOtherParameter);
Here we have now an indent of 8 which we do not want here.
4) Indenting of variable definitions. Even here we have now an unwanted indenting of 8. 
5) No indenting of function definitions where the first parameter is already second first line.
void SomeClass::thisIsAQuiteLongMethod(
	someNamespace:anotherNamespace::someParameter,
	someNamespace:anotherNamespace::anotherParameter) {
	auto event = common::bsp::allocate<events::BluetoothConnectionRequestChanged>();
	...
Here we want the indenting of 8, like it is the case if the there is a parameter already in the first line (see item 2).

Are there any (additional) options to reach this indent style?

About the possibility of joining the project: 
We as BSH are part of the Bosch company. Has Bosch not already joined uncrustify project?
If not, I will try to contact responsible persons that care about open software.

**Comment by guy-maurel** [comment]
Bist in Giengen?
guy.j@maurel.de

**Comment by smaxdax** [comment]
Ja genau.

**Comment by guy-maurel** [comment]
And now?
Please push some more input data and expected output
