### ISSUE TITLE
Indentation of public: / private: not as wanted for class declaration/definition

### ISSUE THREAD

**Issue by MilesTEG1** [uncrustify/uncrustify#2343]
Hello,
I spent several hours tweaking the uncrustify configuration to get a desired result (which best corresponds to what CoolFormat gives me for Notepad ++ under windows).
But I stumble on classes that are not indented as I would like ... and some line breaks before colon.
I use uncrustify Uncrustify-0.69.0_f on macOS, with [SublimeText3 Uncrustify package.](https://packagecontrol.io/packages/Uncrustify)

Here my configuration file for uncrustify : [uncrustify-config.cfg](https://github.com/MilesTEG1/Ecran-7p-pour-Netatmo-Meteo/blob/master/uncrustify-config.cfg)

Here the cpp file I wanted to have : [uncrustify-Desired.cpp](https://github.com/MilesTEG1/Ecran-7p-pour-Netatmo-Meteo/blob/master/uncrustify-Desired.cpp)

Here the file I get : [uncrustify-Results.cpp](https://github.com/MilesTEG1/Ecran-7p-pour-Netatmo-Meteo/blob/master/uncrustify-Results.cpp)

A precision must be made, the code in thoses cpp files aren't working, it's only some copy/paste of what I want to format as I want, for testing purpose.

A screenshot of what I want and what I get : 
![Uncrustify-screenshot.png](https://raw.githubusercontent.com/MilesTEG1/Ecran-7p-pour-Netatmo-Meteo/master/Uncrustify-screenshot.png)

Can you help me ?
I certainly missed something somewhere...

Thanks you in advance,
Miles

**Comment by gmaurel** [comment]
Jette un coup d'oeil sur les options:
 ```.txt
 indent_label
  nl_after_label_colon
  indent_access_spec
  indent_access_spec_body
  nl_before_access_spec
  nl_after_access_spec
```
Il faudrait utiliser un/des example(s) plus court(s) pour chaque problèmes

**Comment by MilesTEG1** [comment]
Hello,
Merci, j'ai essayé et on se rapproche de ce que je souhaite :)
Cependant il reste quelques différences :
![Nouvelle capture](https://raw.githubusercontent.com/MilesTEG1/Ecran-7p-pour-Netatmo-Meteo/master/Uncrustify-screenshot-2.png)
Les modifications du fichier de configuration :
![Changes](https://raw.githubusercontent.com/MilesTEG1/Ecran-7p-pour-Netatmo-Meteo/master/uncrustify-config.cfg-Changes.png)

Est-ce possible de modifier ce comportement ? (au moins pour la 1ère flèche, car pour la seconde, c'est tolérable :)

PS : j'ai modifié les fichiers .cpp en ne laissant que la partie de la capture.
Merci encore

**Comment by guy-maurel** [comment]
La question n'est pas claire.
Il est préferable de transmettre le ficher d'origine (complet) et celui des résultats demandés.
Merci.

**Comment by guy-maurel** [comment]
Alors, les fichiers?

**Comment by MilesTEG1** [comment]
Bonjour,
Quels sont les fichiers que vous voulez voir ?
Dans mon 1er message j'ai mis en lien les deux fichiers exemples .cpp et le fichier de configuration.

**Comment by guy-maurel** [comment]
PR #2753 is a bugfix proposal.
Please test it and report.
Note the discrepences by your expected code:
l`ines 16 and 47`
the 3 missing lines, your configuration wanted to have
 ` nl_end_of_file_min              = 4`
It is preferable to not use TABs at all.
Here the modified configuration:
```.cfg
output_tab_size                 = 4
indent_columns                  = 4
indent_with_tabs                = 0
indent_cmt_with_tabs            = false
indent_class_on_colon           = true
indent_constr_colon             = true
indent_relative_single_line_comments = true
indent_access_spec_body         = true
nl_func_leave_one_liners        = true
nl_end_of_file                  = force
nl_end_of_file_min              = 4
nl_before_opening_brace_func_class_def = force
nl_class_colon                  = add
pos_class_colon                 = lead
align_var_class_span            = 3
align_var_struct_span           = 3
pp_if_indent_code               = true
```

**Comment by MilesTEG1** [comment]
Hello,
Thank you for your answer.
But I have an error 👍 `uncrustify-config.cfg:1317: unknown option 'nl_before_opening_brace_func_class_def'
Parsing: 645 bytes (637 chars) from stdin as language CPP`
I have 0.70.1 installed, and there is no new version for macOS.
`brew upgrade uncrustify
Warning: uncrustify 0.70.1 already installed
uncrustify --version
Uncrustify-0.70.1_f`
Is there any new version for macOS ? (I have Catalina installed)

**Comment by guy-maurel** [comment]
You need to use the PR at 
https://github.com/uncrustify/uncrustify/commit/e2b17b724e00c6180c6bd6cb5b592e969c47b6a9.diff
compile it and run.

**Comment by MilesTEG1** [comment]
I'll see if I manage to do that... I'm not a pro... so compiling is not my thing... I never dit it...

**Comment by guy-maurel** [comment]
It is not difficult!
Download/Clone the sources:
  `git clone https://github.com/uncrustify/uncrustify.git`
Change the directory and build it
```
cd uncrustify
mkdir build
cd build
cmake ..
make

```

**Comment by MilesTEG1** [comment]
Hello,
Ok, I managed to compile the source (after installing cmake).
I already had this values for those lines :
```
output_tab_size                 = 4
indent_columns                  = 4
indent_with_tabs                = 0
indent_class_on_colon           = true
indent_constr_colon             = true
indent_relative_single_line_comments = true
indent_access_spec_body         = true
nl_func_leave_one_liners        = true
nl_end_of_file                  = force
nl_end_of_file_min              = 4
nl_class_colon                  = add
pos_class_colon                 = lead
align_var_class_span            = 3
align_var_struct_span           = 3
pp_if_indent_code               = true
```
I tried your values for the two other parameters, but it don't do what I would like to have.
![CAPTURE](https://raw.githubusercontent.com/MilesTEG1/Ecran-7p-pour-Netatmo-Meteo/master/Uncrustify-screenshot-4.png)

But if I change those two option to this :
```
nl_before_opening_brace_func_class_def = false
indent_cmt_with_tabs            = true
```
I get closer to what I would like to have :
But there is two things not really good : 
- the green rectangle : should be on one line
- the red rectangle (not very important) : the line 15 is to much ident.
![Capture](https://raw.githubusercontent.com/MilesTEG1/Ecran-7p-pour-Netatmo-Meteo/master/Uncrustify-screenshot-3.png)

It's not very important. Do don"t worry :)
Thanks for your time 👍

**Comment by guy-maurel** [comment]
green rectangle:
Please the option:
`use nl_class_colon = remove`

**Comment by guy-maurel** [comment]
red rectangle:
Please the option:
  `indent_class_on_colon = false`
PLease test and report
