### ISSUE TITLE
Convert functions from old K&R style?

### ISSUE THREAD

**Issue by tarruda** [uncrustify/uncrustify#235]
Can we  tell uncrustify to format functions using the new ANSI style? This would be very useful when converting large codebases that use the old K&R style.

**Comment by gmaurel** [comment]
which transformations do you need?

**Comment by binkley** [comment]
Is this still under consideration as an enhancement?  I realize it goes well beyond mere beautification.  In defense, this is superbly helpful in reviving old codebases.

**Comment by guy-maurel** [comment]
Please try the configuration:
_<uncrustify_dir>_`/etc/kr-indent.cfg`

and report.
