### ISSUE TITLE
No option to add newline before multiline condition

### ISSUE THREAD

**Issue by rotu** [uncrustify/uncrustify#2360]
I would like to have uncrustify add a newline after '(' in an if/while/for condition if '(' and ')' are on different lines. Basically the same behavior as `nl_func_call_start_multi_line = true`, but for conditionals. I would expect such an option to be called something like `nl_cond_start_multi_line`, but I don't think one exists.

This is to meet the ROS2 style guide:

https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#open-versus-cuddled-braces

> * When a function call cannot fit on one line, wrap at the open parenthesis (not in between arguments) and start them on the next line with a 2-space indent. Continue with the 2-space indent on subsequent lines for more arguments. (Note that the Google style guide is internally contradictory on this point.)
> 
>     * Same goes for `if` (and `while`, etc.) conditions that are too long to fit on one line.
> 

Simple example:
```
if (this &&
    that ||
    both) {
    // ...
}
```
should uncrustify to:
```
if (
    this &&
    that ||
    both) {
    // ...
}
```

current version: Uncrustify-0.69.0_f

**Comment by guy-maurel** [comment]
yes

**Comment by rotu** [comment]
@guy-maurel what test are you referring to?

**Comment by guy-maurel** [comment]
It is my test to introduce a new line after the opening parenthesis.
But I think, it is not the best way.
Look at that we do:
```.cpp
      if (  chunk_is_token(start, CT_PAREN_CLOSE)
         || chunk_is_token(start, CT_PAREN_OPEN)
         || chunk_is_token(start, CT_FPAREN_CLOSE)
         || chunk_is_token(start, CT_COMMA)
         || chunk_is_token(start, CT_SEMICOLON)
         || chunk_is_token(start, CT_VSEMICOLON)
         || start->len() == 0)
      {
```
or another example, more complex:
```.cpp
   else if (  (start->flags & PCF_IN_FCN_DEF)
           || start->parent_type == CT_FUNC_PROTO            // Issue #1169
           || (  (start->level == (start->brace_level + 1))
              && (start->flags & PCF_IN_FCN_CALL)))
   {
```
The bool operator at the begining pull the people to look at it!
Please try and comment.

**Comment by rotu** [comment]
@guy-maurel That's a reasonable style for your code, but it's not what I'm trying to do.
