### ISSUE TITLE
Please tell me about the indent setting of array.

### ISSUE THREAD

**Issue by cyanocitta** [uncrustify/uncrustify#2364]
Hello.

Please tell me about the indent setting of array.

Since we don't want to indent the brace of the if statement, "indent_braces=false" is set.
However, with this setting, array blocks will not be indented.

Are there any settings to indent array blocks with "indent_braces = false" set?
If there is no setting, you can ignore it.

Thank you.

- input:
```
    const u8_t TEST3[] = 
        {AAAA, BBBB, CCCC, DDDD, EEEE, FFFF, GGGG, HHHH, IIII, JJJJ,
         KKKK, LLLL, MMMM, NNNN, OOOO, PPPP, QQQQ, RRRR, SSSS, TTTT,
         UUUU, VVVV, WWWW, XXXX, YYYY, ZZZZ, 1111, 2222, 3333, 4444,
         5555, 6666, 7777, 8888, 9999, 0000};
```

- output:
```
    const u8_t TEST3[] =
    {AAAA, BBBB, CCCC, DDDD, EEEE, FFFF, GGGG, HHHH, IIII, JJJJ,
     KKKK, LLLL, MMMM, NNNN, OOOO, PPPP, QQQQ, RRRR, SSSS, TTTT,
     UUUU, VVVV, WWWW, XXXX, YYYY, ZZZZ, 1111, 2222, 3333, 4444,
     5555, 6666, 7777, 8888, 9999, 0000};
```

- Expected output:
```
Same as "input" above.
```
working version: uncrustify : 0.68.1 (inspcode)

**Comment by gmaurel** [comment]
Not yet possible
Please fill up your profile.

**Comment by cyanocitta** [comment]
I understood that there is no setting.
I accept this and use it.
Thank you for answering.

I will continue to use this wonderful tool.

I wrote my profile.
