### ISSUE TITLE
Uncrustify: Check fails if content is piped to stdin

### ISSUE THREAD

**Issue by DerHeber** [uncrustify/uncrustify#2367]
Hi everybody,
I tried to pipe the content of C files to uncrustify. Unfortunately, uncrustify fails even if the file has no style violations.

Input:
```
cat Test.c | uncrustify -c config.cfg  -l C --check
```

Output:
``` 
Parsing: 16083 bytes (16083 chars) from stdin as language C
<< file content >>
FAIL: stdin (File size changed from 16083 to 16437)
```
Expected Output:
```
Parsing: Test.c as language C
PASS: Test.c (16437 bytes)
```
I see the change in the byte size, but I can not explain why this is happening.

What I am doing wrong or is there any problem with uncrustify?
Thank you

Uncrustify Version: Uncrustify-0.69.0

**Comment by guy-maurel** [comment]
--check is yet not really useable.
Try instead of:
`uncrustify -c config.cfg  -l C -f Test.c -o out.cpp`
and have a look to out.cpp

**Comment by DerHeber** [comment]
Thanks for your fast response!

Why is check not really usable at the moment?

I'm wondering, because
`uncrustify -f Test.c -c config.cfg -l C --check`
is working well as I can see. 

For that I get the correct output:
```
Parsing: Test.c as language C
PASS: Test.c (16437 bytes)
```

**Comment by guy-maurel** [comment]
We don't have enought tests for it.

**Comment by Josar** [comment]
There seems to be a change in uncrustify 0.69 that produces this error. 
Since 0.69 my Plugin for Eclipse which executes uncrustify stopped working with the same FAIL message.
