### ISSUE TITLE
align_same_func_call_params strange behavior

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2368]
Config:
```
# Uncrustify-0.69.0
align_same_func_call_params = true
```

Input:
```
void Func1()
{
	OtherFunc( a, b );
}

void Func2()
{
	Func3( p1, p2, p3 );
	Func3( p111, p222, p333 );
}
```

Output:
```
void Func1()
{
	OtherFunc( a, b );
}

void Func2()
{
	Func3( p1,   p2,   p3 );
	Func3( p111, p222, p333 );
}
```

So far, so good, this works perfectly, as expected.

But if I change "a" for any number, look what happens.

Input:
```
void Func1()
{
	OtherFunc( 33, b );
}

void Func2()
{
	Func3( p1, p2, p3 );
	Func3( p111, p222, p333 );
}
```

Output:
```
void Func1()
{
	OtherFunc( 33, b );
}

void Func2()
{
	Func3(   p1, p2,   p3 );
	Func3( p111, p222, p333 );
}
```
You can see that "p1" is now right-aligned!
And guess what:  if "b" is replaced by a number, "p2" will also become right-aligned.

**Comment by andrey-starodubtsev** [comment]
Tried to find the culprit and now I'm confused: there're 2 tests, [tests/expected/cpp/30250-align_fcall.cpp](https://github.com/uncrustify/uncrustify/blob/master/tests/expected/cpp/30250-align_fcall.cpp) and [tests/expected/cpp/31567-sf567.cpp](https://github.com/uncrustify/uncrustify/blob/master/tests/expected/cpp/31567-sf567.cpp). Both tests use `align_same_func_call_params = true`, but former one aligns fist param to the right if numbers are present among arguments:

```cpp
	brat(     "foo", 2000, 3000);
	brat("question",    2,  -42);
	brat(       "a",  -22,    1);
```

and latter doesn't:

```cpp
	readConfig(fileName, "asdfasdf", 1);
	readConfig(ame,      "aasdf",    1);
```

Also, default value for `align_number_right` option, which regulates this, is `false`, but func's args are aligned [here](https://github.com/uncrustify/uncrustify/blob/master/src/align_same_func_call_params.cpp#L167) if this option *is* `false`, which seems like a bug.

**Comment by guy-maurel** [comment]
PR #2368 is a bugfix proposal.
Please test it and report.

**Comment by chris-mich** [comment]
Seems ok in uncrustify-0.72 win64, thank you!!
