### ISSUE TITLE
align_assign_span weird behavior

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2371]
Configuration:
```
# Uncrustify-0.69.0
indent_class = true
align_assign_span = 1
```
Input:
```
class CMyClass
{
	CMyClass( int a = 0, int b = 0 );
};
```

Output (no changes were expected)
```
class CMyClass
{
	CMyClass( int a            = 0, int b= 0 );
};
```

Note the extra spaces added after "a", for no apparent reason.
Also, the space was removed after "b".
This was working just fine in version 0.68.

**Comment by andrey-starodubtsev** [comment]
was broken in 1671cc6
