### ISSUE TITLE
Incorrect curly brace pairing when they are #ifdef guarded ( extern "C" { )

### ISSUE THREAD

**Issue by eddyp** [uncrustify/uncrustify#2380]
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

The change (213d02048f278afaec490fddaf28944b3864736a) makes it obvious there is a bug in the uncrustify code in acolade pairing.

I have multiple files on which I get these warnings, even if the code is definitely correct.

A small sample file where this is visible on `Uncrustify-2fcd5d6` is this:

```
/**
 *   @file    template_c.c
 *
 *   @brief   Brief file description (one line).
 *   @details Detailed file description (can be multiple lines).
 *
 *   @addtogroup [MODULE_SECTION]
 *   @{
 */

#ifdef __cplusplus
extern "C" {
#endif



#ifdef __cplusplus
}
#endif

/** @} */

```

For some reason, it seems the bottom `#ifdef __cplusplus` block is not considered correct:

```
$ (cd build/ ; ./uncrustify -c ../etc/ben.cfg ../../template_c.c 2>&1 ; uncrustify -v)
Output suffix: .uncrustify
Parsing: ../../template_c.c as language C
parse_cleanup(422): pc->orig_line is 18, orig_col is 1, text() is '}', type is BRACE_CLOSE
parse_cleanup(424): (frm.top().type + 1) is UNKNOWN
Uncrustify-2fcd5d6
```

If I remove the accolade from the bottom `#ifdef` uncrustify no longer complains.
Same if I put the pair accolade inside the same `#ifdef` block.

**Comment by eddyp** [comment]
The issue occurs even with these simpler examples:

```
#ifdef FOO
extern "C" {
#endif

#ifdef FOO
}
#endif
```

or 

```
#ifdef FOO
void main() {
#endif

#ifdef FOO
}
#endif
```

**Comment by eddyp** [comment]
@guy-maurel ideas?

**Comment by gmaurel** [comment]
uncrustify is not a compiler and doesn't interpret the macros.

**Comment by eddyp** [comment]
> uncrustify is not a compiler and doesn't interpret the macros.

Since it doesn't interpret macros, in case of C/C++ does it considers the languages as a mix of preproc and actual C/C++?

If this is the case, is the `#ifdef/#endif` considered a stand alone statement which should have equal amounts of open and closed braces? Because that would explain why the simple legal examples above incorrectly generate warnings - and, implicitly, incorrectly parse and "interpret" C sources.

**Comment by gmaurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it again and report!

**Comment by eddyp** [comment]
I compiled uncrustify on Windows, i M getting the same results:

```
C:\usr\src\tools\style-checking-files\uncrustify\uncrustify-build\uncrustify\build>Release\uncrustify.exe -c ..\etc\ben.cfg ..\..\tc_doxy.c 2>&1
..\etc\ben.cfg:297: option 'sp_cpp_lambda_paren' is deprecated; use 'sp_cpp_lambda_square_paren' instead
..\etc\ben.cfg:652: option 'sp_word_brace' is deprecated; did you want to use 'sp_type_brace_init_lst' instead?
Output suffix: .uncrustify
Parsing: ..\..\tc_doxy.c as language C
parse_cleanup(446): pc->orig_line is 18, orig_col is 1, text() is '}', type is BRACE_CLOSE
parse_cleanup(448): (frm.top().type + 1) is UNKNOWN

C:\usr\src\tools\style-checking-files\uncrustify\uncrustify-build\uncrustify\build>Release\uncrustify.exe -c ..\etc\ben.cfg ..\..\tc_main.c 2>&1
..\etc\ben.cfg:297: option 'sp_cpp_lambda_paren' is deprecated; use 'sp_cpp_lambda_square_paren' instead
..\etc\ben.cfg:652: option 'sp_word_brace' is deprecated; did you want to use 'sp_type_brace_init_lst' instead?
Output suffix: .uncrustify
Parsing: ..\..\tc_main.c as language C
parse_cleanup(446): pc->orig_line is 6, orig_col is 1, text() is '}', type is BRACE_CLOSE
parse_cleanup(448): (frm.top().type + 1) is UNKNOWN

C:\usr\src\tools\style-checking-files\uncrustify\uncrustify-build\uncrustify\build>git d

C:\usr\src\tools\style-checking-files\uncrustify\uncrustify-build\uncrustify\build>Release\uncrustify.exe -v
Uncrustify-1c71835

C:\usr\src\tools\style-checking-files\uncrustify\uncrustify-build\uncrustify\build>more ..\..\tc_main.c
#ifdef FOO
void main() {
#endif

#ifdef FOO
}
#endif

C:\usr\src\tools\style-checking-files\uncrustify\uncrustify-build\uncrustify\build>more ..\..\tc_doxy.c
/**
 *   @file    template_c.c
 *
 *   @brief   Brief file description (one line).
 *   @details Detailed file description (can be multiple lines).
 *
 *   @addtogroup [MODULE_SECTION]
 *   @{
 */

#ifdef __cplusplus
extern "C" {
#endif



#ifdef __cplusplus
}
#endif

/** @} */

C:\usr\src\tools\style-checking-files\uncrustify\uncrustify-build\uncrustify\build>git show -s
commit 1c718355efc0ab6f2b2992d2008addaf31590751 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: gmaurel <guy.j@maurel.de>
Date:   Sat May 2 17:22:22 2020 +0200

    Merge pull request #2768 from guy-maurel/invariant_paren

    provide test data for sp_after_invariant_paren

C:\usr\src\tools\style-checking-files\uncrustify\uncrustify-build\uncrustify\build>git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

```

**Comment by guy-maurel** [comment]
You need to make some changes:
```.c
#ifdef __cplusplus
extern "C" {
}
#endif


#ifdef FOO
extern "C" {
}
#endif

#ifdef FOO
void main()
{
}


#endif
```

**Comment by eddyp** [comment]
> You need to make some changes

I don't understand what you're suggesting. The C++ parts are a standard way to allow C++ compilers to compile and link C++ with C code.

Do you want me to test this to confirm some hypothesis?

**Comment by gmaurel** [comment]
uncrustify cannot deal with the mix of "{" "}" and macros

**Comment by micheleCTDE** [comment]
Same problem here with uncrustify 0.71.0_f on debian testing. This is definitely something uncrustify is doing wrong. Other than that, it is a fantastic tool!

**Comment by micheleCTDE** [comment]
> uncrustify cannot deal with the mix of "{" "}" and macros

I disagree here. If I have a C macro with if/for/while in it, uncrustify complains if a { } set is missing (using my setup). Once I put { } in the macro code, the complain goes away.<br/>
That proves that uncrustify has at the minimum some understanding of macros.

**Comment by eddyp** [comment]
@micheleCTDE I think @gmaurel  was actually saying C is actually formed out of 2 languages[1], the preprocessor and the actual C language and there is no sane way to deal with both, unless you separate the steps from each other (i.e. preprocess to some degree), which opens its own can of worms.

I undestand this to some degree, yet as the `extern C` thing is a standard way of linking and compiling C with C++ code/compiler, I think it could be handled in some special way. The proposed closed accolade hack will not pass any code review or be an accepted solution in any non-trivial project, especially since its only raison-d-etre would be to make uncrustify happy, and it would confuse the hell out of any developer looking at the code.


[1] I'm not discussing the outright bone-headed decision in C11 to insert special semantics in the preprocessor language, effectively forcing the pre-processor implementation understand C language semantics. See _Generic() in C11 to understand what I'm talkign about.

**Comment by micheleCTDE** [comment]
Thanks @eddyp. Surely @gmaurel has a much deeper understanding of how uncrustify works, given he is one of the top devs. 
I was just highlighting that somehow uncrustify reports warning messages if some braces are missing in a macro, at least with my setup. So it seems reasonable there are some sort of internal checking.

Now, fixing the problem may be a totally different story and may require major changes, I don't know. But "extern C" clauses are quite common and it would be good to see the warning message disappear.

**Comment by jhaand** [comment]
Is a solution for this problem in the works? 
It is still very annoying.

**Comment by eddyp** [comment]
I just realized that I might have sent the wrong signals wrt what I would consider acceptable with my "simpler examples" in the first comment.

To clarify, I think that if uncrustify would deal correctly just with the `extern "C" {` guarded by __cplusplus and ignore any other creative ways of using the preprocessor, this would cover the most often and typical problem of the `extern(C)` declaration, and it would fit my needs nicely.

In other words, I think uncrustify could treat the exact constructs used for C-C++ linking support and ignore anything else so these would always work (both `#ifdef` and `#if defined(__cplusplus)` should work):


```C
#ifdef __cplusplus
extern "C" {
#endif

....
/* C code here */
....

#ifdef __cplusplus
}
#endif
```

while it will NOT handle these kinds of creative preprocessor and accolade mixing, and I'd be fine with it.

Examples of constructs that I'd be fine **NOT** supporting:

```C

#ifdef FOO
void main() {
#endif

..


#ifdef FOO
}
#endif
`

@gmaurel What do you think?

**Comment by gmaurel** [comment]
@thanks for the discussion.
Let us try with some more complete **new code examples**. Please, no link to an old data.
Please, push an example, a configuration file and what you expected to get.

**Comment by eddyp** [comment]
[sample.zip](https://github.com/uncrustify/uncrustify/files/6993471/sample.zip)

The output seems to be correct, so I haven't provided it.

The problem I have is this warning I get on the stderr:

```
Output suffix: .uncrustify
Parsing: sample.h as language C-Header
parse_cleanup(456): pc->orig_line is 55, orig_col is 1, text() is '}', type is BRACE_CLOSE
```

Version info:
```
uncrustify --version
Uncrustify-704034b
```

This was built on Windows 10 with MSVC compiler.

**Comment by yous** [comment]
FWIW, a temporary workaround for this:

``` c
/* *INDENT-OFF* */
#ifdef __cplusplus
extern "C" {
#endif
/* *INDENT-ON* */

...

/* *INDENT-OFF* */
#ifdef __cplusplus
}
#endif
/* *INDENT-ON* */
```

**Comment by turecekpetr** [comment]
@yous thanks for the solution. I use a more compact and better looking version:
```
#ifdef __cplusplus // *INDENT-OFF*
extern "C" {       // *INDENT-ON*
#endif
```
