### ISSUE TITLE
Align macro multi-line parameters on the same column

### ISSUE THREAD

**Issue by julian-poidevin** [uncrustify/uncrustify#2381]
Hello everyone, using Uncrustify `v0.69.0-1-72de5fdb` I can't achieve the following.

Here's my input code _(`PACKET_GENERATOR_ADD_CMD` is a macro)_:

```c
PACKET_GENERATOR_ADD_CMD
(
    aal,"","","",
    NULL,0,
    lm_set_gate_state,UART_EOS3_CMD_LM_GATE_STATE,UART_EOS3_USER,UART_EOS3_SHORT,
    lm_get_gate_state,UART_EOS3_CMD_LM_GATE_STATE,UART_EOS3_USER,UART_EOS3_SHORT, 0
)
```

Here's the desired output :

```
PACKET_GENERATOR_ADD_CMD
(
    aal,                        "",                                   "",                 "",
    NULL,                       0,
    lm_set_gate_state,          UART_EOS3_CMD_LM_GATE_STATE,          UART_EOS3_USER,     UART_EOS3_SHORT,
    lm_get_gate_state,          UART_EOS3_CMD_LM_GATE_STATE,          UART_EOS3_USER,     UART_EOS3_SHORT, 0
)
```

My current configuration file is : [uncrustify.cfg.txt](https://github.com/uncrustify/uncrustify/files/3559175/uncrustify.cfg.txt)

Can Uncrustify do that ?

Thanks !

**Comment by gmaurel** [comment]
je vais voir...

**Comment by julian-poidevin** [comment]
Thanks, I could achieve this by using "Align by RegEx" vscode extension (https://www.google.com/url?sa=t&source=web&rct=j&url=https://marketplace.visualstudio.com/items%3FitemName%3Djanjoerke.align-by-regex&ved=2ahUKEwj-q462lqvkAhUHfBoKHSALC6IQFjAAegQIARAB&usg=AOvVaw2efQSC_iNEa6A_n_Xaw1fF) but still interested by uncrustify solution !

**Comment by gmaurel** [comment]
Pretty, but old data.
How to you expect WHERE (on which block) the needed new option is working?
How to recognize?
Is it correct thet the number of "part"s is different over the lines?

**Comment by julian-poidevin** [comment]
Hello, thanks for getting back to me. I'd prefer not to bother you with this since I found a solution.
Thanks !

**Comment by guy-maurel** [comment]
May I get your solution?
It would be fine. Thanks.

**Comment by julian-poidevin** [comment]
[I commented on the 30 Aug 2019 ](https://github.com/uncrustify/uncrustify/issues/2381#issuecomment-526694639):

> Thanks, I could achieve this by using "Align by RegEx" vscode extension (https://www.google.com/url?sa=t&source=web&rct=j&url=https://marketplace.visualstudio.com/items%3FitemName%3Djanjoerke.align-by-regex&ved=2ahUKEwj-q462lqvkAhUHfBoKHSALC6IQFjAAegQIARAB&usg=AOvVaw2efQSC_iNEa6A_n_Xaw1fF) but still interested by uncrustify solution !
