### ISSUE TITLE
In Objective-C, it forces me to have a space between ^ and string in a block

### ISSUE THREAD

**Issue by sophie-nextdoor** [uncrustify/uncrustify#239]
I have sp_after_oc_block_caret      = remove

This is the line that it forces me to change:
-    BOOL (^compare)(NSString *lastNameIndexKey) = nil;
-    BOOL (^ compare)(NSString *lastNameIndexKey) = nil;

**Comment by shiki** [comment]
I'm also having this problem

**Comment by guy-maurel** [comment]
Please, push what you wanted to get.

**Comment by gmaurel** [comment]
No answer, we close.
