### ISSUE TITLE
Memory corruption in parse_cleanup

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#2429]
I'm trying to debug this CI failure: https://travis-ci.org/uncrustify/uncrustify/jobs/593684565.

On doing some digging, it appears that a bad entry has somehow gotten into the `ParseFrame`; the entry's `pc` is pointing to stack memory that is *not* a `chunk_t`. I have determined that this behavior is happening in master as well; just my luck that something in my branch has perturbed the code in a way that asan is now noticing the problem.

The issue can be seen by adding a logging statement to print the value of `tmp` just before the LOC that causes the ASAN error. There is a clear distinction between heap and stack addresses. With this logging, one can see that the error exists on master:
```
parse_cleanup(638): 1: possibly suspicious token? (nil) (<null>)
parse_cleanup(638): 2: possibly suspicious token? 0x612000000340 ({)
parse_cleanup(638): 3: possibly suspicious token? 0x612000000940 ({)
parse_cleanup(638): 2: possibly suspicious token? 0x612000002740 ({)
parse_cleanup(638): 3: possibly suspicious token? 0x612000002d40 ({)
parse_cleanup(638): 4: possibly suspicious token? 0x612000003340 ({)
parse_cleanup(638): 1: possibly suspicious token? (nil) (<null>)
parse_cleanup(638): 3: possibly suspicious token? 0x612000005a40 ({)
parse_cleanup(638): 4: possibly suspicious token? 0x612000006040 ({)
parse_cleanup(638): 1: possibly suspicious token? (nil) (<null>)
parse_cleanup(638): 2: possibly suspicious token? 0x612000008140 ({)
parse_cleanup(638): 4: possibly suspicious token? 0x612000008d40 ({)
parse_cleanup(638): 1: possibly suspicious token? (nil) (<null>)
parse_cleanup(638): 2: possibly suspicious token? 0x61200000ae40 ({)
parse_cleanup(638): 3: possibly suspicious token? 0x61200000b440 ({)
parse_cleanup(638): 2: possibly suspicious token? 0x7fffc25cb2f0 ()
```

One can also run uncrustify in gdb and wait for `tmp` to have one of these "bad" addresses, at which point one can see that whatever this memory contains, it isn't (currently) a reasonable `chunk_t`:
```
(gdb) p *tmp
$17 = {next = 0x7fffffffb770, prev = 0x668de1 <ParseFrame::top()+193>, align = {next = 0x45e0360e, right_align = 162, star_style = 6720800, 
    amp_style = 18342464, gap = 248, col_adj = 25024, ref = 0x14f, start = 0x7fffffffb710}, indent = {ref = 0x5f3b64 <chunk_is_comment(chunk_t*)+36>, 
    delta = 76864}, type = 76864, parent_type = 24864, orig_line = 0, orig_col = 140737488336576, orig_col_end = 13348758365440, orig_prev_sp = 76864, 
  flags = 140737488336752, column = 140737488336832, column_indent = 140737488337344, nl_count = 0, nl_column = 140737488336560, level = 2, 
  brace_level = 140737488337072, pp_level = 6199172, after_tab = 152, ...}
```

**Comment by mwoehlke-kitware** [comment]
Possibly this became an issue in 896c25688a24b14e30eaaa11f3635ef8105c66c3, but that may be a symptom rather than the cause. Still digging...

**Comment by mwoehlke-kitware** [comment]
...and here's the problem:
```c++
// brace_cleanup.cpp:145 (preproc_start)

   chunk_t tmp{};
   frm.push(tmp);
   frm.top().type = CT_PP_DEFINE;
```

Looks like 2feaebc50aad1ae7ee0594bc9a25f4f04d48a162 is the culprit.

I'm not sure what to do about this; we don't want to heap-allocate a new token, because I don't know how we'd ever free it. OTOH, we certainly can't use a stack-allocated token.

@CDanU, looks like this is your code? Any thoughts?

**Comment by CDanU** [comment]
I'll take a look and try to remember why I did those changes.
