### ISSUE TITLE
Space after typedef'ed function type name

### ISSUE THREAD

**Issue by esmil** [uncrustify/uncrustify#2437]
This is probably trivial, but I can't seem to find the option to stop uncrustify from turning this:
```C
typedef void timer_cb(struct timer_node *n);
```
into this:
```C
typedef void timer_cb (struct timer_node *n);
```

I'm using Uncrustify-0.69.0_f and here is the debug file:
http://ix.io/1Yfz

**Comment by guy-maurel** [comment]
PR #2438 is a bugfix proposal.
Please test it and report.
