### ISSUE TITLE
CT_PP_ENDIF without CT_PP_IF

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#2439]
The test cpp.test:30924 use an CT_PP_ENDIF without CT_PP_IF
```.cpp
#define LOG_FMT(sev, args...)                           \
   do { if (log_sev_on(sev)) { log_fmt(sev, ## args); } } while (0)
#endif
```
This introduce a under running of the variable **cpd.pp_level**
What is better?
ignore, error message or exit?

**Comment by mwoehlke-kitware** [comment]
What is that test supposed to be testing? It isn't obvious that not having a corresponding `#if` is needed for the test to be valid. If that is the case, my usual reaction to tests which use plainly ill-formed code is that testing ill-formed code is rarely useful, and to "correct" the test input file to not be ill-formed. (IOW, [GIGO principle](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out); if you feed uncrustify garbage, we make no promises what you'll get back.)

If you're asking "what should uncrustify do when run with this input", I could go just about any way. It's *possible* someone has a pathological case like:

```c++
// foo.h
#if blah

// foo.cpp
#include foo.h // unmatched #if
/* ... */
#endif // matches #if in foo.h
```

...but I also have severely limited sympathy for anyone doing that :wink:.
