### ISSUE TITLE
Unwanted macro indentation

### ISSUE THREAD

**Issue by r10r** [uncrustify/uncrustify#244]
Hi Ben,

I use uncrustify successfully in a C project - it really keeps the code nice and shiny ;)
I've a single problem where uncrustify doesn't work as desired and constantly reformats the code. I studied the config file but did not find a setting to change it.

running uncrustify (0.60) on 
```
#define FOO
#define BAR

FOO
BAR

#define BAZ
```

results in
```
#define FOO
#define BAR

FOO
        BAR

#define BAZ
```

But `BAR` should not be indented. When removing `#define BAZ` it works as expected.

Cheers,
Ruben

**Comment by gmaurel** [comment]
uncrustify doesn't know what a macro is.
The first word FOO is a type and BAR is a word.
After a type in a first line, the second line will be intended.
This is correct.
