### ISSUE TITLE
Indenting top level region raises a false positive error.

### ISSUE THREAD

**Issue by Benio101** [uncrustify/uncrustify#2440]
### Issue
`PP_REGION` or `PP_ENDREGION` at top level (parent: `NONE`) raises a false positive error at [`indent_text(3157)`](https://github.com/uncrustify/uncrustify/blob/uncrustify-0.69.0/src/indent.cpp#L3157) when `pp_region_indent_code` is set to `true`.

### Details
Version: `Uncrustify-0.69.0_f`

### Repro
Command:
```.txt
uncrustify -c config.cfg -f input.cpp -l CPP -p debug.log
```
Config (`config.cfg`):
```.cfg
pp_region_indent_code           = true    # true/false
```

Input (`input.cpp`):
```.cpp
#pragma region
#pragma endregion
```

Expected result (`stdout`):
```.cpp
Parsing: input.cpp as language CPP
#pragma region
#pragma endregion
```

Generated result (`stdout`):
```.cpp
Parsing: input.cpp as language CPP
indent_text(3155): size is 2
indent_text(3157): File: input.cpp, open_line is 1, parent is NONE: Unmatched PP_REGION_INDENT
indent_text(3155): size is 2
indent_text(3157): File: input.cpp, open_line is 1, parent is NONE: Unmatched PP_REGION_INDENT
#pragma region
#pragma endregion
```

Debug (`debug.log`):
```.txt
# Uncrustify-0.69.0_f
pp_region_indent_code           = true
# option(s) with 'not default' value: 1
#
# -=====-
# Line                Tag              Parent          Columns Br/Lvl/pp     Nl  Text
#   1>            PREPROC[          PP_REGION][  1/  1/  2/  0][0/0/0][0-0] #
#   1>          PP_REGION[               NONE][  2/  2/  8/  0][0/0/0][0-0]  pragma
#   1>       PREPROC_BODY[               NONE][  9/  9/ 15/  1][0/0/0][0-0]         region
#   1>            NEWLINE[               NONE][ 15/ 15/  1/  0][0/0/0][1-0]
#   2>            PREPROC[       PP_ENDREGION][  1/  1/  2/  0][0/0/0][0-0] #
#   2>       PP_ENDREGION[               NONE][  2/  2/  8/  0][0/0/0][0-0]  pragma
#   2>       PREPROC_BODY[               NONE][  9/  9/ 18/  1][0/0/0][0-0]         endregion
# -=====-
```

### Note
Supressing this error by altering `indent.cpp` seems to bypass this issue.
```.diff
3153a3154,3155
>       if (get_token_name(frm.at(idx_temp).parent) == "NONE" && get_token_name(frm.at(idx_temp).type) == "PP_REGION_INDENT") continue;
>       

```
However, it's most likely not a proper fix for this issue.
I bet issue is related to `PP_REGION_INDENT` log hack.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by Benio101** [comment]
### Result
Same (`git rev-parse HEAD` → `32a055c2d4a61d871a79638992563649d73a405e`).

### Debug log
```.txt
# Uncrustify-0.69.0-202-32a055c2
pp_region_indent_code           = true
# option(s) with 'not default' value: 1
#
# -=====-
# Line                Tag              Parent          Columns Br/Lvl/pp     Nl  Text
#   1>            PREPROC[          PP_REGION][  1/  1/  2/  0][0/0/0][0-0] #
#   1>          PP_REGION[               NONE][  2/  2/  8/  0][0/0/0][0-0]  pragma
#   1>       PREPROC_BODY[               NONE][  9/  9/ 15/  1][0/0/0][0-0]         region
#   1>            NEWLINE[               NONE][ 15/ 15/  1/  0][0/0/0][1-0]
#   2>            PREPROC[       PP_ENDREGION][  1/  1/  2/  0][0/0/0][0-0] #
#   2>       PP_ENDREGION[               NONE][  2/  2/  8/  0][0/0/0][0-0]  pragma
#   2>       PREPROC_BODY[               NONE][  9/  9/ 18/  1][0/0/0][0-0]         endregion
# -=====-

```

### stdout
```.txt
Parsing: input.cpp as language CPP
indent_text(3178): size is 2
indent_text(3180): File: input.cpp, open_line is 1, parent is NONE: Unmatched PP_REGION_INDENT
indent_text(3178): size is 2
indent_text(3180): File: input.cpp, open_line is 1, parent is NONE: Unmatched PP_REGION_INDENT
#pragma region
#pragma endregion
```

**Comment by Benio101** [comment]
See: Erroed travis build [#3300](https://travis-ci.org/uncrustify/uncrustify/builds/597363001).

**Comment by guy-maurel** [comment]
I am running Linux.
Having a look to the file tests/input/cpp/Issue_2440.cpp (you have provided)
and my file under Linux, we can see a little difference, at the end of the files.
The linux command diff shows it:
```.txt
diff Benio101.cpp ~/Software/uncrustify/tests/input/cpp/Issue_2440.cpp
2c2
< #pragma endregion
---
> #pragma endregion
\ No newline at end of file
Copying the linux file to ~/Software/uncrustify/tests/input/cpp/Issue_2440.cpp solve the problem.
```

**Comment by Benio101** [comment]
See https://github.com/uncrustify/uncrustify/pull/2446#pullrequestreview-301401917.

> In reply to [comment 541752266](https://github.com/uncrustify/uncrustify/issues/2440#issuecomment-541752266) at #2440;
> 
> None of these files has empty line at the end.
> They are essentially the same.
> 
> ![pragmas](https://user-images.githubusercontent.com/7223948/66765154-977ed200-eeab-11e9-9bd6-f9af8a94b99f.png)
> 
> ```
> Benio@PC MINGW64 /d/Documents/Visual Studio 2017/Projects/uncrustify/uncrustify (tests/issue-2440)
> $ diff tests/input/cpp/Issue_2440.cpp tests/expected/cpp/Issue_2440.cpp
> 
> Benio@PC MINGW64 /d/Documents/Visual Studio 2017/Projects/uncrustify/uncrustify (tests/issue-2440)
> $
> ```

**Comment by Benio101** [comment]
Tested on my debian 10.1.
Also, there is no difference between those files.
```
benio@benio:~/test$ git clone https://github.com/Benio101/uncrustify
Cloning into 'uncrustify'...
remote: Enumerating objects: 68, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 44980 (delta 37), reused 34 (delta 10), pack-reused 44912
Receiving objects: 100% (44980/44980), 15.86 MiB | 7.40 MiB/s, done.
Resolving deltas: 100% (34914/34914), done.
benio@benio:~/test$ cd uncrustify
benio@benio:~/test/uncrustify$ git checkout tests/issue-2440
Branch 'tests/issue-2440' set up to track remote branch 'tests/issue-2440' from 'origin'.
Switched to a new branch 'tests/issue-2440'
benio@benio:~/test/uncrustify$ diff tests/input/cpp/Issue_2440.cpp tests/expected/cpp/Issue_2440.cpp
benio@benio:~/test/uncrustify$ cat /etc/debian_version
10.1
benio@benio:~/test/uncrustify$
```

**Comment by gmaurel** [comment]
The problem is the missing <EOL> at the end of the file/end of the line.
This is shown in my comment on 10/14/2019
You get
```
indent_text(3178): size is 2
```
and the lines
```
   for (size_t idx_temp = 1; idx_temp < frm.size(); idx_temp++)
   {
      LOG_FMT(LWARN, "%s(%d): size is %zu\n",
              __func__, __LINE__, frm.size());
...
```
I get (under Linux) `size is 1`

**Comment by Benio101** [comment]
### Number of lines
Again, Travis on Linux also reports there are two lines there:
> ``` indent_text(3178): size is 2 ```

See: Line 977 of [Travis job #3300.1](https://travis-ci.org/uncrustify/uncrustify/jobs/597363002#L977)'s log for PR #2446.

I bet the correct result is 2 lines, isn't it? I don't remember statement that last line not followed by a blank line counts as continuation of previous line as if there was a raw `\` at the end of second to last line.

Whichever result is correct, running on different devices produces different results.
See results for [Travis job #3300](https://travis-ci.org/uncrustify/uncrustify/builds/597363001): 3300.6 passes, but all the rest not.

### Issue
Going back to the issue: Adding a blank line to the end of file does not change a lot, if anything: test still fails on some devices, while on others not.

See: Results of [Travis job #3312](https://travis-ci.org/uncrustify/uncrustify/builds/598329986?utm_source=github_status&utm_medium=notification) for b3148674ab75e7d75276f0dee341a80f36f0947e at #2446.

Independing on the existence of a blank line on the EOF; On some devices: running `uncrustify` to indent a top level region, throws a false positive error text to the stdout, making some autoformating tools not to work properly or at all.

**Comment by guy-maurel** [comment]
Do we have a problem?
You are right, with your source file, we get differences.
But, is it really the source for some executable(s)?

**Comment by Benio101** [comment]
Extensions like [CodeBeautifier](https://github.com/marianob85/CodeBeautifier) for Visual Studio, fails to work at all when `pp_region_indent_code` is set to `true` and there is a top level region; due to a superflous errors thrown. If you think impact is very low, I think you're ok to state that this won't be fixed. Personally, I am ok to just supress this error line and rebuild the executable. Just though it's important enough to report it.

**Comment by gmaurel** [comment]
No. We should try to anderstand what is happening.
I work with you, but have (today) no idea how to go on.

**Comment by guy-maurel** [comment]
Do we still have a problem?
If not, may I close?
