### ISSUE TITLE
functions as parameters and line splitting bug?

### ISSUE THREAD

**Issue by oddballbutler** [uncrustify/uncrustify#245]
Here is a simple example illustrating my point.

Configuration file
```
code_width = 80
ls_code_width = True
```
crustified code
```
foo(parameter, parameter, parameter, parameter, parameter, parameter, function(parameter));
```
expected uncrustified code
```
foo(parameter, parameter, parameter, parameter, parameter, parameter,
    function(parameter));
```

actual uncrustified code
```
foo(parameter, parameter, parameter, parameter, parameter, parameter, function(
            parameter));
```
---
If the code_width column is before the open parenthesis of the function and after the comma before the function name, I get the expected behavior.

crustified code
```
foo(parameter, parameter, parameter, parameter, parameter, parameter, parameter, function(parameter));
```
actual uncrustified code
```
foo(parameter, parameter, parameter, parameter, parameter, parameter, parameter
    function(parameter));
```
---
I guess the feature that I would like is that the function parameters are always split at the closest comma that comes before code_width. Although, maybe I'm missing something since I'm still an uncrustify noob.

**Comment by gmaurel** [comment]
Well, it is correct.
At the first example the last parameter is align because of 2 functions calls.
The second example has only one function call before splitting.
