### ISSUE TITLE
Avoid splitting function calls across lines

### ISSUE THREAD

**Issue by dnygren** [uncrustify/uncrustify#2458]
Hi -

I'm having trouble preventing uncrustify from splitting function calls across lines if they fit on one line. I don't know if this is a bug, feature request, or I just don't know the proper config file setting.

[Here is a link to the requested debug files.](https://github.com/dnygren/uncrustify_debug)

I'm running the latest uncrustify:
```
$ uncrustify -v
Uncrustify_d-0.69.0-218-accf177a
```
Here is the original source code, with the `strerror_r()` function call formatted on one line as I think it should be:
```
$ cat message.cpp
.
.
.
    ourstream << application << ": " << message_type << " " <<
        function_context << " " << duplicate_errno << " .\n" <<
        strerror_r(duplicate_errno, buf, sizeof (buf)) << endl;
}
```
Here I run the above file through uncrustify and the `strerror_r()` function call is split across lines:
```
$ uncrustify -c mms.cfg -f message.cpp -La -s -p debug.txt 2>stderr.txt
.
.
.
    ourstream << application << ": " << message_type << " " <<
        function_context << " " << duplicate_errno << " .\n" << strerror_r(
        duplicate_errno, buf, sizeof (buf)) << endl;
}
```
Here are the config options I think are relevant:
```
# Try to limit code width to N columns.
code_width                          = 80        # unsigned number

# Whether to split lines as close to code_width as possible and ignore some groupings.
ls_code_width                      = false     # true/false

# Add or remove newline between '()' in a function call.
nl_func_call_empty              = remove   # ignore/add/remove/force

# Whether to add a newline after '(' in a function call,
# has preference over nl_func_call_start_multi_line.
nl_func_call_start              = ignore   # ignore/add/remove/force

# Whether to add a newline after '(' in a function call if '(' and ')' are in
# different lines.
nl_func_call_start_multi_line   = false    # true/false
```
I've played with the above settings, but nothing seems to make a difference.

Here is some debug output at the point of the line break. Once again, the complete set of file are available  [at the link to my debug files.](https://github.com/dnygren/uncrustify_debug)
```
# -=====-
# Line                Tag              Parent          Columns Br/Lvl/pp     Flag   Nl  Text
.
.
.
#   6>               WORD[               NONE][  9/  9/ 25/  0][1/1/0][     40000][0-0]         function_context
#   6>              ARITH[               NONE][ 26/ 26/ 28/  1][1/1/0][ 100000000][0-0]                          <<
#   6>             STRING[         PP_INCLUDE][ 29/ 29/ 32/  1][1/1/0][     40000][0-0]                             " "
#   6>              ARITH[               NONE][ 33/ 33/ 35/  1][1/1/0][ 100000000][0-0]                                 <<
#   6>               WORD[               NONE][ 36/ 36/ 51/  1][1/1/0][     40000][0-0]                                    duplicate_errno
#   6>              ARITH[               NONE][ 52/ 52/ 54/  1][1/1/0][ 100000000][0-0]                                                    <<
#   6>             STRING[         PP_INCLUDE][ 55/ 55/ 61/  1][1/1/0][     40000][0-0]                                                       " .\n"
#   6>              ARITH[               NONE][ 62/ 62/ 64/  1][1/1/0][ 100000000][0-0]                                                              <<
#   7>          FUNC_CALL[               NONE][ 65/  9/ 19/  0][1/1/0][     40000][0-0]                                                                 strerror_r
#   7>        FPAREN_OPEN[          FUNC_CALL][ 75/ 19/ 20/  0][1/1/0][ 100000000][0-0]                                                                           (
#   7>            NEWLINE[               NONE][ 19/ 20/  0/  0][1/1/0][         0][1-0]
#   7>               WORD[               NONE][  9/ 20/ 35/  0][1/2/0][     40010][0-0]         duplicate_errno
```

Is there a config file option that prevents functions from being split if they fit on one line?

 
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by mwoehlke-kitware** [comment]
Your problem is:
```
pos_arith = join
```

This tells uncrustify to eliminate line breaks to either side of operators, which turns your code `ourstream << ... << endl;` into a single line. Then, uncrustify applies `code_width`, adding line breaks as needed.

You probably want:
```
pos_arith = lead
```

BTW, I'd say the repository was overkill, but it sure made it easy to clone your test case to play with locally :slightly_smiling_face:.

**Comment by dnygren** [comment]
Thanks for the tip Matthew! I'll give it a try.

Any additional tips on how I could have debugged this on my own? I did spend the better part of a day rooting around the .cfg file. Even if I had considered `<<` an arithmetic operator, I wouldn't have known that was why uncrustify was breaking  things the way it did

```
# The position of arithmetic operators in wrapped expressions.
pos_arith = ignore   # ignore/break/force/lead/trail/join/lead_break/lead_force/trail_break/trail_force

```

**Comment by mwoehlke-kitware** [comment]
> Any additional tips on how I could have debugged this on my own?

The same way I did (and usually do); comment out about half the config file and see if you get the same results. If you do, try the other half. If you don't, the problem is (likely¹) one of the half of the options you commented out, so comment out half of that half, and repeat until you find the responsible option. (IOW, basic binary search.)

(¹ Occasionally you run into an issue that is only caused by a *combination* of options. These can be a little harder to track down.)

> Even if I had considered `<<` an arithmetic operator

We could possibly stand to split that up... although it *is* the bit-shift operator, which has been abusively repurposed :wink:. (It's also a `CT_ARITH` internally, which I believe encompasses pretty much all binary operators except comparison and Boolean, i.e. the likes of `<` and `&&`. Adding another category would probably be a significant change.)

**Comment by dnygren** [comment]
Yes, I now see you are right about it technically being an arithmetic operator. Perhaps adding a comment to the .cfg file to the effect that it encompasses more than just arithmetic operators would be helpful?
```
# The position of binary arithmetic, bitwise, and I/O operators in line wrapped expressions.
```

Thanks so much for the `uncrustify` debugging advice too. I owe you a beer. Let me know next time you're in San Diego.
