### ISSUE TITLE
GNU::format and GCC?

### ISSUE THREAD

**Issue by zvezdochiot** [uncrustify/uncrustify#2470]
https://github.com/uncrustify/uncrustify/blob/36029af0971702eaacc7500e8d07cbe89a6c02e9/src/option.h#L161-L163

GCC < 4.8 == Error.

**Comment by mwoehlke-kitware** [comment]
Uh... *less than* 4.8? That's not only pretty ancient, that's lacking functional C++11 support. I'd be surprised if this is the only issue with that beyond-ancient compiler, and even if it is, we're liable to introduce other breakage at any time.

(I'm a little surprised actually that the build system doesn't enforce a C++11 dependency... It apparently only does for building the emscripten stuff. I should probably fix that.)

**Comment by mwoehlke-kitware** [comment]
BTW, what distro are you using? I wasn't aware of anything still under support that doesn't provide *at least* 4.8.

**Comment by zvezdochiot** [comment]
@mwoehlke-kitware say:
>I'd be surprised if this is the only issue
Oddly enough, this is the only problem.
@mwoehlke-kitware say:
>what distro are you using?
Debian Wheezy.

**Comment by zvezdochiot** [comment]
Maybe:
```c
#if (defined(__GNUC__) && defined(__GNUC_MINOR__) && (__GNUC__ >= 4) && (__GNUC_MINOR__ >= 8))
    [[gnu::format(printf, 2, 3)]] 
#endif 
```
?
It works for me!

**Comment by mwoehlke-kitware** [comment]
> Debian Wheezy.

That [hasn't been supported for almost a year and a half](https://www.debian.org/releases/wheezy/). I recommend upgrading.

AFAIK (@guy-maurel may want to weigh in here), we are generally assuming a functional C++11 compiler at this point, which GCC 4.7 [isn't](https://gcc.gnu.org/gcc-4.7/cxx0x_status.html). (Strictly speaking, GCC 4.8 [doesn't qualify either](https://stackoverflow.com/questions/12530406), but a) [its quirks](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=50025) are reasonably easy to work around, and b) that is still the compiler on e.g. Red Hat. I'm not aware of any *supported* distros that don't have at least GCC 4.8.)

Feel free to patch it locally. Personally, I am not very interested in adding complexity to support a compiler that is effectively past EOL on all known distros, given that we are unlikely to test such compiler and may well introduce other changes that break with said compiler at any time.

**Comment by zvezdochiot** [comment]
@mwoehlke-kitware say:
>Feel free to patch it locally. Personally, I am not very interested in adding complexity

You know better...

**Comment by mwoehlke-kitware** [comment]
Okay. (And seriously, I would strongly encourage upgrading to a distro that is still receiving maintenance and security updates.)
