### ISSUE TITLE
Incorrect alignment of attributes when type uses leading ::

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#2478]
For some reason, alignment of variables and attributes is incorrect when type uses leading ::

[debug.txt](https://github.com/uncrustify/uncrustify/files/3773579/debug.txt)

Test Case
```
typedef int X35GlobalT1;
typedef int X35T2;

void fooX35a()
{
   ::X35GlobalT1 a1;
   X35T2 a2;

   ::X35GlobalT1 a3 = 1;
   X35T2 a4 = 1;
}

void fooX35b()
{
   X35GlobalT1 a1;
   X35T2 a2;

   X35GlobalT1 a3 = 1;
   X35T2 a4 = 1;
}

class X35_1a
{
   private:
      ::X35GlobalT1 a1;
      X35T2 a2;

      ::X35GlobalT1 a3 = 1;
      X35T2 a4 = 1;
};

class X35_1b
{
   private:
      X35GlobalT1 a1;
      X35T2 a2;

      X35GlobalT1 a3= 1;
      X35T2 a4 = 1;
};
```
Generated output
```
typedef int X35GlobalT1;
typedef int X35T2;

void fooX35a()
{
	::X35GlobalT1 a1;
	X35T2 a2;

	::X35GlobalT1 a3 = 1;
	X35T2 a4 = 1;
}

void fooX35b()
{
	X35GlobalT1 a1;
	X35T2       a2;

	X35GlobalT1 a3 = 1;
	X35T2       a4 = 1;
}

class X35_1a
{
private:
::X35GlobalT1 a1;
X35T2 a2;

::X35GlobalT1 a3 = 1;
X35T2         a4 = 1;
};

class X35_1b
{
private:
X35GlobalT1 a1;
X35T2       a2;

X35GlobalT1 a3 = 1;
X35T2       a4 = 1;
};
```
Observations
1. In function fooX35a nothing is aligned, but in fooX35b everything is aligned as expected. The diiference is only that fooX35a has some types that use leading ::
2. When comparing class X35_1a and X35_1b, we see that leading :: also changes the formatting. The strange thing though is that in X35_1a formatting of a3 and a4 is OK although :: is used.

**Comment by guy-maurel** [comment]
PR #2607 is a bugfix proposal.
Please test it and report.

**Comment by arneforlie** [comment]
Thanks, this looks good.

However, I do not understand the PR's headline, IMHO it doesn't describe the issue.

**Comment by gmaurel** [comment]
Change the description.
