### ISSUE TITLE
indent_align_string and streams

### ISSUE THREAD

**Issue by trollixx** [uncrustify/uncrustify#248]
`indent_align_string = true`:

```c++
qCWarning(QT_BT_ANDROID)
            << "Native registration unable to get method ID:" \
            "getDefaultAdapter of android/bluetooth/BluetoothAdapter";
```

Expected:

```c++
qCWarning(QT_BT_ANDROID)
            << "Native registration unable to get method ID:" \
               "getDefaultAdapter of android/bluetooth/BluetoothAdapter";
```

**Comment by gmaurel** [comment]
Let us change the source.
`qCWarning(QT_BT_ANDROID) <<
    "Native registration unable to get method ID:"
            "getDefaultAdapter of android/bluetooth/BluetoothAdapter";`
The backslash in the source is NOT necessary.
The config file
`indent_columns=12
indent_with_tabs=0
#indent_align_string = true                   NOT necessary
`
and you get
`qCWarning(QT_BT_ANDROID) <<
            "Native registration unable to get method ID:"
            "getDefaultAdapter of android/bluetooth/BluetoothAdapter";`
`qCWarning(QT_BT_ANDROID) <<
            "Native registration unable to get method ID:"
            "getDefaultAdapter of android/bluetooth/BluetoothAdapter";`
