### ISSUE TITLE
When will 1.0.0 be released?

### ISSUE THREAD

**Issue by stevenleeS0ht** [uncrustify/uncrustify#2517]
I would like to use uncrustify for my works. But it is now still in version 0.x.x.

Could someone tell me when will version 1.0.0 be released? Or is there anyone who can add a milestone for version 1.0.0?

@guy-maurel, @bengardner, @CDanU.

**Comment by guy-maurel** [comment]
You can use uncrustify just now!
We don't plan the release 1.0.0
Release 0.70.0 will be released this month.
Number(s) are not important.
Important is that the program is running pretty well.

**Comment by mwoehlke-kitware** [comment]
Possibly "when there are no known bugs" :wink:.
Seriously, don't get hung up on the version number; it's been usable for some time.
