### ISSUE TITLE
scripts/release_tool.py

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#2521]
The script doesn't run as I wish.
I still see some problems:
The files:
```.txt
documentation/htdocs/config.txt
documentation/htdocs/default.cfg
etc/defaults.cfg
etc/uigui_uncrustify.ini
```
get the text:
```.txt
version=Uncrustify_d-0.69.0-324-53006af4
```
The file `etc/uncrustify.xml.in` is not changed

**Comment by mwoehlke-kitware** [comment]
> The file `etc/uncrustify.xml.in` is not changed

See #2515. Updating this via `release_tool.py` is not the correct solution.

Not sure what's going on for the first bit; I'll take a look ASAP.

**Comment by mwoehlke-kitware** [comment]
Oh. Right... sigh. Because the output is generated straight from running `uncrustify`, which, since the tool is now using a branch rather than a temporary tag, doesn't yet output the correct version.

I have an idea for a fix; let me see what I can do...
