### ISSUE TITLE
Not happy with Apex Prettier. Can Uncrustify do this?

### ISSUE THREAD

**Issue by rsoesemann** [uncrustify/uncrustify#2526]
I just learned about Uncrustify and would like to use it to format Apex code. If you can help I would love your answer here on StackExchange https://salesforce.stackexchange.com/questions/284806/adjust-apex-default-formatting-rules-in-prettier

What Prettier gives me
<img width="598" alt="sfappway____dev_projects_sfappway__-_TaskListCtrledd" src="https://user-images.githubusercontent.com/8180281/68769694-0d01cd80-0625-11ea-96c4-40d61505507d.png">

What I want
<img width="823" alt="sfappway____dev_projects_sfappway__-_TaskListCtrl" src="https://user-images.githubusercontent.com/8180281/68769699-0ffcbe00-0625-11ea-9552-c634a04a2f37.png">

**Comment by gmaurel** [comment]
uncrustify has 700 options. Try it.

**Comment by rsoesemann** [comment]
Very helpful comment.  Just ignore my issue instead of doing an RTFM.

**Comment by mwoehlke-kitware** [comment]
*Did* you RTFM. (Having done a non-trivial amount of work on it, I will insist that the 'F' here stands for "Fine" :slightly_smiling_face:.)

Also, what sort of code is this? "Apex" doesn't tell us anything. It looks somewhat akin to C++, but clearly is not. Is it one of the languages Uncrustify supports? If so, chances are you can get Uncrustify to format it how you want it, though it will take some fiddling with options. (I am guessing maybe it is C#? I have never used C#, so...)

As the documentation says, "There are currently 702 options and minimal documentation. Try UniversalIndentGUI and good luck." (The documentation of individual options isn't too bad, but there isn't much in the way of a general users' guide.)

Also, asking us to join some obscure SE... don't hold your breath. (But you can answer your own question and refer back to this issue.)

**Comment by davescruggs** [comment]
I know this is closed, but some people treat Salesforce Apex as Java for formatting purposes. Someone else blogged about it at https://medium.com/@taxnexus/salesforce-apex-beautified-in-vs-code-with-uncrustify-7d0cbfc5ea1a.
