### ISSUE TITLE
Increase minimum CMake version

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#2541]
CMake is currently grumpy that it doesn't understand how `uncrustify_version.h` is generated. There is a fairly simple fix (list it as a [`BYPRODUCT`](https://cmake.org/cmake/help/v3.2/command/add_custom_target.html)), but this requires either CMake ≥ 3.2 or some awkward work-arounds.

Right now, we notionally support CMake 2.8.0, although I very much doubt this is being tested by anyone.

I'd like to propose bumping the minimum CMake version to 3.2, which has been out for quite some time, and should be available in most distros that are still under, or even recently out of, maintenance. (In particular, RHEL6 appears to have 3.6, and Xenial appears to have 3.5.)

**Comment by guy-maurel** [comment]
I use Linux Mint, 19.2 Cinnamon
```.log
$ cmake --version
cmake version 3.10.2
```
