### ISSUE TITLE
INDENT_MEMBER not working correctly for ternary operator

### ISSUE THREAD

**Issue by samishchandra** [uncrustify/uncrustify#2545]
### Input:
```
return
  (options.meta == nil
    ? metaComponent
    : ComponentBuilder()
      .direction(Row)
      .spacing(4));
```

### ✅Expected Output:
```
return
  (options.meta == nil
    ? metaComponent
    : ComponentBuilder()
      .direction(Row)
      .spacing(4));
```

### ❌Actual Output:
```
return
  (options.meta == nil
    ? metaComponent
    : ComponentBuilder()
   .direction(Row)
   .spacing(4));
```

### Config options used:
```
indent_columns = 2
indent_member = 0
indent_member_single = false
```

## # Uncrustify version
Uncrustify-0.70.0

**Comment by gmaurel** [comment]
What is id?
A closing parenthese is missing.
Please, provide a compileable source-

**Comment by mwoehlke-kitware** [comment]
@samishchandra, please check your input and output. Aside from your code being invalid, I get:
```
return
  (options.meta == nil
    ? metaComponent
    : ComponentBuilder()
   .direction(Row)
   .spacing(4);
```

(Note that the last two lines are outdented one space compared to your output.)

That said, if I add a `)` before the `;`, it doesn't change the indent, and, well, the "expected" output is indeed what I would also expect. It appears that the last two lines are being indented relative to the first `(`, and not relative to `ComponentBuilder()` as expected.

**Comment by samishchandra** [comment]
@mwoehlke thanks for checking the issue. Yes, your interpretation is correct.

**Comment by samishchandra** [comment]
I tried to debug the issue in "indent.cpp" but couldn't make it work for all cases. Can you point me to some code or provide some guidance on the fix so that I can work on it?

**Comment by guy-maurel** [comment]
use:
_uncrustify -c abc.cfg -f abc.cpp -L A 2>A.txt_
have a look to A.txt to find where anything is not OK

**Comment by samishchandra** [comment]
Fix at [PR 2662](https://github.com/uncrustify/uncrustify/pull/2662).

**Comment by guy-maurel** [comment]
Could you close?
