### ISSUE TITLE
[Feature Request]: Add detailed documentation for configuation.

### ISSUE THREAD

**Issue by stevenleeS0ht** [uncrustify/uncrustify#2554]
It would be awesome to provided a documentation for each available option in configuration.

Even if there is some description in `uncrustify --show-config` But it is not so detailed and doesn't provide adequate example.

Documentation is a essential part of every software.

**Comment by gmaurel** [comment]
Have a look to documentation/htdocs/
It is a begin

**Comment by mwoehlke-kitware** [comment]
Uh... `--show-config` *does* give documentation of each option. If that is not adequate, please give a more specific example of what you would like to see, and/or please suggest specific options for which you feel the documentation is inadequate.
