### ISSUE TITLE
Strange directory structure in 0.70.1 release

### ISSUE THREAD

**Issue by mcatanzaro** [uncrustify/uncrustify#2558]
The uncrustify-0.70.1.tar.gz available from https://prdownloads.sourceforge.net/uncrustify/uncrustify-0.70.1.tar.gz contains a toplevel directory named uncrustify-uncrustify-0.70.1. This seems odd. Previous releases did not have this extra directory.

It's not a big deal since it's easy to workaround by adding one cd into downstream build processes. But it means recipes that build 0.69.0 and prior releases will not be able to build 0.70.1.

**Comment by mwoehlke-kitware** [comment]
Uh... really? I'm not seeing it. The file I got from that link is identical to https://github.com/uncrustify/uncrustify/archive/uncrustify-0.70.1.tar.gz, both of which appear to have the top level directory `<organization>-<project>-<version>`, i.e. `uncrustify-uncrustify-0.70.1`, but no `.tar.gz`. These are generated by GitHub, and AFAIK have always been like this.

To test, I downloaded https://github.com/uncrustify/uncrustify/archive/uncrustify-0.68.tar.gz, and sure enough, it has the expected `uncrustify-uncrustify-0.68` prefix.

(Maybe Guy already fixed something?)

**Comment by mcatanzaro** [comment]
> The file I got from that link is identical to https://github.com/uncrustify/uncrustify/archive/uncrustify-0.70.1.tar.gz, both of which appear to have the top level directory `<organization>-<project>-<version>`

That's exactly what I see. But this directory was definitely not present in previous releases, e.g. https://prdownloads.sourceforge.net/uncrustify/uncrustify-0.69.0.tar.gz does not have this extra directory. I suspect you did not use GitHub-generated tarballs for previous releases?

Again, it's not a big deal, but it is a bit uglier. E.g. see https://src.fedoraproject.org/rpms/uncrustify/c/fc0c75a50fa82bdbc819b382502ede0a3437475d for an example of required build changes. Most (or almost all?) packages put their configure.ac/CMakeLists.txt/meson.build in the toplevel so we don't have to cd in like this. (Actually, I'm pretty sure this is the first time I've encountered this situation.)

**Comment by mcatanzaro** [comment]
> i.e. `uncrustify-uncrustify-0.70.1`, but no `.tar.gz`.

Oops, yes, there is no .tar.gz. I've edited that typo out of my first comment. I see the same as you.

**Comment by mwoehlke-kitware** [comment]
> But this directory was definitely not present in previous releases, e.g. https://prdownloads.sourceforge.net/uncrustify/uncrustify-0.69.0.tar.gz does not have this extra directory. I suspect you did not use GitHub-generated tarballs for previous releases?

That may be (Guy would know; he's probably asleep right now and won't see this for some hours). That said, I actually prefer having the directory, although it would be better if they had only the project name (i.e. `uncrustify-<version>`, not `uncrustify-uncrustify-<version>`). It is pretty typical for tarballs of open source software to have the package name and version as a prefix for all of their content. Also, these days I would probably recommend the GitHub archives as the preferred way of obtaining the sources for a release.

**Comment by guy-maurel** [comment]
It is now without a directory.
Let us discuss for the next release

**Comment by mcatanzaro** [comment]
This is fixed in 0.71.0.
