### ISSUE TITLE
0.70.1 nl_func_type_name does not work

### ISSUE THREAD

**Issue by qunying** [uncrustify/uncrustify#2561]
It was working up to 0.70.0, but 0.70.1 failed to format the simple hello world into
```
int
main(int argc, char *argv[])
```

Simple hello world program to test:
```
#include <stdio.h>

int main (int argc, char *argv[])
{
    printf("hello world!\n");

    return 0;
}
```

[uncrustify-cfg.txt](https://github.com/uncrustify/uncrustify/files/3899224/uncrustify-cfg.txt)

**Comment by guy-maurel** [comment]
Thanks for the message.
PR #2564 is a bugfix proposal.
Please test it and report.

**Comment by qunying** [comment]
PR #2564 seems working.
