### ISSUE TITLE
misinterpreted boolean operator within a template default argument

### ISSUE THREAD

**Issue by byron-hawkins** [uncrustify/uncrustify#2565]
The XML parsing library [TinyXML2](http://github.com/leethomason/tinyxml2) defines the following template:

    template
    <bool = (sizeof(unsigned long) >= sizeof(size_t))>
    struct LongFitsIntoSizeTMinusOne { ... }

Uncrustify wants to split apart the boolean operator `>=` because it assumes that here, `>` is a delimiter:

    template
    <bool = (sizeof(unsigned long) > = sizeof(size_t))>
    struct LongFitsIntoSizeTMinusOne { ... }

I realize this is a highly unusual case, but the code is very crusty and benefits tremendously from uncrustification--except that we get this compile error.

**Comment by guy-maurel** [comment]
One of our example is:
```.cpp
#include <type_traits>
template <
	typename ... Args,
	typename E = typename std::enable_if<(sizeof...(Args) >= 1), bool>::type
	>
void fun1(Args&& ... args)
{
}
```
Is it the same?

**Comment by byron-hawkins** [comment]
I'm getting some strange indentation with this example, but no compile error:

      1 #include <type_traits>
      2
      3 template<
      4 typename ... Args,
      5          typename E = typename std::enable_if<(sizeof...(Args) >= 1), bool>::type
      6     >
      7 void fun1(Args&& ... args)
      8 {
      9 }

**Comment by byron-hawkins** [comment]
Now this is very strange... if I add the template struct to my example, it also formats without a compile error like this:

     0 #include <cstddef>
     1 #include <type_traits>
     2
     3 template<
     4 typename ... Args,
     5          typename E = typename std::enable_if<(sizeof...(Args) >= 1), bool>::type
     6     >
     7 void fun1(Args&& ... args)
     8 {
     9 }
    10
    11 template<bool = (sizeof(unsigned long) >= sizeof(size_t))>
    12 struct LongFitsIntoSizeTMinusOne
    13 {
    14     int foo;
    15 };
    16
    17     int
    18 main()
    19 {
    20     return 0;
    21 }

However, when using uncrustify within vim (as the `equalprg` and `formatprg`), if I simply open tinyxml2.cpp and then switch back to my example buffer (above), uncrustify splits the boolean operator for both of the templates. This is very difficult to understand, because vim is simply passing the contents of the buffer as stdin to a bash script, which sets up arguments and calls uncrustify. The arguments are:

    uncrustify -q -l cpp /path/to/format.cfg

Something stateful is changing here, but the `formatprg` toolchain appears to be static (i.e., stateless)--so how can anything in the example be affected by the presence of tinyxml.cpp in my vim buffer list? Let me know if anyone is familiar with this, otherwise I'll have to investigate when I have more time.

**Comment by guy-maurel** [comment]
PR #2577 is a bugfix proposal.
Please test it and report.
