### ISSUE TITLE
Improper brace handling inside preprocessor macro

### ISSUE THREAD

**Issue by millert** [uncrustify/uncrustify#2569]
Given the following macro:

```
#define CHECK_SETENV(a, b, c) do { \
    if (setenv((a), (b), (c)) == -1) \
        goto bad; \
} while (0)
```

uncrustify produces the following error:

```
parse_cleanup(444): pc->orig_line is 4, orig_col is 1, text() is '}', type is BRACE_CLOSE
parse_cleanup(446): (frm.top().type + 1) is ELSE
parse_cleanup(452): File: /tmp/foo, orig_line is 4, orig_col is 1, Error: Unexpected '}' for 'IF', which was on line 2
```

However, if a set of braces is added around the `goto bad;`, there is no error.  Setting `pp_ignore_define_body = true` also avoids the error.

I verified the bug is still present in Uncrustify_d-0.70.1-15-f9689538.

**Comment by guy-maurel** [comment]
You need to help uncrustify a little. Change your preprocessor statement to:
```
#define CHECK_SETENV(a, b, c)            \
    do                                   \
    {                                    \
        if (setenv((a), (b), (c)) == -1) \
        {                                \
            goto bad;                    \
        }                                \
    } while (0)
```

**Comment by millert** [comment]
I am aware that adding braces works around the problem--I mentioned that in the original command.  I was hoping for a fix that does not require modifying the code to be reformatted.  If you do not feel like the underlying bug is worth fixing you may as well close this issue.
