### ISSUE TITLE
Insert new line before '.' in method calls C/C++

### ISSUE THREAD

**Issue by vgandari** [uncrustify/uncrustify#2574]
I would like to see (using [uncrustify.txt](https://github.com/uncrustify/uncrustify/files/3964512/uncrustify.txt) as a `cfg` file)

```cpp
#include <pybind11/pybind11.h>
namespace py = pybind11;
PYBIND11_MODULE(example, m)
{
	py::class_<Pet>(m, "Pet").def(py::init<const std::string&>()).def(
		"setName",
		&Pet::setName).def("getName", &Pet::getName);
}
```

formatted as

```cpp
#include <pybind11/pybind11.h>

namespace py = pybind11;

PYBIND11_MODULE(example, m)
{
  py::class_<Pet>(m, "Pet")
    .def(py::init<const std::string &>())
    .def("setName", &Pet::setName)
    .def("getName", &Pet::getName);
}
```

(taken from [pybind11 docs](https://pybind11.readthedocs.io/en/master/classes.html))

Note the newline inserted before the '.' at each method call.

Is there a way to do this already? I only see `sp_member` and `indent_member` for controlling spacing, but nothing for inserting a newline. The `nl_before_member` option seems to be intended for Java only, but doesn't work on C++ files.

Thanks.

**Comment by guy-maurel** [comment]
PR #2574 is a bugfix proposal.
Please test it and report.

**Comment by vgandari** [comment]
Perfect

```cpp
#include <pybind11/pybind11.h>
namespace py = pybind11;
PYBIND11_MODULE(example, m)
{
	py::class_<Pet>(m, "Pet")
		.def(py::init<const std::string&>())
		.def("setName", &Pet::setName)
		.def("getName", &Pet::getName);
}
```

**Comment by vgandari** [comment]
This also inserts a newline before '->' in trailing return types.

**Comment by gmaurel** [comment]
Please push an example

**Comment by vgandari** [comment]
```cpp
auto three()->int
{
	return 3;
}
```

becomes

```cpp
auto three()
->int
{
	return 3;
}
```

when `nl_before_member` is set to `force`/`add`. I don't think there's a way to insert a newline before '->' just for trailing return types, only `sp_trailing_return`.

Also, with

```
nl_before_member                = remove
sp_trailing_return              = force
```
I get

```cpp
auto three()->int
{
	return 3;
}
```

instead of

```cpp
auto three() -> int
{
	return 3;
}
```

Essentially, `sp_trailing_return` has no effect. I haven't found anyone bring up this issue elsewhere.

**Comment by guy-maurel** [comment]
Please have a new test.

**Comment by vgandari** [comment]
`nl_before_member` no longer adds a newline before trailing return type.

`nl_before_member` removes newlines when set to `ignore` and adds a space after `.` when set to `force`/`add`.

`sp_trailing_return` still has no effect when set to `add` or `force`.

Tested on
```cpp
#include <pybind11/pybind11.h>
#include <string>

namespace py = pybind11;
PYBIND11_MODULE(example, m)
{
	py::class_<Pet>(m, "Pet")
		.def(py::init<const std::string&>())
		.def("setName", &Pet::setName)
		.def("getName", &Pet::getName);
}

auto three()->int
{
	return 3;
}
```

Same behavior on latest commit on `master` branch (`eaf53ecc3dac1f6ca5882f17f881641fb81df994`).

**Comment by guy-maurel** [comment]
Sorry for delay.
May we begin again on your data from 5 January?
Please send (again?) your config and what you expect to get.
Thanks
