### ISSUE TITLE
C++: Wrong indentation for assignment continuation with chained function call

### ISSUE THREAD

**Issue by sparist** [uncrustify/uncrustify#2582]
When an assignment continuation contains a chained function call, closing parentheses are indented incorrectly.

Input (and expected output):
```
int pass = doSomething(
  argument
);

int fail = doSomething(
  argument
).doNotIndentMe();
```

Output:
```
int pass = doSomething(
  argument
);

int fail = doSomething(
  argument
  ).doNotIndentMe();
```

Debug: [debug.txt](https://pastebin.com/sAAVNgZq)

A very hacky and unacceptable patch that works around the problem: [hack.diff](https://pastebin.com/iCTik2ww)

**Comment by guy-maurel** [comment]
PR #2590 is a bugfix proposal.
Please test it and report.

**Comment by sparist** [comment]
Thanks! This fixes the described issue.

There is one remaining, related issue that is "fixed" by my hack (linked in the issue) but not by this fix: lambdas.

What I expect:
```
  const auto lambda = [this](int arg) {
    doSomething();
  };
```

What I see instead:
```
  const auto lambda = [this](int arg) {
      doSomething();
    };
```

I will create a separate issue for that one.

**Comment by sparist** [comment]
Added: #2591
