### ISSUE TITLE
C++: std::function incorrectly removes space between return type and parameters

### ISSUE THREAD

**Issue by sparist** [uncrustify/uncrustify#2585]
The space between the return type and parameters of a function type in a `std::function<return (params)>` declaration is incorrectly removed in some cases. Note that the `size_t` is incorrectly assessed as `FUNC_CALL`, whereas `void` is correctly assessed as `TYPE`.

Input (and expected output):
```
// Retains the space after "void".
typedef std::function<void (int arg)> Pass;

// Removes the space after "void".
typedef std::function<size_t (int arg)> Fail;
```

Output:
```
// Retains the space after "void".
typedef std::function<void (int arg)> Pass;

// Removes the space after "void".
typedef std::function<size_t(int arg)> Fail;
```

Debug: [debug.txt](https://pastebin.com/5i6UwNKv)

**Comment by sparist** [comment]
This specific case can be worked around by adding `type = size_t` to the config.

**Comment by guy-maurel** [comment]
PR #2699 is a bugfix proposal.
Please test it and report.
