### ISSUE TITLE
Pawn: crash filter caused, when initializing an array

### ISSUE THREAD

**Issue by ADRFranklin** [uncrustify/uncrustify#2586]
Using the latest version of uncrustify: Compiled it myself
Debug file: https://pastebin.com/78AveEza

The issue is related to this code 
```
static stock const data[][] =
{
	{0b00000011001111000010011100000000, 0b00000011001111000010011100000000},
	{0b00000011001111000010011100000000, 0b00000011001111000010011100000000}
};
```

it appears that the equal sign used to denote initializing the array with values, is the cause of a crash filter. 

The crash filter gives the error:
```
crash_filter: exception 0xC0000005 at [2141:0] (ip=00007FF676F04C3A) [CallStack: pawn_process_variable:261, pawn_process_line:202, pawn_prescan:170]
```

**Comment by ADRFranklin** [comment]
I just found another issue, that also causes a crash_filter error. 
debug: https://pastebin.com/xwLtNQgn

in Pawn it is legal to do this
```
new 
	Text:testText[MAX_PLAYERS] = {Text:INVALID_TEXT_DRAW, ...},
	Text:testText1[MAX_ROWS][MAX_PLAYERS],
	bool:testText2[MAX_PLAYERS],
	testText3[MAX_PLAYERS];
```

However because the data doesn't start on the same line as the quantifier, it does in fact throw a crash filter error.

**Comment by gmaurel** [comment]
Hello !
It is fine to get somebody with pawn experience in our team.
Please create separate issue for each problem.
Stay with us. Thanks. Guy.

**Comment by guy-maurel** [comment]
PR #2587 is a bugfix proposal.
Please test it and report.

**Comment by ADRFranklin** [comment]
Unfortunately the issue is still present. 
I did try messing around with the new config option you added, but it didn't make any difference.

**Comment by ADRFranklin** [comment]
Just to clarify. It does work when it is represented as such 
```
static stock const data[][] = {
	{0b00000011001111000010011100000000, 0b00000011001111000010011100000000},
	{0b00000011001111000010011100000000, 0b00000011001111000010011100000000}
};
```

However if the `{` brace is on a newline, the parser throws a crash filter error

**Comment by gmaurel** [comment]
NO!
Please do uncrustify ... -p p.txt 
and push the p.txt

**Comment by ADRFranklin** [comment]
Debug: https://pastebin.com/ZEexHNy6

**Comment by gmaurel** [comment]
There is NO crash.

**Comment by ADRFranklin** [comment]
According to VS-Code there is:
```
Debug: config file: g:\pawn-uncrustify-test\uncrustify.cfg
Debug: launched: C:\Users\Michael\scoop\apps\uncrustify\0.70.0\uncrustify.exe -l PAWN -c g:\pawn-uncrustify-test\uncrustify.cfg --replace --no-backup g:\pawn-uncrustify-test\main.pwn
Debug: uncrustify exited with error: Parsing: g:\pawn-uncrustify-test\main.pwn as language PAWN
crash_filter: exception 0xC0000005 at [2143:0] (ip=00007FF7B77F4C3A) [CallStack: pawn_process_variable:261, pawn_process_line:202, pawn_prescan:170]
```

**Comment by tr1xy** [comment]
I got crash too

**Comment by tr1xy** [comment]
I got the same error 👍 
`crash_filter: exception 0xC0000005 at [2143:0] (ip=00007FF602064C3A) [CallStack: pawn_process_variable:261, pawn_process_line:202, pawn_prescan:170]`

**Comment by guy-maurel** [comment]
Sorry for the trouble: I work with linux. wait a little bit!

**Comment by guy-maurel** [comment]
Please try the patch, run with:
uncrustify ... -L A
and push the output
[2586-B.diff.txt](https://github.com/uncrustify/uncrustify/files/4041765/2586-B.diff.txt)

**Comment by ADRFranklin** [comment]
Hi, Sorry for the delayed response, I finally got time to try it out, however I noticed a lot of changes where pushed to master, so decided to try the master version with the latest changes to see if the issue persisted and it turns out this issue is now fixed.

There doesn't seem to be any more crash_filters with the code previously shown to have errors. Thanks.
