### ISSUE TITLE
Pawn: crash_filter error caused by data on a newline

### ISSUE THREAD

**Issue by ADRFranklin** [uncrustify/uncrustify#2588]
I just found an issue, that also causes another crash_filter error. 
debug: https://pastebin.com/xwLtNQgn

in Pawn it is legal to do this
```
new 
	Text:testText[MAX_PLAYERS] = {Text:INVALID_TEXT_DRAW, ...},
	Text:testText1[MAX_ROWS][MAX_PLAYERS],
	bool:testText2[MAX_PLAYERS],
	testText3[MAX_PLAYERS];
```

However because the data doesn't start on the same line as the quantifier, it does in fact throw a crash filter error.

**Comment by gmaurel** [comment]
How should I help if you push an example (above) different from the debug link?

**Comment by ADRFranklin** [comment]
Debug: https://pastebin.com/SLMfKzbU

**Comment by ADRFranklin** [comment]
The crash_filter for this, is no more after compiling from the latest master pushes. Seems to be fine now, but will keep testing. Will keep this open for now.
