### ISSUE TITLE
C++: Impossible to remove indent for lambda assignment continuation

### ISSUE THREAD

**Issue by sparist** [uncrustify/uncrustify#2591]
When an assignment continuation contains a lambda, it appears impossible to remove the extra level of indentation.

Input (and desired output):
```
const auto lambda = [this](int arg) {
  doSomething();
};
```

Output:
```
const auto lambda = [this](int arg) {
    doSomething();
  };
```

Debug: [debug.txt](https://pastebin.com/vTYQzKgN)

A very hacky and unacceptable patch that works around the problem: [hack.diff](https://pastebin.com/iCTik2ww)

**Comment by sparist** [comment]
Adding `indent_cpp_lambda_only_once = true` has no effect.

**Comment by JodiTheTigger** [comment]
If you have a lambda inside a namespace block it could be #1813

**Comment by guy-maurel** [comment]
PR #2649 is a bugfix proposal.
Please test it and report.

**Comment by gmaurel** [comment]
You need to use the option:
 ` indent_off_after_assign = true`

**Comment by sparist** [comment]
It looks like it works! Thanks 👍
