### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by davidrohr** [uncrustify/uncrustify#2594]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Using the latest git version (Uncrustify-0.70.1-59-eaf53ecc-dirty) of uncrustify, I get a segmentation fault running it with the attached config file on the attached test case:
```
cat test.cxx | uncrustify -q -c config.cfg -l CPP
```
[testcase.tar.gz](https://github.com/uncrustify/uncrustify/files/4019995/testcase.tar.gz)

**Comment by guy-maurel** [comment]
PR #2594 is a bugfix proposal.
Please test it and report.

**Comment by davidrohr** [comment]
works, thx!
