### ISSUE TITLE
"sp_cond_question = ignore" broken

### ISSUE THREAD

**Issue by dmdeemer** [uncrustify/uncrustify#2596]
versions affected:
Uncrustify_d-0.70.1-59-eaf53ecc (built today from github master branch)
Uncrustify-0.66.1_f (from Ubuntu 18.10 LTS)

config:
~~~
sp_cond_colon                   = ignore
sp_cond_question                = ignore
~~~

source:
~~~
void function(void) {
    int a = 0;
    int b = (a==1)?1:2;
}
~~~

expected output:
~~~
void function(void) {
        int a = 0;
        int b = (a==1)?1:2;
}
~~~

actual output (spaces added around ? and :):
~~~
void function(void) {
        int a = 0;
        int b = (a==1) ? 1 : 2;
}
~~~

**Comment by guy-maurel** [comment]
Thanks for the message.
PR #2600 is a bugfix proposal.
Please test it and report.

**Comment by dmdeemer** [comment]
@guy-maurel 
I fetched and compiled PR #2600, and the bugfix works, both in my test sample above and in my project code (which I cannot share).

Thank you!
