### ISSUE TITLE
Add or remove newline after each ',' in a function call.

### ISSUE THREAD

**Issue by opsidjflksdf** [uncrustify/uncrustify#2604]
I'm making use of the config options:
```
# Add or remove newline after each ',' in a function declaration.
nl_func_decl_args               = remove   # ignore/add/remove/force

# Add or remove newline after each ',' in a function definition.
nl_func_def_args                = remove   # ignore/add/remove/force`
```
, setting them to Remove so that a list of parameters that spans many lines gets compacted to as few lines as possible, as permitted by code_width.

I'm looking for something similar for the parameters of a function call (as opposed to function definition/declaration). I can't seem to find anything. 

For example, this call
```
func( parameter1, parameter2, 
	parameter3, parameter4, 
	parameter5, parameter6, 
	parameter7, parameter8, 
	parameter9 );

```

would be transformed into

```
func( parameter1, parameter2, parameter3, parameter4, parameter5, parameter6, 
	parameter7, parameter8, parameter9 );

```

, assuming a code_width setting of 80 characters.

Any idea for that?
Thank you!

(The language that I'm using uncrustify for is C#, but this applies to C/C++ as well).

**Comment by guy-maurel** [comment]
PR #2614 is a bugfix proposal.
Please test it and report.

**Comment by opsidjflksdf** [comment]
@guy-maurel 
I tested with the current master (after the fix has been merged) and it looks good. Thank you very much!
