### ISSUE TITLE
Using std::decay_t as a template parameter causes Error: Unexpected '}' for 'ANGLE_OPEN'

### ISSUE THREAD

**Issue by JWhitleyAStuff** [uncrustify/uncrustify#2613]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

I'm using the configuration file provided by `ament_uncrustify`, which can be found here: https://github.com/ament/ament_lint/blob/master/ament_uncrustify/ament_uncrustify/configuration/ament_code_style.cfg

When using `uncrustify` on a C++ file which uses `static_cast` with the resultant type of a call to `std::decay_t` as the template parameter, `uncrustify` produces the following result:

```
parse_cleanup(427): test.cpp, orig_line is 8, Error: Unexpected '}' for 'ANGLE_OPEN', which was on line 6
Unmatched BRACE_CLOSE
at orig_line=8, orig_col=1
Try the option 'tok_split_gte = true'
```

The following is a simple example which shows the unintended behavior:

```
#include <type_traits>

int main(int argc, char ** argv)
{
  int value = static_cast<std::decay_t<const int>>(2.0);
  return 0;
}
```

While the following has the expected behavior (passes):

```
include <type_traits>

int main(int argc, char ** argv)
{
  using DecayedIntType = std::decay_t<const int>;
  int value = static_cast<DecayedIntType>(2.0);
  return 0;
}
```

Current version: Uncrustify-0.68_f

**Comment by guy-maurel** [comment]
As proposed at the run of uncrustify:
Try the option 'tok_split_gte = true'

**Comment by JWhitleyAStuff** [comment]
Thanks, @guy-maurel . The option fixes the issue as expected. I will bring it up to the maintainers of `ament_uncrustify` as to whether they want to change this option in their config.
