### ISSUE TITLE
C++: No newline if destructor uses noexcept keyword

### ISSUE THREAD

**Issue by marco-stephan** [uncrustify/uncrustify#2626]
Newlines are removed on class destructors that use the `noexcept` keyword.

### Input:
```C++
class Class1
{
	~Class1()
	{
		// ...
	}
};

class Class2
{
	~Class2() noexcept(false)
	{
		// ...
	}
};
```

### Output:
```C++
class Class1
{
	~Class1()
	{
		// ...
	}
};

class Class2
{
	~Class2() noexcept(false){
		// ...
	}
};
```

### Expected output: 
Same as input

### Uncrustify: 
Version: Uncrustify-0.70.1_f
Debug: [debug.txt](https://gist.github.com/marco-stephan/88808279e393ec4e8fc344fbf2475b95)
Relevant config:
> nl_fdef_brace = force
> nl_fdef_brace_cond= force

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
Using:
```.cfg
nl_fdef_brace       = force
nl_fdef_brace_cond  = force
indent_class        = true
```
with the current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by marco-stephan** [comment]
It does indeed look like it is fixed in the most recent master. Closing as resolved.
