### ISSUE TITLE
C++: Incorrect newline between template and inline function

### ISSUE THREAD

**Issue by MrTheMake** [uncrustify/uncrustify#2639]
An incorrect newline is added between a template and an inline function.

### Input:
```C++
template<typename T>
inline void Test()
{
}
```

### Output:
```C++
template<typename T>

inline void Test()
{
}
```

### Expected output: 
Same as input

### Uncrustify: 
Version: Uncrustify-0.70.1_f
Debug: [debug.txt](https://gist.github.com/MrTheMake/ac1f79931e7bce1b2dacb3b30866c7d7)
Relevant config:
> nl_var_def_blk_start = 2

**Comment by samishchandra** [comment]
Does the following options help ?
> nl_template_func_def
> nl_template_func_def_special
> nl_template_end

**Comment by MrTheMake** [comment]
Using any of the three options you provided did not change the output to the desired format. 
Note that this is most likely a bug because the newline is added by setting `nl_var_def_blk_start` to 2 even though it is described as:

> The number of newlines **before a block of variable definitions** not at the top of a function body. If nl_after_access_spec is non-zero, that option takes precedence.

Clearly the function is not a variable definition but it is treated as such.

**Comment by guy-maurel** [comment]
PR #2667 is a bugfix proposal.
Please test it and report.

**Comment by MrTheMake** [comment]
#2667 Fixes the issue. Thanks!

**Comment by MrTheMake** [comment]
Fixed via https://github.com/uncrustify/uncrustify/pull/2667.
