### ISSUE TITLE
Cygwin: compat_win32.cpp:10:28: fatal error: windows_compat.h: No such file or directory

### ISSUE THREAD

**Issue by XVilka** [uncrustify/uncrustify#264]
Compiling uncrustify from cygwin-64bit: 

  ...
  CXX    uncrustify-unc_text.o
  CXX    uncrustify-compat_posix.o
  CXX    uncrustify-compat_win32.o
compat_win32.cpp:10:28: fatal error: windows_compat.h: No such file or directory
compilation terminated.
Makefile:554: recipe for target 'uncrustify-compat_win32.o' failed
make[2]: *** [uncrustify-compat_win32.o] Error 1
make[2]: Leaving directory '/cygdrive/d/Work/uncrustify/src'
Makefile:242: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/cygdrive/d/Work/uncrustify/src'
Makefile:340: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by gmaurel** [comment]
The actual git version works.
