### ISSUE TITLE
C++: Incorrect spacing after dereference operator

### ISSUE THREAD

**Issue by MrTheMake** [uncrustify/uncrustify#2640]
An additional spacing is added after the dereference operator. 

### Input:
```C++
class Class
{
	void test1(int* x)
	{
		*x = 1;
	}
};

void test2(int* x)
{
	*x = 1;
}
```

### Output:
```C++
class Class
{
void test1(int* x)
{
	* x = 1;
}
};

void test2(int* x)
{
	*x = 1;
}
```

### Expected output: 
```C++
class Class
{
void test1(int* x)
{
	*x = 1;
}
};

void test2(int* x)
{
	*x = 1;
}
```

### Uncrustify: 
Version: Uncrustify-0.70.1_f
Debug: [debug.txt](https://gist.github.com/MrTheMake/6fcee0ebaa5736d209ca478411be4b32)
Relevant config:
> sp_after_ptr_star = force

**Comment by samishchandra** [comment]
This config should fix it.
> # Add or remove space before pointer star '*'.
> sp_before_ptr_star              = force    # ignore/add/remove/force

**Comment by MrTheMake** [comment]
Adding `sp_before_ptr_star = force` results in:
```C++
class Class
{
void test1(int * x)
{
	* x = 1;
}
};

void test2(int * x)
{
	*x = 1;
}
```
Which is not what I want to achieve. It also adds a space before every pointer type. Basically, I want to have the following formatting:
```C++
int* x;
*x = 1;
```

**Comment by samishchandra** [comment]
My bad, this config should fix it.

```
# Add or remove space after pointer star '*', if followed by a word.
#
# Overrides sp_type_func.
sp_after_ptr_star = remove # ignore/add/remove/force
```

**Comment by MrTheMake** [comment]
Changing `sp_after_ptr_star` to `remove` also does not result in the formatting I am looking for:
```C++
int*x;
*x = 1;
```

Note that now the space in the first line is removed. 
In the original post, I have basically the same function once as a member function of a class and once as a global function. This simple difference should not result in different code formats, but it is. Therefore, I would conclude that this behavior is a bug.

**Comment by samishchandra** [comment]
I am not sure what config you have. But basically with just the following config, I was able to get the output you are looking for.

```
sp_before_ptr_star              = force
sp_before_unnamed_ptr_star      = ignore
sp_between_ptr_star             = remove
sp_after_ptr_star               = remove
sp_after_ptr_star_qualifier     = ignore
sp_after_ptr_star_func          = remove
sp_ptr_star_paren               = remove
sp_before_ptr_star_func         = force
```

**Comment by MrTheMake** [comment]
I am always testing it with just the specified configuration and nothing else. 

Formatting the code with your provided configuration also does not result in the format I am looking for:
```C++
class Class
{
void test1(int *x)
{
	*x = 1;
}
};

void test2(int *x)
{
	*x = 1;
}

int test()
{
	int *x;
	*x = 1;
}
```

It should look like:
```C++
class Class
{
void test1(int* x)
{
	*x = 1;
}
};

void test2(int* x)
{
	*x = 1;
}

int test()
{
	int* x;
	*x = 1;
}
```
