### ISSUE TITLE
regression between 0.69 and 0.70, parsing 'namespace' in a C file results in error code -11

### ISSUE THREAD

**Issue by dirk-thomas** [uncrustify/uncrustify#2641]
The problem should be unrelated to the configuration options used.

A C (not C++) header `test.h` containing the name `namespace`:

```
int func(int namespace);
```

fails to parse in version 0.70 while it was working in 0.69.

And uncrustify is parsing the file "as language C-Header".

**Comment by gmaurel** [comment]
namespace is a reserved keyword and cannot be used here.
https://en.cppreference.com/w/cpp/keyword

**Comment by dirk-thomas** [comment]
`namespace` is a reserved keyword in C++ - not C. And the very same code was working in an earlier version of `uncrustify`. So that does look like a regression to me.

**Comment by dirk-thomas** [comment]
@gmaurel Can you please comment if that implies any restriction / rule which applies to C++ code will also be enforce / required by C code? Imo that make the tools less useful for C code than it was before this regression.

**Comment by guy-maurel** [comment]
uncrustify cannot see if a H-file is used as C or C++, you need to help:
`uncrustify -c dirk-thomas.cfg -f dirk-thomas.h -l C`
and you get what you wanted to get.
```.log
Uncrustify_d-0.70.1-200-04882d06
Parsing: dirk-thomas.h as language C
int func(int namespace);
```

**Comment by dirk-thomas** [comment]
> uncrustify cannot see if a H-file is used as C or C++

When invoking it `uncrustify` without an explicit language prints:

`Parsing: dirk-thomas.h as language C-Header`

Maybe I don't understand why passing `-l C` is necessary here is that is already what `uncrustify` has determined automatically?

Also this doesn't comment on the fact that the very same code was working just fine in an earlier release. Wouldn't you call that a regression?

**Comment by dirk-thomas** [comment]
@guy-maurel It would be appreciated if you could answer my above questions.

**Comment by guy-maurel** [comment]
language C-Header is given for both C- and C++ helper file.
uncrustify cannot distinguish which one.
passing -l C as an help for uncrustify
No. Correcting part of the code which is not OK is not a regression.

**Comment by dirk-thomas** [comment]
> language C-Header is given for both C- and C++ helper file.

Quite confusing but thanks for clarifying.

> passing -l C as an help for uncrustify

We have change our logic to explicitly pass the language where we know for sure.
