### ISSUE TITLE
Problem with spanish characters

### ISSUE THREAD

**Issue by Calu85** [uncrustify/uncrustify#2655]
I have a problem when files use non ASCII characters.
I write comments in spanish, using accents and ñ. This characters are deleted in the output file after using uncrustify.
Both input and output files are UTF-8.

I have a simple example.
The file SpanishCharacters.c contains only a comment in Spanish:
```
/** Un cometario en español.

Acento en la á
Acento en la é
Acento en la í
Acento en la ó
Acento en la ú
*/
```
After running uncrustify, I would expect no changes, since it is just a comment and does not have any issues, but instead all accents and ñ are erased:
```
/** Un cometario en espaol.

Acento en la 
Acento en la 
Acento en la 
Acento en la 
Acento en la 
*/
```
Command used: 
`uncrustify -c uncrustify.cfg -f SpanishCharacters.c -o outputWithoutSpanishCharacters.c -p debugFile`
I am using uncrustify version 0.59
Attached is a zip file containing input, output and debug file.
[testingSpanish.zip](https://github.com/uncrustify/uncrustify/files/4192861/testingSpanish.zip)

Is it something in the config file? I am using the default config file generated with visual studio code extension.
I would appreciate any help.
Thanks.

**Comment by gmaurel** [comment]
Your uncrustify is pretty old.
We now have 0.70.1
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
I just now get:
```.c
/** Un cometario en español.

   Acento en la á
   Acento en la é
   Acento en la í
   Acento en la ó
   Acento en la ú
 */
```

**Comment by Calu85** [comment]
You are right. I noticed it was an old version after filling the issue form.
I had installed the version from the linux repository. Now I compiled the latest version and it works fine. I get the same file you posted.
Sorry for the inconvenience and thanks for the answer.
