### ISSUE TITLE
Inconsistent behaviour of indent_cmt_with_tabs

### ISSUE THREAD

**Issue by QuickJack** [uncrustify/uncrustify#2661]
My uncrustify config is as follows
```
# Uncrustify-0.70.1
indent_cmt_with_tabs            = true
```

My C++ test code
```
int i=5;//comment without leading space
int j=3; //comment with leading space
int k=111;//long comment without leading space
```

The result using [https://cdanu.github.io/uncrustify_config_preview/index.html]()
```
int i=5;//comment without leading space
int j=3;//comment with leading space
int k=111;	//long comment without leading space
```

There is also an option called align_right_cmt_span with the description "The span for aligning comments that end lines. 0: Don't align (default).". From looking at the above results it seems that indent_cmt_with_tabs inserts tabs before comments. This will happen for code lines that are 10 characters or longer only. The option align_right_cmt_span doesn't do what it's description says. It does not prevent comments that end lines from beeing aligned.

How exactly does indent_cmt_with_tabs work?

**Comment by gmaurel** [comment]
You need to use the options:
```.txt
##align_right_cmt_gap may NOT be set
indent_with_tabs     = 0
align_right_cmt_span = 3
```
to get:
```.cpp
Uncrustify_d-0.70.1-200-04882d06
Parsing: QuickJack.cpp as language CPP
int i=5;   //comment without leading space
int j=3;   //comment with leading space
int k=111; //long comment without leading space
```

**Comment by QuickJack** [comment]
Thanks, this shows how to align comments by using spaces. By activating indent_cmt_with tabs, the same is done by using tabs.

Is there a way to stop the alignment of trailing comments like in the given example? I want to cover a larger codebase and my goal is to minimize the number of changes introduced by using Unrcustify.

**Comment by gmaurel** [comment]
use the two options:
disable_processing_cmt
enable_processing_cmt

**Comment by QuickJack** [comment]
This will again require to modify existing sources. It would be nice to have a real cfg option to globally disable processing of comments. Alternatively, a method to selectively disable it for right hand comments which are not using spaces/ tabs for alignment. I think, it's not always a good idea to force right hand comments to be aligned.
