### ISSUE TITLE
[Pawn] Unexpected space after function name

### ISSUE THREAD

**Issue by ADRFranklin** [uncrustify/uncrustify#2665]
Debug: https://pastebin.com/ay2D52TQ (with global variable)
Debug: https://pastebin.com/k3VfusVb (without global variable)

When declaring global variables using `static` or with `stock` the next function seems to get an extra space added after the functions name and before the parenthesises.

```
/// <summary>
/// Stores a map of discord channels
/// </summary>
static Map:discord_channels;

/// <summary>
/// The entry point used to setup the discord
/// connectors properties
/// </summary>
static Entrypoint()
{
}

/// <summary>
/// Add Channel provides a way to pass a name and a
/// env name, that will be used to get the env variable
/// which will be used to grab the channel id that is
/// passed via env's in the form of
/// `SAMP_DISCORD_CHANNEL_*_ID
/// </summary>
static AddChannel(const name[], const env_name[])
{
}
```

This code above is how `Entrypoint` is supposed to look like when it is formatted. However what happens after formatting is this:
```
static Entrypoint ()
{
}
```

A space appears after the function name. I have included 2 debug files, one with the global variable defined which is what causes the extra space to appear, and another showing the expected result when the global variable doesn't exist.

**Comment by guy-maurel** [comment]
I am missing the types of the functions.
Is it correct?

**Comment by ADRFranklin** [comment]
Yes, the types.
```
// Variables
stock my_var;
stock static my_var2;
static stock my_var3;
new my_var4;
const my_var5 = 12;
static const my_var6 = 13;

// Functions
my_func()
{}

static my_func2()
{}

static stock my_func3()
{}

stock my_func4()
{}
```

these are expected use cases for types.

**Comment by ADRFranklin** [comment]
@guy-maurel @gmaurel Any update on this one?
