### ISSUE TITLE
C++: Incorrect newline in constructor of sub class

### ISSUE THREAD

**Issue by marco-stephan** [uncrustify/uncrustify#2668]
An additional newline is added between a constructor's function header and its initialization list if the class contains a variable.
This also affects structs.

### Input:
```C++
class SuperClass {
};

class SubClass1 : public SuperClass
{
SubClass1()
	: SuperClass()
{
}
};

class SubClass2 : public SuperClass
{
bool variable;

SubClass2()
	: SuperClass()
{
}
};
```

### Output:
```C++
class SuperClass {
};

class SubClass1 : public SuperClass
{
SubClass1()
	: SuperClass()
{
}
};

class SubClass2 : public SuperClass
{
bool variable;

SubClass2()

	: SuperClass()
{
}
};
```

### Expected output: 
Same as input

### Uncrustify: 
Version: Uncrustify-0.70.1_f
Debug: [debug.txt](https://gist.github.com/marco-stephan/870bc7737a9f62fb995451dbd048a372)
Relevant config:
> nl_var_def_blk_end = 2

**Comment by guy-maurel** [comment]
PR #2682 is a bugfix proposal.
Please test it and report.

**Comment by marco-stephan** [comment]
Thanks for the PR! The issue is indeed fixed by it.
