### ISSUE TITLE
C++: Error while parsing if an anonymous child struct is defined

### ISSUE THREAD

**Issue by marco-stephan** [uncrustify/uncrustify#2672]
Uncrustify throws an error when parsing the following code:

```C++
struct BaseStruct {};
struct : BaseStruct {};
```

Version: Uncrustify-0.70.1-219-6652ddb5-dirty
Relevant config: None (Throws an error regardless of used config file)

**Comment by gmaurel** [comment]
The problem seams to be a little different for me. I use Linux-Mint.
```.log
Uncrustify_d-0.70.1-221-ed7d354c
Parsing: marco-stephan.cpp as language CPP
combine_labels(403): marco-stephan.cpp:2 unexpected colon in col 8 n-parent=STRUCT c-parent=NONE l=0 bl=0
struct BaseStruct {};
struct : BaseStruct {};
```

**Comment by marco-stephan** [comment]
My bad. By "crash" I mean Uncrustify throws an error. I will edit the description accordingly.

**Comment by guy-maurel** [comment]
`clang-6.0 -Xclang -ast-dump -fsyntax-only marco-stephan.cpp`
says:
```.log
marco-stephan.cpp:2:1: error: anonymous structs and classes must be class members
struct : BaseStruct {};
```
Push a more complete example with your error

**Comment by marco-stephan** [comment]
Here is a bit more complete example:
```C++
struct Point2D
{
	float x;
	float y;
};

struct : Point2D
{
	float z;
} point;
```

Syntactically, this code is fine but again Uncrustify throws an error

**Comment by guy-maurel** [comment]
PR #2696 is a bugfix proposal.
Please test it and report.

**Comment by marco-stephan** [comment]
It looks like your PR fixes the issue. Thanks!
