### ISSUE TITLE
Objective-C: Indent switch case 

### ISSUE THREAD

**Issue by TofPlay** [uncrustify/uncrustify#268]
Hi
I have a switch case on my Objective-C code like this one:
```Objective-C
 switch (pCode) {
    case 0: 
    {
       // My code here
    }
      break;
      
    case 1: // Contact by SMS
    {
       // My code here
    }
      break;
      
    default:
      break;
  }
```
I want to align case block like this:
```Objective-C
 switch (pCode) {
    case 0: 
      {
         // My code here
      }
      break;
      
    case 1: 
      {
         // My code here
      }
      break;
      
    default:
      break;
  }
```
I tried to use **indent_switch_case = 2**  to align the case but it doesn't work
I use Xcode 5.1.1 and the plugin BBUncrustifyPlugin install with *[Alcatraz](http://alcatraz.io/)* a package manager for Xcode

**Comment by gmaurel** [comment]
Please use
  indent_switch_case=3
