### ISSUE TITLE
Uniform initialization indentation fails when nested in function argument

### ISSUE THREAD

**Issue by sparist** [uncrustify/uncrustify#2684]
The indentation of uniform initialization fails when done on an argument in a function call. Behold:

- Input:
```
someFunction(
  someType{
    "some argument" // This should be indented
  } // ...and so should this
);
```
- Output:
```
someFunction(
  someType{
  "some argument"   // This should be indented
}   // ...and so should this
);
```
- Debug output: [debug.txt](https://pastebin.com/6W5qcfmn)
- Uncrustify version: Uncrustify-01cca0b

**Comment by guy-maurel** [comment]
You need to use the option:
`indent_paren_open_brace = true`

**Comment by sparist** [comment]
That fixed it! Thanks, and sorry for the noise.
