### ISSUE TITLE
Converts CRLF to LF when newlines=auto and input is from STDIN

### ISSUE THREAD

**Issue by shoogle** [uncrustify/uncrustify#2686]
The config option `newlines=auto` is supposed to preserve the existing newline style, but the behaviour is equivalent to `newlines=lf` if the input comes from STDIN.

With:

- [infile.c](https://github.com/uncrustify/uncrustify/files/4304729/infile.c.txt)
- [newlines.cfg](https://github.com/uncrustify/uncrustify/files/4304730/newlines.cfg.txt)

```bash
$ file infile.c
infile.c: C source, ASCII text, with CRLF line terminators

$ <infile.c uncrustify -c newlines.cfg -o outfile.c

$ file outfile.c
outfile.c: C source, ASCII text
```

Notice that the output file is no longer flagged as having CRLF line terminators.

__Uncrustify Version:__ Uncrustify-0.70.1_f (Windows 10)
__Relevant config:__ `newlines=auto`

**Comment by gmaurel** [comment]
The current git version works under Linux-Mint pretty fine.
  https://github.com/uncrustify/uncrustify
```.log
Uncrustify-0.70.1-247-2e89424c
Parsing: 30 bytes (30 chars) from stdin as language C
file infile.c
infile.c: C source, ASCII text, with CRLF line terminators
file outfile.c 
outfile.c: C source, ASCII text, with CRLF line terminators
```
We have to try with logging.
Please use` uncrustify ... -L A 2>A.txt` and push the A.txt file

**Comment by shoogle** [comment]
I still get the problem with latest git version on Windows 10:

```bash
$ build/Debug/uncrustify.exe --version
Uncrustify_d-0.70.1-253-86143624

$ <infile.c build/Debug/uncrustify.exe -c newlines.cfg -o outfile.c -L A 2>A.txt

$ file infile.c outfile.c
infile.c:  C source, ASCII text, with CRLF line terminators
outfile.c: C source, ASCII text
```

Log: [A.txt](https://github.com/uncrustify/uncrustify/files/4340335/A.txt)

**Comment by gmaurel** [comment]
you wrote:
```
$ file infile.c
infile.c:  C source, ASCII text, with CRLF line terminators
```
but I can find in your A.txt, at line 79:
```Using LF line endings```
why is the question.
Which environment do you have?
Linux/Windows?
Which command interpreter are you using?

**Comment by shoogle** [comment]
Windows. I've tested in Git Bash and CMD and get the same result in both. I've tried other programs and they pass through CRLF unchanged, so the issue is specific to Uncrustify.

I have access to Linux and macOS but I've not tested on those platforms.

**Comment by gmaurel** [comment]
Could you create a little program to "see" what the read is getting from the stdin?

**Comment by shoogle** [comment]
Problem is caused by the Windows C library converting `\r\n` to `\n` in text streams. Solution is to read the file as a binary stream of bytes. This is implemented in PR #2700.

**Comment by guy-maurel** [comment]
@shoogle 
Hello Peter!
Why is it necessary to freopen(NULL, "rb", stdin); for the NOT Windows OS?
Please have a look at https://github.com/uncrustify/uncrustify/pull/2700

**Comment by shoogle** [comment]
@gmaurel, I [answered in the PR](https://github.com/uncrustify/uncrustify/pull/2700/files#r435483694) since that's where the relevant change is. Basically, it does no harm and might be necessary in certain cases. Of couse, if you find that it does do harm for some reason then feel free to change it, or to add more exceptions based on platform.
