### ISSUE TITLE
Vala RegEx expressions are destroyed

### ISSUE THREAD

**Issue by aggsol** [uncrustify/uncrustify#2687]
The following expression in Vala

```
/^[a-zA-Z0-9_-]*$/.match(...)
```

is mangled to 
```
/ ^[a - zA - Z0 - 9_ -] * $ /.match(...);
```

tested with: Uncrustify-0.68_f

**Comment by gmaurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by aggsol** [comment]
I test it with Uncrustify_d-0.70.1-253-86143624 an the problem still persist. This might be a problem with [my config](https://gist.github.com/aggsol/85689b26c9986022ff47775b5f91d5b9) problem on my side. Will inform you after more tests.

**Comment by gmaurel** [comment]
Yes.
Try this:
```
uncrustify -c aggsol.cfg -f aggsol.vala -o out.vala -p p.txt -L A 2>A.txt
uncrustify -c aggsol-2.cfg -f aggsol.vala -o out-2.vala -p p-2.txt -L A 2>A-2.txt
```
and use, to compare:
`meld A*`
you can see:
```
do_space(2247): first->orig_line is 1, first->orig_col is 1, first->text() is '/', [ARITH/NONE] <===>
   second->orig_line is 1, second->orig_col is 2, second->text() '^', [CARET/NONE] : rule sp_arith[line 2247]
 rule = FORCE @ 1 => 3
```
Your config file, at line 111 is
`sp_arith=force`
exactly correct.

**Comment by aggsol** [comment]
@gmaurel Thank you for your debugging steps, that will help me in the future to find problems. I wonder if the parser in uncrustify could detect that `/` surround a Regex that does not contain normal arithmetic operators/assignments/square brackets like elsewhere in the code. 

My workaround now is to wrap the Regex in a string because I want the forced spaces around arithmetic operators in the code but not in the Regex.

**Comment by gmaurel** [comment]
...  could detect that / surround a Regex ...
NO, uncrustify is not a compiler.
You workaround is not a workaround: it is the right way.

**Comment by aggsol** [comment]
Thank you for the clarification. uncrustify does not touch symbols within a string literal. So there must be some context that prevents the beautification within string literals.
