### ISSUE TITLE
Wrong spacing around bool operator inside C++ braces

### ISSUE THREAD

**Issue by samishchandra** [uncrustify/uncrustify#2688]
### ⬇️Input:
```
{
  flag &&(hasFeedback != nil)
  ? objectA
  : objectB,
};
```

### ✅Expected Output:
```
{
  flag && (hasFeedback != nil)
  ? objectA
  : objectB,
};
```

### ❌Actual Output:
```
{
  flag &&(hasFeedback != nil)
  ? objectA
  : objectB,
};
```

### ⚙️Config options used:
> sp_arith  = true 
> sp_bool  = true
> sp_compare = true

**Comment by samishchandra** [comment]
May be `&&` is considered reference pointer instead of `boolean` operator.

**Comment by guy-maurel** [comment]
NO.
I think I will never use this expression such as.
If you write:
```.cpp
{
  objectZ = flag &&(hasFeedback != nil)
  ? objectA
  : objectB,
};
```
the token && is still correct:
`  #   2>               BOOL|                        &&`

**Comment by samishchandra** [comment]
Following is a valid expression. In the following case, we need to treat `&&` as boolean operator, correct ?
```
std::vector<Object> someVector = {
  flag && (hasFeedback != nil)
  ? objectA
  : objectB,
};
```
