### ISSUE TITLE
star in bitfield expression is always treated as pointer

### ISSUE THREAD

**Issue by dlech** [uncrustify/uncrustify#2689]
Bit fields with a `*` such as the one below result in the star being treated as a pointer token instead of an arithmetic token.
[debug.txt](https://github.com/uncrustify/uncrustify/files/4309510/debug.txt)
[log.txt](https://github.com/uncrustify/uncrustify/files/4309511/log.txt)

```cpp
class C
{
public:
   size_t f1 : 1;
   size_t f1:1;
   size_t f2 : sizeof(size_t) - 1;
   size_t f2 : 8 * sizeof(size_t) - 2; // <-- this star is treated a pointer token

Q_SIGNALS:
   void somesignal();
};
```

This can be seen by applying the following patch and running tests.

```diff
diff --git a/tests/config/ben_031.cfg b/tests/config/ben_031.cfg
index fe2182c..a90e6af 100644
--- a/tests/config/ben_031.cfg
+++ b/tests/config/ben_031.cfg
@@ -1,4 +1,5 @@
 indent_columns                  = 3
 indent_class                    = true
 indent_label                    = 2
-indent_access_spec              = 2
\ No newline at end of file
+indent_access_spec              = 2
+sp_after_ptr_star               = remove
\ No newline at end of file
diff --git a/tests/expected/cpp/31720-bit-colon.cpp b/tests/expected/cpp/31720-bit-colon.cpp
index b8e7c4d..1fad941 100644
--- a/tests/expected/cpp/31720-bit-colon.cpp
+++ b/tests/expected/cpp/31720-bit-colon.cpp
@@ -4,6 +4,7 @@ class C
    size_t f1 : 1;
    size_t f1 : 1;
    size_t f2 : sizeof(size_t) - 1;
+   size_t f2 : 8 * sizeof(size_t) - 2;
 
  Q_SIGNALS:
    void somesignal();
@@ -15,6 +16,7 @@ struct S
    size_t f1 : 1;
    size_t f1 : 1;
    size_t f2 : sizeof(size_t) - 1;
+   size_t f2 : 8 * sizeof(size_t) - 2;
 
  Q_SIGNALS:
    void somesignal();
diff --git a/tests/input/cpp/bit-colon.cpp b/tests/input/cpp/bit-colon.cpp
index b593255..dfb8b9b 100644
--- a/tests/input/cpp/bit-colon.cpp
+++ b/tests/input/cpp/bit-colon.cpp
@@ -4,6 +4,7 @@ public:
    size_t f1 : 1;
    size_t f1:1;
    size_t f2 : sizeof(size_t) - 1;
+   size_t f2 : 8 * sizeof(size_t) - 2;
 
 Q_SIGNALS:
    void somesignal();
@@ -15,6 +16,7 @@ private:
    size_t f1 : 1;
    size_t f1:1;
    size_t f2 : sizeof(size_t) - 1;
+   size_t f2 : 8 * sizeof(size_t) - 2;
 
 Q_SIGNALS:
    void somesignal();
```

Using a debgger, I have traced it to:

```
mark_variable_definition(chunk_t * start) (/home/david/work/pybricks/uncrustify/src/combine.cpp:4013)
fix_var_def(chunk_t * start) (/home/david/work/pybricks/uncrustify/src/combine.cpp:3929)
fix_symbols() (/home/david/work/pybricks/uncrustify/src/combine.cpp:2337)
uncrustify_start(const std::deque<int, std::allocator<int> > & data) (/home/david/work/pybricks/uncrustify/src/uncrustify.cpp:1827)
uncrustify_file(const file_mem & fm, FILE * pfout, const char * parsed_file, bool defer_uncrustify_end) (/home/david/work/pybricks/uncrustify/src/uncrustify.cpp:1903)
do_source_file(const char * filename_in, const char * filename_out, const char * parsed_file, bool no_backup, bool keep_mtime) (/home/david/work/pybricks/uncrustify/src/uncrustify.cpp:1470)
main(int argc, char ** argv) (/home/david/work/pybricks/uncrustify/src/uncrustify.cpp:908)
```

Attached .txt files from `./build/uncrustify -p debug.txt -L A -f tests/input/cpp/bit-colon.cpp -c tests/config/ben_031.cfg 2>log.txt`

Actual output is:

```cpp
lass C
{
 public:
   size_t f1 : 1;
   size_t f1 : 1;
   size_t f2 : sizeof(size_t) - 1;
   size_t f2 : 8 *sizeof(size_t) - 2;

 Q_SIGNALS:
   void somesignal();
};

struct S
{
 private:
   size_t f1 : 1;
   size_t f1 : 1;
   size_t f2 : sizeof(size_t) - 1;
   size_t f2 : 8 *sizeof(size_t) - 2;

 Q_SIGNALS:
   void somesignal();
};
```

Expected output is:

```cpp
lass C
{
 public:
   size_t f1 : 1;
   size_t f1 : 1;
   size_t f2 : sizeof(size_t) - 1;
   size_t f2 : 8 * sizeof(size_t) - 2;

 Q_SIGNALS:
   void somesignal();
};

struct S
{
 private:
   size_t f1 : 1;
   size_t f1 : 1;
   size_t f2 : sizeof(size_t) - 1;
   size_t f2 : 8 * sizeof(size_t) - 2;

 Q_SIGNALS:
   void somesignal();
};
```

Using version 0.70.1.

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
PR #2698 is a bugfix proposal.
Please test it and report.

**Comment by dlech** [comment]
I have tested the fix. It is working. Thanks!
