### ISSUE TITLE
C++: Incorrect newline between variable declarations of a class

### ISSUE THREAD

**Issue by marco-stephan** [uncrustify/uncrustify#2692]
An additional newline is added between variable declarations inside a class if one variable's type belongs to a namespace.

This issue seems to be introduced by https://github.com/uncrustify/uncrustify/pull/2682/commits/d76e41304b628eba98debd70e05f4ab36797ea6c.

### Input:
```C++
class Class
{
std::mutex* a;
int* b;
};
```

### Output:
```C++
class Class
{
std::mutex* a;

int* b;
};
```

### Expected output: 
Same as input

### Uncrustify: 
Version: Uncrustify-0.70.1-253-86143624
Debug: [debug.txt](https://gist.github.com/marco-stephan/9e246e21351f4363926f91f437cba736)
Relevant config:
> nl_var_def_blk_start = 2

**Comment by guy-maurel** [comment]
PR #2697 is a bugfix proposal.
Please test it and report.

**Comment by marco-stephan** [comment]
It looks like your PR fixes the issue. Thanks.
