### ISSUE TITLE
C++: function parameter alignment inside macro sometimes not working

### ISSUE THREAD

**Issue by geimer** [uncrustify/uncrustify#2703]
Below is a test case condensed from our code base.  With the given input and configuration, I expect the code not to change when uncrustified.  However, for the first operator defined by the macro, the first parameter is not aligned with the second in the output.  The fun part is that it works for the second operator (and in our code base also for the following ones).  Also, interchanging the two operator definitions does not change things much; in this case the second parameter is not aligned with the first.

From what I could figure out so far, the setting of `sp_after_byref` has an impact. If set to `ignore` or `add`, everything works as expected. But `force` or `remove` should still not break the alignment (and it never does for the second operator).

Input/expected output:
```C++
#define DEFINE_OPERATORS(classT, flagsT)          \
    inline classT::flagsT                         \
    operator&(const classT::flagsT&          lhs, \
              const classT::flagsT::EnumType rhs) \
    {                                             \
        return classT::flagsT(lhs) &= rhs;        \
    }                                             \
                                                  \
    inline classT::flagsT                         \
    operator&(const classT::flagsT::EnumType lhs, \
              const classT::flagsT&          rhs) \
    {                                             \
        return classT::flagsT(lhs) &= rhs;        \
    }
```

Actual output:
```C++
#define DEFINE_OPERATORS(classT, flagsT)          \
    inline classT::flagsT                         \
    operator&(const classT::flagsT& lhs, \
              const classT::flagsT::EnumType rhs) \
    {                                             \
        return classT::flagsT(lhs) &= rhs;        \
    }                                             \
                                                  \
    inline classT::flagsT                         \
    operator&(const classT::flagsT::EnumType lhs, \
              const classT::flagsT&          rhs) \
    {                                             \
        return classT::flagsT(lhs) &= rhs;        \
    }
```

Minimal configuration:
```
indent_columns                            = 4
indent_with_tabs                          = 0
align_func_params                         = true
sp_after_byref                            = force
```

* Debug file: [debug.txt](https://gist.github.com/geimer/62d8c533784b6dbf30a13cb6564ebf1c)
* Uncrustify version: Uncrustify_d-0.70.1-266-00558c13

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
PR #2740 is a bugfix proposal.
Please test it and report.

**Comment by geimer** [comment]
Seems to work, thanks!  I guess you also want to include the test case in the PR?
