### ISSUE TITLE
C++: Indentation of commentary inside class (regression)

### ISSUE THREAD

**Issue by geimer** [uncrustify/uncrustify#2704]
While 350595ec92640289523a681ed0e4b830b52fa13c (identified using bisecting) addresses the way comments are used in #1161, it breaks another valid use case: Doxygen grouping commentary as shown below.  One possible alternative heuristic may be to only align the commentary with the access specifier if it is *not* a Doxygen comment (assuming that this can be identified reliably).

Input:
```C++
class Foo
{
    public:
        /// @name Constructor
        /// @{

        Foo(int value) : value_(value)
        {}

        /// @}

    private:
        int value_;
};
```

Minimal config:
```
indent_columns                            = 4
indent_with_tabs                          = 0
indent_class                              = true
indent_access_spec_body                   = true
```

Expected output:
```C++
class Foo
{
    public:
        /// @name Constructor
        /// @{

        Foo(int value) : value_(value)
        {
        }

        /// @}

    private:
        int value_;
};
```

Actual output:
```C++
class Foo
{
    public:
        /// @name Constructor
        /// @{

        Foo(int value) : value_(value)
        {
        }

    /// @}

    private:
        int value_;
};
```

Debug log: [debug.txt](https://gist.github.com/geimer/0fe3b26a16e02472b245473d1cd26932)
Uncrustify version: Uncrustify_d-0.70.1-275-672f838d

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by gmaurel** [comment]
Thanks
