### ISSUE TITLE
Return statement incorrectly removed when followed by fixed block (mod_remove_empty_return)

### ISSUE THREAD

**Issue by tomekpaszek** [uncrustify/uncrustify#2705]
**mod_remove_empty_return** seems to remove the return statement if it's followed by a `fixed` block.

[debug.txt](https://github.com/uncrustify/uncrustify/files/4386624/debug.txt)
version: Uncrustify_d-0.70.1-275-672f838d

test:
```
public class A
{
public void A(string a)
{
	if (a == null)
	{
		return;
	}

	fixed(char* ptr = a)
	{
		 a = a + a;
	}
}
}
```
generated result:
```
public class A
{
public void A(string a)
{
	if (a == null)
	{
	}

	fixed(char* ptr = a)
	{
		a = a + a;
	}
}
}
```

expected (unchanged):
```
public class A
{
public void A(string a)
{
	if (a == null)
	{
		return;
	}

	fixed(char* ptr = a)
	{
		a = a + a;
	}
}
}
```

**Comment by gmaurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
```.txt
Uncrustify_d-0.70.1-281-725e9965-dirty
Parsing: tomekpaszek.cpp as language CPP
//example file
public class A
{
public void A(string a)
{
        if (a == null)
        {
                return;
        }

        fixed(char* ptr = a)
        {
                a = a + a;
        }
}
}
```

**Comment by tomekpaszek** [comment]
> The current git version works pretty fine.
> https://github.com/uncrustify/uncrustify
> Please test it and report!
> 

Hi @gmaurel !
I have tested it again and got following result:

test.cs.uncrustify:
```csharp
public class A
{
public void A(string a)
{
	if (a == null)
	{
	}

	fixed(char* ptr = a)
	{
		a = a + a;
	}
}
}
```

Repro steps on macos:
- cloned uncrustify (672f838d7ce23f7a30e8ce02d1e9000d5f3460c4)
- build (`mkdir build`; `cd build`; `cmake ..`; `cmake build .`)
- `./uncrustify -c test.cfg test.cs`


test.cs
```csharp
public class A
{
public void A(string a)
{
        if (a == null)
        {
                return;
        }

        fixed(char* ptr = a)
        {
                a = a + a;
        }
}
}
```

test.cfg
```
mod_remove_empty_return         = true
```

**Comment by guy-maurel** [comment]
Sorry.

**Comment by tomekpaszek** [comment]
> Parsing: tomekpaszek.cpp as language CPP

I noticed you parsed it as cpp and my code is in C#

**Comment by guy-maurel** [comment]
PR #2733 is a bugfix proposal.
Please test it and report.

**Comment by tomekpaszek** [comment]
it works, thank you
