### ISSUE TITLE
mod_remove_extra_semicolon removes semicolon of java lambda

### ISSUE THREAD

**Issue by machtelik** [uncrustify/uncrustify#2713]
Config:
```
# Uncrustify-0.70.1_f
mod_remove_extra_semicolon = true
```

Input:
```
Callback callback = foo-> {
    // [...]
};
```

Output (no changes are expected):
```
Callback callback = foo-> {
    // [...]
}
```

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
Sorry: which language is it?

**Comment by guy-maurel** [comment]
I get just now:
```.txt
Uncrustify_d-0.72.0-39-58f399bd
Parsing: machtelik.java as language JAVA
Callback callback = foo-> {
        // [...]
};

```
