### ISSUE TITLE
Erroneous removal of semicolon

### ISSUE THREAD

**Issue by elnull** [uncrustify/uncrustify#2714]
Uncrustify 0.70.1 removes semicolon after initializer in this code:
```
struct A
{
  int b : 4 { 2 };
};
```
so it becomes incorrect
```
struct A
{
  int b : 4 { 2 }
};
```

**Comment by gmaurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
```.txt
Uncrustify_d-0.70.1-281-725e9965-dirty
Parsing: elnull.cpp as language CPP
struct A
{
        int b : 4 { 2 };
};
```

**Comment by elnull** [comment]
It stays the same for me with current master and this config file [default.cfg.gz](https://github.com/uncrustify/uncrustify/files/4409730/default.cfg.gz)

**Comment by elnull** [comment]
I've found it's because of option
```
mod_remove_extra_semicolon = true
```
was set.

**Comment by elnull** [comment]
I think, even if
```
mod_remove_extra_semicolon = true
```
uncrustify shouldn't remove required semicolon.
