### ISSUE TITLE
Function body after trailing return type is treated as brace init list

### ISSUE THREAD

**Issue by eternalphane** [uncrustify/uncrustify#2730]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
### Info
current version: Uncrustify-0.70.1-294-cf50d379
[debug.txt](https://gist.github.com/eternalphane/cbdd08ccfa62e5966f208f92c95fdc28#file-debug-txt)
[log.txt](https://gist.github.com/eternalphane/cbdd08ccfa62e5966f208f92c95fdc28#file-log-txt)
### Input
```cpp
template <class... Args>
struct signal
{
    template <class T>
    auto operator()(void (T::* ptr)(Args...)) const noexcept -> decltype(ptr) { return ptr; }

    template <class T>
    static auto of(void (T::* ptr)(Args...)) noexcept -> decltype(ptr) { return ptr; }
};
```
### Output
```cpp
template <class... Args>
struct signal
{
    template <class T>
    auto operator()(void (T::* ptr)(Args...)) const noexcept -> decltype(ptr) {return ptr;}

    template <class T>
    static auto of(void (T::* ptr)(Args...)) noexcept -> decltype(ptr) {return ptr;}
};
```

**Comment by guy-maurel** [comment]
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by eternalphane** [comment]
It worked. Thanks~
