### ISSUE TITLE
[BUG] Three way (spaceship) operator.

### ISSUE THREAD

**Issue by neok-m4700** [uncrustify/uncrustify#2736]
Hi,
The following is valid `c++20` code: `$ g++ -std=c++2a a.cc`, compiles fine on `gcc master`.

`$ cat a.cc`
```c++
#include <iostream>
using namespace std;

struct Int
{
    int i;
    auto operator<=>(const Int& rhs) const = default;
};

int main()
{
    cout << boolalpha << (Int{-1} < Int{1}) << endl;
}
```
`$ cat cfg`
```
sp_compare = force
```
`$ uncrustify --version`
```
Uncrustify-0.70.1
```

`$ cat a.cc | uncrustify -c cfg -l cpp`
```c++
#include <iostream>
using namespace std;

struct Int
{
	int i;
	auto operator<= > (const Int& rhs) const = default;
};

int main()
{
	cout << boolalpha << (Int{-1} < Int{1}) << endl;
}
```
I expect the line `auto operator<=>(const Int& rhs) const = default;` to remain as is, since the formatted code does NOT compile anymore.

I believe that the three way operator `<=>` should be classified under CT_COMPARE.

Here is a simple patch solving the aforementioned issue, but I'm not expert on the uncrustify code structure, maybe someone could point me in the right direction for writing integration tests for this bug ?
```diff
--- src/symbols_table.h  2020-04-09 22:33:04.791274000 +0000
+++ src/symbols_table.h  2020-04-09 22:33:15.611571000 +0000
@@ -10,7 +10,7 @@
  *
  *   The file "punctuator_table.h" was generated by punc.py from this file.
  *   If you change one of the below symbol tables, re-run punc.py.
- *   $ python scripts/punc.py > src/punctuator_table.h
+ *   $ python scripts/make_punctuator_table.py src/punctuator_table.h src/symbols_table.h
  *   now automatically with CMakeLists.txt
  *
  *   NOTE: the tables below do not need to be sorted.
@@ -48,6 +48,7 @@
    { "!<>",      CT_COMPARE,      LANG_D                                                       },
    { "!==",      CT_COMPARE,      LANG_D | LANG_ECMA                                           },
    { "!>=",      CT_COMPARE,      LANG_D                                                       },
+   { "<=>",      CT_COMPARE,      LANG_CPP                                                     },
    { "->*",      CT_MEMBER,       LANG_C | LANG_CPP | LANG_OC | LANG_D                         },
    { "...",      CT_ELLIPSIS,     LANG_C | LANG_CPP | LANG_OC | LANG_D | LANG_PAWN | LANG_JAVA },
    { "<<=",      CT_ASSIGN,       LANG_ALL                                                     },
```

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by gmaurel** [comment]
Please, make a push request, join the test data and add the case in the file
  uncrustify/tests/cpp.tests
To do that, have a look to CONTRIBUTING.md
Thanks
