### ISSUE TITLE
Disable formatting of NL_CONT'ed macros

### ISSUE THREAD

**Issue by neok-m4700** [uncrustify/uncrustify#2737]
I would like to be able to disable any formatting done by uncrustify on `\ + \n` (NL_CONT) ended lines (basically multi-line macros), **without** wrapping them with ` *INDENT-OFF/ON*` blocks.

`$ cat a.cc`
```c++
#define INC    \
do             \
{              \
  a += 1;      \
} while (0)
```

Maybe I missed some options (I've played around with a lot of options, without success), but I want to disable the following behavior, and leave the definition untouched:
`$ uncrustify -c /dev/null a.cc`
```c++
#define INC    \
	do             \
	{              \
		a += 1;      \
	} while (0)
```
Maybe I can implement some new option called `disable_processing_nl_cont = false # true/false` ? Could you give some advice on that ?

`$ uncrustify --version`
```
Uncrustify-0.70.1
```
**EDIT:**
Tentative patch (1 test fails `cli_options`, for obvious reasons):
```diff
--- src/indent.cpp  2019-11-27 16:14:24.000000000 +0100
+++ src/indent.cpp  2020-04-10 14:01:43.981009842 +0200
@@ -582,6 +582,13 @@
 
    while (pc != nullptr)
    {
+      if (options::disable_processing_nl_cont() && (chunk_is_token(chunk_get_next_nl(pc), CT_NL_CONT) || chunk_is_token(chunk_get_prev_nl(pc), CT_NL_CONT)))
+      {
+         pc = chunk_get_next_nl(pc);
+         continue;
+      }
+
       //  forces string literal to column-1 [Fix for 1246]
       if (  (pc->type == CT_STRING_MULTI)
          && !(cpd.lang_flags & LANG_OC)                      // Issue #1795

--- src/options.h  2020-04-10 13:03:29.652945000 +0200
+++ src/options.h  2020-04-10 13:37:04.651819356 +0200
@@ -75,6 +75,10 @@
 extern Option<bool>
 tok_split_gte;
 
+// Disable formatting of NL_CONT ('\\n') ended lines (e.g. multiline macros)
+extern Option<bool>
+disable_processing_nl_cont;
+
 // Specify the marker used in comments to disable processing of part of the
 // file.
 extern Option<string>
```

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by gmaurel** [comment]
Please, make a PR
Look at my comment at #2736
