### ISSUE TITLE
C++: Weird variable alignment inside macro

### ISSUE THREAD

**Issue by geimer** [uncrustify/uncrustify#2742]
Using `Uncrustify_d-0.70.1-326-6e87f6b6`, I'm experiencing some weirdness with respect to alignment of variables declared inside a macro.

Configuration:
```
align_var_def_span = 2
```
Input 1:
```C++
#define FOO \
    int a; \
    float b; \
    double c;
```
Expected output 1:
```C++
#define FOO \
	int    a; \
	float  b; \
	double c;
```
Actual output 1:
```C++
#define FOO \
	int a; \
	float b; \
	double c;
```
Debug log: [debug1.txt](https://gist.github.com/geimer/637a6f2682d53315a66f158439165008#file-debug1-txt)

When adding some code *before* the macro definition, however, at least variables `b` and `c` are aligned, but `a` is not (see below). Maybe some variable isn't properly initialized?

Input 2:
```C++
extern int ax;

#define FOO \
    int a; \
    float b; \
    double c;
```
Expected output 2:
```C++
extern int ax;

#define FOO \
    int    a; \
    float  b; \
    double c;
```
Actual output 2:
```C++
extern int ax;

#define FOO \
	int a; \
	float  b; \
	double c;
```
Debug log: [debug2.txt](https://gist.github.com/geimer/637a6f2682d53315a66f158439165008#file-debug2-txt)

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by geimer** [comment]
Some further investigation revealed that the described behavior is actually independent of whether there is some actual *code* in front of the macro definition. Here is what can be observed:
* If the `#define` is not in the first line of a file:
  * alignment of variable names works, except for the first variable.
  * alignment of the first variable works if an extra block is inserted, that is, with the following input:
    ```C++
    #define FOO \
    { \
        int a; \
        float b; \
        double c; \
    }
    ```
  * alignment of the first variable also works if some additional statement (e.g., a `typedef` or function prototype) is inserted, that is, with this input:
    ```C++
    #define FOO \
        typedef int my_type; \
        int a; \
        float b; \
        double c;
    ```
* If the `#define` is in the first line of a file:
  * alignment of the variable names is not working at all for the original test case.
  * alignment starts to work if an extra block is inserted (see above), but not with the additional statement (`typedef` or function prototype).

Overall, this still suggests that something isn't properly initialized. Unfortunately, even diff'ing log files from the various test cases with full log severity (`-LA`) didn't get me further in identifying where things start to diverge.

**Comment by guy-maurel** [comment]
I use two files: _geimer-4-b.cpp_ and _geimer-4-c.cpp_
The commands:
```.txt
uncrustify -c geimer.cfg -f geimer-4-b.cpp -p p-4-b.txt -L A 2>A-4-b.txt
uncrustify -c geimer.cfg -f geimer-4-c.cpp -p p-4-c.txt -L A 2>A-4-c.txt
meld A-4-b.txt A-4-c.txt
```
Look at 
the differences A-4-b.txt, lines from 447 and A-4-c.txt, lines from 354
geimer-4-b.cpp is:
```.cpp

#define FOO \
    aa = 5; \
    int my_type; \
    int a; \
    float b; \
    double c
```
geimer-4-c.cpp is:
```.cpp

#define FOO \
\
    int my_type; \
    int a; \
    float b; \
    double c
```
Also the p-files show some differences

**Comment by geimer** [comment]
OK, so it looks like `parse_cleanup()` does not correctly identify and flag the start of the first statement within a macro definition. This is true for both the `aa = 5` in geimer-4-b.cpp and the `int my_type;` in geimer-4-c.cpp. For a simple macro without parameters, the following patch seems to do the trick:
```diff
diff --git a/src/brace_cleanup.cpp b/src/brace_cleanup.cpp
index 0251ae0d..619a41a9 100644
--- a/src/brace_cleanup.cpp
+++ b/src/brace_cleanup.cpp
@@ -779,7 +779,8 @@ static void parse_cleanup(ParseFrame &frm, chunk_t *pc)
       || (  chunk_is_semicolon(pc)
          && frm.top().type != CT_PAREN_OPEN
          && frm.top().type != CT_FPAREN_OPEN
-         && frm.top().type != CT_SPAREN_OPEN))
+         && frm.top().type != CT_SPAREN_OPEN)
+      || chunk_is_token(pc, CT_MACRO))                         // Issue #2742
    {
       LOG_FMT(LSTMT, "%s(%d): orig_line is %zu, reset1 stmt on '%s'\n",
               __func__, __LINE__, pc->orig_line, pc->text());
```
However, I'm not sure how to reliably identify the closing paren of a macro function (i.e., `#define FOO(x) ...`) at this stage of the processing. It seems like the parent type `CT_MACRO_FUNC` that I see in the debug logs is not yet set.
