### ISSUE TITLE
Unexpected blank line in a function prototype group when a function returns a pointer 

### ISSUE THREAD

**Issue by carlolars** [uncrustify/uncrustify#2744]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
When using `nl_var_def_blk_end = 2` then a blank line is inserted in a group of function prototypes after a function that returns a pointer, if the next function does not return a pointer.
* [uncrustify-log.txt](https://gist.github.com/carlolars/3cb86a5a4368eabb22600caede9f66f6)
   ```
   # Uncrustify-0.70.1
   indent_columns                  = 4
   indent_with_tabs                = 0
   nl_var_def_blk_end              = 2
   # option(s) with 'not default' value: 3
   ```
* input:
   ```
   void func1(void);
   int *func2(void);
   int *func3(void);
   int func4(void);
   int *func5(void);
   int *func6(void);
   int var;
   ```
* generated result:
   ```
   void func1(void);
   int *func2(void);
   int *func3(void);
   
   int func4(void);
   int *func5(void);
   int *func6(void);
   int var;
   ```
* expected result:
   ```
   void func1(void);
   int *func2(void);
   int *func3(void);
   int func4(void);
   int *func5(void);
   int *func6(void);
   int var;
   ```

**Comment by guy-maurel** [comment]
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by carlolars** [comment]
Confirmed to work as expected with `Uncrustify-0.70.1-331-8ce62db1`.

Thank you!
