### ISSUE TITLE
Variable $(filename) is not replacing in file footer

### ISSUE THREAD

**Issue by elnull** [uncrustify/uncrustify#2752]
On current master if we have `footer.cfg`:
```
cmt_insert_file_footer = "footer.txt"
```
`footer.txt`
```
// EOF $(filename)
```
and `footer.cpp`:
```cpp
int main() {}
```
then after running `uncrustify -c footer.cfg footer.cpp` we have file `footer.cpp.uncrustify`:
```cpp
int main() {
}
// EOF $(filename)
```
although we should have:
```cpp
int main() {
}
// EOF footer.cpp
```

**Comment by guy-maurel** [comment]
PR #2772 is a bugfix proposal.
Please test it and report.

**Comment by elnull** [comment]
This version doesn't pass tests.

**Comment by guy-maurel** [comment]
OK.
PR #2774  is a bugfix proposal.

Please use the command:
`uncrustify -c footer.cfg -f footer.cpp -p p.txt -L A 2>A.txt`
and push the two files _p.txt_ and _A.txt_

**Comment by elnull** [comment]
Output of command:
```uncrustify -c footer.cfg -f footer.cpp -p p.txt -L A 2>A.txt```
is
```
int main() {
}

// EOF $(filename)
```
Here are [A.txt](https://github.com/uncrustify/uncrustify/files/4595827/A.txt) and [p.txt](https://github.com/uncrustify/uncrustify/files/4595828/p.txt).

**Comment by guy-maurel** [comment]
You need to use the current git sources with the PR diff file.

**Comment by elnull** [comment]
Can I use head of guy-maurel:cmt_insert branch for testing?

**Comment by guy-maurel** [comment]
Yes.
As I already merge the solution, you can also use HEAD

**Comment by elnull** [comment]
It still the same for me. Here are [A.txt](https://github.com/uncrustify/uncrustify/files/4610295/A.txt) and [p.txt](https://github.com/uncrustify/uncrustify/files/4610297/p.txt).

**Comment by guy-maurel** [comment]
If you are using the new version, you get the first line from A.txt as:
  Uncrustify_d-0.70.1-385-xxxx

**Comment by elnull** [comment]
I used current HEAD, 86e83ae8.
