### ISSUE TITLE
Inconsistent indentation of comments

### ISSUE THREAD

**Issue by geimer** [uncrustify/uncrustify#2756]
Using `Uncrustify_d-0.70.1-357-3c5a6da1` with the following configuration
```
indent_columns      = 4
indent_col1_comment = true
pp_if_indent_code   = true
```
on this minimal C++ input:
```C++
int a;

#ifdef FOO
// Commentary for func1()
void func1();

// Commentary for func2()
void func2();
#endif
```
leads to inconsistent indentation of the function commentary:
```C++
int a;

#ifdef FOO
    // Commentary for func1()
    void func1();

// Commentary for func2()
    void func2();
#endif
```

It turns out that the culprit is this code snippet: https://github.com/uncrustify/uncrustify/blob/3c5a6da1a322fb8aa59c27a994b4f385a7b5d288/src/indent.cpp#L3874-L3883

So far, I couldn't come up with a sensible use case that would justify this behavior, so I'm tempted to remove this snippet. Alternatively, one could introduce a new option, for example, named `indent_top_level_comment_span`, to configure the number of newlines required before triggering, or a simple boolean option (can't come up with a good name right now) to enable/disable this behavior.

Any opinions?

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
Yes.
There are some messages with this problem.
There are NOTHING about how it could be done.
Be free to define what we need!
I think, we need a separate indentation for preprocessor, parallel to the one for code.
A mixure would not be ok.

**Comment by geimer** [comment]
I'm not entirely sure what you mean...

As far as I can see, indentation of comments within an ifdef region would be controlled by `pp_if_indent_code` and `indent_col1_comment` (for comments starting in column 1) if the code snippet mentioned above is removed. (This is consistent and the behavior I am actually looking for.)

We could modify the `if` condition used in the code snippet to take a boolean `pp_if_indent_comment` option into account, but this would only restrict indentation of comments based on the setting of `pp_if_indent_code` (i.e., with `pp_if_indent_code = false` and `pp_if_indent_comment = true`, comments would not be indented). Making them completely independent could get rather complicated, and would IMHO require to also adjust the behavior of the `pp_indent_(case|func_def|extern|brace)` options, which currently control the indentation of the whole block if the *first* item found within the block is of the given type.

**Comment by geimer** [comment]
The more I think about the code snippet in `indent.cpp` mentioned above, the less it makes sense. If the comment is not at global scope but, for example, within a function, such as in
```C++
void foo()
{
#ifdef FOO
// Comment for a
int a;

// Comment for b
float b;
#endif
}
```
both comments will be indented and affected by `pp_if_indent_code`. Therefore, I suggest to remove this special handling and let `pp_if_indent_code` consistently control code and comments in both cases. If this would be an acceptable short-term solution, I'm happy to create a PR for this.

**Comment by guy-maurel** [comment]
Yes, please.

**Comment by geimer** [comment]
Done, see #2770.
