### ISSUE TITLE
[C++] Function parameters with template types may mess up alignment

### ISSUE THREAD

**Issue by geimer** [uncrustify/uncrustify#2757]
Whether function parameter alignment works or not seems to depend on the types of the function parameters. Using `Uncrustify_d-0.70.1-357-3c5a6da1` and the following example configuration, alignment works if the first parameter is of type `vector<int>&`, but does not work if it is of type `map<int,int>&`. (Note that this behavior is independent of the number of parameters, or whether the `map` is the first parameter or not).

Configuration:
```
indent_columns           = 4
indent_with_tabs         = 0
align_func_params        = true
align_func_params_span   = 1
align_func_params_gap    = 0
align_func_params_thresh = 0
sp_after_byref           = force
```

Input 1:
```C++
void
foo(vector< int >& a,
int b)
{
}
```

Expected and actual output 1:
```C++
void
foo(vector< int >& a,
    int            b)
{
}
```

Input 2:
```C++
void
foo(map< int, int >& a,
int b)
{
}
```

Expected output 2:
```C++
void
foo(map< int, int >& a,
    int              b)
{
}
```

Actual output 2:
```C++
void
foo(map< int, int >& a,
    int b)
{
}
```

Debug files: [debug1.txt](https://gist.github.com/geimer/dcc9e593491b54fb95ea7583200ff733#file-debug1-txt), [debug2.txt](https://gist.github.com/geimer/dcc9e593491b54fb95ea7583200ff733#file-debug2-txt)

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by geimer** [comment]
My guess is that the comma within the parameter type is erroneously considered to be the separator between parameters, potentially here:
https://github.com/uncrustify/uncrustify/blob/3c5a6da1a322fb8aa59c27a994b4f385a7b5d288/src/align_func_params.cpp#L75-L82
But I might be completely wrong...

**Comment by guy-maurel** [comment]
I work just now on #2278

**Comment by guy-maurel** [comment]
PR #2827 is a bugfix proposal.
Please test it and report.

**Comment by geimer** [comment]
Unfortunately, I was only able to test your bugfix proposal with a single file of our code base, for which it seems to work. All other files that trigger the behavior described here are hit by #2831 (already with `master`)...
