### ISSUE TITLE
[C++] 'nl_constr_init_args' does not play nicely with trailing comments

### ISSUE THREAD

**Issue by geimer** [uncrustify/uncrustify#2759]
Config:
```
nl_constr_colon                           = force
nl_constr_init_args                       = force
pos_constr_comma                          = trail
pos_constr_colon                          = lead
indent_columns                            = 4
indent_ctor_init                          = 0
indent_ctor_init_leading                  = 2
indent_constr_colon                       = true
```

Input:
```C++
Foo::Foo(int a,
         int b)
    : a_(a),  // comment
      b_(b)
{
}
```

Expected output:
```C++
Foo::Foo(int a,
         int b)
    : a_(a),  // comment
      b_(b)
{
}
```

Actual output:
```C++
Foo::Foo(int a,
         int b)
    : a_(a),
      // comment
      b_(b)
{
}
```

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
PR #3012 is a bugfix proposal.
Please test it and report.

**Comment by geimer** [comment]
I will test your bugfix proposal in the next days and report back.  Thanks!
