### ISSUE TITLE
force endif comment 

### ISSUE THREAD

**Issue by atsju** [uncrustify/uncrustify#2760]
```
# If an #ifdef body exceeds the specified number of newlines and doesn't have
# a comment after the #endif, a comment will be added.
mod_add_long_ifdef_endif_comment = 0        # unsigned number
```
According to documentation, changing the `#if` parameter of a code that has already been passed through uncrustify will not update the comment. Thus letting wring comments in code.

I found no way to update the comment.

**Comment by guy-maurel** [comment]
Please, push an example

**Comment by atsju** [comment]
Create file.c
```
#if firstcomment
//
//
//
//
//
//
#endif
```
run uncrustify you get 
```
#if first comment
//
//
//
//
//
//
#endif /* if first comment */
```
no modify the file but only the `#if` part
```
#if modified comment
//
//
//
//
//
//
#endif /* if first comment */
```
Uncrustofy will not update the comment. There should be a way to choose force update VS no update VS update only when no comment (like today)

**Comment by gmaurel** [comment]
Bonjour.
No the option add only if the condition is true.
No modify after.

**Comment by atsju** [comment]
@gmaurel why not add this functionality ? as feature request ?
