### ISSUE TITLE
can't turn off namespace indenting

### ISSUE THREAD

**Issue by bburdette** [uncrustify/uncrustify#2762]
[debug.txt](https://github.com/uncrustify/uncrustify/files/4542384/debug.txt)

before:

```
namespace meh { 
class wat {
};
}
```

after:

```
namespace meh {
    class wat {
    };
}
````

```
[bburdette@trurl:~/code/nix-error-project/nix]$ uncrustify -v
Uncrustify-0.70.1_f
```

**Comment by geimer** [comment]
Setting `indent_namespace = false` should do the trick.

**Comment by bburdette** [comment]
that's what the value is already...

```
[bburdette@trurl:~/code/nix-error-project/nix]$ uncrustify -c unc.cfg.txt meh.hh
Output suffix: .uncrustify
Parsing: meh.hh as language C

[bburdette@trurl:~/code/nix-error-project/nix]$ cat meh.hh
namespace meh { 
class wat {
};
}

[bburdette@trurl:~/code/nix-error-project/nix]$ cat meh.hh.uncrustify 
namespace meh {
    class wat {
    };
}
```

[unc.cfg.txt](https://github.com/uncrustify/uncrustify/files/4547411/unc.cfg.txt)

**Comment by bburdette** [comment]
this is what's different vs a brand new config file:

```
[bburdette@trurl:~/code/nix-error-project/nix]$ uncrustify --update-config-with-doc -o  new.cfg

[bburdette@trurl:~/code/nix-error-project/nix]$ diff new.cfg unc.cfg.txt 
15c15
< input_tab_size                  = 8        # unsigned number
---
> input_tab_size                  = 4        # unsigned number
20c20
< output_tab_size                 = 8        # unsigned number
---
> output_tab_size                 = 4        # unsigned number
922c922
< indent_columns                  = 8        # unsigned number
---
> indent_columns                  = 4        # unsigned number
950c950
< indent_with_tabs                = 1        # unsigned number
---
> indent_with_tabs                = 0        # unsigned number
```

**Comment by geimer** [comment]
For whatever reason, your input file (`.hh`) is recognized and parsed as a C input:
```
Parsing: meh.hh as language C
```
 If the same code is within a `.cpp` file, the `indent_namespace` option works as desired. You can overwrite/enhance Uncrustify's heuristics using, for example, `file_ext CPP .hh` in the configuration file.

**Comment by bburdette** [comment]
That worked!  I guess it says it straightforwardly enough, 'processing language as C'.  I often think C/C++ when I see "C".  Closing!  Thanks for the help.

**Comment by guy-maurel** [comment]
you can also use the command option:
uncrustify ... -l cpp

**Comment by bburdette** [comment]
Yep I did that in my kakoune editor setup, since I think it gives it stdin and uncrustify assumes C.
