### ISSUE TITLE
add newline after function, but don't remove multiple

### ISSUE THREAD

**Issue by jarek083** [uncrustify/uncrustify#2787]
I want this code:

```c
int foo()
{
    return 5;
}
int bar()
{
    return 3;
}


char test()
{
    return 'c';
}
```

to become:

```c
int foo()
{
    return 5;
}

int bar()
{
    return 3;
}


char test()
{
    return 'c';
}
```

But when I set `nl_after_func_body = 2`, two lines before `test()` becomes one. Is there other way?

**Comment by guy-maurel** [comment]
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!
You might use an older version.
Please make the test:
`uncrustify --version`
and
`uncrustify ... -p p.txt`
and push the file p.txt

**Comment by jarek083** [comment]
I installed `Uncrustify-0.71.0-46-071fe1a1`

I made simple test: `uncrustify -c c.conf -f a.c -p p.txt`

Where `c.conf` contains just `nl_after_func_body = 2` and the result is the same:

    int foo()
    {
        return 5;
    }

    int bar()
    {
        return 3;
    }

    char test()
    {
        return 'c';
    }

The second new line before `test()` is lost.

**Comment by CDanU** [comment]
The option works as expected: you get two '\n' chars after your closing brace. 
What you want is a `nl_min_after_func_body` so this is a feature request.

**Comment by Jorengarenar** [comment]
I don't see anybody working on it yet, so I think I might be able to send a PR

**Comment by jarek083** [comment]
Thanks!
