### ISSUE TITLE
Uncrustify-0.71.0-21-d4da2b0f-dirty never returns

### ISSUE THREAD

**Issue by Massimo-B** [uncrustify/uncrustify#2795]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

```
$ uncrustify -v
Uncrustify-0.71.0-21-d4da2b0f-dirty
```

This command never returns and no debug output is created. Files are attached here.
```
$ uncrustify -l CPP -c uncrustify.cfg -f tttest.cpp  -p debug.txt
Parsing: tttest.cpp as language CPP
^C

```
[uncrustify.cfg.tar.gz](https://github.com/uncrustify/uncrustify/files/4694448/uncrustify.cfg.tar.gz)

[tttest.tar.gz](https://github.com/uncrustify/uncrustify/files/4694435/tttest.tar.gz)

**Comment by guy-maurel** [comment]
First aid is to use the option:
```.cfg
# Limit the number of loops.
# Used by uncrustify.cpp to exit from infinite loop.
# 0: no limit.
debug_max_number_of_loops       = 10
```
It doesn't solved the problem but prevent the infinit loop.

**Comment by guy-maurel** [comment]
You wish at the same configuration:
```.cfg
nl_create_func_def_one_liner    = true
code_width                      = 140
```
This cannot fit!
I will make a change to prevent that.

**Comment by Massimo-B** [comment]
> You wish at the same configuration:
> 
> ```haproxy-config
> nl_create_func_def_one_liner    = true
> code_width                      = 140
> ```
> This cannot fit!

While the wish to have both is not unreasonable...

> I will make a change to prevent that.

...and code_width should overrule any *one_liner.

**Comment by guy-maurel** [comment]
PR #2820 is a bugfix proposal.
Please test it and report.

**Comment by Massimo-B** [comment]
Rebuilt from master
```
GIT update -->
   repository:               https://github.com/uncrustify/uncrustify.git
   updating from commit:     d4da2b0f8b2e1a5c138758b226168df1fa258dd2
   to commit:                7fdda9c7cc26d6c1d41add96a12d13466bd9d748
```
and testing again: The infinite loop has been solved. Thanks.
