### ISSUE TITLE
flag_parens error when opening bracket is guarded with #if

### ISSUE THREAD

**Issue by tomekpaszek** [uncrustify/uncrustify#2796]
Uncrustify_d-0.71.0-21-d4da2b0f
[debug.txt](https://github.com/uncrustify/uncrustify/files/4700608/debug.txt)

Hello!
I'm not sure such contact should be supported but on the other hand, when the closing bracket if guarded with #if, there is no error.

Following code will cause an error to be logged:
```
class A
{
void A()
{
#if UNITY_2020_2_OR_NEWER
        Assert.Throws(
#else
        Assert.Throws(
#endif
            );
}
}
```
Error:
```
flag_parens(22): no match for '(' at [10:22] [CallStack: flag_parens:14, mark_function:1508, do_symbol_check:335, fix_symbols:1854]
flag_parens(22): no match for '(' at [10:22] [CallStack: flag_parens:14, do_symbol_check:335, fix_symbols:1854]
```

**Comment by guy-maurel** [comment]
uncrustify is NOT a compiler.
It doesn't evaluate the preprocessor value.
Put your code as:
#if UNITY_2020_2_OR_NEWER
        Assert.Throws(1);
#else
        Assert.Throws(2);
#endif

**Comment by tomekpaszek** [comment]
Thank you for your answer.
Even though I do think it's not the best practice to write code like that, it is a valid C# code. The code does get formatted properly but the errors are emitted nevertheless.
