### ISSUE TITLE
[D] [dlang] Backtick strings are not recognized as raw

### ISSUE THREAD

**Issue by andralex** [uncrustify/uncrustify#2816]
Version: Uncrustify_d-0.71.0_f

D string literals quoted with backticks are raw, i.e. no escapes are expanded inside. Uncrustify attempts to expand escapes inside. This code causes complaints:

```d
auto s = `\`;
```

It should work.

**Comment by CDanU** [comment]
How do `Wysiwyg Strings` behave with linbreaks inside the string? Point [2.9.1](https://dlang.org/spec/lex.html#wysiwyg) is not giving my any info on that, looking at the grammar I see that a [WysiwygCharacter](https://dlang.org/spec/lex.html#WysiwygCharacter) also contains a bunch of EOL markers, as well as "_Character: any Unicode character_". I assume that based on what style is used `"` or ` are forbidden to be inside the string.
