### ISSUE TITLE
Cannot distinguish indentation of continued parameters (in function declaration) vs. continued args (in function call)

### ISSUE THREAD

**Issue by andralex** [uncrustify/uncrustify#2821]
Version: Uncrustify_d-0.71.0_f

Consider this C/C++/D code:

```d
ThisIsTheReturnType thisIsTheFunctionName(string a,
        Doc doc,
        int attributes,
        int asd = someDefault,
        TypeInfo objectType = null) {
    return something;
}

ThisIsTheReturnType var = thisIsTheFunctionName(x,
    y,
    z);
```

It is formatted as I'd want it:

* continued argument lists in function calls are bumped one indent level
* continued parameters in function definitions are bumped two indent levels

The latter is needed so as to distinguish the continued parameter list from the actual body of the function, while preserving the convention that `{` does not go on its own line.

I don't seem to find a way to make this work. The option `indent_param` applies to both definitions and calls. The options `indent_func_call_param` and `indent_func_def_param` are Boolean offering the choice between "align by indenting" or "align at paren". And `indent_func_param_double` offers doubling of the indent for continued lists, but applies to both definition and call. Far as I can tell there is no combinations of these to format the code as desired.

(Not trying to also prescribe a half-baked solution, but off the top of my head one possibility would be to allow numbers for `indent_func_call_param`, `indent_func_def_param` etc to mean how many columns to indent.)

**Comment by guy-maurel** [comment]
I miss your configuration file and the expected output.
Please push.
