### ISSUE TITLE
mod_add_long_namespace_closebrace_comment only adds a comment that goes two namespaces deep

### ISSUE THREAD

**Issue by HornedGod8** [uncrustify/uncrustify#2823]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

[namespacedebug.txt](https://github.com/uncrustify/uncrustify/files/4800842/namespacedebug.txt)

[NamespaceTest.zip](https://github.com/uncrustify/uncrustify/files/4800849/NamespaceTest.zip)

Tested with 0.71.0_f
Only non-default option set is:
mod_add_long_namespace_closebrace_comment = 1

cpp code to be formatted:

namespace farm::animal::chicken::leg
{
}

Current uncrustify output:

namespace farm::animal::chicken::leg
{
} // namespace farm::animal

Expected uncrustify output:

namespace farm::animal::chicken::leg
{
} // namespace farm::animal::chicken::leg

Comment added should have full list of namespaces. If this was five, six, etc. deep, all namespaces should be listed in the comment, not just the first two as is done currently.

**Comment by guy-maurel** [comment]
yes

**Comment by guy-maurel** [comment]
PR #3023 is a bugfix proposal.
Please test it and report.
