### ISSUE TITLE
travis doesn't work!

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#2824]
The travis check doesn't work since some days.
The last working was https://travis-ci.org/github/uncrustify/uncrustify/builds/693600652

Does anybody know what is to do?

**Comment by CDanU** [comment]
It still is doing the work: https://travis-ci.org/github/uncrustify/uncrustify/builds . For some reason the results are not fetched by github.

**Comment by guy-maurel** [comment]
I have got instructions from travis to repair.

**Comment by CDanU** [comment]
Works again.
