### ISSUE TITLE
Missing space when wrapping C-style comments

### ISSUE THREAD

**Issue by ammen99** [uncrustify/uncrustify#2835]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Hi, I encountered a bug in uncrustify's comment wrapping. Here are my settings and how to reproduce:

Settings:
```ini
cmt_width = 30
cmt_star_cont = true
cmt_sp_after_star_cont = 1
```
Unformatted source:
```cpp
/* Short
 * Very long statement, needs wrapping */
```
Formatted source:
```cpp
/* Short
 * Very long statement, needs
 *wrapping */
```
Note the missing space between `*` and `wrapping`.

Also, debug output of uncrustify:
```
# Uncrustify_d-0.71.0-21-d4da2b0f
cmt_width                       = 30
cmt_star_cont                   = true
cmt_sp_after_star_cont          = 1
# option(s) with 'not default' value: 3
#
# -=====-
# number of loops               = 0
# -=====-
# language                      = CPP
# -=====-
# Line                Tag         Parent_type  Type of the parent         Columns Br/Lvl/pp      Flag   Nl  Text
#   1>      COMMENT_MULTI|      COMMENT_WHOLE|     PARENT_NOT_SET[  1/  1/ 42/  0][0/0/0][          0][1-0] /* Short␤ * Very long statement, needs wrapping */
#   2>            NEWLINE|               NONE|     PARENT_NOT_SET[ 42/ 42/  1/  0][0/0/0][          0][1-0]
# -=====-
```

Something I noticed: the bug happens only if the first line is short but the second is long.

**Comment by CDanU** [comment]
Can confirm

**Comment by ammen99** [comment]
Thanks  for the pointer. I have looked around a bit and I am not sure I understand the following line here:
https://github.com/uncrustify/uncrustify/blob/071fe1a16c298cb511a2970e8636129b11bee78b/src/output.cpp#L1074

Seems like `cmt.column` is `1` which I take to mean the very first column. Then, the output position moves to `cmt.column + sp_after_star_cont` which seems wrong (output should advance to column 3, not 2). Without understand much of the code, I'd guess it should be `cmt.column + 1 + (cmt.extra_indent > 0 ? 1 : 0) + sp_after_star_cont`. This is because we have `1` for the `*` and one additional space if `extra_indent` is not zero. What do you think? Is this the correct fix?

**Comment by CDanU** [comment]
I does seem to work I however am uncertain if that is actually correct, our columns start at 0. Test with more involved setups and nests of while/if/case etc.

**Comment by ammen99** [comment]
You are right, this breaks with comments inside functions. I will try to find a proper fix.

**Comment by CDanU** [comment]
`tests/run_format_tests.py -p -e ../build/uncrustify`

**Comment by ammen99** [comment]
I think I finally found out the correct fix for this particular problem, output should be at
```
cmt.column + options::cmt_sp_after_star_cont() + cmt.xtra_indent + cmt.cont_text.size()
```
This actually follows logically from the code: first, the indentation is set to `cmt.column`, then it adds a space if `cmt.xtra_indent` and finally it adds `cont_text`.

That fixes the problem, and I have verified it with a few tests, including comments which are nested inside classes and functions.

However, I have a new problem: formatting the first time with uncrustify runs correctly. The second run however eats an extra space, and **that is also happening without my patch**, so I think it is a completely different bug. Demonstration:

Input:
```
/* Short
 * Very long statement,
 * needs wrapping */

class Test : public Beta
{
    /* Short
     * Very long statement,
     * needs wrapping */
    void func()
    {
        /** Make sure
         * not to break
         * anything */
    }

    /**
     * The quick brown fox
     * jumps over the lazy dog
     */
};
```

Output:
```
/* Short
 * Very long statement,
 * needs wrapping */

class Test: public Beta
{
	/* Short
	 * Very long
	 *statement,
	 * needs wrapping */
	void func()
	{
		/** Make sure
		* not to break
		* anything */
	}

	/**
	 * The quick brown fox
	 * jumps over the lazy
	 *dog
	 */
};
```

This input/output combination is simply with `uncrustify` from master branch without any modifications, and the configuration file in the original message. Can you point me to where to look for the problem for the comment inside `func()`?

**Comment by CDanU** [comment]
Seems to happen here; 
```
1 calculate_comment_body_indent output.cpp     943 
2 output_comment_multi          output.cpp     1540
3 output_text                   output.cpp     640 
4 uncrustify_file               uncrustify.cpp 2192
5 do_source_file                uncrustify.cpp 1489
6 main                          uncrustify.cpp 915 
```

here `cmt.xtra_indent` is set to 1, inside the exceeding line check if block `cmt.cont_text` is `*`

**Comment by ammen99** [comment]
@CDanU Your patch doesn't seem to work, why do you have the `-1`?

Anyway, I debugged a little more about my second problem, so here it is:

I am trying to add a new test with the following code:
```cpp
/* Short
 * Very long statement, needs wrapping */

class Test : public Beta
{
	/* Short
	 * Very long statement, needs wrapping */
	void func()
	{
		/** Make sure
		 * not to break anything */
	}

	/**
	 * The quick brown fox jumps over
	 * the lazy dog
	 */
};
```

With my patch or with your patch without the `-1`, I get the following results:

```cpp
/* Short
 * Very long statement, needs
 * wrapping */

class Test : public Beta
{
/* Short
 * Very long statement, needs
 * wrapping */
void func()
{
	/** Make sure
	 * not to break
	 * anything */
}

/**
 * The quick brown fox jumps
 * over
 * the lazy dog
 */
};
```
However, running `uncrustify` once more on the output produces another file:

```cpp
/* Short
 * Very long statement, needs
 * wrapping */

class Test: public Beta
{
/* Short
 * Very long statement, needs
 * wrapping */
	void func()
	{
		/** Make sure
		* not to break
		* anything */
	}

/**
 * The quick brown fox jumps
 * over
 * the lazy dog
 */
};
```

I followed the functions you mentioned and it seems that here, the option `cmt_multi_check_last` is changing the output the second time. The problem is that the first time, the comment is not wrapped so the lengths of the first and second line are different. However after wrapping (the second run) this changes, so the `cmt_multi_check_last` option kicks in. I think this is not caused by the current patch, right?

**Comment by ammen99** [comment]
> Without looking closer into this I'd say all this `cmt.xtra_indent` handling is superfluous, the cont_text should just be `\ *\ ` as it is with the other cases.

Well I tried removing it but the code breaks - and as you can see, before the space after `*` comes, uncrustify does output both `xtra_indent` and `cmt.cont_text`, so it is needed to add both values together.

**Comment by CDanU** [comment]
My diff is only for using the `cmt_sp_after_star_cont` for the right comments, the problem remains.

I get different results, you should develop on master: uncrustify-0.71.0-46-g071fe1a16

C:
```
cmt_width = 30
cmt_star_cont = true
cmt_sp_after_star_cont = 1
```

I: the one you mentioned above
O1:
```cpp
/* Short
 * Very long statement, needs
 *wrapping */

class Test : public Beta
{
/* Short
 * Very long statement, needs
 *wrapping */
void func()
{
	/** Make sure
	 * not to break
	 *anything */
}

/**
 * The quick brown fox jumps
 *over
 * the lazy dog
 */
};
```

O2:
```cpp
/* Short
 * Very long statement, needs
 * wrapping */

class Test : public Beta
{
/* Short
 * Very long statement, needs
 * wrapping */
void func()
{
	/** Make sure
	 * not to break
	 * anything */
}

/**
 * The quick brown fox jumps
 * over
 * the lazy dog
 */
};
```

```diff
diff --git 1/tmp/t/formatted.d 2/tmp/t/formatted2.d
index bfb5af610..744e28066 100644
--- 1/tmp/t/formatted.d
+++ 2/tmp/t/formatted2.d
@@ -1,22 +1,22 @@
/* Short
* Very long statement, needs
- *wrapping */
+ * wrapping */

class Test : public Beta
{
/* Short
* Very long statement, needs
- *wrapping */
+ * wrapping */
void func()
{
/** Make sure
* not to break
-        *anything */
+        * anything */
}

/**
* The quick brown fox jumps
- *over
+ * over
* the lazy dog
*/
};
```

**Comment by ammen99** [comment]
I have now updated to master. Have you tried indenting a third time (so indenting your O2)? Because after that point is when I get the new issue.

**Comment by ammen99** [comment]
Oh, I finally realized what the problem was: the option to check the length of the first and last comments was turned on, and this changed the indentation the second time! So it should work now. I'll open a PR.
