### ISSUE TITLE
[D] [dlang] Directive to remove newline ends up actually adding newline

### ISSUE THREAD

**Issue by andralex** [uncrustify/uncrustify#2836]
Version: Uncrustify_d-0.71.0_f

Possibly this applies to other languages as well. Consider:

```d
module x;
static if (1) {{
    int x;
}}
```

Run uncrustify will all defaults, result is:

```d
module x;
static if (1) {{
		       int x;
	       }}
```

Now run again with all defaults save for this one: `nl_if_brace = remove`. So the expectation is for the output to not change because there was no newline between `if` and `{` in the first place. The output has two newlines added:

```d
module x;
static if (1) {
	{
		int x;
	}
}
```

Thanks for your consideration!

**Comment by CDanU** [comment]
Hmm what would you expect to happen with: 

```d
module x;
static if (1) 
{{
    int x;
}}
```
 and `nl_if_brace = remove`?

**Comment by guy-maurel** [comment]
PR #3030 is a bugfix proposal.
Please test it and report.
