### ISSUE TITLE
Segmentation fault in uncrustify 0.70.0-0.71.0

### ISSUE THREAD

**Issue by silkeh** [uncrustify/uncrustify#2845]
In uncrustify 0.70.1 and 0.71.0 (and master) I get a segmentation fault with the attached config and header file:

```
$ uncrustify -c uncrustify-riot.cfg cmsis_armcc.h 
Output suffix: .uncrustify
Parsing: cmsis_armcc.h as language C-Header
fish: 'uncrustify -c uncrustify-riot.c…' terminated by signal SIGSEGV (Address boundary error)
```

A `git bisect` found that the issue was introduced in https://github.com/uncrustify/uncrustify/commit/4ddd7f48e016f512dacb87256aeb4ceedb521cd7

[uncrustify-segfault.zip](https://github.com/uncrustify/uncrustify/files/4873959/uncrustify-segfault.zip)

**Comment by guy-maurel** [comment]
I can reproduce

**Comment by gmaurel** [comment]
Thanks for the message.
PR #2850  is a bugfix proposal.
Please test it and report.
