### ISSUE TITLE
Unstable formatting of comments when wrapping

### ISSUE THREAD

**Issue by ammen99** [uncrustify/uncrustify#2848]
This was discovered while working on #2847, but happens on `master` branch also **without** the linked PR.

Config file:
```
cmt_width = 30
cmt_star_cont = true
cmt_sp_after_star_cont = 1
```

Input file:
```
/* Short
 * Very long statement, needs wrapping */

class Test : public Beta
{
	/* Short
	 * Very long statement, needs wrapping */
	void func()
	{
		/** Make sure
		 * not to break anything */
	}

	/**
	 * The quick brown fox jumps over
	 * the lazy dog
	 */
};
```
Behavior: on commit 071fe1a16c298cb511a2970e8636129b11bee78b (master as of today), running uncrustify 3 times on the given input (and then on the output of previous run) gives 3 different results.

With the fixes in #2847, the output stabilizes after only 2 consecutive runs (but is still unstable).

**Comment by guy-maurel** [comment]
The current git source needs two runs, is stable.

**Comment by guy-maurel** [comment]
Anything new?

**Comment by ammen99** [comment]
It seems that with the latest master, it stabilizes after the second run:

After first run:

<details>

```cpp
/* Short
 * Very long statement, needs
 * wrapping */

class Test : public Beta
{
/* Short
 * Very long statement, needs
 * wrapping */
void func()
{
	/** Make sure
	 * not to break
	 * anything */
}

/**
 * The quick brown fox jumps
 * over
 * the lazy dog
 */
};
```
</details>

After second run:

<details>

```cpp
/* Short
 * Very long statement, needs
 * wrapping */

class Test : public Beta
{
/* Short
 * Very long statement, needs
 * wrapping */
void func()
{
	/** Make sure
	* not to break
	* anything */
}

/**
 * The quick brown fox jumps
 * over
 * the lazy dog
 */
};
```
</details>

Running uncrustify a third time does not change anything. However, the output after running uncrustify 2 times (and on subsequent runs) is wrong - notice that the comment inside `func()` does not have properly aligned `*` on the continued lines.

**Comment by micheleCTDE** [comment]
I also experience similar issues with spacing and indentation when running uncrustify a few times. After the third run it seems to stabilize (in my test repo) but it is not unusual that comments are in funny places.

As a side note, perhaps uncrustify should aim at having a stable format in one simgle pass, without hte need to have multiple re-runs. I guess this amy require some major rework though.
