### ISSUE TITLE
Problem with align_keep_extra_space

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2859]
```
# Uncrustify-0.71.0

align_assign_span      = 1
align_func_params      = true
align_keep_extra_space = true
```

Input (no changes were expected)
```
void MyFunction( int    a = 0,
                 double b = 0.0 );
```

Output 
```
void MyFunction( int    a    = 0,
                 double b    = 0.0 );
```

Output (second run)
```
void MyFunction( int    a       = 0,
                 double b       = 0.0 );
```

Every time you format this portion of code, the two "=" will shift 3 characters to the right.

**Comment by guy-maurel** [comment]
You need to use the option:
`sp_assign  = force`

**Comment by chris-mich** [comment]
Let's try this!

```
# Uncrustify-0.71.0

align_assign_span      = 1
align_func_params      = true
align_keep_extra_space = true
sp_assign              = force
```
Input (still no changes were expected)

```
void MyFunction( int    a = 0,
                 double b = 0.0 );
```
Output

```
void MyFunction( int    a    = 0,
                 double b    = 0.0 );
```
Output (second run)

```
void MyFunction( int    a    = 0,
                 double b    = 0.0 );
```
Better, but there are still extra spaces added...

**Comment by guy-maurel** [comment]
why do you use the option
 ` align_keep_extra_space = true`

**Comment by chris-mich** [comment]
To keep alignments that were made manually by the developer.  For example:

```
    CallFunction1( aaaa,  bbbbb,   ccccc );      // Without align_keep_extra_space, spaces will be removed
    CallFunction2( aaaaa, bbbbbbb, ccccccc );
```

**Comment by guy-maurel** [comment]
may I close?

**Comment by chris-mich** [comment]
It is still an issue.  The parameter is called "align_**keep**_extra_space" but it is **adding** extra spaces for no apparent reason...

**Comment by chris-mich** [comment]
Still a problem with version 0.75

**Comment by guy-maurel** [comment]
PR #4287 is a bug fix proposal.
Please test it and report.
