### ISSUE TITLE
Set priority for Kate Highlighting file

### ISSUE THREAD

**Issue by drizt** [uncrustify/uncrustify#2864]
Kate contains a number `*.cfg` formats. So on opening `uncrustify.cfg` it chooses wrong format. For example my Qt Creator shows such  available formats **Nagios**, **Uncrustify Configuration**, **Wesnoth Markup Language**, **Cubescript**, **Quake Script** and **Xonotic Script**. [uncrustify.xml.in](https://github.com/uncrustify/uncrustify/blob/master/etc/uncrustify.xml.in#L3) contains file list in `extensions` attribute. Problem can be fixed with adding `priority="10"` to `language` tag.

**Comment by CDanU** [comment]
That approach seems rather highly problematic. Will this end um in a race for which format has the highest priority? Who's to tell that our config file format is more important than other ones? 

Looking at the extensions attribute however it seems that we are only targeting exactly those file names and not only `cfg`, if that is correct we can indeed set the priority value without messing up any other formatting file. 

Why 10 however? What does that value represent?

**Comment by drizt** [comment]
Any number greater than 0 will be ok. Many Kate highlight files use 5, some 10 or 15.

**Comment by CDanU** [comment]
Sounds good, make a PR.
