### ISSUE TITLE
Prevent newline before close curly brace

### ISSUE THREAD

**Issue by drizt** [uncrustify/uncrustify#2868]
In some cases I don't want to have always newline before `}`. I tried to find a way to disable it but seems it's impossible.

For example such code always will be formated.
```c++
void func()
{
    {
        int a; /* code will be splitted here */ }
}
```
How to disable it?

**Comment by CDanU** [comment]
ref: #2836

**Comment by guy-maurel** [comment]
How do you make a difference betwen the two closing braces in your example? Use
uncrustify ... -p p.txt
to see:
```.txt
#   5>        BRACE_CLOSE|               NONE|     PARENT_NOT_SET[  9/ 49/ 50/  1][1/1/0][  200000000][0-0]         }
#   5>            NEWLINE|               NONE|     PARENT_NOT_SET[ 10/ 50/  1/  0][1/1/0][          0][1-0]
#   6>        BRACE_CLOSE|           FUNC_DEF|     PARENT_NOT_SET[  1/  1/  2/  0][0/0/0][  200000000][0-0] }
```
Do you wanted it at all the places?

**Comment by drizt** [comment]
In my personal case I want to have

``` c++
switch (a) {
    case 1: {
        int b;
        break; }
}
```

**Comment by guy-maurel** [comment]
and what do you wanted to get for the other closing braces?
