### ISSUE TITLE
Fight between sp_bool and sp_before_byref

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2879]
```
# Uncrustify-0.71.0
sp_bool         = add
sp_before_byref = remove
```
Input
```
void f()
{
	CObject obj( b && c, b && c );
}
```

Output (no changes were expected)
```
void f()
{
	CObject obj( b && c, b&& c );
}
```

Here I am constructing a CObject with two boolean expressions.  Notice the missing space after the second "b".

**Comment by guy-maurel** [comment]
PR #2900 is a bugfix proposal.
Please test it and report.

**Comment by chris-mich** [comment]
It works in version 0.73, thank you!!
