### ISSUE TITLE
Template not recognized, interpreted as compare operators

### ISSUE THREAD

**Issue by TeoMan** [uncrustify/uncrustify#2886]
⬇️Input:
    int MyClass::MyFunction(std::vector&lt;MyType&gt; aValues)
    {
        std::vector&lt;MyType&gt; aValues2;
    }

✅Expected Output:
    int MyClass::MyFunction(std::vector&lt;MyType&gt; aValues)
    {
        std::vector&lt;MyType&gt; aValues2;
    }

❌Actual Output:
    int MyClass::MyFunction(std::vector &lt; MyType &gt; aValues)
    {
        std::vector &lt; MyType &gt; aValues2;
    }

⚙️Config options used:
sp_compare = true

Unwanted spaces on < and >
no other option influences this behaviour
Version 0.71.0

**Comment by JodiTheTigger** [comment]
This is also affecting my codebase as well:
```
$ uncrustify --version
Uncrustify-0.71.0_f
```

```
sp_compare = true
```

input:
```cpp
ValuePrimaryKey<int64_t, Schema, ColumnId{0}> id = { kTableName, kColumnNameId };
```

**output expected unchanged** however the output is incorrectly this:
```cpp
ValuePrimaryKey < int64_t, Schema, ColumnId{0} > id = { kTableName, kColumnNameId };
```

**Comment by guy-maurel** [comment]
@JodiTheTigger :  can you push a little bit more code, I want to compile your example.

**Comment by JodiTheTigger** [comment]
Hello, I've got a few examples, it only seems to happen if a template parameter has `{}` in it 
```cpp
// has a problem
ValuePrimaryKey<int64_t, Schema, ColumnId{0}> id = { kTableName, kColumnNameId };

// doesn't have a problem
ValuePrimaryKey<int64_t, Schema, ColumnId> id = { kTableName, kColumnNameId };
```

Anyway, here are a few code snippets from our codebase with the problem:
```cpp
	Value<std::string, Schema, ColumnId{ 2 }> path = {
		kTableName,
		kColumnNamePath,
	};
	Value<int32_t, Schema, ColumnId{ 3 }> trackCount = {
		kTableName,
		kColumnNameTrackCount,
	};
	Value<int64_t, Schema, ColumnId{ 4 }> thingListId = {
		kTableName,
		kColumnNameThingId,
		withOutIndex,
		{
			"C_NAME_UNIQUE_FOR_PARENT",
			"C_NEXT_LIST_ID_UNIQUE_FOR_PARENT"
		}
	};


	ValuePrimaryKeyForeignKey<int64_t, ThingClass, Schema, ColumnId{ 0 }> id = {
		kTableName,
		kColumnNameId,
		ThingClass::kTableName,
		ThingClass::kColumnNameId,
		onDeleteCascade,
		onUpdateCascade,
	};
	ValuePrimaryKey<int64_t, Schema, ColumnId{ 1 }> prevId = {
		kTableName,
		kColumnNamePrevId,
		withoutIndex,
		descending,
		notAutogenerated,
		notNull,
		{ "K_" + kColumnNamePrevId }
	};

	// this is fine
	std::unordered_map<std::string, commandtype> map = {
		{"get-max",      parse_max_things},
		{"get-things",   parse_get_things},
	};
```

**Comment by guy-maurel** [comment]
PR #3088 is a bugfix proposal.
Please test it and report.

**Comment by JodiTheTigger** [comment]
Note: This fixes the issue for me. Thanks!
