### ISSUE TITLE
Unexpected behaviour of indent_member_single

### ISSUE THREAD

**Issue by Astiolo** [uncrustify/uncrustify#2890]
I would expect that indent_member_single = true would mean new lines with '.' or '->' would have exactly one indent more than the initial line. I use tabs for indentation, spaces for alignement (indent_with_tabs = 1). However, it will change all the indentation of those lines to spaces and looks like it will either align to the start of the initial object or one indent (whichever is larger):
```
void Resp::function()
{
	auto response = ResponseBuilder(request)
                    .setStatus(status)
                    .finish();

	ResponseBuilder(request)
        .setStatus(status)
        .finish();

	return ResponseBuilder(request)
           .setStatus(status)
           .finish();
}
```
(I have tab spacing of 4, while it's displaying as 8 here)
With it set to false, I get one tab, then spaces to align matching the indent_member (4) after the start of the class which seems reasonable:
```
void Resp::function()
{
	auto response = ResponseBuilder(m_request)
	                    .setStatus(status)
	                    .finish();

	ResponseBuilder(m_request)
	    .setStatus(status)
	    .finish();

	return ResponseBuilder(m_request)
	           .setStatus(status)
	           .finish();
}
```
I would have expected the result with indent_member_single = true to be:
```
void Resp::function()
{
	auto response = ResponseBuilder(request)
		.setStatus(status)
		.finish();

	ResponseBuilder(m_request)
		.setStatus(status)
		.finish();

	return ResponseBuilder(m_request)
		.setStatus(status)
		.finish();
}
```
(Two tabs for indentation on each of the lines beginning with '.')

**Comment by guy-maurel** [comment]
Could you please push a more complete source, with all declarations.
I want to compile it.

**Comment by Astiolo** [comment]
Here's an example that should compile
```
#include <iostream>
#include <sstream>
#include <string>

struct StringBuilder
{
	template <typename T>
	StringBuilder& append(const T& thing)
	{
		ss << thing;
		return *this;
	}
	std::string build()
	{
		return ss.str();
	}
	std::stringstream ss;
};

int main()
{
	std::string myString = StringBuilder()
		.append(7)
		.append(" + ")
		.append(21)
		.append(" = ")
		.append(7 + 21)
		.build();

	std::cout << myString << std::endl;
}
```

**Comment by Astiolo** [comment]
It's looking better. But, I do see an issue where it inserts spaces for the extra indent when using indent_with_tabs = 1.

With function arguments on multiple lines and indent_func_call_param = true, it inserts tabs. So, I would expect it to do the same for these member functions.

**Comment by Astiolo** [comment]
I see you've closed it without any other changes. Am I wrong to assume it should insert tabs when indent_with_tabs = 1?

**Comment by gmaurel** [comment]
Sorry. I cannot see the problem. Can you point to it with more details?

**Comment by Astiolo** [comment]
Sorry it took me so long to get back to you (it looks like you've been working on it in the meantime anyway). 

I think my concern is best captured in this image:
![Screenshot_20201002_140749](https://user-images.githubusercontent.com/8357652/94888611-d4771680-04b8-11eb-908f-e75cd9eb780e.png)

Where you can see spaces have been inserted when there's new lines between member functions, but it has used tabs when there's new lines between function variables.

I would expect both of these to use tabs, considering indent_with_tabs is set to 1.

**Comment by guy-maurel** [comment]
You need to use the option:
 ` indent_with_tabs = 2`

**Comment by Astiolo** [comment]
If I do that then it will use tabs, even for alignment. I need to have a configuration that allows different tab sizes. I expect indent_with_tabs = 1 to use tabs if something is indented, but spaces if it's being aligned with something. In this case I just want the single indent, so I expect it to be a tab.

If it did use tabs then it would also be more consistent with the indent_func_call_param option as I showed in that image.

It's a minor issue, but I do think the current behavior is incorrect.

**Comment by guy-maurel** [comment]
_I need to have a configuration that allows different tab sizes._ 
uncrustify doesn't support more than ONE tab size.

**Comment by Astiolo** [comment]
> uncrustify doesn't support more than ONE tab size.

If you're consistent with the use of tabs for indentation and spaces for alignment. Then it should all work out no matter how big the tabs are set to in your editor. With the obvious exception of alignment across different levels of indentation, but that's unavoidable. 

However that's really a moot point for this issue. If you've set it to use tabs for indentation then when it's indenting it should use tabs and not spaces.

Having said all that, I've stopped using uncrusitfy so this doesn't impact me anymore.

**Comment by guy-maurel** [comment]
Sorry, I might have not understand your message.
Let me correct my comment:
uncrustify doesn't support more than ONE tab size at ONE time with ONE configuration file.
You choose yourself the value you wanted to have.
Let us make a new try.
