### ISSUE TITLE
Feature: Timeout for uncrustify

### ISSUE THREAD

**Issue by zachriggle** [uncrustify/uncrustify#2893]
Occasionally, a very "interestingly" formatted file may get Uncrustify into a loop.

It would be nice to be able to configure uncrustify to terminate formatting the current file (and exit, or move on to the next file if possible).

Something like `$ uncrustify -c cfg --timeout 10 foo.c` would cause uncrustify to exit if it could not complete processing in 10 seconds.  An easy way to do this is with `alarm(3)`.

**Comment by guy-maurel** [comment]
Thanks for the request.
PR #2899  is a proposal.
Please test it and report.

**Comment by zachriggle** [comment]
I saw the PR, it looks like there is now a `debug_timeout` option, is that right?
