### ISSUE TITLE
How to double-indent before access specifier?

### ISSUE THREAD

**Issue by mwoehlke** [uncrustify/uncrustify#2909]
I would like this output:
```c++
class Foo : QObject
{
    Q_OBJECT

  public:
    Foo();
};
```

There doesn't seem to be any way to get this presently? Should this _always_ be the output with both access specifiers and contents thereof indented, or should it get an option?

**Comment by guy-maurel** [comment]
I use:
```.cfg
indent_columns     = 4
indent_with_tabs   = 0
indent_class       = true
indent_access_spec = 3
```
