### ISSUE TITLE
Please, have a look to the option sp_after_type

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#2912]
We can see the doc:
  `Add or remove space between type and word.`
I think, it is not possible to remove the space between type and word.
If we have:
 ` int a;`
It would become:
 ` inta;`
This is something else!
The only test with this option is:
 ` cpp.test:34307`
with the source:
  `using Foo = std::function<void (const bool)>;`
The option works after the type void. The next token **is not** a word!
The portion code from space.cpp:2609
```.cpp
   if (  !chunk_is_token(second, CT_PTR_TYPE)
      && (chunk_is_token(first, CT_QUALIFIER) || chunk_is_token(first, CT_TYPE)))
   {
      // Add or remove space between type and word.
      iarf_e arg = options::sp_after_type();
      log_rule("sp_after_type");
      return(arg);
   }
```
which don't take care of the second token.

Any comment?

**Comment by mwoehlke-kitware** [comment]
This only pops up in somewhat esoteric situations; see for example tests cpp:31630 and cpp:31631 (also #1916/#1921), and more importantly, tests cpp:31597 and cpp:34307. The former deal with cases such as `decltype(...)<here>word`, the latter with `TemplateType<void<here>(...args...)>` and `result function(type<here>(&array)[size])`.

That said:
-  `decltype(...)<here>word` is also handled by the more specific `sp_after_decltype`, falling back to `sp_after_type`. Possibly the fallback could be removed.
- `result function(type<here>(&array)[size])` is in fact controlling space "after a type", but *not* "between type and word"; the option documentation is poor.
- `TemplateType<void<here>(...args...)>` appears to parse (presumably, incorrectly) the argument list as `CT_CPP_CAST`, but again is in fact controlling space "after a type", but again *not* "between type and word".

So, it looks like the option itself is okay, but the documentation is wrong.

Suggestion:
```diff
-// Add or remove space between type and word.
+// Add or remove space after a type in situations not covered by other options.
+// For example, between the return type and parenthesis of a function type
+// template argument, between the type and parenthesis of an array parameter,
+// or between 'decltype(...)' and the following word.
 extern Option<iarf_e>
 sp_after_type; // = IARF_FORCE
 
 // Add or remove space between 'decltype(...)' and word.
+//
+// Overrides sp_after_type.
 extern Option<iarf_e>
 sp_after_decltype;
```

**Comment by guy-maurel** [comment]
looks fine
do you make a PR ?
