### ISSUE TITLE
nl_func_call_start_multi_line also applies to comments

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2914]
```
# Uncrustify-0.71.0
nl_func_call_start_multi_line = true
nl_func_call_args_multi_line  = true
```

Input
```
void f()
{
    CallFunction( //-V556: Warning disabled because blablabla
        param1,	
        param2 );
}
```

Output (no changes were expected)
```
void f()
{
     CallFunction( 
          //-V556: Warning disabled because blablabla
          param1,	
          param2 );
}
```

I fully understand why Uncrustify behaves like this.  Let me explain why this is a problem for us.  
We use PVS-Studio for static code analysis.  

I the above example, PVS issues a warning at the line were "CallFunction" is invoked.  Let's say it's line # 134.
In some cases, we want to ignore the warning (false positives for example).  The way to do this is to add a comment where the warning happens, like in my input example.

When Uncrustify formats this code, the comment moves to the next line... # 135.  Result:  PVS doesn't "see" our comment anymore.  

This is our workaround for the moment:

```
void f()
{
     CallFunction( param1, param2 );     //-V556: Warning disabled because blablabla
}
```

This works, but not ideal in case param1 and param2 are very long expressions (and this is why we use nl_func_call_start_multi_line and nl_func_call_args_multi_line )

Conclusion:  I am not sure that nl_func_call_start_multi_line should apply to comments...

**Comment by guy-maurel** [comment]
Il  vous faut utiliser l'option:
 ` nl_func_call_start = remove`

**Comment by chris-mich** [comment]
This is only a patch for this particular problem.  It has a big side-effect:

Input

```
void f()
{
    CallFunction(
        param1,	
        param2 );
}
```

Output (we don't want Uncrustify to change this)

```
void f()
{
     CallFunction(param1,	
                  param2 );
}
```

**Comment by guy-maurel** [comment]
Sorry, I don't see the problem.
Please, push a bigger example with input, output and expected files.

**Comment by chris-mich** [comment]
En français alors?

Si je résume simplement, c'est que **nl_func_call_start_multi_line** ajoute un \n aux **commentaires**, alors que ce ne sont pas vraiment des arguments.
Je ne sais pas si c'est voulu; ça me semble louche.  Voir mon exemple dans mon intervention initiale.

**Comment by chris-mich** [comment]
I am not suggesting a new option, but maybe change the current behavior.
It depends if you think that this "issue" is "by design" (you designed it to work this way) or not (either a bug, or nobody thought about this particular case before).

**Comment by guy-maurel** [comment]
I don't want to change the current behavior.
I prefer a new option.
