### ISSUE TITLE
Why was HOW_MANY_AS reduced from 16 to 8?

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#2921]
Back in https://github.com/uncrustify/uncrustify/pull/2761/commits/daba096dcfa63e8d0f155d0db3cd43d9bcee8443 HOW_MANY_AS was changed from 16 to 8. Any particular reason for this?

I of course have some code with exceed this, and get the following:
align_func_param(112): Not enought memory for Stack
align_func_param(114): the current maximum is 8

I have temporarily changed it back to 16, seemingly with no bad effects.
Perhaps is ought to be made a configuration parameter?

**Comment by gmaurel** [comment]
I have used the new value!
I will restore the old value.

**Comment by guy-maurel** [comment]
PR #2935 is a bugfix proposal.
Please test it and report.

**Comment by guy-maurel** [comment]
Can you push your example?

**Comment by arneforlie** [comment]
The test case and the config file are attached.
[test.zip](https://github.com/uncrustify/uncrustify/files/5278660/test.zip)
