### ISSUE TITLE
Configuration align_assign_span is no longer respected

### ISSUE THREAD

**Issue by byron-hawkins** [uncrustify/uncrustify#2926]
Configuration:

    77 align_assign_span                        = 0
    178 align_assign_function_proto_span         = 0
    179 align_assign_decl_func                   = 0
    180 align_assign_thresh                      = 12

Result:

     188                                                                                                                                              
     189     uint64_t available_edge_count          = d->vertex_count * (tree->g->profile.vertex_count - 1);                                          
     190     double edge_density = ratio(free_edge_count, available_edge_count);                                                                      
     191     double relative_size = ratio(d->vertex_count, tree->g->profile.vertex_count);                                                            
     192                                                                                      

Problem:

There should be no indentation of the assignment to `available_edge_count` (it is aligned to a similar assignment occurring above). The configuration seems very clear to me, and this has never been a problem before. So I don't see any reason why uncrustify has started to align these in the latest git clone (built fresh last week).

**Comment by guy-maurel** [comment]
Sorry, I don't understand the question.
Please push yiur input, your outout and the expected file.

**Comment by byron-hawkins** [comment]
It turns out the alignment of the assignment is (now?) controlled by `align_assign_thresh`, so I just set that to `0` and everything is back to normal.
