### ISSUE TITLE
How to get func and func_def closing paren to not be indented

### ISSUE THREAD

**Issue by zachriggle** [uncrustify/uncrustify#2930]
I would like to make the following transformation with Uncrustify.  It's for silly reasons but this is the format I need (ran into a Sublime Text bug!)

## Input

```c
int main(int argc, char** argv) {
    return 0;
}
```

## Desired Output

```c
int 
main (
    int    argc,
    char **argv
) 
{
    return 0;
}
```

## Current State

I'm somewhat close with the attached configuration, but I end up with the following, which is not quite correct.  What options do I need to do to prevent the `)` from floating in alignment with the parameter names?

```c
int
main (
    int     argc,
    char    ** argv
    ) //<--- Should not be preceded by spaces
{
    return 0;
}

```

My configuration is attached:

[uncrustify.cfg.gz](https://github.com/uncrustify/uncrustify/files/5264092/uncrustify.cfg.gz)

### Version info

```
$ uncrustify --version
Uncrustify-0.71.0_f
```

**Comment by guy-maurel** [comment]
PR #2938 is a proposal.
Please test it and report.
