### ISSUE TITLE
Problem with Apex (Java family) SOQL request with '=' character

### ISSUE THREAD

**Issue by Gachdel** [uncrustify/uncrustify#2933]
Hello,

I am using Uncrustify since a few days with Salesforce Apex language, and after a few customiztion, it really works well (with a high performance level).
However, I have one last big problem that I cannot solve, and I wonder if this is possible to solve.

The problem is reproduced on SOQL requests (wrapped in [ ]) that contains at least one '=' character (so almost every SOQL query...).
The line next after the one with '=' is then indented as you can see in my samples.

Would you have a solution to fix this?
Thanks for your help!

PS: Sorry I was unable to generate a debug file, this is triggering errors, so I've included my uncrustify.cfg file. I hope it will be OK.

[uncrustify.cfg](https://gist.github.com/Gachdel/604346d7073603761cdc611c02f09418)

### Input
```java
public with sharing class testSOQLClass {
    public static List<CampagneArbitrageWrapper> getSuggestionCampagneNortia() {
        Set<Id> supportsDesinvestisEligiblesIds=new Set<Id>();
        Id cabinetUserConnected=UserHelper.getuserConnected().Contact.AccountId;
        //on récupère les Ids des supports éligible pour un cabinet CGP
        for(Allocation__c allocation : [SELECT Support__r.Id, Contrat__c
                                        FROM Allocation__c
                                        WHERE Contrat__r.Apporteur__c = :cabinetUserConnected
                                        AND Contrat__r.Statut__c 'En vie']) {
            supportsDesinvestisEligiblesIds.add(allocation.Support__r.Id);
        }
    }
}
```

### What I'm getting
```java
public with sharing class testSOQLClass {
    public static List<CampagneArbitrageWrapper> getSuggestionCampagneNortia() {
        Set<Id> supportsDesinvestisEligiblesIds = new Set<Id>();
        Id cabinetUserConnected = UserHelper.getuserConnected().Contact.AccountId;
        //on récupère les Ids des supports éligible pour un cabinet CGP
        for(Allocation__c allocation : [SELECT Support__r.Id, Contrat__c
                                        FROM Allocation__c
                                        WHERE Contrat__r.Apporteur__c = :cabinetUserConnected
                                            AND Contrat__r.Statut__c 'En vie']) {
            supportsDesinvestisEligiblesIds.add(allocation.Support__r.Id);
        }
    }
}
```

### Current version
```java
uncrustify -v
Uncrustify-0.70.1_f```

[Expected result](https://gist.github.com/Gachdel/c4f3465ff809ff9f88c9d34c1b599327)
[Generated result](https://gist.github.com/Gachdel/512c6b56771b63f42256f0276355ca51)

**Comment by MarieModis** [comment]
same problem here

**Comment by guy-maurel** [comment]
il vous faut utiliser l'option:
  `indent_off_after_assign = true`

**Comment by Gachdel** [comment]
Merci beaucoup Guy!
Utilisant une version de conf assez ancienne, je n'avais pas cette option.
Après upgrade du fichier, cela apporte effectivement la correction à mon problème 👍 

Encore merci 🥇
