### ISSUE TITLE
Problem with some conditional clause in Objective-C

### ISSUE THREAD

**Issue by flabrie** [uncrustify/uncrustify#294]
This line of code was correctly with uncrustify some months ago:

```
    CABasicAnimation *animation = (anchorPoint.y == 0.5) ? [CABasicAnimation animationWithKeyPath:@"transform.rotation.y"] : [CABasicAnimation animationWithKeyPath:@"transform.rotation.x"];
```

And this:

```
    CAAnimation *openAnimation = (direction < 2) ? [CAKeyframeAnimation animationWithKeyPath : @"position.x" function:openFunction fromValue:self.frame.origin.x + self.frame.size.width / 2 toValue:selfFrame.origin.x + self.frame.size.width / 2] :[CAKeyframeAnimation animationWithKeyPath:@"position.y" function:openFunction fromValue:self.frame.origin.y + self.frame.size.height / 2 toValue:selfFrame.origin.y + self.frame.size.height / 2];
```

_(I know, this is bad code, but it's not mine...)_

But now with the latests version since weeks I get error like this:

_unexpected colon in col 126 n-parent=NONE c-parent=OC_MSG l=1 bl=1_
And
_unexpected colon in col 246 n-parent=NONE c-parent=OC_MSG l=1 bl=1_

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by gmaurel** [comment]
No answer, we close.
