### ISSUE TITLE
Concatenation of adjacent string literals not always formatted correctly

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#2940]
There is a small issue with concatenation of string literals when there are more than one space after assignment operator. The second string will then move to the left so that they are no longer aligned.

Test case
```
void foo()
{
   // When there are two, or more, spaces after =, it is not OK
   const auto x =  "abc" 
                   "xyz";

   // When there is one space after =, it is OK
   const auto x = "abc"
                  "xyz";
}
```

Output:
```
void foo()
{
   // When there are two, or more, spaces after =, it is not OK
   const auto x =  "abc"
                  "xyz";

   // When there is one space after =, it is OK
   const auto x = "abc"
                  "xyz";
}
```
Expected output:
Either identical to input, or "abc" and "xyz" aligned under each other with one space after =

See also [debug.txt](https://github.com/uncrustify/uncrustify/files/5287315/debug.txt)

**Comment by guy-maurel** [comment]
You need to use the option:
  `sp_assign = force`

**Comment by arneforlie** [comment]
Thanks, that solved my issue.
