### ISSUE TITLE
about Func Name And "{" in Obj-C

### ISSUE THREAD

**Issue by TaoCheDev** [uncrustify/uncrustify#2946]
What should I do?   about "{"

\- (BOOL)hiddenTabbarItemView
{
    return YES;
}
To:
\- (BOOL)hiddenTabbarItemView {
   return YES;
}

**Comment by guy-maurel** [comment]
You need to use the option:
 ` nl_oc_mdef_brace = remove`

**Comment by TaoCheDev** [comment]
Thanks
