### ISSUE TITLE
C++: '<' and '>' comparison operator misinterpreted as template

### ISSUE THREAD

**Issue by SoftwareApe** [uncrustify/uncrustify#2949]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."

Relevant config options are:

```ini
# Add or remove space around compare operator '<', '>', '==', etc.
sp_compare                      = force    # ignore/add/remove/force

# Add or remove space before '<'.
sp_before_angle                 = remove   # ignore/add/remove/force

# Add or remove space inside '<' and '>'.
sp_inside_angle                 = remove   # ignore/add/remove/force

# Add or remove space inside '<>'.
sp_inside_angle_empty           = ignore   # ignore/add/remove/force

# Add or remove space between '>' and ':'.
sp_angle_colon                  = ignore   # ignore/add/remove/force

# Add or remove space after '>'.
sp_after_angle                  = ignore   # ignore/add/remove/force

# Add or remove space between '>' and '(' as found in 'new List<byte>(foo);'.
sp_angle_paren                  = remove   # ignore/add/remove/force

# Add or remove space between '>' and '()' as found in 'new List<byte>();'.
sp_angle_paren_empty            = ignore   # ignore/add/remove/force

# Add or remove space between '>' and a word as in 'List<byte> m;' or
# 'template <typename T> static ...'.
sp_angle_word                   = ignore   # ignore/add/remove/force

# Add or remove space between '>' and '>' in '>>' (template stuff).
#
# Default: add
sp_angle_shift                  = remove   # ignore/add/remove/force

# (C++11) Permit removal of the space between '>>' in 'foo<bar<int> >'. Note
# that sp_angle_shift cannot remove the space without this option.
sp_permit_cpp11_shift           = true     # true/false
````

debug log output:

```log
Debug: config file: /home/user/.uncrustify
Debug: launched: uncrustify -l CPP -c /home/user/.uncrustify --replace --no-backup /home/user/uncrustify_bug.cpp
Debug: uncrustify exited with status: 0
Debug: uncrustify exited with error: Parsing: /home/user/uncrustify_bug.cpp as language CPP
```

[//]: # "  • include a small but complete test file that will be uncrustifyed"

test file

```c++
int index = -1;

int main(void)
{
    const int x = 2;
    int y = index < -x ? 1 : index > x ? 2 : 0;
}
```

[//]: # "  • include the generated results"

```c++
int index = -1;

int main(void)
{
    const int x = 2;
    int y = index<-x ? 1 : index> x ? 2 : 0;
}
```

[//]: # "  • include the expected results"

expected to leave the file alone.
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"

Uncrustify-0.71.0

[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Don't know about a version that worked

**Comment by SoftwareApe** [comment]
I say misiniterpreted as template, because it looks very much like uncrustify applies the template rules to these comparison operators. Especially since turning around the operators (first > then <) doesn't cause this error.

**Comment by gmaurel** [comment]
PR #2952 is a bugfix proposal.
Please test it and report.

**Comment by SoftwareApe** [comment]
Thankyou @guy-maurel for such a quick fix. I tried it and it works!
