### ISSUE TITLE
Non-free image project-support.jpg

### ISSUE THREAD

**Issue by smlx** [uncrustify/uncrustify#295]
I'm just forwarding this debian bug upstream: 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=753760

It refers to `documentation/htdocs/project-support.jpg`.

I notice that there's another image in `documentation/htdocs/images/linuxlinks.gif`, I'm not sure if that's free or not.

Thanks!

**Comment by gmaurel** [comment]
Done
