### ISSUE TITLE
Add newline between '=' and '{'.

### ISSUE THREAD

**Issue by billwatersiii** [uncrustify/uncrustify#2957]
This is the only line in my config file.

```
nl_assign_brace  = add
```

When I run uncrustify on a file containing this code, I expect a newline to be added between the '=' and '{', but that is not the case.  Is this not the right option for adding a newline here?

```
bus_type i2c_bus_type = {
    .name    = "i2c",
    .match   = i2c_device_match,
    .suspend = i2c_bus_suspend,
    .resume  = i2c_bus_resume,
};
```

Version: Uncrustify-0.71.0_f

**Comment by guy-maurel** [comment]
PR #3438 is a bugfix proposal.
Please test it and report.
