### ISSUE TITLE
Incorrect indentation of comments inside nested blocks

### ISSUE THREAD

**Issue by lyahdav** [uncrustify/uncrustify#296]
Here's my uncrustified code:
```
@implementation Foo

- (void)bar {
    [Baz someMethod:^{
        if (var1) {
            void (^someBlock)(id) = ^(id someVar) {
            // some comment
                doStuff();
            };
        } else {
            // some other comment
        }
    }];
}

@end
```

Note the `some comment` line. I expect that comment to get indented the same as the next line. This seems to indent correctly if there aren't two levels of nested blocks. AFAIK the only relevant line in my config is `indent_sing_line_comments = 0`.
I'm on commit 0cdc9750dea4cea8a7db43287707b7c9f264b967 (top of master), which is after the latest release 0.60 because that release has other issues.

**Comment by gmaurel** [comment]
The actual git version works pretty fine
`@implementation Foo

- (void)bar {
        [Baz someMethod:^{
                 if (var1) {
                         void (^someBlock)(id) = ^(id someVar) {
                                 // some comment
                                 doStuff();
                         };
                 } else {
                         // some other comment
                 }
         }];
}

@end`

Please test it.
