### ISSUE TITLE
Failing test cli_options with new 0.72.0

### ISSUE THREAD

**Issue by misery** [uncrustify/uncrustify#2976]
I tried to update the package of AlpineLinux. But the new 0.72.0 fails on platform aarch64, armv7, ppc64le and s390x in test cli_options.
Platform x86 and x86_64 works.

https://gitlab.alpinelinux.org/misery/aports/-/pipelines/57667

**Comment by guy-maurel** [comment]
Thanks for the message.
I'll look for and report,

**Comment by guy-maurel** [comment]
Is related to PR #2969 
@parkerjs 
Please have a look to 
[aarch64-a.txt](https://github.com/uncrustify/uncrustify/files/5512079/aarch64-a.txt)
Some OS introduce some <newline>  in the comment, as show  here.
Could you have a look on it?

**Comment by parkerjs** [comment]
So I remember having this issue prior to my pull request. The garbage-looking characters are actually encoded newlines and/or carriage returns. The default behavior is to print these characters in multi-line c-style comments - you'll see this behavior in the debug output file produced by Uncrustify. I attempted to get rid of these garbage characters in the csv output, but apparently it doesn't work on all platforms.

**Comment by parkerjs** [comment]
I can modify output_parsed_csv() to print the non-encoded character strings, but what are the implications of doing so?

**Comment by parkerjs** [comment]
This may fix the problem, but I'm not sure - Unfortunately I'm not able to test the platforms mentioned by @misery.

**Comment by parkerjs** [comment]
I updated the csv output to print the encoded newline characters, just as the traditional debug output file does. My initial attempt was to avoid printing them altogether, but the test I had performed to exclude them is apparently not consistent on all platforms. Therefore, best to just print them. The change should only affect c-style (/* ... */) multi-line comments.

**Comment by misery** [comment]
Thanks... seems the patch fixed it: https://gitlab.alpinelinux.org/misery/aports/-/pipelines/57855

**Comment by gmaurel** [comment]
@misery 
- Do you need a new release 0.72.1 ?
- Is it possible in the future, from time to time, to get a complete test "On Demand",
before I create a new tag/release?
It would be fine.
Thanks

**Comment by misery** [comment]
* No, the patch is enough for me. I will add it to the package.
* Yeah, just ping me and I will trigger a build for you. Or you can register https://gitlab.alpinelinux.org/ - but then you need to know the packaging of Alpine.

**Comment by guy-maurel** [comment]
Es hört sich gut an, danke, ich werde mich melden.
