### ISSUE TITLE
"pc->level is 9. This is too big, at line 2905, column 88. Make a report, please."

### ISSUE THREAD

**Issue by zachriggle** [uncrustify/uncrustify#2984]
When running Uncrustify with the attached configuration against this file (attached): https://opensource.apple.com/source/mDNSResponder/mDNSResponder-171.4/mDNSCore/DNSCommon.c

The following error is generated:

```
$ uncrustify --version
Uncrustify-8392f12

$ uncrustify -p debug.txt -c uncrustify.cfg -f DNSCommon.c
uncrustify.cfg:241: option 'sp_cpp_lambda_paren' is deprecated; use 'sp_cpp_lambda_square_paren' instead
Parsing: DNSCommon.c as language C
align_func_proto(87): pc->level is 9. This is too big, at line 2905, column 88. Make a report, please.
```

If I run with `-L all`, no `debug.txt` file is generated, but there is more output.  It looks like an allocated buffer is too small.

```
Will export parsed data to: debug.txt
Uncrustify-8392f12
config_file = uncrustify.cfg
output_file = null
source_file = DNSCommon.c
source_list = null
tracking    = null
prefix      = null
suffix      = null
assume      = null
replace     = 0
no_backup   = 0
detect      = 0
check       = 0
if_changed  = 0
log_config: the configuration file is: uncrustify.cfg
read_number(481): line_number is 163, option(UNUM) indent_switch_case, ref(UNUM) indent_columns
uncrustify.cfg:241: option 'sp_cpp_lambda_paren' is deprecated; use 'sp_cpp_lambda_square_paren' instead
log_rule(main): rule is 'nl_max'
log_rule(load_header_files): rule is 'cmt_insert_file_header'
log_rule(load_header_files): rule is 'cmt_insert_file_footer'
log_rule(load_header_files): rule is 'cmt_insert_func_header'
log_rule(load_header_files): rule is 'cmt_insert_class_header'
log_rule(load_header_files): rule is 'cmt_insert_oc_msg_header'
load_mem_file: 'DNSCommon.c' encoding looks like UTF-8 (2)
Parsing: DNSCommon.c as language C
log_rule(uncrustify_file): rule is 'utf8_force'
log_rule(uncrustify_file): rule is 'utf8_byte'
log_rule(uncrustify_file): rule is 'utf8_bom'
log_rule(parse_next): rule is 'disable_processing_nl_cont'
parse_comment(630): orig_line is 1, orig_col is 1, pc->text() '/*'
   pc->type is NONE, pc->parent_type is NONE => *type is COMMENT, *parent_type is NONE
parse_comment(662): orig_line is 1, orig_col is 1, pc->text() '/* -*- Mode: C; tab-width: 4 -*-␤'
   pc->type is COMMENT, pc->parent_type is NONE => *type is COMMENT_MULTI, *parent_type is NONE
log_rule(parse_comment): rule is 'disable_processing_cmt'
FATAL(2): The variable 'buf' is not big enought:
   it should be bigger as 8192
Please make a report.
For the buffer: %s(%d): orig_line is %zu, orig_col is %zu, text() '%s', type is %s, orig_col_end is %zu
```

No debug file is actually generated.
[uncrustify-bug.zip](https://github.com/uncrustify/uncrustify/files/5530997/uncrustify-bug.zip)

**Comment by gmaurel** [comment]
Thanks for the message.
I change the maximum of levels to 16, it works, BUT
if trying to generate a log file with the option -L A, we must give more time to compute
with the option **debug_timeout**
I will look for an infinite loop.

**Comment by zachriggle** [comment]
I have debug_timeout set to 10 seconds so that shouldn't have played a huge
role.  It crashed immediately.

**Comment by guy-maurel** [comment]
With a value of 180, I get a log file bigger as 4G.
The PR #2985 solve the first problem.
Please try and report.

**Comment by guy-maurel** [comment]
PR #2987 is a proposal to reduce the logging output.
Please test it and report.

**Comment by zachriggle** [comment]
I still see error messages about maximum level when using uncrustify from

```
$ brew install uncrustify --HEAD
$ uncrustify --version
Uncrustify-6f5e32a
```

**Comment by guy-maurel** [comment]
There are two bugs.
The first one is your comment at the beginning of the file. It as 17750 characters.
This is too big to debug. Please don't use the command line option -L, just now.
I am looking for a solution.

The second problem is caused by a double array where one of the index is too big.
I try to find a solution with <vector>
The question is: can you use uncrustify without -L ?
Please report your experience, thanks.

**Comment by guy-maurel** [comment]
PR #3090 is a proposal to reduce the length of the log file.
Please test it and report.

**Comment by guy-maurel** [comment]
PR #3100  is a bugfix proposal.
Please test it and report.
