### ISSUE TITLE
在格式化OC代码的时候 nl_fdef_brace = remove 失效

### ISSUE THREAD

**Issue by xt-input** [uncrustify/uncrustify#2986]
原始代码：
```
#import <Foundation/Foundation.h>

int main(int argc, char *argv[])
{
    @autoreleasepool {
    }
}
void test()
{
    if () {
    }
}
- (void)test1
{
    if () {
    }
}
```
格式化后输出的结果：
```
#import <Foundation/Foundation.h>

int main(int argc, char *argv[]) {
    @autoreleasepool {
    }
}

void test() {
    if () {
    }
}

- (void)test1
{
    if () {
    }
}
```
应要的结果：
```
#import <Foundation/Foundation.h>

int main(int argc, char *argv[]) {
    @autoreleasepool {
    }
}

void test() {
    if () {
    }
}

- (void)test1 {
    if () {
    }
}
```

以上现象表明在格式化C语言函数的时候该配置是有效的，而OC的函数格式化失效

**Comment by guy-maurel** [comment]
Sorry, we cann't read.
Please, use english everywhere (or french or german, I can)

**Comment by gmaurel** [comment]
No answer, I close

**Comment by mwoehlke-kitware** [comment]
I used https://translate.google.com to translate.

It appears the OP is complaining that `- (void)test1 <no newline here> {` is broken. That may be a valid complaint, however, I have no idea what the syntax `- (void)test1` is supposed to be; apparently it is OC-specific, and I know basically nothing about OC.
