### ISSUE TITLE
Newline after Label?

### ISSUE THREAD

**Issue by schancel** [uncrustify/uncrustify#299]
```D
FOO:
	i++;
```

is being transformed into:
```D
FOO: i++;
```

I'm not sure if this is a bug, or if there's a way to fix it so that it adds a newline and indents `i` properly.

**Comment by schancel** [comment]
I just tried the option in PR #316.  It fixes the mentioned problem, but causes others for D code.

Template specialization in is expressions:
```D
-                               } else static if (is (type: AstExpression)) {
+                               } else static if (is (type:
+                                                     AstExpression)) {
```

Explicit symbol importing:
```D
-               import d.ir.dscope: OverloadSet;
+               import d.ir.dscope:
+                      OverloadSet;
```

**Comment by blakemcbride** [comment]
I too would like to see a nl_after_label option for my C/Java code.

**Comment by gmaurel** [comment]
The actual version works pretty fine.
Please test it!
