### ISSUE TITLE
Issue with formatting files with leading commas

### ISSUE THREAD

**Issue by MattBussing** [uncrustify/uncrustify#2999]
[debug.txt](https://gist.github.com/MattBussing/b835071083d61153568d5509839ece5d)
[test file](https://gist.github.com/MattBussing/91252b7358eeb8a00e0eaae250c131ce)
[expected](https://gist.github.com/MattBussing/dbfb9423a0dbadec6db2673e95b51e6e)
 [generated output](https://gist.github.com/MattBussing/4a5489fcc63f0e4817de6901b373bad4)
 
version: Uncrustify-0.72.0_f

I am trying to get uncrustify to format the function's arguments on new lines with trailing commas. The code base I am running it on has leading commas and results in a weird issue (see the generated output). I am wanting and willing to contribute to adding or fixing uncrustify's functionality. Several questions to figure this out:

1. Is there a config option to fix this?
2. If no, is this a bug that needs to be fixed on one of the config options?
3. If no, does there need to be another config option added to fix this?

Like I said, I am willing to work on this functionality, but I wanted to check before I started working on a fix. This is my first time trying to contribute to an open source project, so let me know if there is anything that I can do better.

**Comment by guy-maurel** [comment]
You need to use the options:
```.cfg
nl_before_member      = remove
nl_after_member       = remove
pos_comma             = trail_force
```

**Comment by MattBussing** [comment]
That fixed my problem with args, but for whatever reason, it is now causing an issue with type definitions (I could be wrong about what they are called). When there is more than one class specified in inside "<>" it adds a newline. For example `myClass<int, int>` will be `myClass<int, \nint>`. See the following files. Thank you for your help!

[testFile.cs](https://gist.github.com/MattBussing/68e091726e33fb1b6c6d766aed65459d)
[testFile.cs.expected](https://gist.github.com/MattBussing/0c4b2534dc49c58e9c74e1f9fefd7100)
[testFile.cs.ouput](https://gist.github.com/MattBussing/042ed40e73a74cebbbda3b02cfaeb38f)
[config](https://gist.github.com/MattBussing/431cc461fa3d9cff779e111047fecbd2)
[debug](https://gist.github.com/MattBussing/44db5806a05aca875b4a2212cea57bd9)

**Comment by guy-maurel** [comment]
you have set the option:
```.cfg
# The position of the comma in wrapped expressions.
pos_comma                       = trail_force
```

**Comment by MattBussing** [comment]
@guy-maurel thank you for your help. This issue is resolved. I created a follow up issue to address my new line concerns. See it here: https://github.com/uncrustify/uncrustify/issues/3003
