### ISSUE TITLE
D language:  newline after struct

### ISSUE THREAD

**Issue by schancel** [uncrustify/uncrustify#300]
In D, structs should not end with a `;`.    uncrustify is thinking items following them are variable decls.

```D
struct SomeStruct {
	int x;
}

int main() {
...
}
```

gets transformed into
```D
struct SomeStruct {
	int x;
} int main() {
...
}
```

**Comment by schancel** [comment]
https://gist.github.com/schancel/c42c34c5fe40fe793578

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
Please test!
