### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by shirl12** [uncrustify/uncrustify#3000]
Hi! 
I am a complete beginner and wanted to learn more about Code Beautifier and uncrustify. I have never done this before and need your help. :)
I have a list of formatting rules that I would like to work through with uncrustify. 
I have thought of 10 formatting rules that I want to follow:

not use /.../ style comments
make labels easy to see
ensure consistens line endings
avoid more than 60 lines in a block
avoid more than 500 to 1000 lines per file
avoid more than 140 character per line
prefer break, continue, and return to deeper nesting
ident to reflect nesting and continuation of statements and declarations
avoid more than three levels of nesting
balance space around braced, bracketed and parenthesized areas
How are these things possible with uncrustify? 
Can you help me please?

Thanks a lot in advance!

Best regards

**Comment by guy-maurel** [comment]
have a look to
```.txt
  <uncrustify>/etc/defaults.cfg
  <uncrustify>/documentation/htdocs
```
to find documentations
Some direct answers:
not use /.../ style comments
  no
make labels easy to see
  what do you mean?
ensure consistens line
   what do you mean?
avoid more than 60 lines in a block
   no
avoid more than 500 to 1000 lines per file
  no
avoid more than 140 character per line
  code_width = 140
prefer break, continue, and return to deeper nesting
  ??
ident to reflect nesting and continuation of statements and declarations
  many indent_xyz are available
avoid more than three levels of nesting
  must be done by the author
balance space around braced, bracketed and parenthesized areas
  only compile able files can be proceded

**Comment by shirl12** [comment]
Hi @gmaurel :)
At first thank you for your answer! 
I would like to comment on this.
So it is not possible to set it to avoid more than 60 lines in a block? Or in a comment line? 

With 'ensure consistent line endings' I mean:
Ensure that they do not end up mixing Unix and Windows line endings. So, let the tool do the work. 

prefer break, continue, and return to deeper nesting

For example a representation like this: 

     p = malloc(sizeof (t_dynamicRecord) ) ; 
     if ( p == NULL ) return; 
     memset (p, 0x3A, sizeof (t_dynamicRecord) ) ; 
     ...
     ...
     ...
     return; 

avoid more than three levels of nesting
How can I change it?



Thank you!

**Comment by gmaurel** [comment]
mixing Unix and Windows line endings;
You may force it:
  newlines=lf|newlines=crlf|newlines=cr|newlines=auto
uncrustify doesn't count the length of a block nor in a comment line
The other questions: NO

**Comment by shirl12** [comment]
Hi gmaurel, 

 

 I want to know if it is possible to process multiple files or whole directories at once. For example, is it possible to process all *.c files from a given directory with one command?

Can I do this with uncrustify?

 

 

Thanks!

Shirley 

 
 

Gesendet: Mittwoch, 02. Dezember 2020 um 15:38 Uhr
Von: "gmaurel" <notifications@github.com>
An: "uncrustify/uncrustify" <uncrustify@noreply.github.com>
Cc: "shirl12" <shirley.breuer@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [uncrustify/uncrustify] I need help (#3000)


 

mixing Unix and Windows line endings;
You may force it:
newlines=lf|newlines=crlf|newlines=cr|newlines=auto
uncrustify doesn't count the length of a block nor in a comment line
The other questions: NO

**Comment by gmaurel** [comment]
Have a look to the line option:
  ` -F FILE      : Read files to process from FILE, one filename per line (- is stdin).`
I prefer a script to do that.

**Comment by shirl12** [comment]
Hi @gmaurel  
what do you mean with a script? How can I do this? 

Thank you for your help!

**Comment by guy-maurel** [comment]
have a look to our test: file tests/run_sources_tests.py
line 27 - 36
it runs a script over all cpp files

**Comment by mwoehlke-kitware** [comment]
> is it possible to process all *.c files from a given directory with one command?

Trivial way:
```
$ uncrustify <options> some/path/*.c
```

Round-about way:
```
$ ls -1 some/path/*.c | uncrustify <options> -F-
```

If you want one process per file:
```
$ for f in some/path/*.c; do uncrustify <options> "$f"; done
```

If you want to process all `*.c` in a directory, recursively:
```
$ find some/path/ -name *.c -print0 | xargs -0 uncrustify <options>
```

If you're on Windows... get a decent shell. You'll be glad you did. (IIRC, [git for Windows](https://git-scm.com/download/win) includes an msys build of bash.)
