### ISSUE TITLE
Incorrect indentation of initializer list when namespaces are involved (C++)

### ISSUE THREAD

**Issue by Timvde** [uncrustify/uncrustify#3010]
Issue: When calling a constructor that has a namespace in the initializer list, it impacts the alignment of the next element in the initializer list.

Version: uncrustify 0.71

Input:
```cpp
namespace SomeLongNamespaceName {
class Foo { };
}

class Bar : SomeLongNamespaceName::Foo {
public:
Bar()
	: SomeLongNamespaceName::Foo(),
	myNumber(3), // <-- this line
	myOtherNumber(5)
{
}
private:
int myNumber;
int myOtherNumber;
};
```

Output:
```cpp
namespace SomeLongNamespaceName {
class Foo { };
}

class Bar : SomeLongNamespaceName::Foo {
public:
Bar()
	: SomeLongNamespaceName::Foo(),
	                         myNumber(3), // <-- this line
	myOtherNumber(5)
{
}
private:
int myNumber;
int myOtherNumber;
};
```

Config: 100% default. When trying to get a minimal working example, I ended up with an empty config file, and I could still reproduce it.

(Edit: made the input match the output format and added a comment so the bug is more visible)

**Comment by guy-maurel** [comment]
PR #3106 is a bugfix proposal.
Please test it and report.
