### ISSUE TITLE
D: template conditionals not handle correctly

### ISSUE THREAD

**Issue by schancel** [uncrustify/uncrustify#302]
```D
class Foo(Bar) if (isInputRange!Bar) {
    decls;
}
alias Foo!someRange FooSome;
```
is indented to:
```D
class Foo(Bar) if (isInputRange!Bar) : Bar {
            decls;
        }
        alias Foo!someRange FooSome;
```

**Comment by schancel** [comment]
Here is the uncrustify.cfg.  Sorry for the huge delay.  I was moving across the country and starting a new job :)

https://gist.github.com/schancel/c42c34c5fe40fe793578

**Comment by gmaurel** [comment]
The actual git version works fine.
Please test it!
