### ISSUE TITLE
empty return incorrectly removed from code 

### ISSUE THREAD

**Issue by micheleCTDE** [uncrustify/uncrustify#3024]
uncrustify 0.71.0_f in debian bullseye.
Attached zip contains two files:
test file: t1.cpp
config file: test.cfg

Step to reproduce:
1. open t1.cpp and search for GetHostByNameThread::processResults (line 316). Observe all cases in the switch inside such function have an empty return;
```
	switch (herrno)
	  {
	  case HOST_NOT_FOUND:
	    results.setError(KResolver::NoName);
	    return;

	  case TRY_AGAIN:
	    results.setError(KResolver::TryAgain);
	    return;

	  case NO_RECOVERY:
	    results.setError(KResolver::NonRecoverable);
	    return;

	  case NO_ADDRESS:
	    results.setError(KResolver::NoName);
	    return;

	  default:
	    results.setError(KResolver::UnknownError);
	    return;
	  }
```

2. Execute: "uncrustify -c test.cfg  t1.cpp --no-backup --replace"

3. Open the file file again (line 342) and note the return after the first case is gone
```
			switch (herrno)
			{
				case HOST_NOT_FOUND:
					results.setError(KResolver::NoName);

				case TRY_AGAIN:
					results.setError(KResolver::TryAgain);
					return;

				case NO_RECOVERY:
					results.setError(KResolver::NonRecoverable);
					return;

				case NO_ADDRESS:
					results.setError(KResolver::NoName);
					return;

				default:
					results.setError(KResolver::UnknownError);
					return;
			}
```

4. Repeating the command more times, will progressively remove one empty return each time.

5. Modify test.cfg and change "mod_remove_empty_return" to false. Repeat the steps above, the problem does not happen.
 

[empty return issue.zip](https://github.com/uncrustify/uncrustify/files/5719247/empty.return.issue.zip)

**Comment by guy-maurel** [comment]
Release 0.72.0 don't have it.
Please try it and report

**Comment by micheleCTDE** [comment]
> Release 0.72.0 don't have it.
> Please try it and report

Downloaded and built 0.72 locally.
Repeated the test and the issue no longer shows up.
Thanks for the prompt feedback.
Issue closed :+1:

**Comment by byron-hawkins** [comment]
This is still a problem in `Uncrustify_d-0.72.0_f` which appears in the latest update of Fedora 35. Kind of a small disaster, really, since it can create tiny bugs that the coder would never imagine could have happened (since the disappearing `return` would be unrelated to any code they were changing).

**Comment by micheleCTDE** [comment]
> This is still a problem in `Uncrustify_d-0.72.0_f` which appears in the latest update of Fedora 35. Kind of a small disaster, really, since it can create tiny bugs that the coder would never imagine could have happened (since the disappearing `return` would be unrelated to any code they were changing).

Hi @byron-hawkins,
can you provide a test case (config and input file)?
