### ISSUE TITLE
First capital cyrillic 'Р' in comments lost

### ISSUE THREAD

**Issue by elnull** [uncrustify/uncrustify#3025]
On current master first capital cyrillic 'Р' in single line comments lost when option `sp_cmt_cpp_start` is set to `force` or `remove`.
`uncrustify.cfg`:
```text
sp_cmt_cpp_start = force
```

`test.cpp`:
```cpp
int a;// Рука
int b;// рука
int c;// Лука
int d;/* Рука */
```

`test.cpp.uncrustify`:
```cpp
int a;// ука
int b;// рука
int c;// Лука
int d;/* Рука */
```

**Comment by guy-maurel** [comment]
PR #3026 is a bugfix proposal.
Please test it and report.

**Comment by elnull** [comment]
It works fine. Thank you.

**Comment by gmaurel** [comment]
wait for the next update...
