### ISSUE TITLE
0.72.0 is moving/removing semicolons in certain circumstances

### ISSUE THREAD

**Issue by gprice1129** [uncrustify/uncrustify#3029]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

[Here](https://gist.github.com/gprice1129/c3d778b6d04ca68067d0ce3ff36b60cc) is a link for what I am seeing. Included is the debug file and an example with original, expected, and actual source code.

Current version: Uncrustify_d-0.72.0_f
Last known working version: Uncrustify_d-0.71.0_f (this version was used to generate the expected.cpp source file)

Also note that if `mod_remove_extra_semicolon=false` is set then instead of the extra semicolon being removed it is moved to the end of the if block. For example:

```
if (x)
  v = {1, 2, 3};
```
Will become:
```
if (x)
{
  v = {1, 2, 3}
};

**Comment by samishchandra** [comment]
Even the `return;` statements are incorrectly removed from the `if` statements. Something like

```
if (flag) {
  // do something
  return; // this statement will be removed by Uncrustify
}
```

**Comment by guy-maurel** [comment]
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!
I use:
Uncrustify_d-0.72.0-91-9a22f5ea

**Comment by gprice1129** [comment]
This bug occurs with the tar.gz of the tagged 0.72.0 version. If it has already been fixed thats great but I did not test it with the most recent source.
