### ISSUE TITLE
eclipse formatter mapping

### ISSUE THREAD

**Issue by avdv** [uncrustify/uncrustify#303]
It would be nice if there was a mapping (ie. import) between the Eclipse JDT formatter prefs to the uncrustify settings so that one could use uncrustify instead of Eclipse (e.g. from the command line).

E.g.

```
org.eclipse.jdt.core.formatter.keep_else_statement_on_same_line=false
```

is probably equivalent to 

```
nl_brace_else = add
```

Eclipse docs are here: http://help.eclipse.org/indigo/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fformatter%2FDefaultCodeFormatterConstants.html

**Comment by gmaurel** [comment]
Do you have the script?
