### ISSUE TITLE
Brace added after C-comment in PP line cause fatal error on second pass

### ISSUE THREAD

**Issue by micheleCTDE** [uncrustify/uncrustify#3034]
uncrustify 0.72.0 + backport of commits 45681e8, 64d93e3.
Files in attachment:

- t1_in.cpp: original test file (subset of a real file, it would fail compilation)
- t1_out_1st_pass.cpp: output of the first execution
- test.cfg: configuration used for the test

Step to reproduce: 
1. run "uncrustify -c test.cfg -f t1_in.cpp -o t1_out_1st_pass.cpp"
2. run "uncrustify -c test.cfg -f t1_out_1st_pass.cpp -o t1_out_2nd_pass.cpp"

Problem:
The first pass adds a brace at the end of 
```
#endif /* NO8BIT */ {
```
This is fine, although not what I expected (setup is an Allman setup, unless I got some options wrong).
The real problem comes on a second pass, which I want to use to verify the formatting is consistent across multiple passes. During the second pass, the following error is generated and uncrustify exits leaving "t1_out_2nd_pass.cpp" empty.
```
Parsing: t1_out_1_pass.cpp as language CPP
parse_cleanup(456): pc->orig_line is 13, orig_col is 1, text() is '}', type is BRACE_CLOSE
parse_cleanup(458): (frm.top().type + 1) is UNKNOWN
parse_cleanup(869): Unmatched BRACE_CLOSE
   orig_line is 13, orig_col is 1
parse_cleanup(876): Try the option
 'tok_split_gte = true'
```
Temporary workaround: removing the /* NO8BIT */ comment after #endif in t1_in.cpp
Additional info: comments at the end of PP lines seems to cause more than one issue. Probably something to look into :smile: 

[faulty_brace.zip](https://github.com/uncrustify/uncrustify/files/5739991/faulty_brace.zip)

**Comment by guy-maurel** [comment]
same comment as #3033

**Comment by guy-maurel** [comment]
PR #3145 is a bugfix proposal.
Please test it and report.

**Comment by micheleCTDE** [comment]
Hi Guy,
yesterday I didn't have enough time to test and report.
I have done my usual tests: PR works fine and I do not see any new regression.
Thanks for the good work!!
