### ISSUE TITLE
Brace incorrectly added after a PP directive

### ISSUE THREAD

**Issue by micheleCTDE** [uncrustify/uncrustify#3040]
This issue is similar to issue #3033 but I am reporting it separately since it shows up on a different config option. I wouldn't be surprised if the root cause is the same as the aforementioned issue.

uncrustify 0.72.0 + backport of commits 45681e88, 64d93e3.
Files in attachment:
- t1_in.cpp: test file (subset of a real file, it would fail compilation :wink: )
- t1_out.cpp: output of the test run
- test.cfg: configuration used for the test

Step to reproduce: run "uncrustify -c test.cfg -f t1_in.cpp -o t1_out.cpp"

uncrustify should add braces around "case" blocks, but when PP directive are presents, it seems to get confused.

Current output:
```
void main()
{
	switch (opcode)
	{
		case LocaleCompare:
		{
			return Number(localeCompare(s, a0.toString(exec)));

#ifndef KJS_PURE_ECMA
		}

		case Big:
		{
			result = String("<big>" + s + "</big>");
			break;
		}
#endif
	}
}
```

Note how the closing brace of the "case LocaleCompare:" block is added after the PP #ifndef instead than before it.

uncrustify does not report any error, but if you try to format the file a second time with "uncrustify -c test.cfg t1_out.cpp", the following errors are reported, which at least is a pointer that somethgin is wrong.
```
Parsing: t1_out_1st_pass.cpp as language CPP
indent_text(3862): size is 2
indent_text(3864): File: t1_out_1st_pass.cpp, open_line is 2, parent is NONE: Unmatched BRACE_OPEN
indent_text(3862): size is 2
indent_text(3864): File: t1_out_1st_pass.cpp, open_line is 2, parent is NONE: Unmatched BRACE_OPEN
```

[wrong_case_brace.zip](https://github.com/uncrustify/uncrustify/files/5756752/wrong_case_brace.zip)

**Comment by guy-maurel** [comment]
This can be solved

**Comment by micheleCTDE** [comment]
Hi Guy,
thanks for working on a fix. It works well in the case of the test case, but it introduces a regression. See attachment for a test case.
Files in attachment:
- t2_in.cpp: test file, with original issue and new code to show regression
- t2_out_nofix.cpp: output of the test run using uncrustify 0.72.0 + backport of commits 45681e8, 64d93e3.
- t2_out_with_fix.cpp: output of the test run using uncrustify 0.72.0 + backport of commits 45681e8, 64d93e3 + fix proposed in PR 3043 (commit 5f3f392a).
- test.cfg: configuration used for the test

Step to reproduce: 
1. without the fix in commit 5f3f392a, run "uncrustify -c test.cfg -f t2_in.cpp -o t2_out_nofix.cpp"
2. with the fix in commit 5f3f392a, run "uncrustify -c test.cfg -f t2_in.cpp -o t2_out_with_fix.cpp"

The original problem reported in this issue is fixed but the closing bracket of the "case (MIDI_NOTEON):" block is now placed in the wrong place.

- without the fix
```
    case (MIDI_NOTEON):
    {
      [ ... omissis ]

#ifdef TRACKDEBUG2
      [ ... omissis ]
#endif
      break;
    }                        <<<<----- Correctly placed
```

- with the fix
```
    case (MIDI_NOTEON):
    {
      [ ... omissis ]

#ifdef TRACKDEBUG2
      [ ... omissis ]
    }                        <<<<----- Wrongly placed
#endif
      break;
```

[issue_3040_regression.zip](https://github.com/uncrustify/uncrustify/files/5761284/issue_3040_regression.zip)

**Comment by guy-maurel** [comment]
Thank for the test data!
On which project are you using uncrustify?

**Comment by guy-maurel** [comment]
Please, test the current version and report.

**Comment by micheleCTDE** [comment]
> Please, test the current version and report.

Thanks Guy, the new fix works fine and I have not observed any particular regression in a small sample of 3200+ files.

Just FYI, this fix has highlighted another problem that was already there before but that I had not yet come to observe. I will file a separate issue for that later.

**Comment by micheleCTDE** [comment]
> On which project are you using uncrustify?

The project is called Trinity Desktop Environment [(TDE)](https://www.trinitydesktop.org/). It is a fork of the old KDE 3.5 series. We are still testing uncrustify (as you can see) and have not yet applied it to the [source code](https://mirror.git.trinitydesktop.org/gitea), but the decision has been made, so now it is a matter of working through testing and issues until we reach a level we are happy with.
The source code is just short of 200 repositories, it comprised more than 200 thousands files (not all src code of course) and an estimated 8-10 millions lines of code. So it will be a good test base for uncrustify :smile:

As I mentioned in another comment, I am happy to help testing uncrustify before you make a release to see if there is any major issues when applied on a large test base.
