### ISSUE TITLE
Case brace incorrectly added after #endif directive instead of before it

### ISSUE THREAD

**Issue by micheleCTDE** [uncrustify/uncrustify#3044]
This issue is similar to issue #3040 but relates to the end brace of the case block. The problem happens both with and without the fix proposed in PR #3043.

Test 1: uncrustify 0.72.0 + backport of commits 45681e88, 64d93e3 
Test 2: uncrustify 0.72.0 + backport of commits 45681e88, 64d93e3 + fix for issue 3040 (both commits in PR #3043) 

Files in attachment:
- t1_in.cpp: test file (subset of a real file, it would fail compilation)
- t1_out.cpp: output of the test run
- test.cfg: configuration used for the test

Step to reproduce: run "uncrustify -c test.cfg -f t1_in.cpp -o t1_out.cpp"

The end brace of the "case AF_INET6:" block should be placed before the #endif directive, but instead it is added after that. I understand uncrustify is not a compiler but as for issue #3040, perhaps we can do something to detect this kind of situation.

Current output extract:
```
#ifdef AF_INET6
		case AF_INET6:
		{
			return 2;
#endif
	}
```

uncrustify does not report any error, but if you try to format the file a second time with "uncrustify -c test.cfg t1_out.cpp", the following errors are reported:
```
Output suffix: .uncrustify
Parsing: t1_out.cpp as language CPP
parse_cleanup(456): pc->orig_line is 20, orig_col is 1, text() is '}', type is BRACE_CLOSE
parse_cleanup(458): (frm.top().type + 1) is UNKNOWN
parse_cleanup(869): Unmatched BRACE_CLOSE
   orig_line is 20, orig_col is 1
parse_cleanup(876): Try the option 'tok_split_gte = true'
```

[wrong_end_case_brace.zip](https://github.com/uncrustify/uncrustify/files/5763823/wrong_end_case_brace.zip)

**Comment by micheleCTDE** [comment]
PR #3048 mostly fixes this problem. There is still a regression related to a similar case. I will create a test case and attach it here later.

**Comment by micheleCTDE** [comment]
Here is the test case about the major regression introduced by the commit proposed in PR #3048.

Test 1: uncrustify 0.72.0 + backport of commits 45681e88, 64d93e3 + fix for issue 3040 (both commits in PR #3043) 
Test 2: uncrustify 0.72.0 + backport of commits 45681e88, 64d93e3 + fix for issue 3040 (both commits in PR #3043) + commit from this PR #3048
NOTE: if you don't see the problem using the latest git version of uncrustify, please let me know and I will test accordingly.

Files in attachment:
- t1_in.cpp: test file (subset of a real file, it would fail compilation)
- t1_out_old.cpp: output of test 1
- t1_out_new.cpp: output of test 2
- test.cfg: configuration used for the test

Step to reproduce: run "uncrustify -c test.cfg -f t1_in.cpp -o t1_out_old[/new].cpp" without and with the commit in PR #3048.

The original code has 3 case blocks. The regression is as follow.
- case 1: the closing braces is added before #else directive and it is wrongly placed. It was ok in test 1.
- case 2: the closing braces is added before #endif directive and it is wrongly placed. It was ok in test 1.
- case 3: the closing braces is added before #endif directive and it is wrongly placed. Being the last case of the switch, in test 1 no braces were added. In test 2, the braces are added, but incorrectly as mentioned.

NOTE 2: after fixing case 1, 2 and 3, I suggest copy "case 1" as a new "case 4" to be the last case of the switch and double check parenthesis are correctly placed even when #else is present.

[PR3048-regression.zip](https://github.com/uncrustify/uncrustify/files/5781258/PR3048-regression.zip)

**Comment by micheleCTDE** [comment]
Additional test case. Seems a bit different from previous case, but still the closing brace is incorrectly placed with the new commit (between #else and #endif.

[PR3048-regression4.zip](https://github.com/uncrustify/uncrustify/files/5782094/PR3048-regression4.zip)

**Comment by guy-maurel** [comment]
Thanks for  the major regression!
I now have to look...

**Comment by guy-maurel** [comment]
PR #3056  is a bugfix proposal.
Please test it and report.

**Comment by micheleCTDE** [comment]
Will test during the weekend and feedback

**Comment by micheleCTDE** [comment]
Tested and I can confirm PR #3056 fixes this issue.
