### ISSUE TITLE
Why was the VsCode extension unpublished?

### ISSUE THREAD

**Issue by rsoesemann** [uncrustify/uncrustify#3047]
The VSCodeMarketplace page https://marketplace.visualstudio.com/items?itemName=LaurentTreguier.uncrustify says:

> This extension is now unpublished from Marketplace. You can choose to uninstall it.

**Comment by guy-maurel** [comment]
Ich verstehe die Frage nicht!

**Comment by rsoesemann** [comment]
Ich dachte irgendjemand hier weiss zufällig warum man Uncrustify nicht mehr in VSCode nutzen kann. Mir ist klar dass hier nicht die Maintainer dieses Plugins sind aber es ist doch warscheinlich dass jemand hier weiss was da lost ist.

**Comment by bwiberg** [comment]
Looking at the GitHub repository [LaurentTreguier/vscode-uncrustify](https://github.com/LaurentTreguier/vscode-uncrustify) it has been archived by the owner.

**Comment by derwaldgeist** [comment]
Hi, I want to second on this question. I was using the uncrustify extension for VSCode a lot and am dearly missing it. Is there an alternative out there? I also know this repo is not related to the VSCode extension, but maybe someone knows what we can do now to use uncrustify in combination with VSCode.

**Comment by Gachdel** [comment]
Same question here... Do we have a chance to get Uncrustify back to VSCode?

Do you have any alternative?
