### ISSUE TITLE
Unwarranted newline in lambda when formatted lambda body exceeds line length

### ISSUE THREAD

**Issue by bwiberg** [uncrustify/uncrustify#3054]
Uncrustify 0.72.0

[Link to debug file](https://gist.github.com/bwiberg/9f96357726d5d9c46587e585da2b65f5)

Test file:
```c++
void func(){
  // looks good
  parallel_for(0, 100, [&](const int i){
    const std::vector<int> values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
    return values[i];
  });

  // looks bad
  parallel_for(0, 100, [&](const int i){
    const std::vector<int> values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
    return values[i];
  });
}
```

Generated results:
```c++
void func()
{
  // looks good
  parallel_for(0, 100, [&](const int i){
    const std::vector<int> values = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 };
    return values[i];
  });

  // looks bad
  parallel_for(0, 100, [&](
                 const int i){
    const std::vector<int> values = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 };
    return values[i];
  });
}
```

Expected results:
```c++
void func()
{
  // looks good
  parallel_for(0, 100, [&](const int i){
    const std::vector<int> values = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 };
    return values[i];
  });

  // looks bad
  parallel_for(0, 100, [&](int i){
    const std::vector<int> values = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 };
    return values[i];
  });
}
```
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
Yes!
It is very difficult to have the "best" strategy to cut an expression if it is too long.
You need to help uncrustify a little bit, such as:
```.cpp
  parallel_for(0, 100, [&](const int i){
    const std::vector<int> values =
    { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 };
```
Sorry!

**Comment by gmaurel** [comment]
same problem as #2306

**Comment by bwiberg** [comment]
@gmaurel 
Thanks or your comment. I understand your point, but my initial issue is that the `const int i){` has been put on a newline for seemingly no reason, leaving the `[&](` on the line before. If that makes sense.

**Comment by guy-maurel** [comment]
Yes

**Comment by guy-maurel** [comment]
what is the part of the code:
   (const int i)

is it a cast?

**Comment by bwiberg** [comment]
@guy-maurel: It is the argument list to a lambda function.

My issue is that Uncrustify transforms this:
```c++
parallel_for(0, 100, [&](const int i){
    const std::vector<int> values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
    return values[i];
  });
```
into this
```c++
parallel_for(0, 100, [&](
                 const int i){  // <---- why is this put on a separate line?
    const std::vector<int> values = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 };
    return values[i];
  });
```

**Comment by guy-maurel** [comment]
PR #3063 is a bugfix proposal.
Please test it and report.

**Comment by bwiberg** [comment]
@guy-maurel: Thanks for the quick turnaround with the patch. My testing shows that the initial issue has been fixed. However an unwanted side-effect has been introduced, please see the code snippets below. 

Input file:
```c++
void func(){
  parallel_for(0, 100, [&](const int i){
    const std::vector<int> values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
    return values[i];
  });

  parallel_for(0, 100, [&](const int a, const int b, const int c, const int d, const int e){
    // do something
    return a;
  });
}
```

Uncrustify 0.72:
```c++
void func()
{
  parallel_for(0, 100, [&](
                 const int i){
    /**          ^ looks bad! **/
    const std::vector<int> values = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 };
    return values[i];
  });

  parallel_for(0, 100,
               [&](const int a, const int b, const int c, const int d,
                   const int e){
    /**            ^ aligns with the lambda's open parenthesis **/
    // do something
    return a;
  });
}
```

Proposed patch from your PR ([debug-file](https://gist.github.com/bwiberg/3c42c2812efb47ae99566ad4cacfdfe3)):
```c++
void func()
{
  parallel_for(0, 100, [&](const int i){
    /**                    ^ looks good now! **/
    const std::vector<int> values = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 };
    return values[i];
  });

  parallel_for(0, 100,
               [&](const int a, const int b, const int c, const int d,
               const int e){
    /**        ^ does not align with the lambda's open parenthesis **/
    // do something
    return a;
  });
}

```

**Comment by guy-maurel** [comment]
Please, have a look on the current update.
If you have something more, please open a new Issue.
