### ISSUE TITLE
pp_space preprocessor indentation sometimes unexpected

### ISSUE THREAD

**Issue by chrisemb** [uncrustify/uncrustify#3055]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Tested on https://cdanu.github.io/uncrustify_config_preview/index.html with settings (config output)
```
# Uncrustify-0.71.0
pp_space                        = force
pp_space_count                  = 2
# option(s) with 'not default' value: 2
#
```
and simplified source input
```
#ifndef ABC
#define ABC

#ifdef XYZ
extern "C" {
#endif

#ifdef XYZ
}
#endif

#endif
```

I get the expected result
```
#ifndef ABC
#  define ABC

#  ifdef XYZ
extern "C" {
#  endif

#  ifdef XYZ
}
#  endif

#endif
```

If I omit the #ifdef XYZ parts I get
```
#ifndef ABC
#define ABC

#endif
```
i.e., no indentation of #define ABC
In fact, it is sufficient to omit only the closing brace to get the unexpected indentation. This happens also to "real code" and also with version 0.72.

Did I miss relevant parameters?

Debug output is:
```
# Uncrustify-0.71.0
pp_space                        = force
pp_space_count                  = 2
# option(s) with 'not default' value: 2
#
# -=====-
# number of loops               = 0
# -=====-
# language                      = CPP
# -=====-
# Line                Tag         Parent_type  Type of the parent         Columns Br/Lvl/pp      Flag   Nl  Text
#   1>            PREPROC|              PP_IF|     PARENT_NOT_SET[  1/  1/  2/  0][0/0/0][100100080001][0-0] #
#   1>              PP_IF|               NONE|     PARENT_NOT_SET[  2/  2/  8/  0][0/0/1][      10001][0-0]  ifndef
#   1>               WORD|               NONE|     PARENT_NOT_SET[  9/  9/ 12/  1][0/0/1][      40001][0-0]         ABC
#   1>            NEWLINE|               NONE|     PARENT_NOT_SET[ 12/ 12/  1/  0][0/0/1][          0][1-0]
#   2>            PREPROC|          PP_DEFINE|     PARENT_NOT_SET[  1/  1/  2/  0][1/1/1][  1000e0001][0-0] #
#   2>          PP_DEFINE|               NONE|     PARENT_NOT_SET[  2/  2/  8/  0][1/1/1][      10001][0-0]  define
#   2>              MACRO|               NONE|     PARENT_NOT_SET[  9/  9/ 12/  1][1/1/1][          1][0-0]         ABC
#   2>            NEWLINE|               NONE|     PARENT_NOT_SET[ 12/ 12/  1/  0][0/0/1][          0][2-0]
#   4>            PREPROC|           PP_ENDIF|     PARENT_NOT_SET[  1/  1/  2/  0][0/0/0][ 8100080001][0-0] #
#   4>           PP_ENDIF|               NONE|     PARENT_NOT_SET[  2/  2/  7/  0][0/0/0][          1][0-0]  endif
# -=====-
```

**Comment by guy-maurel** [comment]
The fall is more complicated as writen here.
The question is the use of the function ifdef_over_whole_file(), which determines:
The whole file is/is not covered by a #IF.
If YES, the value of the option _pp_space_count_ will be multiplicated with "zero",
if NO, with "one".
This is currently most of the cases for *.h files.
To see it, add a line of code, such as "int a;", at the end of your examples.

The question is:
is it reasonable?
is it whished?

Every comments are welcome.

**Comment by micheleCTDE** [comment]
Hi Guy,
a few comments from my side.

1) in both the examples above, the code is within a #ifdef/#endif block. So regardless of the discussion related to "ifdef_over_whole_file()", the results of the two examples should be consistent. As reported (I have not tested myself), the results are different and I agree with @chrisemb that this is wrong. Perhaps the function "ifdef_over_whole_file()" has a bug and the detection is different in the two cases.

2) coming to the main point (whether to indent or not based on the result of "ifdef_over_whole_file()"), I think the best way would be to let the user decide using a configuration option. For example something like "ifdef_whole_file_skip_1st_level_indent" which could be true or false
```
- true: the first level of pp directives inside the whole file #if is not indented

#ifndef ABC
#define ABC
#ifdef XYZ
#  ifdef ABC
  ...
#  endif
#endif
#endif

- false: pp directives are indented normally.

#ifndef ABC
#  define ABC
#  ifdef XYZ
#    ifdef ABC
  ...
#    endif
#  endif
#endif
```

**Comment by guy-maurel** [comment]
yes, there where a bug in the function
Thanks for the idea of a new option

**Comment by micheleCTDE** [comment]
You are welcome :smile:
