### ISSUE TITLE
Comment added on wrong line after case brace

### ISSUE THREAD

**Issue by micheleCTDE** [uncrustify/uncrustify#3058]
Uncrustify-0.72.0-103-b0598a72

Files in attachment:
- t1_in.cpp: test file (subset of a real file, it would fail compilation)
- t1_out.cpp: output of the test run
- test.cfg: configuration used for the test

Step to reproduce: run "uncrustify -c test.cfg -f t1_in.cpp -o t1_out.cpp"

The original code has a comment on the same line of a break inside a case block.
```
        break; // Just a comment
```
After uncrustifying the code braces are added to the case block but the comment is incorrectly placed after the added closing brace.
```
			break;
		}          // Just a comment
```

[comment_after_brace.zip](https://github.com/uncrustify/uncrustify/files/5824261/comment_after_brace.zip)

**Comment by micheleCTDE** [comment]
Just realized this is the same issue reported as minor regression 1 in PR #3048 in this [comment](https://github.com/uncrustify/uncrustify/pull/3048#issuecomment-756094359), although the code behind uncrustify is different.

**Comment by guy-maurel** [comment]
PR #3121 is a bugfix proposal.
Please test it and report.

**Comment by micheleCTDE** [comment]
PR #3121 works fine for the problem reported here, but introduced a regression. Attached a zip file with a test case which includes both the original problem and the new problem.

Files in attachment:
- in.cpp: test file
- out_master_ccb3fe4e.cpp: output of the test run using current master version
- out_i3058_cab9f61d.cpp: output of the test run using version in PR #3121
- test.cfg: configuration used for the test

Step to reproduce: run "uncrustify -c test.cfg -f in.cpp -o out_xxxxxx.cpp" with both versions mentioned above.
Comparing the two output files, there are 5 differences. The first 4 are examples of the new regression, note it is handled correctly in the master version. The last difference is an example of the same case reported in this issue and that has been fixed by PR #3121.

The key difference is whether the comment is on a new line or is following some code on the same line. The fix should only work for the  second case, not the first one.

[i3058-2.zip](https://github.com/uncrustify/uncrustify/files/6161939/i3058-2.zip)

**Comment by micheleCTDE** [comment]
The additional work on PR #3121 (up to commit bf4e64a6) works fine for all problems reported above, nevertheless during testing I spotted one new case which didn't happen before. Attached a zip file with a test case which includes all the original problems and the new problem (see "default" added at line 35)

Files in attachment:
- in.cpp: test file
- out_i3058_bf4e64a6.cpp: output of the test run using version in PR #3121 (up to commit bf4e64a6)
- test.cfg: configuration used for the test

Step to reproduce: run "uncrustify -c test.cfg -f in.cpp -o out_bf4e64a6.cpp".
All previous cases are correctly handled. The new case starts from (line 35):
```
			default:
				; // Do nothing

```
and  produces:
```
			default:
			{
				// Do nothing}
```
which clearly results in a compile error since one brace is commented out.
It would be fine if the result was either:
```
			default:
			{
				// Do nothing
			}
```
or

```
			default:
			{
				;  // Do nothing
			}
```
that is, whether the semicolor is present or not makes not much difference.

This seems to be the only case still wrong with this issue and PR #3121, all other cases are now handled correctly.

[I-3058-3.zip](https://github.com/uncrustify/uncrustify/files/6186665/I-3058-3.zip)

**Comment by gmaurel** [comment]
A new version of the PR is ready

**Comment by micheleCTDE** [comment]
Hi Guy, 
not sure if there is going to be a subsequent commit about this, but PR #3121 is not enough as explained in my comment above. 
Specifically it can produce code that will fail compilation (see the attachment in the comment above and the explanation).

Thanks for your work on this so far!

**Comment by guy-maurel** [comment]
The problem is caused by
  mod_remove_extra_semicolon      = true

**Comment by micheleCTDE** [comment]
> The problem is caused by
> mod_remove_extra_semicolon = true

Hi Guy,
yes, without that settings the semi-colon would not be removed and I guess everything would work fine.
But given that such option is available as well as that there are cases where the semicolon is not in the code at all, I don't think it is right to let this problem. The current version of uncrustify gives code that breaks compilation, hence this is quite serious.
IMO this issue should not have closed and the regression fixed :smile:

**Comment by gmaurel** [comment]
yes

**Comment by micheleCTDE** [comment]
PR #3130 fixes this issue.
