### ISSUE TITLE
trailing comment inside an enum

### ISSUE THREAD

**Issue by OdedSt** [uncrustify/uncrustify#3062]
Is there a way to configure Uncrustify so trailing comments inside an enum won't be automatically moved to a new line?

Meaning, I **wish** that if I write the following:

```
enum Foo
{
    ITEM1, // this is item 1
    ITEM2, // this is item 2
    ITEM3  // this is item 3
}
```

Uncrusrify won't turn it into the following:

```
enum Foo
{
    ITEM1,
    // this is item 1
    ITEM2,
    // this is item 2
    ITEM3 // this is item 3
}
```

I went over every field and searched everwhere and just couldn't find how it can be done.

**Comment by guy-maurel** [comment]
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!
Which version are you using:
Try uncrustify --version
and report

**Comment by OdedSt** [comment]
Hi Guy,
I'm using Uncrustify-0.66.1_f.
Which version does include this fix?
Thanks!

**Comment by guy-maurel** [comment]
The current version, a tar file is 0.72.0
You can get it at https://sourceforge.net/projects/uncrustify/
or from github
