### ISSUE TITLE
[UX] uncrustify behaves oddly on stdin, because it doesn't know the language.

### ISSUE THREAD

**Issue by SoftwareApe** [uncrustify/uncrustify#3064]
Behavior:

When using uncrustify with input from STDIN it formats the file, but it's formatted differently than when passing the file directly.

Expected:

If language (with -l) is not set, should output clear error that it doesn't know the file type.

Reasoning:

I wanted to pass in files from stdin, uncrustify didn't complain, and formatted things wrong. Instead it's better to tell the user with a clear error message that the language flag has to be set. That way the user doesn't have to guess why the formatting is off.

**Comment by gmaurel** [comment]
how?

**Comment by SoftwareApe** [comment]
@gmaurel If you provide the file via stdin check if the -l flag set set, otherwise print an error message.

**Comment by guy-maurel** [comment]
Thanks for the message.
PR #3069 is a bugfix proposal.
Please test it and report.

**Comment by SoftwareApe** [comment]
@guy-maurel thank you!
