### ISSUE TITLE
Support special rules for internationalization functions  _, C_, NC_ and Q_ 

### ISSUE THREAD

**Issue by PerfectCarl** [uncrustify/uncrustify#307]
Gnu text/Glib internationalization libraries define [a set of functions](https://developer.gnome.org/glib/stable/glib-I18N.html) `_`, `C_`, `NC_`, `Q_` that are usually formatted with no space between the parenthesis regardless of the `sp_func_call_paren ` parameter.

Something like this: 
```
infobar_message (_("An error occured during the Import of this CD"), Gtk.MessageType.ERROR);
```  
`infobar_message` is a regular function and got a space before the parenthesis while `_` doesn't. 

Would it be possible to support that special use case?

**Comment by gmaurel** [comment]
The actual version does what you wanted to have
