### ISSUE TITLE
Incorrect parsing of in-class initializer

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#3078]
Consider the following code:

```c++
struct Foo {
        Foo* const arr[2] = {
                & x1,
                & x2,
        };
};

Foo* const arr[2] = {
        &x1,
        &x2,
};
```

In all cases, the `&`s should parse as `CT_ADDR`. However, in the first case, they parse as `CT_BYREF`. This results in malformatting, which can be seen with:
```
sp_after_byref                  = add
sp_addr                         = remove
```

**Comment by gmaurel** [comment]
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!
