### ISSUE TITLE
Cannot generate report of what is changed

### ISSUE THREAD

**Issue by gagoyal** [uncrustify/uncrustify#308]
Hi,
I want to generate a report of what uncrustify detected as violation of settings and that it will attempt to change. I am only interested in detecting the violations for reporting but do not want to replace them. One method is file comparison but it will not be a single report/log.

Can you please guide how can I achieve this?

Gaurav

**Comment by gmaurel** [comment]
uncrustify -c <your config file> -f <your source file> -o <the output file>
meld  <your source file> <the output file>
