### ISSUE TITLE
indent_align_string should align to first, not last

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#3086]
Consider the following two (similar) code snippets:
```c++
void foo(){
        bar(
                "text" TOKEN TOKEN
                "more text");
}

void foo(){
        bar(
                "text" TOKEN "text"
                "more text");
}
```

It seems that both of these should be unchanged. However, with `indent_align_string = true`, the second is reformatted as:
```c++
void foo(){
        bar(
                "text" TOKEN "text"
                             "more text");
}
```

It seems that alignment should back up to the first string in a sequence of (`STRING`, `WORD`)+ `STRING` rather than aligning at the last.

(Another possible issue is that the first sequence gets marked `STRING`, `TYPE`, `WORD` when it should probably be `STRING`, `WORD`, `WORD`. Also, why are all string literal arguments apparently being marked with parent type `PP_INCLUDE`?)

**Comment by guy-maurel** [comment]
PR #4288 is a bug fix proposal.
Please test it and report.
