### ISSUE TITLE
Strange behavior of nl_var_def_blk_start

### ISSUE THREAD

**Issue by mwoehlke-kitware** [uncrustify/uncrustify#3097]
Consider the following:
```c++
void foo()
{
    for( unsigned p = 0; p < np;
         ++p )
    {
      double* o = bar[p];
    }
}
```
With `nl_var_def_blk_start = 2` (config otherwise empty/default), uncrustify produces:
```c++
void foo()
{
        for( unsigned p = 0; p < np;

             ++p )
        {
                double* o = bar[p];
        }
}
```

That added blank line does not seem to belong. (And without `nl_var_def_blk_start = 2`, it is not added.)

Using Uncrustify-0.72.0-169-eb324f21.

**Comment by guy-maurel** [comment]
PR #3131 is a bugfix proposal.
Please test it and report.

**Comment by mwoehlke** [comment]
Sigh... I need to start reporting bugs from this account so messages about my own stuff don't get buried. Sorry about that.

The fix caused a "regression" (although I suspect it's not so much a regression as the problem just got moved elsewhere). Consider:
```
foo()
{
  // hello
  int x  = 42;
  if( x )
  {
    bar();
  }
}
```

There is now instead an apparently-spurious blank line being added after the comment.

**Comment by mwoehlke** [comment]
Also, I am confused; it seems like the added test expects the not-working behavior? (And indeed the bug seems to still be present?)
