### ISSUE TITLE
align_func_proto(87): pc->level is 9. This is too big, at line 85, column 25. Make a report, please.

### ISSUE THREAD

**Issue by CedricRBR** [uncrustify/uncrustify#3115]
When running Uncrustify with the attached configuration against this file [.pde file](https://gist.github.com/CedricRBR/3235784e312cbf3e284dc0c7abf77b2d)

The following error is generated:

```
~ ➜ uncrustify -v                                                                                                                                                       11:33:16
Uncrustify-0.72.0_f

~ ➜ uncrustify -f /Users/cedricreber/Documents/personnal/coding/processing/p2048/p2048.pde -c ~/.config/uncrustify/java.cfg -l JAVA -p debug.txt                        11:34:09
Parsing: /Users/cedricreber/Documents/personnal/coding/processing/p2048/p2048.pde as language JAVA
align_func_proto(87): pc->level is 9. This is too big, at line 85, column 25. Make a report, please.
```

No debug file is generated, output sent to stdout.

exchanging `-p debug.txt` with `&> debug.txt` yields this: [debug.txt](https://gist.github.com/CedricRBR/1f60e45045b66febf0cddd45c73b1305)

**Comment by micheleCTDE** [comment]
See #3001

**Comment by guy-maurel** [comment]
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by CedricRBR** [comment]
Sorry for the late response. current git version indeed fixes this issue. Thanks for the quick feedback!
