### ISSUE TITLE
* in dereferencing after a keyword is formatted by arithmetic operator rules

### ISSUE THREAD

**Issue by gg-yb** [uncrustify/uncrustify#3120]
Debug File:
[https://gist.github.com/gg-yb/64a24ab5c97dd70229f44f464c488471](https://gist.github.com/gg-yb/64a24ab5c97dd70229f44f464c488471)

Test Case:
```cpp
#include "whatever.h"

void main()
{
   myFunc( not *myGlobalOptional );
}
```

Expected Results:
```cpp
#include "whatever.h"

void main()
{
	myFunc( not *myGlobalOptional );
}
```

Actual Results:
```cpp
#include "whatever.h"

void main()
{
	myFunc( not * myGlobalOptional );
}
```

Note the space between `*` and `myGlobalOptional`.

Current version: Uncrustify_d-0.72.0

This is possibly related to #3117 and #3118.

*Note:* A temporary workaround can be achieved by parenthesizing the dereferenced expression.

**Comment by guy-maurel** [comment]
what is _myGlobalOptional_ ?

**Comment by gg-yb** [comment]
It is defined possibly like this in the header:

```cpp
#include <optional>

std::optional<int> myGlobalOptional;
```

**Comment by guy-maurel** [comment]
PR #4289 is a bug fix proposal.
Please test it and report.
