### ISSUE TITLE
Uncrustify hangs with pragma to disable warning

### ISSUE THREAD

**Issue by danleowheeler** [uncrustify/uncrustify#3124]
I had this line in my source file : __pragma(warning(disable: 26444))
 
 With Uncrustify 0.72.0 it would hang upon parsing this file 100% of the time. Removing this line stops it from hanging.

**Comment by guy-maurel** [comment]
Under Linux Mint, I get:
```.log
Uncrustify_d-0.72.0-211-fccc188e
Parsing: danleowheeler.cpp as language CPP
int main()
{
        __pragma(warning(disable: 26444));
}
```
Please push some more info to show the bug
