### ISSUE TITLE
bad formatting of class member initialization in C++ constructor

### ISSUE THREAD

**Issue by chris-praxis** [uncrustify/uncrustify#3139]
[uncrustify.cfg.zip](https://github.com/uncrustify/uncrustify/files/6268189/uncrustify.cfg.zip)

Input code snippet:
ImageReader::ImageReader(int width, int height, enum AIMAGE_FORMATS format)
    : presentRotation_(0),
      mIsClosing(false),
      ptr_trainerInterface(nullptr),
      reader_(nullptr) {

Latest commit on master: 6c790e6624cb62dfc8470978d0c24645acba49b7
Result:
ImageReader::ImageReader(int width, int height, enum AIMAGE_FORMATS format)
: presentRotation_ ( 0 ),
mIsClosing ( false ) ,
ptr_trainerInterface ( nullptr ) ,
reader_ ( nullptr ) {

Problems
1. no indentation
2. lots of extra spaces added
3. brace is not moved to new line

Switched to version 0.72.0
Result:
ImageReader::ImageReader(int width, int height, enum AIMAGE_FORMATS format)
    : presentRotation_(0),
    mIsClosing(false),
    ptr_trainerInterface(nullptr),
    reader_(nullptr)
{

All problems are fixed except that 'indent_ctor_init' has no effect.

**Comment by gmaurel** [comment]
adding a closing brace, with your configuration file I get:
```.log
Uncrustify_d-0.74.0-62-46bb1413
do_source_file(1505): Parsing: chris-praxis.cpp as language CPP
ImageReader::ImageReader(int width, int height, enum AIMAGE_FORMATS format)
    : presentRotation_(0),
    mIsClosing(false),
    ptr_trainerInterface(nullptr),
    reader_(nullptr) {}
```
What do you expect to get?
