### ISSUE TITLE
inconsistent indent with const

### ISSUE THREAD

**Issue by wbytteb** [uncrustify/uncrustify#3144]
Hi,
I'm using uncrustify v0.72 with the msvc.cfg file.

### _**Input :**_
  ```
unsigned int
  Sensor1,
  Sensor2;
  
  unsigned int const
  Sensor1,
  Sensor2;
  
  const unsigned int
  Sensor1,
  Sensor2;
```

### _**Output :**_
  ```
unsigned int
          Sensor1,
          Sensor2;
  
  unsigned int const
  Sensor1,
          Sensor2;
  
  const unsigned int
          Sensor1,
          Sensor2;

```
### _**Observations :**_

- I cannot seem to find a rule which forces the indent on Sensor1 and Sensor2, what is causing this indent ?

- Note the inconsistent behavior based on the location of 'const' after or before the type.

**Comment by guy-maurel** [comment]
uncrustify doesn't support the declaration of two(or more) variables in the same statement.
Please use only one.
