### ISSUE TITLE
Space removed from "empty" lines despite *INDENT-OFF*

### ISSUE THREAD

**Issue by tideberg** [uncrustify/uncrustify#3150]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
Description: Spaces on empty lines are removed despite " *INDENT-OFF*" leading to failing checks

Example: failing_uncrustify_check.h (please note 2 spaces on line 2):
```c
/* *INDENT-OFF* */
  
int a(int b);
```

Steps to reproduce:
`uncrustify -c uncrustify.cfg --check -f failing_uncrustify_check.h`

Expected result:
`PASS: failing_uncrustify_check.h (36 bytes)`

Actual result:
`FAIL: failing_uncrustify_check.h (File size changed from 36 to 34)`

Current version: Uncrustify-0.72.0_f

[debug file](https://gist.github.com/tideberg/5ab6919fc5ed5cd87547e6365776e920)

**Comment by gmaurel** [comment]
This is correct.
Space(s) at the end of a line are always removed
