### ISSUE TITLE
Operator leaking from #define statement

### ISSUE THREAD

**Issue by bofh69** [uncrustify/uncrustify#3156]
This code:
```c
#define X(a, b, ...) 1 +
static c d[e] =
#undef X
0;
```
becomes:
```c
#define X(a, b, ...) 1
+ static c d[e] =
#undef X
    0;
```
when running with our config file and version `Uncrustify_d-0.72.0`. It is the same result with 0.68 and 0.69, and with other operators like `-`, `*`, `|`, `&` or `/`. ` >>` and `<<` works fine though.

I expect the `+` to stay in the macro's definition so the code keeps working.

Here's the debug file: 
[debug.txt](https://github.com/uncrustify/uncrustify/files/6350824/debug.txt)

A workaround is to not write such horrible macros in the first place.

**Comment by gmaurel** [comment]
This is correct, your configuration file says:
 ` pos_arith                       = lead`

**Comment by bofh69** [comment]
@gmaurel Making a program become invalid can never be the correct behaviour.

If it is supposed to indent the operator here, the backslash is missing. The result should be:
```c
#define X(a, b, ...) 1 \
    +
static c d[e] =
#undef X
    0;
```
