### ISSUE TITLE
merge duplicate includes

### ISSUE THREAD

**Issue by jayvdb** [uncrustify/uncrustify#3164]
clang-format defaults to removing duplicate includes.  It would be nice if uncrustify had an option to do this.  I rely on this to tidy generated code.

i.e.
```c
#include <cassert>
#include <cassert>
#include <cassert>
...
```

becomes
```c
#include <cassert>
```

**Comment by guy-maurel** [comment]
PR #3276 is a bugfix proposal.
Please test it and report.
