### ISSUE TITLE
Option sp_before_case_colon = ignore  adds spaces before case colon

### ISSUE THREAD

**Issue by devreal** [uncrustify/uncrustify#3173]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

I am currently exploring the use of uncrustify on a larger open source code base. The project has fairly lenient coding standards and I am hoping to use uncrustify to enforce the few requirement that exist (4 space block indentation, braces around all blocks) while not changing most of the existing code. I am encountering several unexpected changes that I am planning to report one by one. The first one is that setting 

```
# Add or remove space before case ':'.
#
# Default: remove
sp_before_case_colon            = ignore   # ignore/add/remove/force
```

leads to added spaces before the case colon. Take the following example:

```C
typedef enum {
  A, B, C
} abc_t;


int foo(abc_t d)
{
  switch (d) 
  {
    case A:
      return 0;
    case B:
      return 1;
    case C:
      return 2;
  }
}
```

The resulting file contains colons after the case labels:

```C
typedef enum {
    A, B, C
} abc_t;


int foo(abc_t d)
{
    switch (d) 
    {   
    case A : 
        return 0;
    case B : 
        return 1;
    case C : 
        return 2;
    }   
}
```

Expected behavior is that the spacing around case labels remains unchanged.

I am attaching the full config file I am using: 
[uncrustify2.cfg.tar.gz](https://github.com/uncrustify/uncrustify/files/6464794/uncrustify2.cfg.tar.gz)

I am using uncrustify 0.72.0 downloaded from the release on github.

**Comment by guy-maurel** [comment]
important catch, thanks
bugfix is coming soon

**Comment by guy-maurel** [comment]
There might be some similar cases with sp_ options and ignore.
I#
I'll test that.

**Comment by devreal** [comment]
Right, I've seen similar issues with spaces between `)` and `{` but haven't had the time yet to reproduce. Thanks for looking into that!

**Comment by guy-maurel** [comment]
We need many new tests for all the sp_ options, where the file space.cpp contains such a line:
`if (options::sp_cond_ternary_short() != IARF_IGNORE)`
uncrustify adds a space instead of ignore case.
