### ISSUE TITLE
Question: how to ignore all spacing except for basic block indentation

### ISSUE THREAD

**Issue by devreal** [uncrustify/uncrustify#3174]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

As mentioned in https://github.com/uncrustify/uncrustify/issues/3173, I am exploring the use of uncrustify on a large legacy code base. Our goal is to not change existing code, except to enforce a few basic coding requirements, which include 4-space block indentation and braces around all blocks.

I tried disabling most of the space formatting but I cannot seem to disable continued assignment indentation. We have a variety of different styles and would like to keep them untouched.

Take the following example:

```C
struct A {
  int a, b, c;
};

struct A foo()
{
  struct A a = {.a = 0,
                .b = 1,
                .c = 2};
  return a;
}
```

After applying uncrustify I see the basic block indentation (4 spaces) for the continued assignment lines:
```C
$ ~/opt/uncrustify-0.72.0/bin/uncrustify -p debug.txt -c ~/uncrustify2.cfg -f test_assign_continue.c 
Parsing: test_assign_continue.c as language C

struct A {
    int a, b, c;
};

struct A foo()
{
    struct A a = {.a = 0,
        .b = 1,
        .c = 2};
    return a;
}
```

I tried turning the knobs I thought as being relevant but to no avail, the result is always the same. I am attaching the used config file: [uncrustify2.cfg.tar.gz](https://github.com/uncrustify/uncrustify/files/6465035/uncrustify2.cfg.tar.gz)

The goal for me is to not change the indentation of this code. My question is thus: is there a way to accomplish this and if so what is the option I need to tune?

More generally: is there a way to disable any indentation other than the 4-space block indentation at the beginning of a statement?

**Comment by guy-maurel** [comment]
Try:
```.cpp
struct A foo()
{
/* *INDENT-OFF* */
  struct A a = {.a = 0,
                .bb = 1,
                .c = 2};
/* *INDENT-ON* */
  return a;
}
```

**Comment by devreal** [comment]
@guy-maurel Unfortunately, that is not a solution since these patterns occur in many places of the 300kloc code base.

**Comment by ruMagnetar** [comment]
Need this feature too. To control applying uncrustify in legacy project with different types of indents I need configuration to start, i.e. do not change the code after run of the tool. After that I will step-by-step apply options and proove there is no change of functionality. I've made the config adding many ignore/false options but uncontrol indent makes diffs literally in every lines, and no one wants review it. As you see the option INDENT-OFF is not helps here.
I tried to add patch but indent_text function is to complex. I look at debug out and I suppose there is no something like OLD_INDENT token. The indent from source just not stored in parsing, so thats problem. So we need option indent_store_old with appropriate parsing and processing.

**Comment by micheleCTDE** [comment]
> Need this feature too. To control applying uncrustify in legacy project with different types of indents I need configuration to start, i.e. do not change the code after run of the tool. After that I will step-by-step apply options and proove there is no change of functionality. I've made the config adding many ignore/false options but uncontrol indent makes diffs literally in every lines, and no one wants review it. As you see the option INDENT-OFF is not helps here. I tried to add patch but indent_text function is to complex. I look at debug out and I suppose there is no something like OLD_INDENT token. The indent from source just not stored in parsing, so thats problem. So we need option indent_store_old with appropriate parsing and processing.

Hi @ruMagnetar,
it is currently not possible to have a fully neutral configuration that makes no changes. The way uncrustify is written at the moment, spaces/tabs are converted based on the options used.
