### ISSUE TITLE
Addition of a config option associated with the attached patch - Alignment of FDef/FDecl parentheses with params

### ISSUE THREAD

**Issue by piyooshm** [uncrustify/uncrustify#318]
Hi,

At my workplace, the coding standard requires a newline before the parenthesis in function declaration and definition. However, the parenthesis also needs to be indented like the parameters. The following lines show an example:
<pre><code>
////// header file
class MyClass
{
   MyClass
      (
      );
      
   void myFunc1
      (
      );
      
   void myFunc2
      (
      int param1,
      int param2
      );
};

/////// cpp file
MyClass::MyClass
   (
   ):
   m_Var1(0),
   m_Var2(4)
{
   // Constructor implementation
}

void MyClass::myFunc1
   (
   )
{
   // myFunc1 implementation
}

void MyClass::myFunc2
   (
   int param1,
   int param2
   )
{
   // myFunc2 implementation
}
</code></pre>

I was able to configure uncrustify using the existing settings/options to get the following closest output:

<pre><code>
void MyClass::myFunc1
   ()
{
   // myFunc1 implementation
}
</code></pre>
or the following type of output:

<pre><code>
void MyClass::myFunc2
(
   int param1,
   int param2
)
{
   // myFunc2 implementation
}
</code></pre>
It seems that the indentation for the function parenthesis is open only if there is no newline right after the opening parenthesis. What I wanted was achievable by disabling the check for next chunk being newline at one place (See attached patch file). I hope that an experienced uncrustify developer can turn this patch into a configuration option to indent/align the function decl/def/call parentheses with the parameters as shown in my first example.

Thanks,
Piyoosh

Patch:
<pre><code>
diff --git "a/C:\\TortoiseGit\\indBF01.tmp\\indent-36a0f44-left.cpp" "b/C:\\Dev\\uncrustify\\src\\indent.cpp"
index 6735758..67530a2 100644
--- "a/C:\\TortoiseGit\\indBF01.tmp\\indent-36a0f44-left.cpp"
+++ "b/C:\\Dev\\uncrustify\\src\\indent.cpp"
@@ -1331,8 +1331,7 @@ void indent_text(void)
          }
 
          if ((pc->type == CT_FPAREN_OPEN) &&
-             chunk_is_newline(chunk_get_prev(pc)) &&
-             !chunk_is_newline(chunk_get_next(pc)))
+             chunk_is_newline(chunk_get_prev(pc)))
          {
             frm.pse[frm.pse_tos].indent = frm.pse[frm.pse_tos - 1].indent + indent_size;
             indent_column_set(frm.pse[frm.pse_tos].indent);
</code></pre>

**Comment by gmaurel** [comment]
I remember the question from  bengardner commented on 3195a30 on 25 Nov 2015
Do you have a test case that shows this problem? What does this change fix?
Please make a "Pull Request" for it.
Thanks

**Comment by piyooshm** [comment]
I do not want this change to be pulled directly. This patch is only a hack that allows me to work in my use-case scenario, but it's not a general enhancement. To add this enhancement, you may need to implement another option/setting, which I'm not equipped to do.
