### ISSUE TITLE
tenary operator (? : ) with method call issue on Objective-C in 0.61

### ISSUE THREAD

**Issue by mhama** [uncrustify/uncrustify#319]
Hi,

I found this issue: unneeded spaces are inserted around the first colon in method call, if used inside a tenary operator.

expected:
```obj-c
CGColorRef color = flag ? [UIColor colorWithWhite:1.f alpha:.5f].CGColor : nil;
```

result:
```obj-c
CGColorRef color = flag ? [UIColor colorWithWhite : 1.f alpha:.5f].CGColor: nil;
```

My guess is that uncrustify mistakenly handle first colon in the method call (colorWithWhite:alpha:) as the colon of the tenary operator.

Thanks,

**Comment by jordanwhitney** [comment]
This has been fixed in #355.  It would be nice to get a version increment so we can update Homebrew and use this without having to do a custom make.

**Comment by gmaurel** [comment]
You can get the actual git version or wait a little bit. I think we will push a new version october 2016

**Comment by mihaipopescu** [comment]
@gmaurel You can this as a milestone https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/
