### ISSUE TITLE
enum type std::int64_t turns into std :: int64_t (spaces added)

### ISSUE THREAD

**Issue by JodiTheTigger** [uncrustify/uncrustify#3198]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

`enum class Flags : std::int64_t` gets spaces put around the `::` which is unwanted

I searched for options to control this but couldn't find any

```
$ ./uncrustify.exe --version
Uncrustify_d-0.73.0
```

uncrustify.cfg
```
indent_columns = 4
```

code:
```cpp
#include <cstdint>

enum class Flags : std::int64_t
{
    MyFlag
};
```

expected: unchanged

got:
```cpp
#include <cstdint>

enum class Flags : std :: int64_t
{
    MyFlag
};
```

debug:
```
# Uncrustify_d-0.73.0
indent_columns                  = 4
# option(s) with 'not default' value: 1
#
# -=====-
# number of loops               = 0
# -=====-
# language                      = CPP
# -=====-
# Line                Tag         Parent_type  Type of the parent         Columns Br/Lvl/pp     Nl  Text
#   1>            PREPROC|         PP_INCLUDE|     PARENT_NOT_SET[  1/  1/  2/  0][0/0/0][0-0] #
#   1>         PP_INCLUDE|               NONE|     PARENT_NOT_SET[  2/  2/  9/  0][0/0/0][0-0]  include
#   1>             STRING|         PP_INCLUDE|     PARENT_NOT_SET[ 10/ 10/ 19/  1][0/0/0][0-0]          <cstdint>
#   1>            NEWLINE|               NONE|     PARENT_NOT_SET[ 19/ 19/  1/  0][0/0/0][2-0]
#   3>               ENUM|               NONE|     PARENT_NOT_SET[  1/  1/  5/  0][0/0/0][0-0] enum
#   3>         ENUM_CLASS|               NONE|     PARENT_NOT_SET[  6/  6/ 11/  1][0/0/0][0-0]      class
#   3>               TYPE|               ENUM|     PARENT_NOT_SET[ 12/ 12/ 17/  1][0/0/0][0-0]            Flags
#   3>          BIT_COLON|               ENUM|     PARENT_NOT_SET[ 18/ 18/ 19/  1][0/0/0][0-0]                  :
#   3>               TYPE|          BIT_COLON|     PARENT_NOT_SET[ 20/ 20/ 23/  1][0/0/0][0-0]                    std
#   3>               TYPE|          BIT_COLON|     PARENT_NOT_SET[ 24/ 23/ 25/  0][0/0/0][0-0]                        ::
#   3>               TYPE|          BIT_COLON|     PARENT_NOT_SET[ 27/ 25/ 32/  0][0/0/0][0-0]                           int64_t
#   3>            NEWLINE|               NONE|     PARENT_NOT_SET[ 34/ 32/  1/  0][0/0/0][1-0]
#   4>         BRACE_OPEN|               ENUM|     PARENT_NOT_SET[  1/  1/  2/  0][0/0/0][0-0] {
#   4>            NEWLINE|               NONE|     PARENT_NOT_SET[  2/  2/  5/  0][1/1/0][1-0]
#   5>               WORD|               NONE|     PARENT_NOT_SET[  5/  5/ 11/  0][1/1/0][0-0]     MyFlag
#   5>            NEWLINE|               NONE|     PARENT_NOT_SET[ 11/ 11/  1/  0][1/1/0][1-0]
#   6>        BRACE_CLOSE|               ENUM|     PARENT_NOT_SET[  1/  1/  2/  0][0/0/0][0-0] }
#   6>          SEMICOLON|               ENUM|     PARENT_NOT_SET[  2/  2/  3/  0][0/0/0][0-0]  ;
#   6>            NEWLINE|               NONE|     PARENT_NOT_SET[  3/  3/  1/  0][0/0/0][1-0]
# -=====-
```

**Comment by guy-maurel** [comment]
PR #3228 is a bugfix proposal.
Please test it and report.

**Comment by JodiTheTigger** [comment]
This fixes my code - thank you
