### ISSUE TITLE
sp_after_byref setting is sometimes incorrectly applied to the 'address-of' operator instead of sp_addr

### ISSUE THREAD

**Issue by vlyova** [uncrustify/uncrustify#3203]
With Uncrustify 0.72, and the following config:
[uncrustify_config.txt](https://github.com/uncrustify/uncrustify/files/6623544/uncrustify_config.txt)

Formatting the following code sample:

```
#include <vector>

class A
{
public:
	int a;
	int b;

	std::vector<int*> v =
	{
		&a,
		&b
	};
};
```

adds unwanted spaces after `&` in the initialization list. The problem is caused by the sp_after_byref option, and is not reproduced if I change this option to "remove" or "ignore".

Since in this case the ampersand is the "address-of" operator, I would expect sp_addr to be used (which is set to 'remove' in the config file).

**Comment by gmaurel** [comment]
I am working just now on this option.
I take your example with me, thanks.
#3204

**Comment by gmaurel** [comment]
PR #3211 is a bugfix proposal.
Please test it and report.
