### ISSUE TITLE
No Windows binaries for uncrustify >= 0.70

### ISSUE THREAD

**Issue by rillig** [uncrustify/uncrustify#3213]
README.md says that Windows binaries are available at SourceForge. However, the latest binary available there is for uncrustify 0.69.0 from May 2019.

**Comment by hghdev** [comment]
https://sourceforge.net/projects/uncrustify/

Released `/uncrustify-0.73.0/uncrustify-0.73.0_f-win64.zip`
Released `/uncrustify-0.73.0/uncrustify-0.73.0_f-win32.zip`

**Comment by guy-maurel** [comment]
more exactly:
**https://sourceforge.net/projects/uncrustify/files/**

**Comment by rillig** [comment]
README.md still refers to https://sourceforge.net/projects/uncrustify/files/uncrustify/, which is one subdirectory too deep to see the current versions.

**Comment by mwoehlke-kitware** [comment]
> README.md still refers to https://sourceforge.net/projects/uncrustify/files/uncrustify/, which is one subdirectory too deep

Right, I think Guy was saying the same things, as it's already fixed by #3216 🙂
