### ISSUE TITLE
Question(cpp): How to remove leading tabs or spaces in front of `#include` directives

### ISSUE THREAD

**Issue by hghdev** [uncrustify/uncrustify#3215]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

`Use_of_uncrustiy` or option `FeatureRequest`
Language: `cpp`

Formatting a `cpp` file does not remove leading tabs or spaces in front of `#include` directives.
I could not find an option related to indenting `#include` directives.

My environment:
    `Uncrustify-0.73.0_f`
binary archive `uncrustify-0.73.0_f-win64.zip` downloaded from
    https://sourceforge.net/projects/uncrustify/
with default config file from
    https://github.com/uncrustify/uncrustify/blob/master/documentation/htdocs/default.cfg

```
systeminfo
OS Name: Microsoft Windows 10 Pro
OS Version: 10.0.19043 Build 19043
```

file `input.cpp` (`<tab>` is a tab, `<nbsp>` is a blank in the test file)
```cpp
<tab>#include <iostream>

<nbsp><nbsp>#include <iostream>
```

Formatting with 
```shell
uncrustify.exe -c .\uncustify-default.cfg .\input.cpp
```
produces unchanged file `input.cpp.uncrustify`
```cpp
<tab>#include <iostream>

<nbsp><nbsp>#include <iostream>
```

The expected or desired result is
```cpp
#include <iostream>

#include <iostream>
```
with leading tabs or spaces removed.

**Comment by mwoehlke-kitware** [comment]
Does `pp_indent = remove` not accomplish this?

**Comment by hghdev** [comment]
It does! Thanks!
