### ISSUE TITLE
Maybe bad comment for option `nl_create_list_one_liner` in `default.cfg` file:

### ISSUE THREAD

**Issue by hghdev** [uncrustify/uncrustify#3217]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

In file https://github.com/uncrustify/uncrustify/blob/master/documentation/htdocs/default.cfg, starting at line 2010,
the comment for option `nl_create_list_one_liner` refers to *unbraced if statements*. The name of the option and the given example refer to list definitions.
```
# Whether to split one-line simple unbraced if statements into three lines by
# adding newlines, as in 'int a[12] = { <here> 0 <here> };'.
```
Suggestion:
```
# Whether to split one-line simple list definitions into three lines by
# adding newlines, as in 'int a[12] = { <here> 0 <here> };'.
```

**Comment by guy-maurel** [comment]
You are right. Thanks for comment.
But it would be better to create a new pull request, look at:
https://github.com/uncrustify/uncrustify/pulls

**Comment by hghdev** [comment]
Created pull request hghdev:fix-comment-for-option-nl_create_list_one_liner-in-default-cfg.

**Comment by guy-maurel** [comment]
I cann't see

**Comment by hghdev** [comment]
Sorry. Now created pull request form my fork. Before there was some badge displayed, showing info which I mistook to already be a pull request.

**Comment by hghdev** [comment]
Fixed with pull requests
https://github.com/uncrustify/uncrustify/pull/3221
https://github.com/uncrustify/uncrustify/pull/3226
