### ISSUE TITLE
Function declarations using macros

### ISSUE THREAD

**Issue by chrullrich** [uncrustify/uncrustify#322]
Uncrustify does not correctly format a (C++ member) function declaration that is obscured by a macro (how should it ...):

    STDMETHOD(Initialize)(void);
    STDMETHOD(AddSubscription)(BSTR bsName);
    STDMETHOD(GetValues)(BSTR bsName, REFDATA** pData);

becomes

    STDMETHOD(Initialize) (void);
    STDMETHOD(AddSubscription) (BSTR bsName);
    STDMETHOD(GetValues) (BSTR bsName, REFDATA  * *pData);

STDMETHOD(x) expands to a lot of declarations, but you can think of it as `#define STDMETHOD(x) int x`.

There are two issues with this result: The space between the `) (`, and the spaces around the pointer asterisks in the argument lists. The latter come from sp_arith, but I don't know where exactly the extra space is coming from.

My config file, mostly courtesy of UniversalIndentGUI:

    tok_split_gte=false
    utf8_byte=false
    utf8_force=false
    indent_cmt_with_tabs=false
    indent_align_string=true
    indent_braces=false
    indent_braces_no_func=false
    indent_braces_no_class=false
    indent_braces_no_struct=false
    indent_brace_parent=false
    indent_namespace=false
    indent_extern=false
    indent_class=true
    indent_class_colon=false
    indent_else_if=false
    indent_var_def_cont=false
    indent_func_call_param=false
    indent_func_def_param=false
    indent_func_proto_param=false
    indent_func_class_param=false
    indent_func_ctor_var_param=false
    indent_template_param=false
    indent_func_param_double=false
    indent_relative_single_line_comments=false
    indent_col1_comment=false
    indent_access_spec_body=false
    indent_paren_nl=false
    indent_comma_paren=false
    indent_bool_paren=false
    indent_first_bool_expr=false
    indent_square_nl=false
    indent_preserve_sql=false
    indent_align_assign=true
    sp_balance_nested_parens=false
    align_keep_tabs=false
    align_with_tabs=false
    align_on_tabstop=false
    align_number_left=false
    align_func_params=false
    align_same_func_call_params=false
    align_var_def_colon=false
    align_var_def_attribute=false
    align_var_def_inline=false
    align_right_cmt_mix=false
    align_on_operator=false
    align_mix_var_proto=false
    align_single_line_func=false
    align_single_line_brace=false
    align_nl_cont=false
    align_left_shift=true
    align_oc_decl_colon=false
    nl_collapse_empty_body=false
    nl_assign_leave_one_liners=false
    nl_class_leave_one_liners=false
    nl_enum_leave_one_liners=false
    nl_getset_leave_one_liners=false
    nl_func_leave_one_liners=false
    nl_if_leave_one_liners=false
    nl_multi_line_cond=false
    nl_multi_line_define=false
    nl_before_case=false
    nl_after_case=false
    nl_after_return=false
    nl_after_semicolon=false
    nl_after_brace_open=false
    nl_after_brace_open_cmt=false
    nl_after_vbrace_open=false
    nl_after_vbrace_open_empty=false
    nl_after_brace_close=false
    nl_after_vbrace_close=false
    nl_define_macro=false
    nl_squeeze_ifdef=false
    nl_ds_struct_enum_cmt=false
    nl_ds_struct_enum_close_brace=false
    nl_create_if_one_liner=false
    nl_create_for_one_liner=false
    nl_create_while_one_liner=false
    ls_for_split_full=false
    ls_func_split_full=false
    nl_after_multiline_comment=false
    eat_blanks_after_open_brace=false
    eat_blanks_before_close_brace=false
    mod_full_brace_if_chain=false
    mod_pawn_semicolon=false
    mod_full_paren_if_bool=false
    mod_remove_extra_semicolon=false
    mod_sort_import=false
    mod_sort_using=false
    mod_sort_include=false
    mod_move_case_break=false
    mod_remove_empty_return=false
    cmt_indent_multi=true
    cmt_c_group=false
    cmt_c_nl_start=false
    cmt_c_nl_end=false
    cmt_cpp_group=false
    cmt_cpp_nl_start=false
    cmt_cpp_nl_end=false
    cmt_cpp_to_c=false
    cmt_star_cont=false
    cmt_multi_check_last=true
    cmt_insert_before_preproc=false
    pp_indent_at_level=false
    pp_region_indent_code=false
    pp_if_indent_code=false
    pp_define_at_level=false
    input_tab_size=4
    output_tab_size=4
    indent_columns=4
    indent_continue=8
    indent_switch_case=4
    indent_case_brace=0
    indent_with_tabs=1
    sp_arith=add
    sp_before_angle=remove
    sp_template_angle=add
    sp_inside_angle=remove
    sp_after_angle=add
    sp_angle_paren=remove
    sp_angle_word=add
    sp_angle_shift=remove
    sp_before_sparen=add
    sp_inside_sparen=remove
    sp_after_sparen=remove
    sp_sparen_brace=add
    sp_special_semi=remove
    sp_before_class_colon=add
    sp_pp_stringify=remove

**Comment by gmaurel** [comment]
The space between the ) ( is no more present at the actual git version.
I looking for the second bug just now.

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
