### ISSUE TITLE
sp_after_byref affects address-of operator in template argument list

### ISSUE THREAD

**Issue by chrullrich** [uncrustify/uncrustify#323]
Before `sp_after_byref=add`:

```
class ATL_NO_VTABLE CProxy :
    public ATL::CComObjectRootEx<ATL::CComSingleThreadModel>,
    public ATL::CComCoClass<CProxy, &CLSID_Proxy>,
```

After:

```
class ATL_NO_VTABLE CProxy :
    public ATL::CComObjectRootEx<ATL::CComSingleThreadModel>,
    public ATL::CComCoClass<CProxy, & CLSID_Proxy>,
```

Note the space after the `&` in the last line.

**Comment by gmaurel** [comment]
Help me:
What is the problem?

**Comment by chrullrich** [comment]
That ampersand is the address-of operator, not declaring a reference. Spacing behind it should be controlled by sp_addr, not sp_after_byref.

**Comment by mihaipopescu** [comment]
Nice catch! Could you paste the tokens map from the dump debug info file (`-p FILE` command line option).

**Comment by chrullrich** [comment]
Here: [uncrustify.txt](https://github.com/uncrustify/uncrustify/files/365812/uncrustify.txt)

**Comment by chrullrich** [comment]
Oh, that was from 0.61.3. Here is the same from 0.63: [uncrustify.txt](https://github.com/uncrustify/uncrustify/files/365828/uncrustify.txt)

**Comment by mihaipopescu** [comment]
Cool, could you also try with the latest master ?

**Comment by chrullrich** [comment]
That, too. [uncrustify.txt](https://github.com/uncrustify/uncrustify/files/366047/uncrustify.txt)

**Comment by gmaurel** [comment]
Is it enough to test if prev is CT_COMMA

**Comment by chrullrich** [comment]
It would have to be either "<" or comma, in case it is the first template argument.

**Comment by gmaurel** [comment]
May I add: "if we are in a template"?
