### ISSUE TITLE
Seeing issues after running uncrustify on my codebase, Please respond ASAP

### ISSUE THREAD

**Issue by hemanthltts** [uncrustify/uncrustify#3231]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by mwoehlke-kitware** [comment]
What's the question here?

**Comment by hemanthltts** [comment]
i am using uncrustify tool on centOS machine. i wanted to edit configfile i.e wanted to add some parameters.

 1 # The uncrustify sources are uncrustified with this config file.
  2 #using 0.70.0
  3
  4 # General options
  5 code_width                                = 80
  6 output_tab_size                           = 8
  7 tok_split_gte                             = true

i wanted to add line number 5 in my config_file and run it on my code base. i wanted to have 80 characters limit per line.
But my additions of new parameters in my config file is not getting considered. how do i achieve it.

**Comment by guy-maurel** [comment]
why not?
Provide the files, the outputs, using
`uncrustify -c your_config_file.cfg -f your_input_file.cpp  -p p.txt  -L A 2>A.txt`

**Comment by hemanthltts** [comment]
uncrustify -c ../Uncrustify.cfg  --no-backup $(find  -name "*.[ch]") ---> This is the command i use to run on my entire code base.

I have one more issue, while running uncrustify on some of my .c or .h files, i am getting issues.. 

^M is getting added. how to solve this issue.. and i see segmentation fault also

 f.h>^M#ifdef AMR_WB^M#include <gsm26_201.h>^M#endif^M^M#include <drcipher.h>^M#include <drviterb.h>^M#include <mcbursts.h>^M#include   <mcchannels.h>^M^M#include <mcamrcodecrate.h>^M#include <mcamrconvolve.h>^M#include <mcamrcyclic.h>^M#include <mcamrdecode.h>^M#inclu  de <mcamribsdecode.h>^M#include <mcamrmcmrim.h>^M#include <mcamrutility.h>^M#include <mcleave.h>^M#include <mcutility.h>^M^M#include   <amr_frame.h>^M#include <gsmbuf.h>^M#include <gsmdatds.h>^M^M#ifndef _CEVA1_EQ_BURST^M#include "ipa_printf.h"^M#else^M#include "dprin

**Comment by hemanthltts** [comment]
I am seeing new issues after running uncrustify tool on my codebase.  In few files special characters  (^M) are getting added after running uncrustify tool.   could some one help why i am facing this type of issues.

**Comment by hemanthltts** [comment]
The uncrustify sources file is of version #using 0.70.0

**Comment by hemanthltts** [comment]
uncrustify -c Uncrustify.cfg --no-backup $(find  -name "*.[ch]")  is the command i am running on my code base.

**Comment by hemanthltts** [comment]
i dont see this parameter in my config file. btw i am using #using 0.70.0 version uncrustify file

**Comment by hemanthltts** [comment]
1 # The uncrustify sources are uncrustified with this config file.
  2 #using 0.70.0
  3
  4 # General options
  5 code_width                                = 80
  6 output_tab_size                           = 8
  7 tok_split_gte                             = true
  8 newlines                                  = auto

Anyways i have added the  newlines = auto line in my config file, but still i see the same issue

**Comment by hemanthltts** [comment]
Wanted to add  one thing from my end.
Steps used by me to use this tool.
1) i have pulled out the latest uncrustify  code base using git clone https://github.com/uncrustify/uncrustify.git  
2) Then i started using forUncrustifySources.cfg as my configuration file which is of version 
# The uncrustify sources are uncrustified with this config file.
  2 using 0.70.0
and i am hitting all this issues.
FYI.. I didn't do anything other than the above two mentioned steps. Is my procedure correct ?

**Comment by hemanthltts** [comment]
Hi anyone can help here ?

**Comment by gmaurel** [comment]
2 is not OK.
The file  forUncrustifySources.cfg is to uncrustify the uncrustify sources.
You need to write your own configuration file.
A description of all the options can be found at
  etc/defaults.cfg
