### ISSUE TITLE
Uncrustify adds space after star of function typedef

### ISSUE THREAD

**Issue by eugene-so** [uncrustify/uncrustify#3232]
I would like to be able to align the pointer star to the variable type in general, but ignore the star in function typedefs.

Uncrustify_d-0.72.0-11-a9e32ac3

[uncrustify.zip](https://github.com/uncrustify/uncrustify/files/6793049/uncrustify.zip)

**Comment by guy-maurel** [comment]
please push the output you wanted to get

**Comment by eugene-so** [comment]
[uncrustify_with_expected.zip](https://github.com/uncrustify/uncrustify/files/6811965/uncrustify_with_expected.zip)

**Comment by guy-maurel** [comment]
you have specify:
`sp_after_ptr_star = force`
which applies here

**Comment by eugene-so** [comment]
Is there any way to configure it so that the variable pointers get aligned to the type while the function pointer is left alone as indicated in my expected output?  Imo, these are not the same thing.

**Comment by guy-maurel** [comment]
to speak about "align" you need at least 2 lines of code.
or you speak about adding/removing a space at some places.
Please try to give us a new source and the expected output.

**Comment by Jorengarenar** [comment]
Eugene wants Uncrustify to apply this style:
```
void (*foo)() = func;       // star to name
int* x;                     // star to type
```

Currently, if `type* name`, then function pointers get transformed into `type (* name)`
