### ISSUE TITLE
Interprets "Type *" as WORD and ARITH: sp_arith=force adds space where it shouldn't

### ISSUE THREAD

**Issue by antoniojpfernandes** [uncrustify/uncrustify#3233]
Expected result
```c
static GDBusProxy *previewer_v2_proxy = NULL;
```

Generated result
```c
static GDBusProxy * previewer_v2_proxy = NULL;
```

A space is added after the "*", which shouldn't happen given `sp_after_ptr_star = remove`.
In the debug file you can find that "GDBusProxy *" is misinterpretted as WORD ARITH. As a consequence, the space is added as per `sp_arith=force = force`.

Removing the `static` qualifier doesn't fix the bug.

Inserting a dummy statement above this line does fix the bug.

I didn't manage to find a minimal test file where this is reproducible.
This is the full file where I found the bug: https://gitlab.gnome.org/GNOME/nautilus/-/blob/fd2e7dfdead8e9046884ca21dcad034e160dae68/src/nautilus-previewer.c

And here is the [debug file](https://gist.github.com/antoniojpfernandes/d44ff49bfa17dc803423232ec4318af5)

current version: Uncrustify_d-0.73.0_f

working version: Uncrustify_d-0.72.0_f

**Comment by guy-maurel** [comment]
PR #3235 is a bugfix proposal.
Please test it and report.

**Comment by ondrejholy** [comment]
I can confirm that the linked pull request fixes the issue for Nautilus, thanks @guy-maurel.
