### ISSUE TITLE
Issue #2236 still present in version 0.73

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#3238]
See #2236  for reference.

**Comment by guy-maurel** [comment]
See #2170
You need to use the option:
# How to apply align_assign_span to function declaration "assignments", i.e.
# 'virtual void foo() = 0' or '~foo() = {default|delete}'.
#
# 0: Align with other assignments (default)
# 1: Align with each other, ignoring regular assignments
# 2: Don't align
align_assign_decl_func = 1

**Comment by chris-mich** [comment]
This seems to work!!  Thank you, case closed. :-)
