### ISSUE TITLE
cannot easily build uncrustify as a meson subproject

### ISSUE THREAD

**Issue by alexttx** [uncrustify/uncrustify#3256]
There are some indirect dependencies that make it a challenge to build uncrustify as a meson subproject.  These dependency issues can be exposed by trying to "make" an individual object file.  For example:

```
$ make -C build src/punctuators.o
/home/test/uncrustify/src/options.h:33:10: fatal error: option_enum.h: No such file or directory
```

When I run make normally (make -C build), everything builds fine.  But when building uncrustify as a meson subproject, the build fails because it hasn't built all the generated source files before trying to compile the object files.

Version info:
```
uncrustify: tag uncrustify-0.73.0
cmake: 3.19.7
python: 3.9.2
meson: 0.58.2
ninja: 1.10.0.git.kitware.jobserver-1
make: GNU Make 4.3
```

Here's a very simple script to demonstrate the issue.  Copy of script and script output also attached.
```
set -xe
meson --version
python --version
ninja --version
cmake --version
rm -fr repro
mkdir -p repro/src repro/src/subprojects
cat > repro/src/meson.build <<'EOF'
project('experiment', ['c'], version: '1.0.0', meson_version: '>=0.58.0', )
cmake = import('cmake')
uncrustify_options = cmake.subproject_options()
uncrustify_options.add_cmake_defines({ 'NoGitVersionString': true })
uncrustify_proj = cmake.subproject('uncrustify', options: uncrustify_options)
EOF

cat > repro/src/subprojects/uncrustify.wrap <<'EOF'
[wrap-git]
url = /home/atomlinson/w/src/experiments/uncrustify-bug/uncrustify.git
revision = uncrustify-0.73.0
EOF

rm -fr repro/build
meson setup repro/src repro/build
meson compile -C repro/build
```

![](https://sbu-web/icons/script.gif)

![](https://sbu-web/icons/text.gif)

**Comment by alex-tomlinson** [comment]
Investigating as a possible issue with meson.   Can hold this here for a few days while I investigate or close as you see fit.

**Comment by alex-tomlinson** [comment]
For reference:  https://github.com/mesonbuild/meson/issues/9062

**Comment by tristan957** [comment]
@guy-maurel I would be interested in converting Uncrustify to Meson for the project or adding it as an alternative build system (maintaining two build systems sounds not fun though). Otherwise I could just write a Meson port and keep it in https://github.com/mesonbuild/wrapdb

**Comment by gmaurel** [comment]
What sould happens?
Please give us some more details.

**Comment by tristan957** [comment]
Essentially one of two things could happen.

1. I rip out the old CMake build system for a new Meson-based build system. If you are not familiar with Meson, please check it out at https://mesonbuild.com.
2. Meson has many Meson ports of popular pieces of software in what is called the WrapDB https://mesonbuild.com/Wrapdb-projects.html. For instance lz4, xxhash, etc. I can create a Meson-based build system for Uncrustify that exists entirely outside the repository of Uncrustify.

Cons of 1: new way to build uncrustify. Can be daunting if people do not like change.
Cons of 2: maintaining 2 build systems sucks, but the maintenance burden of the Meson-based build system would be on the community instead of the Uncrustify maintainers.

**Comment by alex-tomlinson** [comment]
Be aware that Meson does not support Make as a backend builder.  It uses Ninja by default.
https://mesonbuild.com/FAQ.html#why-is-there-not-a-make-backend

**Comment by guy-maurel** [comment]
what about the tests (about 1400 with ctest) ?
Why not both system ? The user/developper may choose one.
Give the opportunity to compare the two.

**Comment by tristan957** [comment]
@guy-maurel in the case of Meson replacing CMake, the tests would have to be converted to Meson. `meson test` instead of `ctest`.

> Why not both system?

Seems like a lot of work to keep both build systems in-sync.

**Comment by guy-maurel** [comment]
Please, let us go on.
Create a new Pull Request.
