### ISSUE TITLE
Need an option to add spaces around "forever" loops but not between the semicolons

### ISSUE THREAD

**Issue by alexhenrie** [uncrustify/uncrustify#3280]
Config file:

```
sp_before_semi_for_empty = add
sp_after_semi_for_empty = add
```

Example code:

```
int main(void)
{
	for (; ;)
		continue;
}
```

Output:

```
int main(void)
{
	for ( ; ; )
		continue;
}
```

What I'm looking for:

```
int main(void)
{
	for ( ;; )
		continue;
}
```

So, Uncrustify has the options to add a space before the first semicolon and after the second semicolon, but it has no option to remove the space in the middle.

**Comment by guy-maurel** [comment]
Sorry, but the option
  `sp_before_semi_for_empty`
does what you wish.

**Comment by alexhenrie** [comment]
Look more closely: There are three places for spaces. `sp_before_semi_for_empty` adds a space on the left, but it doesn't remove the space in the middle.

**Comment by gmaurel** [comment]
I get
```.log
Uncrustify_d-0.73.0-126-3bfd456e
...
do_space(425): first->orig_line is 3, first->orig_col is 14, first->text() is ';', [SEMICOLON/FOR] <===>
           second->orig_line is 3, second->orig_col is 19, second->text() is ';', [SEMICOLON/FOR] : rule sp_before_semi_for_empty[line 425]
 rule = REMOVE @ 0 => 15

```

**Comment by alexhenrie** [comment]
What config file are you using that adds the space on the left AND removes the space in the middle?

**Comment by guy-maurel** [comment]
Your example has no space on the left.
The config file has only one line:
  `sp_before_semi_for_empty = remove`

**Comment by alexhenrie** [comment]
I think you were looking at "Output" instead of "What I'm looking for" in my first comment. At any rate, the [test case](https://github.com/uncrustify/uncrustify/pull/3281/files#diff-7555e57a3f6e551a8da8f208650faf2575da6f0bae11a34f6d19e41ac41df342) included in the pull request definitely has `for ( ;; )`.
