### ISSUE TITLE
indent_member_single=true gives unexected indent in the presense of leading C-style comment

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#3294]
The following test case shows that indent_member_single=true gets confused by leading comments in a ternary expression.
Yes, this seems rather contrived, but turned up in our code, and I have simplified the case to show one example with comments, which is formatted incorrectly, and one example without comments, which is formatted correctly.

Test case: 
```
#include <vector>

std::vector<int> x;

void f1()
{
   int v = x.empty()
         /**/ ? x.size()
         /**/ : x.size();
}

void f2()
{
   int v = x.empty()
         ? x.size()
         : x.size();
}
```
Generated results
```
#include <vector>

std::vector<int> x;

void f1()
{
	int v = x.empty()
	        /**/ ? x.size()
	                /**/ : x.size();
}

void f2()
{
	int v = x.empty()
	 ? x.size()
	 : x.size();
}
```
Expected output 
```
#include <vector>

std::vector<int> x;

void f1()
{
	int v = x.empty()
	      /**/ ? x.size()
	      /**/ : x.size();
}

void f2()
{
	int v = x.empty()
	 ? x.size()
	 : x.size();
}
```

[debug.txt](https://github.com/uncrustify/uncrustify/files/7028097/debug.txt)

**Comment by gmaurel** [comment]
You need the option:
indent_inside_ternary_operator  = true

PR #3478 is a bugfix proposal.
Please test it and report.
