### ISSUE TITLE
User defined types cause unexpected indent in function declarations

### ISSUE THREAD

**Issue by arneforlie** [uncrustify/uncrustify#3308]
PR #3302 introduced a fix for not recognising user defined types (by means of using) correctly in function declaration (reported as issue #3291)
However, the solution chosen is in my opinion too simple and does not solve the underlying problem.
I do not understand the internals of Uncrustify, but I fear that the current approach of recognising types and adding to a them to a table of known types, is futile.

This example shows how a type declared with typedef, struct, and class are not recognized by the current solution. In addition, defining the type in a header file makes it unknown to Uncrustify.

```
typedef int Bar1;

struct Bar2
{
   int f;
};

class Bar3
{
   int f;
};

#include "Bar4.h"

void
foo1(Bar1);

void
foo2(Bar2);

void
foo3(Bar3);

void
foo4(Bar4);
```
Generated result
```
typedef int Bar1;

struct Bar2
{
	int f;
};

class Bar3
{
int f;
};

#include "Bar4.h"

void
        foo1(Bar1);

void
        foo2(Bar2);

void
        foo3(Bar3);

void
        foo4(Bar4);
```

The expected output is identical to the input.

[debug.txt](https://github.com/uncrustify/uncrustify/files/7111620/debug.txt)

**Comment by gmaurel** [comment]
`This example shows how a type declared with typedef, struct, and class are not recognized `
Yes.
It was a first version. The next should follows, but your comment is very precious and show
some more problems. My approach was not "pretty".
I now propose to revert PR #3302, to get time to find a better solution.
Please comment! Thanks for all the examples.

**Comment by arneforlie** [comment]
I agree with you, PR #3302 should be reverted because it only solves one (rather artificial) case.
The long term solution must be that Uncrustify is taught to recognise a word as a TYPE and not as a WORD in function declarations so that works generally.
Looking forward to your next solution on this issue.

**Comment by gmaurel** [comment]
reverted
