### ISSUE TITLE
C++ parameter pack ellipsis - unexpected space being added after ellipsis

### ISSUE THREAD

**Issue by caballist-accsys** [uncrustify/uncrustify#3309]
Input file content (test.h - cannot attach to issue, unsupported filetype)

```
template<typename ...ARGS> void test(ARGS&&... args) {}
```

generated result

```
template<typename ... ARGS> void test(ARGS&&... args) {}
```

expected result

```
template<typename ...ARGS> void test(ARGS&&... args) {}
```

Version: Uncrustify-0.73.0-159-81b1bc77-dirty
Originally found using version 0.71.0

There doesn't appear to be an option which controls this behaviour. I've changed all "= add/=force/= true" options to "= ignore/=false" to try and isolate the behaviour to a specific option without success. This behaviour appears to be built in.

[debug.txt](https://github.com/uncrustify/uncrustify/files/7120916/debug.txt)

**Comment by guy-maurel** [comment]
what is ARGS at line 1, column 22 ?
Is it a type?

**Comment by caballist-accsys** [comment]
ARGS is the name of the template parameter pack. It isn't anything but a name with which the parameter pack can be made reference to. ARGS could be 'XXX', 'YYY', 'Ts' or any other valid template parameter name.

ARGS is equivalent to the name 'ARG' in the following snippet, but here there is no '...' prefix, so ARG does not denote a pack.

```
template<typename ARG> void test(ARG arg) {}
```

**Comment by guy-maurel** [comment]
PR #3312 is a bugfix proposal.
Please test it and report.

**Comment by caballist-accsys** [comment]
Thanks for looking into this... the issue is still active with your commit.

I've added:

```
sp_ellipsis_parameter_pack = ignore
sp_parameter_pack_ellipsis = ignore
```

to my uncrustify.cfg and the executable compiled from your commit does not warn about "unknown options", so I'm using your patch... I get the same output as before

```
../uncrustify/build/uncrustify -c ../uncrustify.cfg -p debug.txt -l CPP -f test.h
Parsing: test.h as language CPP
template<typename ... ARGS> void test(ARGS&&... args) {}
```

[debug.txt](https://github.com/uncrustify/uncrustify/files/7179460/debug.txt)

**Comment by gmaurel** [comment]
Please, test it again. Thanks for the messages.

**Comment by caballist-accsys** [comment]
I am now getting the expected/desired output. Thank you very much.

../uncrustify/build/uncrustify -c ../uncrustify.cfg -p debug.txt -l CPP -f test.h
Parsing: test.h as language CPP
template<typename ...ARGS> void test(ARGS&&... args) {}
