### ISSUE TITLE
Fully parenthesize Boolean expressions even outside if and while

### ISSUE THREAD

**Issue by mxmlnkn** [uncrustify/uncrustify#3316]
There already is a `mod_full_paren_if_bool` option but it won't modify Boolean in assignments no in return statements and other things, which I'm currently forgetting. It would be nice if that capability could be added maybe as an extra option.

### `uncrustify.cfg`

```shell
# Whether to fully parenthesize Boolean expressions in 'while' and 'if'
# statement, as in 'if (a && b > c)' => 'if (a && (b > c))'.
mod_full_paren_if_bool          = true     # true/false
```

### `bool-test.cpp`

```c++
#include <iostream>

bool
foo()
{
    const int i = 3;

    if ( i == 2 || i == 3 || i == 5 ) {
        std::cerr << "Very small prime!\n";
    }

    const auto isSmallPrime = i == 2 || i == 3 || i == 5 || i == 7 || i == 11;

    return isSmallPrime || i == 13 || i == 17 || i == 19;
}
```

### Uncrustifyed Output

```c++
#include <iostream>

bool
foo()
{
	const int i = 3;

	if ( (i == 2) || (i == 3) || (i == 5) ) {
		std::cerr << "Very small prime!\n";
	}

	const auto isSmallPrime = i == 2 || i == 3 || i == 5 || i == 7 || i == 11;

	return isSmallPrime || i == 13 || i == 17 || i == 19;
}
```

### Expected output with hypothetical `mod_full_paren_assign_bool = true` and `mod_full_paren_return_bool = true` options

```c++
#include <iostream>

bool
foo()
{
	const int i = 3;

	if ( (i == 2) || (i == 3) || (i == 5) ) {
		std::cerr << "Very small prime!\n";
	}

	const auto isSmallPrime = ( i == 2 ) || ( i == 3 ) || ( i == 5 ) || ( i == 7)  || ( i == 11 );

	return isSmallPrime || ( i == 13 ) || ( i == 17 ) || ( i == 19 );
}
```

current version: Uncrustify-0.72.0_f

**Comment by guy-maurel** [comment]
Danke für den Vorschlag

**Comment by guy-maurel** [comment]
PR #3483 is a bugfix proposal.
Please test it and report.

**Comment by mxmlnkn** [comment]
Thank you for implementing this!

However, when I tried it (`Uncrustify_d-0.74.0-120-0664cace`) out, I noticed some problems:

## There is a segmentation fault with this trimmed down test file:

```c++
#include <algorithm>
#include <utility>
#include <vector>

void
foo()
{
    std::vector<std::pair<int, int> > vector;

    const auto result = std::max_element(
        vector.begin(), vector.end(),
        [] ( const auto& a, const auto& b ) {
            return std::make_tuple( a.second, a.first ) < std::make_tuple( b.second, b.first );
        } );

    const auto element = result == vector.end() ? -1 : result->first;
}
```

Removing anything more makes the segfault disappear, so it seems like it chokes on the combination of a lambda and a ternary. I can try and send a backtrace if you cannot reproduce it with this.

## It applies some unwanted transformations

```diff
-        for ( ; endEvent != events.end(); ++endEvent, ++lastEvent ) {
+        for ( (; endEvent != events.end(); ++endEvent ), ++lastEvent ) {
```

The introduced change results in the compilation throwing an error.

**Comment by gmaurel** [comment]
Please, make a new Issue of it
AND
add the configuration file, because I cannot reproduce
