### ISSUE TITLE
nl_constr_colon = force not working

### ISSUE THREAD

**Issue by mxmlnkn** [uncrustify/uncrustify#3319]
It seems to me like `pos_constr_colon = trail` and `nl_constr_colon = force` are ignored in my specific case. Using `nl_constr_colon = remove` actually shows an effect but not the desired one.

### `uncrustify.cfg`

```shell
# Add or remove newline after each ',' in the constructor member
# initialization. Related to nl_constr_colon, pos_constr_colon and
# pos_constr_comma.
nl_constr_init_args             = force    # ignore/add/remove/force

# Add or remove newline around a class constructor colon. The exact position
# depends on nl_constr_init_args, pos_constr_colon and pos_constr_comma.
nl_constr_colon                 = force    # ignore/add/remove/force

# The position of the comma in the constructor initialization list.
# Related to nl_constr_colon, nl_constr_init_args and pos_constr_colon.
pos_constr_comma                = trail    # ignore/break/force/lead/trail/join/lead_break/lead_force/trail_break/trail_force

# The position of colons between constructor and member initialization.
# Related to nl_constr_colon, nl_constr_init_args and pos_constr_comma.
pos_constr_colon                = trail    # ignore/break/force/lead/trail/join/lead_break/lead_force/trail_break/trail_force
```

### `constructor-colon-test.cpp`

```c++
struct SimpleStruct
{
    SimpleStruct( bool input )


        :


        result( input ),


        foo( input )
    {}

public:
    const bool result;
    const bool foo;
};
```

### Uncrustifyed Output

```c++
struct SimpleStruct
{
	SimpleStruct( bool input )


		:


		result( input ),
		foo( input )
        {
	}

public:
	const bool result;
	const bool foo;
};
```

### Expected output

```c++
struct SimpleStruct
{
	SimpleStruct( bool input )  :
		result( input ),
		foo( input )
	{
	}

public:
	const bool result;
	const bool foo;
};
```

current version: Uncrustify-0.72.0_f

**Comment by guy-maurel** [comment]
you need to use the option:
`nl_max = 1`

**Comment by mxmlnkn** [comment]
This obviously is not the solution as it deletes ALL blank lines everywhere. I only want them deleted for the member initializer lists.

**Comment by guy-maurel** [comment]
Yes, you are right.
But it is the solution.
First suppress all the newlines with a simple configuration file,
Second, introduce the new lines you wanted to have.

**Comment by gmaurel** [comment]
It would be necessary to define the context where the "too much" newlines are to be removed.
I this example, we have a context "struct" where many newlines are not welcome and should be removed.
What is about other contexts such as "for", "if"?

**Comment by bertwesarg** [comment]
Maybe `ignore/add/remove/force` is not the best option range for these `nl` options, how about:
- -1 – ignore
- 0 – remove
- N>0 – force N newlines

**Comment by rwiesenfarth** [comment]
Ran into the same issue.
The cause seems to be that the colon of the struct's constructor is not classified as CONSTR_COLON, but as CLASS_COLON - and thus not qualifies for the application of nl_constr_colon.
A simple example, containing both a class and a struct is attached, together with uncrustify's output.
[structAndClass.h.txt](https://github.com/uncrustify/uncrustify/files/10134765/structAndClass.h.txt)
[debug.log](https://github.com/uncrustify/uncrustify/files/10134767/debug.log)
