### ISSUE TITLE
'noexcept' keyword alters unrelated behaviours when formatting lambda captures

### ISSUE THREAD

**Issue by caballist-accsys** [uncrustify/uncrustify#3321]
Input test file (test1.h)

```
auto l1 = []() {};
auto l2 = [&]() {};
auto l3 = []() noexcept {};
auto l4 = [&]() noexcept {};
```

expected output

```
auto l1 = []() {
          };
auto l2 = [&]() {
          };
auto l3 = []() noexcept {
          };
auto l4 = [&]() noexcept {
          };
```

actual output

```
auto l1 = []() {
          };
auto l2 = [&]() {
          };
auto l3 = [] () noexcept {};
auto l4 = [&]() noexcept {};
```

Note: l3 has an extra space inserted between ```[]()``` and both l3 and l4 empty function bodies do not get split.

Version: Uncrustify-0.73.0-168-f20a083e-dirty
also present in: Uncrustify-0.71.0

for the purposes of this test, uncrustify.cfg was generated with 

```
uncrustify --show-config > uncrustify.cfg
```

[debug.txt](https://github.com/uncrustify/uncrustify/files/7218130/debug.txt)

**Comment by guy-maurel** [comment]
uncrustify.cfg was generated with...
but not used look at debug.txt
the input file is cpp, not h as written above.
What is correct?

**Comment by caballist-accsys** [comment]
I'm a little bit baffled... 

```
uncrustify --show-config > uncrustify.cfg
```

produces a config file with all options set to their default value. And debug.txt states

```
# option(s) with 'not default' value: 0
```

which is what I would expect - all the options in the uncrustify.cfg are the defaults. So debug.txt doesn't contain anything regarding the content of uncrustify.cfg.

if I change a random setting eg. "sp_inside_paren_cast = force" in uncrustify.cfg then debug.txt flags that up...

```
# Uncrustify-0.73.0-168-f20a083e-dirty
sp_inside_paren_cast            = force
# option(s) with 'not default' value: 1
```

so as far as I can see uncrustify.cfg is being used and has the expected content. Please elaborate if I'm getting something wrong.

I've explicitly passed "-l CPP" on the command line. Apologies, I never checked that debug.txt contained the actual command line parameters being supplied. That appears to me be a bit of an oversight in the output of debug.txt.

**Comment by guy-maurel** [comment]
PR #3332 is a bugfix proposal.
Please test it and report.

**Comment by caballist-accsys** [comment]
PR produces the expected output.

Thank you
