### ISSUE TITLE
[C++] Align variable initializer list 

### ISSUE THREAD

**Issue by xdrm-io** [uncrustify/uncrustify#3323]
#### Config
```ini
# version: Uncrustify-0.72.0_f

align_var_def_span = 1
align_assign_span  = 1
```

#### Input

```c++
void init_expr(){
	const int a = 1;
	std::string bb = { 't', 'w', 'o' };
	std::string ccc = "3";
	double dddd = 4;
}
void init_list(){
	const int a { 1 };
	std::string bb { 't', 'w', 'o' };
	std::string ccc { "3" };
	double dddd { 4 };
}
```

#### Expected output

```c++
void init_expr(){
	const int   a    = 1;
	std::string bb   = { 't', 'w', 'o' };
	std::string ccc  = "3";
	double      dddd = 4;
}
void init_list(){
	const int   a    { 1 };
	std::string bb   { 't', 'w', 'o' };
	std::string ccc  { "3" };
	double      dddd { 4 };
}
```

#### Actual output

```c++
void init_expr(){
	const int   a    = 1;
	std::string bb   = { 't', 'w', 'o' };
	std::string ccc  = "3";
	double      dddd = 4;
}
void init_list(){
	const int   a { 1 };
	std::string bb { 't', 'w', 'o' };
	std::string ccc { "3" };
	double      dddd { 4 };
}
```

#### Description

I would like `init_list()` parameter initializations to align at the opening braces `{` the same way `init_expr()` aligns at equal signs `=`.

I use this syntax in my project for variables and class attributes. I searched for a suiting configuration but haven't found anything. Is it unavailable in uncrustify or am I missing something ?

Thanks in advance.

#### Attachments

- [debug.txt](https://gist.github.com/xdrm-io/b788cb46a004fb70dd2e40f38ba34c34)

**Comment by guy-maurel** [comment]
You need to use the option:
_align_braced_init_list_span = 1_
to get it.

**Comment by xdrm-io** [comment]
Thank you @guy-maurel for your time, it works well for me.
