### ISSUE TITLE
Space after return type of function pointer gets removed for short names

### ISSUE THREAD

**Issue by bofh69** [uncrustify/uncrustify#3353]
When uncrustifying fil.h:
```c
struct A {
    void (*in)(
        void);
    void (*out)(
        void);
};
```
It says:
"Parsing: fil.h as language C-Header"

I get the following result:
```c
struct A {
    void(*in)(
        void);
    void (*out)(
        void);
};
```
(the space before in `void (*in)` was removed).

I didn't expect any change at all, or at least that in and out are handled the same.

I've tried with 0.72, 0.73 and Uncrustify_d-0.73.0-219-dedc17add

Giving the arguments `-l c`, then it works as expected and the file isn't changed.

Here's the debug output:
[debug.txt](https://github.com/uncrustify/uncrustify/files/7351793/debug.txt)

**Comment by guy-maurel** [comment]
The bug cannot be solve within some days.
_in_ and _out_ are keywords for other languages (C sharp, D, vala, objective C).
Please change the string a little bit, to solve the conflict with other languages.

**Comment by guy-maurel** [comment]
The problem is:
uncrustify has all the used keywords whitin only one list.
A string such as **in**, used by the user in the _example.h file_ .
**in** is only used by the languages LANG_D , LANG_CS,  LANG_VALA, LANG_ECMA and LANG_OC,
but will be found by uncrustify.

I am working on the bug, and introduce a new list for the used language.

**Comment by bofh69** [comment]
@guy-maurel Changing the language to C instead of C-Header solves it though (-l c or adding "file_ext C .c .h" to the config).

I thought the problem was that a C-header was treated like a C++ header here.

**Comment by guy-maurel** [comment]
PR #3399 is a bugfix proposal.
Please test it and report.
