### ISSUE TITLE
Parse error with unnamed bitfields in C code

### ISSUE THREAD

**Issue by RobertoBagnara** [uncrustify/uncrustify#3355]
$ cat p.cfg 
code_width                      = 80
$ cat p.c
struct b
{
  int : 1, : 2;
  int a : 3;
};
$ uncrustify p.c -c p.cfg
Output suffix: .uncrustify
Parsing: p.c as language C
combine_labels(421): p.c:3 unexpected colon in col 12 n-parent=NONE c-parent=NONE l=1 bl=1
$ uncrustify --version
Uncrustify_d-0.73.0-210-89d022f5
$

**Comment by guy-maurel** [comment]
uncrustify doesn't works with more than one variable definition per type,
It works pretty well as:
```.txt
Parsing: RobertoBagnara.c as language C
struct b
{
        int : 1;
        int : 2;
        int a : 3;
};
```

**Comment by RobertoBagnara** [comment]
Thanks: I take note of this limitation.
