### ISSUE TITLE
Doxygen command @param can be processed incorrectly

### ISSUE THREAD

**Issue by elnull** [uncrustify/uncrustify#3357]
When `cmt_align_doxygen_javadoc_tags` is set to `true`, doxygen command `@param` looses opening square brace.

Input:
```cpp
/**
 * @param[out] dest The memory area to copy to.
 * @param[in]  src  The memory area to copy from.
 * @param[in]  n    The number of bytes to copy
 */
void memcpy(void *dest, const void *src, size_t n);
```

Output:
```cpp
/**
 * @param out]  dest The memory area to copy to.
 * @param in]   src  The memory area to copy from.
 * @param in]   n    The number of bytes to copy
 */
void memcpy(void *dest, const void *src, size_t n);
```

Config:
```txt
cmt_align_doxygen_javadoc_tags = true
```

[debug.txt](https://github.com/uncrustify/uncrustify/files/7380605/debug.txt)

**Comment by guy-maurel** [comment]
If you have:
```.txt
/**
 * @Param [out] dest The memory area to copy to.
 * @param [in]  src  The memory area to copy from.
 * @param [in]  n    The number of bytes to copy
 */
void memcpy(void *dest, const void *src, size_t n);
```
the output will be OK.
I don't have experience with Doxygen.
What is correct?

**Comment by elnull** [comment]
I took example from [official manual](https://www.doxygen.nl/manual/commands.html#cmdparam). I think that opening square brace shouldn't be lost anyway.

**Comment by guy-maurel** [comment]
PR #3404 is a bugfix proposal.
Please test it and report.

**Comment by elnull** [comment]
It works for me, thanks.
