### ISSUE TITLE
Too many pointers

### ISSUE THREAD

**Issue by RobertoBagnara** [uncrustify/uncrustify#3359]
The test case comes from the tests of the ack compiler (http://www.cs.vu.nl/ack/).

$ cat p.cfg
code_width                      = 80
$ uncrustify test.c -c p.cfg
Output suffix: .uncrustify
Parsing: test.c as language C
Too many pointers
at line 81, column 33.
Please make a report.
$ uncrustify --version
Uncrustify_d-0.73.0-220-27a3bd91
[test.c.gz](https://github.com/uncrustify/uncrustify/files/7383295/test.c.gz)

**Comment by guy-maurel** [comment]
PR #3391 is a bugfix proposal.
Please test it and report.

**Comment by RobertoBagnara** [comment]
The message is very clear now: thanks!
