### ISSUE TITLE
Parse error: indent_text(4060), indent_text(4062)

### ISSUE THREAD

**Issue by RobertoBagnara** [uncrustify/uncrustify#3360]
The test case comes from https://slixe.de/stash/projects/MAS/repos/libfirm/browse/ir/be/test/compress95.c?at=3232017bf40a3784cf75fc5a17bad8c0d545075b
[compress95.c.gz](https://github.com/uncrustify/uncrustify/files/7383681/compress95.c.gz)

$ cat p.cfg
code_width                      = 80
$ uncrustify compress95.c -c p.cfg
Output suffix: .uncrustify
Parsing: compress95.c as language C
indent_text(4060): size is 3
indent_text(4062): File: compress95.c, open_line is 1285, parent is NONE: Unmatched BRACE_OPEN
indent_text(4060): size is 3
indent_text(4062): File: compress95.c, open_line is 1299, parent is NONE: Unmatched BRACE_OPEN
indent_text(4060): size is 3
indent_text(4062): File: compress95.c, open_line is 1285, parent is NONE: Unmatched BRACE_OPEN
indent_text(4060): size is 3
indent_text(4062): File: compress95.c, open_line is 1299, parent is NONE: Unmatched BRACE_OPEN
indent_text(4060): size is 3
indent_text(4062): File: compress95.c, open_line is 1285, parent is NONE: Unmatched BRACE_OPEN
indent_text(4060): size is 3
indent_text(4062): File: compress95.c, open_line is 1299, parent is NONE: Unmatched BRACE_OPEN
$ uncrustify --version
Uncrustify_d-0.73.0-220-27a3bd91

**Comment by guy-maurel** [comment]
uncrustify is NOT a compiler and doesn't evaluate
#ifdef XENIX_16
Please modify your code to have complete blocks, not split with macro statements

**Comment by RobertoBagnara** [comment]
I understand, thanks.  I am closing the issue (I assume this is what I am supposed to do).
