### ISSUE TITLE
Preprocessor file-level #ifdef influencing whether braces are added in switch statements

### ISSUE THREAD

**Issue by micheleCTDE** [uncrustify/uncrustify#3366]
If a file is contained within a #ifdef global block, braces are not added to switch case/default.
Attachments show a bad and good example. To reproduce:
1) unzip the attachment in two folders.
2) if you wish, run "uncrustify -c config.cfg -f in.h -o out.h -ds dump -L A 2>log.txt" in each folder. This step is not necessary since the attachment already contains the output, log and dump files
3) compare the results between the two folders. The input files are the same except that the "bad" example has a global #ifdef protection guard in it. Note the missing braces around the "default" block in the switch. Same applies for case blocks (not shown in the attached files).

I will look into this issue, so this is only for reporting and for the record. I will propose a PR when I get a fix done.

[test_bad.tar.gz](https://github.com/uncrustify/uncrustify/files/7443167/test_bad.tar.gz)
[test_good.tar.gz](https://github.com/uncrustify/uncrustify/files/7443168/test_good.tar.gz)

**Comment by gmaurel** [comment]
look at #3336

**Comment by micheleCTDE** [comment]
As further update, the problem seems to happen when the first line of the file is a preprocessor command (like #ifdef or #define).

**Comment by micheleCTDE** [comment]
> look at #3336

Thanks Guy, somehow I had missed this message. I am going to look at this problem this weekend, hopefully there is an easy fix for it :-)

**Comment by micheleCTDE** [comment]
PR #3389 is a proposed fix for this.

**Comment by micheleCTDE** [comment]
Fixed by above PR, which has now been merged.
