### ISSUE TITLE
Missing versions in spack

### ISSUE THREAD

**Issue by briederer** [uncrustify/uncrustify#3400]
I recently moved all my package management on my Mac from [brew](https://brew.sh/index_de) to [spack](https://spack.io) and realised that the spack repos are not well maintained.

Therefore I added the most recent versions and a patch for `v0.73`in spack/spack#27621.

However if the developers of uncrustify don't want it to be published in spack let me know.

**Comment by bernd1995** [comment]
Also I would be willing to keep this updated in the future and adding future releases to spack in case this is helpful.

**Comment by gmaurel** [comment]
I am the maintainer of uncrustify.
Yes, it is fine.

**Comment by bernd1995** [comment]
Okay than I'll add you as the maintainer in the spack file. Also will close this issue when the PR gets merged.

Thanks for the great work on uncrustify by the way 😊

**Comment by dundargoc** [comment]
> Also will close this issue when the PR gets merged.

:thinking:

@micheleCTDE lol you can close this :)

**Comment by briederer** [comment]
Sorry I thought the reference in the PR would close it automatically.
