### ISSUE TITLE
Handling of CT_ASSIGN_DEFAULT_ARG with align_assign_span and align_assign_decl_func

### ISSUE THREAD

**Issue by rwiesenfarth** [uncrustify/uncrustify#3405]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Version: Uncrustify-0.74.0-2-e6b16b2d

I am starting with the default configuration and this input:

```
class CreationDialog : public QDialog
{
  public:
    // These assignments (CT_ASSIGN_DEFAULT_ARG) should not be aligned...
    CreationDialog( QWidget *parent = 0, QString title = "", double doSpacing = 1.,
      QStringList names = QStringList() << "",
      QStringList processedFiles = QStringList() << "", bool BatchMode = false );

    void setFoo( double unit, const QString &unitString )
    {
      // ...but these (CT_ASSIGN) should
      m_unit = unit;
      m_unitString = unitString.simplified();
    }
};
```

Setting align_assign_span=1 leads to this:

```
class CreationDialog : public QDialog
{
public:
// These assignments (CT_ASSIGN_DEFAULT_ARG) should not be aligned...
CreationDialog( QWidget *parent            = 0, QString title = "", double doSpacing = 1.,
                QStringList names          = QStringList() << "",
                QStringList processedFiles = QStringList() << "", bool BatchMode = false );

void setFoo( double unit, const QString &unitString )
{
	// ...but these (CT_ASSIGN) should
	m_unit       = unit;
	m_unitString = unitString.simplified();
}
};
```

Adding align_assign_decl_func=2 changes the output to

```
class CreationDialog : public QDialog
{
public:
// These assignments (CT_ASSIGN_DEFAULT_ARG) should not be aligned...
CreationDialog( QWidget *parent = 0, QString title = "", double doSpacing = 1.,
                QStringList names = QStringList() << "",
                QStringList processedFiles = QStringList() << "", bool BatchMode = false );

void setFoo( double unit, const QString &unitString )
{
	// ...but these (CT_ASSIGN) should
	m_unit       = unit;
	m_unitString = unitString.simplified();
}
};
```

It seems that align_assign_decl_func not only matches CT_ASSIGN_FUNC_PROTO, but also CT_ASSIGN_DEFAULT_ARG.

What I would like to have is to align "standard" assignments (CT_ASSIGN) and - ideally - function prototypes (CT_ASSIGN_FUNC_PROTO), but definitely not default arguments (CT_ASSIGN_DEFAULT_ARG). Is there an option to achieve this?

**Comment by guy-maurel** [comment]
We have three categories of assignment, internaly taged with:
```.txt
       CT_ASSIGN
       CT_ASSIGN_DEFAULT_ARG
       CT_ASSIGN_FUNC_PROTO
```
If you want to align, you use the option _align_assign_span_ .

_align_assign_decl_func_ works for both  CT_ASSIGN_DEFAULT_ARG and CT_ASSIGN_FUNC_PROTO.
Your example has no CT_ASSIGN_FUNC_PROTO, so you cannot see the differences.
