### ISSUE TITLE
Assigment operator "=>" is not recognized and is formatted to "= >"

### ISSUE THREAD

**Issue by PawelWozniak** [uncrustify/uncrustify#3412]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

I am using Uncrustify to format Salesforce Apex language with pretty good results however I found today an issue with Map values assignment. Apex is treated as JAVA and formated according to JAVA rules.
Code:
```	
	static final Map<String, String> ACCOUNTING_INDICATOR_MAP = new Map<String, String> {
		'Billable' => '99', 'KBM1' => '01', 'KBM3' => '03', 'KBM2' => '02', 'ZKB4' => '04'
	};
```
is formatted to:
```
	static final Map<String, String> ACCOUNTING_INDICATOR_MAP = new Map<String, String> {
		'Billable' = > '99', 'KBM1' = > '01', 'KBM3' = > '03', 'KBM2' = > '02', 'ZKB4' = > '04'
	};
```
so => is changed to =[space]>
Which is not accepted by the compiler and throws an error on compile.

I found by experimentation that the rule which is responsible for this is:
```
# Add or remove space around assignment operator '=', '+=', etc.
sp_assign                       = force    # ignore/add/remove/force/not_defined
```
When set to ignore it won't change => when set to add/force then = gets spaces around and become = >

The expected solution is to treat => as an operator and don't modify it when such an option is turned on.

My Uncrsutify version is 0.74, the same happen with 0.73f

**Comment by gmaurel** [comment]
uncrustify doesn't support Apex

**Comment by PawelWozniak** [comment]
@gmaurel how big effort is it to add another language? I could involve in supporting Apex.
