### ISSUE TITLE
Crash with one-liner struct

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#3414]
Config: 
```
# Uncrustify-0.74 (win64 official version)
align_func_proto_span    = 1
align_single_line_func   = true
align_single_line_brace  = true
nl_func_leave_one_liners = true
```
Input: 
```
namespace
{
struct S { void f() {} };
}
```

Uncrustify will crash trying to process this code with this specific sets of parameters.

**Comment by jodyhagins** [comment]
The same change suggested for #3413 fixes this crash as well.  Here is the generated output

```
namespace
{
struct S { void f() {} };
}
```

If you think this resolves both of these issues, I'll submit a pull request - though it would be nice to verify more than just that it no longer crashes.

However, all the existing tests still pass with this change, so I assume it will be ok - at least it is better than crashing...
