### ISSUE TITLE
Regression 0.74 -> 0.72

### ISSUE THREAD

**Issue by LeHibou2** [uncrustify/uncrustify#3415]
In 0.74:

The option  `nl_after_semicolon = true` will fail with that contruct:

```
for ( auto b = vector.begin(), b_end = vector.end() - 1; b < b_end; ++b ){
...
}
```
Will be transformed to

```
for ( auto b = vector.begin(), b_end = vector.end() - 1; 
        b < b_end; 
        ++b ){
         ...
}
```

It will create a new line at every semi colons, even if it is inside a for block. 
Doesn't occur with 0.72.

Thanks

**Comment by alexhenrie** [comment]
What do you have `code_width` set to?

**Comment by LeHibou2** [comment]
It was not defined.

So, I tried the option with value 0 and 2000 before answering: no effect :)

**Comment by gmaurel** [comment]
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!
Which OS are you using?
I get, under Linux Mint:
```.log
Uncrustify_d-0.74.0-21-b9dc602c
normal
do_source_file(1505): Parsing: LeHibou2.cpp as language CPP
for ( auto b = vector.begin(), b_end = vector.end() - 1; b < b_end; ++b ) {
/* ... */
}
```

**Comment by LeHibou2** [comment]
Thanks!
Debian 11 but I downloaded and used the latest git.
I will check again, maybe an old configuration option is messing everything up.

Time to start over again I guess! I will report here once done ;)

**Comment by LeHibou2** [comment]
Okay... it is QtCreator messing up the output of uncrustify..

Sorry for the bump..
