### ISSUE TITLE
Alignment on assignment not working with multiple assignments.

### ISSUE THREAD

**Issue by micheleCTDE** [uncrustify/uncrustify#3422]
uncrustify b9dc602c.
If multiple assignments are used in the same line, alignment of the following lines doesn't work correctly.

Input
```
void main()
{
        unsigned long uncompressed_size = 0, compressed_size = 0;
        char *data_buffer1 = NULL;

        unsigned long uncompressed_size = 0;
        char *data_buffer2 = NULL;
}
```

Output:
```
void main()
{
        unsigned long uncompressed_size = 0, compressed_size = 0;
        char         *data_buffer1 = NULL;

        unsigned long uncompressed_size = 0;
        char         *data_buffer2      = NULL;
}
```

Expected: same alignment of assignment for both data_buffer1 and data_buffer2 lines.

This issue is mostly for tracking purpose. I will work on a solution and propose a PR when ready.

**Comment by gmaurel** [comment]
uncrustify doesn't support multiple declarations.
It is **evertime** better to spend some more lines for declarations.
Let us never begin with support multiple declarations.

**Comment by micheleCTDE** [comment]
Hi Guy,
I agree on the fact that is better to split declarations on multiple lines, but in case a huge code base has multiple declarations on a line, wouldn't it be nicer to consider the first assignment for alignment with other lines? The example above is minimal, but the definition block could actually several lines longer.
I am not talking about aligning multiple assignments on multiple rows, just the most left side one.
That is I am talking about:
```
int aaaa = 1, bbbb = 2, cccc = 3;
int a       = 1, b = 2, c = 3;
```
Not 
```
int aaaa = 1, bbbb = 2, cccc = 3;
int a    = 1, b    = 2, c    = 3;
```
What do you think?

**Comment by guy-maurel** [comment]
I had the experience of very surprising error with multiple declaration.
Would it be wise to propose a new option to first split such a declaration?

**Comment by micheleCTDE** [comment]
> I had the experience of very surprising error with multiple declaration. 

Interesting, what kind of issue did you run into just for my info. You can drop me an email if you prefer.

>Would it be wise to propose a new option to first split such a declaration?

That's a good idea. Perhaps we can do two things:
1) add option to enable/disable alignment on first assignment (this is quick to do). Default will be false, so no chances to current behavior.
2) add option to split multiple definitions into single definitions over multiple lines (this will probably take some extra work but I am willing to look into it). Default will also be false.

Does it sound good?

**Comment by micheleCTDE** [comment]
> I had the experience of very surprising error with multiple declaration.

Perhaps the same as described [here](https://github.com/uncrustify/uncrustify/pull/3425#issuecomment-994274469)?

**Comment by guy-maurel** [comment]
See another case #2841, #3144
