### ISSUE TITLE
Error with #ifdef macro

### ISSUE THREAD

**Issue by geork46** [uncrustify/uncrustify#3441]
Using uncrustify version: Uncrustify-0.66.1_f

Steps:
1. Generating cfg:
`uncrustify -c uncr.cfg main.cpp`

2. Launch uncrustify with main.cpp

main.cpp
```
int main()
{
               bool run_test = true;
 
               do
               {
#ifndef NO_EXCEPTIONS
                    try
                    {
#endif // NO_EXCEPTIONS
 
                    //do something
 
#ifndef NO_EXCEPTIONS
               }
               catch( ... )
               {
                    //do something
               }
#endif // NO_EXCEPTIONS
               } while( run_test );

}
```
launch:
`uncrustify -p debug.txt -c uncr.cfg main.cpp `

#### Current behavior
Error:
```
Output suffix: .uncrustify
Parsing: main.cpp as language CPP
check_complex_statements(838): main.cpp, orig_line is 16, Error: Expected 'while', got 'catch'
```
There is no debug-file. 

main.cpp.uncrustify
```
int main()
{
	bool run_test = true;

	do
	{
#ifndef NO_EXCEPTIONS
		try
		{
#endif // NO_EXCEPTIONS

		//do something

#ifndef NO_EXCEPTIONS
	}
	catch( ... )
	{
		//do something
	}
#endif // NO_EXCEPTIONS
	} while( run_test );

}
```

#### Expected result:
no errors. 
main.cpp.uncrustify
```
int main()
{
	bool run_test = true;

	do
	{
#ifndef NO_EXCEPTIONS
		try
		{
#endif // NO_EXCEPTIONS

		        //do something

#ifndef NO_EXCEPTIONS
	        }
	        catch( ... )
	        {
		        //do something
	        }
#endif // NO_EXCEPTIONS
	} while( run_test );

}
```

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by gmaurel** [comment]
Remember, uncrustify is not a compiler.
Simplify the macro.
