### ISSUE TITLE
Feature request: have default config file comment out configuration lines with default value

### ISSUE THREAD

**Issue by dtgriscom** [uncrustify/uncrustify#3443]
It's difficult to comprehend all 741 options for Uncrustify, especially as some disable or modify others. This makes it hard to start from scratch when setting up a configuration file.

Suggestion: as is done in some other Linux tools, have the default configuration file (generated by `--update-config` or `--update-config-with-doc`) comment out the configuration lines that are at their default values. Then, when you want to tweak a value, you uncomment it and set its value, and it's then clear just which lines have been modified.

The big problem with this suggestion would be using these options to clean up an existing configuration file; how do you reliably detect and handle currently commented out default options? If that isn't possible, then this feature becomes far less useful.

**Comment by micheleCTDE** [comment]
Hi Daniel,
the default file shows all the options with their default values and an explanation of what they do.
I don't see how commenting out all options would make the config clearer. And if you want all options commented out, it take just a few simple key strokes in vim to comment out the whole file, or a few more to comment out all non-commented lines.
uncrustify has a ton of options and I agree it takes time to go through them, test them and understand what they do. But that's why uncrustify is so configurable. And as with most tools, more powers requires more effort to set them up.

**Comment by dtgriscom** [comment]
Thanks for the response. My final goal was not to change what's written into a clean default options file; as-is, it is indeed clear on its own. My goal was to have it be clearer what values have been changed from the default values once a user has started tweaking the values.

It's great that uncrustify is so flexible, but that makes it a big lift for a newbie (e.g. me) to get started. You want it to be easy for people to do simple customizations, ignoring the more arcane settings unless/until they're needed. This would be a lot easier if:

1. The default configuration executed a fairly clear and simple set of formatting tasks so that we know where we're starting. The current defaults seem to fill that need, although it would be great if there were a description of what the defaults did.
2. As a user tweaks their settings, something makes it clear what's been changed and what hasn't, so that they can ignore the vast majority of settings that a) haven't been changed from the defaults, and b) don't match whatever regex they're using to find settings. This is currently **not** true: once you've change a few settings, it's easy to get completely lost.

In addition, a good way to get a useful set of uncrustify settings is to start with a configuration file that's close and then tweak it. But, if you don't know what's changed, you won't know what the configuration file actually does unless you read and understand all 741 settings. The `--update-config-with-doc` option is great, but it still doesn't help you out by showing which values aren't set to the defaults.

Changing the clean default file to have the defaults commented out, and then users un-comment and change them, seemed like a traditional Linux way to do this. But, as I noted, it would likely make it difficult for uncrustify to implement the "clean up and add documentation" process, which is a big downside. 

What if uncrustify added "# modified" to the end of a non-default setting's assignment? Then, you could take an unfamiliar configuration file, run `--update-config-with-doc`, and then see exactly what's changed/different.

Thanks for listening...

**Comment by micheleCTDE** [comment]
Hi Daniel,
I am also just a user and I also had to go thorugh the learning curve. I agree it is not easy, or at least it take some time for sure. The default config is mostly neutral, most options are set to "ignore", although a totally neutral config is not possible at the moment.  As a user, I find it it would be very annoying having to uncomment an option each time you want to change it, it is easier to simply cahnge it.
Having said that, perhaps this workflow would work for you:
1. start with an empty config file
2. looking at default.cfg, you can add one (or more) options to your config file and see how it behaves. This way your config file will only contain the options you changed.
3. iterate step 2 over and over till you get the config you like.
I suggest you setup a backup-update-compare cycle to ease your testing. This is what I also did and it helped a lot to see what individual option did. Keep in mind some options affects others, so trail and error is expected.

**Comment by gmaurel** [comment]
#3450 introduce an HOW TO

**Comment by dtgriscom** [comment]
Here's where I think the current model fails. Most newbies want to just pick a standard configuration from a list of standard styles (K&R, 1TBS, Kernel, GNU, etc). Even with the vagueness of these styles, you could easily create a list of configuration files that would match someone's idea of how these styles are defined. That, plus a clear definition of how the default configuration works, would make it really easy to get started. (You don't have these yet; I'll suggest that they would be a big leap forward in usability.)

But then, users will want to look at these canned configuration files to find out how a certain feature was done, relative to the default configuration. Or, someone would see a co-worker's config and want a specific aspect of their results. Or, someone would want to merge two configuration files to get the best of both.

How would a newbie do this? By scanning through all 700+ configuration values, wondering which one was changed? That is a steep learning curve; why require this of every new user of uncrustify?

If, instead, you had the non-default values clearly marked (choose your method), then they'd only have to look through perhaps ten or twenty settings. Much, much easier and clearer.

And, that's as clearly as I can explain it. If it still doesn't make sense to you, then such is life, and thanks for the great tool.
