### ISSUE TITLE
Doc request: have description of how default config will reformat code

### ISSUE THREAD

**Issue by dtgriscom** [uncrustify/uncrustify#3444]
It's difficult for a newbie to configure uncrustify due to the plethora of options. Using the default configuration options is a good starting point, but it would be better if there were a prose description of exactly what those defaults do. This may be best done in two parts:

1. Documenting exactly what the defaults values do
2. Changing some of the more obscure default values, if the result is a simpler starting point description.

**Comment by gmaurel** [comment]
#3450 introduce an HOW TO
