### ISSUE TITLE
Undesired alignment of split boolean condition

### ISSUE THREAD

**Issue by fleutot** [uncrustify/uncrustify#3482]
Uncrustify 0.72, this:
```
if ((asdf
        && qwer)
    || zxcv
) {
}
```
becomes this:
```
if ((asdf
     && qwer)
    || zxcv
) {
}
```
After the first new line, uncrustify aligns with the left side of `&&`, although all my `align_*` parameters are false:

```
indent_align_string=false
indent_align_assign=false
align_keep_tabs=false
align_with_tabs=false
align_on_tabstop=false
align_number_right=false
align_func_params=false
align_same_func_call_params=false
align_var_def_colon=false
align_var_def_attribute=false
align_var_def_inline=false
align_right_cmt_mix=false
align_on_operator=false
align_mix_var_proto=false
align_single_line_func=false
align_single_line_brace=false
align_nl_cont=false
align_left_shift=false
align_oc_decl_colon=false
```
Which parameter controls this, if not an `align_*`? I want an indent here.

I tested:
- `indent_paren_nl=true` (no difference),
- `indent_bool_paren=true` (resulted in an additional shift to the _left_),
- `indent_paren_close` affects this, if I set it to an undefined value (3, 10, whatever), then it leaves the original untouched.

It looks like there is a side-effect from `indent_paren_close`, even if I move the closing paren of the offending line to the next line:
```
    if ((asdf
         && qwer
        )
        || zxcv
    ) {
    }
```

Any solution?

```
$ uncrustify -v
Uncrustify_d-0.72.0
```

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
`... uncrustify aligns with the left side of &&, ...`
Not exactly.
I will say uncrustify aligns with the opening parenthesis.

**Comment by alexhenrie** [comment]
Would `indent_bool_paren=-1` and `indent_paren_close=-1` work for you? (You'll need to clone the latest bleeding-edge version of Uncrustify from Git and compile it from source.)

**Comment by fleutot** [comment]
@alexhenrie It would possibly work for me personally, but I would need to get the rest of the team on that. I don't think I can do that :)

**Comment by guy-maurel** [comment]
I get something different:
```.cpp
if ((asdf
     && qwer)
    || zxcv
    ) {
}
```
Let us try to synchronize:
Please use the current git source, use the command
`uncrustify ... -p p.txt`
and give a link to the **p.txt** file
I would like to get exactly the output you wish to get.
Thanks

**Comment by guy-maurel** [comment]
you have 2 problems.
Please, create a new issue for the second one, function_call...
It would be better for us to solve.

**Comment by fleutot** [comment]
Sorry, my comment about the function is not a problem in itself, it was just to say that I probably don't want to change the flags as suggested by alexhenrie.

**Comment by fleutot** [comment]
The example source (github made me add the .txt extension):
[bool_align.c.txt](https://github.com/uncrustify/uncrustify/files/8160818/bool_align.c.txt)

The debug file:
[p.txt](https://github.com/uncrustify/uncrustify/files/8160819/p.txt)

Running uncrustify's current master, `8edf48ad767bf4c9dba09dca79c0f8333d92146f`.

**Comment by fleutot** [comment]
The example source file (github made me add the txt extension):
[bool_align.c.txt](https://github.com/uncrustify/uncrustify/files/8160835/bool_align.c.txt)

The debug file:
[p.txt](https://github.com/uncrustify/uncrustify/files/8160837/p.txt)

Uncrustify_d-0.74.0-225-8edf48ad (current master)

**Comment by guy-maurel** [comment]
what do you expect to get?

**Comment by gmaurel** [comment]
The new created (25 02 2022) option _indent_ignore_first_continue_
gives you want you expected to get.
Please try and report

**Comment by fleutot** [comment]
Tried, report as working, thanks!

But I still don't understand what this does, if not that:

```
// How to indent a Boolean operator when inside parentheses.
//  0: Indent by one level (default)
//  1: Align under the open parenthesis
// -1: Preserve original indentation
extern BoundedOption<signed, -1, 1>
indent_bool_paren;
```
