### ISSUE TITLE
Ending parameter modifier causes incorrect formatting.

### ISSUE THREAD

**Issue by JingJiangAtIntel** [uncrustify/uncrustify#3487]
I used the latest 73.0.3 release and found a problem:

EDK2 coding standard - 5.7.1.10

The opening brace of the function body is alone on the next line.
Both the opening and closing brace of the function body must be aligned in the left most column. All other lines of the function body are indented in multiples of two spaces.
/** Brief and Detailed Descriptions.

  @param[in]      Arg1  Description of Arg1.
  @param[in]      Arg2  Description of Arg2, which is optional.
  @param[out]     Arg3  Description of Arg3.
  @param[in,out]  Arg4  Description of Arg4.

  @retval  EFI_SUCCESS   Description of what EFI_SUCCESS means.
  @retval  !EFI_SUCCESS  Failure.

--*/
EFI_STATUS
EFIAPI
FooName (
  IN UINTN           Arg1,
  IN UINTN           Arg2, OPTIONAL
  OUT UINTN       *Arg3,
  IN OUT UINTN  *Arg4
  );
{
  UINTN Local;
  ...
}
=============================================================
The OPTIONAL causes a problem - I got something like below:
 IP_CSI_STATUS
MessageQueueCreate (
  IN OUT MESSAGE_QUEUE_CONTEXT *MessageQueueContext,
  IN     MESSAGE_CHANNEL_CONTEXT MessageChannelContext,
  IN     IP_WR_MEM_CNTXT IpWrapperMemoryContext,
  IN     IP_WR_TIME_CNTXT IpWrapperTimeContext,
  IN     IP_WR_PRINT_CNTXT IpWrapperPrintContext,
  IN     MESSAGE_QUEUE_INFO_IDENTIFIER *Identifier,
  IN     UINT32 NumberOfResources,
  IN     MESSAGE_QUEUE_INFO_RESOURCE *Resources, OPTIONAL
  IN     UINT8                         MaximumNonBlocking,
  IN     UINT8                         MaximumIpSpecificHandlers,
  IN     UINT32                        MaximumRetry,
  IN     UINT32                        DelayMicroseconds,
  IN     BOOLEAN                       EnableStatistics,
  IN     UINT32                        SourceLevelDebugPacketSize
  );

If I remove the "OPTIONAL" modifier, the problem will be resolved.  If this line is the last line in the list, it is also fine.

**Comment by guy-maurel** [comment]
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!
I get:
```.cpp
/** Brief and Detailed Descriptions.

   @param[in] Arg1 Description of Arg1.
   @param[in] Arg2 Description of Arg2, which is optional.
   @param[out] Arg3 Description of Arg3.
   @param[in,out] Arg4 Description of Arg4.

   @RetVal EFI_SUCCESS Description of what EFI_SUCCESS means.
   @RetVal !EFI_SUCCESS Failure.
   --*/
EFI_STATUS
EFIAPI
FooName (
        IN UINTN Arg1,
        IN UINTN Arg2, OPTIONAL
        OUT UINTN *Arg3,
        IN OUT UINTN *Arg4
        );
{
        UINTN Local;
//...
}

//The OPTIONAL causes a problem - I got something like below:
IP_CSI_STATUS
MessageQueueCreate (
        IN OUT MESSAGE_QUEUE_CONTEXT *MessageQueueContext,
        IN MESSAGE_CHANNEL_CONTEXT MessageChannelContext,
        IN IP_WR_MEM_CNTXT IpWrapperMemoryContext,
        IN IP_WR_TIME_CNTXT IpWrapperTimeContext,
        IN IP_WR_PRINT_CNTXT IpWrapperPrintContext,
        IN MESSAGE_QUEUE_INFO_IDENTIFIER *Identifier,
        IN UINT32 NumberOfResources,
        IN MESSAGE_QUEUE_INFO_RESOURCE *Resources, OPTIONAL
        IN UINT8 MaximumNonBlocking,
        IN UINT8 MaximumIpSpecificHandlers,
        IN UINT32 MaximumRetry,
        IN UINT32 DelayMicroseconds,
        IN BOOLEAN EnableStatistics,
        IN UINT32 SourceLevelDebugPacketSize
        );


```

**Comment by JingJiangAtIntel** [comment]
I built the tool from the master branch, and I used edk2.cfg and got the error below. 
edk2.cfg:78: unknown option 'indent_func_call_edk2_style'
edk2.cfg:240: option 'indent_sing_line_comments' is deprecated; did you want to use 'indent_single_line_comments_before' instead?
edk2.cfg:269: unknown option 'align_edk2_style'

I ran the prebuild window version 0.74. I got a different format problem:

IP_CSI_STATUS
MessageQueueCreate (
        IN OUT MESSAGE_QUEUE_CONTEXT     *MessageQueueContext,
        IN MESSAGE_CHANNEL_CONTEXT         MessageChannelContext,
        IN IP_WR_MEM_CNTXT                           IpWrapperMemoryContext,
        IN IP_WR_TIME_CNTXT                           IpWrapperTimeContext,
        IN IP_WR_PRINT_CNTXT                         IpWrapperPrintContext,
        IN MESSAGE_QUEUE_INFO_IDENTIFIER *Identifier,
        IN UINT32                                               NumberOfResources,
        IN MESSAGE_QUEUE_INFO_RESOURCE *Resources, 
        OPTIONAL
        IN UINT8                                                 MaximumNonBlocking,
        IN UINT8                                                 MaximumIpSpecificHandlers,
        IN UINT32                                               MaximumRetry,
        IN UINT32                                               DelayMicroseconds,
        IN BOOLEAN                                          EnableStatistics,
        IN UINT32                                              SourceLevelDebugPacketSize
        );

**Comment by guy-maurel** [comment]
I don't know what edk2.cfg is.
Line 78: The same for indent_func_call_edk2_style
Line 240: You need to use the new option as written above.
Line  269: The same 
Please push a link to your configuration file.
As you can see in the comment before, I don't have such a problem.

**Comment by gmaurel** [comment]
please try:
`uncrustify ... -p p.txt`
und push the p.txt file

**Comment by JingJiangAtIntel** [comment]
The attached is the file and its debug output, so you can see what I got
[test.zip](https://github.com/uncrustify/uncrustify/files/8009643/test.zip)

**Comment by guy-maurel** [comment]
C++ knows about qualifier:
`https://en.cppreference.com/w/cpp/language/cv`
a qualifier is used before or after a type, not after the variable.

**Comment by JingJiangAtIntel** [comment]
The format is for EDK2 coding specs:
https://edk2-docs.gitbook.io/edk-ii-c-coding-standards-specification/5_source_files/57_c_programming

**Comment by gmaurel** [comment]
You use the option _nl_func_decl_args = force_
Your OPTIONAL is a qualifier for the next parameter

**Comment by JingJiangAtIntel** [comment]
The issue was fixed by removing the comma between variable and the "OPTIONAL" modifier, The comma is after the "OPTIONAL".
