### ISSUE TITLE
sp_deref is not respected in inlined member functions

### ISSUE THREAD

**Issue by markus456** [uncrustify/uncrustify#3509]
With `sp_deref=remove`, the behavior changes if the code is defined as an inlined member function. This doesn't seem like it worked in any version I've used.

Source code:
```c++
struct Test
{
    void fn(int* i)
    {
        *i = 1;
    }
};


void fn(int* i)
{
    *i = 1;
}
```

Generated result:
```c++
struct Test
{
    void fn(int* i)
    {
        * i = 1;
    }
};


void fn(int* i)
{
    *i = 1;
}
```

Expected result: same as input file, no changes.

Debug output: [debug.txt](https://github.com/uncrustify/uncrustify/files/8013472/debug.txt)

Version: `Uncrustify-0.74.0` (commit 62048b01507304653ea98a74b31e0edbadaf7496)

**Comment by guy-maurel** [comment]
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by markus456** [comment]
Yep, it seems to be fixed.
