### ISSUE TITLE
the type of options has changed --> Regression

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#3511]
with 8b9a7611f276776689f0643d2bc1142d92eece1c the type of _indent_comma_paren_ has changed from **Option<bool>** to **BoundedOption<signed, -1...**
This produce a regression with old configuration file using the value **true**
@alexhenrie : could you have a look on it.

**Comment by alexhenrie** [comment]
What do you think the right solution is?

**Comment by gmaurel** [comment]
Goal is to don't have any regression

**Comment by alexhenrie** [comment]
Yes, but how do we do that? For example, do you want more warnings in [process_option_line_compat_0_73](https://github.com/uncrustify/uncrustify/blob/719cf9d153a9ec14be8d5f01536121ced71d8bc9/src/option.cpp#L345)? Do you want to revert commit 026162b8da51660126863b42d00245e21a47d7c0?

**Comment by alexhenrie** [comment]
Or are you saying that when an integer parameter is set to `true` or `false`, it should automatically become `1` or `0`?

**Comment by guy-maurel** [comment]
What about:
```
enum class abc_xyz : int
{
     false_abc = 0,
     true_abc = 1,
     ignore_abc = 2
}
```
The line indent.cpp:3960:
`            if (options::indent_shift() == -1)`

is not really fine!
I prefer:
`            if (options::indent_shift() == ignore_abc)`

**Comment by gmaurel** [comment]
Have a look to https://ci.appveyor.com/project/gmaurel/uncrustify/builds/42530858/job/xe0qopqx0qwh7f6f
