### ISSUE TITLE
Uncrustify apparently confused by 'const' qualifier in operator definition

### ISSUE THREAD

**Issue by RobertoBagnara** [uncrustify/uncrustify#3513]
<pre>
$ uncrustify -v
Uncrustify_d-811d13a4
</pre>

<pre>
$ cat p.cc
struct S {
  int get() const {
    return 5;
  }
  operator bool() {
    return true;
  }
  operator int() const {
    return get();
  }
};
</pre>

<pre>
$ uncrustify -c p.cfg p.cc
Output suffix: .uncrustify
Parsing: p.cc as language CPP
</pre>

The obtained result is:

<pre>
struct S
{
	int get() const
	{
		return 5;
	}
	operator bool()
	{
		return true;
	}
	operator int() const {
		return get();
	}

};
</pre>

The expected result is (note the positioning of the opening brace in the last operator definition):

<pre>
struct S
{
	int get() const
	{
		return 5;
	}
	operator bool()
	{
		return true;
	}
	operator int() const
	{
		return get();
	}

};
</pre>

As you can see, the problem seems to be tied to the presence of the const qualifier, but I have found nothing in options.h that might have an effect on that.

[p.zip](https://github.com/uncrustify/uncrustify/files/8021799/p.zip)

**Comment by guy-maurel** [comment]
PR #3534 is a bugfix proposal.
Please test it and report.
