### ISSUE TITLE
nl_var_def_blk_end is ignored

### ISSUE THREAD

**Issue by RobertoBagnara** [uncrustify/uncrustify#3516]
<pre>
$ uncrustify -v
Uncrustify_d-4dbe0768
</pre>
<pre>
$ cat p.cfg
nl_var_def_blk_end  = 1
</pre>
<pre>
$ cat p.c
void g () {
  h();
  int x;
  return;
  {
    h();
    int x;
    return;
  }
}
</pre>
<pre>
$ uncrustify -c p.cfg p.c
Output suffix: .uncrustify
do_source_file(1505): Parsing: p.c as language C
</pre>
<pre>
$ cat p.c.uncrustify 
void g () {
	h();
	int x;
	return;
	{
		h();
		int x;
		return;
	}
}
</pre>

The two occurrences of ``int x;`` are variable definitions not at the top of a function body,
hence they should be followed by a blank line.

**Comment by guy-maurel** [comment]
PR #3535 is a bugfix proposal.
Please test it and report.

**Comment by RobertoBagnara** [comment]
It works, thanks!
