### ISSUE TITLE
uncrustify --no-backup changing symbolic links to plain text files

### ISSUE THREAD

**Issue by jreybert** [uncrustify/uncrustify#353]
In a project tree, some source files are symbolic links to other source files. When uncrustifying such project tree witht he option --no-backup, symbolic files become plain text files.

How to reproduce:

```
$ uncrustify --version
uncrustify 0.60
```

config created with this command

```
$ touch config; uncrustify --update-config-with-doc -c config -o config
```

project tree before uncrustify

```
$ tree
.
├── a
│   └── test.h -> ../b/test.h
├── b
│   └── test.h
├── config
└── test.c
$ file a/test.h 
a/test.h: symbolic link to `../b/test.h'
```

uncrustify command:

```
$ uncrustify --no-backup -c config $(find . -name *.c -or -name *.h)
Parsing: ./a/test.h as language CPP
Parsing: ./test.c as language C
Parsing: ./b/test.h as language CPP

```

project tree after uncrustify

```
$ tree
.
├── a
│   └── test.h
├── b
│   └── test.h
├── config
└── test.c
$ file a/test.h 
a/test.h: ASCII text
```

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!

**Comment by jreybert** [comment]
I tested this test case, it works like a charm! Thanks.
