### ISSUE TITLE
Please add options for support c++11 rvalue references

### ISSUE THREAD

**Issue by telychko** [uncrustify/uncrustify#354]

**Comment by gmaurel** [comment]
Can you give more details about what you are looking for?

**Comment by mihaipopescu** [comment]
@telychko if you have any issue in formatting please report them as your request is too general.

I suspect that maybe in some instances the rvalue references could be tokenized as `CT_ARITH` but we need concrete examples.

**Comment by gmaurel** [comment]
no more message
