### ISSUE TITLE
Function header in macro parameter adds spaces to pointer arguments

### ISSUE THREAD

**Issue by fleutot** [uncrustify/uncrustify#3544]
Uncrustify_d-0.74.0

I just upgraded from 0.72.

I am using Contiki OS, which uses pre-processor macros to mangle function names (and more magic) to turn them into processes and threads.

The definition of a thread looks like this:

    PT_THREAD(my_thread_function_name(
        struct pt *pt, 
        process_event_t ev, 
        my_data_type_t *data))
    {
        // the implementation...
    }

Up until 0.74, uncrustify let this format be. Now, there is an added space before `data`. 

```
 static PT_THREAD(my_thread_function_name(
     struct pt *pt,
     process_event_t ev,
-    my_data_type_t *ctx))
+    my_data_type_t * ctx))
```

If I add `struct` before the offending row, no space is added:

```
 static PT_THREAD(my_thread_function_name(
     struct pt *pt,
     process_event_t ev,
-    my_data_type_t *ctx))
+    struct my_data_type_t *ctx))
```

It's probably the macro that disturbs uncrustify. I'm not sure what has changed between 0.72 and 0.74, that broke this.

Do you know any option or work-around to prevent from adding this space?

**Comment by fleutot** [comment]
From the output file, it seems that the `*` character in the pointer argument is treated as arithmetics?

**Comment by fleutot** [comment]
I bisected this, and reaches this first bad commit:

```
c1fd2029c655bac1a0a254547f623c2c3d2bc256 is the first bad commit
commit c1fd2029c655bac1a0a254547f623c2c3d2bc256
Author: Joshua Parker <redracer2000@gmail.com>
Date:   Thu Nov 12 11:29:41 2020 -0600

    Improve classification of class/enum/struct/union
```

**Comment by guy-maurel** [comment]
No. The problem is older.
uncrustify at line 5, doesn't know anything about t
Remember, uncrustify is not a compiler.

**Comment by fleutot** [comment]
Commit c1fd2029c655 adds a space after `*` in @bofh69's example.
This commits parent does not add a space.

There is a difference in behavior between c1fd2029c655 and its parent.

**Comment by guy-maurel** [comment]
you need to help uncrustify, use the option:
  _set TYPE t_
to get
```.c
#define x(f) void f

typedef int t;

x(func(t *a))
{
    (void) a;
}
```
and the p-file shows:
```.txt
#   5>               TYPE|               NONE|     PARENT_NOT_SET[  8/  8/  9/  0][0/2/0][        8 0010][0-0]        t
#   5>           PTR_TYPE|               NONE|     PARENT_NOT_SET[ 10/ 10/ 11/  1][0/2/0][   2 0000 0010][0-0]          *
#   5>               WORD|               NONE|     PARENT_NOT_SET[ 11/ 11/ 12/  0][0/2/0][            10][0-0]           a
```

**Comment by fleutot** [comment]
Good to know. Would it be viable for the future, to make uncrustify understand this by parsing the typedefs? I suppose it could be a whole can of worms.

**Comment by fleutot** [comment]
@guy-maurel This works. I think the usual types in stdint.h should not need to be added manually. Right now I have this at the end of my config file:

```

set TYPE uint8_t
set TYPE uint16_t
set TYPE uint32_t
set TYPE uint64_t
set TYPE int8_t
set TYPE int16_t
set TYPE int32_t
set TYPE int64_t
```
