### ISSUE TITLE
Incorrect spacing added after address-of operator in macro when macro has an argument.

### ISSUE THREAD

**Issue by NickolasLapp** [uncrustify/uncrustify#3559]
[debug.txt](https://github.com/uncrustify/uncrustify/files/8164688/debug.txt)
test.c:
```
#define my_thing \
  &object1, &object2

#define my_thing(stuff) \
  &object1, &object2
```

Expect no change, but get:
```
#define my_thing \
  &object1, &object2

#define my_thing(stuff) \
  & object1, &object2
``` 
(Notice the extra space after the ampersand)

```
➜  Downloads uncrustify -v
Uncrustify-0.73.0_f
```

**Comment by NickolasLapp** [comment]
Looking at the debug output, it seems like the `&` in the second version gets incorrectly detected as `ARITH` instead of `ADDR`:

**Comment by guy-maurel** [comment]
PR #3655 is a bugfix proposal.
Please test it and report.
