### ISSUE TITLE
Option to modify infinite loop syntax

### ISSUE THREAD

**Issue by alexhenrie** [uncrustify/uncrustify#3591]
I don't know if it's possible in Uncrustify's current architecture, but it would be nice to have an option to enforce a consistent syntax for infinite loops in C and C++. Something like:

* `mod_infinite_loop=0`: Leave syntax alone
* `mod_infinite_loop=1`: Replace `while (1)` and `while (true)` with `for (;;)`
* `mod_infinite_loop=2`: Replace `for (;;)` and `while (1)` with `while (true)`
* `mod_infinite_loop=3`: Replace `for (;;)` and `while (true)` with `while (1)`

Ideally, these options would also convert infinite `do...while` loops into plain `for` or `while` loops.

**Comment by micheleCTDE** [comment]
Good idea Alex.
Re conversion of do...while loops, that could be more tricky because sometimes conditions could be very complex. But surely doable as well.
I suggest to start from for/while loops first. Maybe split the options into "mod_infinite_for_loop" and "mod_infinite_while_loop"
