### ISSUE TITLE
Ability to provide additional qualifier identifiers

### ISSUE THREAD

**Issue by zachriggle** [uncrustify/uncrustify#36]
Is there any way to get an output where alignments can work like so with `IN` and `OUT` keywords (`#define`'d to whitespace).  They have no meaning in source, they are just for API documentation.'

I've tried defining `"IN OUT"`, `"IN____"` and `"___OUT"` as identifiers, but this doesn't have the desired effect. (replace '_' with a space).

```` c
	/**
	 * Blah Documentation Blah
	 */
	int
	SomeFunction (
		IN OUT int  *blah,
		IN     int   blah2,
		   OUT void *blah3
	)
```

**Comment by gmaurel** [comment]
There is no way today for what you wanted to have, sorry.
