### ISSUE TITLE
Objective-c new line after curly brace

### ISSUE THREAD

**Issue by fabiojgrocha** [uncrustify/uncrustify#360]
Hi,

While configuring my uncrustify for Xcode, I've added configs to have new lines before curly braces as follows:

```
nl_after_brace_open = true
nl_after_brace_open_cmt = true
nl_after_brace_close = true
```

Initial code:

```obj-c
    if (YES) {
        return NO;
    } else {
        return YES;
    }
```

Expected:
```obj-c
    if (YES) {

        return NO;
    } else {

        return YES;
    }
```

It wont work, the code remains exactly the same. I've tried running uncrustify directly on the console (terminal) with the same output.

Thanks!

**Comment by gmaurel** [comment]
If the token before "return" is not a { such as:

    if (YES) {
        a = 1;
        return NO;
    } else {
        b = 2;
        return YES;
    }

you get it with the option:

nl_before_return=true
