### ISSUE TITLE
Asterisk identified as PTR_TYPE instead of ARITH since commit c1fd2029

### ISSUE THREAD

**Issue by rkta** [uncrustify/uncrustify#3601]
Asterisk identified as PTR_TYPE instead of ARITH since commit c1fd2029

```
% cat ex.c
struct cage cages[MAX_CAGES * sizeof(struct cage)];
```

```
% cat ex.cfg
sp_after_ptr_star = remove
```

Generated results:
```
% build/uncrustify --version
Uncrustify_d-0.72.0-20-c1fd2029
% build/uncrustify -c ex.cfg -f ex.c -p debug.txt
Parsing: ex.c as language C
struct cage cages[MAX_CAGES *sizeof(struct cage)];
```

Expected results:
```
% build/uncrustify --version
Uncrustify_d-0.72.0-19-f19cca5c
% build/uncrustify -c ex.cfg -f ex.c -p working.debug.txt
Parsing: ex.c as language C
struct cage cages[MAX_CAGES * sizeof(struct cage)];
```

Debug log files:
[debug.txt](https://github.com/uncrustify/uncrustify/files/8402565/debug.txt)
[working.debug.txt](https://github.com/uncrustify/uncrustify/files/8402566/working.debug.txt)

**Comment by parkerjs** [comment]
The following git diff patch should fix the issue:

[patch.txt](https://github.com/uncrustify/uncrustify/files/8406517/patch.txt)

**Comment by parkerjs** [comment]
May need to potentially test for nullptr on two of the calls I made in that patch:

`next->IsSquareBracket()`

and

`prev->GetNextNcNnl(E_Scope::PREPROC)`

For ill-formed source code, 'next' or 'prev' could possibly be null.

**Comment by rkta** [comment]
On Sun, Apr 03, 2022 at 08:41:25PM -0700, Josh Parker wrote:
> The following git diff patch should fix the issue:
> 
> [patch.txt](https://github.com/uncrustify/uncrustify/files/8406517/patch.txt)

Yes, I can confirm that this fixes the issue. Thanks.

**Comment by guy-maurel** [comment]
PR #3602 is a bugfix proposal.
Please test it and report.

**Comment by guy-maurel** [comment]
Danke fuer die Meldung @rkta
