### ISSUE TITLE
long method and variable declarations not correctly indented 

### ISSUE THREAD

**Issue by kaiser101** [uncrustify/uncrustify#361]
Ported an issue here from sourceforge page, seems github is now the official issue reporting mechanism.

http://sourceforge.net/p/uncrustify/bugs/555/

Long method and variable declarations though are still not being indented correctly. They work normally, but in case of templatized parameters they break.

Would appreciate it if someone can check it out.

**Comment by gmaurel** [comment]
Hello again.
Could you push a new version of your indent.cpp or a diff again the aktual git version?

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
