### ISSUE TITLE
Indentation wrong when using throw

### ISSUE THREAD

**Issue by dirk-thomas** [uncrustify/uncrustify#362]
I created a minimal example which shows the problem (https://github.com/dirk-thomas/uncrustify_issues/blob/master/throw_indentation/main.cpp):

    func(
      "Long error message to make this line be wrapped in the first place");
    throw std::runtime_error(
      "Long error message to make this line be wrapped in the first place");

With two space indentation (https://github.com/ament/ament_lint/blob/781066367a1935a7e5e93b47e73258716aac8faf/ament_uncrustify/ament_code_style.cfg) both lines should be "correct". While uncrustify does not change the indentation of the message for `func` it does increase the indentation for the `throw`. Since the new indentation is exactly 8 characters that looks like a hard-coded value.

The reformatted file with uncrustify 0.61 as well as current master (while it should stay the same):

    func(
      "Long error message to make this line be wrapped in the first place");
    throw std::runtime_error(
            "Long error message to make this line be wrapped in the first place");

**Comment by dirk-thomas** [comment]
@gmaurel Maybe you can consider to look into this issue?

**Comment by gmaurel** [comment]
This is correct.
The option "indent_column" controls the indentation of the next line of the function call.
In your example: 2 spaces after the beginning of the function name.
For the first line after "func": column 3,
for the second line after "std::runtime_error": column 9.

**Comment by dirk-thomas** [comment]
This does not look "correct" to me. The indentation of a block is commonly not depending on the function or keyword. For a setting of 2 spaces the indentation of a nested block is always two spaces more than the parent level, e.g.:

```
if (...) {
  do_something
```

```
while (...) {
  do_something
```

```
function_call(
  args
```

```
{
  {
    {
      some_nested_scope
    }
  }
}
```

Why should it be different in the case of calling `throw`? I would expect it to look the same:

```
throw whatever(
  args
```

For `return` this is not different too:

```
return SomeClass(
  arg
```

If you still don't think this is desired by default would you consider to add an option to achieve this formatting?

Can you please point me to the line which performs this - then I can just modify it in our fork until an option becomes available?
