### ISSUE TITLE
default config file with option error

### ISSUE THREAD

**Issue by cstyhj** [uncrustify/uncrustify#3623]
current version: Uncrustify-0.74.0
source commit: e8564e37a28150eafabd6a74d03c13cb4efb2417

Option<NUM>: at e:\work\coding\beethoven\tools\ttt.cfg:1182: Expected number , for 'indent_shift'; got 'false'
Option<NUM>: at e:\work\coding\beethoven\tools\ttt.cfg:1356: Expected number , for 'indent_comma_brace'; got 'false'
Option<NUM>: at e:\work\coding\beethoven\tools\ttt.cfg:1360: Expected number , for 'indent_comma_paren'; got 'false'
Option<NUM>: at e:\work\coding\beethoven\tools\ttt.cfg:1364: Expected number , for 'indent_bool_paren'; got 'false'
Option<UNUM>: at e:\work\coding\beethoven\tools\ttt.cfg:2988: Expected unsigned number , for 'mod_full_brace_if_chain'; got 'false'
Option<NUM>: at e:\work\coding\beethoven\tools\ttt.cfg:3217: Expected number , for 'pp_indent_brace'; got 'true'

**Comment by micheleCTDE** [comment]
Some options have change from boolean to number. You need to update your config accordingly.
Default config file is already up to date.

This issue should be consider invalid. Please confirm everything is fine after you update your ttt.cfg file and then this can be closed.

**Comment by cstyhj** [comment]
the ttt.cfg file，i copy from "default config file", found in htdocs/index.html
![图片](https://user-images.githubusercontent.com/16204670/163916940-d30ee63e-ef6d-4476-b399-c431dfccf03a.png)

so, should doc be updated? my issue is about doc

**Comment by micheleCTDE** [comment]
You may have an old copy perhaps?
Here is for example the option "indent_shift", you can see a number is expected.

![default](https://user-images.githubusercontent.com/76247647/163992759-a4e9e45a-6052-4315-bee5-e8d72d0e44dd.png)

**Comment by cstyhj** [comment]
thanks, problem solved after pull newest status.

**Comment by micheleCTDE** [comment]
Ok, I will close the issue then.
