### ISSUE TITLE
Adding unwanted parenthesis around parts of the condition

### ISSUE THREAD

**Issue by dirk-thomas** [uncrustify/uncrustify#363]
I created a minimal example which shows the problem (https://github.com/dirk-thomas/uncrustify_issues/blob/master/parenthesis_around_conditions/main.cpp):

    if ("foo" == "bar" && 23 != 42 && true != false) {
      // something
    }

Even with `mod_full_paren_if_bool` set to `false` (https://github.com/ament/ament_lint/blob/41d5b12c98ef1f59721b1b60a955145ceb314d07/ament_uncrustify/ament_code_style.cfg) every boolean part of the condition is wrapped in parenthesis.

The reformatted file with uncrustify 0.61 as well as current master (while it should stay the same):

    if (("foo" == "bar") && (23 != 42) && (true != false)) {
      // something
    }

**Comment by gmaurel** [comment]
works for me with actual git version.
