### ISSUE TITLE
C++/other langs: wrong spacing with nl_brace_else = remove

### ISSUE THREAD

**Issue by dbartolini** [uncrustify/uncrustify#3634]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

With ``Uncrustify_d-0.74.0-338-50025791`` the spacing between ``else if`` and ``{`` is wrong.

Command ([debug.txt](https://pastebin.com/GPiHat6B)):
```
./build/uncrustify -p debug.txt -c elseif.cfg -f elseif.cpp
```

Input:
```
if (false)
{
}
else if (false)
{
}
```

Output:
```
if (false) {
} else if (false)   {
}
```

Expected output:
```
if (false) {
} else if (false) {
}
```

If you remove ``nl_brace_else = remove`` from config uncrustify produces expected output.
If you disable [this](https://github.com/uncrustify/uncrustify/blob/50025791cdcbd18fcc50404446cf7ac2b7f3f556/src/chunk.cpp#L556-L559) code block uncrustify produces expected output.

I didn't investigate further.

**Comment by guy-maurel** [comment]
you need to use the option
```.txt
# Add or remove space between ')' and '{' of control statements.
sp_sparen_brace                 = force
```

**Comment by dbartolini** [comment]
It does the trick. Thanks.
