### ISSUE TITLE
fail to create files when using absolute path and --prefix

### ISSUE THREAD

**Issue by dirk-thomas** [uncrustify/uncrustify#364]
When passing an absolute path to `--prefix` (e.g. `C:\\foo`) as well as an absolute path for the file to reformat (e.g. `C:\\bar\\file`) *uncrustify* tries to create the new "uncrustified" file at `C:\\fooC:\\bar\\file`) which does not work.

**Comment by gmaurel** [comment]
Do we have the problem yet?

**Comment by mihaipopescu** [comment]
@dirk-thomas how could Uncrustify extract a relative path from an absolute one ? relative to what?

**Comment by dirk-thomas** [comment]
I am not advocating that it is a "valid" use case. But if you pass two absolute paths on Linux something "reasonable" happens. But if you do it on Windows it breaks with a rather weird error message.

Imo it could either check if the second of the concatenated paths is absolute and only use that (that's what is happening on Linux afaik) or simply exit with a reasonable error message.

**Comment by mihaipopescu** [comment]
The file systems you're talking about are inherently different. What if next someone asks to have also support for URIs ?

What's the error message you get on Windows if you pass absolute path both to file and prefix ?

Probably Uncrustify should check if the new path is a valid path before trying to create the file but if the message is something like `Can't create file C:\\fooC:\\bar\\file` I think it's quite obvious what is wrong and why it's failing.

**Comment by dirk-thomas** [comment]
Currently the program blindly concats the two paths and then fails to access that path. A simple check for this case and either picking only the second path (instead if trying to concat, which is what happens on Linux) or print a message earlier would be nice imo.

If you think the current error message is good enough please feel free to close this ticket.

**Comment by gmaurel** [comment]
fine
