### ISSUE TITLE
Windows binary zip files on SourceForge incorrect

### ISSUE THREAD

**Issue by AlanGillespie** [uncrustify/uncrustify#3647]
The zip files on SourceForge for the binary distribution of 0.75 for Windows appear to contain the Linux executable, "uncrustify", instead of the Windows executable, "uncrustify.exe". This affects both the 64-bit and 32-bit builds.

**Comment by guy-maurel** [comment]
yes, I am looking ...

**Comment by micheleCTDE** [comment]
Should be ok now. Could you please check and let us know?

**Comment by AlanGillespie** [comment]
It's good now. Thanks a lot for your help :)
