### ISSUE TITLE
Wrong indentation

### ISSUE THREAD

**Issue by Massimo-B** [uncrustify/uncrustify#366]
This is a minimal example with a "broken" indentation.
This is uncrustify-0.60.

I'm going to provide my configuration, which was started from
`uncrustify --update-config-with-doc > ~/.uncrustify.cfg`

```cpp
$ uncrustify -q -l cpp -c ~/.uncrustify.cfg -f crusty-test.cpp 
void Response::write( QString const &_fileName ) {
QDomElement     root = m_responseDoc.createElement( "Message" );

root.appendChild( getNodeMessageBody() );
	QFile       outFile( _fileName );

	if( !outFile.open( QIODevice::WriteOnly | QIODevice::Text ) ) {
		return false;
	}
	QTextStream stream( &outFile );
	stream << m_responseDoc.toString();
	outFile.close();
}
```

**Comment by Massimo-B** [comment]
Trying to attach the config: "Unfortunately, we don't support that file type."

Should I paste it completely or can you already see some option causing the identation switch?

**Comment by Massimo-B** [comment]
Deleting the line `stream << m_responseDoc.toString();` makes uncrustify segfaulting with my configuration, which does not happen with `/usr/share/uncrustify/linux.cfg`.
So investigating my configuration would be important anyway.

**Comment by Massimo-B** [comment]
This is my config:
https://bitbucket.org/massimo/configs/raw/8699a5e5c0401148ad91e789326b432e3caed914/.uncrustify.cfg

**Comment by Massimo-B** [comment]
Same issues with uncrustify-0.61

**Comment by Massimo-B** [comment]
https://bitbucket.org/massimo/configs/src/14235d0d695a82cfa48db4e3bc980e9fbf46b3af/.uncrustify.cfg
Merged config to 0.61:
```bash
gvimdiff <(uncrustify --update-config-with-doc) ~/.uncrustify.cfg
```

**Comment by Massimo-B** [comment]
I tried toggling all variables and found the option for the broken indentation: indent_var_def_blk
Setting from 1 to 0 fixes the indentation.

I also investigated the segfault bug. As this is some different bug I open another ticket...

**Comment by gmaurel** [comment]
Works for me now.
