### ISSUE TITLE
sp_before_unnamed_byref failed in std::function

### ISSUE THREAD

**Issue by cstyhj** [uncrustify/uncrustify#3691]
current version: Uncrustify-0.75.1
source commit: e8564e37a28150eafabd6a74d03c13cb4efb2417

test options:
```
sp_type_func                = add       # 
sp_after_type               = add       #
sp_fparen_brace             = force

sp_before_byref             = add
sp_after_byref              = remove    # "int * a" vs "int *a"
sp_before_unnamed_byref     = remove    # "int&" vs "int &" (return type)
sp_before_byref_func        = remove
sp_after_byref_func         = add
sp_byref_paren              = add
```

test code:
```
void test(std::function<void(const int&)> func);
```

my test environment is win 10，and test command is:
{path}\uncrustify.exe -c {path}\test.cfg {path}\test.h

output code:
```
void test(std::function<void(const int &)> func);
}
```

my expectation is same as original code, 
no space between "const int" and "&"
thanks for any advice.

**Comment by guy-maurel** [comment]
PR #3693  is a bug fix proposal.
Please test it and report.

**Comment by micheleCTDE** [comment]
>  sp_before_byref             = add

You have specified this, so a space is added before the & sign.
You should also use 
```
sp_before_unnamed_byref = remove
```
this should remove the space before an unnamed & sign.

**Comment by micheleCTDE** [comment]
> > sp_before_byref             = add
> 
> You have specified this, so a space is added before the & sign. You should also use
> 
> ```
> sp_before_unnamed_byref = remove
> ```
> 
> this should remove the space before an unnamed & sign.

Correction, it seems that ```sp_before_byref = add``` takes precedence on ```sp_before_unnamed_byref = remove```, which IMO is wrong, given the description of the second option.

**Comment by guy-maurel** [comment]
replaced by PR#3885
