### ISSUE TITLE
Error code 70 crash when checking/formatting files

### ISSUE THREAD

**Issue by Purg** [uncrustify/uncrustify#3710]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

I recently updated to version 0.75.1 and now uncrustify will crash (error code 70) when checking/formatting some files that were previously not causing any issues. I tried generating a debug file but the crash happens before that gets handled, it seems.
* This crash seems to occur for tagged versions `uncrustify-0.75.0` (cfb9cdf7) and `uncrustify-0.75.1` (639856e6), as well as the `master` branch (846adb43).
* Version `uncrustify-0.74.0` (62048b01) does _**NOT**_ crash.

Below is a minimal example of the line that seems to be causing a crash and the minimal config.

C++ file:
```c++
void foo()
{
  PyErr_SetString( PyExc_KeyError, sstr.str().c_str() );
}                                                       
```

Config file:
```cfg
sp_balance_nested_parens        = true
indent_member                   = 2
indent_member_single            = true
```

The command I was specifically using was:
```bash
uncrustify -c test_config.cfg -lCPP --check test_file.cxx
echo "$?"  # shows me "70"
```

---
Thank you @mwoehlke-kitware for helping my isolate the code and config options that were causing my issue.

**Comment by guy-maurel** [comment]
The error message is not correct.
Thanks for the message.

**Comment by guy-maurel** [comment]
PR #3721 is a bugfix proposal.
Please test it and report.
