### ISSUE TITLE
Enhancement:  squeeze namespace closing braces

### ISSUE THREAD

**Issue by meldavis** [uncrustify/uncrustify#374]
I wish for a way to format:

``` c++
namespace ns1 {
namespace ns2 {
namespace ns3 {

class class1 {
};
}
}
}
```

so that the namespaces' closing braces are squeezed onto one line:

``` c++
namespace ns1 {
namespace ns2 {
namespace ns3 {

class class1 {
};

}}}
```

 I have tried setting 

``` INI
nl_after_brace_close  false
nl_brace_brace  remove
nl_remove_extra_lines  1
eat_blanks_before_close_brace  true
```

  But it still expands the squeezed braces.

Note:  If lines under a namespace are being indented, then, probably, squeezing together the braces would not be desired.   However, if the content under the namespace is not indented, then squeezed braces are likely preferred.  If multiple namespaces are defined in a file, this visually separates the end of one  namespace from, possibly, the beginning of the next one.

For example: 

``` c++
namespace company {
namespace application {
namespace module {
namespace detail {

class some_internal_class {};

}}}}

namespace company {
namespace application {
namespace module {

class public_interface_class {};

}}}
```

**Comment by gmaurel** [comment]
uncrustify has nothing for you. Sorry.
