### ISSUE TITLE
objc colon alignment issue with ternary operator

### ISSUE THREAD

**Issue by PoeticPete** [uncrustify/uncrustify#3744]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Ternary operators mess up the `align_oc_msg_colon_span` option.

Command: `./uncrustify -c test.config -f test.mm > test.mm.out`

```
// Original file
static void func() {
    [object test:NO ? NO : NO
           test2:YES
           test3:YES];
}
```

```
// After running uncrustify
static void func() {
	[object test:NO ? NO : NO
	 test2:YES
	       test3:YES];
}
```

Config file is just 1 line
```
align_oc_msg_colon_span         = 1
```

[debug.txt](https://github.com/uncrustify/uncrustify/files/9091437/debug.txt)

I just built latest master. My only changes are logging statements.

```
./uncrustify -v
Uncrustify-0.75.0-165-595e9a04-dirty
```

I've bisected it to this commit: https://github.com/uncrustify/uncrustify/commit/1564795d567ed81d4166d0bdcd5a4e507496c003

**Comment by micheleCTDE** [comment]
@PoeticPete 
The : between NO and NO is correctly identified as colon. It seems to me you may need to update your PR #3739 to check when a colon is a conditional color or an OC  parameter colon.

**Comment by PoeticPete** [comment]
I'll make that update.

Although this bug is unrelated because all diffs prior to @https://github.com/uncrustify/uncrustify/commit/1564795d567ed81d4166d0bdcd5a4e507496c003 don't have this issue.
