### ISSUE TITLE
No option to control Objective-C access modifier @public, @protected, @private

### ISSUE THREAD

**Issue by mgrebenets** [uncrustify/uncrustify#376]
The only option available to control access modifiers is for C++ `public:` and `private:`, as well as `protected:`. However, these options have no effect on Objective-C `@public`, `@protected` and `@private`.

``` objective-c
@implementation FMWeakCountedSet {
    @private
    __weak id *_weakObjects;
}

```

**Comment by Krizai** [comment]
@mgrebenets Which type of control do you think will be useful for them  ?

**Comment by mgrebenets** [comment]
I guess a standard indentation control.
Like 0 spaces (all the way to the left), 2 spaces and 4 spaces are the most comm use-cases for formatting control access modifiers.

**Comment by guy-maurel** [comment]
Please push files with input, expected output and config

**Comment by gmaurel** [comment]
No answer, we close.
