### ISSUE TITLE
Bug: Objective-C __has_include is not handled properly.

### ISSUE THREAD

**Issue by mgrebenets** [uncrustify/uncrustify#378]
uncrustify doesn't handle Objective-C `__has_include` language extension properly. 

More specifically, it doesn't treat header inside `__has_include` as such and applies other rules to it. For example

``` objective-c
#if defined(__has_include) && __has_include(<FacebookSDK/FacebookSDK.h>)
    // ...
#endif
```

is turned into

``` objective-c
#if defined(__has_include) && __has_include(<FacebookSDK / FacebookSDK.h>)
    // ...
#endif
```

This happens when rule for forcing spaces around arithmentic operations is enabled.

```
sp_arith    force
```

And if an `sp_compare` option is forced, then it gets worse

``` objective-c
#if defined(__has_include) && __has_include(< FacebookSDK / FacebookSDK.h >)
    // ...
#endif
```

The bug with `sp_compare` is definitely related to https://github.com/bengardner/uncrustify/issues/195

This is not just a styling problem, those extra spaces change the way a code actually compiles. Even if the project has a `<FacebookSDK/FacebookSDK.h>` include, the `__has_include(<FacebookSDK / FacebookSDK.h>)` will be false anyway.

**Comment by flabrie** [comment]
I have the same problem here with the `__has_include()` condition.

**Comment by mgrebenets** [comment]
I have a dirty hack to fix it up.

``` bash
FILE_PATH=filename.m
# Fix the '__has_include(< UIKit / UIKit.h >)' and similar problems
	awk '{
		if (/__has_include/) {
			sub(/\(< */, "(<");
			sub(/ *>\)/, ">)");
			sub(/ *\/ */, "/");
		}
		print;
	}' "${FILE_PATH}"
```

Should be ran after uncrustify.

But that's  just a hack, ideally uncrusity should not break it in the first place.

**Comment by mgrebenets** [comment]
Btw, just an update, clang-format has exactly the same issue.

**Comment by flabrie** [comment]
Any plan to fix this bug yet?

**Comment by gmaurel** [comment]
well. We have to less people to fix all the bugs.
It will be fine/welcome if you would work on the Objectiv C part.
I am working on C++ and the system itself.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by gmaurel** [comment]
No answer, we close.
