### ISSUE TITLE
Braces infinitely pushed by `align_struct_init_span` when using commas before closing brace

### ISSUE THREAD

**Issue by rankaisija64** [uncrustify/uncrustify#3786]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Current version: Uncrustify-0.75.1_f
[debug.txt](https://pastebin.com/CJSRh9yK)

Debug text is generated with the latest version I was able to use with my WSL. Mainly I use `0.75.1` on Windows. There is no difference between these two when it comes to this issue though.

Here's the original file:
```c
unsigned char wow[][2] = {
	{ 0, 24, },
	{ 152, 1, },
};
```
Running the formatter once gives pretty much the results I expect.
```c
unsigned char wow[][2] = {
	{ 0,   24, },
	{ 152, 1,  },
};
```
Every time it's ran again it keeps slightly pushin the braces away. Here's the results after 8 reformats.
```c
unsigned char wow[][2] = {
	{ 0,   24,                           },
	{ 152, 1,                            },
};
```
I noticed that this behaviour only happens because I have the commas inside the braces after the last numbers. For example this here wouldn't have the same issue:
```c
unsigned char wow[][2] = {
	{ 0,   24   },
	{ 152, 1    },
};
```

**Comment by guy-maurel** [comment]
PR #3826 is a bug fix proposal.
Please test it and report.

**Comment by rankaisija64** [comment]
Still keeps pushing on each format.

**Comment by guy-maurel** [comment]
Please, give us the output of:
```.txt
uncrustify -v
uncrustify <your data> -p p.txt
```

**Comment by rankaisija64** [comment]
I'm terribly sorry. I failed to do the test properly last night so the results were not correct. I can actually confirm that it works now.
