### ISSUE TITLE
RFC: OK to implement ternary operator (?:) in brace_cleanup.cpp?

### ISSUE THREAD

**Issue by fwojcik** [uncrustify/uncrustify#3806]
When running uncrustify on my sources, there is a specific problem that I run into somewhat often, which is that multi-level ternary operators get mis-indented. For example, here is a manual fixup of this problem:
```diff
     if (len <= 24) {
         return len <= 12 ?
                    (len <= 4 ?
                        Hash32Len0to4(s, len, seed) :
                        Hash32Len5to12<bswap>(s, len, seed)) :
-                       Hash32Len13to24<bswap>(s, len, seed);
+                   Hash32Len13to24<bswap>(s, len, seed);
     } 
```

When I tried to fix this with something like:
```diff
commit 2cd6c43d1d4c003819db19adfe1466b2a9289616
Author: Frank J. T. Wojcik <fwojcik@uw.edu>
Date:   Wed Jul 13 13:55:48 2022 -0700

    Correct indentation for multi-level ternary operators

diff --git a/src/indent.cpp b/src/indent.cpp
index 45aac7a8..7494f5d2 100644
--- a/src/indent.cpp
+++ b/src/indent.cpp
@@ -4070,7 +4070,7 @@ void indent_text()
                     || chunk_is_token(pc, CT_PAREN_OPEN)))
          {
             log_rule_B("indent_ternary_operator");
-            Chunk *tmp = prev->GetPrevType(CT_QUESTION);
+            Chunk *tmp = prev->GetPrevType(CT_QUESTION, prev->level);
 
             if (tmp->IsNotNullChunk())
             {
@@ -4088,7 +4088,7 @@ void indent_text()
                  && chunk_is_token(pc, CT_COND_COLON))
          {
             log_rule_B("indent_ternary_operator");
-            Chunk *tmp = pc->GetPrevType(CT_QUESTION);
+            Chunk *tmp = pc->GetPrevType(CT_QUESTION, pc->level);
 
             if (tmp->IsNotNullChunk())
             {
```

I was partially successful, but writing some unit tests for this change showed that this fix was incomplete at best. The reason that it mostly worked in my codebase was that many of the ternary expressions there had enclosing parentheses, which meant that the `level` of those chunks were essentially correct. However, it seems that ternary expressions without parens are all on the same level:
```
#   2>            NEWLINE|               NONE|     PARENT_NOT_SET[ 16/ 16/  5/  0][1/1/0][             0][1-0]
#   3>             RETURN|               NONE|     PARENT_NOT_SET[  9/  5/ 11/  0][1/1/0][        e 0000][0-0]         return
#   3>               WORD|               NONE|     PARENT_NOT_SET[ 16/ 12/ 17/  1][1/1/0][        8 0000][0-0]                maybe
#   3>           QUESTION|               NONE|     PARENT_NOT_SET[ 22/ 18/ 19/  1][1/1/0][1000 2000 0000][0-0]                      ?
#   3>             NUMBER|               NONE|     PARENT_NOT_SET[ 24/ 20/ 23/  1][1/1/0][1000 0000 8000][0-0]                        123
#   3>              ARITH|               NONE|     PARENT_NOT_SET[ 28/ 24/ 25/  1][1/1/0][1000 2000 0000][0-0]                            +
#   3>               WORD|               NONE|     PARENT_NOT_SET[ 30/ 26/ 29/  1][1/1/0][1000 0000 8000][0-0]                              var
#   3>         COND_COLON|               NONE|     PARENT_NOT_SET[ 34/ 30/ 31/  1][1/1/0][1000 2000 0000][0-0]                                  :
#   3>             NUMBER|               NONE|     PARENT_NOT_SET[ 36/ 32/ 35/  1][1/1/0][1000 0000 c000][0-0]                                    456
#   3>              ARITH|               NONE|     PARENT_NOT_SET[ 40/ 36/ 37/  1][1/1/0][1000 2000 0000][0-0]                                        *
#   3>               WORD|               NONE|     PARENT_NOT_SET[ 42/ 38/ 41/  1][1/1/0][1000 0000 8000][0-0]                                          var
#   3>          SEMICOLON|               NONE|     PARENT_NOT_SET[ 45/ 41/ 42/  0][1/1/0][1000 2000 0000][0-0]                                             ;
#   3>            NEWLINE|               NONE|     PARENT_NOT_SET[ 46/ 42/  1/  0][1/1/0][             0][1-0]
```

So my questions are:
- is there any known reason why the if_true and if_false branches of the ternary operator are all on the same level?
- similarly, if I change this, do you think anything will break?
- if changing this isn't a good idea, then do you have a good suggestion for finding the matching `?` for a given `:`?
- does it make sense to implement handling of the ternary operator in `brace_cleanup.cpp`? From the comments, it seems to want to handle all nestable structures, which the ternary operator definitely is.
- if not, where should it be fixed?
- does it make sense to use VBRACE chunks to enclose each branch or not?
- does it make sense to set the parent of any of these chunks?

I also do not know how this operator is used outside of C/C++, so my questions may have a sort of language tunnel-vision. Please feel free to let me know anything else relevant.

Thanks!

**Comment by guy-maurel** [comment]
I need your config file.
Better, you make a proposal PR

**Comment by fwojcik** [comment]
I will work on coming up with a specific config and full code demo if you think it will help, sure.

However, the whole reason for me filing this issue and asking these questions is to _avoid_ starting with a proposal PR. I do not want to put lots of effort into coding a solution only to later discover that there is some important aspect that was not handled, or that the chosen solution fundamentally doesn't work for a particular language,or that it is incompatible with some other formatting option that I personally would never use. Developer time is limited, and it is far more efficient to find problems in the design phase. I would like to at least agree on the sketch of the design before beginning implementation.

So if you could please answer the specific questions I posed, I would really appreciate it. Thank you.

**Comment by guy-maurel** [comment]
You are right. I try to give you an answer.

> is there any known reason why the if_true and if_false branches of the ternary operator are all on the same level?
  I don't know
> similarly, if I change this, do you think anything will break?
    If yes, one may separate the languages, one for C/C++, one for the others
> if changing this isn't a good idea, then do you have a good suggestion for finding the matching ? for a given :?
  The use of level is fine
> does it make sense to implement handling of the ternary operator in brace_cleanup.cpp? From the comments, it seems to want to handle all nestable structures, which the ternary operator definitely is.
  Yes
> if not, where should it be fixed?
> does it make sense to use VBRACE chunks to enclose each branch or not?
  YES! It will also change the level(s)
> does it make sense to set the parent of any of these chunks?
  YES
uncrustify defines a "parent" but doesn't use it every where

It will be very useful to introduce all your data for a test

**Comment by fwojcik** [comment]
Excellent. Thank you for answering. I'll try to get to this as soon as I can, which is probably less soon than I'd like. :)
