### ISSUE TITLE
Parsing error on formatting embedded SQL (informix)

### ISSUE THREAD

**Issue by awilhelmer** [uncrustify/uncrustify#386]
The following syntax in C produce parsing errors on formatting:

  $ DECLARE cursorName CURSOR for
  SELECT
   a,
   b
INTO
  $struct->a,
  $struct->b
FROM table;

Message:
Error: Expected '(', got 'SELECT' for 'FOR'

**Comment by bengardner** [comment]
Uncrustify only looks for lines starting with `EXEC SQL` when parsing embedded SQL.
See tests/input/sql/mysql.sqc for examples.

It doesn't currently support the '$' format.
