### ISSUE TITLE
[C] Single line while loop with comment between the braces, braces get reversed, breaking compilation

### ISSUE THREAD

**Issue by tz18** [uncrustify/uncrustify#3873]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

[debug.txt](https://gist.github.com/tz18/9d94a5e541e65c2596cc38122614458e)
[debug.A](https://gist.github.com/tz18/6b7e5ba12308584faf0a8cea2d2e7d96)
[example.c](https://gist.github.com/tz18/71cee31ce6f2a66af4b95b361db7611a)
[example.c.uncrustify](https://gist.github.com/tz18/51333b7a1a8c6b5bf93da3d40a884c4a)
current version: Uncrustify_d-0.75.0-365-5c8a10f2

Not sure which option in my config is causing this.

`while(true) { /* hello */ }`
gets rewritten to
`while(true) /* hello */ } {`

Which is incorrect and doesn't compile.

[a7a8fb3](https://github.com/uncrustify/uncrustify/commit/a7a8fb35d653e0b49e1c86f2eb8a2970025d5989) does not have the issue

**Comment by guy-maurel** [comment]
The option is _nl_while_brace = add_,
but doesn't run properly

**Comment by guy-maurel** [comment]
PR #3881 is a bug fix proposal.
Please test it and report.
