### ISSUE TITLE
"namespace" not ignored in a C-Header 

### ISSUE THREAD

**Issue by fenugrec** [uncrustify/uncrustify#3874]
A bit of a contrived example (simplified from actual code). Source file test.h :

```
enum namespace tmpvar;

int var2;
```

I happen to have an enum type called `namespace`. Bad idea, and I will change it, but it's still valid C.

uncrustify complains , despite detecting it as a C header: 

```
$ uncrustify -p debug.txt --no-backup -c ../uncrustify.cfg  -f test.h
do_source_file(1507): Parsing: test.h as language C-Header
newlines_cleanup_braces(4879): Missing BRACE_OPEN after namespace
   orig_line is 1, orig_col is 6
```

(doesn't actually produce a debug.txt file...)

- version : Uncrustify_d-0.75.1_f on Arch

Thanks !

**Comment by guy-maurel** [comment]
your test.h file might be used (with #include test.h) from a C-source as well from a C++-source.
In the first case, namespace is not a keyword,
in the second case, namespace is a keyword.
uncrustify doesn't have any information about that.
Sorry!

**Comment by fenugrec** [comment]
> your test.h file might be used (with #include test.h) from a C-source as well from a C++-source.

I had not considered this. No problem.

**Comment by guy-maurel** [comment]
you may also use the command line option:
_uncrustify ... -l C_
to say to uncrustify which language you are using.
