### ISSUE TITLE
No Way to Use Default NS_ENUM Spacing

### ISSUE THREAD

**Issue by sethfri** [uncrustify/uncrustify#388]
By default, an NS_ENUM is formatted like this in Xcode:

```objc
typedef NS_ENUM(NSUInteger, SomeType) {
    SomeTypeA,
    SomeTypeB,
    SomeTypeC,
};
```

However, Uncrustify seems to want to add a space between "NS_ENUM" and "(" so that it looks like this

```objc
typedef NS_ENUM (NSUInteger, SomeType) {
    SomeTypeA,
    SomeTypeB,
    SomeTypeC,
};
```

To my knowledge, there's not a flag to override this behavior. Is there? If not, this should be added.

**Comment by pankkor** [comment]
Have somebody found a solution?

**Comment by pankkor** [comment]
There is an option to control enum paren spacing.
```
# Add or remove space in 'NS_ENUM ('
sp_enum_paren                             = ignore   # ignore/add/remove/force
```
This issue can be closed

**Comment by hpsoar** [comment]
seems that this options has no effect, is there a bug?

**Comment by hpsoar** [comment]
sorry, I didn't specify -l option when I use the command to process multiple files, may be the auto detecting process can be refined
