### ISSUE TITLE
c# align variable names broken since v0.63

### ISSUE THREAD

**Issue by LaraSQP** [uncrustify/uncrustify#3888]
First of all, my sincere thanks to the devs for this must-have tool.

The problem is the alignment of variable names, which is broken since v0.63

The expected outcome is:

```
public string			add	= "add";
private static readonly string	insert	= "Insert";
public int			count	= 0;
```

... but what I get from all versions after v0.63 is:

```
public string add			= "add";
private static readonly string insert	= "Insert";
public int count			= 0;
```

I have not changed the configuration file which is as follows regarding this issue:

```
align_typedef_star_style		= 1
align_var_def_star_style		= 0
align_with_tabs				= true
align_on_tabstop			= true
align_enum_equ_span			= 4
align_nl_cont				= true
align_var_def_span			= 2
align_var_def_inline			= true
align_var_def_colon			= true
align_assign_span			= 1
align_struct_init_span			= 3
align_var_struct_span			= 3
align_right_cmt_span			= 3
align_pp_define_span			= 3
align_pp_define_gap			= 4
align_number_left			= true
align_typedef_span			= 5
align_typedef_gap			= 3
```

I really want to move on to a newer version because a lot of bugs have been fixed (e.g., switch statements).

Any help would be most appreciated.

**Comment by guy-maurel** [comment]
The current git runs pretty well.
```.txt
Uncrustify_d-0.75.0-391-6d21e020
normal
do_source_file(1524): Parsing: LaraSQP.cs as language CS
public string                   add     = "add";
private static readonly string  insert  = "Insert";
public int                      count   = 0;
```

**Comment by LaraSQP** [comment]
Please post the relevant parts of your config so I can see where I went wrong.

**Comment by micheleCTDEAdmin** [comment]
@LaraSQP 
It seems you are missing the threshold config. `align_var_def_span` is not enough, you need to set also `align_var_def_thresh` to set the max column gap to look for alignment. Suggest you start with a big value (40) and then reduce to find a value you are happy with.
Variable alignment definitely works fine with the right options.

**Comment by LaraSQP** [comment]
I have created a config file with nothing but the two parameters `align_var_def_span` and `align_var_def_thresh` but the problem remains. In fact, it is worse because not even the assignments are aligned anymore.

Could you please post a working config file? I will then work my way back to what I need elsewhere.

Much, much appreciated.

**Comment by micheleCTDE** [comment]
Here you go (apologies if it is a big one, I had it ready). There are a number of `span` and `thresh` options, for different purposes. 
[cfg.cfg.zip](https://github.com/uncrustify/uncrustify/files/10046202/cfg.cfg.zip)

**Comment by LaraSQP** [comment]
Great, thanks again.

**Comment by micheleCTDE** [comment]
No problem. Ok to close this issue then?

**Comment by LaraSQP** [comment]
It's a big file, like you said. I need a bit of time to work this out. Maybe tomorrow. But I will close the ticket or else.

**Comment by LaraSQP** [comment]
Turns out your config file chokes `uncrustify.exe` (SHA1: `C3E8FAA74DDA95272B88E9BD9A1A53063C7EA6BD`) so there is something else going on here.

I am closing this issue since the alignment problem does not seem to be what's actually wrong.

Thank you for your quick and kind support.

**Comment by micheleCTDEAdmin** [comment]
> Turns out your config file chokes uncrustify.exe (SHA1: C3E8FAA74DDA95272B88E9BD9A1A53063C7EA6BD) so there is something else going on here.

Can you give me some more feedback? The config I uploaded works fine here with latest master code...

**Comment by LaraSQP** [comment]
I wish I could.

I tried getting some logs or errors but `uncrustify` simply does nothing with that config.

The likely culprits are the source files I am using. I mean, what else?

**Comment by micheleCTDE** [comment]
do you have any error message on the command line? anything at all?

If you are using version 0.63, it is quite likely that uncrustify will complain since all the options would be unrecognized. If you launch it from command line, you should definitely get some sort of output I guess.

**Comment by LaraSQP** [comment]
0.63 is the last one that works.

After that, the config chokes uncrustify.

This is going to take me some time to figure out. I'm working through vs2022 and will need to go to the command line, like you said.

**Comment by micheleCTDE** [comment]
ok, please report back once you have a chance to look into it. Even better, try using latest version if possible.
