### ISSUE TITLE
OC methods are getting split

### ISSUE THREAD

**Issue by sethfri** [uncrustify/uncrustify#390]
I have a method that looks like this:

```objc
[self.metricsStore logMetricWithSource:someSource
                                  name:someName
                                 count:1];
```

And for some reason Uncrustify is splitting it to look like this:

```objc
[self.metricsStore
     logMetricWithSource:someSource
                    name:someName
                   count:1];
```

However, Uncrustify is not doing this with most methods that span multiple lines, like:

```objc
[foo bar:X
     baz:Y];
```

Does anyone know what flag causes this?

**Comment by sethfri** [comment]
Ping. Anyone know what flag is causing this?

**Comment by sobeski** [comment]
I ran into the same thing and fixed it with this pull request:
https://github.com/bengardner/uncrustify/pull/412

**Comment by jtwigg** [comment]
@sobeski  Thanks for the solution. This worked for me.
