### ISSUE TITLE
uncrustify-0.76.0.tar.gz release tarball is broken

### ISSUE THREAD

**Issue by mcatanzaro** [uncrustify/uncrustify#3901]
Looks like something went very wrong when generating the uncrustify-0.76.0.tar.gz hosted at https://prdownloads.sourceforge.net/uncrustify/uncrustify-0.76.0.tar.gz. Instead of containing a toplevel directory `uncrustify-0.76.0`, instead all file names are prefixed with `uncrustify-0.76.0`. For example, the tarball contains the file `uncrustify-0.76.0.gitignore`. It's as if the `/` directory separator got nuked somehow.

**Comment by guy-maurel** [comment]
Thanks for the message
Fixed

**Comment by mcatanzaro** [comment]
Verified, thanks.

**Comment by gmaurel** [comment]
How could you find the fail, short after I upload the software?guy
-------- Ursprüngliche Nachricht --------Von: Michael Catanzaro ***@***.***> Datum: 30.11.22  18:25  (GMT+01:00) An: uncrustify/uncrustify ***@***.***> Cc: Subscribed ***@***.***> Betreff: Re: [uncrustify/uncrustify] uncrustify-0.76.0.tar.gz release tarball is broken (Issue #3901) 
Verified, thanks.

**Comment by mcatanzaro** [comment]
> How could you find the fail, short after I upload the software?

I was trying to update the Fedora package. https://release-monitoring.org/project/5043/ creates a bug report https://bugzilla.redhat.com/show_bug.cgi?id=2149398 when you create a new release.
