### ISSUE TITLE
Bad layout for IBOutletCollection() macro under Objective-C

### ISSUE THREAD

**Issue by flabrie** [uncrustify/uncrustify#391]
In Objective-C, we can define properties with IBOutletCollection macro:

```
@property (nonatomic, copy) IBOutletCollection(UITextField) NSArray *textFields;
```

Unfortunately, _uncrustify_ doesn't format these correctly: the space before `IBOutletCollection` is removed, and a space is added between the `*` and the `textFields` variable name.

```
@property (nonatomic, copy)IBOutletCollection(UITextField) NSArray * textFields;
```

**Comment by Visput** [comment]
Have the same problem.

**Comment by realf** [comment]
+1

**Comment by Sunnyyoung** [comment]
+1

**Comment by addonszz** [comment]
Post also the debug results. Example:
Uncrustify.exe -c amxmodx.cfg -f new.sma -p debug.txt

[debug.txt](https://github.com/bengardner/uncrustify/files/105036/debug.txt)

**Comment by mgrebenets** [comment]
I have some kind of workaround for this.

```bash
# Custom Types
# -------

# This will fix an issue like this:
# @property (nonatomic, copy)IBOutletCollection(UIBarButtonItem) NSArray *leftBarButtonItemsCollection;
# Uncrustify will now treat IBOutletCollection as a type and also have to tell it that NSArray is a type too
# So that uncrustify doesn't treat it as type case and remove the space before NSArray like so
# @property (nonatomic, copy) IBOutletCollection(UIBarButtonItem) NSArray *leftBarButtonItemsCollection;
type IBOutletCollection NSArray
```

But this is a work around. I'd rather prefer uncrustify to understand this Objective-C feature by default.

**Comment by realf** [comment]
[debug.txt](https://github.com/bengardner/uncrustify/files/107505/debug.txt)
Please see debug results.
Parameters: `uncrustify -c uncrustify.cfg -f NGBaseViewController.h -p debug.txt -l OC`

**Comment by bengardner** [comment]
I don't use Objective-C, so I don't know what the `(nonatomic, copy)` part means.
Is that part of the `@property` or `IBOutletCollection`?

```
@property (nonatomic, copy) IBOutletCollection(UITextField) NSArray *textFields;
```
So, is it a property qualifier that may always be there?

**Comment by realf** [comment]
`(nonatomic, copy)` part is property attributes. They are optional. Syntax for attributes is:
```
@property (<attribute list>) propertyName;
```
where `<attribute list>` is the list of attributes separated by commas.
Some attributes may have values:
```
@property (nonatomic, getter=isConditionValid) conditionValid;
```

**Comment by revolter** [comment]
And on top of this, [UncrustifyX](https://github.com/ryanmaxwell/UncrustifyX) doesn't support `type IBOutletCollection NSArray`.

**Comment by CDanU** [comment]
UncrustifyX is 3rdParty software, we are not involved in that. 

The problem is that I know nothing about obj-c and don't really have all that much interest in it. Priority wise it is right down at he bottom of my list. 

We take patches however and would really be glad if someone would like to step up and fix some obj-c related bugs.

**Comment by guy-maurel** [comment]
Patches are welcome. Every time.

**Comment by revolter** [comment]
@CDanU, I know that it's 3rd party.

The thing is that except clang format, this is the second most founded result for Objective C formatting tools.

It's a GUI that creates an Uncrustify config file using documentation and drag and drop. It is comparable with UniversalIndentGUI but tons better.

@guy-maurel, Is there any overview of the source code? As this seems like a pretty big project.

**Comment by guy-maurel** [comment]
Sure.
Which kind of overview to you wish?

**Comment by revolter** [comment]
A short presentation of the modules or structure. For example, is there a/some files specifically for Obj-C formatting? Where can one find the core logic of an option?

**Comment by CDanU** [comment]
> It's a GUI that creates an Uncrustify config file using documentation and drag and drop. It is comparable with UniversalIndentGUI but tons better.
Neat, could you check out https://cdanu.github.io/uncrustify_config_preview/index.html and tell me what it is missing compared to UncrustifyX?

**Comment by gmaurel** [comment]
I got contact with the developer. He has very short time for that. Sorry.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by gmaurel** [comment]
No answer, we close.
