### ISSUE TITLE
nl_func_call_paren should only remove a newline between the function name and first parenthesis that follow

### ISSUE THREAD

**Issue by DeuceBox** [uncrustify/uncrustify#3914]
[debug.txt](https://github.com/uncrustify/uncrustify/files/10262227/debug.txt)

Code to be uncrustifyed
```
void foo()
{
using namespace boost::program_options;
options_description desc("Allowed options");
desc.add_options()
    ("help,h", "produce help message")
    ("version,v", "print the version number")
    ("include-path,I", value< vector<string> >(), "include path")
    ("input-file,i", value<string>(), "input file");
}
```

Generated results:

```
void foo()
{
	using namespace boost::program_options;
	options_description desc("Allowed options");
	desc.add_options()("help,h", "produce help message")("version,v", "print the version number")("include-path,I", value< vector<string> >(), "include path")("input-file,i", value<string>(), "input file");
}

```

Expected results:

```
void foo()
{
	using namespace boost::program_options;
	options_description desc("Allowed options");
	desc.add_options()
	        ("help,h", "produce help message")
	        ("version,v", "print the version number")
	        ("include-path,I", value< vector<string> >(), "include path")
	        ("input-file,i", value<string>(), "input file");
}

```

Version:
`Uncrustify-0.76.0-21-e1ab302b`

We can see that boost::program_options's add_options() uses a kind-of fluent style API, but it appears uncrustify tries to remove all the newlines before every open parenthesis following the function name

**Comment by gmaurel** [comment]
Can you provide a comple source (with #include...) which can be compiled?
Thanks.

**Comment by DeuceBox** [comment]
Sure, a slightly modified version of my original example:

```
#include <boost/program_options.hpp>

void foo()
{
	using namespace boost::program_options;
        using namespace std;
	options_description desc("Allowed options");
	desc.add_options()
	        ("help,h", "produce help message")
	        ("version,v", "print the version number")
	        ("include-path,I", value< vector<string> >(), "include path")
	        ("input-file,i", value<string>(), "input file");
}
```

Compiling example of the above: https://godbolt.org/z/hGejGGE1h

Alternatively, a similar demonstration with no dependencies:

``` 
struct foo
{
        foo& add_options()
        {
                return *this;
        }

        foo& operator()(int x)
        {
                return *this;
        }
};

int
main(int argc, char *argv[])
{
        foo f;
        f.add_options()
                (1)
                (2)
                (3);
}
```

Which, with `nl_func_call_paren = remove` results unexpectedly in

```
struct foo
{
	foo& add_options()
	{
		return *this;
	}

	foo& operator()(int x)
	{
		return *this;
	}
};

int
main(int argc, char *argv[])
{
	foo f;
	f.add_options()(1)(2)(3);
}

```

**Comment by guy-maurel** [comment]
Do we have to deal with functor?

**Comment by DeuceBox** [comment]
I don't know if you need to (or if you even could) explicitly identify functors and modify behaviour around them. Maybe if there was some additional option to check if nl_func_call_paren would be invoked, check if after removing the newline, if the opening parenthesis would end up adjacent to a closing parenthsis on the previous line, and if it would, ignore nl_func_call_paren in that case?

**Comment by guy-maurel** [comment]
PR #3948 is a bug fix proposal.
Please test it and report.

**Comment by guy-maurel** [comment]
PR #3948  is a new bug fix proposal.
Please test it and report.
