### ISSUE TITLE
indent_member_single = true causes NO output to be generated

### ISSUE THREAD

**Issue by jodyhagins** [uncrustify/uncrustify#3915]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

The source file is named file.txt - because the site would not let me upload the file as either .cpp or .hpp - which makes absolutely no sense.

There is no use posting the result, because the command generates absolutely nothing to stdout.  Change the "indent_member_single  value" to "false" and you will see output.

Uncrustify-0.76.0-21-e1ab302b

[debug.txt](https://github.com/uncrustify/uncrustify/files/10263050/debug.txt)
[file.txt](https://github.com/uncrustify/uncrustify/files/10263063/file.txt)

**Comment by guy-maurel** [comment]
Using the command:
uncrustify -c jodyhagins.cfg -f jodyhagins.cpp -L A 2>A.txt

you get at the end of the A.txt file an information:
```.log
indent_text(1303): pop_pc orig line is 6, orig col is 35, Text() is '==', type is COMPARE
indent_text(1307): pc orig line is 6, orig col is 35, Text() is '==', type is COMPARE
indent_text(1313): pc orig line is 6, orig col is 35, Text() is '==', type is COMPARE
ParseFrame::pop (indent_text:1314): orig line is    6, orig col is   35, type is      COMPARE,
ParseFrame::pop (indent_text:1314): the type is COMPARE, is not coded. Please make a call.
```
It is now my job to look why. Thanks for the message.

**Comment by guy-maurel** [comment]
PR #3934 is a bug fix proposal.
Please test it and report.

**Comment by jodyhagins** [comment]
Yes, this seems to have addressed the issue.  Thank you.
