### ISSUE TITLE
Feature request:  add "sp_cmt_cpp_pvs"?

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#3919]
We would like to activate this parameter:

sp_cmt_cpp_start = add

Exception:  this particular case where we want to disable a specific PVS-Studio warning:

```
void Test
{
    // <-- Here we want a space after //
    DoSomething();   //-V612 : warning #612 disabled, because blablabla.  No space after //, unless PVS will not recognize it.
}
```

I guess we would need a new parameter like "sp_cmt_cpp_qttr".  Just a suggestion.

```
# If true, space added with sp_cmt_cpp_start will be added after PVS-Studio 
# special mark-up comment, like '//-V1234' or '//-V::1234'
sp_cmt_cpp_pvs = false    # true/false
```
Reference:  https://pvs-studio.com/en/docs/manual/0017/

**Comment by guy-maurel** [comment]
PR #3935 is a bug fix proposal.
Please test it and report.
