### ISSUE TITLE
code_width doesnt do what it says it should?

### ISSUE THREAD

**Issue by pikaboo** [uncrustify/uncrustify#393]
I want my line width to be max 200

I've tried setting code_width to 200, or to 0
but it still limits it to 80 for some reason
How to fix that? Is there another property I need?

**Comment by bengardner** [comment]
Make sure you don't have `code_width` specified multiple times in your config file.
Failing that, please specify the language and provide example code and configuration options.

**Comment by gmaurel** [comment]
And now? Can you push some examples?

**Comment by mihaipopescu** [comment]
@pikaboo Is this still relevant ?

**Comment by gmaurel** [comment]
NoResponse
