### ISSUE TITLE
Very ugly --help

### ISSUE THREAD

**Issue by wtfbbqhax** [uncrustify/uncrustify#394]
Running `uncrustify --help` produces an very ugly help output. 

1. Too dang long - an help output should realistically fit on most terminal screens without scrolling.

2. Usage and the "Usage Examples" are not supposed to be 2 different things (please move usage examples to the top and delete your existing usage section.)

3. Various problems with formatting (everything else here).

```
# uncrustify 
Usage:
uncrustify [options] [files ...]
```
Remove the '# uncrustify' entirely.

Remove the newline between "Usage:" and the "uncrustify..."

```
If no input files are specified, the input is read from stdin
If reading from stdin, you should specify the language using -l

If -F is used or files are specified on the command line, the output filename is
'prefix/filename' + suffix

When reading from stdin or doing a single file via the '-f' option,
the output is dumped to stdout, unless redirected with -o FILE.
```
Inconsistent choice of newlines which causes the 3 notes to stagger in a weird way. Choose at minimum 70 width please. (Though why break the lines at all?)

While this needs some adjustments, I would prefer it were rewritten altogether. The most important information for an new user is "the output". Considering that the default "suffix" is not specified, means that the "output" is not actually specified.

```
Errors are always dumped to stderr
```
This should go without saying; I would only be interested if you were not writing them to stderr.

```
The '-f' and '-o' options may not be used with '-F', '--replace' or '--no-backup'.
The '--prefix' and '--suffix' options may not be used with '--replace' or '--no-backup'.
```

This information should be apart of the description of the options. 

---
The remaining I'm just going to focus on the first "options" section.

```
Basic Options:
 -c CFG       : use the config file CFG
```
Arguably this needs to be in the "Config/Help", due to the not great name choices for theses sections. 

You should either use "CONFIG" or "FILE" but not "CFG".

Description should be "Path to configuration file."

```
 -f FILE      : process the single file FILE (output to stdout, use with -o)
```
Why does this one even exist? Does it do something different than if I had just specified the file without "-f"? If so, can I specify it multiple times?

```
 -o FILE      : Redirect stdout to FILE
```
What? Do you actually mean stdout or do you mean my uncrustified source code? If you actually mean stdout, then why? 

```
 -F FILE      : read files to process from FILE, one filename per line
```
This one just needs an capitol, and a period. 

```
 files        : files to process (can be combined with -F)
```
Delete this, it doesn't go here.

```
 --suffix SFX : Append SFX to the output filename. The default is '.uncrustify'
 --prefix PFX : Prepend PFX to the output filename path.
```
Finally! Now I know what the output is. 

```
 --replace    : replace source files (creates a backup)
 --no-backup  : replace files, no backup. Useful if files are under source control
```
Ok. So I know the default output, but this looks more useful. However, what is the "backup" file going to be named; is it even the same directory?

Do the "suffix" and "prefix" options apply to the backup file? What about the "-o" option?

More capitols and periods.

```
 --mtime      : preserve mtime on replaced files
```
Ok, this is a cute option, but it would be in my best interest to rebuild my project after running uncrustify. In case something broke. 

More capitols and periods.

```
 -l           : language override: C, CPP, D, CS, JAVA, PAWN, OC, OC+
```
Description should read "Specify alternate interpretation of input files". 

Which raises the question; how do you detect the language by default? The answer needs to be in the help output.

```
 -t           : load a file with types (usually not needed)
```
If its not usually needed, then it should be found in the manual; not taking up room. 

```
 -q           : quiet mode - no output on stderr (-L will override)
```
I do not know what "-L" does, but I can tell you this is backwards from what should normally happen. 

Normally "-q" would take precedence (or the order of the options would be important). 

```
 --frag       : code fragment, assume the first line is indented correctly
```

Undersold feature I think. 

More capitols and periods; "assume" -> "assumes".

**Comment by gmaurel** [comment]
Thanks
