### ISSUE TITLE
Uncrustify-0.76.0-88-3cb80873-dirty failing

### ISSUE THREAD

**Issue by Massimo-B** [uncrustify/uncrustify#3965]
```
uncrustify --version
Uncrustify-0.76.0-88-3cb80873-dirty
```

Uncrustify just doesn't output anything. Please adjust the subject as I can't give any description but a minimal example to reproduce:

```
$ cat win.cpp
void Win::fill()
{
    product->addItem(product.name + "%1");
}
```
```
$ uncrustify -f win.cpp -o win.cpp.unc -p debug
do_source_file: Parsing: win.cpp as language CPP
```
```
cat win.cpp.unc |wc -l
0
```

Why doesn't uncrustify output any error on STDOUT or STDERR? I general how do I debug such issues? Why is there no debug file created?

PS.: I'm migrating my own config on every update by
`gvimdiff ~/.uncrustify.cfg  <(uncrustify --show-config`

[win.cpp.txt](https://github.com/uncrustify/uncrustify/files/11028448/win.cpp.txt)
[uncrustify.cfg.txt](https://github.com/uncrustify/uncrustify/files/11027030/uncrustify.cfg.txt)

**Comment by Massimo-B** [comment]
Issue can also be reproduced on Uncrustify-0.76.0_f.

**Comment by guy-maurel** [comment]
using:
`uncrustify -c massimo-B.cfg -f massimo-B.cpp -o out.cpp -p p.txt -L A 2>A.txt`
you get at the end of the file A.txt:
```.txt
ParsingFrame::pop (indent_text:1308): orig line is    3, orig col is   35, type is        ARITH,
ParsingFrame::pop (indent_text:1308): the type is ARITH, is not coded. Please make a call.
```
Now, I got your call and I am looking...

**Comment by guy-maurel** [comment]
PR #3969 is a bug fix proposal.
Please test it and report.

**Comment by Massimo-B** [comment]
I tested it, now it fails for another part, attached the new example.
[win2.cpp.txt](https://github.com/uncrustify/uncrustify/files/11078921/win2.cpp.txt)

**Comment by gmaurel** [comment]
Please, test at new.
If you get a new problem, please open a new issue.

**Comment by Massimo-B** [comment]
Seems to be fixed now.
