### ISSUE TITLE
Add support for integer suffix constants 8, 16, 32, 128 (64 is already supported)

### ISSUE THREAD

**Issue by apop5** [uncrustify/uncrustify#3980]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Uncrustify supports the i64/I64 integer suffix constants, as detailed in:
https://learn.microsoft.com/en-us/cpp/c-language/c-integer-constants?view=msvc-170

But it only supports I64/i64, not the full range, as mentioned in
https://learn.microsoft.com/en-us/cpp/c-runtime-library/data-type-constants?view=msvc-170

It is missing suport for:
i8/I8, i16/I16, i32/I32, i128/I128

The existing function just needs expanded for the additional unsupported cases:
https://github.com/uncrustify/uncrustify/blob/master/src/tokenize.cpp#L1099

**Comment by guy-maurel** [comment]
Yes

**Comment by guy-maurel** [comment]
PR #3988 is a bug fix proposal.
Please test it and report.

**Comment by apop5** [comment]
Tested and this is working in the repository.
