### ISSUE TITLE
(C++) Crash when parsing dot `.` in a print statement with `indent_member_single` set to true

### ISSUE THREAD

**Issue by fletcher97** [uncrustify/uncrustify#3983]
I've been playing with uncrustify the past few days and ran into a problem while formatting one of my CPP files. Uncrustify simply didn't want to parse/format it. After a bit of digging I found that the issue only happened if the option `indent_member_single` was set to true.

Info:
* [Logs](https://gist.github.com/fletcher97/f36de195f846d9c4ea0f181a64370bec) (Generated with 75.1)
* Versions tested:
  * `Uncrustify-0.76.0-115-964a00cc`
  * `Uncrustify_d-0.75.1_f` (AUR shipped)
  * `Uncrustify-0.75.0 cfb9cdf7`
  * `Uncrustify-0.74.0 62048b01` (This version didn't crash)
* System: Manjaro (Arch linux) x86-64

Step to reproduce:
* create a cpp file with the following cotent
```cpp
#include <iostream>
struct s {int i;};

int main()
{
	struct s x;
	x.i = 5;
	std::cout << x.i << std::endl;
}	// main
```
* create a config file with only the option `indent_member_single` set to true
* execute uncrustify:
    `uncrustify -c tst.cfg -f test.cpp`

Expected output:
```
do_source_file(1507): Parsing: test.cpp as language CPP
#include <iostream>
struct s {int i;};

int main()
{
	struct s x;
	x.i = 5;
	std::cout << x.i << std::endl;
}       // main
```

Actual output:
```
do_source_file(1507): Parsing: test.cpp as language CPP
```

According to the doc for that option, it affects both `.` and `->` but this issue only happens with a dot. When using `->` uncrustify didn't crash

**Comment by micheleCTDE** [comment]
PR #3984  is a fix for the issue. Please test and let us know.

**Comment by micheleCTDE** [comment]
PR #3984 has been merged. Will wait closing the issue till confirmation from @fletcher97 that it works fine for him too.

**Comment by fletcher97** [comment]
Works fine. Thank you very much for the fast response
