### ISSUE TITLE
Request for if/else/if style matching

### ISSUE THREAD

**Issue by rdebath** [uncrustify/uncrustify#400]
I have a small problem with uncrustify's brace processing. Generally I use all these styles depending of the size of the code. Now I can (and have) turned this all off, but that doesn't match what I do.

The way I see it this is one statement.
```c
if (fn1()) { fn2(); fn3(); } else { fn4(); fn3() fn5(); }
```
For something this short that is fine so that should be left alone. If it's a little too long (but very simple) I may switch to this:
```c
if (fn1()) { fn2(); fn3(); } 
else       { fn4(); fn3(); fn5(); }
```
A single space after the else would look a bit untidy so I usually line up the braces; if anything is too long for a line but the whole statement is only a few lines it becomes this:
```c
if (fn1()) {
    fn2(); 
    fn3();
} else {
    fn4();
    fn3();
    fn5(); 
}
```
But I switch to this if the statement is too long (to fit on a "page" normally, but also if it's "too complicated to fit in one statement or concept").
```c
if (fn1()) 
{
    fn2(); 
    fn3();
}
else
{
    fn4();
    fn3();
    fn5(); 
}
```

The point is that these constructs don't mix, if the top is long form so it the bottom, but if they're self consistent (and not too long) there's no problem.
 
```
# Add or remove newline between 'if' and '{'
nl_if_brace                              = ignore   # ignore/add/remove/force

# Add or remove newline between '}' and 'else'
nl_brace_else                            = ignore   # ignore/add/remove/force

# Add or remove newline between 'else if' and '{'
# If set to ignore, nl_if_brace is used instead
nl_elseif_brace                          = ignore   # ignore/add/remove/force

# Add or remove newline between 'else' and '{'
nl_else_brace                            = ignore   # ignore/add/remove/force

# Add or remove newline between 'else' and 'if'
nl_else_if                               = ignore   # ignore/add/remove/force
```

**Comment by gmaurel** [comment]
With the actual git version and the options:
    # Add or remove newline between 'if' and '{'
    nl_if_brace                              = remove
    # Add or remove newline between '}' and 'else'
    nl_brace_else                            = remove
    # Add or remove newline between 'else' and '{'
    nl_else_brace                            = remove
    nl_after_semicolon                       = true

you get what you wanted to have:
if (fn1()) {
        fn2();
        fn3();
} else {
        fn4();
        fn3();
        fn5();
}
