### ISSUE TITLE
Test cli_options fails with 0.77.0

### ISSUE THREAD

**Issue by AMDmi3** [uncrustify/uncrustify#4015]
Test output log:
https://gist.github.com/AMDmi3/4868914d319744307bd295f466402ebf

**Comment by AMDmi3** [comment]
Ping. FYI I don't update FreeBSD port of uncrustify because of this failure.

**Comment by guy-maurel** [comment]
can you please the version 0.77.1 instead ?

**Comment by AMDmi3** [comment]
Affair it was the same with 0.77.1, but I'll recheck

**Comment by AMDmi3** [comment]
Yes, it's the same with 0.77.1

https://gist.github.com/AMDmi3/fef7ecaaadd7308e9ff3b4e05fe1a308

**Comment by guy-maurel** [comment]
under which OS do you get the problem?

**Comment by AMDmi3** [comment]
FreeBSD

**Comment by guy-maurel** [comment]
Sorry for the delay and for the confusion.
Please, comment it out, until I solve the problem.
see also the issue 4066

**Comment by guy-maurel** [comment]
The lines to test tracking (file test_cli_options.py) where commented out with the commit 1e4d1ba8b570b4bbd30422805961a8164bf6dd4e
on 2023-05-23 18:44:57
Do you have that?
