### ISSUE TITLE
Strange directory structure in 0.77.0 release

### ISSUE THREAD

**Issue by mcatanzaro** [uncrustify/uncrustify#4019]
The uncrustify-0.77.0.tar.gz available from https://prdownloads.sourceforge.net/uncrustify/uncrustify-0.77.0.tar.gz contains a toplevel directory named uncrustify-uncrustify-0.77.0. This seems odd. Previous releases did not have this extra directory, except for 0.70.1 from three years ago (#2558). It's not a big deal since it's easy to workaround by adding one cd into downstream build processes. But it means recipes that build 0.76.0 and prior releases will not be able to build 0.77.0.

(Note: uncrustify 0.77.1 has not yet been released to sourceforge. I'm ignoring the GitHub releases because they use the same very strange naming scheme "uncrustify-uncrustify" for tarball names instead of just "uncrustify".)

**Comment by gmaurel** [comment]
Yes, you are right.
I'll look.

**Comment by mcatanzaro** [comment]
I see it's fixed in the 0.77.1 that you just published. Thanks!
