### ISSUE TITLE
the type is INCDEC_AFTER, is not coded. Please make a call.

### ISSUE THREAD

**Issue by unity-emilk** [uncrustify/uncrustify#4026]
Running a build from current master: 31190617093a8dc1fa553c8df7d0714f05b2dec5

Another issue with the config line `indent_member_single=true`

A file like: 
```
class foo {
public:
    int var;
 
    foo(int x) { var = x; }
};

int main() 
{
    int a = 2;
    a++;

    foo f(3);
    f.var++;
}
```

fails with:
```
ParsingFrame::pop (indent_text:1351): orig line is   14, orig col is   10, type is INCDEC_AFTER,
ParsingFrame::pop (indent_text:1351): the type is INCDEC_AFTER, is not coded. Please make a call.
```

Let me know if you prefer I submit PRs instead of issues.

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by unity-emilk** [comment]
This seems to be all related to unhandled types in `parsing_frame.cpp`

I don't have test cases for all of them, but the following ones (and perhaps more) seem like they should be handled?

```
|| pc->GetType() == CT_OPERATOR
|| pc->GetType() == CT_CARET
|| pc->GetType() == CT_INCDEC_AFTER
|| pc->GetType() == CT_TYPE
|| pc->GetType() == CT_VBRACE_OPEN
|| pc->GetType() == CT_TEMPLATE
|| pc->GetType() == CT_ANGLE_OPEN
|| pc->GetType() == CT_OC_MSG_FUNC
|| pc->GetType() == CT_PTR_TYPE
|| pc->GetType() == CT_FUNC_CTOR_VAR
|| pc->GetType() == CT_DESTRUCTOR
|| pc->GetType() == CT_ASSIGN_FUNC_PROTO
```

**Comment by micheleCTDE** [comment]
PR #4026 is a fix the for the INCDEC_AFTER and some of the missing open parenthesis. At a later stage I will test a big test repo and see if any of the other missing CT_* is needed, this way I can have test cases for them.

**Comment by micheleCTDE** [comment]
PR #4026 merged. 
@unity-emilk please check with latest code and close the issue of ok.

> I don't have test cases for all of them, but the following ones (and perhaps more) seem like they should be handled?

some of the CT_* here have been added, some not yet. Will add them in future as I run a test on a big repo

**Comment by unity-emilk** [comment]
Thanks, feel free to ping me here if you need help with test fixtures.

**Comment by micheleCTDE** [comment]
Ok to close this issue @unity-emilk ?

**Comment by unity-emilk** [comment]
Sure, but I'm interested in following up on the other CT_* types that I mentioned, since it breaks my project. Like I said I can try to mock up example files for it.

**Comment by micheleCTDE** [comment]
I can make some example on my own but some others I don't have any. So if you can provide examples for the missing ones, I will add the fix and the test in the code.

**Comment by micheleCTDE** [comment]
I have added a few more CT_* to the code in PR #4031. If you run into other missing cases, please let us know.
