### ISSUE TITLE
Weird C macro modification (spaces added to macro value)

### ISSUE THREAD

**Issue by egrandem** [uncrustify/uncrustify#4027]
Uncrustify 0.77.1 is adding spaces in the middle of some macro values:

test.h:
`#define KK1 2C300000`
`#define KK2 2F300000`

uncrustify.cfg
`[empty]`

uncrustify -c uncrustify.cfg -f test.h
`#define KK1 2C300000`
`#define KK2 2F 300000`

**Comment by gmaurel** [comment]
I confirm

**Comment by guy-maurel** [comment]
PR #4084 is a bug fix proposal.
Please test it and report.

**Comment by egrandem** [comment]
I have just seen the PR proposal, sorry for the delay.
Thank you for the fix!
