### ISSUE TITLE
Spaces are inserted in each run

### ISSUE THREAD

**Issue by nicodecker** [uncrustify/uncrustify#403]
The following code is spaced differently with each run:

     int        test[ 1 ][ 1 ] = {
      { 12, 2    },
      { 1,  21   }
     };

The reason seems to be the two inverting lengths of the items.

Here is the configuration I used:

    newlines                                  = auto     # auto/lf/crlf/cr
    input_tab_size                            = 8        # number
    output_tab_size                           = 8        # number
    string_escape_char                        = 92       # number
    string_escape_char2                       = 0        # number
    tok_split_gte                             = false    # false/true
    utf8_bom                                  = ignore   # ignore/add/remove/force
    utf8_byte                                 = false    # false/true
    utf8_force                                = false    # false/true
    indent_columns                            = 1        # number
    indent_continue                           = 0        # number
    indent_with_tabs                          = 0        # number
    indent_cmt_with_tabs                      = false    # false/true
    indent_align_string                       = false    # false/true
    indent_xml_string                         = 0        # number
    indent_brace                              = 0        # number
    indent_braces                             = false    # false/true
    indent_braces_no_func                     = false    # false/true
    indent_braces_no_class                    = false    # false/true
    indent_braces_no_struct                   = false    # false/true
    indent_brace_parent                       = false    # false/true
    indent_paren_open_brace                   = false    # false/true
    indent_namespace                          = true    # false/true
    indent_namespace_single_indent            = false    # false/true
    indent_namespace_level                    = 1        # number
    indent_namespace_limit                    = 0        # number
    indent_extern                             = true    # false/true
    indent_class                              = true    # false/true
    indent_class_colon                        = true    # false/true
    indent_constr_colon                       = true    # false/true
    indent_ctor_init_leading                  = 2        # number
    indent_ctor_init                          = 0        # number
    indent_else_if                            = false    # false/true
    indent_var_def_blk                        = 0        # number
    indent_var_def_cont                       = false    # false/true
    indent_func_def_force_col1                = false    # false/true
    indent_func_call_param                    = false    # false/true
    indent_func_def_param                     = false    # false/true
    indent_func_proto_param                   = false    # false/true
    indent_func_class_param                   = false    # false/true
    indent_func_ctor_var_param                = false    # false/true
    indent_template_param                     = false    # false/true
    indent_func_param_double                  = false    # false/true
    indent_func_const                         = 0        # number
    indent_func_throw                         = 0        # number
    indent_member                             = 0        # number
    indent_sing_line_comments                 = 0        # number
    indent_relative_single_line_comments      = false    # false/true
    indent_switch_case                        = 5        # number
    indent_case_shift                         = -4        # number
    indent_case_brace                         = 1        # number
    indent_col1_comment                       = false    # false/true
    indent_label                              = 1        # number
    indent_access_spec                        = 0        # number
    indent_access_spec_body                   = true    # false/true
    indent_paren_nl                           = true    # false/true
    indent_paren_close                        = 1        # number
    indent_comma_paren                        = false    # false/true
    indent_bool_paren                         = false    # false/true
    indent_first_bool_expr                    = false    # false/true
    indent_square_nl                          = false    # false/true
    indent_preserve_sql                       = false    # false/true
    indent_align_assign                       = true     # false/true
    indent_oc_block                           = false    # false/true
    indent_oc_block_msg                       = 0        # number
    indent_oc_msg_colon                       = 0        # number
    indent_oc_msg_prioritize_first_colon      = true     # false/true
    indent_oc_block_msg_xcode_style           = false    # false/true
    indent_oc_block_msg_from_keyword          = false    # false/true
    indent_oc_block_msg_from_colon            = false    # false/true
    indent_oc_block_msg_from_caret            = false    # false/true
    indent_oc_block_msg_from_brace            = false    # false/true
    indent_min_vbrace_open                    = 2
    indent_vbrace_open_on_tabstop             = true
    sp_arith                                  = add   # ignore/add/remove/force
    sp_assign                                 = force   # ignore/add/remove/force
    sp_cpp_lambda_assign                      = add   # ignore/add/remove/force
    sp_cpp_lambda_paren                       = add   # ignore/add/remove/force
    sp_assign_default                         = force   # ignore/add/remove/force
    sp_before_assign                          = ignore   # ignore/add/remove/force
    sp_after_assign                           = ignore   # ignore/add/remove/force
    sp_enum_paren                             = ignore   # ignore/add/remove/force
    sp_enum_assign                            = add   # ignore/add/remove/force
    sp_enum_before_assign                     = ignore   # ignore/add/remove/force
    sp_enum_after_assign                      = ignore   # ignore/add/remove/force
    sp_pp_concat                              = force      # ignore/add/remove/force
    sp_pp_stringify                           = remove   # ignore/add/remove/force
    sp_before_pp_stringify                    = force   # ignore/add/remove/force
    sp_bool                                   = force   # ignore/add/remove/force
    sp_compare                                = ignore   # ignore/add/remove/force
    sp_inside_paren                           = force   # ignore/add/remove/force
    sp_paren_paren                            = ignore   # ignore/add/remove/force
    sp_cparen_oparen                          = remove   # ignore/add/remove/force
    sp_balance_nested_parens                  = false    # false/true
    sp_paren_brace                            = add   # ignore/add/remove/force
    sp_before_ptr_star                        = add   # ignore/add/remove/force
    sp_before_unnamed_ptr_star                = ignore   # ignore/add/remove/force
    sp_between_ptr_star                       = remove   # ignore/add/remove/force
    sp_after_ptr_star                         = remove   # ignore/add/remove/force
    sp_after_ptr_star_qualifier               = remove   # ignore/add/remove/force
    sp_after_ptr_star_func                    = remove   # ignore/add/remove/force
    sp_ptr_star_paren                         = remove   # ignore/add/remove/force
    sp_before_ptr_star_func                   = add   # ignore/add/remove/force
    sp_before_byref                           = add   # ignore/add/remove/force
    sp_before_unnamed_byref                   = ignore   # ignore/add/remove/force
    sp_after_byref                            = remove   # ignore/add/remove/force
    sp_after_byref_func                       = remove   # ignore/add/remove/force
    sp_before_byref_func                      = remove   # ignore/add/remove/force
    sp_after_type                             = add    # ignore/add/remove/force
    sp_before_template_paren                  = add   # ignore/add/remove/force
    sp_template_angle                         = add   # ignore/add/remove/force
    sp_before_angle                           = remove   # ignore/add/remove/force
    sp_inside_angle                           = remove   # ignore/add/remove/force
    sp_after_angle                            = add   # ignore/add/remove/force
    sp_angle_paren                            = remove   # ignore/add/remove/force
    sp_angle_word                             = add   # ignore/add/remove/force
    sp_angle_shift                            = add      # ignore/add/remove/force
    sp_permit_cpp11_shift                     = false    # false/true
    sp_before_sparen                          = add   # ignore/add/remove/force
    sp_inside_sparen                          = add   # ignore/add/remove/force
    sp_inside_sparen_close                    = ignore   # ignore/add/remove/force
    sp_inside_sparen_open                     = ignore   # ignore/add/remove/force
    sp_after_sparen                           = add   # ignore/add/remove/force
    sp_sparen_brace                           = add   # ignore/add/remove/force
    sp_invariant_paren                        = ignore   # ignore/add/remove/force
    sp_after_invariant_paren                  = ignore   # ignore/add/remove/force
    sp_special_semi                           = add   # ignore/add/remove/force
    sp_before_semi                            = remove   # ignore/add/remove/force
    sp_before_semi_for                        = add   # ignore/add/remove/force
    sp_before_semi_for_empty                  = remove   # ignore/add/remove/force
    sp_after_semi                             = add      # ignore/add/remove/force
    sp_after_semi_for                         = force    # ignore/add/remove/force
    sp_after_semi_for_empty                   = remove   # ignore/add/remove/force
    sp_before_square                          = remove   # ignore/add/remove/force
    sp_before_squares                         = remove   # ignore/add/remove/force
    sp_inside_square                          = add   # ignore/add/remove/force
    sp_after_comma                            = add   # ignore/add/remove/force
    sp_before_comma                           = remove   # ignore/add/remove/force
    sp_paren_comma                            = force    # ignore/add/remove/force
    sp_before_ellipsis                        = add   # ignore/add/remove/force
    sp_after_class_colon                      = add   # ignore/add/remove/force
    sp_before_class_colon                     = add   # ignore/add/remove/force
    sp_after_constr_colon                     = add   # ignore/add/remove/force
    sp_before_constr_colon                    = add   # ignore/add/remove/force
    sp_before_case_colon                      = remove   # ignore/add/remove/force
    sp_after_operator                         = remove   # ignore/add/remove/force
    sp_after_operator_sym                     = remove   # ignore/add/remove/force
    sp_after_cast                             = remove   # ignore/add/remove/force
    sp_inside_paren_cast                      = remove   # ignore/add/remove/force
    sp_cpp_cast_paren                         = remove   # ignore/add/remove/force
    sp_sizeof_paren                           = remove   # ignore/add/remove/force
    sp_after_tag                              = ignore   # ignore/add/remove/force
    sp_inside_braces_enum                     = add   # ignore/add/remove/force
    sp_inside_braces_struct                   = add   # ignore/add/remove/force
    sp_inside_braces                          = add   # ignore/add/remove/force
    sp_inside_braces_empty                    = remove   # ignore/add/remove/force
    sp_type_func                              = add   # ignore/add/remove/force
    sp_func_proto_paren                       = remove   # ignore/add/remove/force
    sp_func_def_paren                         = remove   # ignore/add/remove/force
    sp_inside_fparens                         = remove   # ignore/add/remove/force
    sp_inside_fparen                          = add   # ignore/add/remove/force
    sp_inside_tparen                          = remove   # ignore/add/remove/force
    sp_after_tparen_close                     = remove   # ignore/add/remove/force
    sp_square_fparen                          = remove   # ignore/add/remove/force
    sp_fparen_brace                           = add   # ignore/add/remove/force
    sp_fparen_dbrace                          = ignore   # ignore/add/remove/force
    sp_func_call_paren                        = remove   # ignore/add/remove/force
    sp_func_call_paren_empty                  = ignore   # ignore/add/remove/force
    sp_func_call_user_paren                   = ignore   # ignore/add/remove/force
    sp_func_class_paren                       = remove   # ignore/add/remove/force
    sp_return_paren                           = add   # ignore/add/remove/force
    sp_attribute_paren                        = add   # ignore/add/remove/force
    sp_defined_paren                          = add   # ignore/add/remove/force
    sp_throw_paren                            = add   # ignore/add/remove/force
    sp_after_throw                            = add   # ignore/add/remove/force
    sp_catch_paren                            = add   # ignore/add/remove/force
    sp_version_paren                          = ignore   # ignore/add/remove/force
    sp_scope_paren                            = ignore   # ignore/add/remove/force
    sp_macro                                  = add   # ignore/add/remove/force
    sp_macro_func                             = add   # ignore/add/remove/force
    sp_else_brace                             = add   # ignore/add/remove/force
    sp_brace_else                             = add   # ignore/add/remove/force
    sp_brace_typedef                          = add   # ignore/add/remove/force
    sp_catch_brace                            = add   # ignore/add/remove/force
    sp_brace_catch                            = add   # ignore/add/remove/force
    sp_finally_brace                          = add   # ignore/add/remove/force
    sp_brace_finally                          = add   # ignore/add/remove/force
    sp_try_brace                              = add   # ignore/add/remove/force
    sp_getset_brace                           = add   # ignore/add/remove/force
    sp_word_brace                             = add      # ignore/add/remove/force
    sp_word_brace_ns                          = add      # ignore/add/remove/force
    sp_before_dc                              = remove   # ignore/add/remove/force
    sp_after_dc                               = remove   # ignore/add/remove/force
    sp_d_array_colon                          = ignore   # ignore/add/remove/force
    sp_not                                    = remove   # ignore/add/remove/force
    sp_inv                                    = remove   # ignore/add/remove/force
    sp_addr                                   = remove   # ignore/add/remove/force
    sp_member                                 = remove   # ignore/add/remove/force
    sp_deref                                  = remove   # ignore/add/remove/force
    sp_sign                                   = remove   # ignore/add/remove/force
    sp_incdec                                 = remove   # ignore/add/remove/force
    sp_before_nl_cont                         = add      # ignore/add/remove/force
    sp_after_oc_scope                         = add   # ignore/add/remove/force
    sp_after_oc_colon                         = add   # ignore/add/remove/force
    sp_before_oc_colon                        = ignore   # ignore/add/remove/force
    sp_after_oc_dict_colon                    = ignore   # ignore/add/remove/force
    sp_before_oc_dict_colon                   = ignore   # ignore/add/remove/force
    sp_after_send_oc_colon                    = ignore   # ignore/add/remove/force
    sp_before_send_oc_colon                   = ignore   # ignore/add/remove/force
    sp_after_oc_type                          = ignore   # ignore/add/remove/force
    sp_after_oc_return_type                   = ignore   # ignore/add/remove/force
    sp_after_oc_at_sel                        = ignore   # ignore/add/remove/force
    sp_after_oc_at_sel_parens                 = ignore   # ignore/add/remove/force
    sp_inside_oc_at_sel_parens                = ignore   # ignore/add/remove/force
    sp_before_oc_block_caret                  = ignore   # ignore/add/remove/force
    sp_after_oc_block_caret                   = ignore   # ignore/add/remove/force
    sp_after_oc_msg_receiver                  = ignore   # ignore/add/remove/force
    sp_after_oc_property                      = ignore   # ignore/add/remove/force
    sp_cond_colon                             = add   # ignore/add/remove/force
    sp_cond_colon_before                      = ignore   # ignore/add/remove/force
    sp_cond_colon_after                       = ignore   # ignore/add/remove/force
    sp_cond_question                          = add   # ignore/add/remove/force
    sp_cond_question_before                   = ignore   # ignore/add/remove/force
    sp_cond_question_after                    = ignore   # ignore/add/remove/force
    sp_cond_ternary_short                     = ignore   # ignore/add/remove/force
    sp_case_label                             = force   # ignore/add/remove/force
    sp_range                                  = ignore   # ignore/add/remove/force
    sp_after_for_colon                        = ignore   # ignore/add/remove/force
    sp_before_for_colon                       = ignore   # ignore/add/remove/force
    sp_extern_paren                           = ignore   # ignore/add/remove/force
    sp_cmt_cpp_start                          = add   # ignore/add/remove/force
    sp_cmt_cpp_doxygen                        = true    # false/true
    sp_endif_cmt                              = add   # ignore/add/remove/force
    sp_after_new                              = add   # ignore/add/remove/force
    sp_before_tr_emb_cmt                      = add   # ignore/add/remove/force
    sp_num_before_tr_emb_cmt                  = 0        # number
    sp_annotation_paren                       = ignore   # ignore/add/remove/force
    align_keep_tabs                           = false    # false/true
    align_with_tabs                           = false    # false/true
    align_on_tabstop                          = true    # false/true
    align_number_left                         = false    # false/true
    align_keep_extra_space                    = false    # false/true
    align_func_params                         = true    # false/true
    align_same_func_call_params               = false    # false/true
    align_var_def_span                        = 100      # number
    align_var_def_star_style                  = 1        # number
    align_var_def_amp_style                   = 1        # number
    align_var_def_thresh                      = 0        # number
    align_var_def_gap                         = 8        # number
    align_var_def_colon                       = false    # false/true
    align_var_def_attribute                   = false    # false/true
    align_var_def_inline                      = true    # false/true
    align_assign_span                         = 8        # number
    align_assign_thresh                       = 0        # number
    align_enum_equ_span                       = 100      # number
    align_enum_equ_thresh                     = 0        # number
    align_var_struct_span                     = 100      # number
    align_var_struct_thresh                   = 0        # number
    align_var_struct_gap                      = 8        # number
    align_struct_init_span                    = 100      # number
    align_typedef_gap                         = 8        # number
    align_typedef_span                        = 100      # number
    align_typedef_func                        = 0        # number
    align_typedef_star_style                  = 1        # number
    align_typedef_amp_style                   = 1        # number
    align_right_cmt_span                      = 16        # number
    align_right_cmt_mix                       = true    # false/true
    align_right_cmt_gap                       = 0        # number
    align_right_cmt_at_col                    = 64        # number
    align_func_proto_span                     = 50        # number
    align_func_proto_gap                      = 0        # number
    align_on_operator                         = true    # false/true
    align_mix_var_proto                       = false    # false/true
    align_single_line_func                    = true    # false/true
    align_single_line_brace                   = false    # false/true
    align_single_line_brace_gap               = 0        # number
    align_oc_msg_spec_span                    = 0        # number
    align_nl_cont                             = true    # false/true
    align_pp_define_together                  = false    # false/true
    align_pp_define_gap                       = 1        # number
    align_pp_define_span                      = 8        # number
    align_left_shift                          = true     # false/true
    align_oc_msg_colon_span                   = 0        # number
    align_oc_msg_colon_first                  = false    # false/true
    align_oc_decl_colon                       = false    # false/true
    nl_collapse_empty_body                    = true    # false/true
    nl_assign_leave_one_liners                = false    # false/true
    nl_class_leave_one_liners                 = false    # false/true
    nl_enum_leave_one_liners                  = false    # false/true
    nl_getset_leave_one_liners                = false    # false/true
    nl_func_leave_one_liners                  = false    # false/true
    nl_cpp_lambda_leave_one_liners            = false    # false/true
    nl_if_leave_one_liners                    = false    # false/true
    nl_oc_msg_leave_one_liner                 = false    # false/true
    nl_start_of_file                          = remove   # ignore/add/remove/force
    nl_start_of_file_min                      = 0        # number
    nl_end_of_file                            = add   # ignore/add/remove/force
    nl_end_of_file_min                        = 2        # number
    nl_assign_brace                           = ignore   # ignore/add/remove/force
    nl_assign_square                          = ignore   # ignore/add/remove/force
    nl_after_square_assign                    = ignore   # ignore/add/remove/force
    nl_func_var_def_blk                       = 1        # number
    nl_typedef_blk_start                      = 0        # number
    nl_typedef_blk_end                        = 0        # number
    nl_typedef_blk_in                         = 0        # number
    nl_var_def_blk_start                      = 0        # number
    nl_var_def_blk_end                        = 0        # number
    nl_var_def_blk_in                         = 2        # number
    nl_fcall_brace                            = force   # ignore/add/remove/force
    nl_enum_brace                             = remove  # ignore/add/remove/force
    nl_struct_brace                           = remove   # ignore/add/remove/force
    nl_union_brace                            = remove   # ignore/add/remove/force
    nl_if_brace                               = remove   # ignore/add/remove/force
    nl_brace_else                             = add   # ignore/add/remove/force
    nl_elseif_brace                           = remove   # ignore/add/remove/force
    nl_else_brace                             = remove   # ignore/add/remove/force
    nl_else_if                                = remove   # ignore/add/remove/force
    nl_brace_finally                          = force   # ignore/add/remove/force
    nl_finally_brace                          = remove   # ignore/add/remove/force
    nl_try_brace                              = remove   # ignore/add/remove/force
    nl_getset_brace                           = remove   # ignore/add/remove/force
    nl_for_brace                              = remove   # ignore/add/remove/force
    nl_catch_brace                            = remove   # ignore/add/remove/force
    nl_brace_catch                            = force   # ignore/add/remove/force
    nl_brace_square                           = ignore   # ignore/add/remove/force
    nl_brace_fparen                           = ignore   # ignore/add/remove/force
    nl_while_brace                            = remove   # ignore/add/remove/force
    nl_scope_brace                            = ignore   # ignore/add/remove/force
    nl_unittest_brace                         = ignore   # ignore/add/remove/force
    nl_version_brace                          = ignore   # ignore/add/remove/force
    nl_using_brace                            = remove   # ignore/add/remove/force
    nl_brace_brace                            = force   # ignore/add/remove/force
    nl_do_brace                               = remove   # ignore/add/remove/force
    nl_brace_while                            = remove   # ignore/add/remove/force
    nl_switch_brace                           = remove   # ignore/add/remove/force
    nl_multi_line_cond                        = true    # false/true
    nl_multi_line_define                      = true    # false/true
    nl_before_case                            = false    # false/true
    nl_before_throw                           = remove   # ignore/add/remove/force
    nl_after_case                             = false    # false/true
    nl_case_colon_brace                       = force   # ignore/add/remove/force
    nl_namespace_brace                        = remove   # ignore/add/remove/force
    nl_template_class                         = force   # ignore/add/remove/force
    nl_class_brace                            = remove   # ignore/add/remove/force
    nl_class_init_args                        = ignore   # ignore/add/remove/force
    nl_constr_init_args                       = ignore   # ignore/add/remove/force
    nl_func_type_name                         = ignore   # ignore/add/remove/force
    nl_func_type_name_class                   = ignore   # ignore/add/remove/force
    nl_func_scope_name                        = ignore   # ignore/add/remove/force
    nl_func_proto_type_name                   = ignore   # ignore/add/remove/force
    nl_func_paren                             = remove   # ignore/add/remove/force
    nl_func_def_paren                         = remove   # ignore/add/remove/force
    nl_func_decl_start                        = ignore   # ignore/add/remove/force
    nl_func_def_start                         = ignore   # ignore/add/remove/force
    nl_func_decl_start_single                 = remove   # ignore/add/remove/force
    nl_func_def_start_single                  = remove   # ignore/add/remove/force
    nl_func_decl_args                         = ignore   # ignore/add/remove/force
    nl_func_def_args                          = ignore   # ignore/add/remove/force
    nl_func_decl_end                          = ignore   # ignore/add/remove/force
    nl_func_def_end                           = ignore   # ignore/add/remove/force
    nl_func_decl_end_single                   = remove   # ignore/add/remove/force
    nl_func_def_end_single                    = remove   # ignore/add/remove/force
    nl_func_decl_empty                        = remove   # ignore/add/remove/force
    nl_func_def_empty                         = remove   # ignore/add/remove/force
    nl_oc_msg_args                            = false    # false/true
    nl_fdef_brace                             = force   # ignore/add/remove/force
    nl_cpp_ldef_brace                         = ignore   # ignore/add/remove/force
    nl_return_expr                            = remove # ignore/add/remove/force
    nl_after_semicolon                        = false    # false/true
    nl_paren_dbrace_open                      = ignore   # ignore/add/remove/force
    nl_after_brace_open                       = false    # false/true
    nl_after_brace_open_cmt                   = false    # false/true
    nl_after_vbrace_open                      = false    # false/true
    nl_after_vbrace_open_empty                = false    # false/true
    nl_after_brace_close                      = false    # false/true
    nl_after_vbrace_close                     = false    # false/true
    nl_brace_struct_var                       = remove   # ignore/add/remove/force
    nl_define_macro                           = true    # false/true
    nl_squeeze_ifdef                          = false    # false/true
    nl_before_if                              = ignore   # ignore/add/remove/force
    nl_after_if                               = ignore   # ignore/add/remove/force
    nl_before_for                             = ignore   # ignore/add/remove/force
    nl_after_for                              = ignore   # ignore/add/remove/force
    nl_before_while                           = ignore   # ignore/add/remove/force
    nl_after_while                            = ignore   # ignore/add/remove/force
    nl_before_switch                          = ignore   # ignore/add/remove/force
    nl_after_switch                           = ignore   # ignore/add/remove/force
    nl_before_do                              = ignore   # ignore/add/remove/force
    nl_after_do                               = ignore   # ignore/add/remove/force
    nl_ds_struct_enum_cmt                     = false    # false/true
    nl_ds_struct_enum_close_brace             = false    # false/true
    nl_class_colon                            = ignore   # ignore/add/remove/force
    nl_constr_colon                           = ignore   # ignore/add/remove/force
    nl_create_if_one_liner                    = false    # false/true
    nl_create_for_one_liner                   = false    # false/true
    nl_create_while_one_liner                 = false    # false/true
    pos_arith                                 = ignore   # ignore/join/lead/lead_break/lead_force/trail/trail_break/trail_force
    pos_assign                                = ignore   # ignore/join/lead/lead_break/lead_force/trail/trail_break/trail_force
    pos_bool                                  = ignore   # ignore/join/lead/lead_break/lead_force/trail/trail_break/trail_force
    pos_compare                               = ignore   # ignore/join/lead/lead_break/lead_force/trail/trail_break/trail_force
    pos_conditional                           = ignore   # ignore/join/lead/lead_break/lead_force/trail/trail_break/trail_force
    pos_comma                                 = ignore   # ignore/join/lead/lead_break/lead_force/trail/trail_break/trail_force
    pos_class_comma                           = ignore   # ignore/join/lead/lead_break/lead_force/trail/trail_break/trail_force
    pos_constr_comma                          = ignore   # ignore/join/lead/lead_break/lead_force/trail/trail_break/trail_force
    pos_class_colon                           = ignore   # ignore/join/lead/lead_break/lead_force/trail/trail_break/trail_force
    pos_constr_colon                          = ignore   # ignore/join/lead/lead_break/lead_force/trail/trail_break/trail_force
    code_width                                = 140        # number
    ls_for_split_full                         = true    # false/true
    ls_func_split_full                        = true    # false/true
    ls_code_width                             = true    # false/true
    nl_max                                    = 6        # number
    nl_after_func_proto                       = 0        # number
    nl_after_func_proto_group                 = 0        # number
    nl_after_func_body                        = 0        # number
    nl_after_func_body_class                  = 0        # number
    nl_after_func_body_one_liner              = 0        # number
    nl_before_block_comment                   = 0        # number
    nl_before_c_comment                       = 0        # number
    nl_before_cpp_comment                     = 0        # number
    nl_after_multiline_comment                = false    # false/true
    nl_after_struct                           = 0        # number
    nl_after_class                            = 0        # number
    nl_before_access_spec                     = 1        # number
    nl_after_access_spec                      = 0        # number
    nl_comment_func_def                       = 0        # number
    nl_after_try_catch_finally                = 0        # number
    nl_around_cs_property                     = 0        # number
    nl_between_get_set                        = 0        # number
    nl_property_brace                         = ignore   # ignore/add/remove/force
    eat_blanks_after_open_brace               = false    # false/true
    eat_blanks_before_close_brace             = false    # false/true
    nl_remove_extra_newlines                  = 0        # number
    nl_before_return                          = false    # false/true
    nl_after_return                           = false    # false/true
    nl_after_annotation                       = ignore   # ignore/add/remove/force
    nl_between_annotation                     = ignore   # ignore/add/remove/force
    mod_full_brace_do                         = ignore   # ignore/add/remove/force
    mod_full_brace_for                        = ignore   # ignore/add/remove/force
    mod_full_brace_function                   = ignore   # ignore/add/remove/force
    mod_full_brace_if                         = ignore   # ignore/add/remove/force
    mod_full_brace_if_chain                   = false    # false/true
    mod_full_brace_nl                         = 0        # number
    mod_full_brace_while                      = ignore   # ignore/add/remove/force
    mod_full_brace_using                      = ignore   # ignore/add/remove/force
    mod_paren_on_return                       = ignore   # ignore/add/remove/force
    mod_pawn_semicolon                        = false    # false/true
    mod_full_paren_if_bool                    = false    # false/true
    mod_remove_extra_semicolon                = false    # false/true
    mod_add_long_function_closebrace_comment  = 0        # number
    mod_add_long_namespace_closebrace_comment = 0        # number
    mod_add_long_switch_closebrace_comment    = 0        # number
    mod_add_long_ifdef_endif_comment          = 0        # number
    mod_add_long_ifdef_else_comment           = 0        # number
    mod_sort_import                           = false    # false/true
    mod_sort_using                            = false    # false/true
    mod_sort_include                          = false    # false/true
    mod_move_case_break                       = false    # false/true
    mod_case_brace                            = ignore   # ignore/add/remove/force
    mod_remove_empty_return                   = false    # false/true
    cmt_width                                 = 0        # number
    cmt_reflow_mode                           = 0        # number
    cmt_convert_tab_to_spaces                 = true    # false/true
    cmt_indent_multi                          = true     # false/true
    cmt_c_group                               = false    # false/true
    cmt_c_nl_start                            = false    # false/true
    cmt_c_nl_end                              = false    # false/true
    cmt_cpp_group                             = false    # false/true
    cmt_cpp_nl_start                          = false    # false/true
    cmt_cpp_nl_end                            = false    # false/true
    cmt_cpp_to_c                              = false    # false/true
    cmt_star_cont                             = false    # false/true
    cmt_sp_before_star_cont                   = 0        # number
    cmt_sp_after_star_cont                    = 0        # number
    cmt_multi_check_last                      = true     # false/true
    cmt_insert_file_header                    = ""         # string
    cmt_insert_file_footer                    = ""         # string
    cmt_insert_func_header                    = ""         # string
    cmt_insert_class_header                   = ""         # string
    cmt_insert_oc_msg_header                  = ""         # string
    cmt_insert_before_preproc                 = false    # false/true
    pp_indent                                 = force   # ignore/add/remove/force
    pp_indent_at_level                        = false    # false/true
    pp_indent_count                           = 1        # number
    pp_space                                  = ignore   # ignore/add/remove/force
    pp_space_count                            = 0        # number
    pp_indent_region                          = 0        # number
    pp_region_indent_code                     = false    # false/true
    pp_indent_if                              = 0        # number
    pp_if_indent_code                         = false    # false/true
    pp_define_at_level                        = false    # false/true

**Comment by gmaurel** [comment]
With the actual git version
Please use the options:
  sp_inside_braces  = force
  align_var_def_gap = 0
  sp_after_type     = force
to get what you wanted to have:
int test[ 1 ][ 1 ] = {
 { 12, 2 },
 { 1,  21 }
};

**Comment by nicodecker** [comment]
Thanks, @gmaurel. I'll check it as soon as I am able to.
