### ISSUE TITLE
Space before bitfield colon always added

### ISSUE THREAD

**Issue by mid-kid** [uncrustify/uncrustify#4036]
The configuration is left default.

Original file:
```c
struct a {
    bool b: 1;
};
```

Output file:
```c
struct a {
    bool b : 1;
};
```

I don't want this space before the colon to be added, but it's currently always added, due to:
```
           second orig line is 2, orig col is 11, Text() is ':', [BIT_COLON/NONE] : rule ADD from add_space_table[line 3183]
```

add_space_table should be updated to not always add spaces before or after a BIT_COLON.

**Comment by guy-maurel** [comment]
yes, it comes soon

**Comment by gmaurel** [comment]
#4040 must been solved before me can go on.

**Comment by guy-maurel** [comment]
PR #4054 is a bug fix proposal.
Please test it and report.
