### ISSUE TITLE
union constructor - fatal error

### ISSUE THREAD

**Issue by sonk33** [uncrustify/uncrustify#4042]
when add '**noexcept**( expression )' to **union constructor** , uncrustify exited with status: 70
code that trigger the problem.

```
   union Data {
      int val1;
      long val2;
      Data( ) noexcept(false )
         : val1( 1 ) { }
   };
```
the logger print : 
'stdin:5 unexpected colon in col 10 n-parent=NONE c-parent=NONE l=1 bl=1 Debug: uncrustify exited with status: 70'

if we convert : noexcept(fasle) to noexcept - the problem go away
//-----------------------
i use **default** configuration
my OS is : **Debian**
my editor : **vscode**
the problem was in version 0.72 - i downloaded it through apt 
and i **clone** the project and **build it** -- on the date **6/21/2023**
and The  **problem still exists**.

**Comment by guy-maurel** [comment]
I can reproduce

**Comment by guy-maurel** [comment]
PR #4057 is a bug fix proposal.
Please test it and report.
