### ISSUE TITLE
C++ keywords recognized in C

### ISSUE THREAD

**Issue by gilles-peskine-arm** [uncrustify/uncrustify#4044]
The C++ keywords `private`, `protected` and `public` are recognized as keywords in C, which sometimes leads to weird spacing (and possibly other symptoms, I haven't investigated further). Specifically, the example I encountered is:
```
    f(1, normal->x);
    f(1, private ->x); // <--- uncrustify added a space after private
```

Observed with 0.75.1 as well as 970fef45708d78535f89ccf8ba9ed4b0b38bf7a2.

Full reproducer (input `good.c` which checks all the words that are official keywords in some version of C++ but in no version of C, minimalist configuration, actual output and debug file):
[report.zip](https://github.com/uncrustify/uncrustify/files/11837941/report.zip)

**Comment by guy-maurel** [comment]
Thanks for the message

**Comment by guy-maurel** [comment]
PR #4049 is a bug fix proposal.
Please test it and report.
