### ISSUE TITLE
template argument alignment behaviour

### ISSUE THREAD

**Issue by Ulfgard** [uncrustify/uncrustify#405]
I am trying to indent template arguments in the following way:
```C++
namespace shark {
	template<class Closure>
	struct indexed_iterator{
		typedef typename boost::mpl::if_<
			boost::is_const<
				Closure
			>,
			typename Closure::const_reference,
			typename Closure::reference
		>::type reference;
	};
}
```
Given an input file of this form, indenting with a config
indent_with_tabs=2
gives
```C++
namespace shark {
template<class Closure>
struct indexed_iterator {
typedef typename boost::mpl::if_<
                boost::is_const<
                        Closure
                        >,
                typename Closure::const_reference,
                typename Closure::reference
                >::type reference;
};
}
```
so most of the template formatting is treated as alignment, including the indentation of class and namespace - and the closing parenthesis are aligned with the previous line. So there is a weird mixture of "treat as alignment" and "treat as indentation" in place.

now I add indentation to namespace and class level
indent_columns                           = 8
indent_namespace = true
indent_class = true
```C++
namespace shark {
	template<class Closure>
	struct indexed_iterator {
		typedef typename boost::mpl::if_<
		                boost::is_const<
		                        Closure
		                        >,
		                typename Closure::const_reference,
		                typename Closure::reference
		                >::type reference;
	};
}
```
which just moves the aligned part further right. But the real odd part is when I finally add

indent_paren_close                       = 2

which then yields
```C++
namespace shark {
	template<class Closure>
	struct indexed_iterator {
		typedef typename boost::mpl::if_<
		                boost::is_const<
		                        Closure
		                >,//aligned as I want it to be
		                typename Closure::const_reference,
		                typename Closure::reference
>::type reference;//???
	};
}
```

what is going on here? Is what I want possible at all? Is here some weird bug at play?

**Comment by gmaurel** [comment]
In the file indent.cpp for pc->type == CT_TYPEDEF at
      else if ((pc->type == CT_OC_SCOPE) || (pc->type == CT_TYPEDEF))
      {
         indent_pse_push(frm, pc);

the frame must be completed with:
         // Issue # 405
         frm.pse[frm.pse_tos].indent     = frm.pse[frm.pse_tos - 1].indent;
         frm.pse[frm.pse_tos].indent_tmp = frm.pse[frm.pse_tos].indent;

Both "typedef" and the "ANGLE_OPEN" work as intender. The indentation is double.
   typedef typename boost::mpl::if_<

Please try it at git bb263db..a094c39
