### ISSUE TITLE
Do not add a space before and/or after a single quote in numbers

### ISSUE THREAD

**Issue by StarFire75** [uncrustify/uncrustify#4053]
Hello World,

I have the following C++ statement:

`constexpr int FOO = 123'456;`

After the formatting I get

`constexpr int FOO = 123 '456;` (note the space after 123)

I have not found any option to avoid this, and it is not only unfortunate, but the code is no longer compiling! I think a single quote within digits should not be spaced at all!

Best regards - Andreas

**Comment by guy-maurel** [comment]
which version/OS do you are using?
The current git version works pretty fine under Linux Mint.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by StarFire75** [comment]
Sorry, my bad.
We used a very old version of uncrustify (0.63.0), now I've updated to 0.77.1 and the bug is fixed.

Sorry for the noise!
