### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by atsju** [uncrustify/uncrustify#4058]
I followed command as described in readme.md on this repo and get "failed to load". Doesn't it support `*.something` format or  am i doing something wrong ?

running on win10 64

>uncrustify0.77.1.exe -c uncrustify.cfg --no-backup \*.cpp
Failed to load (*.cpp)

>uncrustify0.77.1.exe -v
Uncrustify-0.77.1

**Comment by gmaurel** [comment]
Please use (first)
`uncrustify0.77.1.exe -c uncrustify.cfg -f yourfile.cpp`

**Comment by atsju** [comment]
This works. It's the *.cpp that does not

**Comment by micheleCTDE** [comment]
> uncrustify0.77.1.exe -c uncrustify.cfg --no-backup .cpp

You didn't specify the file to load (`*.cpp` is not a valid way), hence you have the error reported. @gmaurel already explained the right syntax to use. You will need a small script to call uncrustify for each file you want to parse.
I don't see anything wrong, so IMO this issue is invalid and shoud be closed.

**Comment by atsju** [comment]
> > uncrustify0.77.1.exe -c uncrustify.cfg --no-backup .cpp
> 
> You didn't specify the file to load (`*.cpp` is not a valid way), hence you have the error reported. @gmaurel already explained the right syntax to use. You will need a small script to call uncrustify for each file you want to parse. I don't see anything wrong, so IMO this issue is invalid and shoud be closed.

If `*.cpp` is not a valid way, then why is it in documentation ? Please close this issue only once documentation is fixed !

https://github.com/uncrustify/uncrustify/blob/master/README.md#running-the-program

By the way, I see I needed to escape the * in initial comment. I eddited

**Comment by micheleCTDE** [comment]
> If *.cpp is not a valid way, then why is it in documentation ? 

actually, it is! I never knew that, by bad. I always thought we need a script for it.
I just tried out a simple `*.cpp` as parameter and it works fine in my linux box
Sorry for the confusion in my previous comment, learnt something new today :-)

When you tried in your windows box, the cpp files where in the same folder or where they in subfolders?

**Comment by JamesBloomScheff2** [comment]
I have the same problem. Specifying an individual file works. Specifying *.h or *.cc does not. 
`E:\Program Files\uncrustify\uncrustify\bin>uncrustify -c options.cfg cSI_project_tree.cc
Output suffix: .uncrustify
do_source_file: Parsing: cSI_project_tree.cc as language CPP

E:\Program Files\uncrustify\uncrustify\bin>uncrustify -c options.cfg *.cc
Output suffix: .uncrustify
Failed to load (*.cc)`

This is with windows 11.

**Comment by gmaurel** [comment]
just now: uncrustify doesn't support *.h or *.cc
Please use individual file, or use a script with one line per file
