### ISSUE TITLE
Failed to use my.cfg

### ISSUE THREAD

**Issue by SAIL-Fang** [uncrustify/uncrustify#4059]
Uncrustify version: Uncrustify-0.77.1_f
In Linux 
uncrustify -c /home/administrator/test/gtest/scripts/myuncrustify.cfg --no-backup 
/home/administrator/test/gtest/esim/virt/sys_ext/esim_client/esim_plot.cpp 

The .cfg file is empty but i still can format the cpp. How can I use my own.cfg file instead of the built-in configuration?

**Comment by SAIL-Fang** [comment]
It seems that the purpose of the my.cfg file is to modify the value of the default configuration, rather than formatting it with the contents of my.cfg.

**Comment by micheleCTDE** [comment]
Any option not specifically listed in a cfg file will use the default value. So an empty config file is pretty much the same as using the default for all options.
What exactly is the issue here? I don't see any fix required for this this issue.

**Comment by SAIL-Fang** [comment]
> Any option not specifically listed in a cfg file will use the default value. So an empty config file is pretty much the same as using the default for all options. What exactly is the issue here? I don't see any fix required for this this issue.

I misunderstood, I thought the empty file did not perform any operation, but didn't expect the cfg file is modified default value

**Comment by SAIL-Fang** [comment]
I misunderstood, I thought the empty file did not perform any operation, but didn't expect the cfg file is used to modify the default value
