### ISSUE TITLE
base_types.h:18:10: fatal error: 'config.h' file not found

### ISSUE THREAD

**Issue by DrayChou** [uncrustify/uncrustify#406]
when i run this command in my iterm
sudo xcodebuild -configuration 'Install'

it told me:
** BUILD FAILED **

The following build commands failed:
	CompileC build/uncrustify.build/Install/uncrustify.build/Objects-normal/x86_64/args.o src/args.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

and this  log was that:

/uncrustify/src/base_types.h:18:10: fatal error: 'config.h' file not found
#include "config.h"
         ^
1 error generated.

**Comment by jhmacdon** [comment]
+1

**Comment by racorretjer** [comment]
+1 Bump. Same error.

**Comment by bengardner** [comment]
I don't know anything about XCode, but did you run "configure"?
That creates the config.h file.

**Comment by gmaurel** [comment]
On the top of the file config.h you can find:
/* src/config.h.  Generated from config.h.in by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

Please test again by following the instructions you can find in INSTALL
If you mean, anything is not correct, feel free to make a proposal. Thanks
