### ISSUE TITLE
'align_assign_span' option can't align '=' after member '.' or '->'

### ISSUE THREAD

**Issue by SAIL-Fang** [uncrustify/uncrustify#4063]
[debug.txt](https:github.com/uncrustify/uncrustify/files/12122738/debug.txt)

test file:
```
void BaseMotor::SetShaftLoad(realtype J, realtype B)
{
    realtype reltol = 1;
    this->t = this->t0;
}
```
generated results
```
void BaseMotor::SetShaftLoad(realtype J, realtype B)
{
    realtype reltol = 1;
    this->t = this->t0;
}
```
expected results
```
void BaseMotor::SetShaftLoad(realtype J, realtype B)
{
    realtype reltol = 1;
    this->t         = this->t0;
}
```

working version: Uncrustify-0.77.1_f"

**Comment by SAIL-Fang** [comment]
It seems that the '=' that defines a variable and initializes it at the same time is different from the '=' statement. I can't find the relevant option to control whether they are mixed and aligned

**Comment by guy-maurel** [comment]
The align is different for a variable declaration:
realtype reltol = 1;

and an assignment:
this->t = this->t0;

as an example:
```.cpp
void BaseMotor::SetShaftLoad(realtype J, realtype B)
{
   realtype reltol = 1;
   int      abc    = 777;

   this->t    = this->t0;
   this->tttt = this->t0;
}
```

**Comment by SAIL-Fang** [comment]
> 



> The align is different for a variable declaration:变量声明的对齐方式有所不同： realtype reltol = 1;真实类型reltol = 1；
> 
> and an assignment: 和一个作业： this->t = this->t0;  这个->t = 这个->t0;
> 
> as an example: 举个例子：
> 
> ```c++
> void BaseMotor::SetShaftLoad(realtype J, realtype B)
> {
>    realtype reltol = 1;
>    int      abc    = 777;
> 
>    this->t    = this->t0;
>    this->tttt = this->t0;
> }
> ```

Thanks for answer, because they are all '=' so I want to make them align, it seems that there is no option for the time being

**Comment by guy-maurel** [comment]
uncrustify doesn't have any option for "all"
