### ISSUE TITLE
Incorrect spacing before unnamed reference [C++]

### ISSUE THREAD

**Issue by alir3zakh** [uncrustify/uncrustify#4064]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

In our project, we place pointers & references next to the identifier rather than the type, unless it is an unnamed reference/pointer.
unnamed pointers have correct behaviour but unnamed references have bug when they are followed by '>'
I wrote an elementary program to reproduce the bug. the corresponding files are under [this](https://github.com/alir3zakh/uncrustify_bugs/) repo.

[link](https://github.com/alir3zakh/uncrustify_bugs/blob/main/uncrustify.cfg) to config file.
[link](https://github.com/alir3zakh/uncrustify_bugs/blob/main/debug.txt) to debug file.

```
uncrustify -v
Uncrustify-0.77.1_f
```

input code:
```cpp
#include <iostream>

int main() {
	int a, b;
	std::pair<int &, int &> p(a, b);

	void foo(int &, int &);
}
```

generated result:
```cpp
#include <iostream>

int main() {
	int a, b;
	std::pair<int&, int &> p(a, b);

	void foo(int&, int&);
}
```

expected result:
```cpp
#include <iostream>

int main() {
	int a, b;
	std::pair<int&, int&> p(a, b);

	void foo(int&, int&);
}
```

**Comment by gmaurel** [comment]
fixed by #4065
