### ISSUE TITLE
the type is PARAMETER_PACK, is not coded. Please make a call.

### ISSUE THREAD

**Issue by pemessier** [uncrustify/uncrustify#4075]
Using `Uncrustify-0.77.1` with default config on Windows using this snippet of code:

```
#pragma once
template< template< typename... > typename TContainer, typename TFnct, typename TInValue, typename... TArgs >
requires std::ranges::range< TContainer< TInValue, TArgs... > >
auto Transform( const TContainer< TInValue, TArgs... >& srcCont_, TFnct&& fctr_ ) ->
TContainer< std::invoke_result_t< TFnct, TInValue > >
{
    TContainer< std::invoke_result_t< TFnct, TInValue > > destination;
    Transform( srcCont_, std::inserter( destination, destination.end() ), std::forward< TFnct >( fctr_ ) );
    return destination;
}
```

Fails with:
```
uncrustify.exe -c - -l CPP --no-backup --if-changed c:\temp\File.h
do_source_file: Parsing: c:\temp\File.h as language CPP
ParsingFrame::pop (indent_text:1152): orig line is    3, orig col is   63, type is PARAMETER_PACK,
ParsingFrame::pop (indent_text:1152): the type is PARAMETER_PACK, is not coded. Please make a call.
```

**Comment by micheleCTDE** [comment]
Will try to push a fix for this during the week. It's similar to some other reports I have already fixed, I just need some time to code it and test it.

**Comment by guy-maurel** [comment]
I am already doing

**Comment by guy-maurel** [comment]
PR #4076 is a bug fix proposal.
Please test it and report.

**Comment by pemessier** [comment]
@guy-maurel I tested your fix locally with the real file, it does work.

This code then shows another error: `open_line is 13, parent is NONE: Unmatched ANGLE_OPEN`

It seems to be related with this construct: `template< template< typename... > typename TContainer`

However, this is a totally other issue than this one.
