### ISSUE TITLE
Multiplication sign is incorrectly treated as pointer star (Objective-C)

### ISSUE THREAD

**Issue by realf** [uncrustify/uncrustify#408]
```
# Add or remove space around arithmetic operator '+', '-', '/', '*', etc
sp_arith                                  = add   # ignore/add/remove/force
```
```
# Add or remove space before pointer star '*'
sp_before_ptr_star                        = remove   # ignore/add/remove/force
```
Produces
```
-    CGFloat fontSize = floorf([font pointSize] * [self tileContentScale] + 0.5);
+    CGFloat fontSize = floorf([font pointSize]* [self tileContentScale] + 0.5);
```

**Comment by gmaurel** [comment]
Sorry: Which language is it?

**Comment by creederickson** [comment]
That would be Objective-C

**Comment by gmaurel** [comment]
uncrustify tests the next character after "*"
If the next is a "[" the "*" will be transform to a POINTER.

I don't know about the syntax of Objective-C.
Is there anybody who could tell me how to modify the rule?

**Comment by realf** [comment]
In Objective-C, `[font pointSize]` means call method `pointSize` on object `font`. This is identical to `font->pointSize()` in C++. Similarly, `[self tileContentScale]` is like `this->tileContentScale()` in C++.

**Comment by gmaurel** [comment]
Change
      else if ((next->type == CT_SQUARE_OPEN)

to
      else if ((next->type == CT_SQUARE_OPEN) &&
               !(cpd.lang_flags & LANG_OC))

The issue # 408 is fixed.
Please test it at git 275f281..5c8947a
