### ISSUE TITLE
Option to separate single line if statements and function.

### ISSUE THREAD

**Issue by Crayder** [uncrustify/uncrustify#409]
Example code:

	if(X == Y) X = Z;
	if(Y == Z)
		Y = X;

Running that with the option to turn the second if statement into a one-liner is already possible and outputs the following:

	if(X == Y) X = Z;
	if(Y == Z) Y = X;

Sure that's nice but I want the option to do the opposite (and from what I see, it's not there):

	if(X == Y)
		X = Z;
	if(Y == Z)
		Y = X;

**Comment by Crayder** [comment]
Bump.

**Comment by gmaurel** [comment]
ou get you wanted to have. The new options are:
  nl_split_if_one_liner      = true
  nl_split_for_one_liner     = true
  nl_split_while_one_liner   = true

Please test it from git version bb263db0bc9b75142584f54ae4bc74a1e80a0488 at 2016-05-24 10:21

**Comment by Crayder** [comment]
Awesome, thanks
