### ISSUE TITLE
"sp_cpp_lambda_argument_list = add" always adds a space for lambda with no argument list

### ISSUE THREAD

**Issue by pemessier** [uncrustify/uncrustify#4094]
Using Uncrustify-0.77.1 with the following config file on Windows
```
sp_cpp_lambda_argument_list = add
```

Using this snippet of code:
```
auto lambda1 = [](int x){};
auto lambda2 = [](){};
```

Outputs:
```
auto lambda1 = []( int x ){
	       };
auto lambda2 = []( ){
	       };
```

Is it possible to have a setting like sp_func_proto_paren_empty/sp_func_def_paren_empty/sp_func_call_paren_empty/sp_func_class_paren_empty where the extra space in lambda2 argument list could be removed so that the expected output would be:
```
auto lambda1 = []( int x ){
	       };
auto lambda2 = [](){
	       };
```

**Comment by guy-maurel** [comment]
Yes

**Comment by guy-maurel** [comment]
Et voilà!
Il vous faut utiliser la nouvelle option;
`sp_cpp_lambda_argument_list_empty`

**Comment by pemessier** [comment]
Works beautifully! Merci!
