### ISSUE TITLE
Interaction of sp_cpp_before_struct_binding and sp_after_byref

### ISSUE THREAD

**Issue by Parranoh** [uncrustify/uncrustify#4100]
My config:
```
sp_cpp_before_struct_binding = force
sp_after_byref = remove
```

My C++ code:
```cpp
void f()
{
	auto[x,y]=g();
	auto  [  x  ,  y  ]  =  z  ;
	auto&[x,y]=g();
	auto  &  [  x  ,  y  ]  =  z  ;
}
```

The [debug output](https://github.com/uncrustify/uncrustify/files/12622225/debug.txt) from version `Uncrustify-0.77.1-83-5cf1e79f`.

Uncrustify's output:
```cpp
void f()
{
	auto [x,y]=g();
	auto [  x,  y  ]  =  z;
	auto& [x,y]=g();
	auto  & [  x,  y  ]  =  z;
}
```

What I had hoped for:
```cpp
void f()
{
	auto [x,y]=g();
	auto [  x,  y  ]  =  z;
	auto&[x,y]=g();
	auto  &[  x,  y  ]  =  z;
}
```

Inspecting the [output of `-L66`](https://github.com/uncrustify/uncrustify/files/12622256/L66.txt), it seems to me like `sp_after_byref` is never triggered in this example. This is also true if I set `sp_cpp_before_struct_binding` to `ignore` or `not_defined`.

Outside this toy example, I'd like the spaces to be `auto [` in the first two cases and `auto &[` in the other two, but `sp_before_byref` doesn't seem relevant here, so I left it out. Is there a way to achieve this?

**Comment by guy-maurel** [comment]
We have:
```
   if (  language_is_set(LANG_CPP)
      && (  first->Is(CT_BYREF)
         || first->Is(CT_QUALIFIER)
         || first->Is(CT_TYPE))
      && second->Is(CT_SQUARE_OPEN)
       ...
```
just now.

**Comment by gmaurel** [comment]
Hello @Parranoh 
Do you wish 3 new options for the 3 cases as listed above ?

**Comment by guy-maurel** [comment]
PR #4171 is a bug fix proposal.
Please test it and report.
