### ISSUE TITLE
blank lines (newlines) after constructor/ destructor 

### ISSUE THREAD

**Issue by tmbeniamin** [uncrustify/uncrustify#411]
I'm using uncrustify uncrustify-0.61.3-gf65394e-win32 to format c++ code.
After each function declaration in header file, I want 2 blank lines.
It's working for methodes but not for constructors and destructors.

I have the code in a header file:
```C++
class settings final
{
public:
settings();
~settings(	) = default;
settings(const settings&) = delete;
settings& operator=(const settings&) = delete;
void set_something(const std::string& p_settings_name);
void set_another_setting(const std::string& p_settings_name);
}
```

I'm using this settings:
  nl_after_func_proto = 3
  nl_after_func_proto_group = 3

and my code looks now so:
```C++
class settings final
{
public:
settings();
~settings(	) = default;
settings(const settings&) = delete;
settings& operator=(const settings&) = delete;
void set_something(const std::string& p_settings_name);


void set_another_setting(const std::string& p_settings_name);


}
```
And I need to look like:
```C++
class settings final
{
public:
settings();


~settings(	) = default;


settings(const settings&) = delete;


settings& operator=(const settings&) = delete;


void set_something(const std::string& p_settings_name);


void set_another_setting(const std::string& p_settings_name);


}
```

**Comment by byron-hawkins** [comment]
There appears to be a regression on this issue. Starting with:

    class Foo {                                                                            
        public:                                                                            
            Foo();                                                                         
            bool isBar();                                                                  
            void setBar(bool bar);                                                         
    };  
    
Applying these settings:

    nl_after_func_proto = 2
    nl_after_func_proto_group = 2

The uncrustified result has no space between the constructor and the function `isBar`:

    class Foo {                                                                            
    public:                                                                                
        Foo();                                                                             
        bool                                                                               
        isBar();                                                                           
                                                                                           
        void                                                                               
        setBar(bool bar);                                                                  
    };   

[debug.txt](https://github.com/uncrustify/uncrustify/files/1376445/debug.txt)

    > uncrustify --version
    Uncrustify-0.65-208-9ced1ed

**Comment by guy-maurel** [comment]
Please make a "new issue" with it.
Make a link to this issue here, which is closed.
Thanks.

**Comment by guy-maurel** [comment]
This is not a bug:
You are using:
`nl_func_type_name_class  = force`
which means:
_Add or remove newline between return type and function name inside a class {}_
Change the option to:
`nl_func_type_name_class  = remove`
to get what you wanted to get.
