### ISSUE TITLE
Single line C-style comment trailing a #endif are not converted to CPP

### ISSUE THREAD

**Issue by micheleCTDE** [uncrustify/uncrustify#4124]
Single line C-style comment trailing a #ifdef are correctly converted to CPP style if requested. But single line C-style comment trailing a #endif are not converted to CPP. Expected behavior is that those are also converted.
Attached zip file with input file, configuration and output showing the problem.
[comment_conversion_endif.zip](https://github.com/uncrustify/uncrustify/files/12903094/comment_conversion_endif.zip)

**Comment by micheleCTDEAdmin** [comment]
Solved by PR #4125
