### ISSUE TITLE
Single line javadoc comments should not be converted to CPP `//` style

### ISSUE THREAD

**Issue by micheleCTDE** [uncrustify/uncrustify#4127]
Single line javadoc comments should not be converted to CPP `//` style if conversion option is set.
Attached zip file with input file, configuration and output showing the problem.
[comment_conversion_javadoc_single.zip](https://github.com/uncrustify/uncrustify/files/13035802/comment_conversion_javadoc_single.zip)

**Comment by micheleCTDEAdmin** [comment]
Fixed by PR #4128
