### ISSUE TITLE
Trailing multiline C comment get out of position

### ISSUE THREAD

**Issue by micheleCTDE** [uncrustify/uncrustify#4129]
Multiline C comments with the first line starting in a trailing position (that is at the end of the line, after some code) get out of position. Example of such comment
```
	LIBR_ERROR_EXPANDSECTION = -20, /* Failed to set output file architecture to input file
	                                   architecture */
```
Attached zip file with config, input and output file.
[comment_trailing_c_multiline.zip](https://github.com/uncrustify/uncrustify/files/13040535/comment_trailing_c_multiline.zip)

**Comment by micheleCTDEAdmin** [comment]
Solved by PR #4130
