### ISSUE TITLE
Space Being Added After Cast Despite Rule Forbidding It

### ISSUE THREAD

**Issue by ghost** [uncrustify/uncrustify#4132]
Single-line test file:
```cpp
using stdsize = typename _arch_helper< (int)sizeof(void*) >::sz_t;
```
Single-line configuration file:
```text
sp_cpp_cast_paren = remove
```
The `sp_cpp_cast_paren` option can even be omitted, making for an empty configuration that's all defaults.

Uncrustify erroneously adds a space in the C-style cast:
```cpp
using stdsize = typename _arch_helper< (int) sizeof(void*) >::sz_t;
```
Using current release `Uncrustify-0.77.1`.

**Comment by guy-maurel** [comment]
I can reproduce

**Comment by guy-maurel** [comment]
PR #4133 is a bug fix proposal.
Please test it and report.
