### ISSUE TITLE
Function definition line splitting not working as expected

### ISSUE THREAD

**Issue by dundargoc** [uncrustify/uncrustify#4151]
• a link to a debug file:
https://gist.github.com/dundargoc/a9feecce60bd336464e6c548ca6df014

• include a small but complete test file that will be uncrustifyed

```c
void buf_write_make_backup(char *fname, bool append, FileInfo *file_info_old, vim_acl_T acl,
                           int perm, unsigned bkc, bool file_readonly, bool forceit,
                           int *backup_copyp, char **backupp,
                           int *err) {
}
```

• include the generated results
```c
void buf_write_make_backup(char *fname, bool append, FileInfo *file_info_old, vim_acl_T acl,
                           int perm, unsigned bkc, bool file_readonly, bool forceit,
                           int *backup_copyp, char **backupp,
                           int *err) {
}
```

• include the expected results
```c
void buf_write_make_backup(char *fname, bool append, FileInfo *file_info_old, vim_acl_T acl,
                           int perm, unsigned bkc, bool file_readonly, bool forceit,
                           int *backup_copyp, char **backupp, int *err) {
}
```

• include the current version of your Uncrustify executable
Uncrustify-0.78.0_f

• if possible include a version that worked
Uncrustify-0.77.1_f

---

I have bisected the change in behavior to the commit 57fa941489536a4beb4e55428cc85628a9423ccc

**Comment by micheleCTDE** [comment]
Already working on a fix, will probably publish tomorrow after I complete some test files and clean up the code.

**Comment by micheleCTDE** [comment]
@dundargoc
PR#4152 is a proposed fix. As far as I can say from testing on the neovim code base, a lot of the awkward splits reported in neovim/neovim#26065 are now solved.
Please test and let me know.

**Comment by dundargoc** [comment]
Yup, the PR fixes the problem.

**Comment by micheleCTDE** [comment]
PR merged, thanks for testing. It definitely fixes a number of bad splits. I still see corner cases in our code base that will need extra work, but I think this was the bigger step needed.
