### ISSUE TITLE
Brace Underflow Crash

### ISSUE THREAD

**Issue by agatha2** [uncrustify/uncrustify#4157]
The following valid C++ code causes uncrustify to crash (config file can be empty):
```cpp
void test(int var) {
	switch (var) {
		#define CASE(VAL)\
			case VAL: {
		CASE(1) break; }
		CASE(2) break; }
		CASE(3) break; }
		default: break;
	}
}
```
Error is:
```text
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 1)
```
The version is the [current binary release](https://github.com/uncrustify/uncrustify/releases/tag/uncrustify-0.78.1), reported by `-v` as "Uncrustify-0.78.1_f".

The problem seems to be an underflow in a stack of braces. While I appreciate that correctly understanding the code requires a macro processor (and could even be impossible if e.g. `CASE` were defined in an `#include`), as well as that the code itself is questionable (it will be rewritten, regardless), uncrustify should still try to handle this gracefully. At the very least, uncrustify should detect this and emit an error message instead of crashing (tracking this down from an autoformatter silently failing to do anything was pretty annoying).

**Comment by micheleCTDE** [comment]
There is already an option to print a message in case of unbalanced braces related to preprocessor (`pp_warn_unbalanced_if`).
I agree uncrustify should at least not crash with the above code, but beside that there won't be much more that uncrustify can do since it is not a compiler and does not expand #define in place (pretty much as you wrote in your comment :-) )

**Comment by micheleCTDE** [comment]
What config file did you use for your testing?

**Comment by micheleCTDE** [comment]
PR #4158 avoids the crash and add a message in the log if such scenario is encountered.

**Comment by micheleCTDEAdmin** [comment]
PR merged.
