### ISSUE TITLE
C : whitespace added between strings

### ISSUE THREAD

**Issue by dev-pac** [uncrustify/uncrustify#4176]
My C code is formatted by uncrustify with a whitespace added between my strings but i don't want this whitespace between the SEP and "%%".

Original code:
```
void main()
{
  foo(" LIKE '%s"SEP"%%'");
}
```
Formatted:
```
void main()
{
  foo(" LIKE '%s"SEP "%%'"); // whitespace added
}
```
 
I tried replacing all "force" and "add" of "sp_" fields with "ignore" but the whitespace is always added.

It's a bug or i'm missing something in ths config file ?

**Comment by guy-maurel** [comment]
PR #4180 is a bug fix proposal.
Please test it and report.
You need to use the new option: **sp_string_string**
with the the value _ignore_ or _remove_
