### ISSUE TITLE
Comment mangled

### ISSUE THREAD

**Issue by jlee975** [uncrustify/uncrustify#418]
Pipe is inserted when uncrustify processes the following comment (which is a small portion of some ascii art I had in my code):

```
/*
 |
 |-
 */
```
becomes
```
/*
 |
 ||-
 */
```
Doesn't happen if the first pipe or trailing '-' is removed.

**Comment by mananaBanana** [comment]
@jlee975 What configuration file are you using? Also, is it a C source file that you are processing in uncrustify?

**Comment by jlee975** [comment]
I'm using the default configuration file created by 0.61. The file is a C++ file (but the same problem happens as a C file). I can reproduce with:

>uncrustify --version
uncrustify 0.61
>rm ~/.uncrustify.cfg
>uncrustify --update-config-with-doc -o derp.cfg
>uncrustify -c derp.cfg -l CPP test.cpp

**Comment by jlee975** [comment]
Still happening in 0.62

**Comment by gmaurel** [comment]
The actual git version works fine.
