### ISSUE TITLE
Unexpected handling of the increment operator in a macro.

### ISSUE THREAD

**Issue by JosiahdpGit** [uncrustify/uncrustify#4182]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

CURRENT VERSION:
Uncrustify-0.78.1-32-c543ad255

ISSUE:
The increment operator is handled incorrectly in this macro, to the point where it breaks the build.

CODE (written in *.c files):
```
#define FOO( x )      { if ( x < 10 ) ptrTest->foo[x]++; }
```

EXPECTED OUTPUT:
```
#define FOO( x )      { if ( x < 10 ) ptrTest->foo[x]++; }
```

ACTUAL OUTPUT:
```
#define FOO( x )      { if ( x < 10 ) ptrTest->foo[x] ++; }
```

**A space is added between the closing bracket and the increment operator**.
I believe this is because uncrustify tokenises the ‘++’ as INCDEC_BEFORE, which can be seen in the debug.

SIDE NOTE:
Adding braces around the body of the if results in uncrustify handling the ‘++’ correctly.
```
#define INCFOO( x )      { if ( x < 10 ) { ptrTest->foo[x]++; } }
```

There were no changes made to the ‘++’ after running uncrustify on the line.

EXAMPLE FILE:
```
#define FOO( x )      { if ( x < 10 ) ptrTest->foo[x]++; }

int main() {
          struct Test
          {
                    int foo[10];
                    int bar;
          };
          struct Test myTest = { { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 }, 4 };
          struct Test *ptrTest;

          ptrTest = &myTest;

          INCFOO( 5 )
};
```

CONCLUSION:
This seems like a bug to us. How would you like to proceed?

Please let me know if there is any more information needed, and I will provide it if I can.

DEBUG:
[uncrustify_debug.txt](https://github.com/uncrustify/uncrustify/files/13725738/uncrustify_debug.txt)

UNCRUSTIFY CONFIGURATION:
[uncrustify.txt](https://github.com/uncrustify/uncrustify/files/13725742/uncrustify.txt)

SIDE NOTE 2:
Example: uncrustify handles the increment operator successfully within a for loop.

```
#include <stdio.h>

/**
 * @brief   TODO
 */
int main() {
          int c = 0;

          for (c = 0; c < 5; c++)
          {
                    printf( "Count: %d\n", c );
          }

          return 0;
};
```

There were more cases than this loop that we used to try and identify a pattern which led to our macro breaking, but our search did not bear fruit.

DEBUG:
[uncrustify_debug_case_two.txt](https://github.com/uncrustify/uncrustify/files/13725982/uncrustify_debug_case_two.txt)

**EDIT:**
Further investigation into the debug logs brought this block to our attention:
```
   do_space(3438): WARNING: unrecognize do_space:
   first orig line  is 1, orig col  is 85, Text()  ']', GetType() is  SQUARE_CLOSE
   second orig line is 1, orig col is 89, Text() '++', GetType() is INCDEC_BEFORE
   Please make a call at https://github.com/uncrustify/uncrustify/issues/new
   or merge the line:
   { CT_SQUARE_CLOSE,    CT_INCDEC_BEFORE},
```
Appending the ``` { CT_SQUARE_CLOSE,    CT_INCDEC_BEFORE}, ``` to the ```no_space_table_t no_space_table[]``` corrected the spacing problem introduced by uncrustify, leaving the macro as ``` #define FOO( x )      { if ( x < 10 ) ptrTest->foo[x]++; } ```.

We hope that this change can be made to the master branch, how do you want to proceed?

**Comment by guy-maurel** [comment]
Please, only ONE bug pro message!

What is function_header.txt

**Comment by pablomcmaster** [comment]
> Please, only ONE bug pro message!
> 

The issue text relates to the single problem of the post-increment operator spacing being modified when used in a macro.
Included above is the analysis undertaken, steps to reproduce, and a fix for the problem. This issue #4182 is to confirm that the addition of `{ CT_SQUARE_CLOSE,    CT_INCDEC_BEFORE},` into `no_space_table_t no_space_table[]` is a correct fix, and request that this be incorporated into the codebase.

**Comment by JosiahdpGit** [comment]
I think the issue relates to one single bug: "The increment operator is handled incorrectly in this macro, to the point where it breaks the build."
The edit provides further information to our findings on this matter, and a potential solution.
 
function_header.txt is used by uncrustify. It is referenced in the config file, and the file contents are pulled in during execution of the tool when needed. The body of function_header.txt is used as the brief for functions without a brief.
e.g.
```int main() { return 1 }```
becomes
```
/**
* @brief   TODO
*/
int main() { return 1 }
```

**Comment by guy-maurel** [comment]
PR #4187 is a bug fix proposal.
Please test it and report.

**Comment by JosiahdpGit** [comment]
Thank you, this has worked.
