### ISSUE TITLE
The mod_full_brace_function is putting braces inside the preprocessor and broken the code

### ISSUE THREAD

**Issue by addonszz** [uncrustify/uncrustify#419]
The mod_full_brace_function is putting braces inside the preprocessor and broken the code. The option description is : 

#Add or remove braces on single-line function definitions. (Pawn)
```pawn
#if AMXX_VERSION_NUM < 183
public client_disconnect( player_id )
#else
public client_disconnected( player_id )
#endif
{

}
```
Became this, which is broken code:
```pawn
#if AMXX_VERSION_NUM < 183
public client_disconnect( player_id )
#{ \
    else }

public client_disconnected( player_id )
#{ \
    endif }

{
}
```
He is my debug file: [debug.txt](https://github.com/bengardner/uncrustify/files/81851/debug.txt)

**Comment by gmaurel** [comment]
Could you push the output you expected to get?

**Comment by bengardner** [comment]
This has been fixed.
