### ISSUE TITLE
`template` keyword usage in method 

### ISSUE THREAD

**Issue by mathstuf** [uncrustify/uncrustify#4220]
Configuration: https://gist.github.com/mathstuf/d28e774a3f7b3e7f058db1a65b1cf9f3

Debug file: not written when attempted.

Source:

```cpp
template <typename T>
int foo()
{
    return T{}.template method<arg>();
}
```

See [this part](https://timsong-cpp.github.io/cppwp/n3337/temp.names#5) of the C++ standard which talks about this syntax.

Command and output:

```commands
% uncrustify -p template.txt -c .uncrustify.cfg -f template.cxx
do_source_file: Parsing: template.cxx as language CPP
ParsingFrame::pop (indent_text:1352): orig line is    4, orig col is   16, type is     TEMPLATE,
ParsingFrame::pop (indent_text:1352): the type is TEMPLATE, is not coded. Please make a call
```

```commands
% uncrustify -v
Uncrustify-0.78.1
```

**Comment by guy-maurel** [comment]
PR #4225 is a bug fix proposal.
Please test it and report.
