### ISSUE TITLE
Issue (C header file): backslashes at end of MACRO are not aligned with uncrustify version 0.78.*

### ISSUE THREAD

**Issue by precla** [uncrustify/uncrustify#4245]
see example file and how the output differs on 0.77.1 and 0.78.* (0.78.* tested with both 0.78.0 and 0.78.1)
(the gist has the END result for each version, but can be used for testing)
https://gist.github.com/precla/8afe63ec3ba9266e0d4dce756949843b

expected in `>=0.78.*` is to have the backslash at the end aligned but it's off by the one space that has been added between `e & BIT_MASK`

attached debug of each version

[debug_0.77.1.txt](https://github.com/uncrustify/uncrustify/files/14268354/debug_0.77.1.txt)

[debug_0.78.1.txt](https://github.com/uncrustify/uncrustify/files/14268355/debug_0.78.1.txt)

config file (renamed to .txt to be able to upload it here):

[uncrustify.cfg.txt](https://github.com/uncrustify/uncrustify/files/14268373/uncrustify.cfg.txt)

**Comment by guy-maurel** [comment]
You need to use the option:
`align_nl_cont  = 1`
to get it, with the current git.
The current git version works pretty fine under Linux Mint.

**Comment by precla** [comment]
just tried it and it didn't work out well. The spaces between `do` and `\` get turned into tabs, which makes everything look even more worse:

```
#define SOME_MACRO(abc, d, e)								 \
	do										 \
	{										 \
		abc[BIT_ABC(d) / 8] |= (uint8_t)((e & BIT_MASK(d)) << (BIT_ABC(d) % 8)); \
	} while (0)
```
(unfortunately when i copy it here, it formats it correctly, therefore i also attach a screenshot)

![image](https://github.com/uncrustify/uncrustify/assets/7177449/a3c36ef4-746d-45dc-8d16-d9540864cbe0)

**Comment by precla** [comment]
thank you a lot!

having both set, works fine:
```
indent_with_tabs = 0
align_nl_cont = 1
```
