### ISSUE TITLE
Error with sp_return sp_case_label and sp_after_type when set to not_defined

### ISSUE THREAD

**Issue by JEAYNE** [uncrustify/uncrustify#4253]
Hi,

I'm running uncrustify 0.78.1_f under Windows 11.

According to files config.txt, default.cfg and uigui_uncrustify.ini these 3 options `sp_return`  `sp_case_label` and `sp_after_type`, can take 5 values: ignore/add/remove/force/not_defined.
But when I use the '`not-defined`' value I get the error: **` to_string: Unknown iarf_e '5'`**

_Note: Adding  `-p debug.txt`  doesn't help because the file debug.txt is not created._

# sp_return

```
uncrustify -c - --set sp_return=not_defined -f input.cpp
```
input.cpp:
``` 
int f1(){ return a; }
```
Output:
```
  do_source_file: Parsing: input.cpp as language CPP
  to_string: Unknown iarf_e '5'
```

# sp_case_label

```
  uncrustify -c - --set sp_case_label=not_defined -f input.cpp
```
input.cpp
```
  void f2(){ 
    switch(a){ 
      case 1: break;
    } 
  }
```
Output:
```
  do_source_file: Parsing: input.cpp as language CPP
  to_string: Unknown iarf_e '5'
```

# sp_after_type

```
  uncrustify -c - --set sp_after_type=not_defined -f input.cpp
```
input.cpp
```
  void f3(){ int n; }
```
Output:
```
  do_source_file: Parsing: input.cpp as language CPP
  to_string: Unknown iarf_e '5'
```

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

**Comment by guy-maurel** [comment]
It is difficult to debug, because I am using Linux.
Could you try another way to call:
`uncrustify -c JEAYNE.cfg -f JEAYNE.cpp -L A 2>A.txt`

and put the option/value of the set command in the config file JEAYNE.cfg
Push the lines about do_source_file: Parsing:  (and some more lines) from
the A.txt file
Which version are you using? From github?

**Comment by JEAYNE** [comment]
I'm using Uncrustify-0.78.1_f published on github.
```
> certutil -hashfile uncrustify.exe
SHA1 hash of uncrustify.exe:
c0be02ee7e9a340641f70c9679db01a8e581a1fc
```
I executed this command for each option:
`uncrustify.exe -c <option>.cfg -f <option>.cpp -L A 2> <option>.txt`

Each .tar.gz file below contains the config (.cfg), the code (.cpp) and the output (.txt)

- [sp_after_type.tar.gz](https://github.com/uncrustify/uncrustify/files/14451881/sp_after_type.tar.gz)
- [sp_case_label.tar.gz](https://github.com/uncrustify/uncrustify/files/14451887/sp_case_label.tar.gz)
- [sp_return.tar.gz](https://github.com/uncrustify/uncrustify/files/14451888/sp_return.tar.gz)

**Comment by guy-maurel** [comment]
PR #4256 is a bug fix proposal.
Please test it and report.
