### ISSUE TITLE
--tracking cannot be used with a file including a colon

### ISSUE THREAD

**Issue by JEAYNE** [uncrustify/uncrustify#4261]
Hi,
Here a bug preventing to use `--tracking <art>:<file>` with a file including a `:` (colon)
A colon is mainly used by Windows paths that include a drive.
Example  `--tracking space:C:\path\to\file.html`

The root cause of this bug is this short piece of code in the function main() in uncrustify.cpp
```
      // Tokenize and extract key and value
      const char *tracking_art = strtok(buffer, ":");
      const char *html_file    = strtok(nullptr, ":");    // <-- bug
```
The second call to strtok() captures the substring between the first `:` and the second `:`
As a result html_file points to "`C`".

The fix is very simple:
```
      // Tokenize and extract key and value
      const char *tracking_art = strtok(buffer, ":");
      const char *html_file    = strtok(nullptr, "\0");   // <-- fix
```
Now, the second call to strtok() captures the substring after the first `:` up to the end of the string.
As expected Html_file points to "`C:\path\to\file.html`"

Regards

**Comment by micheleCTDEAdmin** [comment]
Solved by PR #4262
