### ISSUE TITLE
Infinite loop - nested if statements (without braces) with a single line comment after a return.

### ISSUE THREAD

**Issue by AnthonySWest** [uncrustify/uncrustify#4268]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
Uncrustify version 0.78.1 hangs when there is a comment after a return line within nested if statements without braces. That is a mouthful, I know. Please see the attached zip for the sample config and the sample code that causes the infinite loop.

[Uncrustify_0.78.1_Hangs.zip](https://github.com/uncrustify/uncrustify/files/14878557/Uncrustify_0.78.1_Hangs.zip)

Code that causes the infinite loop (at least with the config settings we are using - see the attached zip file):
```
void foo()
{
  if (a)
    if (b)
      return; //
}
```

Any of these work fine:
```
// Works
void foo()
{
  if (a)
  {
    if (b)
      return; //
  }
}

// Works
void foo()
{
  if (a)
    if (b)
      return;
}

// Works
void foo()
{
  if (a)
    if (b)
    {
      return; //
    }
}
```

**Comment by guy-maurel** [comment]
Thanks for the message

**Comment by guy-maurel** [comment]
PR #4275 is a bug fix proposal.
Please test it and report.

**Comment by AnthonySWest** [comment]
@guy-maurel  Tested working. Thanks!
