### ISSUE TITLE
Uncrustify hangs until the system runs out of memory

### ISSUE THREAD

**Issue by pemessier** [uncrustify/uncrustify#4274]
Using Uncrustify-0.78.1_f, with with the default configuration on Windows 10:

`uncrustify.exe -c - file.cpp`

Use the following code example (the error here is that the user made a typo: there is a bogus `0` leading the method name).

```
int foo( const Object& object )
{
    return object.0Method();
}
```

The process hangs until the system runs out of memory.

**Comment by guy-maurel** [comment]
merci pour le message.
Je m'en occupe.

**Comment by guy-maurel** [comment]
et voilà:
PR #4281 is a bug fix proposal.
Please test it and report.

**Comment by pemessier** [comment]
Works great, merci :)
