### ISSUE TITLE
stmt never reached

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#4327]
The case a config file with
```
sp_after_emb_cmt      = force
sp_num_after_emb_cmt  = 3
```

was never reached
I:
FooBar::CFooBar(CWnd* pParent/*=NULL*/);
E:
CFooBar::CFooBar(CWnd* pParent /*=NULL*/   );

**Comment by micheleCTDE** [comment]
New solution in PR #4380 has replaced the original solution. The new option `sp_emb_cmt_priority` can now be used to control between old and new behavior. By default, the old behavior is preserved. If the option is set to `true`, then embedded comment spacing options will have priority over other spacing options (parenthesis, commas, braces, ...) providing the beharior required for this issue.
