### ISSUE TITLE
c# interpolation symbol problem

### ISSUE THREAD

**Issue by LaraSQP** [uncrustify/uncrustify#435]
A space is added between the interpolation symbol and the following string so that...

$"whatever {var} and more"

...becomes...

$ "whatever {var} and more"

... breaking the syntax of the interpolated string.

Thank you guys for all the hard work, btw.

**Comment by addonszz** [comment]
Hi, could you post also the debug results. Example:
Uncrustify.exe -c amxmodx.cfg -f my_file.sma -p debug.txt
[debug.txt](https://github.com/uncrustify/uncrustify/files/136996/debug.txt)

**Comment by LaraSQP** [comment]
Thank you for the quick reply. Debug output attached.
[debug.txt](https://github.com/uncrustify/uncrustify/files/137197/debug.txt)

**Comment by bengardner** [comment]
An update was posted that fixes this issue.

**Comment by LaraSQP** [comment]
Sorry, missed that update. I'm still having the issue, though. Which one is the option relevant here?

**Comment by bengardner** [comment]
https://github.com/uncrustify/uncrustify/commit/3e272544f71c188fdb6dda88c264cbd4aabf8f14

**Comment by LaraSQP** [comment]
I'm daft. Thanks.
