### ISSUE TITLE
Bug: nl_end_of_file does not add new lines

### ISSUE THREAD

**Issue by radoslav06** [uncrustify/uncrustify#4363]
Version: 0.79.0

Config file:
```
nl_end_of_file=force
```

Input code:
```C
int main()
{
	return 0;
} /* No new line here. */
```

Expected output code:
```C
int main()
{
	return 0;
} /* New line is inserted here. Stripped by markdown formatting. */

```

Actual output code: the same as input (unchanged).

The same is for `add` value. Interestingly the `add` value even remove existing new line at the end of the file (i.e. it transforms expected output code into the input code mentioned above).

`remove` value works as expected.

**Comment by micheleCTDE** [comment]
`nl_end_of_file` together with `nl_end_of_file_min` definitely works. Depending on the editor you use, you may or may not see it if you just open the file but if you analyze the file with an hex editor, you will see the number of new lines as per your config.

**Comment by radoslav06** [comment]
Indeed, I was not aware that `nl_end_of_file_min` is needed. Now it works.
