### ISSUE TITLE
[Feature Request] new option to enforce adding `{` on specific situations

### ISSUE THREAD

**Issue by saccarosium** [uncrustify/uncrustify#4392]
As mentioned #4391 vim is likely to choose uncrustify for formatting.

Currently we have monstrosities like:

```c
if (cond)
{
  cmd;
  cmd;
  cmd;
  cmd;
} else
  cmd;
```

It would be great if there was an option to simply add force add braces on multiline `if/else` statements.

It is ok if I do a PR adding this feature?

**Comment by micheleCTDE** [comment]
Ciao Luca,
there are already options to add missing braces in code where needed. Look through the config, you will find them.
Try [this](https://github.com/uncrustify/uncrustify/blob/master/tests/config/common/tde.cfg) config file for a reference, this will add braces wherever needed.

**Comment by saccarosium** [comment]
Awesome! Grazie for letting me know!
