### ISSUE TITLE
Simple test failed with v0.80.0

### ISSUE THREAD

**Issue by daeho-ro** [uncrustify/uncrustify#4401]
From this PR, 
- https://github.com/Homebrew/homebrew-core/pull/197792

We have a test with a simple c file as follows:

`test.c`
```c
#include <stdio.h>
int main(void) {return 0;}
```

`expected`
```
#include <stdio.h>
int main(void) {
    return 0;
}
```

but got real.
```
#include <stdio.h>
int main(void) {
    return 0;}
```

Is there any changes and intended?

**Comment by micheleCTDE** [comment]
Could you post the config used?
I take it that it worked ok with 0.79.0, right?

**Comment by daeho-ro** [comment]
Yeap, I think so. 
Config from the doc path, `documentation/htdocs/default.cfg`

**Comment by micheleCTDE** [comment]
I will look into it.

**Comment by micheleCTDE** [comment]
The problem seems very limited: it only happens if the brace is the last token of a file and in specific circumstances.
Testing on about ~3200 files with a non default config does not show any regression of sort.

**Comment by micheleCTDE** [comment]
PR #4405 reverts the offending PR and adds the simple test as an additional test.

**Comment by chenrui333** [comment]
@micheleCTDE great to hear, any chance to cut a new release soon? :)

**Comment by micheleCTDE** [comment]
Waiting for Guy (the main maintainer) to feedback on that (see [this](https://github.com/uncrustify/uncrustify/pull/4349#issuecomment-2480470396) comment.

**Comment by micheleCTDE** [comment]
@chenrui333 release 0.80.1 is out :slightly_smiling_face:
