### ISSUE TITLE
Question: difference between config values "add" and "force" ?

### ISSUE THREAD

**Issue by UffeJakobsen** [uncrustify/uncrustify#4411]
Question: difference between config values "add" and "force" ?

What is the difference between config values "add" and "force" ?

I cannot find an explanation for those anywhere...

Thanks

**Comment by micheleCTDE** [comment]
`Force` will enforce the value, so it may add or remove as needed (for example to have `one exact` space).
`Add` will add if needed (for example add one space if missing) but will not modify if you have more than enough.
If the explanation is clear, I guess we can then close this issue?

**Comment by UffeJakobsen** [comment]
Thank you for your swift answer and explanation - it makes sense !!! 

Maybe it would be good to put this explanation into the documentation somewhere ?

**Comment by micheleCTDE** [comment]
It's already there, see [this](https://github.com/uncrustify/uncrustify/blob/master/documentation/control_the_spaces.txt) file. Perhaps a bit hidden :-)

**Comment by UffeJakobsen** [comment]
Thanks - my (Archlinux distribution) package does not include any of that documentation... 

Digging further into the problem it seems that the build/install targets for uncrustify does not seem to have an option that populated the install stage-dir with the documentation...

Anyway thanks for the pointers - I'm closing this issue :+1:  :-)
