### ISSUE TITLE
Tab size is always 8 no matter which value was used

### ISSUE THREAD

**Issue by phuclv90** [uncrustify/uncrustify#4420]
I'm formatting a file that has tab indentation, and want an output that uses 4 spaces for indentation. However no matter which value I use for `input_tab_size` and `output_tab_size`, the output always uses 8 spaces for indentation like this
```
keyValuePair_t *keyValuePair_create(char *key, void *value) {
        keyValuePair_t *keyValuePair = malloc(sizeof(keyValuePair_t));
        if(keyValuePair) {
                keyValuePair->key = key;
                keyValuePair->value = value;
        }
        return keyValuePair;
}
```
Here's the 
[debug.txt](https://github.com/user-attachments/files/17880235/debug.txt)

Config:
```
align_with_tabs=false
indent_with_tabs=0
input_tab_size=4
output_tab_size=4
```

**Comment by micheleCTDE** [comment]
Those options tells uncrustify how to treat tabs when it comes to space counting.
How the file is displayed on you console depends on your tab settings on the console. If your console or editor render a tab as 8 spaces, you will see that.
I tested the example and it seems to work fine, tabs are correctly used and rendered. Also I format about 3200 files with tab size 2, so tabs are definitely working fine.

**Comment by micheleCTDE** [comment]
Ah of course, you need to specify the amount of spaces you want to indent each level. Then spaces/tabs will be used accordingly based on the tab size and indent size defined :-)
I will close this issue then, since it is not an issue.
