### ISSUE TITLE
incorrect extra newline between C++ access modifier and var

### ISSUE THREAD

**Issue by todd-richmond** [uncrustify/uncrustify#444]
Using new sun.cfg from my PR #455, there is an extra newline between public: and the first member variable. I think this may be a conflict between nl_typedef_blk_start/nl_var_dev_blk_start (2) and nl_after_access_spec(1). In this case nl_after_access_spec should take precedence

The following code should remain unchanged

    class foo {
    public:
        typedef int bar;
    
        foo() {}
        ~foo() {}
    
    private:
        int i2;
    
        bool func5(const char *v1, const char *v2, const char *v3)
            { return send(v1, v2, v3); }
    };

returns

    class foo {
    public:

        typedef int bar;

        foo() {}

        ~foo() {}

        void func3() {}
    private:

        int i2;

        bool func5(const char *v1, const char *v2, const char *v3) {
            return send(v1,
                v2, v3);
        }
    };

**Comment by todd-richmond** [comment]
I think this is related to the bug in #447. If func5 is removed with the incorrect break, the other blank lines before var/typedef are removed. However, the missing newline before private: is still missing

**Comment by gmaurel** [comment]
Yes, the option "nl_after_access_spec" takes preference over "nl_typedef_blk_start" and "nl_var_def_blk_start".
I'll complete the description soon.

I don't have a missing line before "private:".

Please, test again with the actual git version.

**Comment by todd-richmond** [comment]
Still broken with latest git version using the same test case above. The key is that the "func5" re-format causes extra new lines to appear elsewhere. If that function is removed, the access modifier values work correctly
