### ISSUE TITLE
incorrect indent on long function definition wrap within C++ class

### ISSUE THREAD

**Issue by todd-richmond** [uncrustify/uncrustify#445]
Using new sun.cfg from my PR #455 a long method declaration breaks without an extra 4 char indent. Certain cases do seem to wrap properly, but this simple one shows the problem

The following code should break with the '0' indented 8 chars, but ends up at 4 chars

    class foo {
    public:
        foo() {}

        int i1;

        bool func2(const char *v1, const char *v2, const char *v3 = NULL, int v4 =
            0);
    };

returns

    class foo {
    public:
        foo() {}

        int i1;

        bool func2(const char *v1, const char *v2, const char *v3 = NULL, int v4 =
        0);
    };

**Comment by todd-richmond** [comment]
I tried the latest tip code which fixes an issue with using tabs for indent, but it did not resolve this issue and in fact dumps core on comments as well as thinks a c++ constructor () is syntax error - will file separate issues

**Comment by bengardner** [comment]
Make sure you do a make clean after pulling new code.


On March 7, 2016, at 8:11 PM, Todd Richmond <notifications@github.com> wrote:

I tried the latest tip code which fixes an issue with using tabs for indent, but it did not resolve this issue and in fact dumps core on comments as well as thinks a c++ constructor () is syntax error - will file separate issues

**Comment by todd-richmond** [comment]
Thx - I found out the rebuild problem shortly before you commented. Core dumps are gone, but it still didn't indent for me

**Comment by todd-richmond** [comment]
this is still happening on the latest code with the test case above - code wraps to 4th column instead of 8th

please re-open
