### ISSUE TITLE
missing newline between C++ function body and access modifier

### ISSUE THREAD

**Issue by todd-richmond** [uncrustify/uncrustify#446]
Using new sun.cfg from my PR #455, there is a missing newline between the end of a function and the next access modifier. Could be a conflict with nl_before_access_spec(2) and settings to not add a blank line between methods in a class definition

The following code should remain unchanged

    class foo {
    public:
        void func3() {
            return;
        }

    private:
        int i2;
    };

**Comment by gmaurel** [comment]
The actual git version works fine.
