### ISSUE TITLE
additional newlines if typedef included in c++ class

### ISSUE THREAD

**Issue by todd-richmond** [uncrustify/uncrustify#448]
Using new sun.cfg from my PR #455, if a typedef is included in a class, then every function gets additional newlines after them even when not configured to

The following code should remain unchanged

    class foo {
    public:
        typedef int bar;

        foo() {}
        ~foo() {}
    };

but instead returns

    class foo {
    public:
        typedef int bar;

        foo() {}

        ~foo() {}
    };

**Comment by gmaurel** [comment]
The new option with value:
nl_before_func_class_def = 1

works as you wished. Unfortunately it takes preference over
nl_typedef_blk_end       = 2
