### ISSUE TITLE
C++ template member variables have extra pre and post newlines

### ISSUE THREAD

**Issue by todd-richmond** [uncrustify/uncrustify#449]
Using new sun.cfg from my PR #455, there is an extra newline before and after a templated member variable

The following code should remain unchanged

    class foo {
    public:
        int i1;
        templateclass<char> tclass;
        int i2;
    };

**Comment by gmaurel** [comment]
You need to use the two options:
nl_var_def_blk_start                      = 1        
nl_var_def_blk_end                        = 1

**Comment by todd-richmond** [comment]
that won't work because setting those values to 1 then eliminates the extra blank line before or after a variable block. Sun standard requires blank lines around variable and typedef blocks with non in-between and this case the templated class is a member variable declaration, not a function

verified failing on the latest code today
