### ISSUE TITLE
How can i fix just one issue

### ISSUE THREAD

**Issue by arslanmkhan** [uncrustify/uncrustify#457]
Hello I am trying to break long lines in shorter lines for c++.
I don't want to do anything else kindly let me know how can i achieve it. I have tried using Universal Indent GUI but its adding lot of new lines and reformatting everything which is not required. Any help would be appreciated

Regards

**Comment by gmaurel** [comment]
Universal Indent GUI is a developer tool, very nice to develop uncrustify, which can be found at
https://github.com/uncrustify/uncrustify
download, compile, use it.
