### ISSUE TITLE
Uncrustify doesn't parse command line correctly

### ISSUE THREAD

**Issue by egarrulo** [uncrustify/uncrustify#458]
Dear Uncrustify maintainers,

this command:

    uncrustify -c /opt/uncrustify/uncrustify-0.62/share/uncrustify/linux.cfg -o Beautified.java FindRoom.java

fails with:

    Cannot specify -o with a multi-file option.
    Try running with -h for usage information

Yet, `uncrustify -h` says:

    Usage:
    uncrustify [options] [files ...]

Therefore the command is correct, isn't it?

I am using Uncrustify 0.62.

Thanks for your attention.

**Comment by addonszz** [comment]
Try:
```
uncrustify -c /opt/uncrustify/uncrustify-0.62/share/uncrustify/linux.cfg -f FindRoom.java -o Beautified.java 
```

**Comment by egarrulo** [comment]
That worked, thanks.  As this is a workaround, I am leaving the issue open.

**Comment by addonszz** [comment]
This is not a workaround, this is how the program works. See:
```
>uncrustify --help
Usage:
uncrustify [options] [files ...]

If no input files are specified, the input is read from stdin
If reading from stdin, you should specify the language using -l
or specify a filename using --assume for automatic language detection.

If -F is used or files are specified on the command line, the output filename is
'prefix/filename' + suffix

When reading from stdin or doing a single file via the '-f' option,
the output is dumped to stdout, unless redirected with -o FILE.

Errors are always dumped to stderr

The '-f' and '-o' options may not be used with '-F', '--replace' or '--no-backup'.
The '--prefix' and '--suffix' options may not be used with '--replace' or '--no-backup'.

Basic Options:
 -c CFG       : use the config file CFG
 -f FILE      : process the single file FILE (output to stdout, use with -o)
 -o FILE      : Redirect stdout to FILE
 -F FILE      : read files to process from FILE, one filename per line (- is stdin)
 --check      : Do not output the new text, instead verify that nothing changes when
                the file(s) are processed.
                The status of every file is printed to stderr.
                The exit code is EXIT_SUCCESS if there were no changes, EXIT_FAILURE otherwise.
 files        : files to process (can be combined with -F)
 --suffix SFX : Append SFX to the output filename. The default is '.uncrustify'
 --prefix PFX : Prepend PFX to the output filename path.
 --replace    : replace source files (creates a backup)
 --no-backup  : replace files, no backup. Useful if files are under source control
 --mtime      : preserve mtime on replaced files
 -l           : language override: C, CPP, D, CS, JAVA, PAWN, OC, OC+, VALA
 -t           : load a file with types (usually not needed)
 -q           : quiet mode - no output on stderr (-L will override)
 --frag       : code fragment, assume the first line is indented correctly
 --assume FN  : Uses the filename FN for automatic language detection if reading
                from stdin unless -l is specified.

Config/Help Options:
 -h -? --help --usage     : print this message and exit
 --version                : print the version and exit
 --show-config            : print out option documentation and exit
 --update-config          : Output a new config file. Use with -o FILE
 --update-config-with-doc : Output a new config file. Use with -o FILE
 --universalindent        : Output a config file for Universal Indent GUI
 --detect                 : detects the config from a source file. Use with '-f FILE'
                            Detection is fairly limited.

Debug Options:
 -p FILE           : dump debug info to a file
 -s                : Show the log severity in the logs
 --decode          : decode remaining args (chunk flags) and exit

As this project use auto-tools, to enable DEBUG mode you can use something like this:
                    ./configure CXXFLAGS="-ggdb3 -O0 -DDEBUG" CXX="ccache g++"

Debug Log Levels available when DEBUG mode is enabled. Use 'a' for all levels.
See the log severities availiable on './src/log_levels.h'. Example: -L0-3,45,56-58
                    -L SEV1, SEV2, ..., SEV_START_RANGE-SEV_END_RANGE, ...

Pragram Usage Examples
cat foo.d | uncrustify -q -c my.cfg -l d
uncrustify -c my.cfg -f foo.d
uncrustify -c my.cfg -f foo.d -L0-2,20-23,51
uncrustify -c my.cfg -f foo.d -o foo.d
uncrustify -c my.cfg foo.d
uncrustify -c my.cfg --replace foo.d
uncrustify -c my.cfg --no-backup foo.d
uncrustify -c my.cfg --prefix=out -F files.txt

Note: Use comments containing ' *INDENT-OFF*' and ' *INDENT-ON*' to disable
      processing of parts of the source file (these can be overridden with
      enable_processing_cmt and disable_processing_cmt.

There are currently 511 options and minimal documentation.
Try UniversalIndentGUI and good luck.
```

**Comment by egarrulo** [comment]
Thanks for the explanation.  However, albeit I agree that Help states that this is not the case, to a hurried reader - like I was - the line:

    uncrustify [options] [files ...]

seems to imply that:

    uncrustify -o beautified.c my-file.c

is correct.  Maybe, a little clarification in Help could prove useful, don't you think?

**Comment by addonszz** [comment]
If you do not provide the pattern, [options] [files ...]
```
If no input files are specified, the input is read from stdin
```
So, to use files, provide [options] [files ...]
```
 -f FILE      : process the single file FILE (output to stdout, use with -o)
```
Using:
```
uncrustify -o beautified.c my-file.c
```
Means to use the default cfg and output your std-in code 'my-file.c' to the file 'beautified.c'.
If will not read the file 'my-file.c', it will interpret 'my-file.c' as a code segment, parse it and output it to the file 'beautified.c'.

**Comment by egarrulo** [comment]
As far as I can see, the command:

    uncrustify -o beautified.c my-file.c

does match the template:

    uncrustify [options] [files ...]

therefore, yes, I am providing an input file.  Anyway, according to your explanation, I can't see how the result should be any different, because I am providing both an input - be it a file or stdin - and an output file.

Actually, the command:

    $ uncrustify -c ~/uncrustify-java.cfg  -o Beautified.java Main.java

does helpfully fail with:

    Cannot specify -o with a multi-file option.
    Try running with -h for usage information

I am only suggesting that `Cannot specify -o with a multi-file option.` would be more complete as `Cannot specify -o with a multi-file option: use -f.`

**Comment by addonszz** [comment]
```
$ uncrustify -c ~/uncrustify-java.cfg  -o Beautified.java Main.java
```
Means that you want to pass 2 files 'Beautified.java' and 'Main.java' for the '-o' option. The program cannot guess what does you are trying to do specifying 2 files outputs.

This fully respect the pattern [options] [files ...]

**Comment by egarrulo** [comment]
If the help says:

     -o FILE      : Redirect stdout to FILE

and that means: `-o` takes one argument, why would Uncrustify think that I am trying to specify two output files?  If that were allowed, then the help would have said:

     -o FILE...     : Redirect stdout to one or more files.

or something like that.

The help for `indent` - a similar utility - showcases a similar pattern.  If you feel like it, you can run a poll and ask people what they would expect from the command:

    uncrustify -o beautified.c my-file.c

Anyway, we are wasting too much time for a small interface detail.  As long as Uncrustify fails instead of misinterpreting arguments, that's acceptable.
