### ISSUE TITLE
Out of date build instructions?

### ISSUE THREAD

**Issue by Gary-Ash** [uncrustify/uncrustify#459]
The build instructions seem out of date. How to use go about a build  on OS X?

**Comment by addonszz** [comment]
I just build and they are fine:
```
$ ./configure
$ make
```
The executable is src/uncrustify. Copy that to your ~/bin/ folder or wherever you want.

Have you installed the Apple developer tools? What happens if you type gcc -v ?

Your configure is successfully finished?

**Comment by Gary-Ash** [comment]
there doesn't seem to be a configure in the repository. I have a complete Xcode 7.21 loaded

**Comment by Gary-Ash** [comment]
the new instructions should be 
./autogen.sh
./configure
make

**Comment by bengardner** [comment]
Good point. We recently removed all generated files from the repository.
"configure" was one of them.
Would you care to submit a pull request with that change?
