### ISSUE TITLE
No continued indentation of wrapped member access

### ISSUE THREAD

**Issue by JohannesZiegenbalg** [uncrustify/uncrustify#463]
There seems to be an issue with the continued indentation of long wrapped member access patterns.
After the formatting with the current uncrustify version my code looks like:
```
void
ClassFoo::foo()
{
     m_foo1->bar().baz().bak()
     .setFoo( ClassFoo:BAR );
}
```
Correctly it should look like the the following snippet:
```
void
ClassFoo::foo()
{
      m_foo1->bar().baz().bak()
              .setFoo( ClassFoo:BAR );
}
```
The same thing happens if the member access is followed by an assignment:
```     
     m_foo1->bar().baz().bak()
     .Foo( ) = 42;
```
In conjunction with a `return` statement or a variable declaration the error doesn't occur.

**Comment by gmaurel** [comment]
You need to use the option:
  indent_member=nn
