### ISSUE TITLE
README missing in 0.62 release

### ISSUE THREAD

**Issue by mcatanzaro** [uncrustify/uncrustify#468]
I noticed when upgrading Fedora's uncrustify to version 0.62 that the release tarball no longer includes a README file since #383, hence it will no longer be included in our doc package. I suspect this change was not intentional? You could choose to distribute the README.md by adding it to EXTRA_DIST in the toplevel Makefile.am. (Files named README get distributed automatically, but not so for README.md.)

**Comment by gmaurel** [comment]
Thanks for it.
