### ISSUE TITLE
Spaces in PAWN macros.

### ISSUE THREAD

**Issue by Crayder** [uncrustify/uncrustify#471]
In PAWN, there can't be spaces in the macros. There can be in the value of the macro, just not the macro. Everything after the first space is considered the value of the macro in PAWN.

So, this, is broken: `#define min(%0,%1) (%0 < %1 ? %0 : %1)`
Since Uncrustify does this: `#define min(% 0, % 1) (%0 < %1 ? %0 : %1)`

**Comment by gmaurel** [comment]
Use three options:
  sp_compare=remove
  sp_cond_question=remove
  sp_cond_colon=remove

**Comment by Crayder** [comment]
No... There should be spaces in this part:

>min(%0,%1)

**Comment by gmaurel** [comment]
Please correct me if necessary.
You want to have:
if (language == PAWN)&&
    code in a define_pp_line) {
    don't put any space
else
   use sp-options
end

**Comment by Crayder** [comment]
Yeah basically, that should do it. That's just how it has to be to be correct.

**Comment by gmaurel** [comment]
which sp-options should NOT work in a #define line?
Please push a complete source and what you expect to get.

**Comment by Crayder** [comment]
No matter what sp-options are enabled/disabled, there cannot be spaces in the macro part. There can be spaces in the replacement. There can also be line breaks in the replacement, but that's beside the point.

Given any of these:

    #define bleh(%0,%1) duh(%1,%0)
    #define bleh(%0,%1)\
        duh(%1,%0)
    #define bleh(%0,%1) duh(%1, %0)
    #define bleh(%0,%1) duh( %1, %0 )
    #define bleh(%0,%1) \
        duh(%1,%0)
    #define bleh(%0,%1) \
        duh(%1, %0)

There should just never be a space in the `bleh` part.

There also can't be spaces between the variable characters. That is, `%0` can't be turned into `% 0`.

**Comment by gmaurel** [comment]
I take this request in the todo list.

**Comment by bengardner** [comment]
This has been addressed. Please retest with the latest from git.
See tests/input/pawn/preproc.pawn and the commits from Jan 1, 2016.
a8f4771b2e4ad48d91f14d2c2ceba228c5f93c9d

Reopen if there is still an issue.
