### ISSUE TITLE
Semi-colons in arrays in PAWN.

### ISSUE THREAD

**Issue by Crayder** [uncrustify/uncrustify#472]
For some reason, this:

	static Float:grad2lut[8][2] = {
	    { -1.0, -1.0 }, { 1.0, 0.0 }, { -1.0, 0.0 }, { 1.0, 1.0 },
	    { -1.0, 1.0 }, { 0.0, -1.0 }, { 0.0, 1.0 }, { 1.0, -1.0 }
	};

Is turned into this:

	static Float:grad2lut[8][2] = {
	    { -1.0, -1.0 };, { 1.0, 0.0 };, { -1.0, 0.0 };, { 1.0, 1.0 };,
	    { -1.0, 1.0 };, { 0.0, -1.0 };, { 0.0, 1.0 };, { 1.0, -1.0 };
	};

Obviously this isn't right, in any language that I know.

**Comment by gmaurel** [comment]
the actual git version works fine.
