### ISSUE TITLE
`indent_first_bool_expr` and `indent_bool_paren` do not use tabs

### ISSUE THREAD

**Issue by itavero** [uncrustify/uncrustify#475]
We have the tab size set to `3` and have configured uncrustify so it should use tabs to indent code.
However, when indenting boolean expressions, Uncrustify decides to use spaces instead of tabs, causing the alignment to fail.

Some parts of the config:
````
input_tab_size=3
output_tab_size=3
indent_columns=output_tab_size
indent_bool_paren=true
indent_first_bool_expr=true
````

So this code would align nicely with tab size `3`.
````c
static void SomeExampleMethod(UINT8 a, UINT8 b) {
	if(	(a > 3)
		&&	(a < b)) {
		// do something
	}
}
````

However, uncrustify decides that it should use spaces for indents, so it screws up the alignment:
````c
static void SomeExampleMethod(UINT8 a, UINT8 b) {
	if(   (a > 3)
	  && (a < b) ) {
		// do something
	}
}
````

**Comment by gmaurel** [comment]
I need your full config file and the version you are using.

**Comment by itavero** [comment]
I believe this is the last configuration I tried: https://gist.github.com/itavero/61511b2ec3228470d32833f165952aa5

**Comment by gmaurel** [comment]
works for me, see i.txt
[i.txt](https://github.com/uncrustify/uncrustify/files/276030/i.txt)

**Comment by bengardner** [comment]
Might have had `indent_with_tabs=1` in a previous version of the config file.
Closing the issue, as @gmaurel has indicated that it works with the current config file.
