### ISSUE TITLE
uncrustify incorrectly handles Q_GADGET 

### ISSUE THREAD

**Issue by evsh** [uncrustify/uncrustify#476]
Uncrustify transforms the following input 
```C++
class A 
{
    Q_GADGET
    Q_ENUMS(E)
...
};
```
into
```C++
class A 
{
    Q_GADGET
                              Q_ENUMS(E)
...
};
```
With the same fragment and `Q_GADGET` replaced with  `Q_OBJECT` it works fine.  The strange thing is that `set Q_OBJECT Q_GADGET` in the config does not change anything.
Compiled from the master branch.

**Comment by gmaurel** [comment]
add Q_GADGET to the keywords.
Please test it.

**Comment by evsh** [comment]
Now it produces
```C++
class A
{
    Q_GADGET
        Q_ENUMS(E)
```

Q_ENUMS indent is one level deeper.

**Comment by evsh** [comment]
Why does the `set Q_OBJECT Q_GADGET` not work? Shall I write something else to make `Q_GADGET == Q_OBJECT`?

**Comment by gmaurel** [comment]
Please push your config file.

**Comment by evsh** [comment]
[Here](https://github.com/qbittorrent/qBittorrent/blob/master/uncrustify.cfg) it is, please.

**Comment by gmaurel** [comment]
my output is:
Parsing: evsh.cpp as language CPP
class A
{
    Q_GADGET
    Q_ENUMS(E)
    ...
};

Could you please use:
  uncrustify -c evsh.cfg -f evsh.cpp -p a.p
and push the a.p file?

**Comment by evsh** [comment]
I beg your pardon, was building from an incorrect branch. Uncristify works correctly, thank you!
