### ISSUE TITLE
Objective-C Feature request: Blocks opening curly bracket support similar to nl_fdef_brace

### ISSUE THREAD

**Issue by andrassomogyi** [uncrustify/uncrustify#477]
It would be really nice to have a feature similar to *nl_fdef_brace* and *nl_if_brace*...
```objective-c
    [dataArray enumerateObjectsUsingBlock:^(DataType *data, NSUInteger idx, BOOL *stop)
     {
         // Do stuff!
     }];
```
...to place the opening curly bracket with or without newline.
```objective-c    
    [dataArray enumerateObjectsUsingBlock:^(DataType *data, NSUInteger idx, BOOL *stop) {
         // Do stuff!
     }];
```
Thanks!

**Comment by gmaurel** [comment]
Which language is it?
May I ask for a proposal for the new option?

**Comment by andrassomogyi** [comment]
Hi @gmaurel 

The language is Objective-C. 

Currently, you can specify where opening brackets should be for methods, but you can't do so for Objective-C blocks.

So even though your methods look like this:

```objc
- (void)foo
{
// stuff
}
```

Your blocks will look like this:

```objc
[dataArray enumerateObjectsUsingBlock:^(DataType *data, NSUInteger idx, BOOL *stop) {
// Do stuff!
}];
```

I would propose 
```
# Add or remove newline between Objective-C block signature and '{'
nl_objc_block_brace                             = ignore   # ignore/add/remove/force
```

**Comment by gmaurel** [comment]
The proposal #477 is implemented.
It would be really nice to have a feature similar to nl_fdef_brace and nl_if_brace...
    [dataArray enumerateObjectsUsingBlock:^(dataType *data, NSUInteger idx, BOOL *stop)
     {
         // Do stuff!
     }];
...to place the opening curly bracket with or without newline.

The new option is:
  nl_oc_block_brace
