### ISSUE TITLE
Regression: Qt Macro SIGNAL or SLOT causes spacing issues around braces and commas 

### ISSUE THREAD

**Issue by CDanU** [uncrustify/uncrustify#481]
Input
```
namespace
{
    /*[...manually removed unnecessary comment...]*/
    const static std::map< Form, QString > MapFormEnumString = {
        { Viereck,"Viereck" },
        { Kreis,  "Kreis"   }
    };
}
const QPoint MainWindow::ObjMaxPos = genMaxPos(SceneSize,ObjSize);
MainWindow::MainWindow( QWidget* parent ) : QMainWindow( parent )
{
    connect( timer, SIGNAL( timeout() ), this, SLOT( timeoutImage() ) );
}
void MainWindow::createView()
{
    for(auto mapEntry : MapFormEnumString)
    {
selectObjectForm->addItem( mapEntry.second, mapEntry.first);
    }
}
```
__________________________________________________________

Ok output 4abfb665092e4ef238be42b71f308b43ecccb9b2
```
namespace
{
    /*[...manually removed unnecessary comment...]*/
    const static std::map< Form, QString > MapFormEnumString = {
        { Viereck, "Viereck" },
        { Kreis,   "Kreis"   }
    };
}
const QPoint MainWindow::ObjMaxPos = genMaxPos( SceneSize, ObjSize );
MainWindow::MainWindow( QWidget* parent ) :
    QMainWindow( parent )
{
    connect( timer, SIGNAL( timeout() ), this, SLOT( timeoutImage() ) );
}
void MainWindow::createView()
{
    for( auto mapEntry : MapFormEnumString )
    {
        selectObjectForm->addItem( mapEntry.second, mapEntry.first );
    }
}
```
[_debug.txt_](https://gist.github.com/CDanU/84b47d6b8a5485b93fd9ed9e583bb351)
__________________________________________________________

Buggy output 573febe996ad22841b240c2357294b75cd4ad8c6
```
namespace
{
    /*[...manually removed unnecessary comment...]*/
    const static std::map< Form, QString > MapFormEnumString = {
        { Viereck,"Viereck"  },
        { Kreis,  "Kreis"    }
    };
}
const QPoint MainWindow::ObjMaxPos = genMaxPos( SceneSize, ObjSize );
MainWindow::MainWindow( QWidget* parent ) :
    QMainWindow( parent )
{
    connect( timer, SIGNAL( timeout() ),this,SLOT( timeoutImage() ) );
}
void MainWindow::createView()
{
    for( auto mapEntry : MapFormEnumString )
    {
        selectObjectForm->addItem(mapEntry.second,mapEntry.first);
    }
}
```
[_debug.txt_](https://gist.github.com/CDanU/55babd6054de9df18459a5a6ac5ed012)
__________________________________________________________

Notice the missing/wrong spaces inside the parentheses of addItem, connect and the MapFormEnumString Map.

This only occurs if the
```
connect( timer, SIGNAL( timeout() ),this,SLOT( timeoutImage() ) );
```
line is available, affecting everything before and after it.
The current HEAD f8f7c9ff42ddac1c2722ec37aa1c21c59a7524c0 has the same problem.

**Comment by gmaurel** [comment]
Correct.
BUT, you are using the option:
  sp_balance_nested_parens = true

which adds spaces after ( and before ).
Now uncrustify takes care of that and remove the spaces
for the QT macros SIGNAL and SLOT.
PLease the git version 81f994da564b228bfbdf984e1b5527d2cda289ce at 2016-05-21

**Comment by CDanU** [comment]
I have tested the changes and all problems are gone. Thanks!

I am not sure though about the missing spaces after ( and before ) in SIGNAL and SLOT. 
```
connect( timer, SIGNAL(timeout()), this, SLOT(timeoutImage()) );
```
In my previous post I had not defined set sp_inside_paren and sp_paren_paren. The option sp_inside_paren defaulted to ignore, sp_paren_paren on the other hand to remove ( I think this also should default to ignore ). 
Defining sp_inside_paren = force and sp_paren_paren = ignore also does not produce spaces inside the parentheses. Maybe that is related to sp_balance_nested_parens.

Could you tell me in the mean time what sp_balance_nested_parens is actually doing ? The description "Whether to balance spaces inside nested parens" is not really helpful.
