### ISSUE TITLE
JAVA - Class declaration continuation indent

### ISSUE THREAD

**Issue by kaiser101** [uncrustify/uncrustify#486]
According to this(http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-136091.html) class continuation indent should be 8 spaces. Currently it only indents it by 4 spaces.

**Comment by gmaurel** [comment]
It is your choose to use another value:
  indent_columns=8

**Comment by kaiser101** [comment]
Not quite. It is controlled by indent_continue, which I have set to 8. Normal indent should be 4 spaces.
It is working for all except the class declaration.
