### ISSUE TITLE
Reopening $486

### ISSUE THREAD

**Issue by kaiser101** [uncrustify/uncrustify#487]
According to this(http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-136091.html) class continuation indent should be 8 spaces. Currently it only indents it by 4 spaces.

@gmaurel
gmaurel commented an hour ago
It is your choose to use another value:
indent_columns=8

@gmaurel gmaurel closed this an hour ago

Not quite, Guy. It is controlled by indent_continue, which I have set to 8. Normal indent should be 4 spaces.
It is working for all except the class declaration.

**Comment by gmaurel** [comment]
what about using:
  indent_class=true

**Comment by kaiser101** [comment]
That I believe is for indenting the entire contents, i.e. body of the class. In my case, that is set to true, which indents the body by the number of indent columns which is set to 4 using indent_columns. What I need is if the class declaration exceeds code_width it continues on the next line. The next line should be indented by 8 space instead of the existing 4. It is working for method declarations, so that should help in the fix.

**Comment by gmaurel** [comment]
Please push an example source and the output you expected to get.

**Comment by kaiser101** [comment]
[KeyValueItemWriter.zip](https://github.com/uncrustify/uncrustify/files/281056/KeyValueItemWriter.zip)

Check lines 29 and 30. Thats the class declaration. The indentation on line number 30 is 4 spaces. It should be 8 spaces.

I think what is happening is, indent_continue is not being effected for class declarations.

**Comment by gmaurel** [comment]
It works for me with the actual git at a094c39ec0180a3cc31921208bf350df65fca127
with the configuration:
indent_columns=8
indent_with_tabs=0
indent_class=true
