### ISSUE TITLE
JAVA - Space after variable type and variable name

### ISSUE THREAD

**Issue by kaiser101** [uncrustify/uncrustify#488]
There should be an option to control spaces after a variable type and the variable name. Currently it does not remove extra spaces between the type and name.

	protected Converter<V, K>           itemKeyMapper;

Note the extra spaces after Converter<V, K> and itemKeyMapper;

**Comment by CDanU** [comment]
I believe with sp_after_type you can adjust what you want. force: 1 space, add: >= 1 space

**Comment by kaiser101** [comment]
I tried it, but does not work. It inserts spaces if there are none, but does not remove extra spaces.

**Comment by gmaurel** [comment]
Please send a complete source and your config file.

**Comment by kaiser101** [comment]
Attached the source code and config. Please refer to line 31 of the java code to see the issue.

Thanks.
[488.zip](https://github.com/uncrustify/uncrustify/files/276243/488.zip)

**Comment by gmaurel** [comment]
Please use the option:
  sp_angle_word = force
