### ISSUE TITLE
Test 30011 crashes

### ISSUE THREAD

**Issue by jibsen** [uncrustify/uncrustify#495]
Test 30011 crashes here on Windows due to dereferencing `pc` while `NULL` in indent.cpp:403.

**Comment by gmaurel** [comment]
I need some more details with the actual git version. Thanks

**Comment by jibsen** [comment]
This is with the current git version.

The reason it is crashing on Windows and not on Linux, is because `src/windows_compat.h` defines `NO_MACRO_VARARG`, which means `logger.h:101` defines `LOG_FMT` without the log level test, which in turn means the parameters of the call at `indent.cpp:403` are evaluated, which crashes the program if `pc` is `NULL`.

If you run test 30011 on Linux with `-L 99`, or compile with `-DNO_MACRO_VARARG`, it crashes there as well.

**Comment by gmaurel** [comment]
Correct! Thanks for debugging.
It is now fixed. git at 31e441f..d68ea3f
