### ISSUE TITLE
objective-c multiline array literals and indent_continue

### ISSUE THREAD

**Issue by pankkor** [uncrustify/uncrustify#497]
With any value in ```indent_continue``` obj-c array literals got formatted like this:
```
array = @[@1,
@2,
@3,
@4];
```
instad of like this:
```
array = @[@1,
          @2,
          @3,
          @4];
```
Dictionary literals are formatted the second way as expected.

**Comment by gmaurel** [comment]
I am missing the config file

**Comment by Krizai** [comment]
@gmaurel I believe you can close this one.

**Comment by gmaurel** [comment]
fine

**Comment by pankkor** [comment]
@gmaurel you can use this one
{code}
indent_continue = 1
{code}

**Comment by Krizai** [comment]
@pankkor Please test after my fix. Works fine for my configs including indent_continue
