### ISSUE TITLE
How can I remove multi-blankline in method body?

### ISSUE THREAD

**Issue by Lingyj** [uncrustify/uncrustify#498]
Object-C code as this:

		- (void)initFrame
		{
		    self.view.backgroundColor = [GB_DeviceColor getContentGray];
		    UIView *topBgView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, [GB_DeviceUtils getScreenWidth], 64)];
		    topBgView.backgroundColor = [UIColor whiteColor];
		    [self.view addSubview:topBgView];
		
		    UIView *iv1 = [[UIView alloc] initWithFrame:CGRectMake(0, 62, [GB_DeviceUtils getScreenWidth], 2)];
		    iv1.backgroundColor = [GB_DeviceColor getContentGreen];
		    [self.view addSubview:iv1];
		
		    UILabel *titleLabel = [[UILabel alloc]init];
		    titleLabel.frame = CGRectMake(60, 20 + 13, [GB_DeviceUtils getScreenWidth] - 120, 18);
		    titleLabel.font = [UIFont systemFontOfSize:16.0f];
		    [titleLabel setTextColor:[UIColor blackColor]];
		    titleLabel.textAlignment = NSTextAlignmentCenter;
		    [self.view addSubview:titleLabel];
		
		    UIButton *btn = [UIButton buttonWithType:UIButtonTypeCustom];
		    [btn setImage:[GB_DeviceTool imagPNGPathName:@"CourseLeft"] forState:UIControlStateNormal];
		    btn.frame = CGRectMake(0, 20, 44, 44);
		    [btn addTarget:self action:@selector(c_back) forControlEvents:UIControlEventTouchUpInside];
		    [self.view addSubview:btn];
		
		
		
		    UITableView *contentTV = [[UITableView alloc]initWithFrame:CGRectMake(0, 64, [GB_DeviceUtils getScreenWidth], [GB_DeviceUtils getScreenHeight] - 20 - 44)];
		    contentTV.dataSource = self;
		    contentTV.delegate = self;
		    contentTV.backgroundColor = [UIColor clearColor];
		    contentTV.tableFooterView = [[UIView alloc] init];
		    //    [contentTV setSeparatorInset:UIEdgeInsetsZero];
		    [self.view addSubview:contentTV];
		    self.contentTV = contentTV;
		
		    self.maskView = [[UIView alloc] initWithFrame:CGRectMake(0, 88, [GB_DeviceUtils getScreenWidth], [GB_DeviceUtils getScreenHeight])];
		    self.maskView.backgroundColor = [UIColor colorWithRed:153 / 255.f green:153 / 255.f blue:153 / 255.f alpha:.3];
		})

**Comment by gmaurel** [comment]
Use the option:
  nl_max = 2
