### ISSUE TITLE
Broken compilation of c/cpp sources which contains VS inline assembler with constants like octal literals

### ISSUE THREAD

**Issue by bloodthirsty89** [uncrustify/uncrustify#503]
Example
Before uncrustify:
_asm
{
    mov al, 0B8h
}

After uncrustify:
_asm
{
    mov al, 0B 8h
}

Hex constant '0B8h' are split to '0B 8h' and that causes break down.
Any other code that contains literals like '018' is also incorrectly formatted ('018' splits to '01 8').

**Comment by gmaurel** [comment]
Can you send me a collection of the possible strings and what they are?
Yet uncrustify makes two "NUMBER" which is not correct.

**Comment by bloodthirsty89** [comment]
> Can you send me a collection of the possible strings and what they are?

1) Consider any hexadecimal number that: 
- starts with digit 0,
- contains digit 8 or 9,
- has the suffix 'h' in the end (MS specific).
2) Also, consider any instances of invalid octal numbers (018, 039, 091,.. - any that contains 8 or 9).

Apparently, the uncrustify tries to correct wrong octal number. And the hexadecimal constants (from case 1) are considered like octal by mistake.

**Comment by mihaipopescu** [comment]
This is quite bad. Do you have any specific option in your config file (like the recent `align_asm_colon`) ?

**Comment by bloodthirsty89** [comment]
No, I use default config

**Comment by bloodthirsty89** [comment]
The problem is not related with asm only. It's related with how uncrustify handle octal constants (and hexadecimal constants with leading zero). To see that try to create demo.cpp with 0B8 only (without quotes). Then run uncrustify on that file with any configs (I use defaults.cfg). See what happens. I got 0B 8 in result file.

**Comment by gmaurel** [comment]
We have two problems.
1. the __asm keyword, see https://msdn.microsoft.com/en-us/en-en/library/45yd4tzz.aspx,
will be consider by the next bugfix. It will let the lines as they are.
2. The constant problem.
I am working on 1. just now.
