### ISSUE TITLE
Space in ternary conditional operator without first parameter

### ISSUE THREAD

**Issue by pankkor** [uncrustify/uncrustify#507]
What I want to achieve is that ternary conditional operator without a first parameter in this example:
```
NSDictionary *p = payload ?: @{};
```
is formatted like this ```?:``` instead of like this ```? :```.
```sp_cond_colon``` and ```sp_cond_question``` don't give me anything. Even setting both to ```ignore``` still formats it like this ```? : ```.

**Comment by nmccann** [comment]
I think what you want is the following:

```
# In the abbreviated ternary form (a ?: b), add/remove space between ? and :.'. Overrides all other sp_cond_* options.
sp_cond_ternary_short                     = add   # ignore/add/remove/force
```

**Comment by pankkor** [comment]
@nmccann it works, thank you!
