### ISSUE TITLE
Blank line after namespace opening

### ISSUE THREAD

**Issue by jpetereit** [uncrustify/uncrustify#508]
It would be great to have an option that controls the number of blank lines after the opening brace of a namespace and before the closing namespace brace such that

```cpp
namespace ns
{
class A
{
    // a lot of code
};
} // namespace ns
```

would become

```cpp
namespace ns
{

class A
{
    // a lot of code
};

} // namespace ns
```

Maybe, whether to put a blank line or not could be made configurable on the basis of the length of the code block in the namespace, i.e., only insert a blank line if namespace body is longer than X lines.

It would be even greater to have an additional option to control the number of blank lines between *nested* namespaces so that it is possible to achieve the following output formatting:

```cpp
namespace ns
{
namespace nested_ns
{

class A
{
    // a lot of code
};

} // namespace nested_ns
} // namespace ns
```

(no blank line between two namespace deklarations, one blank line between namespace content and braces.)

**Comment by gmaurel** [comment]
uncrustify doesn't have such an option.

**Comment by jpetereit** [comment]
I know. It was a feature request :)

**Comment by mihaipopescu** [comment]
Patches are more than welcomed !
