### ISSUE TITLE
Error: Unexpected '>' for 'PAREN_OPEN', which was on line

### ISSUE THREAD

**Issue by clach04** [uncrustify/uncrustify#509]
c:\tmp>C:\Users\Ingres\Downloads\uncrustify_v063.exe -v
    uncrustify 0.63.0-g44ce0f1

    c:\tmp>wget http://uncrustify.sourceforge.net/default.cfg

    c:\tmp>C:\Users\Ingres\Downloads\uncrustify_v063.exe -c uncrustify_v063.cfg  bug_form3.h
    Output suffix: .uncrustify
    Parsing: bug_form3.h as language CPP
    bug_form3.h:10 Error: Unexpected '>' for 'PAREN_OPEN', which was on line 10

Where:

    c:\tmp>type bug_form3.h
    #if defined(_MSC_VER)
        #if _MSC_VER < 1300
            #define __func__ "unknown function"
        #else
            #define __func__ __FUNCTION__
        #endif /* _MSC_VER < 1300 */
    #endif /* defined(_MSC_VER) */

    #define bug_demo        (1 > 2) ? (1 : 2)

* If the #if directives are removed, no errors.
* this appears to be benign, the fixed generated code is fine - the "error" is misleading

**Comment by clach04** [comment]
Attached [bug.zip](https://github.com/uncrustify/uncrustify/files/305575/bug.zip) (git but won't allow .h nor .cfg files), contains:

    249 bug_form3.h
 82,340 uncrustify_v063.cfg

**Comment by mihaipopescu** [comment]
Your issue is related with the change 12d474f44f6caa9c07c8cfbb7ef7371bc2d75fe6 introduced by @gmaurel after which compare operators from #if statements are detected as CT_ANGLE_OPEN/CLOSE tokens. We have the same issue on our side.

**Comment by gmaurel** [comment]
Thanks for it.
The issue #509 is fixed.

**Comment by mihaipopescu** [comment]
@gmaurel maybe I wasn't clear. The specified change introduced this regression.

**Comment by clach04** [comment]
Looks like this is resolved by commit ad23416e344edd73e82f40391fe2dc0165946530 - not sure why GitHub isn't linking it?
