### ISSUE TITLE
Uncrustify changes file if run a second time

### ISSUE THREAD

**Issue by 4hopp** [uncrustify/uncrustify#510]
Uncrustify is inconsistent if run multiple times. Minimal example:

Original file (using tabs):
```c++
enum A {
	value1,		// Asdf
	othervalue2,		// Bsdf
	value3,		// Csdf
	value4		// Dsdf
};
```

After the first run:
```c++
enum A {
	value1,	// Asdf
	othervalue2,	// Bsdf
	value3,	// Csdf
	value4	// Dsdf
};
```

After the second run:
```c++
enum A {
	value1,	// Asdf
	othervalue2,// Bsdf
	value3,	// Csdf
	value4	// Dsdf
};
```

For the effective use of uncrustify with productive tools (such as git filters) uncrustify should guarantee that files do not change if uncrustify is run a second time.

([Uncrustify config used for the example](https://github.com/uncrustify/uncrustify/files/309054/uncrustify_config.txt))

**Comment by gmaurel** [comment]
It works for me.
Which version are you using?
Please push as attachment your input file.

**Comment by 4hopp** [comment]
That's strange. I can reproduce this with several versions of uncrustify:

- Current version in "master"
- 0.59, 0.60, 0.63

[input.cpp](https://github.com/uncrustify/uncrustify/files/334264/input.txt)
[uncrustify.cfg](https://github.com/uncrustify/uncrustify/files/309054/uncrustify_config.txt)

Executed commands:
```bash
uncrustify -c uncrustify.cfg -o v2.cpp -f input.cpp
uncrustify -c uncrustify.cfg -o v3.cpp -f v2.cpp
diff v2.cpp v3.cpp # Compare both files  ...
```

Expected result: v2.cpp and v3.cpp should be identical
Actual result: v2.cpp and v3.cpp differ

**Comment by sjakub** [comment]
I can reproducesee that behaviour...
Could you try to figure out which option in the config file causes that?

**Comment by 4hopp** [comment]
Okay, this happens when `input_tab_size` is set to a different value than `output_tab_size`; when both options are set to the same value everything is fine.

Seems like this is even expected behaviour after all and I just did not manage to set up uncrustify correctly. Thanks for helping out!
