### ISSUE TITLE
Error: Unexpected ')' for 'ANGLE_OPEN'

### ISSUE THREAD

**Issue by sjakub** [uncrustify/uncrustify#513]
Hi,

I am having an issue with uncrustify 0.63, version 0.62 works fine.

This is what I did:
$ ./uncrustify62 --update-config > default_62.cfg
$ ./uncrustify62 -c default_62.cfg --no-backup test.h
Parsing: test.h as language CPP
$ ./uncrustify63 -c default_62.cfg --no-backup test.h
Parsing: test.h as language CPP
test.h:6 Error: Unexpected ')' for 'ANGLE_OPEN', which was on line 6
test.h:7 Error: Unexpected '}' for 'ANGLE_OPEN', which was on line 6
test.h:8 Error: Unexpected '}' for 'ANGLE_OPEN', which was on line 6

I am attaching the test file (as a .txt file)
[test.txt](https://github.com/uncrustify/uncrustify/files/314790/test.txt)

**Comment by mihaipopescu** [comment]
Your issue may be related with #509. See if my comment helps.

**Comment by sjakub** [comment]
Thanks for letting me know :)

Yeah, it looks like it's the same thing...
I will have a look to see if I can figure out a way to fix it :)

Also, even something like this triggers it:
`#define CHECK_STATE foo ( a < c )`

**Comment by sjakub** [comment]
It looks like this was a duplicate of #509. This issue was also fixed by commit ad23416.
