### ISSUE TITLE
What are columns ?

### ISSUE THREAD

**Issue by BigfootN** [uncrustify/uncrustify#517]
Hello,

I am stuck with an option I can't understand:

> indent_columns                            Number
  The number of columns to indent per level.
Usually 2, 3, 4, or 8.

So, my question is, what do you mean by columns, and more importantly what are their size ?

Also, what do you mean by a level ? If I understand correctly, if I write this:

```c
int main(){
    for(...)
        if(...)
}
```

Is `if` a level further from `for` ?

Thank you very much in advance :)

P.S: Is there a place where I can get a more detailed explanation from the options, than from the `config.txt` file ?

**Comment by gmaurel** [comment]
Please try:
uncrustify --update-config-with-doc
uncrustify --universalindent

Have a look to a not complete doc. Some of the options are present.
documentation/htdocs/options.html

**Comment by BigfootN** [comment]
Thank you very much :)
