### ISSUE TITLE
nl_func_type_name removes lines between public: label and destructor

### ISSUE THREAD

**Issue by rtsuk** [uncrustify/uncrustify#52]
If I have the following class

```c++
class Test
{
public:
  ~Test();
};
```

and my config file is the default with one change

```
nl_func_type_name                        = remove   # ignore/add/remove/force
```

the code ends up formatted as

```c++

class Test
{
public: ~Test();
};
```

it seems that uncrustify is confusing the access label for a return value.

**Comment by CJCombrink** [comment]
Uusing uncrustify 0.62 I also have this issue with classes that does not have constructors specified, only a destructor. 
If a add a constructor before the destructor it indents as expected.

**Comment by budokaiman** [comment]
I just upgraded to 0.63 and this issue is no longer present, it's even correcting any instances of the broken
`public: ~Test();`

to
`public:
    ~Test();`

**Comment by gmaurel** [comment]
The last comments are correct. The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
