### ISSUE TITLE
Space between '> >' in templates gets eaten inside macros

### ISSUE THREAD

**Issue by sjakub** [uncrustify/uncrustify#523]
Current git version, using default config.
This input:
```
#define MACRO(templ_type) template <typename T> class Abc<templ_type<T> > { }
template<typename T> class Foo<Bar<T> > { };
```
Is converted to this:
```
#define MACRO(templ_type) template <typename T> class Abc<templ_type<T>> { }
template<typename T> class Foo<Bar<T> > { };
```

It looks like in the actual template, the space between '> >' got preserved, which is correct given the default settings. However, when the same thing happens inside a template, that space gets removed...

With macros like that I also saw that '>>' sometimes gets moved to the next line,
when pos_arith is set to lead. Which means it's not recognized correctly as a part of a template.

**Comment by sjakub** [comment]
It looks like there is a lot of issues related to macros....
Is there a way to make it not format macros at all?

**Comment by sjakub** [comment]
And it looks like this has been broken by the same change 12d474f introduced by @gmaurel that broke #509 ... undoing changes from 12d474f fixes this bug.

**Comment by sjakub** [comment]
I created a pull request that reverts the original behaviour from before the 12d474f
and fixes the original bug in a different way, that doesn't cause issues with templates.

**Comment by gmaurel** [comment]
Please test the actual git version and report.
Thanks for helping.

**Comment by sjakub** [comment]
Just tested it: It works as expected using the current master.
