### ISSUE TITLE
esqlc (embedded SQL C) variable null indicator markers have incorrect spacing

### ISSUE THREAD

**Issue by clach04** [uncrustify/uncrustify#526]
Following code:

    EXEC SQL BEGIN DECLARE SECTION;
    static char            *tbuf;
    static short            *null_indicator;
    EXEC SQL END DECLARE SECTION;

    void myfunc1()
    {
        EXEC SQL SELECT col1 INTO :tbuf:null_indicator;
    }

When ran through uncrustify 0.63.0-g44ce0f1 result in:

    EXEC SQL SELECT col1 INTO :tbuf :null_indicator;

Note the space before the second colon. I'm not sure there is an option to control this behavior.

**Comment by gmaurel** [comment]
No, we don't have such an option.
