### ISSUE TITLE
esqlc (embedded SQL C) variable assignment odd spacing

### ISSUE THREAD

**Issue by clach04** [uncrustify/uncrustify#527]
The following esqlc, this is actually Oracle ProC syntax for a database function/procedure (smallest test case I can create):

```
void myfunc1()
{
    EXEC SQL create or replace
        function my_func (in_str IN varchar2)
        return date
        IS
        x date;
    BEGIN
    IF in_str IS NULL THEN
        x:  = NULL;
    ELSIF substr(in_str, 5,  1) = '-' THEN
    x := to_date(in_str, 'YYYY-MM-DD HH24:MI:SS');
    END IF;
    return x;
    END my_func;
    END-EXEC;
}
```

When ran through uncrustify 0.63.0-g44ce0f1 results in:

```
void myfunc1()
{
    EXEC SQL create or replace
        function my_func (in_str IN varchar2)
        return date
        IS
        x date;
    BEGIN
    IF in_str IS NULL THEN
x:  = NULL;
    ELSIF substr(in_str, 5,  1) = '-' THEN
x:                                = to_date(in_str, 'YYYY-MM-DD HH24:MI:SS');
    END IF;
    return x;
    END my_func;
    END-EXEC;
}
```

NOTE the second `x := to_date....` where lots of spaces are present between the colon and the equals sign. `:=` is an assignment and should be preserved as-is.

There are issues with leading spaces being removed BUT the critical issue is the assignment operator spacing.

**Comment by bengardner** [comment]
The root problem here is that the SQL is being parsed as C.
Perhaps the whole SQL block should be parsed out as one chunk and modifier by a (new) custom SQL formatter.

**Comment by gmaurel** [comment]
I need your configuration file.

**Comment by clach04** [comment]
@gmaurel sorry for the delay, only just saw this!

[issue_527.cfg.txt](https://github.com/uncrustify/uncrustify/files/697596/issue_527.cfg.txt)

[issue_527.sc.txt](https://github.com/uncrustify/uncrustify/files/697600/issue_527.sc.txt)

    C:\uncrustify-0.63.0-g44ce0f1-win32>uncrustify -c issue_527.cfg issue_527.sc

**Comment by guy-maurel** [comment]
I can reproduce.

**Comment by guy-maurel** [comment]
#732 is a bugfix proposal

**Comment by gmaurel** [comment]
Fixed
