### ISSUE TITLE
c++ comments to the right of code aligned with tabs regardless of "align_with_tabs"

### ISSUE THREAD

**Issue by dfberger** [uncrustify/uncrustify#528]
with

indent_with_tabs = 2
indent_cmt_with_tabs = true
align_with_tabs = false

code like this:

`int i = 5; // comment`

gets turned into

`int i = 5;\t// comment`

I'm not sure this is the right fix (in particular the comparison between column and brace_col), but after looking at the comment output code, I landed on this, which worked for my test case but hasn't been tested extensively yet.

```
$ git diff src/output.cpp
diff --git a/src/output.cpp b/src/output.cpp
index d0cc181..2387a2a 100644
--- a/src/output.cpp
+++ b/src/output.cpp
@@ -199,7 +199,8 @@ static void output_to_column(int column, bool allow_tabs)

 /**
  * Output a comment to the column using indent_with_tabs and
- * indent_cmt_with_tabs as the rules.
+ * indent_cmt_with_tabs as the rules, unless we're aligning
+ * in which case use the align_with_tabs
  * base_col is the indent of the first line of the comment.
  * On the first line, column == base_col.
  * On subsequnet lines, column >= base_col.
@@ -213,8 +214,9 @@ static void cmt_output_indent(int brace_col, int base_col, int column)
    int iwt;
    int tab_col;

-   iwt = cpd.settings[UO_indent_cmt_with_tabs].b ? 2 :
-         (cpd.settings[UO_indent_with_tabs].n ? 1 : 0);
+   iwt = (column == brace_col ? (cpd.settings[UO_indent_cmt_with_tabs].b ? 2 :
+                                (cpd.settings[UO_indent_with_tabs].n ? 1 : 0)) :
+                                (cpd.settings[UO_align_with_tabs].b ? 1 : 0));

    tab_col = (iwt == 0) ? 0 : ((iwt == 1) ? brace_col : base_col);

@@ -861,7 +863,8 @@ static void output_cmt_start(cmt_reflow& cmt, chunk_t *pc)
    }

    /* tab aligning code */
-   if (cpd.settings[UO_indent_cmt_with_tabs].b &&
+   if (((cmt.column == cmt.brace_col && cpd.settings[UO_indent_cmt_with_tabs].b) ||
+       (cmt.column != cmt.brace_col && cpd.settings[UO_align_with_tabs].b)) &&
        ((pc->parent_type == CT_COMMENT_END) ||
         (pc->parent_type == CT_COMMENT_WHOLE)))
    {
```

**Comment by mihaipopescu** [comment]
It is very hard to understand just by looking at this diff as there is not enough context and no history. Instead, you can create a PR for this issue. Also if you have test files, please add it to Uncrustify test suite and make sure they all pass.

PS: You can use markdown to have syntax highlight on the diff you've pasted in like this:

    ```diff

**Comment by dfberger** [comment]
I did a bit more experimentation last night, and I think it's not the bug I thought it was, just an unexpected interaction, and maybe questionable naming, of configuration options.

it seems ```indent_cmt_with_tabs``` is actually (only) controlling alignment in the case where ```indent_with_tabs = 2``` 

without ```indent_cmt_with_tabs``` set, but ```indent_with_tabs=2``` comments at brace level are correctly tab indented and right hand comments remain preceded by space.  enabling ```indent_cmt_with_tabs``` doesn't change the brace level indentation, but does cause right hand comments to be preceded by tabs. 

I'm closing this issue.
