### ISSUE TITLE
nl_after_XX and nl_before_XX not respected for if/comment chains

### ISSUE THREAD

**Issue by zachriggle** [uncrustify/uncrustify#53]
The expected behavior is that there should be a newline between the closing brace `}` and the following comment.

## Configuration

```
nl_after_if = add
nl_after_brace_close = true
nl_before_cpp_comment = 1
nl_before_c_comment = 1
```

## Input
```
//
// Comments
//
if(x)
{
    // ...
}
//
// Comments
//
else ( ... )
{
    // ...
}
//
// More comments
//
```

## Expected Output

```
//
// Comments
//
if(x)
{
    // ...
}

//
// Comments
//
else ( ... )
{
    // ...
}

//
// More comments
//
```

**Comment by gmaurel** [comment]
The input code is NOT correct.
After the else should be statement(s).
Look at http://en.cppreference.com/w/cpp/language/if
  attr(optional) if ( condition ) statement-true else statement-false

Using else if (b)
you get what you need.
