### ISSUE TITLE
Introduction of CT_AUTO regressed formatting in range-based for loops that use auto keyword

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#534]
As side effect of the change 502b5e10 which changed `auto` to be a unique token and not a qualifier (as it was before) made usages of `auto` in range-based for loops to regress.

For instance:
```c++
void foo()
{
	for (auto const& item : list)
		bar(item);
}
```

makes `CT_AMP` to be translated as `CT_ARITH` instead of `CT_BYREF` as it was in 0.62.

```
#   3>              FOR[            NONE][  5/  5/  8/  0][1/1/0][     60000][0-1]     for
#   3>      SPAREN_OPEN[             FOR][  9/  9/ 10/  1][1/1/0][ 100000000][0-0]         (
#   3>             AUTO[            NONE][ 10/ 10/ 14/  0][1/2/0][     72020][0-0]          auto
#   3>        QUALIFIER[            NONE][ 15/ 15/ 20/  1][1/2/0][      2020][0-0]               const
#   3>            ARITH[            NONE][ 21/ 20/ 21/  0][1/2/0][ 100002020][0-0]                     &
#   3>             WORD[            NONE][ 23/ 22/ 26/  1][1/2/0][      2020][0-0]                       item
#   3>        FOR_COLON[            NONE][ 28/ 27/ 28/  1][1/2/0][ 100002020][0-0]                            :
#   3>             WORD[            NONE][ 30/ 29/ 33/  1][1/2/0][     62020][0-0]                              list
#   3>     SPAREN_CLOSE[             FOR][ 34/ 33/ 34/  0][1/1/0][ 100002000][0-0]                                  )
```

Note that Uncrustify doesn't currently have a test for this rather common usage of `auto` c++ keyword.

After debugging a possible fix to avoid the `CT_ARITH` tokenization would be:

```diff
diff --git a/src/combine.cpp b/src/combine.cpp
--- a/src/combine.cpp
+++ b/src/combine.cpp
@@ -1093,7 +1093,8 @@
       {
          set_chunk_type(pc, CT_ADDR);
       }
-      else if (prev->type == CT_TYPE)
+      else if ((prev->type == CT_TYPE) ||
+               (prev->type == CT_QUALIFIER) ||
+               (prev->type == CT_AUTO))
       {
          set_chunk_type(pc, CT_BYREF);
       }
```
for which I will create a pull request.

If you have any other ideas to stop this detection even sooner do not hesitate to leave a comment.

**Comment by sjakub** [comment]
I'm confused... after the change that introduced the problem, 'auto' is no longer a qualifier, but a special token. however, your fix adds special case for handling the qualifier... it doesn't make sense...

**Comment by mihaipopescu** [comment]
Yes you are right. It didn't handled all the cases. I've made an update.

**Comment by sjakub** [comment]
So what exactly did the original change fix?
Because if it did help you, the problem might be elsewhere...

**Comment by mihaipopescu** [comment]
What I was actually trying to point out was that the proposed fix is trying to fix side-effects rather than trying to give a more general solution for the regression.

As an example, I've just stumbled yet another case in which the proposed fix didn't work:
```diff
-	auto* var = bar();
+	auto * var = bar();
```

where in this case `CT_STAR` was tokenized as `CT_ARITH` instead of `CT_PTR_TYPE`.

I mean, we could try to fix all the side effects as long we're sure we have a good coverage. The solution types I was looking for:
* should `CT_AUTO` be handled everywhere where `CT_QUALIFIER` is handled ?
* could `CT_AUTO` be set to `CT_QUALIFIER` after we've done with it ?
* instead of introducing a new keyword can the detection of the function prototype that returns an `auto` be fixed by checking the token value ?

I guess to figure this out requires some advanced knowledge of the intricate workings of Uncrustify.

**Comment by sjakub** [comment]
I don't know why CT_AUTO is needed, I'll have to have a look.
But I'm not sure why it should be treated (and why it was treated in the past) as a qualifier...
it's a type, not a qualifier...

**Comment by mihaipopescu** [comment]
yeah, it worked before because the qualifiers were properly handled around types.
Well, I guess we could ask @gmaurel why he wanted a new token as from what I can see `CT_TYPE` could actually work for his bugfix as well.

**Comment by sjakub** [comment]
I created a change that, I think, corrects the issue in a very simple way: #537.
I didn't include the auto test files, since you created them,
but they work fine with this change...

**Comment by sjakub** [comment]
Also, if there are some issues with qualifiers around the types,
it's probably a separate issue, not really related to 'auto'...
Regardless, I think 'auto' should be handled like a type, not a qualifier...

**Comment by mihaipopescu** [comment]
Yes, it seems like the right fix. I agree that `auto` should be treated as a type. 👍 Thanks!
