### ISSUE TITLE
add PR testing on Windows

### ISSUE THREAD

**Issue by dirk-thomas** [uncrustify/uncrustify#538]
As a follow up of #470 it would be good to run the tests on Windows, too.

**Comment by mihaipopescu** [comment]
What is the actual problem ? Can you be more specific ?

**Comment by dirk-thomas** [comment]
Similar to Travis every PR should be tested on Windows as well, e.g. using AppVeyor.

**Comment by dirk-thomas** [comment]
Can someone with admin priviliges please login to AppVeyor (using the GitHub account) and create a project for this repo. Then I can provide the pull request adding the necessary `appveyor.yml` file. For my fork it already works: dirk-thomas/uncrustify#1

**Comment by mihaipopescu** [comment]
I guess only @bengardner and @gmaurel have admin rights but I in any case I think CMake scripts need to be merged in master first along with the project files cleanup as well.

Can you make PRs for those as well ?

**Comment by dirk-thomas** [comment]
I don't think anything else is required for this. In my fork adding the appveyor config was sufficient.

**Comment by dirk-thomas** [comment]
@gmaurel This should just take a minute and would allow all PRs to be tested on Windows.

**Comment by mihaipopescu** [comment]
Could the Gnu autotools and solution files be removed ? I'd love to see a PR with that change.

**Comment by dirk-thomas** [comment]
@mihaipopescu That would absolutely make sense. I commented on the PR which added the CMake files with the same suggestion (https://github.com/uncrustify/uncrustify/pull/492#issuecomment-223014326). But I think it is unrelated to this issue.

**Comment by mihaipopescu** [comment]
Yes of course. Then for this, you can make a PR for adding `appveyor.yml` and add a comment that @gmaurel has to create the project on GitHub (probably adding some instructions to do that).

**Comment by dirk-thomas** [comment]
As mentioned above I think it makes sense to first create the AppVeyor project and then create the pull request. Otherwise AppVeyor won't run on that pull request. The `appveyor.yml` file is already available and "ready" in my referenced fork.

The process is easy:
* goto https://www.appveyor.com/
* click on "Sign In" (at the top right)
* login with your GitHub account
* click "New Project"
* click on "add" for this repository
* optionally change "Build version format" to "{build}" (cosmetic change only)

**Comment by gmaurel** [comment]
I validate your appveyor.yml
What is now to do?

**Comment by dirk-thomas** [comment]
Phrase create the appveyor project. Afterwards I can create the PR adding the appveyor configuration file to this repo. For the PR it should then trigger a Windows build and report the status of the tests.

**Comment by mihaipopescu** [comment]
Maybe you can consider integrating Coverity as well https://scan.coverity.com/github.

**Comment by gmaurel** [comment]
I already followed your instructions from 2016-07-19.
Do you miss anything to continue.

**Comment by jibsen** [comment]
Assuming you're part of the uncrustify organization, when you sign into AppVeyor with GitHub, it will ask which account you want to use. I would think you'd have to sign in with the uncrustify account to be able to set it up for the project in the organization.

From then on, it's just New Project, find the project under the organization, and click Add, like @dirk-thomas said. 

I don't know if it requires a certain level of access to the organization to be able to set this up, but I would assume so, since AppVeyor needs to put some hooks in.

**Comment by dirk-thomas** [comment]
I have just created #615 and AppVeyor is not being triggered. Whenever you have registered the project on AppVeyor you can close and reopen that PR to try retriggering the tests.

**Comment by mihaipopescu** [comment]
The most probable link for appveyor https://ci.appveyor.com/project/uncrustify/uncrustify it's not working which means @gmaurel didn't created the project on https://www.appveyor.com/.
