### ISSUE TITLE
Add new lines after class open brace

### ISSUE THREAD

**Issue by BigfootN** [uncrustify/uncrustify#541]
Hello,

Is there an option that can configure the number of lines after an open brace from a class definition, example:

``` C++

class Test {
   // .. define the number of empty lines here ..
   // some code
};

```

This function seems to work (since I am mostly concerned about access specifiers): `nl_before_access_spec` but :

"Will not change the newline count if after a brace open."

Thank you very much in advance :)

**Comment by tmbeniamin** [comment]
I need also this option.
And after namespace also.
For example, I have the code:

```
namespace test_namespace
{
class Test 
{
// lines of code...
}
}
```
and I want to achieve this:
```
namespace test_namespace
{

class Test 
{

// lines of code...

}

}
```

**Comment by gmaurel** [comment]
No. We don't have.
nl_before_access_spec,         // The number of newlines before a 'private:', 'public:', 'protected:', 'signals:', or 'slots:' label
but only if there are code before

**Comment by BigfootN** [comment]
Thank you very much for your answer :)
