### ISSUE TITLE
Regression on column alignment

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#546]
Uncrustify 0.63 regressed in column alignment. For instance:

```diff
namespace Align
{
    internal class Class
    {
         public void Foo()
         {
-            if (data)   go = new ClassA();
-            else        go = new ClassB();
+            if (data) go = new ClassA();
+            else go = new ClassB();
 
-            if (evt.alt)        modifiers += "Alt+";
-            if (evt.command)    modifiers += "Cmd+";
-            if (evt.control)    modifiers += "Ctrl+";
-            if (evt.shift)      modifiers += "Shift+";
+            if (evt.alt) modifiers += "Alt+";^M
+            if (evt.command) modifiers += "Cmd+";
+            if (evt.control) modifiers += "Ctrl+";
+            if (evt.shift) modifiers += "Shift+";
         }
     }
 }
```

Reverting the change from d44b48669 on `src/space.cpp` appears to be fixing the issue.

**Comment by Zillustrator** [comment]
You need to look at the config settings for "align_assign_span" which is the number of lines that will be aligned on assignment operators in one scope. It is probably set to 4. I've got mine set to 9999. I also tweaked the alignment conditions so that it won't align assignments separated by blank lines

**Comment by mihaipopescu** [comment]
`align_assign_span` is for assignments (like in `00401-align-equ.c`) and it doesn't apply in my case.
You can reproduce the regression using the `empty.cfg` and testing v0.62 versus 0.63.

The fix for bug 637 produced this regression removing old functionality. I'm going to create a new PR that address this.

**Comment by gmaurel** [comment]
It will be fine.
