### ISSUE TITLE
align_assign_span not applied for multiple variables in single definition for 0.63

### ISSUE THREAD

**Issue by CJCombrink** [uncrustify/uncrustify#551]
This might be related to issue #546 but I am not sure.

I have the following code:

```
void SomeClass::run()
{
    /* a */
    uint32_t numWorkers = 10;
    uint32_t numPulse = 5;

    double someDouble;
    doSomethign();

    /* b */
    int scan = 0;
    int block = 0;
    int someLongName = 0;
    /* issue */
    float start, end;
}

```

With the setting `align_assign_span                         = 2`

The result is:

```
void SomeClass::run()
{
    /* a */
    uint32_t numWorkers = 10;
    uint32_t numPulse   = 5;
    double someDouble;
    doSomethign();

    /* b */
    int scan = 0;
    int block = 0;
    int someLongName = 0;
    /* issue */
    float start, end;
}
```

From the example, the code under `a` is indented correctly but `b` not.

If I modify the line `float start, end;` after `/* issue */` to `float start;` the result is correct:

```
void SomeClass::run()
{
    /* a */
    uint32_t numWorkers = 10;
    uint32_t numPulse   = 5;
    double someDouble;
    doSomethign();

    /* b */
    int scan         = 0;
    int block        = 0;
    int someLongName = 0;
    /* issue */
    float start;
}
```

Please let me know if I need to send through my complete config file.

**Comment by mihaipopescu** [comment]
No, I don't think they are related. You've probably found a new alignment issue. Can you reproduce it by altering one of the tests, like `00401-align-equ.c` ?

**Comment by CJCombrink** [comment]
Yes I can reproduce, I have attached the modified input and output that reproduces this issue. 

The output of the test with the attached is:
```
./run_tests.py c -d
Tests: ['c']
Processing c.test
MISMATCH: 00401
--- output/c/00401-align-equ.c	2016-07-12 07:39:48.105778100 +0200
+++ results/c/00401-align-equ.c	2016-07-12 07:41:33.542012349 +0200
@@ -29,11 +29,11 @@
    ffffff = 6;
 
 
-   int a      = 1;
-   int bb     = 2;
-   int ccc    = 3;
-   int dddd   = 4;
-   int eeeee  = 5;
+   int a = 1;
+   int bb = 2;
+   int ccc = 3;
+   int dddd = 4;
+   int eeeee = 5;
    int ffffff = 6;
    int a, b;
    int a      = 1;
```

From the input and output you can see that the issue only occurs on variable declaration + equals statements. 

Please let me know if there is anything else that I can do.

[issue551.tar.gz](https://github.com/uncrustify/uncrustify/files/358622/issue551.tar.gz)

**Comment by CJCombrink** [comment]
Any update on this issue?

**Comment by mihaipopescu** [comment]
Only what you've probably already noticed from the other linked issue. Did you tried reverting that commit ?

**Comment by gmaurel** [comment]
The line ```float start, end;``` closes the stack to search something to align.
You only need to change this line (with the multiple declaration) to two lines:
```
float start;
float end;
```
One could say: "never declare more than one variable per statement"

**Comment by CJCombrink** [comment]
@gmaurel I agree that the "never declare more than one variable per statement" is specified in most coding standards. 

The issue is more with why is the indentation broken for variables before the line `float start, end;`? 

Is there a way to ask uncrustify to split the declaration into 2 lines, which would solve the issue on a subsequent pass?

**Comment by guy-maurel** [comment]
No, uncrustify doesn't split.
uncrustify stops and brakes at the COMMA.
Please, make a little change to your code re-run uncrustify and report.
