### ISSUE TITLE
Regression on brace indentation in array assignments

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#552]
The change introduced with changeset 7e8fedfd7 promised to fix issue #467 but unfortunately introduced other regressions for array assignments:

You can reproduce it with an `empty.cfg` and this input:

```cpp
char *array_assign[2][4]=
{
	{
		// foo
		{"foo"},
		{"foo@1"},{"foo@2"},{"foo@3"}
	},
	{
		// bar
		{"bar"},
		{"bar@1"},{"bar@2"},{"bar@3"}
	}
};
```

Uncrustify v0.63 has regressed from v0.62 with this diff on the resulted formatted file:

```diff
@@ -1,13 +1,13 @@
 char *array_assign[2][4]=
 {
 	{
-		// foo
-		{"foo"},
-		{"foo@1"},{"foo@2"},{"foo@3"}
-	},
+	 // foo
+	 {"foo"},
+	 {"foo@1"},{"foo@2"},{"foo@3"}
+},
 	{
-		// bar
-		{"bar"},
-		{"bar@1"},{"bar@2"},{"bar@3"}
-	}
+	 // bar
+	 {"bar"},
+	 {"bar@1"},{"bar@2"},{"bar@3"}
+}
 };

```

**Comment by gmaurel** [comment]
I cannot reproduce with 0.62
At least indent_columns=4 is missing.
Can you push more information?

**Comment by mihaipopescu** [comment]
The issue is present starting with 0.63 regardless using or not `indent_columns`.

**Comment by gmaurel** [comment]
It is now OK for #552.
Another solution has to be found for #467.
