### ISSUE TITLE
[C++] Unable to parse UCN identifiers

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#555]
Uncrustify is not able to handle `Universal Character Names` identifiers:

```cpp
int main()
{
   int IdentContainingTwoUCNCharacters\u1234\U00001234 = 0;
}
```

complaining about garbage in the console output:
```console
input/cpp/ucn.cpp:3 Garbage in col 40: 5c
input/cpp/ucn.cpp:3 Garbage in col 46: 5c
```

and generating illformed C++ code:
```cpp
int main()
{
	int IdentContainingTwoUCNCharacters \ u1234 \ U00001234 = 0;
}
```

They are somehow handled by other languages (like D) but as strings not as identifiers.

**Comment by gmaurel** [comment]
This has to be fixed

**Comment by mihaipopescu** [comment]
@gmaurel what do you mean ?
