### ISSUE TITLE
Test 30080 has problem

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#557]
It was necessary to revoque the changes for #467.
By this way the test 30080 is no more OK.
@sjakub: could you have a look at it?

**Comment by mihaipopescu** [comment]
@gmaurel  why do you think `30080` doesn't look OK anymore ?

```diff
@@ -6,15 +6,15 @@ SHOW_VAR status_vars[]= {

 SHOW_VAR status_vars[]=
 {
-        { "Aborted_clients", (char *)&aborted_threads,
-          SHOW_LONGLONG, }
+       { "Aborted_clients", (char *)&aborted_threads,
+         SHOW_LONGLONG, }
 };

 SHOW_VAR status_vars[]=
 {
-        {
-         "Aborted_clients", (char *)&aborted_threads,
-         SHOW_LONGLONG,
-}
+       {
+               "Aborted_clients", (char *)&aborted_threads,
+               SHOW_LONGLONG,
+       }
 };
```
I think the new diff looks a lot better than the previous one, especially the indentation of the brace close.

**Comment by mihaipopescu** [comment]
@gmaurel you can graft my commit to fix the failure on master or I could create a PR with that. Which one do you prefer ?

**Comment by sjakub** [comment]
I think there is some confusion going on...
This is about 30080 that I had nothing to do with,
but test 33080 was disabled instead... which still works fine.

Thoughts (@gmaurel) ?

**Comment by mihaipopescu** [comment]
Maybe @gmaurel wanted to ping @ib instead of you but yeah, there are still confusions with 30080.

**Comment by sjakub** [comment]
I created a pull request #576 that re-enables this test.

**Comment by gmaurel** [comment]
is merged

**Comment by mihaipopescu** [comment]
And what about 30080 ?
