### ISSUE TITLE
Please use pull requests for all code-changing commits

### ISSUE THREAD

**Issue by bengardner** [uncrustify/uncrustify#560]
Commit 5c36767220a942f004b1b04b14181b1a231dc2c1 makes two test cases (02100 and 30080) fail.

That wasn't done as part of a pull request, so the CI step was skipped.
Or rather, it isn't obvious that it had failed.
The status is visible here: https://github.com/uncrustify/uncrustify/branches

Would you please use pull requests for all code-changing commits?
I understand that is a bit more work, but it will help find bad commits before they are pushed to the main repository.

**Comment by mihaipopescu** [comment]
After Windows automated build system will be set in place issue #538 we will even have more coverage that what can you can do with local testing.

**Comment by gmaurel** [comment]
I commented the tests until a fix is written

**Comment by mihaipopescu** [comment]
I think Ben was referring to the workflow of pushing to `master` which should only be done only through a PR. For instance commit f65ad52 should have been a PR which you would later approve it yourself and merge to master if everything was ok.

This change in workflow is just to increase test coverage and make sure we're not blocking new PRs from getting in (as tests will fail for them).

**Comment by mihaipopescu** [comment]
@gmaurel What do you think about Ben's proposal ? Would you like to start using this new approach and create PRs even for your own work ?

**Comment by gmaurel** [comment]
OK.
I have now an experience more!
It is a better way to work together.
Thanks for your help.
