### ISSUE TITLE
is there a way to skip some lines?

### ISSUE THREAD

**Issue by pvinis** [uncrustify/uncrustify#564]
sometime i have something like
```
CGPathMoveToPoint   (bottomArrow, NULL, round(aPoint.x) + .5/self.contentsScale -3, aPoint.y - aLength+1 +4);
CGPathAddLineToPoint(bottomArrow, NULL, round(aPoint.x) + .5/self.contentsScale   , aPoint.y - aLength+1   );
CGPathAddLineToPoint(bottomArrow, NULL, round(aPoint.x) + .5/self.contentsScale +3, aPoint.y - aLength+1 +4);
```
can i somehow make uncrustify skip those?

**Comment by mihaipopescu** [comment]
What do you mean by _skip some lines_ ? What is your expected output ?

**Comment by pvinis** [comment]
i mean i want to format the file that contains these lines, and i want everything formatted except for these lines. they should stay as they are.

**Comment by CJCombrink** [comment]
Look at `disable_processing_cmt` and `enable_processing_cmt`

**Comment by mihaipopescu** [comment]
That will do but you should do that only as a workaround when Uncrustify doesn't understand the thing you're throwing at it or it's very complex to make it understand.

Uncrustify has an option `align_same_func_call_params` but it's for the same function calls like `CGPathAddLineToPoint` here. Maybe @pvinis can play with those... even though, on the other hand, alignment could sometimes be hard to get it working the way you want.

**Comment by pvinis** [comment]
aha. alright, then we can close this. i will play around with these options. lets see if they can convince me to use uncrustify.

**Comment by gmaurel** [comment]
Fine. Let us know about any issue
