### ISSUE TITLE
nl_case_colon_brace does not work as expected

### ISSUE THREAD

**Issue by Jaydyou** [uncrustify/uncrustify#566]
While putting `nl_case_colon_brace = remove` I was expecting something like

```
case 1: {
}
```
but I got:
```
case 1:
{
}
```

**Comment by Jaydyou** [comment]
Its working now. No idea why it was not working before.

**Comment by bengardner** [comment]
Sometimes a "make clean && make" fixes odd errors when you pull from git.
The build scripts don't do a good job of detecting header changes.
