### ISSUE TITLE
Don't align assignments in variable definition lists breaks if in the middle of the list

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#567]
The patch introduces on 2016-03-17 20:37:17, at 5869ad7c3f2f283344339b14d955302982454e70
breaks the indentation of the first part if a definition with more as one variable is in the middle of the list.
Let us take the example:
`void foo(void)
{
   float a = 1;
   int bb = 2;
   int b,c;
   aaaxxxxxx xxxx = 51;
   bbbxxxxxx yy = 251;
}`

The output will be:
`void foo(void)
{
   float a = 1;
   int bb = 2;
   int b, c;
   aaaxxxxxx xxxx = 51;
   bbbxxxxxx yy   = 251;
}`
void foo(void)
{
   float a = 1;
   int bb = 2;
   int b, c;
   aaaxxxxxx xxxx = 51;
   bbbxxxxxx yy   = 251;
}
@ib: Could you have a look on it?
[a-false_c.txt](https://github.com/uncrustify/uncrustify/files/364139/a-false_c.txt)
[align-1_cfg.txt](https://github.com/uncrustify/uncrustify/files/364140/align-1_cfg.txt)

Source and config files are attached

**Comment by CJCombrink** [comment]
This is probably a duplicate of #551

**Comment by gmaurel** [comment]
The line ```int b, c;``` closes the stack to search something to align.
You only need to change this line (with the multiple declaration) to two lines:
```
int b;
int c;
```
One could say: "never declare more than one variable per statement"

**Comment by guy-maurel** [comment]
uncrustify stops and brakes at the COMMA.
Please, make a little change to your code re-run uncrustify and report.

**Comment by gmaurel** [comment]
No answer, we close.
