### ISSUE TITLE
uncrustify removes the desired space before closing braces in objc blocks

### ISSUE THREAD

**Issue by benrudhart** [uncrustify/uncrustify#569]
When working with blocks in ObjC I can't get uncrustify to force the style I'd like to have.
The closing braces are not aligned with the opening braces.
How can I force this?
##### desired output

``` objC
[myFoo bar:^{
              [bar foo];
              if (1) {
                  [bar foobar];
              }
          }
      bar1:nil
      bar2:some];
```
##### actual output

``` objc
[foo bar:^{
     [self.menuLeadingConstraint.firstItem layoutIfNeeded];
     if (1) {
        [bar foobar];
    }
 }
    bar1:nil
    bar2:some];
```

There are some issues with this output:
- closing braces of `if` statements inside blocks are not aligned. Outside of a block they properly get aligned with the `if` keyword. Inside the block they are misaligned by ~12 spaces. (this is probably hard to see here)
- closing braces of blocks themselves are not aligned with the beginning of the block (e.g. the colon). Similar to the issue with the `if` keyword they are too far left (too small indent)
- all content within the block is too far left (indentation too small)

I'm currently using the following options:

```
indent_oc_block_msg_xcode_style         = true
indent_oc_block                         = true
indent_oc_block_msg                     = 0   
```

Are there any options I'm missing for objc blocks? Any hints what could help to make uncrustify create this output?

**Comment by mihaipopescu** [comment]
We have a lot of fixes for ObjC but they are coming from an old branch (https://github.com/Unity-Technologies/uncrustify/commits/fixes/c-oc-java) that we still have to merge in to our master but you could take a look at some of our changes that relate to your issue.

Try grafting:
https://github.com/Unity-Technologies/uncrustify/commit/65b136baa2e7397293e3e16a82ec100af8798219
https://github.com/Unity-Technologies/uncrustify/commit/51ff11c3c20802f7ecba798f334568683870096b

It doesn't look it's completely what you want but it could be a good starting point.

**Comment by guy-maurel** [comment]
Do you have take care of the comment from @mihaipopescu ?
Please report

**Comment by mihaipopescu** [comment]
Didn't @CDanU started integrating the ObjC changes from our fork?

**Comment by CDanU** [comment]
Yes I had started to migrate one of the updated branches from aet, so far I had done all but one C++ and Java fixes (reported a problem, didn't get an answer). The OC ones still have to be imported gradually.

**Comment by mihaipopescu** [comment]
Would be nice to land what you have right now. Let me know if your question is still unanswered and link it back here for reference.
