### ISSUE TITLE
[meta] Uncrustify has two issue tracking services creating confusion

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#573]
Now, as the main development was moved to GitHub, it's very difficult to maintain and keep track of the old SourceForge bugs. Even if we've made the convention that for github we use "issue" and for SourceForge "bug" it's still creating confusion in code comments and github PR's.

The bugs from SourceForge can be migrated using an automated script like https://github.com/cmungall/gosf2github (or similar), leave a comment with the new issue number and close the issue. Should save the 1-1 mapping to a log file.

What do you think ?

**Comment by gmaurel** [comment]
It would be fine.
Could you manage it for us?

**Comment by mihaipopescu** [comment]
Yes. Would you export the issues from SourceForge using this link https://sourceforge.net/p/uncrustify/admin/export ? It requires admin privileges and I cannot do it myself.

**Comment by mihaipopescu** [comment]
I'd also suggest to keep this issue open until we will actually fix it.

**Comment by mihaipopescu** [comment]
@gmaurel Could you send me the exported SourceForge tickets ?

**Comment by jayvdb** [comment]
Aye; and there are dups like https://sourceforge.net/p/uncrustify/feature-requests/179/ and #351

**Comment by gmaurel** [comment]
Sorry, I forgot to read the messages.
I make now the export and inform you asap.

**Comment by gmaurel** [comment]
@mihaipopescu : the backup was send to you.
Do you need anything else?

**Comment by mihaipopescu** [comment]
I'm not sure. Please keep this issue open until we have migrated the issues.

**Comment by mihaipopescu** [comment]
I did a bunch o tests and the script seems to be working now on my own fork https://github.com/mihaipopescu/uncrustify/issues.

There are though some considerations to be made:

It would be nice to have a more complete sourceforge -> github username map. I have only this:
```json
{
 "scottbilas" : "scottbilas",
 "guymaurel" : "gmaurel",
 "mehy" : "mihaipopescu",
 "bengardner" : "bengardner"
}
```

My current issue filter is this:

```perl
foreach my $ticket (@tickets) {
    if ($ticket->{status} =~ /wont-fix/
        or $ticket->{status} =~ /closed/
        or $ticket->{status} =~ /fixed/
        or $ticket->{status} =~ /works-for-me/
        or $ticket->{status} =~ /invalid/
        or $ticket->{status} =~ /duplicate/)
    {
        next;
    }
...
```

And I can run this script on `bugs`, `feature-requests` and `support-requests`.

Some features will be missing like attachments but the links to the original tickets will be present in the issue so basically the files would be retrievable.

Currently the script assigns "sourceforge" and "auto-migrated" labels + all the previous sourceforge labels. The problem is that I don't have enough permissions to add labels on the main project so that won't work. It would be nice if I can get a new GitHub OAuth token with more elevated privileges to be able to add labels. 

Another option would be if @gmaurel runs the script or maybe better we could have a new GitHub user (new email address) say _uncrustify-sf2gh_ and use this one to create the tickets.

What should it be ?

**Comment by mihaipopescu** [comment]
@gmaurel The script will create 78 new issues. Do you wish to proceed ?

**Comment by mihaipopescu** [comment]
It would be awesome if you can do it from your side because you have elevated privileges and can create the issues with their SourceForge labels (+ some migration ones).

Steps:

1. Download this perl script https://gist.github.com/mihaipopescu/99e412468f54ca49fc724399c9ceff14
2. Copy it next to the extracted backup you gave me (next to bugs.json for example)
3. Generate a GitHub personal access token only with *repo* permissions (instructions from https://help.github.com/articles/creating-an-access-token-for-command-line-use)
4. Create a file named `users_sf2gh.json` with this content (and modify it if you want)
```json
{
 "scottbilas" : "scottbilas",
 "guymaurel" : "gmaurel",
 "mehy" : "mihaipopescu",
 "bengardner" : "bengardner"
}
```
5. Make sure you have `curl` in your path
6. Run the script in `--dry-run` mode for each issue type to see what GitHub Restful API calls will be called and if that's what you want:
- `perl gosf2github.pl --dry-run --token <TOKEN> --usermap users_sf2gh.json --sf-tracker uncrustify/bugs bugs.json`
- `perl gosf2github.pl --dry-run --token <TOKEN> --usermap users_sf2gh.json --sf-tracker uncrustify/feature-requests feature-requests.json`
- `perl gosf2github.pl --dry-run --token <TOKEN> --usermap users_sf2gh.json --sf-tracker uncrustify/support-requests support-requests.json`
7. Run the script for good by removing the `--dry-run` argument.

If your perl installation is missing the JSON module `Can't locate JSON.pm in @INC (you may need to install the JSON module)` then you can installing by running: `cpanm install JSON`

Tell me if you have any issues with this. Thanks !

**Comment by gmaurel** [comment]
Hello again!

Am 09.09.2016 um 00:18 schrieb Mihai Popescu:

> 2. Copy it next to the extracted backup you gave me (next to bugs.json for example)
This is the step I don't anderstand.
I send you a file uncrustify-backup-2016-08-31-132350.zip which was
build at the export function.
Where is the data, the file we are missing "bugs.json"?
What does it mean: "... next to bugs.json for example"
My english is poor!

Guy
-- 
Guy Maurel
Sebastian-Fischer-Weg 13
89077 Ulm

**Comment by mihaipopescu** [comment]
I see that you managed to do it. Thanks a lot.
