### ISSUE TITLE
Crash with qt cpp code

### ISSUE THREAD

**Issue by yeoupooh** [uncrustify/uncrustify#574]
I've run uncrustify with below options
uncrustify.exe -l cpp -c cfg\qt.cfg -f crash.cpp

qt.cfg from https://gist.github.com/trollixx/11204806

Only one case as below it crashed. It looks like happened when something mixed.

```
class A {
// crash (two parameter, 2nd string parameter has space)
void check( const QObject* object, const QStringList& strList = QStringList(QString(QLatin1String("one two"))));
// no crash (two parameter, 2nd string parameter has no space)
void check( const QObject* object, const QStringList& strList = QStringList(QString(QLatin1String("one"))));
// no crash (removed QLatin1String)
void check( const QObject* object, const QStringList& strList = QStringList(QString(("one two"))));
// no crash (removed QString(QLatin1String))
void check( const QObject* object, const QStringList& strList = QStringList());
// no crash (removed 1st parameter only)
void check( const QStringList& strList = QStringList(QString(QLatin1String("one two"))) );
};

```

**Comment by mihaipopescu** [comment]
What version of Uncrustify are you running ? I've just tried your example and it's not crashing.

**Comment by yeoupooh** [comment]
I'm using uncrustify 0.63.0-g44ce0f1.

**Comment by mihaipopescu** [comment]
Uh ok. Can you try with the latest and see if it's still present ? I can't reproduce your crash.

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
