### ISSUE TITLE
Wrong newlines after = assignments

### ISSUE THREAD

**Issue by Massimo-B** [uncrustify/uncrustify#575]
``` cpp
$ (cfg="https://bitbucket.org/massimo/configs/raw/72329a67bd4fa2f321faf3e6df1ab6e7dd90f262/uncrustify.cfg" ; input="https://bitbucket.org/massimo/test/raw/c7fec4fca601bec29cb35946ab92edd642bda02b/crusty-test_001.cpp" ; uncrustify -v ; curl -s "$input" ; curl -s "$input" | uncrustify -l cpp -c <(curl -s "$cfg") )

uncrustify 0.63
void Foo::doo()
{
    m_stackCache[m_currentStackNr]->operator [](0) = new QStandardItem(QString::number(m_currentStackNr));
    m_stackCache[m_currentStackNr]->operator [](1) = new QStandardItem(tr("OK"));
    m_stackCache[m_currentStackNr]->operator [](2) = new QStandardItem("0");
    m_stackCache[m_currentStackNr]->operator [](3) = new QStandardItem("0");
    m_stackCache[m_currentStackNr]->operator [](4) = new QStandardItem();
}                                                                                                   
Parsing: 536 bytes (536 chars) from stdin as language CPP
void                                         Foo::doo()
{
    m_stackCache[m_currentStackNr]->operator [](0) = new QStandardItem(QString::number(m_currentStackNr));
    m_stackCache[m_currentStackNr]->operator [](1) = new QStandardItem(tr("OK"));

    m_stackCache[m_currentStackNr]->operator [](2) = new QStandardItem("0");

    m_stackCache[m_currentStackNr]->operator [](3) = new QStandardItem("0");

    m_stackCache[m_currentStackNr]->operator [](4) = new QStandardItem();
}
```

There are too many additional newlines that are only added for some of those lines.

Beside that, the function name is aligned to operator argument of the body which does not make sense at all. Is that possible to configure or a bug?

**Comment by mihaipopescu** [comment]
Can you edit your issue (add some markup https://guides.github.com/features/mastering-markdown/) to show where the problem is ? You can even provide a diff between the expected and the output.

**Comment by Massimo-B** [comment]
Original:
```cpp
void Foo::doo()
{
    m_stackCache[m_currentStackNr]->operator [](0) = new QStandardItem(QString::number(m_currentStackNr));
    m_stackCache[m_currentStackNr]->operator [](1) = new QStandardItem(tr("OK"));
    m_stackCache[m_currentStackNr]->operator [](2) = new QStandardItem("0");
    m_stackCache[m_currentStackNr]->operator [](3) = new QStandardItem("0");
    m_stackCache[m_currentStackNr]->operator [](4) = new QStandardItem();
}                                                  
```                                                 
uncrustified:
```cpp
void                                         Foo::doo()
{
    m_stackCache[m_currentStackNr]->operator [](0) = new QStandardItem(QString::number(m_currentStackNr));
    m_stackCache[m_currentStackNr]->operator [](1) = new QStandardItem(tr("OK"));

    m_stackCache[m_currentStackNr]->operator [](2) = new QStandardItem("0");

    m_stackCache[m_currentStackNr]->operator [](3) = new QStandardItem("0");

    m_stackCache[m_currentStackNr]->operator [](4) = new QStandardItem();
}
```
The original should not be changed by uncrustify.

**Comment by mihaipopescu** [comment]
What happens if you're using an `empty.cfg` ?

**Comment by Massimo-B** [comment]
Then the content is unchanged.

**Comment by mihaipopescu** [comment]
Good, then it's likely that one of the options (or a combination of them) could be at the root of this issue. If you want to investigate further you can check to see what's the difference between your config and the default config (dump it with `--show-config` and diff it against yours). You could also add this as a test and run `./run_tests -g` option to dump some log files you could inspect.

**Comment by Massimo-B** [comment]
I always merge my config against new git revisions after rebuilding uncrustify:
```
vimdiff .uncrustify.cfg  <(uncrustify --update-config-with-doc)
```
But this issue is rather that there is no reason to put newlines for some of the assignments, for others not. Then I did not find the parameter causing this after toggling every of my parameters.

Which ticket system is the main today, here on github or the old on sourceforge? That had a ticket type "Support Request". If this is not a bug (I doubt) then it's more a forum or support question.

**Comment by mihaipopescu** [comment]
I'm not sure... I'm not a maintainer but I think SourceForge is probably going to fade away as we will be migrating all remaining opened issues to GitHub Issues. But no, I think you've found a real bug that worth investigating. It's just the question of how much _you_ want to contribute in this effort.

**Comment by sjakub** [comment]
@Massimo-B Which option causes that behaviour?

**Comment by Massimo-B** [comment]
I reverted my configuration step by step and found the culprit. Setting
`nl_after_func_proto_group                 = 2`
in my configuration fixes the issue. However this is an incorrect behaviour for that option.

**Comment by mihaipopescu** [comment]
Is this a regression in 0.63 ? Did it happen in 0.62 for instance ?

**Comment by mihaipopescu** [comment]
I think uncrustify gets confused about the `operator []()` call. Can you also paste the tokens dump here (`-p` option if IIRC).

**Comment by Massimo-B** [comment]
[dump.zip](https://github.com/uncrustify/uncrustify/files/383408/dump.zip)

**Comment by gmaurel** [comment]
Using the actual git version and
indent_columns=4
indent_with_tabs=0
The output is identical to the input

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!

**Comment by Massimo-B** [comment]
That didn't solve it.

I did
`git pull;cd build;cmake ..;cmake --build .`

Using the new binary with my oneliner still gives the same result:
```
$ (cfg="https://bitbucket.org/massimo/configs/raw/72329a67bd4fa2f321faf3e6df1ab6e7dd90f262/uncrustify.cfg" ; input="https://bitbucket.org/massimo/test/raw/c7fec4fca601bec29cb35946ab92edd642bda02b/crusty-test_001.cpp" ; uncrustify -v ; curl -s "$input" ; curl -s "$input" | uncrustify -l cpp -c <(curl -s "$cfg") )
uncrustify 0.64_d
void Foo::doo()
{
    m_stackCache[m_currentStackNr]->operator [](0) = new QStandardItem(QString::number(m_currentStackNr));
    m_stackCache[m_currentStackNr]->operator [](1) = new QStandardItem(tr("OK"));
    m_stackCache[m_currentStackNr]->operator [](2) = new QStandardItem("0");
    m_stackCache[m_currentStackNr]->operator [](3) = new QStandardItem("0");
    m_stackCache[m_currentStackNr]->operator [](4) = new QStandardItem();
}                                                                                                   
Parsing: 536 bytes (536 chars) from stdin as language CPP
void                                         Foo::doo()
{
    m_stackCache[m_currentStackNr]->operator [](0) = new QStandardItem(QString::number(m_currentStackNr));
    m_stackCache[m_currentStackNr]->operator [](1) = new QStandardItem(tr("OK"));

    m_stackCache[m_currentStackNr]->operator [](2) = new QStandardItem("0");

    m_stackCache[m_currentStackNr]->operator [](3) = new QStandardItem("0");

    m_stackCache[m_currentStackNr]->operator [](4) = new QStandardItem();
}
```

```
 $ ls -al $(type -P uncrustify)
lrwxrwxrwx 1 mb mb 46 Nov  9 09:34 /home/mb/bin/uncrustify -> /home/mb/src/other/uncrustify/build/uncrustify*

$ ls -alL $(type -P uncrustify)
-rwxr-xr-x 1 mb mb 1,2M Dez 23 09:29 /home/mb/bin/uncrustify*
```

**Comment by gmaurel** [comment]
Sorry. I can reproduce and I'm looking after.

**Comment by gmaurel** [comment]
I need the definition file *.h to compile it.
Could you push it?

**Comment by gmaurel** [comment]
Please: test it and report.
Thanks for the message.

**Comment by Massimo-B** [comment]
Working, thanks.
