### ISSUE TITLE
New lines inside enumeration declaration

### ISSUE THREAD

**Issue by BigfootN** [uncrustify/uncrustify#591]
Hello,

I am having trouble indenting enumerations in c language. When I write this:

``` c
typedef enum {
    A,
    B
} MyEnum;
```

it is formatted to this:

``` c
typedef enum { A, B } MyEnum;
```

Here is my [config](https://gist.github.com/BigfootN/9338cbc706f8e415352c52e9f633f2c6)

Thank you very much in advance :)

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!

**Comment by BigfootN** [comment]
Thank you very much for your answer I will then take a look.
