### ISSUE TITLE
nl_func_class_scope?

### ISSUE THREAD

**Issue by dzenanz** [uncrustify/uncrustify#592]
`nl_func_scope_name` controls the newline after `::` in `void A::f() { }`. Is there a setting which controls the newline before `::`? If not, it could be added and named `nl_func_class_scope`.

If you don't have the time, I am willing to try digging into the code and making a pull request. It is needed for [ITK](https://github.com/InsightSoftwareConsortium/ITK).

**Comment by mihaipopescu** [comment]
I don't see such option but patches are welcome. Check `newline_func_def` from newlines.cpp.

**Comment by dzenanz** [comment]
Thanks Mihai for confirming that `newline_func_def` is the right place to add modifications.

**Comment by dzenanz** [comment]
@thewtex When this pull request is merged we should be ready to use uncrustify in a git hook.

**Comment by thewtex** [comment]
:+1: !

**Comment by gmaurel** [comment]
merged
