### ISSUE TITLE
--update-config-with-doc added another 8 spaces to default config

### ISSUE THREAD

**Issue by todd-richmond** [uncrustify/uncrustify#595]
In the last month or so since I last merged, it seems that the default config output added another 8 spaces before the = in every key/value pair. This makes diffing config challenging and is no longer consistent with the checked in example files. Also, the extra spaces now cause a large # of lines to wrap beyond 80 chars when they did not before (all the ignore/add/remove/force options)

I want to update sun.cfg again with the latest settings

**Comment by todd-richmond** [comment]
looks like this was possibly caused by new warn_level_tabs_found_in_verbatim_string_literals. can that config name be shortened?

**Comment by mihaipopescu** [comment]
By the way, the command line argument you mentioned can't add extra spaces in the dumped config file but indeed there were new options even before the new `warn_` one that introduced extra spaces while aligning the options making the merge a bit challenging. You have to use a smart merge tool to be able to ignore whitespace changes and then manually fix the spacing if you want to have your options aligned. 

Shortening the new options that overflow the old alignment convention won't ensure other new options would not break it again. In some cases shortening is not possible as the new option name could create confusions... although that doesn't mean we should allow option names to grow indefinitely.

I think there is a way to fix this from code. The new option added `-set` can override default options with specific values so in theory if that option is processed before the `--show-config` one (not the case now) you could output the custom config you want with the alignment fixed.

**Comment by todd-richmond** [comment]
that would help. the 80 column friendly format is definitely easier to read on terminals, even if a couple extra long params end up with just a single space before =

**Comment by mihaipopescu** [comment]
I don't think I've mentioned any 80 column alignment as it's just not relevant nowadays. Most terminals and editors can handle more than 80 columns. I personally have 3 guideline rulers set to 80, 100 and 120 but that's just me.

You are talking about a different alignment method using a _thresholding technique_ like in https://github.com/uncrustify/uncrustify/blob/master/documentation/align-thresholds.txt. In this case you end with some options that are outliers. Is that what you are saying ?

**Comment by todd-richmond** [comment]
80 columns is still relevant in many style guides as it allows for 2 side-by-side text files in IDEs with large monitors and many people use terminals set to 80 as well.
 
correct on alignment threshold - a few long winded config names sprawling past 80 would be fine. The main issue is that > 650 lines in every default config no longer match and this was a very recent change because I've been keeping sun.cfg up to date every few months w/o problems until now

**Comment by mihaipopescu** [comment]
What do you mean by
> 650 lines in every default config no longer match
?

**Comment by gmaurel** [comment]
Using the -p option for a uncrustify command and you get a list of the *only* options which value is not the default.
By this way you get a new config file which is mostly shorter as the original one.

**Comment by mihaipopescu** [comment]
Yes but `--show-config` is more useful as you also have options descriptions which are very useful.

**Comment by bengardner** [comment]
Perhaps we should set an upper limit for the name size?
See pull request #660

**Comment by gmaurel** [comment]
The file options.cpp defines at line 103 the maximal length of an option name.
```#define OptionMaxLength    60```
