### ISSUE TITLE
introducing labels. Need help for objectiv C

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#598]
I tried to put some labels for all the calls.
One can see the most of them are about objectiv C.

We need an experienced guy (or more) to fixed these calls.

Please take contact with us.
Thanks

**Comment by CDanU** [comment]
```
Awaiting Answer:
https://github.com/uncrustify/uncrustify/issues/931
```

**Comment by mihaipopescu** [comment]
As previously said, we have a lot of fixes sitting on a very old branch that I'll try to bring back to date. Maybe it will fix some of the issues.
