### ISSUE TITLE
is config.h.in necessary

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#622]
Why to cmake needs config.h.in to READ?

**Comment by mihaipopescu** [comment]
@jibsen ?

**Comment by bengardner** [comment]
config.h.in is generated by automake and used by autotools to generate config.h.
It gets recreated by ./autogen.sh, so I don't think it needs to be in git.

**Comment by jibsen** [comment]
CMake generates `config.h` from it by looking for the headers and symbols it lists and defining the names for those it finds. If you look for preprocessor checks with `HAVE_` in them, you will find a few throughout the source.

**Comment by gmaurel** [comment]
If I read the first line from src/config.h.in
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

I understand that

1. I *must* run autoheader to get it.
2. only after that I may run cmake

I thought we are trying to make a alternative solution with only cmake.

**Comment by jibsen** [comment]
At the moment, for compatibility between both makesystems, the CMake script takes the `config.h.in` produced by Autotools, converts it into a version it can process, and then uses that to generate `config.h`.

If we remove Autotools at some point, we can change `config.h.in` into the version CMake uses, and skip the conversion.

You can check out the `config.h.in` in [this branch](https://github.com/jibsen/uncrustify/tree/makesystem-cleanup), where I am playing around with that.

**Comment by gmaurel** [comment]
Can I close the call?
