### ISSUE TITLE
Variable declare/assign alignment broken by commit 5869ad7c3f2f283344339b14d955302982454e70

### ISSUE THREAD

**Issue by m3m0ryh0l3** [uncrustify/uncrustify#631]
I have align_assign_span = 2, and align_assign_thresh = 0. Using the following simple example:

void foo(int arg)
{
  int *a = NULL; // these don't align properly
  char *ba = NULL;
  short *bc = NULL;
  uint64_t c, d, e; // unless I delete THIS line

  // These *do* align!
  a = NULL;
  ba = NULL;
  bc = NULL;
}

If I delete the indicated line, then the initialization assignments above it will align correctly. If I leave the indicated line there, the initialization assignments do NOT align correctly.

It looks like the logic for computing var_dev_cnt is a bit too generous.

**Comment by mihaipopescu** [comment]
Probably duplicate of #567 and #551.

**Comment by m3m0ryh0l3** [comment]
Yes, it's a duplicate of #551 .
