### ISSUE TITLE
Improperly formatting for-loops within pre-processor blocks of C++ files

### ISSUE THREAD

**Issue by m3m0ryh0l3** [uncrustify/uncrustify#632]
Starting in commit 12d474f44f6caa9c07c8cfbb7ef7371bc2d75fe6, the following code gets re-indented strangely in C++ files (it gets handled just fine in C files):

#define foo(x) \
    something() { \
        for (int x=0; x<10; x++) { \
            do_something(); \
        } \
    }

Uncrustify is handling the < symbol improperly (note that if I change the for-loop condition to be "x != 10", the code gets formatted correctly).

**Comment by mihaipopescu** [comment]
Can you pass `-p file` to uncrustify and see how it tokenizes this example ?

**Comment by m3m0ryh0l3** [comment]
I guess you mean log-level 40?

Here's the output from Uncrustify 0.63 (uncrustify -l C -p debug.txt -L 40 test.c):

           # [PP_DEFINE]
      define [PP_DEFINE]
        foo [PP_DEFINE]
           ( [PP_DEFINE] [PAREN_OPEN]
           x [PP_DEFINE] [PAREN_OPEN]
           ) [PP_DEFINE]
    somethin [PP_DEFINE]
           ( [PP_DEFINE] [PAREN_OPEN]
           ) [PP_DEFINE]
           { [PP_DEFINE] [BRACE_OPEN]
         for [PP_DEFINE] [BRACE_OPEN] [FOR - 1]
           ( [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
         int [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           x [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           = [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           0 [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           ; [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           x [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           < [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
          10 [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           ; [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           x [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
          ++ [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           ) [PP_DEFINE] [BRACE_OPEN] [FOR - 6]
           { [PP_DEFINE] [BRACE_OPEN] [FOR - 6] [BRACE_OPEN]
    do_somet [PP_DEFINE] [BRACE_OPEN] [FOR - 6] [BRACE_OPEN]
           ( [PP_DEFINE] [BRACE_OPEN] [FOR - 6] [BRACE_OPEN] [PAREN_OPEN]
           ) [PP_DEFINE] [BRACE_OPEN] [FOR - 6] [BRACE_OPEN]
           ; [PP_DEFINE] [BRACE_OPEN] [FOR - 6] [BRACE_OPEN]
           } [PP_DEFINE] [BRACE_OPEN]
           } [PP_DEFINE]


And here's the output for the same code when treated as C++ (uncrustify -l CPP -p debug.txt -L 40 test.c):

           # [PP_DEFINE]
      define [PP_DEFINE]
         foo [PP_DEFINE]
           ( [PP_DEFINE] [PAREN_OPEN]
           x [PP_DEFINE] [PAREN_OPEN]
           ) [PP_DEFINE]
    somethin [PP_DEFINE]
           ( [PP_DEFINE] [PAREN_OPEN]
           ) [PP_DEFINE]
           { [PP_DEFINE] [BRACE_OPEN]
         for [PP_DEFINE] [BRACE_OPEN] [FOR - 1]
           ( [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
         int [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           x [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           = [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           0 [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           ; [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           x [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN]
           < [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN] [ANGLE_OPEN]
          10 [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN] [ANGLE_OPEN]
           ; [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN] [ANGLE_OPEN]
           x [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN] [ANGLE_OPEN]
          ++ [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN] [ANGLE_OPEN]
           ) [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN] [ANGLE_OPEN]
           { [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN] [ANGLE_OPEN] [BRACE_OPEN]
    do_somet [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN] [ANGLE_OPEN] [BRACE_OPEN]
           ( [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN] [ANGLE_OPEN] [BRACE_OPEN] [PAREN_OPEN]
           ) [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN] [ANGLE_OPEN] [BRACE_OPEN]
           ; [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN] [ANGLE_OPEN] [BRACE_OPEN]
           } [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN] [ANGLE_OPEN]
           } [PP_DEFINE] [BRACE_OPEN] [FOR - 1] [SPAREN_OPEN] [ANGLE_OPEN]

**Comment by m3m0ryh0l3** [comment]
Ah! It seems to be fixed on git master (commit 07be75582db3c96e94bbbf71ca7031e56e569db0 appears to entirely revert the troublesome commit in question: 12d474f44f6caa9c07c8cfbb7ef7371bc2d75fe6)! Nevermind then! I guess the fix will be in the next release (0.64!)
