### ISSUE TITLE
typename derails variable definition alignment

### ISSUE THREAD

**Issue by dzenanz** [uncrustify/uncrustify#633]
With `align_var_def_span` turned on
```
typename TImage::PixelType m_Label;
int                        m_Axis;
bool                       m_HeuristicAlignment;
```
gets turned into
```
typename TImage::PixelType m_Label;
int  m_Axis;
bool m_HeuristicAlignment;
```
instead of remaining as it is.

I created a test depicting this problem in my [fork](https://github.com/dzenanz/uncrustify/commit/07399f30fb846fa181d14f207320598c295e6887). Should I turn it into a pull request and reference this ticket?

**Comment by mihaipopescu** [comment]
`align_var_def_span` it's not an on/off option. It is used to determine if it should align variables or not within that defined span. 

```
align_var_def_span                                Number
  The span for aligning variable definitions (0=don't align)
```

for eg.:

```cpp
extern bool           QT_SIGNAL_SLOT_found;
extern int            QT_SIGNAL_SLOT_level;
extern bool           restoreValues;
align_var_def_span    ^
```

**Comment by dzenanz** [comment]
OK, I updated my [fork](https://github.com/dzenanz/uncrustify/commit/99606ba7fb72fd6278cb40e43450d9437ba3c7b7) to contain both positive and negative examples:
```
typename TImage::PixelType m_Label;
int                        m_Axis;
bool                       m_HeuristicAlignment;

aLongTypeNameButNotSpecial m_Label;
int                        m_Axis;
bool                       m_HeuristicAlignment;
```
which gets transformed into:
```
typename TImage::PixelType m_Label;
int  m_Axis;
bool m_HeuristicAlignment;

aLongTypeNameButNotSpecial m_Label;
int                        m_Axis;
bool                       m_HeuristicAlignment;
```

**Comment by mihaipopescu** [comment]
Do you think the problem is the `typename` or the namespaced type `TImage::PixelType` ? What happens if you change one or the other ?

**Comment by dzenanz** [comment]
typename is the problem. This code fraction gets aligned correctly:
```
TImage::PixelType m_Label;
int               m_Axis;
bool              m_HeuristicAlignment;
```
but this does not:
```
typename PixelType m_Label;
int  m_Axis;
bool m_HeuristicAlignment;
```

**Comment by mihaipopescu** [comment]
Could you also dump the tokenization map using the `-p` flag ? I suspect something fishy going on there around the `typename` keyword.

**Comment by dzenanz** [comment]
[debug.txt](https://github.com/uncrustify/uncrustify/files/420998/debug.txt)

**Comment by mihaipopescu** [comment]
Ok nothing strange but I'm seeing from your log you don't seem to have tested setting other value to `align_var_def_span` like 10 or something else ? Can you try this ?

**Comment by dzenanz** [comment]
Setting it to 2 works for this example because there is `aLongTypeNameButNotSpecial m_Label;` and everything is aligned to it. If I remove it the problem of misalignment remains. Setting it to 1, 2, 4 of 15 does not align `typename TImage::PixelType m_Label;`

**Comment by mihaipopescu** [comment]
Ok, indeed there was an issue. I've debugged the code and found it. I'll prepare a PR.
