### ISSUE TITLE
Alignment of second line of a ternary conditional operator

### ISSUE THREAD

**Issue by jayvdb** [uncrustify/uncrustify#638]
For ternary conditional operators, especially when the line length is exceeded, I would like the line split on the `:`, and the second line to be aligned to after the `?`.

i.e. the following:

``` c
    y = x ? foo :
            bar;

    if (x ? foo :
            bar) {
        baz;
    }
```

I cant find an existing incantation to achieve this.  My apologies if that is already possible.

**Comment by jayvdb** [comment]
They are currently being reformatted to be:

```c
    y = x ? foo :
        bar;

    if (x ? foo :
        bar) {
        baz;
    }
```

I suspect that I can improve the way it is reformatted, but I would prefer it isnt reformatted.

**Comment by gmaurel** [comment]
Please push your actual config

**Comment by jayvdb** [comment]
@gmaurel , how is my config related?

Are you implying that there is support for aligning ternary conditional operators spanning multiple physical lines as I have indicated in the first post?

**Comment by gmaurel** [comment]
Are you using an empty config?

**Comment by jayvdb** [comment]
I have tried empty config, and 50+ other config combinations. None appear
to add support for the special indentation alignment I need for ternary
conditional operators.
I've also dug around in the source and not found the functionality I need.

**Comment by bengardner** [comment]
I don't think there is an option for that style.   A new option would be needed.

**Comment by Soukyuu** [comment]
If such an option will be added, I'd like to also be able to align the ternary operator like this, if possible:
```
int a = flag ? b
             : b + c;
```
That's about the only thing missing for me to be able to uncrustify my code, I'm amazed how far I got considering how early some of the other tools I tried failed...

**Comment by jayvdb** [comment]
I would be happy to switch code to the same style as @Soukyuu offers directly above:
```
int a = flag ? b
             : b + c;
```

And likewise, this is the last hurdle for me; I can swallow most other minor changes needed to deploy uncrustify, but ... the currently imposed layout for ternary conditional operators is a deal-breaker.

**Comment by mihaipopescu** [comment]
@Soukyuu @jayvdb This option will be nice indeed ! Patches are most welcomed !
