### ISSUE TITLE
Ignore lines matching regex

### ISSUE THREAD

**Issue by jayvdb** [uncrustify/uncrustify#640]
As there is no intention to allow a configuration that would not change anything (https://sourceforge.net/p/uncrustify/feature-requests/125/) , there will always be the odd occasion that uncrustify has bugs or deficiencies that make its output less desirable (or even completely unacceptable), compared to human crafted layout.

It would be nice to be able to specify that lines matching a regex (or similar) should be left unmodified by uncrustify.
A very dumb approach that is strictly input line based, rather than logical C statement based, would suffice.

A variation on this would be to have a lint mode (https://sourceforge.net/p/uncrustify/feature-requests/130/), or a lint wrapper, that exposes the source code line with the error so that some lines can be conditionally suppressed using regex.

**Comment by jayvdb** [comment]
Ah, I see `disable_processing_cmt` and `enable_processing_cmt` can be used to workaround problems by demarcating regions in the source.

I would prefer an out-of-source option.

**Comment by mihaipopescu** [comment]
There are ways to get around that from an out-of-source approach. You can have a wrapper preprocessor script which takes your regex and replace with a `/* */` comment which you can put back later.

@gmaurel We need a label for _Feature Requests_.

**Comment by gmaurel** [comment]
Done
