### ISSUE TITLE
Q_SIGNALS / Q_SLOTS

### ISSUE THREAD

**Issue by misery** [uncrustify/uncrustify#644]
If we use uncrustify 0.62 or 0.63 the following code will be changed. We expect the same indention of Q_SLOTS and Q_SIGNALS here.

Looks like Q_SIGNALS and Q_SLOTS are not recognized as "slots:" and "signals:". If we use "slots:" and "signals:" instead of the QT macros it works as expected.

```
class test_Dummy
    : public QObject
{
    Q_OBJECT

    public:
        int mDummy;

    private:
        int mDummy2;

    Q_SLOTS:
        void dummyMethod1();
        void dummyMethod1() const;

    public Q_SLOTS:
        void dummyMethod2();
        void dummyMethod2() const;

    private Q_SLOTS:
        void dummyMethod3();
        void dummyMethod3() const;

    Q_SIGNALS:
        void dummyMethod4(int number);
        void dummyMethod4();

};
```

Our used uncrustify.cfg is attached.
[uncrustify.cfg.txt](https://github.com/uncrustify/uncrustify/files/432392/uncrustify.cfg.txt)

**Comment by misery** [comment]
https://sourceforge.net/p/uncrustify/patches/27/

Maybe broken?

**Comment by bengardner** [comment]
Were we going to encourage people to use a config file for QT extension?
In this case, this addition might work:
```
set private Q_SLOTS Q_SIGNALS
```

**Comment by misery** [comment]
Thanks for your answer. If I add your setting it will add a line break between private and Q_SLOTS

```
	private

	Q_SLOTS:
```


This was enough for us.
```
set private Q_SIGNALS
```
