### ISSUE TITLE
Global scope friend declaration misinterpreted

### ISSUE THREAD

**Issue by dzenanz** [uncrustify/uncrustify#646]
`friend class ::MultiLabelMeshPipeline;` declares that a class MultiLabelMeshPipeline from global scope (starting with `::`) is a friend of this class. However, this declaration gets interpreted as something else, and gets formatted as `friend class::MultiLabelMeshPipeline;` (the space between `class` and `::` is removed).

**Comment by mihaipopescu** [comment]
Yes, it's a known issue on our side as well. I didn't had time to report it so thanks for this opportunity.
I have to mention though that in our case it's happening with `sp_before_dc=remove` and `sp_after_dc=remove`. What's your config file look like ?

**Comment by dzenanz** [comment]
Here is the config file. We also have both `sp_before_dc=remove` and `sp_after_dc=remove`.

[uncrustify_itk_aggressive.cfg](https://github.com/uncrustify/uncrustify/files/432866/uncrustify_itk_aggressive.cfg.txt)

**Comment by gmaurel** [comment]
fixed
