### ISSUE TITLE
Group class in align_var_struct_span instead of align_var_def_span?

### ISSUE THREAD

**Issue by dzenanz** [uncrustify/uncrustify#648]
Currently `align_var_def_span` controls alignment of variable/member declarations in both functions and classes, while `align_var_struct_span` controls alignment in structs and unions. Wouldn't it be more logical to group class member declarations together with struct/union than with functions?

I tried adding `align_var_class_span`, `align_var_class_thresh` and `align_var_class_gap` to have separate control over class member declaration alignment, but these tests fail (as reported by CTest):

```
5 - c_sharp_10010 (Failed)
267 - cpp_30018 (Failed)
272 - cpp_30023 (Failed)
436 - cpp_32003 (Failed)
522 - d_40000 (Failed)
528 - d_40006 (Failed)
529 - d_40007 (Failed)
556 - java_80030 (Failed)
```

Should I modify the tests to comply with the separation, join class with struct/union or what?

**Comment by dzenanz** [comment]
Perhaps I should make it backwards compatible by using the new settings only if `UO_align_var_class_span` is non-zero? @mihaipopescu @gmaurel

**Comment by mihaipopescu** [comment]
I think your PR #649 is reasonable. I think the solution is to update the tests as well to take the new option into account. We should mention that in the release notes.

**Comment by dzenanz** [comment]
Done.
