### ISSUE TITLE
Docs included with zip

### ISSUE THREAD

**Issue by jibsen** [uncrustify/uncrustify#650]
As pointed out by @jayvdb in #625, the release zip built by `make_win32.sh` (and now also CPack), only includes `index.html` from `documentation/htdocs`.
- What exactly from that folder is supposed to be included?
- Some things are 7 years old, what is still relevant?
- `index.html` links to nonexistent `uncrustify1.css`, there is a file `uncrustify.css`

**Comment by mihaipopescu** [comment]
I think the package requires everything that is referenced from `index.html`. Wouldn't that be sufficient ?
