### ISSUE TITLE
Can not figure out which options to use to fix extra spaces added to objective-c code

### ISSUE THREAD

**Issue by 1951FDG** [uncrustify/uncrustify#652]
`[(NSMutableDictionary *)infoDictionary removeObjectForKey:@"CFBundleInfoPlistURL"];`

changes to:

`[(NSMutableDictionary *) infoDictionary removeObjectForKey:@"CFBundleInfoPlistURL"];`

`NSMenuItem *menuItem __attribute__((unused)) = (NSMenuItem *)sender;`

changes to:

`NSMenuItem * menuItem __attribute__((unused)) = (NSMenuItem *)sender;`

How do I prevent the extra space from being added after crustification?

[my config file](https://github.com/1951FDG/BBUncrustifyPlugin-Xcode/blob/master/Resources/uncrustify.cfg)

**Comment by guy-maurel** [comment]
You need to set the option:
`sp_after_oc_msg_receiver                          = remove`

Please test it and report!
