### ISSUE TITLE
Update GitHub Wiki home page text

### ISSUE THREAD

**Issue by bengardner** [uncrustify/uncrustify#659]
Since it looks like Uncrustify has mostly switched to GitHub, perhaps the message on the GitHub wiki page should be changed to not encourage filing bug reports on SF.net?

**Comment by mihaipopescu** [comment]
Also, I want to take the opportunity of reiterating that the existing SourceForge bugs were not migrated to GitHub as per #573 even if the issue was closed.

**Comment by gmaurel** [comment]
Yes, this would be fine.

**Comment by mihaipopescu** [comment]
Now that is done I guess we can change this as well.
<img width="420" alt="screen shot 2016-09-09 at 20 21 03" src="https://cloud.githubusercontent.com/assets/272470/18398050/33a6237e-76cb-11e6-896c-4409e4475589.png">

and then we have somehow to stop receiving any incoming new issues from SourceForge (from Admin settings maybe). I think SourceForge could remain just for releasing packages. What do you guys think ?

**Comment by gmaurel** [comment]
@bengardner The transfer is done.
Could you please close the bugs-forum?

**Comment by gmaurel** [comment]
All empty
