### ISSUE TITLE
missing "token_names.h"

### ISSUE THREAD

**Issue by invisible-clew** [uncrustify/uncrustify#662]
I tried to compile Uncrustify, but I received this error:
uncrustify.cpp(16): fatal error C1083: Cannot open include file: 'token_names.h': No such file or directory

Anyway, thanks for the great work! :)

**Comment by jibsen** [comment]
Thanks for the report. It would help a lot if you provide some more information so people have a better chance of reproducing the error. For instance:

  - What OS
  - Which compiler
  - What build system
  - Exact steps you performed up to encountering the error

**Comment by invisible-clew** [comment]
Sorry, my fault... :(
I directly used the Visual Studio project found in "win32" folder, but probably the missing file "token_names.h" is a auto generated file.

**Comment by jibsen** [comment]
If you have Python installed, you can run `make_token_names.bat` to generate `token_names.h` on Windows.

Alternatively, if you use the CMake build system it should be automatically generated.

**Comment by invisible-clew** [comment]
All done using CMake.
Thanks for help, very appreciated! :)
