### ISSUE TITLE
Wrong indentation of 'break'

### ISSUE THREAD

**Issue by invisible-clew** [uncrustify/uncrustify#663]
Empty config.

Simple case, before formatting:

```
void test1( int n )
{
    switch ( n )
    {
    case 1:
    {
        std::cout << "1" << std::endl;
    }
    break;
    }
}

void test2( int n )
{
    switch ( n )
    {
    case 1:
    { std::cout << "1" << std::endl; }
    break;
    }
}
```

After formatting:

```
void test1( int n )
{
    switch ( n )
    {
    case 1:
    {
        std::cout << "1" << std::endl;
    }
    break;
    }
}

void test2( int n )
{
    switch ( n )
    {
    case 1:
    { std::cout << "1" << std::endl; }
                                 break;
    }
}
```

'break' in test1 is ok.
'break' in test2 has a wrong indentation.

**Comment by mihaipopescu** [comment]
I don't understand if this is before or after formatting.

**Comment by invisible-clew** [comment]
Sorry, you are right! :)

Before:

```
void test2( int n )
{
    switch ( n )
    {
    case 1:
    { std::cout << "1" << std::endl; }
    break;
    }
}
```

After:

```
void test2( int n )
{
	switch ( n )
	{
	case 1:
	{ std::cout << "1" << std::endl; }
		                         break;
	}
}
```

**Comment by mihaipopescu** [comment]
I guess you'll need to find the proper combination of options to achieve your wanted formatting. What is your expected formatting result ?

**Comment by invisible-clew** [comment]
In my real configuration, I use those options:

```
indent_with_tabs   = 0
indent_columns     = 4
indent_switch_case = 4
indent_case_brace  = 4
```

Code before formatting (expected unchanged after formatting):
```
void test()
{
    switch ( n )
    {
        case 1:
            std::cout << "1";
            break;

        case 2:
            {
                std::cout << "2";
            }
            break;

        case 3:
            { std::cout << "3"; }
            break;
    }
}
```

After formatting I obtain this:
```
void test()
{
    switch ( n )
    {
        case 1:
            std::cout << "1";
            break;

        case 2:
            {
                std::cout << "2";
            }
            break;

        case 3:
            { std::cout << "3"; }
                                break;
    }
}
```

It seems strange the position of the last 'break'.

**Comment by mihaipopescu** [comment]
uh ok, you're right ! It probably thinks it's an oneliner and it doesn't add newlines and the indentation is dependent on the previous brace close. Can you play with oneliner options as a workaround ?

**Comment by invisible-clew** [comment]
I set all *_leave_one_liners options to false, but that line always remains unchanged. Probably I miss the right option (or I didn't understand your suggestion).
Anyway, it's not a great problem, I can manually change my code for the moment.

PS: Thanks for your patience! :D

**Comment by evsh** [comment]
I have a similar issue. My configuration is:
```
indent_with_tabs		= 0
indent_columns	    	= 4
indent_switch_case		= 0
indent_case_shift		= 0
indent_case_brace		= 4
```
The following example:
```C++
switch (var) {
case 1: {
    }
    anything;
    break;
}

switch (var) {
case 1: {
    }
    break;
}
```
uncrustify trasforms into:
```C++
switch (var) {
case 1: {
    }
    anything;
    break;
}

switch (var) {
case 1: {
    }
        break;
}
```

There seems to be a problem when there is nothing between closing brace and `break`. And when 
`mod_move_case_break             = true`, the indentation of 'break' is the same, but inside the braces:
```C++
switch (var) {
case 1: {
        break;
    }
}
```

**Comment by guy-maurel** [comment]
This is correct, as wished from invisible-clew.
break becomes the indentation of the opening brace if the previous is a closing brace.

**Comment by evsh** [comment]
What can I do to disable this, please?

**Comment by guy-maurel** [comment]
uncrustify cannot do disable.

**Comment by mihaipopescu** [comment]
That doesn't mean that we should fix issues as per "first come first served". @evsh please state your case in another issue.

**Comment by Krizai** [comment]
Experiencing the same issue
```
+ (void)analyticsEventForType:(int)eventType
{
    switch (eventType) {
        case 2: {
            eventName = @"1";
        }
        break;

        case 1: {
            eventName = @"1";
        }
        break;

    }

}
```
becomes
```
+ (void)analyticsEventForType:(int)eventType
{
    switch (eventType) {
        case 2: {
            eventName = @"1";
        }
                break;

        case 1: {
            eventName = @"1";
        }
                break;

    }

}

```

**Comment by mihaipopescu** [comment]
I think it's time to create a new issue referencing back this one.
