### ISSUE TITLE
priority question about newline after semicolon

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#665]
Looking at newlines.cpp one can see "nl_after_semicolon" has priority above "nl_after_class"
I have a configuration file with `nl_after_semicolon = true` and `nl_after_class = 5` and get only a blank line.
Is it what we wanted to have?

**Comment by todd-richmond** [comment]
I've had several similar problems with new line handling attempting to adhere to the Sun standard and have never been able to get it right. Shouldn't nl_after_semicolon be the lowest priority so that all the specific config settings for particular cases take precedence?

**Comment by mihaipopescu** [comment]
@gmaurel what is the conclusion? What was the action taken?
