### ISSUE TITLE
Extra newline with 'nl_after_brace_close'

### ISSUE THREAD

**Issue by invisible-clew** [uncrustify/uncrustify#666]
Config:

```
indent_else_if       = true
nl_after_brace_close = true
```

Here's a (dummy) example.
Code before formatting (expected unchanged after formatting):

```
bool test()
{
    if ( true )
    {
        i = 10;
    }
    else
        if ( true )
        {
            i = 10;
        }
}
```

After formatting:

```
bool test()
{
    if ( true )
    {
        i = 10;
    }
    else
        if ( true )
        {
            i = 10;
        }

}
```

Note the extra newline before the last closed brace.

**Comment by mihaipopescu** [comment]
Nice catch! What happens if you add braces on else as well ?

**Comment by invisible-clew** [comment]
With braces, the result is ok!
```
bool test()
{
	if ( true )
	{
		i = 10;
	}
	else
	{
		if ( true )
		{
			i = 10;
		}
	}
}
```

Another thing, if I run Uncrustify N times, it adds N newlines.
For example, after 5 runs:
```
bool test()
{
	if ( true )
	{
		i = 10;
	}
	else
		if ( true )
		{
			i = 10;
		}





}
```

**Comment by mihaipopescu** [comment]
Yeah. I guess the `nl_after_brace_close ` option checks also for "virtual" braces as well. Shouldn't be hard to fix if you do a little debug.

> Another thing, if I run Uncrustify N times, it adds N newlines.

That's an instability. There are like 3 known instabilities which have to be addressed at one point.

**Comment by guy-maurel** [comment]
A bugfix is proposed at #1135

**Comment by gmaurel** [comment]
Fixed
