### ISSUE TITLE
`sp_func_call_paren = remove` removing space of const function pointer variables

### ISSUE THREAD

**Issue by Snaipe** [uncrustify/uncrustify#668]
uncrustify.cfg:

```
sp_func_call_paren = remove
```

test.cc:

``` c++
#include <cstdlib>

namespace foo {
void (*const test)(void *) = std::free; // should be "void (*const test)(void *) = std::free"
}

int main(void) {
       foo::test (nullptr); // should be "foo::test(NULL);"
}
```

Applying the config yields this diff:

``` patch
diff --git a/test.cc b/-
index a2cd09d..0000000 100644
--- a/test.cc
+++ b/-
@@ -1,9 +1,9 @@
 #include <cstdlib>

 namespace foo {
-void (*const test)(void *) = std::free; // should be "void (*const test)(void *) = std::free"
+void(*const test)(void *) = std::free;  // should be "void (*const test)(void *) = std::free"
 }

 int main(void) {
-       foo::test (nullptr); // should be "foo::test(NULL);"
+       foo::test(nullptr); // should be "foo::test(NULL);"
 }
```

1rst change is wrong, 2nd is expected.

**Comment by Snaipe** [comment]
Follow-up to show that the `const` seems to be triggering the issue:

```c++
#include <cstdlib>

namespace foo {
void (*test)(void *) = std::free; // should be "void (*const test)(void *) = std::free"
}

int main(void) {
       foo::test (nullptr); // should be "foo::test(NULL);"
}
```

resulting diff:

```patch
diff --git a/test.cc b/-
index 1e383a4..0000000 100644
--- a/test.cc
+++ b/-
@@ -5,5 +5,5 @@ void (*test)(void *) = std::free; // should be "void (*const test)(void *) = std
 }
 
 int main(void) {
-       foo::test (nullptr); // should be "foo::test(NULL);"
+       foo::test(nullptr); // should be "foo::test(NULL);"
 }
```

**Comment by gmaurel** [comment]
I don't anderstand what for is the line void (*test)(void *) = std::free;
Could you please explain for me? Thanks.

The second line needs the option sp_type_func=force

**Comment by Snaipe** [comment]
> I don't anderstand what for is the line void (*test)(void *) = std::free;
> Could you please explain for me? Thanks.

This declares a variable named test of function pointer type taking a `void *` parameter and return type `void`, and initializes it to the address of the `std::free` function.

> The second line needs the option sp_type_func=force

 This change is actually expected, I included it to show the current behaviour of `sp_func_call_paren=remove`

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!

**Comment by gmaurel** [comment]
No answer --> I close the call
