### ISSUE TITLE
Case statement brackets identation wrong if inline array defined

### ISSUE THREAD

**Issue by csoriano89** [uncrustify/uncrustify#669]
Given this code and the uncrustify.cfg attached:

```
static const test test2 [] =
{
    {test3}
};

switch (container->details->dnd_info->drag_info.data_type)
{
    case NAUTILUS_ICON_DND_GNOME_ICON_LIST:
        {
        }
        break;
}
```

The case brackets are wrongly aligned. The expected alignment is:

```
switch (container->details->dnd_info->drag_info.data_type)
{
    case NAUTILUS_ICON_DND_GNOME_ICON_LIST:
    {
    }
    break;
}
```

This doesn't happen when the array inline declaration is removed, or even just removing the actual value "{test}". So uncrustify work for most of the my project code, except for those files with an inline array declaration.

**Comment by csoriano89** [comment]
[uncrustify.txt](https://github.com/uncrustify/uncrustify/files/456713/uncrustify.txt)

**Comment by CDanU** [comment]
Your example with the provided config generates the expected result on d4f1e03ab91caa2f4c04a5edf21e569db69d8bf3.

**Comment by csoriano89** [comment]
Yes, thanks!
