### ISSUE TITLE
JAVA - Indent continue does not work for class definitions

### ISSUE THREAD

**Issue by kaiser101** [uncrustify/uncrustify#670]
According to JAVA convention, continued lines should be indented by 2 tab stops rather than one. In uncrustify this is controlled by indent_continue.

When long class definitions are split at code_width, the next line is indented only by indent_columns. The indent_continue does not come into play. It works for function calls or statements but not for class definitions.

Class definition:
public class AReallyReallyLongClassName extends AnotherReallyLongClassName<MyTemplate> {

My configuration:
code_width = 80
indent_columns = 4
indent_continue = 4

Expected:

```
public class AReallyReallyLongClassName extends 
        AnotherReallyLongClassName<MyTemplate> {
```

Actual:

```
public class AReallyReallyLongClassName extends 
    AnotherReallyLongClassName<MyTemplate> {
```

**Comment by kaiser101** [comment]
I did some investigation and found that it is actually indented correctly for the first pass. But then indent_line is called a second time from indent.cpp on line 2112 and thats when it goes wrong. The second call to indent sets the indent_column back to 5 spaces.

**Comment by gmaurel** [comment]
@paolodedios
Could you make a pull request for that?

**Comment by paolodedios** [comment]
@gmaurel I don't believe I have a authored a commit referencing this issue.  Github seems to be referring to one of your commits that I merged into my fork.

**Comment by kaiser101** [comment]
Any updates on this?

**Comment by mihaipopescu** [comment]
@paolodedios it was an old convention when we used #sourceforge_bug_id which got github confused.

**Comment by mihaipopescu** [comment]
@kaiser101 unfortunately not but patches are more than welcomed !

**Comment by nevercast** [comment]
I'm not savvy enough to provide a patch for this unfortunately, but something that I'd consider a temporary solution is using Google's Java formatter. Obviously because it's Google's there is no option to change the style, it just follows their in-house standard. But for me it will tide me over until I can use Uncrustify again.

**Comment by guy-maurel** [comment]
Duplicate to #672, 1109

**Comment by guy-maurel** [comment]
PR #2204 is a bugfix proposal.
Please test it and report.

**Comment by kaiser101** [comment]
I will test it over the weekend and report. Thanks for the update. Big help.

**Comment by kaiser101** [comment]
I tried it with the following. But it does not seem to work. Indents by 4 spaces only.
[670.cfg.txt](https://github.com/uncrustify/uncrustify/files/2896958/670.cfg.txt)
[A_Really_Really_Long_Class_Name.java.txt](https://github.com/uncrustify/uncrustify/files/2896959/A_Really_Really_Long_Class_Name.java.txt)

**Comment by gmaurel** [comment]
With your data, I get:
```.java
public class A_Really_Really_Long_Class_Name extends
        Another_Really_Long_Class_Name {
}
```

**Comment by kaiser101** [comment]
Can you help me with the binary please? Maybe I am doing something wrong while building the code.

**Comment by guy-maurel** [comment]
Yes. Which OS? Which e-mail address?

**Comment by kaiser101** [comment]
Windows 7 64 bit. 

kaiser101@gmail.com

Thanks.

**Comment by kaiser101** [comment]
Works now, thanks. We can close this.
