### ISSUE TITLE
Adding unwanted spaces in the protocol specification when casting inside a method call

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#673]
[(id<TextViewObserver>)self.escNotifier textDidChange:textView.text];

becomes 

[(id < TextViewObserver >)self.escNotifier textDidChange:textView.text];

Reported by: micahhainline

Original Ticket: [uncrustify/bugs/566](https://sourceforge.net/p/uncrustify/bugs/566)

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
