### ISSUE TITLE
Two passes required to uncrustify nested class methods

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#678]
Given this code:

```
class C
{
    class D { void F() {} }
}
```

and this config...

```
indent_class=true
nl_class_leave_one_liners=true
nl_class_brace=force
```

I would expect it to go straight to this output:

```
class C
{
	class D
	{
		void F() {}
	}
}
```

However, it initially has to go to this intermediate output first:

```
class C
{
	class D { void F() {}
	}
}
```

So I need to run Uncrustify twice to get the output I expect (and then it stabilizes). The bug is that it should only require a single pass.

Attachments:

  * test.cs: input
  * test.cfg: config file
  * test1.cs: output after first pass
  * test2.cs: output after second pass (expected to be output from test.cs)

Reported by: @scottbilas

Original Ticket: [uncrustify/bugs/614](https://sourceforge.net/p/uncrustify/bugs/614)

**Comment by gmaurel** [comment]
Yes. But the first run is only necessary once for the project.

**Comment by mihaipopescu** [comment]
I was wrong with that comment. The issue is still present.
