### ISSUE TITLE
Objective-C blocks: Allow aligning just like regular blocks

### ISSUE THREAD

**Issue by nschum** [uncrustify/uncrustify#68]
Currently, uncrustify indents Objective-C blocks like this:

```
id foo = [bar execute:^(NSNumber * value) {
              [value doSomething];
          }];
```

The following seems to be the most common way to indent this and I'd like to request an option for it:

```
id foo = [bar execute:^(NSNumber * value) {
    [value doSomething];
}];
```

The mixed indentation seems to be off, too. `[value doSomething]` is indented mostly using spaces, `}]` using mostly tabs.

```
input_tab_size                          = 4        # number
output_tab_size                         = 4        # number
```

**Comment by carlossless** [comment]
I second @kuon comment, this issue should probably be reopened to address nested blocks. And found another issue regarding multiple parameter blocks.

Here's what I want:
```
[UIView transitionWithView:self.view.window duration:0.75 options:UIViewAnimationOptionTransitionFlipFromRight animations:^{
            [self presentViewController:viewController animated:NO completion:nil];
}
complete:^{}];
```

Here's what I get:
```
[UIView transitionWithView:self.view.window duration:0.75 options:UIViewAnimationOptionTransitionFlipFromRight animations:^{
            [self presentViewController:viewController animated:NO completion:nil];
        }

                          complete:^{}];
```

**Comment by sghiassy** [comment]
There's also flag `indent_oc_block_msg_xcode_style` which you can set to `true`

**Comment by revile** [comment]
`indent_oc_block_msg_xcode_style` doesn't seem to work properly with nested blocks either.
