### ISSUE TITLE
Request for options to control C# 'where' constraint clauses

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#680]
Given this code:

```
class C<T1, T2>
    where T1 : D
where T2: D
{
    void F<T3, T4>()
        where T3 : D
    where T4: D
    {
    }
}
```

And this config:

```
indent_class=true
```

I get this result:

```
class C<T1, T2>
    where T1 : D
    where T2 : D
{
    void F<T3, T4>()
    where T3: D
    where T4: D
    {
    }
}
```

First, there is an inconsistency in how the indentation and colon spacing happens. In the class constraints, the clauses are indented and the colon gets spaces on either side. In the method constraints, the clauses are not indented and only the right side of the colon gets a space. These should at least be the same by default (I personally prefer how class constraints are formatted, which is a common style).

Second, I'd like to be able to have options to control the spacing and indentation of these.

Reported by: @scottbilas

Original Ticket: [uncrustify/bugs/625](https://sourceforge.net/p/uncrustify/bugs/625)

**Comment by gmaurel** [comment]
@mihaipopescu 
Do you have clean it for us?

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

**Comment by mihaipopescu** [comment]
Yes. You can close it. Most of the code is already upstream anyway.
