### ISSUE TITLE
Newline count after interface and class definitions 

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#681]
How do I add empty line after interface and class definitions and before @end?

**Existing code:**

@interface MyClass ()
@property (nonatomic, weak) UIView *someView;
@property (nonatomic, weak) UIView *anotherView;
@end
@implementation MyClass
- (void)someKindOfFunction
  {
  some code;
  }
- (void)anotherOfFunction
  {
  some code;
  }
  @end

**Desired code:**

@interface MyClass ()

@property (nonatomic, weak) UIView *someView;
@property (nonatomic, weak) UIView *anotherView;

@end

@implementation MyClass
- (void)someKindOfFunction
  {
  some code;
  }
- (void)anotherOfFunction
  {
  some code;
  }

@end

Reported by: fuxlud

Original Ticket: [uncrustify/bugs/648](https://sourceforge.net/p/uncrustify/bugs/648)

**Comment by denghui1010** [comment]
+1

**Comment by guy-maurel** [comment]
Two new options are necessary

**Comment by guy-maurel** [comment]
PR #2495 is a bugfix proposal.
Please test it and report.
