### ISSUE TITLE
Trigraph ??' causes uncrustify to improperly parse file

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#683]
While trying to convince others in my group to use uncrustify to clean up old, unformatted code, the testfile that I chose happened to have the trigraph ??' in it.  (In particular, the code looked like "src ??'= 0x40" .)  Uncrustify missed that ??' was actually the character ^ and instead treated it like an open quote, pulling in everything until it hit an apostrophe in the word "don't" in a comment record and causing it through multiple missing brace type messages.  I can write a Perl script or use sed to remove the trigraph before running uncrustify for our purposes, if need be, but uncrustify should catch this situation itself.

Reported by: gftaylor

Original Ticket: [uncrustify/bugs/658](https://sourceforge.net/p/uncrustify/bugs/658)

**Comment by CDanU** [comment]
I'm on this.

**Comment by gmaurel** [comment]
is solved by #1131
