### ISSUE TITLE
split_fcn_params fails to properly split function calls with very long first argument

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#684]
`split_fcn_params` fails to properly split function calls with very long first argument.

In the folllowing example (attached as input.c)

```
int main(int argc, char *argv[])
{
    int a, b, c;

    printf("This is a very long string that goes beyond the code_width, and it should not be split", a, b, c);

    return 0;
}
```

with configuration (attached as test.cfg):

```
# True:  indent continued function call parameters one indent level
# False: align parameters under the open paren
indent_func_call_param                    = false    # false/true

# Try to limit code width to N number of columns
code_width                                = 80       # number

# Whether to fully split long function protos/calls at commas
ls_func_split_full                        = false    # false/true
```

uncrustify produces

```
int main(int argc, char *argv[])
{
    int a, b, c;

    printf(
            "This is a very long string that goes beyond the code_width, and it should not be split", a, b,
            c);

    return 0;
}
```

while it should produce

```
int main(int argc, char *argv[])
{
    int a, b, c;

    printf("This is a very long string that goes beyond the code_width, and it should not be split",
            a, b, c);

    return 0;
}
```

Note that adding a new line after the fparen open when indent_func_call_param is set to false is meaning less.
Also note that it only puts c in a new line, which is not the best we can do.

Using 0.62 (and tested with master as well)

Reported by: zakkak

Original Ticket: [uncrustify/bugs/665](https://sourceforge.net/p/uncrustify/bugs/665)

**Comment by guy-maurel** [comment]
Using a long name for the function such as:
```
        AAAAAAAAAAAAAAAAAAAprintf(
                "This is a very long string that goes beyond the code_width, and it should not be split",
```
it is better to split.
A better result cannot be achieve with uncrustify. Sorry.

**Comment by dcommander** [comment]
This is a problem for me as well, and I don't understand why `nl_func_call_start_multi_line` couldn't be extended to cover the case of function calls with long arguments.  Uncrustify is inserting a newline after the '(', which is similar to what would happen if `nl_func_call_start_multi_line=true`, but in this case, it isn't giving the user the ability to control that behavior.  printf() is never going to be a long function name.
