### ISSUE TITLE
Rewrite comment output code

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#692]
The comment output code currently cannot reflow the comment text.  The cmt_width option is a simple start, but it doesn't work quite right.

Details will follow in comments.

Reported by: @bengardner

Original Ticket: [uncrustify/feature-requests/74](https://sourceforge.net/p/uncrustify/feature-requests/74)

**Comment by gmaurel** [comment]
Example:
 1 is OK.
 2 is not OK.
 3 is not OK.
 4 is OK.
 5 is OK.
 8 is OK.

**Comment by CDanU** [comment]
Issue #113 is related to this issue.
