### ISSUE TITLE
cmt_insert_oc_msg_header missing $(javaparam) output

### ISSUE THREAD

**Issue by eidng8** [uncrustify/uncrustify#71]
Not sure if I'm messed up, but I can't get the parameters generated in comment block.

Content in the comment header file:
/**
- $(message)
- <Description here>
  *
- $(javaparam)
  */

Generated comment:
/**
- setObject:forKey:
- <Description here>
  *
  *
  */
  - (void)setObject:(id)value forKey:(id)key

**Comment by gmaurel** [comment]
Please push a complete source example, the config file and the result you wish to get

**Comment by gmaurel** [comment]
NoResponse
