### ISSUE TITLE
How to create a null configuration

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#710]
Hi,

Is there a way to generate a null configuration? This is a configuration file
that will not affect the output at all, thereby providing a baseline in which
all the options are false/off/0. That way, I can selectively turn options on
to fix/detect specific coding styles without affecting all other aspects.

The default configuration I get from uncrustify does not have the desired null
effect.

I would like use uncrustify in a project without having to make everyone else
use it. They can adopt it in time, but meantime, I would like to use uncrustify
without stepping on their favourite coding styles.

One use of this is update code incrementally. For example, add spaces to '=' on
the team's code without breaking their favourite comment scheme etc.

UniversalIndent is ideal for visually tuning small code. For looking at the entire
code base and study the effect of an option, uncrustify can be batched more easily.

Thanks,

Reported by: khtan

Original Ticket: [uncrustify/feature-requests/125](https://sourceforge.net/p/uncrustify/feature-requests/125)

**Comment by gmaurel** [comment]
One must first recognize which option is applicable on each part of the code.
Second one must detect the value for this option.
If each option gets more than one value over the file(s), it is not possible to do anything.

**Comment by swilmet** [comment]
Filed https://github.com/uncrustify/uncrustify/issues/820 with the same goal, but with a better description.

(the purpose is not to find the current uncrustify configuration of a certain codebase, the purpose is to ignore all options except a few).
