### ISSUE TITLE
align #define values at fixed column

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#719]
#define blocks will currently align values based on the longest name, but I need a way to align at a column if possible. The reason is that I have lots of code with multiple #define blocks - 1 for each set of like items. I would like all blocks to align on the same column rather than different columns for each block. Something like the column parameter for trailing comments (I use 41) and have it obey tabstop settings

For example

#define F_ULOCK         0
#define F_LOCK          1
#define F_TLOCK         2
#define F_TEST          3

#define F_RDLCK         0
#define F_WRLCK         1
#define F_UNLCK         2
#define F_GETLK         5
#define F_SETLK         6
#define F_SETLKW        7

formats to this instead of values @ column 41

#define F_LOCK  1
#define F_TLOCK 2
#define F_TEST  3

#define F_RDLCK         0
#define F_WRLCK         1
#define F_UNLCK         2
#define F_GETLK         5
#define F_SETLK         6
#define F_SETLKW        7

Reported by: richmond

Original Ticket: [uncrustify/feature-requests/138](https://sourceforge.net/p/uncrustify/feature-requests/138)

**Comment by stleusc** [comment]
another good one.
seems like there is not much focus on Enhancements lately?!

**Comment by mihaipopescu** [comment]
@stleusc I agree there isn't too much focus on what you called _Enhancements_ lately but a lot of people are working on making uncrustify better in any way they can. Patches are more than welcomed. Please take a look at https://github.com/uncrustify/uncrustify/blob/master/CONTRIBUTING.md if you want to join the effort. Thanks for your feedback and interest.

**Comment by juancols** [comment]
Hi guys, does anyone know if this feature was implemented? Thanks!

**Comment by guy-maurel** [comment]
Sorry, the comment before is wrong!
You need to use:
```
align_pp_define_span = 1
align_pp_define_gap  = 4
```
to get what you wish:
```
#define F_ULOCK    0
#define F_LOCK     1
#define F_TLOCK    2
#define F_TEST     3

#define F_RDLCK     0
#define F_WRLCK     1
#define F_UNLCK     2
#define F_GETLK     5
#define F_SETLK     6
#define F_SETLKW    7
```
