### ISSUE TITLE
 "span" functionality to align same func name params.

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#720]
It would be nice to convert this:
foo1( x,  y );
foo1(xxx,  yyy);
foo2(x, y);
foo1(xxxxxxx,   yyyyyyy);
foo1(xxxxx,    yyyy);

to this (using the align_same_func_call_params option); note that the foo1 calls are "interrupted" by a foo2 call:

foo1( x,            y );
foo1(xxx,          yyy);
foo2(x, y);
foo1(xxxxxxx,   yyyyyyy);
foo1(xxxxx,      yyyy);

Reported by: gdukeman1964

Original Ticket: [uncrustify/feature-requests/139](https://sourceforge.net/p/uncrustify/feature-requests/139)

**Comment by gmaurel** [comment]
cannot see what you wanted to get.

**Comment by CJCombrink** [comment]
I guess the reporter wanted:
```
foo1( x, y );
foo1(xxx, yyy);
foo2(x, y);
foo1(xxxxxxx, yyyyyyy);
foo1(xxxxx, yyyy);
```

to be aligned as
```
foo1( x,       y );
foo1(xxx,     yyy);
foo2(x, y);
foo1(xxxxxxx, yyyyyyy);
foo1(xxxxx,   yyyy);
```

**Comment by CJCombrink** [comment]
I have a similar request, a span for `align_same_func_call_params` but a different desire.

Uncrustify aligns my code as follow (using min() as an example) with `align_same_func_call_params = true` : 
```
  min( 1,              0 );
  min( 10,             0 );
  min( 100,            0 );
  min( 1000,           0 );
  min( 10000,          0 );

  min( 100000000000,   0 );
  min( 10000000000000, 0 );
  min( 10000000000000, 0 );
```

I would hope that the requested `span` of `1` would result in:
```
  min( 1,     0 );
  min( 10,    0 );
  min( 100,   0 );
  min( 1000,  0 );
  min( 10000, 0 );

  min( 100000000000,   0 );
  min( 10000000000000, 0 );
  min( 10000000000000, 0 );
```

@gmaurel should I create a new issue or can this one perhaps be re-opened?

Using Uncrustify-0.67

**Comment by CJCombrink** [comment]
I see that this was added with version 0.68.1 `align_same_func_call_params_span`
