### ISSUE TITLE
Curly bracket after @interface

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#726]
Hi,
In an objC class, I would like the option to put the curly bracket in a new or in the same line:

@interface TestViewController : UIViewController <UIActionSheetDelegate>
{
Something *something;
}

into

@interface TestViewController : UIViewController <UIActionSheetDelegate> {
Something *something;
}

Thanks.

Reported by: *anonymous

Original Ticket: [uncrustify/feature-requests/155](https://sourceforge.net/p/uncrustify/feature-requests/155)

**Comment by guy-maurel** [comment]
Fixed at https://github.com/uncrustify/uncrustify/commit/74d8571a095f3700909167d6020de5ee21aae077
