### ISSUE TITLE
class formatting

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#729]
Would it be possible to add an option to control the formatting of base classes for c++? This would be similar to the leading comma and colon for initialization lists.

Input:
class Foo : public Bar, public Baz {
 public:
        Foo();
};

Desired Output:
class Foo
    : public Bar
    , public Baz
{
public:
        Foo();
};

Reported by: jdegesys

Original Ticket: [uncrustify/feature-requests/159](https://sourceforge.net/p/uncrustify/feature-requests/159)

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!

With the options:
```.cfg
pos_class_colon    = lead  
nl_class_colon     = force 
nl_class_init_args = force 
pos_class_comma    = lead 
nl_class_brace     = force
```
you get:
```.cpp
Uncrustify_d-0.67-154-441e735
class Foo
        : public Bar
        , public Baz
        , public Xyz
{
public:
Foo();
};
```
