### ISSUE TITLE
Leading comma for function calls

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#732]
It would be nice if the following formatting existed:
Input:

```
:::c
foo(this_would_only_occur, if_this_line_was_really_long, and_you_had_to_wrap_the_arguments);
```

Output:

```
:::c
foo( this_would_only_occur
   , if_this_line_was_really_long
   , and_you_had_to_wrap_the_arguments
   );
```

Note the leading space for the function call. This would only be added when wrapped with leading commas. Otherwise, sp_inside_fparen would prevail. Also, note the final closing ')' This should only be placed on a new line if the args are wrapped, otherwise nl_func_decl_end (or nl_func_def_end/nl_func_call_end) would prevail.

Reported by: jdegesys

Original Ticket: [uncrustify/feature-requests/162](https://sourceforge.net/p/uncrustify/feature-requests/162)

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
With the options:
```.cfg
sp_inside_fparen = force
sp_after_dc      = remove
pos_comma        = lead_force
```
you get:
```.c
::c foo( this_would_only_occur
         , if_this_line_was_really_long
         , and_you_had_to_wrap_the_arguments );
```
