### ISSUE TITLE
New lines after #include, using, import 

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#735]
It would be great to have ability to control number of new lines after #include .../import... set and before next top level entry (for ex. class declaration)

Reported by: ksareal

Original Ticket: [uncrustify/feature-requests/167](https://sourceforge.net/p/uncrustify/feature-requests/167)

**Comment by gmaurel** [comment]
Please, push an source example:
What you have
and
what you expect to get.

**Comment by mxmlnkn** [comment]
#include <iostream>
    class A;

should be uncrustified to:

    #include <iostream>

    class A;
