### ISSUE TITLE
Fill empty lines with spaces

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#744]
Hi,

I would like to have blank lines filled with as many spaces as the current indentation. This makes navigating with the cursor easier, as the cursor will not jump to the first column when moving over such lines.

AStyle has such an option (--fill-empty-lines).

Yours
Markus

Reported by: buehrenm

Original Ticket: [uncrustify/feature-requests/182](https://sourceforge.net/p/uncrustify/feature-requests/182)

**Comment by gmaurel** [comment]
mmmh!
If you are using git, the system inform you about trailing space(s).
We keep it such as.

**Comment by buehrenm** [comment]
Hmm, why not offer this as an option? I am not working with Git...

**Comment by mihaipopescu** [comment]
That is a strange option. What happens if you change the previous line ? Should it also change the next line as well ?

**Comment by buehrenm** [comment]
I am using such an option in my personal C style in Emacs and I am quite confident with it. However, I never checked what exactly happens when adding/removing spaces in consecutive blank/only space lines. When reformatting a whole file it is quite clear how many spaces to add.

**Comment by mihaipopescu** [comment]
As I understand it, this simply adds additional noise to version control. I don't think this can be an acceptable tradeoff just for the sake of a particular way of scrolling in some IDE.

**Comment by buehrenm** [comment]
There is no noise being added as there is no randomness in where to put how many spaces.

**Comment by mihaipopescu** [comment]
By noise I mean "irrelevant change being made when making another change". For instance, say you have this file:

```cpp
int main(int argc, char **argv)
{
(sp)(sp)int a;
(sp)(sp)(sp)(sp)(sp)(sp)
(sp)(sp)return 0;
}
```
if you rename the variable `a` to `foo` you will have two line diffs instead of one.

```diff
 int main(int argc, char **argv)
 {
-  int a;
-        
+  int foo;
+          
   return 0;
}
```

**Comment by buehrenm** [comment]
Then you got me wrong. The file should look like this:

int main(int argc, char **argv)
{
(sp)(sp)int a;
(sp)(sp)
(sp)(sp)return 0;
}

Lines without code shall be filled until the depth of the current indentation.

Markus
Am 29.11.2016, 21:50, Mihai Popescu <notifications@github.com> schrieb:

  
    
      By noise I mean "irrelevant change being made when making another change". For instance, say you have this file:
    
    
      
int main(int argc, char **argv)
{
(sp)(sp)int a;
(sp)(sp)(sp)(sp)(sp)(sp)
(sp)(sp)return 0;
}
    
    
      if you rename the variable a to foo you will have two line diffs instead of one.
    
    
      
 int main(int argc, char **argv)
 {- int a;- + int foo;+
   return 0;
}

**Comment by CDanU** [comment]
Are you sure that your editor does not have such a feature build in? 
Most IDEs do this, some text editors (like kate) have this feature too and for vim and emacs there are plenty of capability extending scripts.

**Comment by buehrenm** [comment]
Sure my editor has that feature but it interferes with uncrustify which doesn't. 
Am 29.11.2016, 22:59, CDanU <notifications@github.com> schrieb:

  
    
      Are you sure that your editor does not have such a feature build in?
      Most IDEs do this, some text editors (like kate) have this feature too and for vim and emacs there are plenty of capability extending scripts.

**Comment by mihaipopescu** [comment]
@buehrenm Ok, you are right, but then consider the case of reindentation.

```cpp
namespace foo
{
class Bar
{
public:
(sp)(sp)Bar();
(sp)(sp)~Bar();
(sp)(sp)
private:
};
}
```

formatted diff:

```diff
 namespace foo
 {
-class Bar
-{
-public:
-  Bar();
-  ~Bar();
-  
-private:
-};
+  class Bar
+  {
+  public:
+    Bar();
+    ~Bar();
+    
+  private:
+  };
 }
```

If I understood correctly, according to your feature request, the line with two spaces must be reindented to have four now. That can noise to version control even if reindentation adds a lot of it already. Note my diff is manufactured - in reality they are uglier.

Uncrustify trims trailing whitespace by default and unfortunately the change is not trivial. There were some similar issues (need to find then).

In the mean time, maybe you can find a plugin for your IDE to move the cursor even if there is no whitespace there. I know that Visual Studio has it and I'm pretty sure you can find something for emacs as well.
