### ISSUE TITLE
C/C++ files, newline after comma in enum block

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#745]
I'd like to have my enum entries each on new lines.  I can't seem to fine a way to do that with uncrustify.  Like this:

```
typedef enum {
    ONE,
    TWO,
    THREE
}
```

Reported by: samw3

Original Ticket: [uncrustify/feature-requests/183](https://sourceforge.net/p/uncrustify/feature-requests/183)

**Comment by gmaurel** [comment]
Not yet available.

**Comment by rustamko** [comment]
It would be nice to check comments before line breaking. Otherwise we have the following:
```
enum X
{
    ITEM1,
    // this is item 1
    ITEM2,
    // this is item 2
    ITEM3 // this is item 3
}
```

**Comment by BigfootN** [comment]
It would indeed be nice to have one line per entry in enumerations.

**Comment by wdobbe** [comment]
Another vote to have the option to keep comments on the same line.

So 
```
enum Foo
{
    ITEM1, // this is item 1
    ITEM2, // this is item 2
    ITEM3  // this is item 3
}
```

i.s.o.

```
enum Foo
{
    ITEM1, 
    // this is item 1
    ITEM2, 
    // this is item 2
    ITEM3 // this is item 3
}
```

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
With the options:
```.cfg
indent_columns        = 3
indent_with_tabs      = 0
sp_inside_braces_enum = remove
nl_enum_own_lines     = force
pos_enum_comma        = trail_force
```
You get:
```.cpp
typedef enum {
   ONE,
   TWO,
   THREE
};
enum abc {
   ONE,
   TWO,
   THREE
};
```
