### ISSUE TITLE
Option for added comments to be C or C++ style

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#746]
The following options can add ("old school") C comments ("/\* comment */"):

mod_add_long_function_closebrace_comment
mod_add_long_namespace_closebrace_comment
mod_add_long_switch_closebrace_comment
mod_add_long_ifdef_endif_comment
mod_add_long_ifdef_else_comment

It would be nice to have a option for these the be ("new school") C++ comments ("// comment") instead.

Reported by: geowar

Original Ticket: [uncrustify/feature-requests/184](https://sourceforge.net/p/uncrustify/feature-requests/184)

**Comment by stefan-nu** [comment]
I'd love this feature too. 

Additionally I would like to have a modification option that converts only single line comments.

**Comment by guy-maurel** [comment]
If the input file has the extention "c" you get an old comment.
If the input file has the extention "cpp" you get a new comment.
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it and report!
