### ISSUE TITLE
aligning initializers in c++ class headers

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#750]
In C++ x11 we can initialize data members with = or {} in the class definition.  Uncrustify aligns ok with = but not with {}.  Maybe it just needs to know '{' is similar to '='.

```

class Greeks
{
        double                  _dRho               = 0.0;
        double                  _dTheoretical       = 0.0;
        double                  _dTheta             = 0.0;
        double                  _dTimeValue         = 0.0;
        double                  _dVega { 0.0 };
        double                  _dVolatility { 0.0 };
        double                  _dPvDiv             = 0.0;
}

```

At least it puts a space before '{'.  

Similar initialization code in a *.cpp has the same behavior:

```
    double      sdf[6]  = { 5.0, 6, 6, 34, 324, 5 };
    int         fsaf[6] = { 5, 6, 6, 34, 324, 5 };
    char        msa[3] { 6, 5, 3 };
    int         y[3] { 6, 5, 3 };

```

Maybe there is a way to align '{' initializers but i suspect c++x11 is just too new for uncrustify.

Reported by: edwinchenloo

Original Ticket: [uncrustify/support-requests/14](https://sourceforge.net/p/uncrustify/support-requests/14)

**Comment by guy-maurel** [comment]
PR #3434 is a bugfix proposal.
Please test it and report.
