### ISSUE TITLE
Lamda flow c++11 broken by removing semicolon. 

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#751]
Use http_examples.cpp
https://github.com/eidheim/Simple-Web-Server.git

Reported by: p8877dril

Original Ticket: [uncrustify/support-requests/17](https://sourceforge.net/p/uncrustify/support-requests/17)

**Comment by gmaurel** [comment]
Please push a simple example source file and the output you expected to get.

**Comment by brianw1** [comment]
Here's a simple example where the semicolon in incorrectly removed.
`
// before
void foo() {
    int count = 0;
    // define a callback function
    auto fun = [&](const TestMsg& msg) {
        count++;
    };
}
`
`
// after
void foo() {
    int count = 0;
    // define a callback function
    auto fun = [&](const TestMsg& msg) {
        count++;
    }
}
`
[uncrustify.cfg.txt](https://github.com/uncrustify/uncrustify/files/1153771/uncrustify.cfg.txt)

**Comment by CDanU** [comment]
Your example works as expected on the current version.

Your Uncrustify version is quiet old, I assume you are on Ubuntu? Unless you are using the LTS (16.04) version there is no reason to not upgrade to version 17.04 (Zesty Zapus). That version has Uncrustify 0.64. Alternatively compile Uncrustify from the sources.

**Comment by yamokosk** [comment]
Does anyone know of a PPA out there for 16.04 with an updated version of uncrustify? Just curious.

**Comment by mihaipopescu** [comment]
I recollect this happening on our fork as well which was 0.64 based.
