### ISSUE TITLE
Indent between #ifdef and #endif blocks?

### ISSUE THREAD

**Issue by bumblebritches57** [uncrustify/uncrustify#766]
I tried searching google for how to indent between ifdef and endif blocks, but nothing's showing up.

In Xcode, it indents all code between ifdef extern statements, and I really wanna replicate that.

    #ifdef __cplusplus
    extern "C" {
    #endif`
        // like this
    #ifdef __cplusplus
    }
    #endif

**Comment by gmaurel** [comment]
uncrustify doesn't make an evaluation of the value
  __cplusplus
You must put the { out of the #ifdef such as
'''#ifdef __cplusplus
extern "C"
#else
void a()
#endif
{
    int a;
    // like this
}
#ifdef __cplusplus
#endif
'''
