### ISSUE TITLE
The length of options names

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#768]
The options names have many different lengths. The bigger one is 49.
Many have 41, 40, 37 or 36 characters.
Ben says, it would nice to limit the length.
Which value should me take?

**Comment by mihaipopescu** [comment]
I think the option names should be as explicit and clear as possible. On the other hand, if it gets too specific then probably that's not fixing the bigger issue. I think everyone can understand an option made of maximum 10 words so basically with an average of 5 characters/word + the 9 underscore characters you can easily end up with options around 60 characters. If you count also the `=value` it's still under the old-school 80 limit characters.

**Comment by gmaurel** [comment]
Merged at https://github.com/uncrustify/uncrustify/pull/770
