### ISSUE TITLE
Oscillatory pointer alignment

### ISSUE THREAD

**Issue by JohnMcCann** [uncrustify/uncrustify#771]
I am not sure if this is the desired behavior, but it seems that having pointers to pointers to etc... variables give uncrustify some difficulties. It looks like the `*` are being used to align the variables (as requested by align_var_def_star_style = 1), but not completely consistently. For example look at this oscillatory behavior.

> original C file  

    typedef struct Foo_s {
      FooBar ***A;
      FoBar ***B;
    }FooS;

> uncrustify configure file

    align_var_def_star_style  = 1
    align_var_struct_span     = 1
    align_var_struct_thresh   = 2

> C file uncrusified once (notice the variables are aligned)

    typedef struct Foo_s {
      FooBar ***A;
      FoBar  ***B;
    }FooS;

> C file uncrustified twice (same as original, with variables unaligned, why does it do this?)

    typedef struct Foo_s {
      FooBar ***A;
      FoBar ***B;
    }FooS;

We are now back at the original state. If you use 

    typedef struct Foo_s {
      FooBar **A;
      FoBar **B;
    }FooS;

there is no oscillatory behavior.

**Comment by JohnMcCann** [comment]
Perhaps more instructive is

> .cfg

    align_var_def_star_style  = 1
    align_var_struct_span     = 1
    align_var_struct_thresh   = 1

> Original (all misaligned by one)

    typedef struct Foo3_s {
      FooBar ***A;
      FoBar ***B;
    }Foo3S;

    typedef struct Foo2_s {
      FooBar **A;
      FoBar **B;
    }Foo2S;

    typedef struct Foo1_s {
      FooBar *A;
      FoBar *B;
    }Foo1S;

    typedef struct Foo_s {
      FooBar A;
      FoBar B;
    }FooS;

> uncrustify once (all aligned except for Foo3S)

    typedef struct Foo3_s {
      FooBar ***A;
      FoBar ***B;
    }Foo3S;

    typedef struct Foo2_s {
      FooBar **A;
      FoBar  **B;
    }Foo2S;

    typedef struct Foo1_s {
      FooBar *A;
      FoBar  *B;
    }Foo1S

    typedef struct Foo_s {
      FooBar A;
      FoBar  B;
    }FooS;

> uncrustify twice (Neither Foo3S or Foo2S aligned)

    typedef struct Foo3_s {
      FooBar ***A;
      FoBar ***B;
    }Foo3S;

    typedef struct Foo2_s {
      FooBar **A;
      FoBar **B;
    }Foo2S;

    typedef struct Foo1_s {
      FooBar *A;
      FoBar  *B;
    }Foo1S;

    typedef struct Foo_s {
      FooBar A;
      FoBar  B;
    }FooS;

**Comment by gmaurel** [comment]
Thanks for the bug.
It is now solved at 2a5e88fd64a506de0856c32e1756ef0b3e2fb2a2
