### ISSUE TITLE
version number is not build correctly

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#773]
@mihaipopescu 
The script make_version.py produces the file uncrustify_version.h
By using cmake and make, make install I get
```
uncrustify --version
uncrustify 0.63_d
```
which is not correct

**Comment by jibsen** [comment]
If you mean the `_d` suffix, then looking at `src/uncrustify_version.h.in`, I guess this is because the default build is debug. Try running CMake with `-DCMAKE_BUILD_TYPE=Release`
