### ISSUE TITLE
0.63 breaks const auto reference alignment

### ISSUE THREAD

**Issue by RoffelKartoffel** [uncrustify/uncrustify#785]
Upgrading from 0.62 to 0.63 changes

    for (const auto& readerName : readerNames)

to

    for (const auto & readerName : readerNames)

Only const auto references seem to be affected. The configuration file is attached. [uncrustify.cfg.txt](https://github.com/uncrustify/uncrustify/files/521195/uncrustify.cfg.txt)

**Comment by gmaurel** [comment]
The actual git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
Release 0.64 is coming end of this week.

**Comment by RoffelKartoffel** [comment]
The issue is indeed solved. Thank you!
