### ISSUE TITLE
a new line about the used OS

### ISSUE THREAD

**Issue by gmaurel** [uncrustify/uncrustify#788]
I would like to print a line about the used OS as using the command option -p
How to build a USED_OS macro text, which could be used by output.cpp
may be with make_version.py

**Comment by mihaipopescu** [comment]
I don't quite understand what you want. What do you mean by "used OS" ? Can you give an example ?

**Comment by gmaurel** [comment]
I like to have a line such as by using the linux command:
uname -a
Linux renard 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mihaipopescu** [comment]
Where you want this line to be printed ? From uncrustify e.g. when you call `uncrustify -p` ?
Why is that relevant for you ?

**Comment by gmaurel** [comment]
Yes, we could add it at the part of options.cpp::save_option_file_kernel
It should help by debugging and if someone send a file generated by -p
Some more informations could be added there latter.

**Comment by mihaipopescu** [comment]
Formatting files should be OS independent. I don't see how that would help. Do you have knowledge of any formatting issue that happens only on one OS and not on the others?

**Comment by gmaurel** [comment]
If an user create a new issue, it might be important to have some informations about the system where uncrustify was running to better anderstand where the problem is.
We might find, in the future, some more informations about the run.
Packing all these in the output generated by -p is a simple way.
