### ISSUE TITLE
"make test" fails for every test

### ISSUE THREAD

**Issue by nivekkagicom** [uncrustify/uncrustify#789]
When I run "make test" with the new cmake build system every test is failing and many are crashing.

[uncrustify]# cd build
[build]# cmake ..
[build]# cmake --build .
[build]# make test
Running tests...
Test project ./uncrustify/build
...
653: Test command: /usr/bin/cmake "-DTEST_PROGRAM=./build/uncrustify" "-DTEST_LANG=ecma" "-DTEST_CONFIG=config/ben.cfg" "-DTEST_RERUN_CONFIG=config/ben.cfg" "-DTEST_INPUT=input/ecma/example-1.es" "-DTEST_RESULT=results/ecma/90000-example-1.es" "-DTEST_OUTPUT=output/ecma/90000-example-1.es" "-DTEST_DIR=./tests" "-P" "./tests/run_test.cmake"
653: Test timeout computed to be: 1500
653: CMake Error at ./tests/run_test.cmake:44 (message):
653:   Uncrustify error: Assertion failed: (ARRAY_SIZE(token_names) ==
653:   CT_TOKEN_COUNT_), function main, file
653:   ./src/uncrustify.cpp,
653:   line 254.
653: 
653: 
653: 
653/653 Test #653: 90000 ............................***Failed    0.01 sec

0% tests passed, 653 tests failed out of 653

**Comment by mihaipopescu** [comment]
Never tried `make test`. I think we're using `ctest` instead.
