### ISSUE TITLE
emscripten build

### ISSUE THREAD

**Issue by CDanU** [uncrustify/uncrustify#796]
@bengardner, @gmaurel 

Take a look at:
https://github.com/CDanU/uncrustify/commits/emscripten
https://cdanu.github.io/uncrustify_config_preview/index.html

and tell me what you think of this.

--------------------

- [x] prepare for Emscripten 0
- [x] prepare for Emscripten 1
- [x] prepare for Emscripten 2 && merge mistake fix
- [x] prepare for Emscripten 3
- [x] ambiguity fix
- [x] Emscripten Interface

**Comment by mihaipopescu** [comment]
@CDanU This is awesome! I was looking for something like this for uncrustify. clang-format has something. Previously it was a bit cumbersome to play with config options. We were using [UniversalIndentGUI](http://universalindent.sourceforge.net/) but what you did is so much better and faster. Thank you!

**Comment by mihaipopescu** [comment]
I'd like to see a PR (or more) to get those changes upstream. :)

**Comment by gmaurel** [comment]
If the tool is usable direct on my processor (not online), it would be very fine.
I don't like to be always on line to test my sources, might be I don't like to upload all my sources.
The output on the right for "sp_arith" is fine. It would be fine to get such examples for all the options.
It is a better documentation to see what is working on. 
I use, for my debugging, the line numbers of the uigui_uncrustify.ini (with universalindentgui),
I only need to put my cursor on the area of the option.
As a developer, I haave option(s) you don't know about. I need to test that. 
I find the display  (with universalindentgui) left the options (such as your display) AND on the right a display of my (changed) source.

**Comment by CDanU** [comment]
Both links are separate projects. 
The first link contains everything that is needed to compile the Uncrustify C++ code into JavaScript.
I would hope the changes that where made in this repo could be merged into the Uncrustify repo.

The second link on the other hand is just an example of what could be done with the JS port. It will not be merged into Uncrustify itself. It is just a preview for now as it is lacking examples, option dependencies, some comport functions and a more automated build process.
At some point this example could be used to aid in development but for now it is targeted at users that have no or an incomplete Uncrustify config file.

As of now the JS port is set up to work completely without the need of a webserver. Later I have to figure out how to enable higher Emscripten optimization settings to significantly reduce the filesize of the generated JS lib ( from 5mb to 1mb ). The higher optimization settings require a server ( like a local node server ) to load a 'pre-compiled' blob. This still would let the execution of the formatting run only locally.

The file that enables the Emscripten build is a fairly simple one: [uncrustify_emscripten.cpp](https://github.com/CDanU/uncrustify/blob/emscripten/src/uncrustify_emscripten.cpp) and some documentation is provided [here](https://github.com/CDanU/uncrustify/blob/emscripten/src/emscripten/usage.txt)

The only problem that I am currently able to see is that I have no clue about cmake and therefore do not know how to integrate the Emscripten build as its own target.

**Comment by mihaipopescu** [comment]
@gmaurel The whole point of this tool is to be an online service but I'm pretty sure you run the tool offline for testing purposes (maybe @CDanU can add some details on this).

**Comment by CDanU** [comment]
Right, the web part, which powered by the port of Uncrustify, is intended to be hosted on a web site. Despite this it does not send out data as everything runs locally on your machine. The website will even work if you download it, cut your internet connection and then open the index.html in your web browser.

**Comment by gmaurel** [comment]
... Additionally some documentation is provided here ...
"here" is broken.

**Comment by CDanU** [comment]
^ updated

**Comment by CDanU** [comment]
> Sorry, wrong question.
I try again:
What is the relation uncrustify <--> emscripten

Ok, here is how the Emscripten process works:
Code (python, **C, C++**, ...) is compiled via the [clang compiler](http://clang.llvm.org/index.html) into a somewhat assembly like format ( LLVM Intermediate Representation (IR) )
And secondly as the main purpose of Emscripten this IR code is rearanged/reformated/optimized into Javascript code. 
More about this process in detail here: [Emscripten: An LLVM-to-JavaScript Compiler](http://fpf3.net/files/emscripten/emscripten/docs/paper.pdf , esp. in section 2)

This allows, as in this endeavour, to transform Uncrustify which consists of C/C++ Code into a version of Uncrustify that purely consists of JavaScript Code. That enables Uncrustify to run on web targets as demonstrated in the very first link that I posted.

**Comment by gmaurel** [comment]
Fine.
Let us try.
Please make lot of little independent PR.
It is better for us to comment and merge.

**Comment by CDanU** [comment]
Ok, I will do that.

-----------------

Going trough the the changes I guess I figured out why bengardner decided to use a list instead of a vector for group_map_value::options, he did not want a vector to cause reallocations while adding the options via unc_add_option(). 

My problem now is that Emscripten most likely won't get the needed [bindings](https://github.com/kripken/emscripten/pull/3475) any time soon.
The solution to that problem would be:
- use vector, add something like UO_option_count for every group ( UO_indent_count as example ) in order to be able to pre-reserve the needed space and prevent reallocations for the groups
- use extra prepocessor defines to let group_map_value::options be a vector only in the Emscripten build.

Which one ( if any ) of those would you accept ?

**Comment by CDanU** [comment]
For some reason I get this funny error messages from the emscripten compiler:
```
In file included from ../align.cpp:11:
../chunk_list.h:203:71: error: use of overloaded operator '[]' is ambiguous (with operand types 'unc_text' and 'int')
   return((pc != NULL) && (pc->len() >= 1) && CharTable::IsKw1(pc->str[0]));
                                                               ~~~~~~~^~
../unc_text.h:164:8: note: candidate function
   int operator[](size_t idx) const
       ^
../chunk_list.h:203:71: note: built-in candidate operator[](const char *, int)
   return((pc != NULL) && (pc->len() >= 1) && CharTable::IsKw1(pc->str[0]));
                                                                      ^
../chunk_list.h:203:71: note: built-in candidate operator[](const volatile char *, int)
```
after 7f268aff6c652be6088fd619d5fccb05bb04f509 was introduced. 
The  [operator[]](https://github.com/uncrustify/uncrustify/blob/7f268aff6c652be6088fd619d5fccb05bb04f509/src/unc_text.h#L164) function is currently causing this. Changing the parameter type back from size_t to int fixes it, but I am not sure wether I actually understand the problem.
I know that a _0_ could be an int, ulong or a const char* which is allowed to be inside those operator brackets. But why is it complaining about ambiguity for functions that don't have the same amount of parameters ? 

`operator[](size_t idx)` 
    **vs** 
`operator[](const char *, int)`
`operator[](const volatile char *, int)`

**Comment by gmaurel** [comment]
Could it be that the expression is too complicated for the emscripten compiler?
Please try:
```
int ch = pc->str[0];
return((pc != NULL) && (pc->len() >= 1) && CharTable::IsKw1(ch));
```
and push the compiler output.

**Comment by CDanU** [comment]
```
In file included from ../align.cpp:11:
../chunk_list.h:203:21: error: use of overloaded operator '[]' is ambiguous (with operand types 'unc_text' and 'int')
    int ch = pc->str[0];
             ~~~~~~~^~
../unc_text.h:164:8: note: candidate function
   int operator[](size_t idx) const
       ^
../chunk_list.h:203:21: note: built-in candidate operator[](const char *, int)
    int ch = pc->str[0];
                    ^
../chunk_list.h:203:21: note: built-in candidate operator[](const volatile char *, int)
```

**Comment by CDanU** [comment]
Looking with the debuger at `int operator[](size_t idx) const` I get to the conclusion that **size_t** should not be used here. 
I get hits when setting up a conditional breakpoint that triggers when [pc_length](https://github.com/uncrustify/uncrustify/blob/e4e0cc7515b26d464dc11f4d42e85aa88f9ce9e9/src/tokenize.cpp#L684) == 0 in tokenize.cpp while uncrustifying _uncrustify.cpp_. 
In `ch        = pc_temp.str[pc_length - 1];` 
`pc_length - 1` becomes -1 and underfloats the size_t.

When the type is **int** the size check 
`return((idx < m_chars.size()) ? m_chars[idx] : 0); `
prevents errors for negative values.

**Comment by gmaurel** [comment]
Please try
```
int ch = pc->str[(size_t)0];
```

**Comment by CDanU** [comment]
Yes that works, but only for this one of four cases where pc->str[0] is used in the code. Changing the other cases accordingly would be ok?

**Comment by gmaurel** [comment]
You can also write something like:
```
#ifdef EMSCRIPTEN
   ... pc->str[(size_t)0];
#else
   ... pc->str[0];
#endif
```
Make a PR for that.
Generate a bug at emscripten.
As the bug is fixed, make a new PR.

**Comment by mihaipopescu** [comment]
I've seen that as well and not because of emscripten.
> When the operator const char *() function is removed ( every chunk_t->str needs to be changed to chunk_t->str.c_str() ) the complaining stops.

I think this is a better approach.

**Comment by CDanU** [comment]
Here are PRs for both approaches, choose one: #829, #830
