### ISSUE TITLE
the space number after '=' and before '('  can't custom define?

### ISSUE THREAD

**Issue by DaSea** [uncrustify/uncrustify#802]
```cpp
void Hello() {
    int x = 3;
    int j = 10;
    if   ((x < 10)
         && (j > 11)) {
        int z = x + j;
    } else {
        int y =   j;
    }
}
```

1. the space number with in `if`  and `((x < 10)` can't custom define?
2. the space number with in `int y = ` and `j` can't custom define?

who can tell me the option? thanks!

**Comment by gmaurel** [comment]
Please use the options
```
sp_before_sparen = force
sp_arith         = force
sp_assign        = force
```
For the question 2, have a look to the options ```xxx_align_xxx```
