### ISSUE TITLE
* as multiplication is taken as pointer in ClassA a( x * y)

### ISSUE THREAD

**Issue by MarcelMeschenmoser** [uncrustify/uncrustify#809]
in v 0.64 the * is taken as a pointer instead of an arithmetical sign in:
`ClassA a(x * y)`
vs
`ClassA a(x* y)`

to force the space around * you would normally use sp_arith=force
but unfortunately the sp_before_ptr_star is taken into account and no space is printed between x and 'x' with:
sp_arith=force
sp_before_ptr_star=remove
`ClassA a(x* y)`

**Comment by gmaurel** [comment]
Please push a little but complete source example which shows the problem.
Join your relevant options file.

**Comment by MarcelMeschenmoser** [comment]
Code Example
[CodeExample.txt](https://github.com/uncrustify/uncrustify/files/581074/CodeExample.txt)

Config File
[uncrustify.txt](https://github.com/uncrustify/uncrustify/files/581072/uncrustify.txt)

As you can see is the x*y operation without a space, because of the sp_before_ptr_start setting!

**Comment by MarcelMeschenmoser** [comment]
This is a reason for me, not to use v0.64.

**Comment by gmaurel** [comment]
Are there any version without this bug?

**Comment by MarcelMeschenmoser** [comment]
v0.62 works for me

**Comment by gmaurel** [comment]
This is a C++ problem.
More under:
  https://en.wikipedia.org/wiki/Most_vexing_parse
You can find a proposal to get x be seen as a variable such as:
  ```ClassA a((x)* y)```
Part of the output with ```uncrustify ... -p filename``` is:
```
#  17>             TYPE[            NONE][  9/  9/ 15/  0][1/1/0][     70000][0-0]         ClassA
#  17>    FUNC_CTOR_VAR[            NONE][ 16/ 16/ 17/  1][1/1/0][   1800000][0-0]                a
#  17>      FPAREN_OPEN[   FUNC_CTOR_VAR][ 17/ 17/ 18/  0][1/1/0][ 100000000][0-0]                 (
#  17>       PAREN_OPEN[            NONE][ 19/ 19/ 20/  1][1/2/0][ 100040008][0-0]                   (
#  17>             WORD[            NONE][ 20/ 20/ 21/  0][1/3/0][     40008][0-0]                    x
#  17>      PAREN_CLOSE[            NONE][ 21/ 21/ 22/  0][1/2/0][ 100000008][0-0]                     )
#  17>            ARITH[            NONE][ 23/ 22/ 23/  0][1/2/0][ 100000008][0-0]                       *
#  17>             WORD[            NONE][ 25/ 24/ 25/  1][1/2/0][     40008][0-0]                         y
#  17>     FPAREN_CLOSE[   FUNC_CTOR_VAR][ 27/ 26/ 27/  1][1/1/0][ 100000000][0-0]                           )
#  17>        SEMICOLON[   FUNC_CTOR_VAR][ 28/ 27/ 28/  0][1/1/0][ 100000000][0-0]                            ;
```
The star is seen as an ARITH, what you wanted to have.
