### ISSUE TITLE
package.json file

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#815]
@shazron The npm package.json file needs an update as some things have changed:

I've identified some things (can be more):
- [x] https://github.com/uncrustify/uncrustify/blob/master/package.json#L3 => update version
- [x] https://github.com/uncrustify/uncrustify/blob/master/package.json#L7 => replace with cmake
- [x] https://github.com/uncrustify/uncrustify/blob/master/package.json#L12 => update link

Also, if you can add some instructions in README.md on how to use it would be great.

**Comment by CDanU** [comment]
I assume this package.json is for npm, right? I am not 100% on this but isn't npm used for JavaScript Packages?
