### ISSUE TITLE
uncrustify 0.64: not possible to have same value for nl_max and nl_func_var_def_blk

### ISSUE THREAD

**Issue by rdan** [uncrustify/uncrustify#839]
uncrustify 0.64: not possible to have same value for nl_max and nl_func_var_def_blk (and perhaps same issue for other "nl_..." options).

This was OK in uncrustify 0.59.

**Comment by CDanU** [comment]
Error 
> The option 'nl_func_var_def_blk' is too big against the option 'nl_max'
is thrown starting with release 0.63

**Comment by gmaurel** [comment]
Some more such tests will be integrated to show problems with two options.
