### ISSUE TITLE
Alignment of braced initialization define on comma?

### ISSUE THREAD

**Issue by Soukyuu** [uncrustify/uncrustify#844]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
I have some code fragments like this:
```
#define LINKTYPELIST { \
      { -1,      -1,       -1,      0xffffffff, 0xffffffff }, \
      { 10,     50,        5,       100,        50 }, \
      { 10,      10,       5,       100,         10 }, \
      { -1,      -1,       -1,      0xffffffff, 0xffffffff } \
};
```
and I would like to re-format it like this:
```
#define LINKTYPELIST { \
      { -1, -1, -1, 0xffffffff, 0xffffffff }, \
      { 10, 50, 5,         100,         50 }, \
      { 10, 10, 5,         100,         10 }, \
      { -1, -1, -1, 0xffffffff, 0xffffffff }  \
};
```

The furthest I got is using `sp_after_comma=force` or `sp_after_comma=add`, but the former just eats away spaces and the latter does not align the numbers. Is there any way to do what I want or would that require a new option?

**Comment by mihaipopescu** [comment]
Not that I know of... You can achieve something similar with `align_struct_init_span` (see `align-struct-init.c` test file) but I'm not sure if that would work on multi-line defines.

**Comment by Soukyuu** [comment]
Yes, it doesn't seem to work for multi-line defines

**Comment by mihaipopescu** [comment]
maybe @gmaurel can help from this point forward

**Comment by gmaurel** [comment]
uncrustify don't have (as far as I know) any option for your wish. Sorry.
