### ISSUE TITLE
0.63 to 0.64 variable declarations are no longer aligned

### ISSUE THREAD

**Issue by LaraSQP** [uncrustify/uncrustify#849]
With 0.63:
```
event EventHandler	OnChange;
bool			_blockCheck;
```

With 0.64:
```
event EventHandler OnChange;
bool _blockCheck;
```

Thank you for all the hard work.

**Comment by mihaipopescu** [comment]
Thanks for the bug report and for trying to narrowing down the issue.

**Comment by gmaurel** [comment]
Please push your config.

**Comment by LaraSQP** [comment]
Attached.

It's a bit of a mess because I'm also having issues aligning cases in the switch statement (the 1st one, in particular, is misaligned) which, in turn, started with problems regarding the indentation and bracketing of nested using statements. This is for c#, btw.

Thank you for following up on this.

**Comment by LaraSQP** [comment]
Attached now inside a zip.

[lara.0.64.0.cfg.zip](https://github.com/uncrustify/uncrustify/files/646981/lara.0.64.0.cfg.zip)

**Comment by gmaurel** [comment]
with:
```
indent_with_tabs = 0
align_keep_tabs  = false
align_with_tabs  = false
align_on_tabstop = false
```
is the output pretty fine
```
void a()
{
    event EventHandler OnChange;
    bool               _blockCheck;
}
```

**Comment by CDanU** [comment]
On the current HEAD (d4f1e03ab91caa2f4c04a5edf21e569db69d8bf3) I get:
```cpp
void a()
{
        event EventHandler OnChange;
        bool _blockCheck;
}
```
with only `indent_with_tabs = 0` (the other mentioned option values are set to defaults)

--------------------------

I tested a bit with LaraSQPs settings and get:

```cpp
void a()
{
	event EventHandler OnChange;
	bool			   _blockCheck;
}
```

when
```
input_tab_size != 8
output_tab_size != 8
indent_with_tabs != 1
align_with_tabs = true
align_var_def_span > 0
```

If only one of this option values is defined differently I get the expected result:
```cpp
void a()
{
	event EventHandler OnChange;
	bool               _blockCheck;
}
```

**Comment by CDanU** [comment]
It does work however with just `align_var_def_span              = 1`

The problem that @LaraSQP has results from the options:
```sql
output_tab_size                 = 4
align_with_tabs                 = true
align_var_def_span              = 1
```
generating
```cpp
void a()
{
		event EventHandler OnChange;
		bool			   _blockCheck;
}
```
It seems that Uncrustify in not able to align var defs with tabs when `output_tab_size` is not set to 8.

**Comment by guy-maurel** [comment]
The use of tabs is always a problem because one needs to configure all the displays with the same tab setting.
The use of spaces is easier at any time.

**Comment by gmaurel** [comment]
We will not follow this problem at this time.
