### ISSUE TITLE
align_right_cmt_span seems to work differently than other _span options

### ISSUE THREAD

**Issue by Soukyuu** [uncrustify/uncrustify#851]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
uncrustify 0.64, commit 40abc470, windows.

Using config consisting of only `align_right_cmt_span=0` (or 1) with the following example
```
void Test()
{
   a = (double) (b / 60 / 1000) // some comment
                 * c / 2         // continued
                 * 1024;       // here
   
   if (a)
   {
   
   } /* if */
}/* Test */
```
results in misalignment of comments (for *both* 0 and 1!):
```
void Test()
{
        a = (double) (b / 60 / 1000) // some comment
            * c / 2              // continued
            * 1024;            // here

        if (a)
        {

        } /* if */
}/* Test */
```
Adding `indent_columns=3` fixes the behavior for `align_right_cmt_span=0`:
```
void Test()
{
   a = (double) (b / 60 / 1000) // some comment
       * c / 2                   // continued
       * 1024;                 // here

   if (a)
   {

   } /* if */
}/* Test */
```
However: `align_right_cmt_span=1` still doesn't work as other `_span` options:
```
void Test()
{
   a = (double) (b / 60 / 1000) // some comment
       * c / 2                   // continued
       * 1024;                 // here

   if (a)
   {

   } /* if */
}/* Test */
```
I expected to see this (works starting with `align_right_cmt_span=2`):
```
void Test()
{
   a = (double) (b / 60 / 1000) // some comment
       * c / 2                  // continued
       * 1024;                  // here

   if (a)
   {

   } /* if */
}    /* Test */
```

**Comment by gmaurel** [comment]
correct!
The option ```align_right_cmt_span``` must be >=2
