### ISSUE TITLE
Different results on 1st and 2nd run.

### ISSUE THREAD

**Issue by sniper-developer** [uncrustify/uncrustify#852]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

working version: uncrustify 0.64

===ex.cpp===
```
void func
{
    if (true)
    {

        return;
    }
}
```
result after pass 1:
```
void func
{
	if (true)
	{
		return;
	}
}
```
result after step 2 (expected result)
```
void func
{
	if (true)
		return;
}
```
===config file u.cfg===
eat_blanks_after_open_brace=true
mod_full_brace_if=remove
mod_full_brace_nl=2

===command line===
uncrustify.exe -c u.cfg -q -l CPP ex.cpp & uncrustify.exe -c u.cfg -q -l CPP ex.cpp.uncrustify

**Comment by CDanU** [comment]
That is a tough one. Here everything works as it should and I am not really sure if this should be solved if it is solvable in the first place.

**Comment by sniper-developer** [comment]
Of course it's not the same, issue is that it becomes what it should be only after 2nd run on same file.
Different files is just to show reproduce quickly.

**Comment by CDanU** [comment]
I thought you wanted to point out that some options in stacked up runs can mess up the formatting.

> mod_full_brace_nl: Don't remove braces around statements that span N newlines

So this is what maybe happens:
In your first run the _mod_full_brace_nl_ option triggered because your if body spans two lines, therefore the braces are **not** removed. I guess after that the _eat_blanks_after_open_brace_ removes the blank line.

On your second run _mod_full_brace_nl_ is not activated since your if body now spans only one line and _mod_full_brace_if_ removes the braces.

**Comment by sniper-developer** [comment]
Well... Can it be fixed with some another options or from developer's side?
It's looks like a bug, if I use format once, do no changes, press it again and file changes.
Maybe these options should be applied in different order or recursively by uncrustify.

**Comment by CDanU** [comment]
In this case triggering eat_blanks_after_open_brace first could maybe help, but I am not sure if that opens up some other holes. In general you can not avoid the 

> I use format once, do no changes, press it again and file changes

situation as Uncrustify does the changes for you. Your case is a perfect example for this.

**Comment by mihaipopescu** [comment]
If you run the tests you'll notice that uncrustify has already around 5 instabilities (marked with UNSTABLE). Is this a new one?

**Comment by CDanU** [comment]
Are we talking about the

> cmake .. && make && make test 

tests? On HEAD all 666/666 are passing.

**Comment by mihaipopescu** [comment]
I think I remember issuing a warning from cmake when tests are unstable but I can't remember.
The fastest is to run them with the old test runner something like this `./run_tests --exe build/uncrustify`.

**Comment by CDanU** [comment]
Ok, found it, 5 unstable and interestingly enough 2 additional tests.

**Comment by mihaipopescu** [comment]
what do you mean by:
> and interestingly enough 2 additional tests.

are there new tests in the other suite and not in cmake ?

**Comment by CDanU** [comment]
Yes , when I run the run_tests.py it prints Passed 668 / 668 tests, so apparently there are two additional tests.

**Comment by mihaipopescu** [comment]
That is strange. One thing you could try is to rename the `tests/results` directory after the first run and compare the directories to identify the new files.

**Comment by CDanU** [comment]
In the run_tests.py sql is missing, adding it causes errors as there is no sql.test file.

**Comment by mihaipopescu** [comment]
For this issue can you add a PR with a new test showing the instability ?

**Comment by guy-maurel** [comment]
The provided data is not an instability.
In this case, two runs are necessary.
It is not a bug, we can close.
