### ISSUE TITLE
sp_(num_)before_tr_emb_cmt not invariant to input_tab_size

### ISSUE THREAD

**Issue by Soukyuu** [uncrustify/uncrustify#853]
version: uncrustify 0.64 (40abc47)

config:
```
indent_columns=3
#input_tab_size=3
sp_num_before_tr_emb_cmt=1
sp_before_tr_emb_cmt=force
```
source:
```
void test()
{
	func ();	// comment
}
```
expected result:
```
void test()           
{
   func (); // comment
}
```
actual result:
```
void test()
{
   func ();             // comment
}
```
I can get the expected result by setting `input_tab_size=3`, but the default value of `8` doesn't seem to work for whatever reason. I expected uncrustify to first replace all tabs with spaces, then `force` the number of spaces between the code and the trailing comment to `1`. 

Running uncrustify one more time gets rid off the redundant spaces, but that shouldn't be required - else the user can never know how many times they have to run the tool to achieve the correct formatting. Which is kinda what #852 is about, as well.

**Comment by CDanU** [comment]
I would expect that 
> sp_before_tr_emb_cmt=force 
forces that there is always only one space, but that is not the case when combined with sp_num_before_tr_emb_cmt, as force here acts like an add.

Contrary to your results my tests show that without _indent_columns_ the options do work in the uncrustify 0.64 release and the current HEAD.


With _indent_columns_ however they do not as the output always is:

```
void test()
{
   func ();             // comment
}
```

-------------------------------

Sidenote:
Having both options:
> sp_num_before_tr_emb_cmt
> sp_before_tr_emb_cmt

is generally strange. 

Having only sp_num_before_tr_emb_cmt (0: do nothing, 1 remove spaces, 2: force 1 space, ...) would be better but that would not cover the case where if no space is available only add one else ignore the amount of spaces.

**Comment by Soukyuu** [comment]
I suppose I can remove the `sp_num_before_tr_emb_cmt`, I was under the impression I have to set it, but now that I think about it, it does make sense for the default to be 1.

You are right about `indent_columns` causing it.
Or rather, `indent_columns != input_tabs` is what seems to be triggering it.

**Comment by guy-maurel** [comment]
The solution is to synchronize the two options, such as
```
input_tab_size=3
output_tab_size=3
```

**Comment by Soukyuu** [comment]
If I do as you suggest, I end up with:
```
void test()
{
        func (); // comment
}
```
while the intended result is
```
void test()
{
   func (); // comment
}
```
I can get the intended result by synchronizing `indent_columns` and `input_tab_size`, as I said above, however. 

Which is kind of weird! Why am I ending up with 8 spaces when I set `output_tab_size=3`, and with 3 spaces when I leave it at default 8?

**Comment by guy-maurel** [comment]
Well. The use of TAB is very difficult.
Nowhere in your message can I find an information about the width of TAB on your display.
Not all the displays have the same width! I.e. using the command ```meld``` you can specify
the width of TAB.
The best method is not to use any tab. Have a look to the option: ```indent_with_tabs=0```
The solution is to synchronize the two options with the width of your display(s).

**Comment by Soukyuu** [comment]
That option is set in my full config, actually (we are converting each leftover tabs to 3 spaces), but I was having the same issue with the option set, as well. Synchronizing `input_tab_size` and `output_tab_size` works with `indent_with_tabs=0`, as you suggested. 

One thing unclear to me is, if this is needed, why are there two separate options in the first place?
The usage is a bit counter-intuitive, IMHO. I expected to be able to set the size of tabs in the input file with `input_tab_size` and how many spaces I want them to be converted to with the combination of `indent_with_tabs=0` and `output_tab_size`. 

Is the issue occurring because my actual `input_tab_size` is not what I expect it to be (8)?

**Comment by guy-maurel** [comment]
Well. uncrustify is a living program. 
You are right, some options might be obsolete now, but we cannot delete them.
