### ISSUE TITLE
CMake and run_tests.py do not test equally

### ISSUE THREAD

**Issue by CDanU** [uncrustify/uncrustify#854]
While discussing #852 I and @mihaipopescu discovered that the 

> cmake .. && make && make test 

and 

> python2 ./run_tests.py --exe ../b/uncrustify

are generating different results.

The outputs of the camke and run_tests.py generally are not equal:

**run_tests.py**:
Passed 668 / **668** tests
```
['c']           218 / 218 tests
['cpp']         284 / 284 tests
['c-sharp']      39 /  39 tests
['d']            27 /  27 tests
['ecma']          1 /   1 tests
['java']         15 /  15 tests
['objective-c']  67 /  67 tests
['pawn']         10 /  10 tests

['vala']          7 /   7 tests
```
I made this output by manually running with a single language (in the all_tests var) each time and cleaning the output a bit. 
**Note** that in run_tests.py _sql_ is missing, adding it to the all_tests var causes errors as there is no sql.test file.

**cmake**:
100% tests passed, 0 tests failed out of **666**
```
Label Time Summary:
c       =   7.43 sec (215 tests)
cpp     =   6.69 sec (286 tests)
cs      =   0.96 sec (39 tests)
d       =   1.56 sec (27 tests)
ecma    =   0.03 sec (1 test)
java    =   0.30 sec (15 tests)
oc      =   2.18 sec (64 tests)
pawn    =   0.20 sec (10 tests)
sql     =   0.07 sec (2 tests)
vala    =   0.22 sec (7 tests)
```

Diffing the tests/results folders for both tests shows [differences](https://gist.github.com/CDanU/8ecef9a38028616b5646af31b4640b4e):

The cmake run is missing this files:
```Diff
+++ uncrustify/tests/results_run_tests/c/02501-custom_types_ssl.c
+++ uncrustify/tests/results_run_tests/c/02502-custom_types_ssl.c
+++ uncrustify/tests/results_run_tests/c/02503-pp_concat_asn1.h
+++ uncrustify/tests/results_run_tests/oc/50001-Fraction.h
+++ uncrustify/tests/results_run_tests/oc/50002-Fraction.m
+++ uncrustify/tests/results_run_tests/oc/50005-Declarations.h
+++ uncrustify/tests/results_run_tests/oc/50410-oc_cond_colon.m
```

**Comment by mihaipopescu** [comment]
Thanks for investigating and for branching this into to another issue.
If you look carefully at those tests they contain tabs but the regex from the cmake .test parsing expects spaces (see https://github.com/uncrustify/uncrustify/blob/master/tests/CMakeLists.txt#L29).

**Comment by gmaurel** [comment]
If new tests are present, the cmake cache must be deleted, cmake .. at new to get the new tests prepared for ctest

**Comment by CDanU** [comment]
As @mihaipopescu pointed out it's most likely only the weak regex. Out of the million different Regex implementations CMake is using the one that does not support escape sequences like \d \s and \S.
