### ISSUE TITLE
Use standardised exit code values for Uncrustify

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#857]
As discussed in #842 and noted here https://github.com/uncrustify/uncrustify/blob/fef2b74b9678e34fd99eaff610da3b1c2f0bef08/src/uncrustify.cpp#L510 we need to clean our exit code as other tools may depend on them. Uncrustify is returning `EXIT_SUCCESS` and `EXIT_FAILURE` from the C/C++ standard and some other exit code that apparently match the ones from FreeBSD `sysexits.h`.

Even though there is no such thing globally accepted exit codes values, we could use the ones from `sysexits.h` and when not available just redefine them.

**Comment by stefan-nu** [comment]
Me too I'd prefer some human readable error codes.

I looked through the code and found the following return codes as magic numbers when calling exit()

Magic number - function location - meaning
0 - version_exit - EXIT_SUCCESS
1 - chunk_dup - NULL pointer
2 - main - option 'nl_func_var_def_blk' too big with respect to 'nl_max'
56 - usage_exit - cannot open stdout
56 - usage_exit - Unable to load the config file
58 - usage_exit - config file missing
64 - usage_exit - Error while parsing --set
66 - usage_exit - Cannot use --replace with --prefix or --suffix
66 - usage_exit - Cannot use --replace or --no-backup with -f or -o
67 - usage_exit - Cannot use --check with output option
67 - usage_exit - Cannot specify both the single file option and a multi-file option
68 - usage_exit - Cannot specify -o with a multi-file option

In my opinion the used magic numbers do not really  correspond to the meaning of sysexits.h

When using sysexits.h this is nice for BSD. But on Linux or Windows the values may not be recognized as expected. Also sysexits.h may not be available when not building for BSD. 

I think we need a portable solution. 
1. Either using different error codes depending on the platform. Seems a bit too complicated to me.
2. Or using some known error codes like sysexits.h and providing them to other systems as well. 
3. Or using or own error codes.

What do you think?

**Comment by CDanU** [comment]
I am for option 2, microsoft has defined _some_ [error codes](https://msdn.microsoft.com/library/ms681381(v=vs.85))  too.

**Comment by mihaipopescu** [comment]
I'm happy with the result. Thanks @stefan-nu !
