### ISSUE TITLE
Remove comma after last value of enum list

### ISSUE THREAD

**Issue by stefan-nu** [uncrustify/uncrustify#858]
It would be great if uncrustify had an option to remove commas appearing after the last value in an enum list. Such commas are commonly found in C/C++ source code but are not conform with some standard versions.

An example
```
enum {
    item1,
    item2,
}
```
should be changed to
```
enum {
    item1,
    item2
}
```

**Comment by gmaurel** [comment]
Yes!
Don't forget to change the ```./cmake/GenerateTokenNames.cmake``` to remove the last comma.

**Comment by CDanU** [comment]
If this is done please implement this as an AT_IARF type option, I'd like to force the last value comma.

**Comment by guy-maurel** [comment]
#1853 is a proposal for a new option: **mod_enum_last_comma**

**Comment by gmaurel** [comment]
Introduced.
