### ISSUE TITLE
Using macro without ; and then next line use * as pointer seems to mess things up with arith

### ISSUE THREAD

**Issue by Timohan** [uncrustify/uncrustify#867]
First: Q_UNUSED is macro's in Qt that contain ";", but this works with any macro
----- using configs:
```
sp_arith = add
sp_after_ptr_star = remove
sp_after_ptr_star_qualifier = remove
sp_after_ptr_star_func = remove
```
----- code example:
```
#include <QObject>
#include "test.h"

int main(int argc, char *argv[])
{
     Q_UNUSED(argc)
     Q_UNUSED(argv)

     TestClass *pTestClass = new TestClass();
     return 0;
}
```
uncrustify thinks "TestClass * pTestClass" is arith ---> becames:
TestClass * pTestClass = new TestClass();
it should be:      TestClass *pTestClass = new TestClass();

if adding ";" to end of "Q_UNUSED(argv);", then it works fine, but macro already adds ",", so it's kinda wrong thing to do.

current version: uncrustify 0.64_d c407f412ad34d04728c22f3586a07edccc8cc182
also can be redo version with tag/uncrustify-0.64

**Comment by gmaurel** [comment]
This is correct.
uncrustify is not a compiler and doesn't anderstand any macro.
May be you could join us and merge clang and uncrustify?

**Comment by Timohan** [comment]
I am not sure if that can be arith in any situations. because there is "= new" on right side without ')'.

I believe that all <something without> *<something_else but without ')'> = new <something but can be different>(<something again but can be empty>.);
Should "*" be considered as pointer. even the first <something> would be multiple lines and contain '(', ')' - equal amount.
-> if there is ')' after the *, but before new, then it could be macro and arith. but if no, then it cannot be macro.

and new could be also be "<some>malloc" or "<some>realloc" and so on. for example (char *)malloc(...
-----
And I am too busy with own pointless projects. But I hope these situations can be improved later, uncrustify seems to be very good.

**Comment by guy-maurel** [comment]
You can help uncrustify to do the right work.
Let use a file My.type with
```
TestClass
```
and call uncrustify with:
```
uncrustify -c Timohan.cfg -t My.type -f Timohan.cpp
```
Please test and report.

**Comment by gmaurel** [comment]
No answer --> I close the call.
