### ISSUE TITLE
Header files code layout

### ISSUE THREAD

**Issue by stefan-nu** [uncrustify/uncrustify#868]
I would like to propose to restructure the header files. But before I do that, I would ask you to comment on my propositions to know if you like or dislike them.

1. Create an individual header file for ever C file with the same name but ending *.h Thus splitting up prototypes.h into several header files
2. Create a subdirectory "inc" and move all headers to there. Keeping the *.cpp files in the subdirectory "src"
3. Move things that are used only in one C file from the header to the C file to keep it "private"
4. Move things that are used in more than one file to the header to make it "public"
5. All headers use a standard include guard

I think point 3,4,5 are already satisfied. But I wanted to point out the basic idea.

I think this would make the code structure more logical. Maybe there are good reasons why this have not been done so far. If you don't agree with my proposition I would love to learn what is the advantage of the current header layout.

**Comment by gmaurel** [comment]
Proposal 2 is OK for me, but using ```include```.
Proposal 1:
I don't understand the first part!
I don't like ```prototypes.h``` at all.

**Comment by CDanU** [comment]
He wants to split the content of _prototypes.h_ into several _.h_ files that are included by their _.cpp_ files. This would be nice, I am not entirely sure tough on point 4 if there are such cases in the code.

**Comment by jibsen** [comment]
I think an `include` folder is usually used to separate the public header files from the source code of libraries, so people know which headers are needed to link with the library.
