### ISSUE TITLE
use variable declaration/definition with type only

### ISSUE THREAD

**Issue by stefan-nu** [uncrustify/uncrustify#869]
I would like to propose to restructure the way types are defined and used. But before I do that, I would ask you to comment on my proposition to know if you like or dislike it.

Take the example of lang_ext_t

```
struct lang_ext_t
{
   const char *ext;
   const char *name;
};

struct lang_ext_t language_exts[] =
{
   { ".c",    "C"    },
   { ".cpp",  "CPP"  },
   ...
}
```

I would like to change that to 
```
typedef struct lang_ext_s
{
   const char *ext;
   const char *name;
}lang_ext_t;

lang_ext_t language_exts[] =
{
   { ".c",    "C"    },
   { ".cpp",  "CPP"  },
   ...
}
```

In my opinion the declaration/definition of a variable gets clearer if only the type is visible but not the underlying code element. Thus enum, struct, union will not appear anymore in variable declarations/definitions.

I think this would make the code easier to read. Maybe there are good reasons why this have not been done so far. If you don't agree with my proposition I would love to learn what is the advantage of the current approach.

**Comment by jibsen** [comment]
This is C++, so the typedef and the use of struct in the declarations of variables should not be required? Basically, it should be:

~~~.cpp
struct lang_ext_t
{
   const char *ext;
   const char *name;
};

lang_ext_t language_exts[] =
{
   { ".c",    "C"    },
   { ".cpp",  "CPP"  },
   ...
}
~~~

**Comment by stefan-nu** [comment]
You are right. So do you agree to remove the unnessary struct/enum/union specifier and keep only the actual type name?

**Comment by bengardner** [comment]
I'm all for it. It looks like the "struct parse_frame" is the most common.
That all pre-dates the change from C to C++.

**Comment by stefan-nu** [comment]
Most of the struct have been removed from the variable definitions. I close the issue.
