### ISSUE TITLE
use variables with minimal scope

### ISSUE THREAD

**Issue by stefan-nu** [uncrustify/uncrustify#870]
Throughout the code there are many variables that have unecessary large scope. In my opinion it is good practice to keep the scope of variables as small as possible. This greatly improves code readability and reduces the risk for bugs.

An example from args.cpp

 ```C
   int idx;

   if (token != NULL)
   {
      for (idx = 0; idx < m_count; idx++)
      {
         if (strcmp(token, m_values[idx]) == 0)
         {
            SetUsed(idx);
            return(true);
         }
      }
   }
 ```
 would become

 ```C
   if (token != NULL)
   {
      for (int idx = 0; idx < m_count; idx++)
      {
         if (strcmp(token, m_values[idx]) == 0)
         {
            SetUsed(idx);
            return(true);
         }
      }
   }
```
The approach to define all variables at the head of a function was necessary in the old days where compiler where stupid. But every decend compiler nowadays accepts later variable definitions.

Would you agree if I reduced the scope of the variables?

**Comment by gmaurel** [comment]
It is a fine idea.

**Comment by stefan-nu** [comment]
I think the objective of this issue was reached with the various commits. Thus I close the issue.
