### ISSUE TITLE
Want to use <tab> after #define instead of space (illumos coding)

### ISSUE THREAD

**Issue by gdamore** [uncrustify/uncrustify#876]
In illumos & Solaris (www.illumos.org) we have a style guide (and an enforcement tool), that requires that #define be followed by a TAB rather than a space.  (Now it doesn't matter that much for display, since they both look like one character blank on screen -- at least with the indent set to 8 which is also the standard.)

I'd like to be able to craft up a rule / config that would convert spaces after #define into <tab>, probably just a single one.  This is only for C code.

**Comment by gmaurel** [comment]
uncrustify convert, globaly, TAB to spaces or spaces to TAB.
What you wanted to get can't be get with uncrustify, sorry.

**Comment by gdamore** [comment]
I understand it isnt supported now.  It is a feature request.  Some large code bases need this.

**Comment by gmaurel** [comment]
why do you say: "need"?
can you give an example?

**Comment by gdamore** [comment]
We have a style enforcement tool (cstyle.pl, located in
github.com/illumos/illumos-gate/usr/src/tools/scripts/) that we have used
for a *long* time (decades actually, though for the first part of its life
that was inside Sun).  It demands that #define be followed by a <tab> — its
a stupid rule IMO, but there you go.

Anyway, for this code base, which has hundreds of developers — we can’t use
uncrustify unless we can make uncrustify produce cstyle.pl conformant code.
You could argue that we could just “fix cstyle”, but the problem with that
is that it is been in use by so many for so long, that changing the coding
style in even trivial ways like this becomes a political morass, so that
it’s easier to just not use uncrustify than to debate about the style.
 (After all we’ve done without uncrustify for this long…)

**Comment by gmaurel** [comment]
Thanks for the message.
One should not discuss about any "style"! They are all "pretty".
You only need a "better" uncrustify!
I am looking for a solution for you.

**Comment by gdamore** [comment]
Thank you!

**Comment by gmaurel** [comment]
Where is the "coding style"?

**Comment by gmaurel** [comment]
The proposal is implemented

**Comment by gdamore** [comment]
Thank you!!
