### ISSUE TITLE
Regression? in 0.63 relative to 0.59

### ISSUE THREAD

**Issue by gdamore** [uncrustify/uncrustify#888]
I use the indent_continue=4 option (my coding style is similar to FreeBSD).  In 0.59 this was indented properly:

				while (!ep->ep_close) {
					rv = nni_cond_waituntil(&ep->ep_cv,
						cooldown);

However, in 0.63, it wants to indent that "cooldown" line by 8 (my standard indent).  What gives?  It seems to happen only to certain statements.

I'm pretty sure 0.61 works properly too.

**Comment by CDanU** [comment]
@gdamore Do you need one/two tabs (size 8/4) and 4 spaces or only 8 & 4 spaces ? 
Could you please post your full config file and a closed example? An the expected formatting example would be nice.

I tried 
```cpp
			while (!ep->ep_close) {
				rv = nni_cond_waituntil(&ep->ep_cv,
					cooldown);
                        }
```
and it seems that from version 0.60 (earliest that I have right now) it doubles the `indent_continue`. 
So `indent_continue=2` should produce the right output for this example. Could you confirm that?

I believe I saw a similar opened issue already somewhere.

**Comment by gdamore** [comment]
so doubling the indent continue is exactly the wrong thing for me.  I use tabs to indent normally but for lines like this I expect tabs followed by 4 trailing spaces.

**Comment by gmaurel** [comment]
Have a look to the option:
```use_indent_continue_only_once=true```

**Comment by gmaurel** [comment]
No answer --> I close the call.
