### ISSUE TITLE
sp_after_cast not applied if cast value is return from namespace-qualified function call

### ISSUE THREAD

**Issue by chrullrich** [uncrustify/uncrustify#889]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

See line 23 of the attached file, renamed from .cpp to .txt because GitHub won't accept the former.

Expected result:

    boost::iostreams::mapped_file_source pdf((LPSTR)ATL::CW2A(sTemp));

Actual result:

    boost::iostreams::mapped_file_source pdf((LPSTR) ATL::CW2A(sTemp));

uncrustify always adds a space after the cast to (LPSTR).

uncrustify is 0.63 9170ac, i.e. current master.

[debug.txt](https://github.com/uncrustify/uncrustify/files/675457/debug.txt)
[Attachment.txt](https://github.com/uncrustify/uncrustify/files/675466/Attachment.txt)

**Comment by gmaurel** [comment]
The casting is not found...

**Comment by chrullrich** [comment]
Great. Now I can't repeat it either. I think when I had it working, the token sequence wasn't PAREN_CLOSE, TYPE, DC_MEMBER, CPP_CAST, as it now is, but the last one was FUNC_CALL. I won't pretend I understand any of combine.cpp, and I cannot see how that sequence could have come out of it.
