### ISSUE TITLE
sp_elseif_brace - `else if` and `{`

### ISSUE THREAD

**Issue by ferologics** [uncrustify/uncrustify#894]
In `obj-c` I'm trying to enforce following syntax

```obj-c
if (foo)
{
 ...
} else if (bar) {
  ...
} else {
  ...
}
```

but with the input

```obj-c
if (foo)
{
  ...
}
else if (bar)
{
  ...
}
else
{
  ...
}
```

uncrustify is not forcing the single ` ` between `) {` in `} else if (bar) {` and produces

```obj-c
if (foo)
{
 ...
} else if (bar)        {
  ...
} else {
  ...
}
```

uncrustify lacks the rule for `sp_elseif_brace` or for `sp_if_brace` if on same line

**Comment by CDanU** [comment]
Try the option `sp_after_sparen`.

**Comment by ferologics** [comment]
@CDanU `sp_after_sparen` already set to `force`, a space before sparen is unrelated

**Comment by CDanU** [comment]
```
sp_after_sparen                 = force
sp_else_brace                   = force
sp_brace_else                   = force
nl_brace_else                   = remove
nl_elseif_brace                 = remove
nl_else_brace                   = remove
nl_else_if                      = remove
```

Turns this: 
```cpp
if (foo)
{
        int a = 1;
}
else if (bar)
{
        int b = 1;
}
else
{
        int c = 1;
}
```
into:
```cpp
if (foo)
{
	int a = 1;
} else if (bar) {
	int b = 1;
} else {
	int c = 1;
}
```
on 237eb8aaa944b5286cbfc92762b480d9a3bfac92

I those settings do not work, post your version/commit sha, config and a full minimal example.

**Comment by guy-maurel** [comment]
The current git version works pretty fine.
  https://github.com/uncrustify/uncrustify
Please test it!
