### ISSUE TITLE
Parameter sp_compare splits operator <>

### ISSUE THREAD

**Issue by yeti01** [uncrustify/uncrustify#896]
In Perl, a line like this

`while (<>)`

is converted to

`while (< >)`

This happens if you set

`sp_compare = force`

I use the latest version from macports.org.

`uncrustify -v`
`uncrustify 0.61`

**Comment by CDanU** [comment]
> [Uncrustify:] Source Code Beautifier for C, C++, C#, ObjectiveC, D, Java, Pawn and VALA

**Perl** is not officially supported and the version that you use (`uncrustify 0.61`) is quiet cold. 

If you really want get help on this try the current release (or better yet the current git state, you should be able to use cmake to build uncrustify on macs) and also post the needed info (read the [ISSUE_TEMPLATE](https://github.com/uncrustify/uncrustify/blob/master/.github/ISSUE_TEMPLATE))

**Comment by yeti01** [comment]
Hi and thanks for the reply.
Yes, you are right of course. Although very similar to C syntax, Perl is not a supported language.

**Comment by mihaipopescu** [comment]
@yeti01 You can take a look at other beautifiers for perl like `perltidy`.
