### ISSUE TITLE
Uncrustify uncrustifying itself

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#898]
PR #840 introduced a change that enabled a CI test to run uncrustify on itself and fail if diffs are detected. While this is a good idea (we're doing it as well) I've noticed that a lot of people are struggling with this committing multiple times just to make the test happy.

Things we need to consider some things:
- [ ] Uncrustify code doesn't need to have instabilities and `Run_uncrustify_for_sources` should check for that as well
- [x] Have `CONTRIBUTE` section in our README file where we specify that people have to run this script before creating a PR
- [ ] Provide a simple commit hooks configuration in the README that people can easily use in their setup

**Comment by gmaurel** [comment]
instabilities: if the test is OK --> there are no instability and the sources are conform to the config file.

**Comment by mihaipopescu** [comment]
@gmaurel The code from `Run_uncrustify_for_sources` doesn't check for instabilities.

By an instability I mean: `uncrustify(file) == uncrustify(uncrustify(file))`

**Comment by gmaurel** [comment]
`Run_uncrustify_for_sources` uncrustify first. If the results are identical to the sources, then there is no instability.
I mean: `uncrustify(file) == file`

**Comment by mihaipopescu** [comment]
Also, I'm afraid that with all these code refactoring happening in the code base, we're making merge harder for the old forks (like our own).

**Comment by gmaurel** [comment]
It is important to merge as most as possible.
How to help.
Could you tell us which differences are "more important" and "less important"?
We could freeze other changes for this time and merge the most important toogether.

**Comment by mihaipopescu** [comment]
Due to recent changes, the cost of merging increased. See my comment in https://github.com/uncrustify/uncrustify/pull/939#issuecomment-274451822.

If I can find the time, I'll try to do another check this week and create issues for the regressions we've seen.

**Comment by mihaipopescu** [comment]
Also, I've noticed there are two scripts `Run_uncrustify_for_sources` for Unix/Win. We need the script in a cross-platform language (say python).

**Comment by gmaurel** [comment]
Right, but I can't python.
Can anybody help us?

**Comment by mihaipopescu** [comment]
The script is not big so I'd say it can be done in a couple of hours. It's just a matter of finding that free time to do it.

**Comment by gmaurel** [comment]
This would be fine! Thanks.

**Comment by mihaipopescu** [comment]
I think the experience is still not improved. What do you guys think?

**Comment by satishp87** [comment]
yes it is tough to down-merge initially , now a days we are habituated to the same and becomes not that difficult.

**Comment by mihaipopescu** [comment]
Yes, I think so. Running the uncrustify self-format and support files scripts is still a convoluted experience, especially on windows.

**Comment by guy-maurel** [comment]
No more comment!
May I close?

**Comment by mihaipopescu** [comment]
Sure. The experience is slightly better having the format scripts as `ctest`.

**Comment by mwoehlke-kitware** [comment]
...also, there's now the `format-sources` target :slightly_smiling_face:.
