### ISSUE TITLE
Contribute code of conduct

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#899]
As I was talking in the previous issue that I've opened #898 to have a contribute section in our readme file, we need to add more conventions to enable us to work together more smoothly.

Rules:
- branches should be named after what the work is about
- branches should not be named after the issue number, developer name, etc.
- branch name should contain keywords like `fix`, `feature`, etc.
- it is recommended to do one thing on the branch and get that to master, splitting work if necessary.
- the PR title should represent _what_ is being changed (could be a rephrasing of the branch name if set correctly)
- the PR description should document the _why_ not the _what_
- try to avoid merges, always rebase your work on top of master before creating a PR
- no PR should be approved to be merged in master if the work is incomplete (no fix-up commits). That's why core reviews are for, not for automatic testing by a CI server. Be very critical but not try to over-engineer things.
- the changes should always be accompanied by regression tests (if not possible, why not ?)

Please comment and let's contribute to this list.

**Comment by gmaurel** [comment]
Thanks for the proposals.

**Comment by CDanU** [comment]
I also like this conventions (even when I most likely had broken every one of those at some point). 

One thing that I don't get is why we use merge commits when they are not really needed:
* Merging the master branch into a feature branch: Why not just rebase on the master instead?
* Merging PRs that have no conflicts: There is a rebase option in github.

The other thing that I don't like are PRs with fix-up commits. Split them up and include them into their respective commits.

I get that most of this means one has to do more work while additionally having to have a slightly deeper understanding of git but that would produce a cleaner tree: 
* No fix-up commits that are fixing issues for commit n, n-2, n-5 together in one extra commit.
* Less looking at merge commits to see if and/or which changes where made to resolve conflicts. 
* most likely some other benefits ....

At this point in time there aren't that many PR

**Comment by mihaipopescu** [comment]
@CDanU thanks for your proposals. I've updated the list. I think it needs more iteration until we go and modify README.

Let me know if rebasing is possible in git/github after pushing some changes. What feature/option is that in github. Is it something for the maintainer to care about ?

**Comment by CDanU** [comment]
Yes this is mostly only for the maintainer: https://github.com/blog/2243-rebase-and-merge-pull-requests
I have not used this but as I understand int works like this: If there are no merge conflicts caused by the pr github can instead of pushing the changes with a merge commit do a rebase and just put the commits on top of the tree without introducing a new merge commit.

**Comment by mihaipopescu** [comment]
Is that also possible for the PR owner ? Can he rebase his changes on top of new master? As far as I know in my limited git knowledge, `git pull --rebase` could do this work. Is this correct?

**Comment by CDanU** [comment]
I don't think that this is possible for the PR owner in github but you can do this with git. You update your master to the latest remote master, checkout into your feature branch, `git rebase master`, handle the possible conflicts and force push the changes to your remote feature branch. The `git pull --rebase` command is, as far as I know, only used when someone altered the history of the master branch.

**Comment by mihaipopescu** [comment]
> even when I most likely had broken every one of those at some point

I'm guilty as well on a lot of points but if we have a set of common sense rules we all agree on I think it will help the development as a continuous process and engage more developers in this effort. They are also good even if you work alone, it helps you from understanding your own changes you did 6 months ago.

We also need a sense of trust to be able to work together and to contribute back to the community. Ideally, the experience of merging in a new master should be seamless without regressions, which is not true in the present moment.

I hope you all agree that we need this.

**Comment by stefan-nu** [comment]
I like the idea of a code of conduct a lot. It helps new contributors a lot to understand how the development process of uncrustify works. I'd propose to not only add a file to the repository but also add a a link in the wiki as this is probably one of the first places people will look into.

**Comment by CDanU** [comment]
Another proposal:
Don't include #issue numbers in the commit title. Every time when a commit is changed after creating the pull request a new reference entry is generated on the issue page. This quickly gets really messy (see #870).
Reference issues inside the commit description.

**Comment by stefan-nu** [comment]
@CDanU thanks for pointing that out. I was wondering already why there are so many links. Now I know.

**Comment by jibsen** [comment]
How about trying to use a common format for commit messages, like for instance [this one](http://chris.beams.io/posts/git-commit/). Especially keeping the first line consistent helps the commit log.

**Comment by mihaipopescu** [comment]
Yep. I think they are common sense rules. I'm afraid if we're adding too many rules not many people will even try to read them. Actually what do you guys think in renaming from _rules_ to _best practices_ ?

**Comment by jibsen** [comment]
GitHub has [special support](https://github.com/blog/1184-contributing-guidelines) for a file called CONTRIBUTING.md which people who open a PR will be made aware of. They call them contributing _guidelines_.

I agree it should be a fairly short list. The only reason I brought up commit messages is that the current commit log is a bit of a mixed bag. Of course this has no influence on the code itself, so it's less important.

**Comment by mihaipopescu** [comment]
Nice. We'll use that file name then. I'll start the PR then.

**Comment by mihaipopescu** [comment]
I hope I collected everyone's feedback. Let's see how this goes.
