### ISSUE TITLE
nl_before_func_body_def and cpp style comments newlines bug

### ISSUE THREAD

**Issue by CDanU** [uncrustify/uncrustify#902]
As mentioned in #897 Uncrustify adds unnecessary newlines with this config: 

```
nl_before_func_body_def         = 2
```
example0, expected output0 :
```cpp
// unc_add_option("sp_cond_colon", UO_sp_cond_colon, AT_IARF,
//                "Add or remove space around the ':' in 'b ? t : f'");
// unc_add_option("sp_cond_question", UO_sp_cond_question, AT_IARF,
//                "Add or remove space around the '?' in 'b ? t : f'");


void detect_options(void)
{
	detect_space_options();
}


```
generated code0:
```cpp
// unc_add_option("sp_cond_colon", UO_sp_cond_colon, AT_IARF,
//                "Add or remove space around the ':' in 'b ? t : f'");
// unc_add_option("sp_cond_question", UO_sp_cond_question, AT_IARF,

//                "Add or remove space around the '?' in 'b ? t : f'");


void detect_options(void)
{
	detect_space_options();
}
```
[debug](https://gist.github.com/CDanU/54e2095b7c893742d8103eb752d4811f)

-------------------------

Everything works as expected when before the detect_options functions a c type comment is placed.

example1, expected output1, generated code:1 :
```cpp
// unc_add_option("sp_cond_colon", UO_sp_cond_colon, AT_IARF,
//                "Add or remove space around the ':' in 'b ? t : f'");
// unc_add_option("sp_cond_question", UO_sp_cond_question, AT_IARF,
//                "Add or remove space around the '?' in 'b ? t : f'");

/**/
void detect_options(void)
{
	detect_space_options();
}
```
[debug](https://gist.github.com/CDanU/e9044ac6569e48578edc686dfc6dae2d)

-------------------------

Tested on: 8da4bdcdd4e2801e8821f302e6e3fb547fef5014
This behaviour started with commit 3ea4b6d which introduced the `nl_before_func_body_def` option.

**Comment by gmaurel** [comment]
Correct.
It isn't a bug but a problem.
Some (most) of function have some comment before the first lines of code to
comment the function (call, use, ...).
It is NOT possible to distinguish between that and the case you are showing.
As uncrustify finds a function, it look for comment before and add the NL as specified
at ```nl_before_func_body_def```.

The only solution is to introduce a (little) comment before the function. Sorry.

**Comment by stefan-nu** [comment]
This seems a bit odd to me. In the example above there is already a newline before the function definition. Imho in this case the `nl_before_func_body_def` should not add another newline. An exception would be if a specific number of newlines are required. But in this case the newlines should be added before the function definition. 

The example shows however, that a newline is added before the last line of the block comment. This seems wrong to me and I don't understand why uncrustify could not recognize this situation.

**Comment by CDanU** [comment]
Well I have a solution for this example but I don't know if it does work everywhere and does not cause other issues somewhere:

```diff
diff --git i/src/newlines.cpp w/src/newlines.cpp
old mode 100755
new mode 100644
index 4db74eb..23c9f7e
--- i/src/newlines.cpp
+++ w/src/newlines.cpp
@@ -821,7 +821,8 @@ static void newlines_func_pre_blank_lines(chunk_t *start)
          case CT_FUNC_DEF:
             if (cpd.settings[UO_nl_before_func_body_def].n > 0)
             {
-               if (cpd.settings[UO_nl_before_func_body_def].n != last_nl->nl_count)
+               if (cpd.settings[UO_nl_before_func_body_def].n != last_nl->nl_count
+                       && last_comment->next->nl_count < 2 )
                {
                   LOG_FMT(LNLFUNCT, "   set blank line(s) to %d\n",
                           cpd.settings[UO_nl_before_func_body_def].n);
```
This basically looks at how much newlines are between the last comment and a func def. Here I assume that after a comment a newline is followed but I am not sure if that is always the case.

**Comment by stefan-nu** [comment]
Regarding the fact if your solution fits in every case, I'd say if it passes all tests then it's fine. I'd stick to a test driven approach. Thus any solution that passes all tests is correct. If someone wants another behaviour he/she had to add a failing test first.

However I still don't get why the newline was added **before** the last comment line. This makes no sense to me. The newline should always be added before the function definition that is **after** the last line of comment.

**Comment by CDanU** [comment]
Well look at [newlines_func_pre_blank_lines()](https://github.com/uncrustify/uncrustify/blob/master/src/newlines.cpp#L722). 
Currently it works like this: 
* find func def token
* iterate token order backwards
* save last newline token
* check if a tokens triggers a formatting event

The formatting event for comments is triggered if when two times comments are found (before something else triggers a formatting event). The amount of newlines in the newline token after the second found comment is changed to the option value. This approach does not check how far away the newline token of the first found comment is away from the func def.

So far this is my best attempt:
```diff
diff --git i/src/newlines.cpp w/src/newlines.cpp
old mode 100755
new mode 100644
index 4db74eb..746da8f
--- i/src/newlines.cpp
+++ w/src/newlines.cpp
@@ -747,13 +747,15 @@ static void newlines_func_pre_blank_lines(chunk_t *start)
       else if (chunk_is_comment(pc))
       {
          LOG_FMT(LNLFUNCT, "   <chunk_is_comment> found at line=%zu column=%zu\n", pc->orig_line, pc->orig_col);
-         if (last_comment)
+         if( (pc->orig_line < start->orig_line && (start->orig_line - pc->orig_line) < 2) ||
+             (last_comment != NULL && last_comment->orig_line > pc->orig_line && (last_comment->orig_line - pc->orig_line) < 2))
          {
-            do_it = true;
-            break;
+             last_comment = pc;
+             continue;
          }
-         last_comment = pc;
-         continue;
+
+         do_it = true;
+         break;
       }
       else if (pc->type == CT_DESTRUCTOR)
       {
```

**Comment by stefan-nu** [comment]
Great that you fixed it! 
It would be nice to have a test that checks for the unwanted behaviour too.

Thanks for your explanation. The current approach seems unnecessarly complicated to me. Also the code seems rather difficult to understand at first glance. 

Wouldn't it be easier to count the number of newlines directly before the func def token and if necessary add/remove the required number of newlines?

Anyway I assume there is a good reason for the current approach.
