### ISSUE TITLE
Placement of static function comments

### ISSUE THREAD

**Issue by stefan-nu** [uncrustify/uncrustify#921]
I would like to ask your opinion about where a function comment shall be located.

In my opinion a function comment goes always right before a function declaration.
The function definition gets no comment.

When implementing #897 I have moved several function comments from the function definition to the function declaration in the header. As far as I understood that was agreed to by the team members.

Now I would also like to propose to move function comments of static functions to their declarations at the beginning of the respective *.cpp files. 

To give an example referring to file brace_cleanup.cpp

Current state:

```
/* function declarations */
...
static void parse_cleanup(struct parse_frame *frm, chunk_t *pc);
...
/* function definitions */
...
/**
 * At the heart of this algorithm are two stacks.
... long comment removed ...
 * When a #define is exited, the frame is popped.
 */
static void parse_cleanup(struct parse_frame *frm, chunk_t *pc)
```

Shall be changed to 
```
/* function declarations */
...
/**
 * At the heart of this algorithm are two stacks.
... long comment removed ...
 * When a #define is exited, the frame is popped.
 */
static void parse_cleanup(struct parse_frame *frm, chunk_t *pc);
...
/* function definitions */
...
static void parse_cleanup(struct parse_frame *frm, chunk_t *pc)
```

The reason for this change is that imho the code and the documentation become both easier to read.

Please let me know if you agree or if you prefer another approach.

**Comment by mihaipopescu** [comment]
Your efforts in trying to find a good place for the comments is well received. I think that we should keep in mind that when documenting a function (at least in C++) we can differentiate the function interface/contract to it's implementation. The details of the implementation are not relevant for the function's clients. Also, let's try to avoid documenting what is obvious.

**Comment by stefan-nu** [comment]
Yes I agree. In my opinion too the function comment is intendet for the caller of the function. Thus it shall only describe how to use a function. 
Any comment that describes the implementation shall go directly into the function.

**Comment by stefan-nu** [comment]
Another related thing I would like to propose is to always have a function prototype. Either public i.e. in the header or private/static i.e. in the source file. The reason for this is that this will evenutually lead to a fully documented API.

**Comment by stefan-nu** [comment]
Regarding your remark "let's try to avoid documenting what is obvious."
In general I agree with that. The problem is just, what is "obvious" is quite different between people.
I think the best approach is to write code that is self explanatory.

**Comment by stefan-nu** [comment]
The objective of this ticket was reached by the various commits listed above. I close the ticket.

**Comment by mihaipopescu** [comment]
>  write code that is self explanatory
👍
