### ISSUE TITLE
Question: is there a way to leave continuation 'as is'?

### ISSUE THREAD

**Issue by parapaul** [uncrustify/uncrustify#931]
It looks like uncrustify is too strict regarding line wrapped function defs/calls: it allows either to indent or align continuation:
```
// indent (can also be double indent)
void long_function_name(int arg1,
    int arg2)

// align around (under, under +1 space) open paren (spaces or tab + spaces)
void long_function_name(int arg1,
                        int arg2)
```

Our C++ project uses line-wrapping rules inspired by official java codestyle:

> Following are two examples of indenting method declarations. The first is the conventional case. The second would shift the second and third lines to the far right if it used conventional indentation, so instead it indents only 8 spaces.
```
//CONVENTIONAL INDENTATION
someMethod(int anArg, Object anotherArg, String yetAnotherArg,
           Object andStillAnother) 

//INDENT 8 SPACES TO AVOID VERY DEEP INDENTS
private static synchronized horkingLongMethodName(int anArg,
        Object anotherArg, String yetAnotherArg,
        Object andStillAnother)
```

But it seems like we just can't achieve it with uncrustify, even manually! I hope I am wrong and there's some option to completely 'ignore' line-wrapping style :)

**Comment by CDanU** [comment]
Check if `indent_continue = 8` works for you.

**Comment by parapaul** [comment]
No, it breaks aligned continuations :)
As I've written in my original post, our code style states that preferred style of line wrapping is aligned around open paren. Say I've aligned arguments manually (IDE does it for me when I hit 'Enter') - with 'indent_continue = 8' alignment is broken as soon as I call uncrustify.

**Comment by guy-maurel** [comment]
Please make a test with the new options:
```
indent_func_def_param = true
indent_param          = 8
```
and report. Thanks.

**Comment by parapaul** [comment]
Tried it, but it doesn't solve my issue (breaks aligned arguments as described in my comment above).

Maybe my description of the problem wasn't that clear, what I really want is something like:

```
indent_func_def_param = false

# this is new option that I want - it allows to align params when appropriate and indent them when not
# If 'indent_func_def_param ' is false, behave as if it was true if paren position is more than this value
indent_func_def_param_paren_pos_threshold = 40
```

Thank you!

**Comment by guy-maurel** [comment]
PR #2512 is a bugfix proposal.
Please test it and report.
