### ISSUE TITLE
Sorting order of usings

### ISSUE THREAD

**Issue by Leopotam** [uncrustify/uncrustify#935]
Expected behaviour with mod_sort_using=true:

```
using System;

using System.Collections.Generic;
```

Actual behaviour with mod_sort_using=true:  

```
using System.Collections.Generic;

using System;
```

So, sorting direction option required at config for proper behaviour of sorting process.

uncrustify version: 0.64.

**Comment by mihaipopescu** [comment]
No, I think it's a bug if you look at it like that.
Last time I've checked this feature it was only sorting within groups. An empty line is what splits the includes/usings in groups.

**Comment by Leopotam** [comment]
Now its looks like reverse sorting. Btw, VS / R# has special option - put System.xxx usings first (like at 
[screenshot at this question](http://stackoverflow.com/questions/12831038/how-to-tell-resharper-to-sort-usings-with-system-namespaces-not-at-the-top). Is it possible to add similar (optional) behaviour?

**Comment by mihaipopescu** [comment]
Can you check now ? @gmaurel have made some changes.

**Comment by Leopotam** [comment]
0.64 version:
```
using Client.Common;
using LeopotamGroup.Common;
using LeopotamGroup.Serialization;
using System;
using UnityEngine.EventSystems;
using UnityEngine.Events;
using UnityEngine;
```

patched version:
```
using Client.Common;
using LeopotamGroup.Common;
using LeopotamGroup.Serialization;
using System;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.Events;
```
Better, but order still wrong, check 2 last positions.

Btw, what about option for sort SystemXXX separately and put them first?
Expected:
```
using System;
using Client.Common;
using LeopotamGroup.Common;
using LeopotamGroup.Serialization;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.EventSystems;
```

**Comment by gmaurel** [comment]
Is it correct to sort without comparing lower letter vs. upper letter?

**Comment by Leopotam** [comment]
No, case important. Expected order:
```
using nameSpace;
using Namespace;
using NameSpace;
using NameSpacEveryday;
```

**Comment by Leopotam** [comment]
[Example of proper sorting (C#)](https://gist.github.com/Leopotam/a165b09004ad4361b34ce1c404727b43)

**Comment by mihaipopescu** [comment]
yes, we have a similar thing on our side:

```cs
using (var ex = x.GetEnumerator())
            using (var ey = y.GetEnumerator())
            {
                while (ex.MoveNext() && ey.MoveNext())
                {
                    // exactly the same character ?
                    if (ex.Current == ey.Current)
                        continue;

                    int diff = char.ToLower(ex.Current, CultureInfo.InvariantCulture) - char.ToLower(ey.Current, CultureInfo.InvariantCulture);
                    if (diff == 0)
                    {
                        // if we're comparing the same character but in different case
                        // we want to favor lowercase before uppercase (e.g. a before A)
                        // so the order is the reverse of ASCII order (we negate).
                        return -(ex.Current - ey.Current);
                    }
                    else
                    {
                        // return the case-insensitive diff to sort alphabetically
                        return diff;
                    }
                }
            }
            return x.Length - y.Length;
```

**Comment by Leopotam** [comment]
well, it can be simplified:
```
    /// <summary>
    /// /// Usings sorter.
    /// </summary>
    /// <param name="a">String 1.</param>
    /// <param name="b">String 2.</param>
    /// <param name="systemFirst">Is System.xxx nusings should be at top.</param>
    /// <returns>Compare result (-1, 0, +1).</returns>
    int UsingSortMethod2 (string a, string b, bool systemFirst) {
        int res = 0;
        if (systemFirst) {
            res -= a.StartsWith ("using System") ? 1 : 0;
            res += b.StartsWith ("using System") ? 1 : 0;
            if (res != 0) {
                return res;
            }
        }
        int idx = a.IndexOf (";");
        if (idx != -1) {
            a = a.Substring (0, idx);
        }
        idx = b.IndexOf (";");
        if (idx != -1) {
            b = b.Substring (0, idx);
        }
        return string.Compare (a, b);
    }
```

**Comment by gmaurel** [comment]
Would you like to make a PR for it?

**Comment by Leopotam** [comment]
Im already not c / c++ programmer last 11 years. So, no, i have no plans for PR. You can close issue, i will write custom plugin for vscode for usings sorting and will disable sorting for uncrustify.

**Comment by gmaurel** [comment]
Thanks for the info.
I 'll make the PR myself.
The last PR will be overwritten by me. Please wait a bit.

**Comment by gmaurel** [comment]
Should we have a new option to put SystemXXX first?

**Comment by Leopotam** [comment]
It will be great, because VisualStudio has special option for this. It will be good for following both styles - with alphabetical sorting and alphabetical + system first. Thanks.

**Comment by mihaipopescu** [comment]
> Should we have a new option to put SystemXXX first ?
Well, not necessarily.

We can achieve this in a more generic way if we introduce the concept of prioritised include categories. It's actually not an original idea, it's borrowed from [clang-format](http://clang.llvm.org/docs/ClangFormatStyleOptions.html).

I've done some preliminary work in this direction here https://github.com/Unity-Technologies/uncrustify/commit/b76bf3662e74301ce3e7bd95163ee934ce044f6a but I never got the time to clean it and push it upstream. Our fork is well behind as well but that's another problem.

So, in this case, you would just have to define a higher priority:

```include_category_0=System```

and because `mod_sort_include` option is for C++ as well, you can have this only for C# in your cfg file, not hardcoded somewhere in uncrustify.

**Comment by gmaurel** [comment]
@mihaipopescu : do you take the call now?

**Comment by mihaipopescu** [comment]
I'll work on a PR. You can assign it to me.

**Comment by mihaipopescu** [comment]
@Leopotam Can you try with the latest ?

**Comment by Leopotam** [comment]
Yes, it works as must.

**Comment by CDanU** [comment]
Everyone should take notice that with the merged #959 Uncrustify now is (finally) using c++11 🥇

**Comment by mihaipopescu** [comment]
@Leopotam You can close the issue if verified.
@CDanU Correct, should we make this note more visible? Any ideas?

**Comment by CDanU** [comment]
Slapping a badge into the readme I guess:
<img src="https://img.shields.io/badge/C++-11-blue.svg?style=flat-square">
https://img.shields.io/badge/C++-11-blue.svg?style=flat-square

**Comment by mihaipopescu** [comment]
@CDanU I like this a lot ! 👍

**Comment by jibsen** [comment]
I think linking it to a specific line in the build file gives two unrelated places that need to be kept in sync. It doesn't really need to link anywhere.

**Comment by mihaipopescu** [comment]
yeah, that's a good point.

**Comment by CDanU** [comment]
Ok no links then, my main concern didn't even exist in the first place. Github is intercepting every image and delivers it from _camo.githubusercontent.com_. I'll open up a PR.
