### ISSUE TITLE
nl_comment_func_def causes segfault on initial blank line

### ISSUE THREAD

**Issue by jrosenberger** [uncrustify/uncrustify#938]
test.h:
\n
void function(void);

uncrustify.cfg:
nl_comment_func_def=1

running with the above config on the above header (consisting of a blank line and then a function prototype) causes a segfault

**Comment by jibsen** [comment]
Dereferencing NULL pointer pcmt at newlines.cpp:3849:

    Thread 1 received signal SIGSEGV, Segmentation fault.
    0x000000000043c91c in do_blank_lines () at uncrustify\src\newlines.cpp:3849
    3849              (pcmt->type == CT_COMMENT_MULTI) &&
    (gdb) p pcmt
    $1 = (chunk_t *) 0x0

**Comment by gmaurel** [comment]
Thanks for the report
