### ISSUE TITLE
UTF-16 character literals get illegally formatted

### ISSUE THREAD

**Issue by tepperly** [uncrustify/uncrustify#945]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Here is the original code:

    $ cat /tmp/foo.cpp
    #include <string>
    
    int main(int argc, char **argv) {
      char16_t c = u'\u007f';
    }
    $

After running uncrustify `uncrustify 0.64_d`, I get the following:

    $ cat /tmp/newfoo.cpp
    #include <string>
    
    int main(int argc, char **argv) {
      char16_t c = u '\u007f';
    }
    $
The space inserted between the u and the first single quote makes the character literal unpareable.

    $ g++ -std=gnu++11 -o /tmp/newfoo.o -c /tmp/newfoo.cpp
    /tmp/newfoo.cpp: In function 'int main(int, char**)':
    /tmp/newfoo.cpp:4:16: error: 'u' was not declared in this scope
       char16_t c = u '\u007f';
                 ^
    $

Here is the [debug file](https://gist.github.com/tepperly/5907ab5ba419d81dc095e0c83bf5dcf8).

**Comment by mihaipopescu** [comment]
Oh, I think uncrustify doesn't expects the new string or char literals from C++11. Need to add support for that.

**Comment by j000** [comment]
Does that merged PR fix it for C++? I'm having the same issue with C...
`u"test"` -> `u "test"`

**Comment by CDanU** [comment]
Yes, the merged commit, and the ones before it handle the prefixes only for C++. I didn't know [C11](http://en.cppreference.com/w/c/language/string_literal) supports those too. A PR for that will be submitted soon.

**Comment by j000** [comment]
I just wasn't sure if it's working properly for C++, so I asked. It's good to know it does :) Thanks!
