### ISSUE TITLE
Qt dialect should not be treated as a language

### ISSUE THREAD

**Issue by mihaipopescu** [uncrustify/uncrustify#961]
Branching issue #531 for Qt keywords, the idea is to have a config file:
```
set QT_KEYWORD foreach
set QT_KEYWORD Q_EMIT
set QT_KEYWORD Q_FOREACH
set QT_KEYWORD Q_FOREVER
set QT_KEYWORD Q_GADGET
set QT_KEYWORD Q_OBJECT
```

Can this work ?

**Comment by guy-maurel** [comment]
No more comment!
MAy I close?

**Comment by mihaipopescu** [comment]
Well, nothing was done to remove Qt dialect so I'm not sure. It's up to you.
