### ISSUE TITLE
dependency of cpp.test is missing

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#972]
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"
If the file tests/cpp.test (i.e.) has changed then the next make command doesn't take care.
What is to modify at the CMakeLists.txt to get it?

**Comment by CDanU** [comment]
[CMakeLists.txt:258](https://github.com/uncrustify/uncrustify/blob/master/CMakeLists.txt#L248) calls [tests/CMakeLists.txt](https://github.com/uncrustify/uncrustify/blob/master/tests/CMakeLists.txt). There with every entry in the foreach loop
```cmake
foreach(test_lang c-sharp c cpp d java pawn objective-c vala ecma)
```
the according files are opened, every line is processed and added via the `add_uncrustify_test` function to ctest.
One problem that we still have is that the Regex that is processing the lines can't deal with tabs (see [here](https://github.com/uncrustify/uncrustify/issues/854#issuecomment-265780826)).

I do not think that cmake is keeping track of the state of the test files, like it would with actual source files, so you have to rerun cmake before make.

**Comment by gmaurel** [comment]
It is exactly what I don't want to have.
Do anybody have a solution for that?

**Comment by mihaipopescu** [comment]
I think in this case you just need to invalidate the cache which in cmake terms is deleting the `build` folder and recreate it.

**Comment by mihaipopescu** [comment]
This is another shortcoming of the new build system and as said elsewhere, one of the reasons why we still have `tests/run_tests.py` around.

**Comment by gmaurel** [comment]
Deleting the build directory works, yes, but it is not what I expected from Makefile.
Where to put the dependency?

**Comment by jibsen** [comment]
Perhaps something along the lines of:

~~~.diff
diff --git a/tests/CMakeLists.txt b/tests/CMakeLists.txt
index e63771e..bd7ac56 100644
--- a/tests/CMakeLists.txt
+++ b/tests/CMakeLists.txt
@@ -19,6 +19,7 @@ function(add_uncrustify_test name lang config rerun_config input result output)
 endfunction()
 
 foreach(test_lang c-sharp c cpp d java pawn objective-c vala ecma)
+  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${test_lang}.test")
   file(READ "${test_lang}.test" content)
   string(REPLACE "\n" ";" lines "${content}")
   foreach(line ${lines})
~~~

This should rerun CMake whenever one of the .test files changes.

**Comment by jibsen** [comment]
Oh, looks like that requires CMake 3.0+. There is a workaround [here](http://cmake.3232098.n2.nabble.com/Build-system-dependency-as-opposed-to-target-td7593692.html), which might work.

**Comment by gmaurel** [comment]
This is exactly what I wished to get!
Can you please make a new PR? Thanks.
