### ISSUE TITLE
OS X build - where's uncrustify.xcodeproj

### ISSUE THREAD

**Issue by jm4rc05** [uncrustify/uncrustify#975]
I'm trying to build the latest version and I can't find the project file for OS X!

**Comment by jibsen** [comment]
I am not familiar with macOS, but I think CMake should be able to generate Xcode project files. Perhaps something along the lines of:

~~~.bash
mkdir build
cd build
cmake -G Xcode ..
~~~

If that doesn't work, I am sure someone with more experience with that platform can help you further.

**Comment by jm4rc05** [comment]
Thanks.

I'm not familiar with cmake, but I'll do a try!
