### ISSUE TITLE
'unbreak' lines that would fit within one line

### ISSUE THREAD

**Issue by stleusc** [uncrustify/uncrustify#994]
assume max code width is set to 200
original file contains:
```c
for (i=0
, i<10
,i++
)
```

I want this to look like
```c
for (i=0 , i<10 ,i++)
```

any way to remove the newlines?

**Comment by CDanU** [comment]
Other than `nl_remove_extra_newlines > 0` there is currently no other option that removes the newlines in your case. I doubt though that that option will help you.

>nl_remove_extra_newlines: How aggressively to remove extra newlines not in preproc.
0: No change
1: Remove most newlines not handled by other config
2: Remove all newlines and reformat completely by config

**Comment by stleusc** [comment]
option 2 kinda does the trick, except that I now need to work on more options to get the code to like I it did before.
setting it to 2 forces all rules to be applied which is what I want.
I guess I play with 1 or 2 for now.

Thanks!
