### ISSUE TITLE
Github Topics

### ISSUE THREAD

**Issue by CDanU** [uncrustify/uncrustify#997]
Github recently introduced a keyword/tag search system: https://github.com/blog/2309-introducing-topics
Do we want to use it?

I would recommend the following _topics_:

- beautifier
- beautify
- code-style
- format
- formatter

Here is a search example for the topic: [formatter](https://github.com/search?utf8=%E2%9C%93&q=topic%3Aformatter&type=Repositories&ref=searchresults)

**Comment by gmaurel** [comment]
Done. Thanks for it.
