### ISSUE TITLE
sp_after_cast after fixing #889

### ISSUE THREAD

**Issue by chrullrich** [uncrustify/uncrustify#998]
After the fix to #889 went in (sorry, I must not have received an e-mail on the commit, or I would have mentioned this earlier), the behavior in that situation (spacing after cast of result of namespace-qualified function call) is now to always remove the space. Why does it still not follow the `sp_after_cast` setting?

I tried returning the option's value, rather than `AV_REMOVE`, and at first glance, it works as expected. Is there another corner case that gets broken by this?

**Comment by chrullrich** [comment]
I also marvel at the coincidence that allowed this question about #889 to be #998.

**Comment by gmaurel** [comment]
Bugfix with https://github.com/uncrustify/uncrustify/pull/895
