### ISSUE TITLE
equals sign aligned between template argument and template body

### ISSUE THREAD

**Issue by jlee975** [uncrustify/uncrustify#999]
These equals signs are aligned, but it doesn't seem like they should be.

```
template< class T, unsigned N = 0 >
constexpr unsigned long extent_v = extent< T, N >::value;
```

See align.cpp, align.cpp.uncrustify, align.debug in https://github.com/jlee975/uncrustify-tests

Using uncrustify v0.64_d 1f538888ad9b3adc8a46828ebe2ad6578629df29

**Comment by gmaurel** [comment]
Bug is fixed
